In [1]:
# wandbのライブラリをimport
import wandb

# wandbへログイン
wandb.login()

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter:wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /Users/hfukumor/.netrc
wandb: Currently logged in as: hideo-fukumori (hideo-fukumori-personal) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [2]:
# Pandasのライブラリをインポート
import pandas as pd

# 学習データを読み込んで変数 train に格納
train = pd.read_csv('./train.csv')

# 学習データの表示
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
# テストデータを読み込んで変数 test に格納
test = pd.read_csv('./test.csv')

# テストデータの表示
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [4]:
# 学習データとテストデータ数を確認
print(train.shape)
print(test.shape)

(891, 12)
(418, 11)

In [5]:
# trainの欠損値の数を調査して、表示する
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
# testの欠損値の数を調査して、表示する
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [7]:
# 新しい空のDataFrameを作成する
temp = pd.DataFrame()

# 学習データとテストデータのAge列を連結させ、tempにAge列として追加する
temp['Age'] = pd.concat([train['Age'], test['Age']])

# trainとtestのAge列について、欠損値をtempのAge列の平均値で埋める
train['Age'] = train['Age'].fillna(temp['Age'].mean())
test['Age'] = test['Age'].fillna(temp['Age'].mean())

In [8]:
# 学習データとテストデータのFare列を連結させ、tempにFare列として追加する
temp['Fare'] = pd.concat([train['Fare'], test['Fare']])

# testのみに存在するFare列の欠損値をtempのFare列の平均値で埋める
test['Fare'] = test['Fare'].fillna(temp['Fare'].mean())

In [9]:
# 学習データとテストデータのEmbarked列を連結させ、tempにEmbarked列として追加する
temp['Embarked'] = pd.concat([train['Embarked'], test['Embarked']])

# tempのEmbakedの値を集計する
temp['Embarked'].value_counts()

Embarked
S    914
C    270
Q    123
Name: count, dtype: int64

In [10]:
# trainのみに存在するEmbarked列の欠損値を'S'で埋める
train['Embarked'] = train['Embarked'].fillna('S')

In [11]:
# trainとtestから、Cabin,Name,Ticket列を削除する
train = train.drop(columns=['Cabin', 'Name', 'Ticket'])
test = test.drop(columns=['Cabin', 'Name', 'Ticket'])

In [12]:
# trainのSex列とEmbarked列をダミー変数化して、変数train2に格納する
train2 = pd.get_dummies(data=train, columns=['Sex', 'Embarked'])

# testのSex列とEmbarked列をダミー変数化して、変数test2に格納する
test2 = pd.get_dummies(data=test, columns=['Sex', 'Embarked'])

In [13]:
# train2の欠損値の数を調査して、表示する
train2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [14]:
# test2の欠損値の数を調査して、表示する
test2.isnull().sum()

PassengerId    0
Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Sex_female     0
Sex_male       0
Embarked_C     0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [15]:
# train2の各列の型を表示する
train2.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Sex_female        bool
Sex_male          bool
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [16]:
# numpyのimport
import numpy as np

# train2をX_trainとY_trainに分ける
X_train = np.array(train2.drop(columns=['Survived'])).astype('float32')
Y_train = np.array(train2['Survived']).astype('float32')

# test2のデータ全体をX_testに格納する
X_test = np.array(test2).astype('float32')

In [17]:
# X_trainとY_trainの3割をX_validとY_validに分割する
from sklearn.model_selection import train_test_split

X_train, X_valid, Y_train, Y_valid = train_test_split(X_train, Y_train, test_size=0.3, random_state=0)

In [18]:
# 学習データと検証データ、テストデータの形状を確認
print("X_train=", X_train.shape, ", Y_train=", Y_train.shape)
print("X_valid=", X_valid.shape, ", Y_valid=", Y_valid.shape)
print("X_test=", X_test.shape)

X_train= (623, 11) , Y_train= (623,)
X_valid= (268, 11) , Y_valid= (268,)
X_test= (418, 11)

In [18]:
# tensorflowのimport
import tensorflow as tf

In [19]:
# モデルの構築と学習を定義する関数
def train_model():
    # wandbの初期設定
    wandb.init(
        # wandbでのプロジェクト名
        project="kaggle-titanic",
        # wandbで記録してもらいたい設定値
        config={
            "input_dense_shape": 8,
            "hidden_dense_shape": 8,
            "optimizer": "rmsprop",
            "batch_size": 32
        })

    # モデルの初期化とレイヤー定義
    model = tf.keras.Sequential([
        # 入力層 (Inputオブジェクトを使用)
        tf.keras.Input(shape=(11,)),
        tf.keras.layers.Dense(wandb.config.input_dense_shape, activation='relu'),
        # 隠れ層
        tf.keras.layers.Dense(wandb.config.hidden_dense_shape, activation='relu'),
        # 出力層
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    # モデルの構築
    model.compile(optimizer=wandb.config.optimizer,
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    # 学習の実施
    log = model.fit(X_train, Y_train, epochs=5000, batch_size=wandb.config.batch_size, verbose=True,
                    callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss',
                                                                min_delta=0, patience=100,
                                                                verbose=1),
                              wandb.keras.WandbMetricsLogger(log_freq='epoch')
                              ],
                    validation_data=(X_valid, Y_valid))

In [20]:
# train_modelを実行する
train_model()

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4960 - loss: 2.4860 - val_accuracy: 0.6119 - val_loss: 1.0886
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 1.1773 - val_accuracy: 0.3694 - val_loss: 1.2425
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5538 - loss: 1.0205 - val_accuracy: 0.6493 - val_loss: 0.9088
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.8543 - val_accuracy: 0.6418 - val_loss: 0.8123
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.7665 - val_accuracy: 0.6679 - val_loss: 0.7013
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.7235 - val_accuracy: 0.6903 - val_loss: 0.6578
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6628 - val_accuracy: 0.6903 - val_loss: 0.6397
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6529 - val_accuracy: 0.6978 - val_loss: 0.6375
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6361 - val_accuracy: 0.4627 - val_loss: 0.7429
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6447 - val_accuracy: 0.6231 - val_loss: 0.6593
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6248 - val_accuracy: 0.6530 - val_loss: 0.7651
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6301 - val_accuracy: 0.7015 - val_loss: 0.5921
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6272 - val_accuracy: 0.6828 - val_loss: 0.6617
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6143 - val_accuracy: 0.7052 - val_loss: 0.5843
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6151 - val_accuracy: 0.7276 - val_loss: 0.6110
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6172 - val_accuracy: 0.7201 - val_loss: 0.5722
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6123 - val_accuracy: 0.7201 - val_loss: 0.5684
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.5961 - val_accuracy: 0.7090 - val_loss: 0.5816
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5888 - val_accuracy: 0.6940 - val_loss: 0.5967
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5927 - val_accuracy: 0.7201 - val_loss: 0.5621
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5981 - val_accuracy: 0.6716 - val_loss: 0.6344
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.5918 - val_accuracy: 0.4627 - val_loss: 0.8231
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6081 - val_accuracy: 0.7425 - val_loss: 0.5677
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.5872 - val_accuracy: 0.7239 - val_loss: 0.5983
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5853 - val_accuracy: 0.7948 - val_loss: 0.5893
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5911 - val_accuracy: 0.7873 - val_loss: 0.5859
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5620 - val_accuracy: 0.6940 - val_loss: 0.6128
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5777 - val_accuracy: 0.6418 - val_loss: 0.8623
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.5959 - val_accuracy: 0.7500 - val_loss: 0.5461
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5614 - val_accuracy: 0.7052 - val_loss: 0.6003
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5752 - val_accuracy: 0.7575 - val_loss: 0.5427
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5759 - val_accuracy: 0.7463 - val_loss: 0.5388
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5549 - val_accuracy: 0.7052 - val_loss: 0.5857
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5618 - val_accuracy: 0.7799 - val_loss: 0.5449
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5411 - val_accuracy: 0.7687 - val_loss: 0.5413
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5636 - val_accuracy: 0.7388 - val_loss: 0.5615
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5504 - val_accuracy: 0.7687 - val_loss: 0.5480
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5511 - val_accuracy: 0.7351 - val_loss: 0.5280
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5444 - val_accuracy: 0.7687 - val_loss: 0.5442
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5485 - val_accuracy: 0.7351 - val_loss: 0.5268
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5373 - val_accuracy: 0.7612 - val_loss: 0.5679
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5415 - val_accuracy: 0.7239 - val_loss: 0.5462
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5367 - val_accuracy: 0.7313 - val_loss: 0.5508
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5525 - val_accuracy: 0.7649 - val_loss: 0.5185
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5351 - val_accuracy: 0.5299 - val_loss: 0.6764
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5441 - val_accuracy: 0.7612 - val_loss: 0.5150
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5417 - val_accuracy: 0.7276 - val_loss: 0.5584
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5446 - val_accuracy: 0.7761 - val_loss: 0.5220
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5221 - val_accuracy: 0.6903 - val_loss: 0.6667
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5317 - val_accuracy: 0.6940 - val_loss: 0.6501
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5390 - val_accuracy: 0.7575 - val_loss: 0.5108
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5276 - val_accuracy: 0.7612 - val_loss: 0.5120
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5300 - val_accuracy: 0.6940 - val_loss: 0.6659
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5322 - val_accuracy: 0.7500 - val_loss: 0.5244
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5129 - val_accuracy: 0.7687 - val_loss: 0.5555
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5308 - val_accuracy: 0.7351 - val_loss: 0.5231
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5286 - val_accuracy: 0.7090 - val_loss: 0.6075
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5286 - val_accuracy: 0.7052 - val_loss: 0.6060
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5225 - val_accuracy: 0.7463 - val_loss: 0.5234
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5038 - val_accuracy: 0.7090 - val_loss: 0.5861
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5237 - val_accuracy: 0.7761 - val_loss: 0.5254
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5285 - val_accuracy: 0.7425 - val_loss: 0.5105
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5115 - val_accuracy: 0.7313 - val_loss: 0.5465
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5337 - val_accuracy: 0.7500 - val_loss: 0.5091
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5015 - val_accuracy: 0.7239 - val_loss: 0.5929
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5239 - val_accuracy: 0.7575 - val_loss: 0.4990
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5030 - val_accuracy: 0.7351 - val_loss: 0.5705
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5046 - val_accuracy: 0.7724 - val_loss: 0.5386
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4940 - val_accuracy: 0.7313 - val_loss: 0.5797
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5332 - val_accuracy: 0.7612 - val_loss: 0.5061
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5159 - val_accuracy: 0.7724 - val_loss: 0.5097
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4946 - val_accuracy: 0.7351 - val_loss: 0.5467
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5123 - val_accuracy: 0.7575 - val_loss: 0.5057
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4982 - val_accuracy: 0.7351 - val_loss: 0.5554
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5184 - val_accuracy: 0.7239 - val_loss: 0.5559
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5187 - val_accuracy: 0.7575 - val_loss: 0.4991
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5057 - val_accuracy: 0.7649 - val_loss: 0.5356
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4921 - val_accuracy: 0.7612 - val_loss: 0.4984
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5014 - val_accuracy: 0.7612 - val_loss: 0.4979
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5228 - val_accuracy: 0.7351 - val_loss: 0.5718
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5085 - val_accuracy: 0.7687 - val_loss: 0.5484
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4991 - val_accuracy: 0.7724 - val_loss: 0.4978
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4780 - val_accuracy: 0.7687 - val_loss: 0.5031
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5024 - val_accuracy: 0.7313 - val_loss: 0.5737
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5076 - val_accuracy: 0.7649 - val_loss: 0.5026
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4853 - val_accuracy: 0.7463 - val_loss: 0.5436
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4905 - val_accuracy: 0.7724 - val_loss: 0.5148
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4862 - val_accuracy: 0.7351 - val_loss: 0.5697
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4941 - val_accuracy: 0.7761 - val_loss: 0.5000
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5261 - val_accuracy: 0.7239 - val_loss: 0.5959
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4824 - val_accuracy: 0.7164 - val_loss: 0.6149
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5010 - val_accuracy: 0.5261 - val_loss: 0.7115
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4954 - val_accuracy: 0.7649 - val_loss: 0.4969
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4919 - val_accuracy: 0.7425 - val_loss: 0.5621
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4803 - val_accuracy: 0.7500 - val_loss: 0.5232
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5166 - val_accuracy: 0.7612 - val_loss: 0.5031
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4881 - val_accuracy: 0.7649 - val_loss: 0.5103
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4961 - val_accuracy: 0.7500 - val_loss: 0.5825
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4936 - val_accuracy: 0.7687 - val_loss: 0.5361
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4964 - val_accuracy: 0.7537 - val_loss: 0.5401
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4900 - val_accuracy: 0.7500 - val_loss: 0.5793
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4948 - val_accuracy: 0.7873 - val_loss: 0.5168
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4723 - val_accuracy: 0.7799 - val_loss: 0.5043
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4940 - val_accuracy: 0.6381 - val_loss: 0.6615
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4746 - val_accuracy: 0.7687 - val_loss: 0.4933
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5123 - val_accuracy: 0.7649 - val_loss: 0.4968
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4844 - val_accuracy: 0.7276 - val_loss: 0.6218
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4754 - val_accuracy: 0.7687 - val_loss: 0.4920
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4870 - val_accuracy: 0.7537 - val_loss: 0.5193
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4856 - val_accuracy: 0.7612 - val_loss: 0.5168
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4864 - val_accuracy: 0.7500 - val_loss: 0.5327
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4957 - val_accuracy: 0.7724 - val_loss: 0.5019
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4981 - val_accuracy: 0.7463 - val_loss: 0.5638
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4713 - val_accuracy: 0.6231 - val_loss: 0.6499
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5071 - val_accuracy: 0.7276 - val_loss: 0.6149
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4950 - val_accuracy: 0.7537 - val_loss: 0.5484
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4813 - val_accuracy: 0.7500 - val_loss: 0.5672
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5063 - val_accuracy: 0.7649 - val_loss: 0.4961
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4908 - val_accuracy: 0.7612 - val_loss: 0.5040
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5065 - val_accuracy: 0.7761 - val_loss: 0.5005
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4867 - val_accuracy: 0.7687 - val_loss: 0.5126
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4764 - val_accuracy: 0.7127 - val_loss: 0.6592
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4927 - val_accuracy: 0.7575 - val_loss: 0.5269
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4844 - val_accuracy: 0.7388 - val_loss: 0.5840
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4971 - val_accuracy: 0.7612 - val_loss: 0.5681
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4780 - val_accuracy: 0.7761 - val_loss: 0.5387
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4845 - val_accuracy: 0.7575 - val_loss: 0.4949
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4776 - val_accuracy: 0.7537 - val_loss: 0.5521
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5011 - val_accuracy: 0.7649 - val_loss: 0.5164
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4780 - val_accuracy: 0.7724 - val_loss: 0.4920
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4916 - val_accuracy: 0.7761 - val_loss: 0.4941
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4904 - val_accuracy: 0.7724 - val_loss: 0.5453
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4957 - val_accuracy: 0.7724 - val_loss: 0.5112
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4715 - val_accuracy: 0.7649 - val_loss: 0.4952
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4716 - val_accuracy: 0.7388 - val_loss: 0.6072
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4993 - val_accuracy: 0.7687 - val_loss: 0.5002
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4938 - val_accuracy: 0.7164 - val_loss: 0.6333
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4819 - val_accuracy: 0.7612 - val_loss: 0.4979
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4835 - val_accuracy: 0.7724 - val_loss: 0.5081
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4907 - val_accuracy: 0.7537 - val_loss: 0.5688
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5029 - val_accuracy: 0.7724 - val_loss: 0.4933
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4698 - val_accuracy: 0.6940 - val_loss: 0.7772
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4903 - val_accuracy: 0.7836 - val_loss: 0.5034
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4821 - val_accuracy: 0.7799 - val_loss: 0.5200
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4734 - val_accuracy: 0.7575 - val_loss: 0.5686
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4947 - val_accuracy: 0.7612 - val_loss: 0.4952
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4857 - val_accuracy: 0.7687 - val_loss: 0.4897
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4911 - val_accuracy: 0.7649 - val_loss: 0.5201
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4820 - val_accuracy: 0.7537 - val_loss: 0.5795
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4677 - val_accuracy: 0.7612 - val_loss: 0.4959
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4800 - val_accuracy: 0.7351 - val_loss: 0.5622
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4732 - val_accuracy: 0.7649 - val_loss: 0.4857
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5057 - val_accuracy: 0.7761 - val_loss: 0.4882
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4810 - val_accuracy: 0.7724 - val_loss: 0.4916
Epoch 155/5000

In [21]:
# wandbの動作を終了させる
wandb.finish()

In [22]:
# wandbでsweep（グリッドサーチ）を行なうための設定
sweep_config = {
    'method': 'grid',
    'name': 'kaggle-titanic-sweep',
    'metric': {
        'goal': 'maximize',
        'name': 'accuracy'
    },
    'parameters': {
        'input_dense_shape': {'values': [8, 16, 24]},
        'hidden_dense_shape': {'values': [8, 16, 24]},
        'optimizer': {'values': ['sgd', 'rmsprop', 'adam']},
        'batch_size': {'values': [16, 32, 64]}
     }
}

# sweep_configの設定値でsweepを初期化する
sweep_id = wandb.sweep(sweep=sweep_config, project="kaggle-titanic")

Create sweep with ID: qrl8sn1z
Sweep URL: https://wandb.ai/hideo-fukumori-personal/kaggle-titanic/sweeps/qrl8sn1z

In [23]:
# sweepを開始する
wandb.agent(sweep_id, function=train_model)

wandb: Agent Starting Run: 8kbq0yf4 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 2.5478 - val_accuracy: 0.6269 - val_loss: 0.6898
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6869 - val_accuracy: 0.6269 - val_loss: 0.6855
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6116 - loss: 0.6835 - val_accuracy: 0.6269 - val_loss: 0.6819
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6116 - loss: 0.6808 - val_accuracy: 0.6269 - val_loss: 0.6790
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6116 - loss: 0.6785 - val_accuracy: 0.6269 - val_loss: 0.6765
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6116 - loss: 0.6767 - val_accuracy: 0.6269 - val_loss: 0.6744
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6116 - loss: 0.6751 - val_accuracy: 0.6269 - val_loss: 0.6726
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6116 - loss: 0.6739 - val_accuracy: 0.6269 - val_loss: 0.6712
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6116 - loss: 0.6728 - val_accuracy: 0.6269 - val_loss: 0.6699
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.6116 - loss: 0.6720 - val_accuracy: 0.6269 - val_loss: 0.6688
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6116 - loss: 0.6712 - val_accuracy: 0.6269 - val_loss: 0.6678
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6116 - loss: 0.6707 - val_accuracy: 0.6269 - val_loss: 0.6671
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6116 - loss: 0.6702 - val_accuracy: 0.6269 - val_loss: 0.6665
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6116 - loss: 0.6698 - val_accuracy: 0.6269 - val_loss: 0.6660
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6116 - loss: 0.6694 - val_accuracy: 0.6269 - val_loss: 0.6654
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6691 - val_accuracy: 0.6269 - val_loss: 0.6651
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6689 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6644
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6642
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6640
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6638
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6636
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6635
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6633
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6116 - loss: 0.6680 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6116 - loss: 0.6680 - val_accuracy: 0.6269 - val_loss: 0.6631
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6116 - loss: 0.6680 - val_accuracy: 0.6269 - val_loss: 0.6631
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6116 - loss: 0.6680 - val_accuracy: 0.6269 - val_loss: 0.6630
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6629
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6629
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6116 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6116 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 153/5000

wandb: Agent Starting Run: x6hhmys5 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 2.5139 - val_accuracy: 0.6828 - val_loss: 1.4203
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 1.1384 - val_accuracy: 0.6791 - val_loss: 0.9473
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.9354 - val_accuracy: 0.6381 - val_loss: 0.8572
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.5955 - loss: 0.9151 - val_accuracy: 0.5336 - val_loss: 1.0308
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6212 - loss: 0.7887 - val_accuracy: 0.7090 - val_loss: 0.7183
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6035 - loss: 0.8473 - val_accuracy: 0.6306 - val_loss: 0.9201
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.5939 - loss: 0.7978 - val_accuracy: 0.4478 - val_loss: 1.2525
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.6196 - loss: 0.7954 - val_accuracy: 0.6679 - val_loss: 0.6873
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6180 - loss: 0.7717 - val_accuracy: 0.7201 - val_loss: 0.6606
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6276 - loss: 0.7507 - val_accuracy: 0.6381 - val_loss: 1.0233
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6196 - loss: 0.7505 - val_accuracy: 0.7015 - val_loss: 0.6435
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.7339 - val_accuracy: 0.6716 - val_loss: 0.7761
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6404 - loss: 0.7319 - val_accuracy: 0.6754 - val_loss: 0.6519
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6581 - loss: 0.6904 - val_accuracy: 0.6791 - val_loss: 0.7348
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7225 - val_accuracy: 0.6791 - val_loss: 0.6451
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6693 - loss: 0.6872 - val_accuracy: 0.4627 - val_loss: 1.1946
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6774 - loss: 0.6889 - val_accuracy: 0.6866 - val_loss: 0.6822
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6952 - val_accuracy: 0.7201 - val_loss: 0.6022
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6597 - loss: 0.7017 - val_accuracy: 0.6530 - val_loss: 0.9350
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6714 - val_accuracy: 0.6642 - val_loss: 0.6991
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6806 - loss: 0.6736 - val_accuracy: 0.7276 - val_loss: 0.5890
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6822 - loss: 0.6517 - val_accuracy: 0.7463 - val_loss: 0.5793
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6432 - val_accuracy: 0.7537 - val_loss: 0.5844
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6982 - loss: 0.6967 - val_accuracy: 0.7649 - val_loss: 0.5830
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6645 - loss: 0.6790 - val_accuracy: 0.7649 - val_loss: 0.5753
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6934 - loss: 0.6247 - val_accuracy: 0.6567 - val_loss: 0.9760
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6902 - loss: 0.6402 - val_accuracy: 0.7127 - val_loss: 0.6387
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6902 - loss: 0.6583 - val_accuracy: 0.7612 - val_loss: 0.5618
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6918 - loss: 0.6462 - val_accuracy: 0.7313 - val_loss: 0.5959
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7127 - loss: 0.6548 - val_accuracy: 0.7239 - val_loss: 0.6070
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7191 - loss: 0.6126 - val_accuracy: 0.7575 - val_loss: 0.5527
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7175 - loss: 0.5941 - val_accuracy: 0.4664 - val_loss: 1.4107
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7143 - loss: 0.6258 - val_accuracy: 0.6791 - val_loss: 0.7672
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7239 - loss: 0.6215 - val_accuracy: 0.7164 - val_loss: 0.6376
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7175 - loss: 0.6364 - val_accuracy: 0.6007 - val_loss: 0.7813
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6854 - loss: 0.6317 - val_accuracy: 0.7463 - val_loss: 0.5829
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7047 - loss: 0.6179 - val_accuracy: 0.7537 - val_loss: 0.5731
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5823 - val_accuracy: 0.7649 - val_loss: 0.5394
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7207 - loss: 0.5928 - val_accuracy: 0.7761 - val_loss: 0.5955
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7095 - loss: 0.6157 - val_accuracy: 0.7052 - val_loss: 0.6991
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7063 - loss: 0.6390 - val_accuracy: 0.7761 - val_loss: 0.5552
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7416 - loss: 0.5634 - val_accuracy: 0.6828 - val_loss: 0.6943
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7127 - loss: 0.6439 - val_accuracy: 0.7649 - val_loss: 0.5361
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7448 - loss: 0.5843 - val_accuracy: 0.5410 - val_loss: 0.8966
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7335 - loss: 0.5988 - val_accuracy: 0.7799 - val_loss: 0.5486
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7464 - loss: 0.5756 - val_accuracy: 0.7052 - val_loss: 0.7220
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7464 - loss: 0.5887 - val_accuracy: 0.4925 - val_loss: 1.1749
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7239 - loss: 0.5979 - val_accuracy: 0.7836 - val_loss: 0.5522
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7303 - loss: 0.5980 - val_accuracy: 0.7575 - val_loss: 0.5226
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7303 - loss: 0.5897 - val_accuracy: 0.7201 - val_loss: 0.6925
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7544 - loss: 0.5448 - val_accuracy: 0.7612 - val_loss: 0.5275
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7303 - loss: 0.6177 - val_accuracy: 0.7761 - val_loss: 0.5215
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7512 - loss: 0.5593 - val_accuracy: 0.7425 - val_loss: 0.5818
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7416 - loss: 0.5589 - val_accuracy: 0.4963 - val_loss: 1.1567
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7111 - loss: 0.6496 - val_accuracy: 0.7836 - val_loss: 0.5251
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7689 - loss: 0.5454 - val_accuracy: 0.6679 - val_loss: 0.8952
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7592 - loss: 0.5528 - val_accuracy: 0.7873 - val_loss: 0.5833
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7496 - loss: 0.5849 - val_accuracy: 0.7612 - val_loss: 0.5129
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7400 - loss: 0.5709 - val_accuracy: 0.7500 - val_loss: 0.5732
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7624 - loss: 0.5846 - val_accuracy: 0.7276 - val_loss: 0.6290
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7785 - loss: 0.5570 - val_accuracy: 0.7425 - val_loss: 0.6195
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7464 - loss: 0.5747 - val_accuracy: 0.6642 - val_loss: 0.8520
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7560 - loss: 0.5907 - val_accuracy: 0.7388 - val_loss: 0.5819
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7528 - loss: 0.5793 - val_accuracy: 0.7873 - val_loss: 0.5424
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7640 - loss: 0.5556 - val_accuracy: 0.7836 - val_loss: 0.5331
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7576 - loss: 0.5581 - val_accuracy: 0.7649 - val_loss: 0.5214
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7673 - loss: 0.5347 - val_accuracy: 0.7500 - val_loss: 0.5816
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7480 - loss: 0.5457 - val_accuracy: 0.6828 - val_loss: 0.7045
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5815 - val_accuracy: 0.7649 - val_loss: 0.5285
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7865 - loss: 0.5117 - val_accuracy: 0.7761 - val_loss: 0.5756
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7592 - loss: 0.5466 - val_accuracy: 0.7276 - val_loss: 0.6745
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7640 - loss: 0.5784 - val_accuracy: 0.7836 - val_loss: 0.5450
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7608 - loss: 0.5465 - val_accuracy: 0.7687 - val_loss: 0.5193
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7849 - loss: 0.5434 - val_accuracy: 0.7649 - val_loss: 0.5205
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7769 - loss: 0.5119 - val_accuracy: 0.6194 - val_loss: 0.7741
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7544 - loss: 0.6013 - val_accuracy: 0.7873 - val_loss: 0.5449
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7640 - loss: 0.5438 - val_accuracy: 0.7873 - val_loss: 0.5467
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7512 - loss: 0.5634 - val_accuracy: 0.7612 - val_loss: 0.5769
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7560 - loss: 0.5442 - val_accuracy: 0.7388 - val_loss: 0.6473
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7496 - loss: 0.5480 - val_accuracy: 0.7687 - val_loss: 0.5564
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7608 - loss: 0.5608 - val_accuracy: 0.7761 - val_loss: 0.5474
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7624 - loss: 0.5492 - val_accuracy: 0.7575 - val_loss: 0.5670
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7496 - loss: 0.5346 - val_accuracy: 0.7799 - val_loss: 0.5387
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7608 - loss: 0.5675 - val_accuracy: 0.6791 - val_loss: 0.7051
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.7881 - loss: 0.5330 - val_accuracy: 0.7687 - val_loss: 0.5197
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7608 - loss: 0.5464 - val_accuracy: 0.7612 - val_loss: 0.5819
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7640 - loss: 0.5392 - val_accuracy: 0.7799 - val_loss: 0.5815
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7833 - loss: 0.5370 - val_accuracy: 0.5112 - val_loss: 1.0664
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7496 - loss: 0.5864 - val_accuracy: 0.7761 - val_loss: 0.5597
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5432 - val_accuracy: 0.7836 - val_loss: 0.6126
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7769 - loss: 0.5526 - val_accuracy: 0.7799 - val_loss: 0.6151
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7480 - loss: 0.5841 - val_accuracy: 0.7836 - val_loss: 0.5820
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7512 - loss: 0.5265 - val_accuracy: 0.7649 - val_loss: 0.5233
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7368 - loss: 0.5631 - val_accuracy: 0.5821 - val_loss: 0.8770
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7673 - loss: 0.5301 - val_accuracy: 0.5821 - val_loss: 0.8858
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7528 - loss: 0.5502 - val_accuracy: 0.5970 - val_loss: 0.8477
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7673 - loss: 0.5378 - val_accuracy: 0.7575 - val_loss: 0.5948
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7448 - loss: 0.6051 - val_accuracy: 0.7724 - val_loss: 0.5435
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7640 - loss: 0.5440 - val_accuracy: 0.7090 - val_loss: 0.7977
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7705 - loss: 0.5374 - val_accuracy: 0.7500 - val_loss: 0.6663
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7689 - loss: 0.5548 - val_accuracy: 0.7425 - val_loss: 0.6341
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7640 - loss: 0.5806 - val_accuracy: 0.7761 - val_loss: 0.5444
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7785 - loss: 0.5595 - val_accuracy: 0.7687 - val_loss: 0.5409
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7705 - loss: 0.5110 - val_accuracy: 0.7537 - val_loss: 0.5948
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7833 - loss: 0.5168 - val_accuracy: 0.7575 - val_loss: 0.5371
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7673 - loss: 0.5557 - val_accuracy: 0.7425 - val_loss: 0.6768
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7721 - loss: 0.5334 - val_accuracy: 0.7687 - val_loss: 0.5529
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7865 - loss: 0.5671 - val_accuracy: 0.7575 - val_loss: 0.5936
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5057 - val_accuracy: 0.7687 - val_loss: 0.5461
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7432 - loss: 0.5898 - val_accuracy: 0.7575 - val_loss: 0.5422
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7785 - loss: 0.5041 - val_accuracy: 0.7500 - val_loss: 0.6363
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7657 - loss: 0.5606 - val_accuracy: 0.7724 - val_loss: 0.6519
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7673 - loss: 0.5307 - val_accuracy: 0.7090 - val_loss: 0.7667
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7737 - loss: 0.5306 - val_accuracy: 0.7575 - val_loss: 0.6015
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7833 - loss: 0.5293 - val_accuracy: 0.7687 - val_loss: 0.5819
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7865 - loss: 0.5022 - val_accuracy: 0.7575 - val_loss: 0.5475
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7608 - loss: 0.5367 - val_accuracy: 0.7612 - val_loss: 0.5958
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7753 - loss: 0.5269 - val_accuracy: 0.7313 - val_loss: 0.6951
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7721 - loss: 0.5440 - val_accuracy: 0.7612 - val_loss: 0.6103
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7753 - loss: 0.5413 - val_accuracy: 0.7687 - val_loss: 0.5478
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7865 - loss: 0.5277 - val_accuracy: 0.7612 - val_loss: 0.5511
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7721 - loss: 0.5398 - val_accuracy: 0.7649 - val_loss: 0.6837
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7737 - loss: 0.5157 - val_accuracy: 0.7537 - val_loss: 0.5464
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7657 - loss: 0.5407 - val_accuracy: 0.7351 - val_loss: 0.6973
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7528 - loss: 0.5404 - val_accuracy: 0.7351 - val_loss: 0.7219
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7673 - loss: 0.5356 - val_accuracy: 0.7761 - val_loss: 0.5504
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5536 - val_accuracy: 0.7537 - val_loss: 0.6051
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7897 - loss: 0.4952 - val_accuracy: 0.7015 - val_loss: 0.7945
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7978 - loss: 0.5297 - val_accuracy: 0.7164 - val_loss: 0.8238
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7721 - loss: 0.5477 - val_accuracy: 0.7127 - val_loss: 0.7829
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7753 - loss: 0.5396 - val_accuracy: 0.7761 - val_loss: 0.5538
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7897 - loss: 0.5516 - val_accuracy: 0.7687 - val_loss: 0.5545
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7608 - loss: 0.5416 - val_accuracy: 0.7761 - val_loss: 0.5863
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7929 - loss: 0.5218 - val_accuracy: 0.7276 - val_loss: 0.7589
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7753 - loss: 0.5292 - val_accuracy: 0.7687 - val_loss: 0.5589
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7769 - loss: 0.5250 - val_accuracy: 0.7052 - val_loss: 0.8162
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7849 - loss: 0.5338 - val_accuracy: 0.6642 - val_loss: 0.7791
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7881 - loss: 0.5006 - val_accuracy: 0.7724 - val_loss: 0.5694
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7753 - loss: 0.5348 - val_accuracy: 0.7649 - val_loss: 0.5537
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7945 - loss: 0.4959 - val_accuracy: 0.7313 - val_loss: 0.7556
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7673 - loss: 0.5625 - val_accuracy: 0.7463 - val_loss: 0.6663
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7833 - loss: 0.5288 - val_accuracy: 0.7724 - val_loss: 0.5785
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7721 - loss: 0.5506 - val_accuracy: 0.7649 - val_loss: 0.5657
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5260 - val_accuracy: 0.7761 - val_loss: 0.5782
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7544 - loss: 0.5772 - val_accuracy: 0.7649 - val_loss: 0.5627
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7881 - loss: 0.4953 - val_accuracy: 0.7649 - val_loss: 0.5664
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7785 - loss: 0.5293 - val_accuracy: 0.7351 - val_loss: 0.7112
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7640 - loss: 0.5367 - val_accuracy: 0.7799 - val_loss: 0.5897
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7705 - loss: 0.5319 - val_accuracy: 0.6455 - val_loss: 0.8059
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7849 - loss: 0.5125 - val_accuracy: 0.7239 - val_loss: 0.7899
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7496 - loss: 0.5520 - val_accuracy: 0.7612 - val_loss: 0.5619
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7994 - loss: 0.4972 - val_accuracy: 0.7612 - val_loss: 0.5614
Epoch 153/5000

wandb: Agent Starting Run: cp2rkfla with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 35.4682 - val_accuracy: 0.3731 - val_loss: 13.2831
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4575 - loss: 5.2684 - val_accuracy: 0.4552 - val_loss: 3.9757
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4671 - loss: 3.5196 - val_accuracy: 0.4664 - val_loss: 3.5074
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.4767 - loss: 3.1253 - val_accuracy: 0.5000 - val_loss: 3.0831
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4719 - loss: 2.7643 - val_accuracy: 0.4664 - val_loss: 2.7844
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.4848 - loss: 2.5506 - val_accuracy: 0.5112 - val_loss: 2.3959
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.4928 - loss: 2.2215 - val_accuracy: 0.4888 - val_loss: 2.0761
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4880 - loss: 1.9812 - val_accuracy: 0.4627 - val_loss: 1.8664
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.4992 - loss: 1.7219 - val_accuracy: 0.5149 - val_loss: 1.5425
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.4880 - loss: 1.5276 - val_accuracy: 0.5522 - val_loss: 1.3779
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.5072 - loss: 1.3581 - val_accuracy: 0.5373 - val_loss: 1.1002
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.5217 - loss: 1.0863 - val_accuracy: 0.5485 - val_loss: 0.9331
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.5474 - loss: 0.9847 - val_accuracy: 0.5784 - val_loss: 0.7815
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.5891 - loss: 0.8243 - val_accuracy: 0.6381 - val_loss: 0.7179
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.5923 - loss: 0.8204 - val_accuracy: 0.6567 - val_loss: 0.7358
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6645 - loss: 0.7532 - val_accuracy: 0.7164 - val_loss: 0.5706
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6806 - loss: 0.6941 - val_accuracy: 0.7052 - val_loss: 0.5482
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.6763 - val_accuracy: 0.6903 - val_loss: 0.5501
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.6529 - val_accuracy: 0.6940 - val_loss: 0.5343
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.6806 - loss: 0.6540 - val_accuracy: 0.6940 - val_loss: 0.5481
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6982 - loss: 0.6478 - val_accuracy: 0.7537 - val_loss: 0.5168
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.6950 - loss: 0.6409 - val_accuracy: 0.7687 - val_loss: 0.5516
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7095 - loss: 0.6090 - val_accuracy: 0.7201 - val_loss: 0.5081
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6966 - loss: 0.6104 - val_accuracy: 0.6978 - val_loss: 0.5598
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.7111 - loss: 0.6249 - val_accuracy: 0.6828 - val_loss: 0.6214
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6934 - loss: 0.6266 - val_accuracy: 0.7127 - val_loss: 0.5127
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7143 - loss: 0.5837 - val_accuracy: 0.7948 - val_loss: 0.5466
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7175 - loss: 0.5707 - val_accuracy: 0.7201 - val_loss: 0.5182
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7287 - loss: 0.5734 - val_accuracy: 0.7575 - val_loss: 0.4948
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7271 - loss: 0.5771 - val_accuracy: 0.7090 - val_loss: 0.5315
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6854 - loss: 0.5941 - val_accuracy: 0.7201 - val_loss: 0.5113
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7111 - loss: 0.5772 - val_accuracy: 0.6978 - val_loss: 0.6147
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5674 - val_accuracy: 0.7313 - val_loss: 0.4988
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7303 - loss: 0.5676 - val_accuracy: 0.7836 - val_loss: 0.5462
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7111 - loss: 0.5508 - val_accuracy: 0.7649 - val_loss: 0.4937
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7223 - loss: 0.5347 - val_accuracy: 0.7276 - val_loss: 0.5024
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7255 - loss: 0.5582 - val_accuracy: 0.7388 - val_loss: 0.4958
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7352 - loss: 0.5486 - val_accuracy: 0.7649 - val_loss: 0.5152
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7143 - loss: 0.5624 - val_accuracy: 0.6866 - val_loss: 0.6009
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7464 - loss: 0.5508 - val_accuracy: 0.7761 - val_loss: 0.5252
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7303 - loss: 0.5451 - val_accuracy: 0.7687 - val_loss: 0.4891
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7448 - loss: 0.5400 - val_accuracy: 0.7687 - val_loss: 0.5355
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7400 - loss: 0.5421 - val_accuracy: 0.7687 - val_loss: 0.4863
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7560 - loss: 0.5325 - val_accuracy: 0.7612 - val_loss: 0.4894
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7480 - loss: 0.5364 - val_accuracy: 0.7649 - val_loss: 0.4910
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7480 - loss: 0.5389 - val_accuracy: 0.7575 - val_loss: 0.4941
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7496 - loss: 0.5279 - val_accuracy: 0.7537 - val_loss: 0.4937
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7576 - loss: 0.5163 - val_accuracy: 0.7388 - val_loss: 0.4974
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.7255 - loss: 0.5696 - val_accuracy: 0.7425 - val_loss: 0.5002
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7255 - loss: 0.6050 - val_accuracy: 0.7612 - val_loss: 0.4849
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7560 - loss: 0.5185 - val_accuracy: 0.7500 - val_loss: 0.4883
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7673 - loss: 0.5121 - val_accuracy: 0.7612 - val_loss: 0.4829
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7624 - loss: 0.5287 - val_accuracy: 0.7649 - val_loss: 0.4983
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7432 - loss: 0.5453 - val_accuracy: 0.7612 - val_loss: 0.4810
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.7544 - loss: 0.5319 - val_accuracy: 0.7575 - val_loss: 0.4824
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7368 - loss: 0.5597 - val_accuracy: 0.7052 - val_loss: 0.6014
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6950 - loss: 0.6192 - val_accuracy: 0.7649 - val_loss: 0.4942
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7352 - loss: 0.5491 - val_accuracy: 0.7612 - val_loss: 0.4803
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7448 - loss: 0.5363 - val_accuracy: 0.7239 - val_loss: 0.5240
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7528 - loss: 0.5527 - val_accuracy: 0.7500 - val_loss: 0.4860
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7753 - loss: 0.5171 - val_accuracy: 0.7090 - val_loss: 0.5829
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7592 - loss: 0.5231 - val_accuracy: 0.7463 - val_loss: 0.5083
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7657 - loss: 0.4955 - val_accuracy: 0.7313 - val_loss: 0.5144
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7817 - loss: 0.5010 - val_accuracy: 0.7649 - val_loss: 0.5215
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7705 - loss: 0.5080 - val_accuracy: 0.7612 - val_loss: 0.5023
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7560 - loss: 0.5138 - val_accuracy: 0.7425 - val_loss: 0.5046
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7624 - loss: 0.5026 - val_accuracy: 0.7388 - val_loss: 0.5002
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7640 - loss: 0.5100 - val_accuracy: 0.7425 - val_loss: 0.5027
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7576 - loss: 0.5194 - val_accuracy: 0.7351 - val_loss: 0.5022
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7464 - loss: 0.5361 - val_accuracy: 0.7575 - val_loss: 0.5376
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7640 - loss: 0.5060 - val_accuracy: 0.7500 - val_loss: 0.4980
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7721 - loss: 0.4988 - val_accuracy: 0.7500 - val_loss: 0.4889
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7673 - loss: 0.5111 - val_accuracy: 0.7500 - val_loss: 0.4919
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7640 - loss: 0.5176 - val_accuracy: 0.7351 - val_loss: 0.5020
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5136 - val_accuracy: 0.7463 - val_loss: 0.4905
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7785 - loss: 0.4947 - val_accuracy: 0.7500 - val_loss: 0.4803
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7560 - loss: 0.5246 - val_accuracy: 0.7388 - val_loss: 0.4857
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7448 - loss: 0.5683 - val_accuracy: 0.7537 - val_loss: 0.4818
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7721 - loss: 0.5083 - val_accuracy: 0.7463 - val_loss: 0.4918
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7640 - loss: 0.5002 - val_accuracy: 0.7575 - val_loss: 0.4919
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7287 - loss: 0.5549 - val_accuracy: 0.7239 - val_loss: 0.5637
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7496 - loss: 0.5225 - val_accuracy: 0.7500 - val_loss: 0.4792
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7544 - loss: 0.5126 - val_accuracy: 0.7575 - val_loss: 0.5421
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7255 - loss: 0.5503 - val_accuracy: 0.7090 - val_loss: 0.5917
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7239 - loss: 0.5687 - val_accuracy: 0.7164 - val_loss: 0.5974
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7303 - loss: 0.5493 - val_accuracy: 0.7351 - val_loss: 0.4842
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7576 - loss: 0.5228 - val_accuracy: 0.7575 - val_loss: 0.4784
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7576 - loss: 0.5106 - val_accuracy: 0.7500 - val_loss: 0.4924
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7592 - loss: 0.5253 - val_accuracy: 0.7500 - val_loss: 0.4779
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7560 - loss: 0.5100 - val_accuracy: 0.7127 - val_loss: 0.5593
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7721 - loss: 0.4983 - val_accuracy: 0.7388 - val_loss: 0.4849
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7657 - loss: 0.5055 - val_accuracy: 0.7537 - val_loss: 0.5196
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7657 - loss: 0.4864 - val_accuracy: 0.7575 - val_loss: 0.5285
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7689 - loss: 0.4946 - val_accuracy: 0.7425 - val_loss: 0.4805
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7833 - loss: 0.4836 - val_accuracy: 0.7463 - val_loss: 0.4962
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4855 - val_accuracy: 0.7463 - val_loss: 0.4822
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7657 - loss: 0.4972 - val_accuracy: 0.7388 - val_loss: 0.4879
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7496 - loss: 0.5331 - val_accuracy: 0.7575 - val_loss: 0.5214
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7673 - loss: 0.4929 - val_accuracy: 0.7537 - val_loss: 0.4876
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7608 - loss: 0.5142 - val_accuracy: 0.7537 - val_loss: 0.4940
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7544 - loss: 0.5132 - val_accuracy: 0.7463 - val_loss: 0.4809
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7785 - loss: 0.4900 - val_accuracy: 0.7612 - val_loss: 0.5089
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7673 - loss: 0.5120 - val_accuracy: 0.7575 - val_loss: 0.5125
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7480 - loss: 0.5323 - val_accuracy: 0.7537 - val_loss: 0.4926
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7640 - loss: 0.5075 - val_accuracy: 0.7537 - val_loss: 0.5748
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7512 - loss: 0.5534 - val_accuracy: 0.7463 - val_loss: 0.4814
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7785 - loss: 0.4850 - val_accuracy: 0.7463 - val_loss: 0.4783
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7753 - loss: 0.4814 - val_accuracy: 0.7500 - val_loss: 0.4771
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7496 - loss: 0.5388 - val_accuracy: 0.7015 - val_loss: 0.5775
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7640 - loss: 0.5285 - val_accuracy: 0.7463 - val_loss: 0.4948
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7544 - loss: 0.5638 - val_accuracy: 0.7500 - val_loss: 0.4786
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7608 - loss: 0.5309 - val_accuracy: 0.7425 - val_loss: 0.4842
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7705 - loss: 0.4904 - val_accuracy: 0.7425 - val_loss: 0.5010
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7528 - loss: 0.5078 - val_accuracy: 0.7463 - val_loss: 0.4906
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4868 - val_accuracy: 0.6903 - val_loss: 0.6150
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7640 - loss: 0.5078 - val_accuracy: 0.7463 - val_loss: 0.4769
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7608 - loss: 0.5250 - val_accuracy: 0.7463 - val_loss: 0.4971
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7689 - loss: 0.5079 - val_accuracy: 0.7537 - val_loss: 0.5261
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7737 - loss: 0.4950 - val_accuracy: 0.7164 - val_loss: 0.5311
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7753 - loss: 0.5234 - val_accuracy: 0.7425 - val_loss: 0.4821
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7640 - loss: 0.5116 - val_accuracy: 0.7500 - val_loss: 0.5033
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7753 - loss: 0.4895 - val_accuracy: 0.7463 - val_loss: 0.4838
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7705 - loss: 0.5058 - val_accuracy: 0.7500 - val_loss: 0.4989
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7480 - loss: 0.5287 - val_accuracy: 0.6455 - val_loss: 0.6666
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7640 - loss: 0.5139 - val_accuracy: 0.7463 - val_loss: 0.4772
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7753 - loss: 0.4870 - val_accuracy: 0.7575 - val_loss: 0.5022
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7528 - loss: 0.5247 - val_accuracy: 0.7537 - val_loss: 0.4840
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7528 - loss: 0.5241 - val_accuracy: 0.7575 - val_loss: 0.5204
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7705 - loss: 0.5058 - val_accuracy: 0.7313 - val_loss: 0.5181
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7817 - loss: 0.4904 - val_accuracy: 0.7612 - val_loss: 0.5539
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7721 - loss: 0.5359 - val_accuracy: 0.7388 - val_loss: 0.4862
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4868 - val_accuracy: 0.7500 - val_loss: 0.4783
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7416 - loss: 0.5556 - val_accuracy: 0.5746 - val_loss: 0.7924
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7560 - loss: 0.5466 - val_accuracy: 0.7500 - val_loss: 0.4764
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7753 - loss: 0.4814 - val_accuracy: 0.7463 - val_loss: 0.4823
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7705 - loss: 0.4909 - val_accuracy: 0.7500 - val_loss: 0.4758
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7592 - loss: 0.5482 - val_accuracy: 0.6567 - val_loss: 0.6678
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7496 - loss: 0.5303 - val_accuracy: 0.7500 - val_loss: 0.4791
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7737 - loss: 0.4792 - val_accuracy: 0.7575 - val_loss: 0.4780
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7801 - loss: 0.4758 - val_accuracy: 0.7537 - val_loss: 0.5672
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7657 - loss: 0.4961 - val_accuracy: 0.7500 - val_loss: 0.4877
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7753 - loss: 0.4917 - val_accuracy: 0.7500 - val_loss: 0.5307
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7624 - loss: 0.5045 - val_accuracy: 0.7425 - val_loss: 0.4771
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7801 - loss: 0.4876 - val_accuracy: 0.7500 - val_loss: 0.5242
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7817 - loss: 0.4702 - val_accuracy: 0.7537 - val_loss: 0.4785
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7817 - loss: 0.4726 - val_accuracy: 0.7463 - val_loss: 0.4837
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7640 - loss: 0.5125 - val_accuracy: 0.7463 - val_loss: 0.5045
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7657 - loss: 0.5194 - val_accuracy: 0.7425 - val_loss: 0.4845
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5055 - val_accuracy: 0.7425 - val_loss: 0.5120
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7592 - loss: 0.5105 - val_accuracy: 0.6455 - val_loss: 0.6692
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7352 - loss: 0.5675 - val_accuracy: 0.7351 - val_loss: 0.4924
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7817 - loss: 0.4913 - val_accuracy: 0.7537 - val_loss: 0.5362
Epoch 153/5000

wandb: Agent Starting Run: hpb3rgiz with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5859 - loss: 1.3132 - val_accuracy: 0.6007 - val_loss: 0.8110
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.7069 - val_accuracy: 0.6082 - val_loss: 0.7511
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6100 - loss: 0.6939 - val_accuracy: 0.6045 - val_loss: 0.7345
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6132 - loss: 0.6874 - val_accuracy: 0.6082 - val_loss: 0.7280
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6083 - loss: 0.6838 - val_accuracy: 0.6082 - val_loss: 0.7191
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6132 - loss: 0.6810 - val_accuracy: 0.6082 - val_loss: 0.7255
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6164 - loss: 0.6771 - val_accuracy: 0.6082 - val_loss: 0.7275
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6148 - loss: 0.6756 - val_accuracy: 0.6045 - val_loss: 0.7261
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6732 - val_accuracy: 0.6119 - val_loss: 0.7245
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6148 - loss: 0.6707 - val_accuracy: 0.6082 - val_loss: 0.7289
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.6164 - loss: 0.6701 - val_accuracy: 0.6045 - val_loss: 0.7267
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6696 - val_accuracy: 0.6045 - val_loss: 0.7239
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6148 - loss: 0.6691 - val_accuracy: 0.6082 - val_loss: 0.7207
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.6164 - loss: 0.6684 - val_accuracy: 0.6082 - val_loss: 0.7284
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.6196 - loss: 0.6670 - val_accuracy: 0.6082 - val_loss: 0.7228
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6082 - val_loss: 0.7194
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6670 - val_accuracy: 0.6082 - val_loss: 0.7197
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6082 - val_loss: 0.7148
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6148 - loss: 0.6679 - val_accuracy: 0.6082 - val_loss: 0.7243
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6180 - loss: 0.6661 - val_accuracy: 0.6082 - val_loss: 0.7235
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6164 - loss: 0.6684 - val_accuracy: 0.6082 - val_loss: 0.7222
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6082 - val_loss: 0.7212
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6148 - loss: 0.6653 - val_accuracy: 0.6082 - val_loss: 0.7177
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6082 - val_loss: 0.7222
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6116 - loss: 0.6673 - val_accuracy: 0.6082 - val_loss: 0.7278
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6082 - val_loss: 0.7195
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6082 - val_loss: 0.7294
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6082 - val_loss: 0.7269
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6082 - val_loss: 0.7247
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6082 - val_loss: 0.7284
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6228 - loss: 0.6644 - val_accuracy: 0.6045 - val_loss: 0.7279
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6082 - val_loss: 0.7252
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6157 - val_loss: 0.7353
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6196 - loss: 0.6635 - val_accuracy: 0.6082 - val_loss: 0.7228
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6212 - loss: 0.6632 - val_accuracy: 0.6082 - val_loss: 0.7225
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6119 - val_loss: 0.7359
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6045 - val_loss: 0.7312
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6082 - val_loss: 0.7239
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6082 - val_loss: 0.7224
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6212 - loss: 0.6640 - val_accuracy: 0.6082 - val_loss: 0.7221
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6228 - loss: 0.6626 - val_accuracy: 0.6082 - val_loss: 0.7253
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6196 - loss: 0.6635 - val_accuracy: 0.6082 - val_loss: 0.7297
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6196 - loss: 0.6639 - val_accuracy: 0.6119 - val_loss: 0.7322
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6212 - loss: 0.6637 - val_accuracy: 0.6082 - val_loss: 0.7243
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6164 - loss: 0.6665 - val_accuracy: 0.6082 - val_loss: 0.7292
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6082 - val_loss: 0.7335
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6082 - val_loss: 0.7297
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6082 - val_loss: 0.7238
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6228 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7319
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6228 - loss: 0.6625 - val_accuracy: 0.6082 - val_loss: 0.7264
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6196 - loss: 0.6636 - val_accuracy: 0.6082 - val_loss: 0.7349
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6228 - loss: 0.6639 - val_accuracy: 0.6119 - val_loss: 0.7341
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6228 - loss: 0.6621 - val_accuracy: 0.6082 - val_loss: 0.7259
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6119 - val_loss: 0.7336
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6119 - val_loss: 0.7404
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6196 - loss: 0.6633 - val_accuracy: 0.6082 - val_loss: 0.7302
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6244 - loss: 0.6634 - val_accuracy: 0.6119 - val_loss: 0.7345
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6196 - loss: 0.6630 - val_accuracy: 0.6082 - val_loss: 0.7292
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6635 - val_accuracy: 0.6082 - val_loss: 0.7307
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6212 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.7306
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6119 - val_loss: 0.7405
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6212 - loss: 0.6623 - val_accuracy: 0.6119 - val_loss: 0.7430
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6212 - loss: 0.6637 - val_accuracy: 0.6119 - val_loss: 0.7345
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6157 - val_loss: 0.7408
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6212 - loss: 0.6621 - val_accuracy: 0.6119 - val_loss: 0.7333
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7315
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6244 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.7446
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6196 - loss: 0.6635 - val_accuracy: 0.6119 - val_loss: 0.7385
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.7509
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6228 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7330
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.7366
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6228 - loss: 0.6619 - val_accuracy: 0.6119 - val_loss: 0.7371
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6212 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.7362
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6119 - val_loss: 0.7382
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6212 - loss: 0.6623 - val_accuracy: 0.6119 - val_loss: 0.7432
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6212 - loss: 0.6622 - val_accuracy: 0.6157 - val_loss: 0.7424
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.7366
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6244 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.7424
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6228 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7487
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6119 - val_loss: 0.7463
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6244 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.7419
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.7465
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.7519
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.7523
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6212 - loss: 0.6624 - val_accuracy: 0.6119 - val_loss: 0.7446
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.7356
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.7429
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.7491
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7431
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6228 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7441
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6228 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.7550
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7553
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6212 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.7434
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.7474
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6228 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.7469
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6157 - val_loss: 0.7484
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6244 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7452
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.7494
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6228 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.7523
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6602 - val_accuracy: 0.6119 - val_loss: 0.7540
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6228 - loss: 0.6603 - val_accuracy: 0.6119 - val_loss: 0.7428
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7457
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6157 - val_loss: 0.7500
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6119 - val_loss: 0.7430
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6244 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7400
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6228 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.7428
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6228 - loss: 0.6599 - val_accuracy: 0.6119 - val_loss: 0.7523
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6228 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.7494
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6212 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.7491
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6157 - val_loss: 0.7545
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.7409
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6212 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.7494
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6228 - loss: 0.6596 - val_accuracy: 0.6119 - val_loss: 0.7410
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6228 - loss: 0.6603 - val_accuracy: 0.6119 - val_loss: 0.7458
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6228 - loss: 0.6600 - val_accuracy: 0.6157 - val_loss: 0.7428
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6244 - loss: 0.6602 - val_accuracy: 0.6119 - val_loss: 0.7512
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6244 - loss: 0.6593 - val_accuracy: 0.6119 - val_loss: 0.7454
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6228 - loss: 0.6603 - val_accuracy: 0.6119 - val_loss: 0.7418
Epoch 118: early stopping

wandb: Agent Starting Run: oj842717 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5795 - loss: 3.7380 - val_accuracy: 0.7015 - val_loss: 1.0609
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 1.1209 - val_accuracy: 0.6903 - val_loss: 0.7035
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.8015 - val_accuracy: 0.6082 - val_loss: 0.6852
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6276 - loss: 0.7257 - val_accuracy: 0.6940 - val_loss: 0.6029
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.6591 - val_accuracy: 0.7164 - val_loss: 0.6119
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.6629 - loss: 0.6608 - val_accuracy: 0.6866 - val_loss: 0.6165
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6569 - val_accuracy: 0.5784 - val_loss: 0.6984
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6415 - val_accuracy: 0.7276 - val_loss: 0.6177
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6717 - val_accuracy: 0.6828 - val_loss: 0.6172
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5949 - val_accuracy: 0.7164 - val_loss: 0.5732
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6349 - val_accuracy: 0.6866 - val_loss: 0.6352
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6629 - loss: 0.6170 - val_accuracy: 0.7425 - val_loss: 0.5690
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6886 - loss: 0.6125 - val_accuracy: 0.7127 - val_loss: 0.5702
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.7079 - loss: 0.5970 - val_accuracy: 0.7127 - val_loss: 0.6149
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5962 - val_accuracy: 0.7388 - val_loss: 0.5504
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7047 - loss: 0.5794 - val_accuracy: 0.6791 - val_loss: 0.6320
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5886 - val_accuracy: 0.7127 - val_loss: 0.5414
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5932 - val_accuracy: 0.4851 - val_loss: 0.8566
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6998 - loss: 0.5863 - val_accuracy: 0.7276 - val_loss: 0.5319
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6902 - loss: 0.5792 - val_accuracy: 0.6045 - val_loss: 0.6742
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.7143 - loss: 0.5683 - val_accuracy: 0.6754 - val_loss: 0.6047
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7030 - loss: 0.5671 - val_accuracy: 0.5336 - val_loss: 0.7357
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7047 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.5463
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6950 - loss: 0.5803 - val_accuracy: 0.7239 - val_loss: 0.5203
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7335 - loss: 0.5548 - val_accuracy: 0.7313 - val_loss: 0.5180
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5593 - val_accuracy: 0.7500 - val_loss: 0.5433
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7352 - loss: 0.5345 - val_accuracy: 0.7537 - val_loss: 0.5785
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.7175 - loss: 0.5684 - val_accuracy: 0.7500 - val_loss: 0.5392
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7159 - loss: 0.5703 - val_accuracy: 0.7463 - val_loss: 0.5142
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7207 - loss: 0.5501 - val_accuracy: 0.6791 - val_loss: 0.6297
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7319 - loss: 0.5519 - val_accuracy: 0.7015 - val_loss: 0.5454
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7400 - loss: 0.5243 - val_accuracy: 0.6940 - val_loss: 0.5894
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7352 - loss: 0.5426 - val_accuracy: 0.6828 - val_loss: 0.6296
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7448 - loss: 0.5493 - val_accuracy: 0.7537 - val_loss: 0.5387
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7175 - loss: 0.5447 - val_accuracy: 0.6418 - val_loss: 0.6521
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7207 - loss: 0.5289 - val_accuracy: 0.7127 - val_loss: 0.5862
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7175 - loss: 0.5655 - val_accuracy: 0.7201 - val_loss: 0.5061
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7560 - loss: 0.5172 - val_accuracy: 0.7201 - val_loss: 0.5202
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7335 - loss: 0.5386 - val_accuracy: 0.7388 - val_loss: 0.5215
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7576 - loss: 0.5311 - val_accuracy: 0.7351 - val_loss: 0.5097
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7560 - loss: 0.5298 - val_accuracy: 0.7761 - val_loss: 0.5319
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7432 - loss: 0.5133 - val_accuracy: 0.6978 - val_loss: 0.5768
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7480 - loss: 0.5167 - val_accuracy: 0.6679 - val_loss: 0.6574
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7673 - loss: 0.5119 - val_accuracy: 0.6791 - val_loss: 0.6370
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7544 - loss: 0.5046 - val_accuracy: 0.6157 - val_loss: 0.7302
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7496 - loss: 0.5382 - val_accuracy: 0.7575 - val_loss: 0.4944
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7737 - loss: 0.5004 - val_accuracy: 0.7127 - val_loss: 0.5709
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7769 - loss: 0.4853 - val_accuracy: 0.7127 - val_loss: 0.5534
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7640 - loss: 0.5037 - val_accuracy: 0.7575 - val_loss: 0.4855
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5222 - val_accuracy: 0.7537 - val_loss: 0.4864
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7705 - loss: 0.5259 - val_accuracy: 0.7276 - val_loss: 0.5039
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7833 - loss: 0.4996 - val_accuracy: 0.7090 - val_loss: 0.6087
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7705 - loss: 0.5205 - val_accuracy: 0.6791 - val_loss: 0.6855
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7753 - loss: 0.5052 - val_accuracy: 0.7649 - val_loss: 0.5387
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7721 - loss: 0.4910 - val_accuracy: 0.7649 - val_loss: 0.5155
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5078 - val_accuracy: 0.7276 - val_loss: 0.5241
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7608 - loss: 0.5290 - val_accuracy: 0.7612 - val_loss: 0.5034
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7753 - loss: 0.4936 - val_accuracy: 0.7463 - val_loss: 0.5121
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7673 - loss: 0.5320 - val_accuracy: 0.7724 - val_loss: 0.5427
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7849 - loss: 0.4928 - val_accuracy: 0.7537 - val_loss: 0.5346
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7737 - loss: 0.4998 - val_accuracy: 0.7164 - val_loss: 0.5871
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7881 - loss: 0.5099 - val_accuracy: 0.7612 - val_loss: 0.5187
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7689 - loss: 0.5218 - val_accuracy: 0.7425 - val_loss: 0.4963
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7881 - loss: 0.4949 - val_accuracy: 0.7127 - val_loss: 0.5628
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7801 - loss: 0.4978 - val_accuracy: 0.7351 - val_loss: 0.5179
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7913 - loss: 0.4901 - val_accuracy: 0.7164 - val_loss: 0.5564
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7769 - loss: 0.4962 - val_accuracy: 0.7500 - val_loss: 0.4995
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7608 - loss: 0.5006 - val_accuracy: 0.7052 - val_loss: 0.6399
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5036 - val_accuracy: 0.7537 - val_loss: 0.5013
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7817 - loss: 0.5084 - val_accuracy: 0.7687 - val_loss: 0.5854
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7897 - loss: 0.4823 - val_accuracy: 0.7425 - val_loss: 0.5150
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7978 - loss: 0.4876 - val_accuracy: 0.7425 - val_loss: 0.5016
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7753 - loss: 0.4882 - val_accuracy: 0.7425 - val_loss: 0.5065
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7881 - loss: 0.5097 - val_accuracy: 0.7425 - val_loss: 0.5019
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7769 - loss: 0.5057 - val_accuracy: 0.7276 - val_loss: 0.5404
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.7929 - loss: 0.4836 - val_accuracy: 0.7276 - val_loss: 0.5393
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7673 - loss: 0.5123 - val_accuracy: 0.7388 - val_loss: 0.5182
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7978 - loss: 0.4971 - val_accuracy: 0.7388 - val_loss: 0.5313
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7849 - loss: 0.4945 - val_accuracy: 0.7239 - val_loss: 0.5489
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7849 - loss: 0.5053 - val_accuracy: 0.7388 - val_loss: 0.5262
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7913 - loss: 0.4884 - val_accuracy: 0.7201 - val_loss: 0.6573
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7897 - loss: 0.4756 - val_accuracy: 0.6269 - val_loss: 0.7334
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7753 - loss: 0.5019 - val_accuracy: 0.7425 - val_loss: 0.5927
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.7849 - loss: 0.4908 - val_accuracy: 0.6194 - val_loss: 0.7510
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7961 - loss: 0.4939 - val_accuracy: 0.7052 - val_loss: 0.6296
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7881 - loss: 0.4822 - val_accuracy: 0.7164 - val_loss: 0.5612
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4882 - val_accuracy: 0.7425 - val_loss: 0.5027
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7881 - loss: 0.5028 - val_accuracy: 0.7537 - val_loss: 0.5047
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7945 - loss: 0.4843 - val_accuracy: 0.7201 - val_loss: 0.6202
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4885 - val_accuracy: 0.7463 - val_loss: 0.5305
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7913 - loss: 0.4781 - val_accuracy: 0.7575 - val_loss: 0.5148
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7978 - loss: 0.4984 - val_accuracy: 0.7463 - val_loss: 0.5198
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7913 - loss: 0.4895 - val_accuracy: 0.7425 - val_loss: 0.5218
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.8010 - loss: 0.4883 - val_accuracy: 0.7761 - val_loss: 0.5479
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7881 - loss: 0.4893 - val_accuracy: 0.7500 - val_loss: 0.5033
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7801 - loss: 0.4838 - val_accuracy: 0.7500 - val_loss: 0.4942
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7833 - loss: 0.5001 - val_accuracy: 0.7575 - val_loss: 0.4991
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7929 - loss: 0.4798 - val_accuracy: 0.7388 - val_loss: 0.5358
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7994 - loss: 0.4795 - val_accuracy: 0.7724 - val_loss: 0.5717
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7881 - loss: 0.5025 - val_accuracy: 0.7612 - val_loss: 0.5316
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7897 - loss: 0.4791 - val_accuracy: 0.7687 - val_loss: 0.5301
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8106 - loss: 0.4679 - val_accuracy: 0.7015 - val_loss: 0.6406
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7978 - loss: 0.4867 - val_accuracy: 0.7500 - val_loss: 0.4967
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7978 - loss: 0.4675 - val_accuracy: 0.7575 - val_loss: 0.4913
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7978 - loss: 0.5011 - val_accuracy: 0.7463 - val_loss: 0.5153
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8010 - loss: 0.4820 - val_accuracy: 0.7425 - val_loss: 0.5312
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7897 - loss: 0.4982 - val_accuracy: 0.7500 - val_loss: 0.5099
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7913 - loss: 0.5042 - val_accuracy: 0.7052 - val_loss: 0.6202
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4802 - val_accuracy: 0.7537 - val_loss: 0.4903
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7833 - loss: 0.4931 - val_accuracy: 0.7537 - val_loss: 0.5210
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8074 - loss: 0.4689 - val_accuracy: 0.7537 - val_loss: 0.5159
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8122 - loss: 0.4798 - val_accuracy: 0.7015 - val_loss: 0.6469
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7978 - loss: 0.4821 - val_accuracy: 0.7836 - val_loss: 0.5682
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.8090 - loss: 0.4706 - val_accuracy: 0.7575 - val_loss: 0.5047
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7817 - loss: 0.4901 - val_accuracy: 0.7575 - val_loss: 0.5141
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7994 - loss: 0.4891 - val_accuracy: 0.7836 - val_loss: 0.5759
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8122 - loss: 0.4771 - val_accuracy: 0.7761 - val_loss: 0.5568
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7913 - loss: 0.4773 - val_accuracy: 0.7052 - val_loss: 0.6252
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7849 - loss: 0.5005 - val_accuracy: 0.7463 - val_loss: 0.5411
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7961 - loss: 0.4724 - val_accuracy: 0.7537 - val_loss: 0.4981
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7978 - loss: 0.4710 - val_accuracy: 0.7575 - val_loss: 0.5038
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7994 - loss: 0.4750 - val_accuracy: 0.7575 - val_loss: 0.5232
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7978 - loss: 0.4616 - val_accuracy: 0.6604 - val_loss: 0.6986
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7913 - loss: 0.4754 - val_accuracy: 0.7724 - val_loss: 0.5605
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.8026 - loss: 0.4911 - val_accuracy: 0.7537 - val_loss: 0.4966
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7929 - loss: 0.4820 - val_accuracy: 0.7575 - val_loss: 0.5165
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.8042 - loss: 0.4713 - val_accuracy: 0.7463 - val_loss: 0.5021
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5038 - val_accuracy: 0.7463 - val_loss: 0.5063
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7929 - loss: 0.4724 - val_accuracy: 0.7612 - val_loss: 0.5104
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7961 - loss: 0.4608 - val_accuracy: 0.7500 - val_loss: 0.5329
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7897 - loss: 0.5051 - val_accuracy: 0.6007 - val_loss: 0.7820
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7961 - loss: 0.4752 - val_accuracy: 0.6978 - val_loss: 0.6406
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.8026 - loss: 0.4732 - val_accuracy: 0.7612 - val_loss: 0.5109
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7994 - loss: 0.4656 - val_accuracy: 0.6604 - val_loss: 0.6991
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8026 - loss: 0.4757 - val_accuracy: 0.7761 - val_loss: 0.5780
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7865 - loss: 0.4824 - val_accuracy: 0.7351 - val_loss: 0.5423
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7897 - loss: 0.4744 - val_accuracy: 0.5560 - val_loss: 0.8657
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8106 - loss: 0.4764 - val_accuracy: 0.7425 - val_loss: 0.5319
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7881 - loss: 0.4647 - val_accuracy: 0.7537 - val_loss: 0.5115
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7929 - loss: 0.4694 - val_accuracy: 0.7351 - val_loss: 0.6184
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7913 - loss: 0.4711 - val_accuracy: 0.7276 - val_loss: 0.6307
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.8026 - loss: 0.4787 - val_accuracy: 0.7052 - val_loss: 0.6397
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8026 - loss: 0.4706 - val_accuracy: 0.7575 - val_loss: 0.5221
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7994 - loss: 0.4802 - val_accuracy: 0.6866 - val_loss: 0.7533
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8010 - loss: 0.4628 - val_accuracy: 0.7500 - val_loss: 0.5173
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8042 - loss: 0.4678 - val_accuracy: 0.7164 - val_loss: 0.5768
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8058 - loss: 0.4791 - val_accuracy: 0.7052 - val_loss: 0.7063
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8026 - loss: 0.4624 - val_accuracy: 0.7575 - val_loss: 0.5025
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7689 - loss: 0.4880 - val_accuracy: 0.7649 - val_loss: 0.5304
Epoch 149: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ldf2xgt2 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4446 - loss: 12.1187 - val_accuracy: 0.6045 - val_loss: 3.1263
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4976 - loss: 1.6259 - val_accuracy: 0.3209 - val_loss: 1.0661
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5345 - loss: 0.7987 - val_accuracy: 0.6269 - val_loss: 0.7381
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.6936 - val_accuracy: 0.6679 - val_loss: 0.7169
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.6758 - val_accuracy: 0.6791 - val_loss: 0.6951
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6549 - loss: 0.6670 - val_accuracy: 0.5261 - val_loss: 0.8055
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6260 - loss: 0.7172 - val_accuracy: 0.6343 - val_loss: 0.8964
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6504 - val_accuracy: 0.6493 - val_loss: 0.7243
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.6806 - loss: 0.6293 - val_accuracy: 0.6903 - val_loss: 0.6891
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6790 - loss: 0.6405 - val_accuracy: 0.6754 - val_loss: 0.6598
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6218 - val_accuracy: 0.7090 - val_loss: 0.6357
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6918 - loss: 0.6161 - val_accuracy: 0.6754 - val_loss: 0.6476
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6006 - val_accuracy: 0.7201 - val_loss: 0.6372
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5965 - val_accuracy: 0.7351 - val_loss: 0.6322
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6742 - loss: 0.6112 - val_accuracy: 0.6567 - val_loss: 0.7583
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.6139 - val_accuracy: 0.7463 - val_loss: 0.6299
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.5709 - val_accuracy: 0.6679 - val_loss: 0.6585
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6026 - val_accuracy: 0.6604 - val_loss: 0.7073
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7111 - loss: 0.5647 - val_accuracy: 0.7463 - val_loss: 0.6382
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5641 - val_accuracy: 0.7313 - val_loss: 0.5872
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7416 - loss: 0.5405 - val_accuracy: 0.7575 - val_loss: 0.5897
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7448 - loss: 0.5360 - val_accuracy: 0.7313 - val_loss: 0.5898
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7496 - loss: 0.5410 - val_accuracy: 0.7388 - val_loss: 0.5801
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7271 - loss: 0.5543 - val_accuracy: 0.7724 - val_loss: 0.6053
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7255 - loss: 0.5533 - val_accuracy: 0.7239 - val_loss: 0.5728
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5437 - val_accuracy: 0.7761 - val_loss: 0.5793
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7528 - loss: 0.5181 - val_accuracy: 0.6567 - val_loss: 0.7274
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7560 - loss: 0.5238 - val_accuracy: 0.6604 - val_loss: 0.7523
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7480 - loss: 0.5516 - val_accuracy: 0.7463 - val_loss: 0.5504
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7705 - loss: 0.4983 - val_accuracy: 0.7649 - val_loss: 0.5451
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7640 - loss: 0.5020 - val_accuracy: 0.7239 - val_loss: 0.5588
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7640 - loss: 0.5092 - val_accuracy: 0.7537 - val_loss: 0.5327
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7865 - loss: 0.5023 - val_accuracy: 0.7201 - val_loss: 0.5690
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7560 - loss: 0.5166 - val_accuracy: 0.7649 - val_loss: 0.5461
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7753 - loss: 0.5080 - val_accuracy: 0.7239 - val_loss: 0.5551
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7608 - loss: 0.5117 - val_accuracy: 0.7687 - val_loss: 0.5926
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7287 - loss: 0.5536 - val_accuracy: 0.7537 - val_loss: 0.5186
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5290 - val_accuracy: 0.7351 - val_loss: 0.5515
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7817 - loss: 0.4935 - val_accuracy: 0.7575 - val_loss: 0.5203
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7721 - loss: 0.5121 - val_accuracy: 0.7201 - val_loss: 0.5686
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7833 - loss: 0.4717 - val_accuracy: 0.7388 - val_loss: 0.5448
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7673 - loss: 0.4821 - val_accuracy: 0.7687 - val_loss: 0.5206
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7945 - loss: 0.4741 - val_accuracy: 0.7761 - val_loss: 0.5465
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7817 - loss: 0.4840 - val_accuracy: 0.7761 - val_loss: 0.5500
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7945 - loss: 0.4713 - val_accuracy: 0.7537 - val_loss: 0.5295
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7721 - loss: 0.5129 - val_accuracy: 0.6978 - val_loss: 0.6226
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7897 - loss: 0.4763 - val_accuracy: 0.7537 - val_loss: 0.5128
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7929 - loss: 0.4647 - val_accuracy: 0.7724 - val_loss: 0.5097
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4851 - val_accuracy: 0.7761 - val_loss: 0.5366
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7528 - loss: 0.5301 - val_accuracy: 0.7799 - val_loss: 0.5038
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7817 - loss: 0.5006 - val_accuracy: 0.7873 - val_loss: 0.5737
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7721 - loss: 0.5113 - val_accuracy: 0.6978 - val_loss: 0.6482
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7255 - loss: 0.5994 - val_accuracy: 0.7537 - val_loss: 0.5217
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7881 - loss: 0.4777 - val_accuracy: 0.7649 - val_loss: 0.5054
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7978 - loss: 0.4632 - val_accuracy: 0.7724 - val_loss: 0.5673
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7929 - loss: 0.4664 - val_accuracy: 0.7500 - val_loss: 0.5271
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7961 - loss: 0.4770 - val_accuracy: 0.7649 - val_loss: 0.5284
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7785 - loss: 0.4906 - val_accuracy: 0.7276 - val_loss: 0.6123
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7978 - loss: 0.4741 - val_accuracy: 0.7463 - val_loss: 0.5393
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7528 - loss: 0.5204 - val_accuracy: 0.7724 - val_loss: 0.5126
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7961 - loss: 0.4848 - val_accuracy: 0.7687 - val_loss: 0.5139
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.7961 - loss: 0.4497 - val_accuracy: 0.7351 - val_loss: 0.6042
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7817 - loss: 0.4813 - val_accuracy: 0.7463 - val_loss: 0.5481
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7865 - loss: 0.4872 - val_accuracy: 0.7276 - val_loss: 0.6193
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7881 - loss: 0.4956 - val_accuracy: 0.7761 - val_loss: 0.5062
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7881 - loss: 0.4821 - val_accuracy: 0.7761 - val_loss: 0.5074
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7929 - loss: 0.4520 - val_accuracy: 0.7649 - val_loss: 0.5033
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.8010 - loss: 0.4539 - val_accuracy: 0.8022 - val_loss: 0.5831
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.7801 - loss: 0.4753 - val_accuracy: 0.7313 - val_loss: 0.5822
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4617 - val_accuracy: 0.7687 - val_loss: 0.5095
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7945 - loss: 0.4725 - val_accuracy: 0.7649 - val_loss: 0.5115
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7897 - loss: 0.4645 - val_accuracy: 0.7276 - val_loss: 0.6222
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7560 - loss: 0.5680 - val_accuracy: 0.7388 - val_loss: 0.6272
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7801 - loss: 0.4750 - val_accuracy: 0.7724 - val_loss: 0.5117
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7881 - loss: 0.4716 - val_accuracy: 0.7687 - val_loss: 0.5093
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7849 - loss: 0.4578 - val_accuracy: 0.7687 - val_loss: 0.6168
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7608 - loss: 0.5134 - val_accuracy: 0.7649 - val_loss: 0.5012
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7994 - loss: 0.4594 - val_accuracy: 0.7687 - val_loss: 0.5019
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7753 - loss: 0.4994 - val_accuracy: 0.7724 - val_loss: 0.5030
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8074 - loss: 0.4435 - val_accuracy: 0.7761 - val_loss: 0.5098
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8106 - loss: 0.4532 - val_accuracy: 0.7799 - val_loss: 0.5282
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.8058 - loss: 0.4490 - val_accuracy: 0.7799 - val_loss: 0.5433
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.8058 - loss: 0.4533 - val_accuracy: 0.7724 - val_loss: 0.5220
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7673 - loss: 0.5135 - val_accuracy: 0.7836 - val_loss: 0.5421
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8042 - loss: 0.4433 - val_accuracy: 0.7537 - val_loss: 0.5485
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.8042 - loss: 0.4751 - val_accuracy: 0.7836 - val_loss: 0.5145
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8042 - loss: 0.4583 - val_accuracy: 0.7799 - val_loss: 0.5115
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8138 - loss: 0.4434 - val_accuracy: 0.7463 - val_loss: 0.5549
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4546 - val_accuracy: 0.7799 - val_loss: 0.5231
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8058 - loss: 0.4464 - val_accuracy: 0.7537 - val_loss: 0.5755
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7881 - loss: 0.4648 - val_accuracy: 0.7463 - val_loss: 0.5500
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7913 - loss: 0.4977 - val_accuracy: 0.7687 - val_loss: 0.5156
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.8026 - loss: 0.4688 - val_accuracy: 0.7649 - val_loss: 0.5321
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7978 - loss: 0.4593 - val_accuracy: 0.7836 - val_loss: 0.5582
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.8026 - loss: 0.4447 - val_accuracy: 0.7761 - val_loss: 0.5234
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.8026 - loss: 0.4637 - val_accuracy: 0.7388 - val_loss: 0.5956
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8042 - loss: 0.4674 - val_accuracy: 0.7799 - val_loss: 0.5363
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8010 - loss: 0.4751 - val_accuracy: 0.7724 - val_loss: 0.5205
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.8090 - loss: 0.4998 - val_accuracy: 0.7052 - val_loss: 0.7143
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7881 - loss: 0.4889 - val_accuracy: 0.7799 - val_loss: 0.5349
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7897 - loss: 0.4639 - val_accuracy: 0.7724 - val_loss: 0.5373
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8138 - loss: 0.4468 - val_accuracy: 0.7313 - val_loss: 0.6564
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8106 - loss: 0.4571 - val_accuracy: 0.7687 - val_loss: 0.5237
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8074 - loss: 0.4960 - val_accuracy: 0.6978 - val_loss: 0.6915
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7640 - loss: 0.5013 - val_accuracy: 0.7836 - val_loss: 0.5608
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8074 - loss: 0.4517 - val_accuracy: 0.7761 - val_loss: 0.5452
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8042 - loss: 0.4410 - val_accuracy: 0.7724 - val_loss: 0.5247
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4492 - val_accuracy: 0.7687 - val_loss: 0.5179
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7897 - loss: 0.4811 - val_accuracy: 0.7799 - val_loss: 0.5488
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7945 - loss: 0.4740 - val_accuracy: 0.7276 - val_loss: 0.6801
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7978 - loss: 0.4706 - val_accuracy: 0.7761 - val_loss: 0.5453
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7833 - loss: 0.4842 - val_accuracy: 0.7425 - val_loss: 0.6329
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7849 - loss: 0.5139 - val_accuracy: 0.6866 - val_loss: 0.8210
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7817 - loss: 0.5042 - val_accuracy: 0.7575 - val_loss: 0.5840
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8106 - loss: 0.4505 - val_accuracy: 0.7649 - val_loss: 0.5290
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7994 - loss: 0.4514 - val_accuracy: 0.7873 - val_loss: 0.5716
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7929 - loss: 0.4613 - val_accuracy: 0.7873 - val_loss: 0.6215
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8186 - loss: 0.4495 - val_accuracy: 0.7910 - val_loss: 0.5925
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.8010 - loss: 0.4417 - val_accuracy: 0.7799 - val_loss: 0.5711
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7994 - loss: 0.4512 - val_accuracy: 0.7463 - val_loss: 0.5629
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8010 - loss: 0.4428 - val_accuracy: 0.7724 - val_loss: 0.5264
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7913 - loss: 0.4642 - val_accuracy: 0.7724 - val_loss: 0.5382
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8010 - loss: 0.4504 - val_accuracy: 0.7724 - val_loss: 0.5413
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4532 - val_accuracy: 0.7799 - val_loss: 0.5710
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4665 - val_accuracy: 0.7687 - val_loss: 0.5301
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7994 - loss: 0.4528 - val_accuracy: 0.7836 - val_loss: 0.5412
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7994 - loss: 0.4532 - val_accuracy: 0.7388 - val_loss: 0.5883
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7673 - loss: 0.5267 - val_accuracy: 0.7537 - val_loss: 0.5858
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.8074 - loss: 0.4547 - val_accuracy: 0.7724 - val_loss: 0.5220
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8074 - loss: 0.4563 - val_accuracy: 0.7239 - val_loss: 0.6622
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7961 - loss: 0.4600 - val_accuracy: 0.7724 - val_loss: 0.5204
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8074 - loss: 0.4629 - val_accuracy: 0.7687 - val_loss: 0.5672
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.8042 - loss: 0.4408 - val_accuracy: 0.7799 - val_loss: 0.5495
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7913 - loss: 0.4531 - val_accuracy: 0.7724 - val_loss: 0.5444
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8138 - loss: 0.4410 - val_accuracy: 0.7836 - val_loss: 0.5469
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7945 - loss: 0.4617 - val_accuracy: 0.7910 - val_loss: 0.6203
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.7978 - loss: 0.4581 - val_accuracy: 0.7351 - val_loss: 0.6565
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7785 - loss: 0.5009 - val_accuracy: 0.7724 - val_loss: 0.5529
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7994 - loss: 0.4510 - val_accuracy: 0.7649 - val_loss: 0.5437
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8106 - loss: 0.4314 - val_accuracy: 0.7687 - val_loss: 0.5763
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7865 - loss: 0.4603 - val_accuracy: 0.7649 - val_loss: 0.6594
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5094 - val_accuracy: 0.7836 - val_loss: 0.5651
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7785 - loss: 0.4950 - val_accuracy: 0.7761 - val_loss: 0.5574
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8042 - loss: 0.4415 - val_accuracy: 0.7761 - val_loss: 0.5859
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.8010 - loss: 0.4568 - val_accuracy: 0.7799 - val_loss: 0.5723
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8026 - loss: 0.4473 - val_accuracy: 0.7836 - val_loss: 0.6381
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7881 - loss: 0.4728 - val_accuracy: 0.7388 - val_loss: 0.6446
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7881 - loss: 0.4730 - val_accuracy: 0.7873 - val_loss: 0.5898
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8170 - loss: 0.4497 - val_accuracy: 0.7127 - val_loss: 0.7108
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7624 - loss: 0.5329 - val_accuracy: 0.7687 - val_loss: 0.5444
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8026 - loss: 0.4568 - val_accuracy: 0.7761 - val_loss: 0.5445
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7978 - loss: 0.4409 - val_accuracy: 0.7687 - val_loss: 0.5746
Epoch 153/5000

wandb: Agent Starting Run: z4elg0d9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5698 - loss: 18.2745 - val_accuracy: 0.6082 - val_loss: 0.7173
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6051 - loss: 0.7075 - val_accuracy: 0.6306 - val_loss: 0.6766
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.6003 - loss: 0.6972 - val_accuracy: 0.6157 - val_loss: 0.7078
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6116 - loss: 0.6897 - val_accuracy: 0.6269 - val_loss: 0.7102
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6164 - loss: 0.6839 - val_accuracy: 0.6231 - val_loss: 0.7148
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6116 - loss: 0.6764 - val_accuracy: 0.6269 - val_loss: 0.7178
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6132 - loss: 0.6809 - val_accuracy: 0.6269 - val_loss: 0.7072
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6132 - loss: 0.6827 - val_accuracy: 0.6269 - val_loss: 0.6931
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6132 - loss: 0.6756 - val_accuracy: 0.6231 - val_loss: 0.6941
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6228 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6958
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6180 - loss: 0.6729 - val_accuracy: 0.6231 - val_loss: 0.6798
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6212 - loss: 0.6654 - val_accuracy: 0.6231 - val_loss: 0.6841
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6228 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.7080
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6643 - val_accuracy: 0.6231 - val_loss: 0.6961
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6116 - loss: 0.6696 - val_accuracy: 0.6269 - val_loss: 0.7174
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6731 - val_accuracy: 0.6231 - val_loss: 0.6870
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6212 - loss: 0.6668 - val_accuracy: 0.6231 - val_loss: 0.6864
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6212 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6774
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6228 - loss: 0.6679 - val_accuracy: 0.6231 - val_loss: 0.6767
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6196 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.6759
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6837
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6231 - val_loss: 0.6813
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6212 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6843
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6194 - val_loss: 0.6805
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6633 - val_accuracy: 0.6231 - val_loss: 0.6829
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6228 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6769
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6228 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.6752
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6260 - loss: 0.6593 - val_accuracy: 0.6194 - val_loss: 0.7018
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6228 - loss: 0.6670 - val_accuracy: 0.6157 - val_loss: 0.6745
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6292 - loss: 0.6604 - val_accuracy: 0.6194 - val_loss: 0.6839
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6838
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6212 - loss: 0.6606 - val_accuracy: 0.6157 - val_loss: 0.6816
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6157 - val_loss: 0.6802
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6228 - loss: 0.6596 - val_accuracy: 0.6343 - val_loss: 0.6958
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6260 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6790
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6228 - loss: 0.6594 - val_accuracy: 0.6231 - val_loss: 0.6805
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6276 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.6794
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6231 - val_loss: 0.6813
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.6814
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6157 - val_loss: 0.6839
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.6808
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.6834
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6244 - loss: 0.6584 - val_accuracy: 0.6231 - val_loss: 0.6903
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6597 - val_accuracy: 0.6157 - val_loss: 0.6794
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6157 - val_loss: 0.6873
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.6244 - loss: 0.6599 - val_accuracy: 0.6231 - val_loss: 0.6798
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6157 - val_loss: 0.6828
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6228 - loss: 0.6596 - val_accuracy: 0.6157 - val_loss: 0.6854
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6228 - loss: 0.6593 - val_accuracy: 0.6269 - val_loss: 0.6987
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6180 - loss: 0.6598 - val_accuracy: 0.6157 - val_loss: 0.6911
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6212 - loss: 0.6600 - val_accuracy: 0.6194 - val_loss: 0.6855
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6157 - val_loss: 0.6848
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6244 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6899
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6276 - loss: 0.6579 - val_accuracy: 0.6194 - val_loss: 0.6920
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 799us/step - accuracy: 0.6292 - loss: 0.6583 - val_accuracy: 0.6194 - val_loss: 0.6895
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6228 - loss: 0.6599 - val_accuracy: 0.6194 - val_loss: 0.6878
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.6196 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.6951
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6228 - loss: 0.6589 - val_accuracy: 0.6269 - val_loss: 0.6928
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6228 - loss: 0.6609 - val_accuracy: 0.6194 - val_loss: 0.6823
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6231 - val_loss: 0.6873
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6260 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.6878
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6228 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6891
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6276 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.6871
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6194 - val_loss: 0.6908
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6260 - loss: 0.6564 - val_accuracy: 0.6157 - val_loss: 0.6866
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6576 - val_accuracy: 0.6157 - val_loss: 0.6942
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6157 - val_loss: 0.6886
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6276 - loss: 0.6574 - val_accuracy: 0.6157 - val_loss: 0.6849
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6260 - loss: 0.6572 - val_accuracy: 0.6231 - val_loss: 0.7032
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6196 - loss: 0.6631 - val_accuracy: 0.6157 - val_loss: 0.6873
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.7031
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6260 - loss: 0.6578 - val_accuracy: 0.6157 - val_loss: 0.7052
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6244 - loss: 0.6574 - val_accuracy: 0.6157 - val_loss: 0.7018
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6228 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.7006
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6260 - loss: 0.6569 - val_accuracy: 0.6231 - val_loss: 0.7037
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6260 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.7010
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6244 - loss: 0.6571 - val_accuracy: 0.6194 - val_loss: 0.7065
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6196 - loss: 0.6586 - val_accuracy: 0.6157 - val_loss: 0.6993
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6244 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.7021
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6228 - loss: 0.6573 - val_accuracy: 0.6157 - val_loss: 0.7026
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6260 - loss: 0.6574 - val_accuracy: 0.6157 - val_loss: 0.7016
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6260 - loss: 0.6558 - val_accuracy: 0.6157 - val_loss: 0.7034
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6562 - val_accuracy: 0.6306 - val_loss: 0.7020
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6157 - val_loss: 0.7009
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6260 - loss: 0.6564 - val_accuracy: 0.6157 - val_loss: 0.7008
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6276 - loss: 0.6564 - val_accuracy: 0.6231 - val_loss: 0.7062
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6244 - loss: 0.6579 - val_accuracy: 0.6157 - val_loss: 0.6965
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6228 - loss: 0.6562 - val_accuracy: 0.6157 - val_loss: 0.7016
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6244 - loss: 0.6583 - val_accuracy: 0.6157 - val_loss: 0.6972
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.6999
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6276 - loss: 0.6567 - val_accuracy: 0.6157 - val_loss: 0.7025
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6228 - loss: 0.6565 - val_accuracy: 0.6157 - val_loss: 0.7013
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6228 - loss: 0.6563 - val_accuracy: 0.6269 - val_loss: 0.6958
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6194 - val_loss: 0.6999
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6228 - loss: 0.6562 - val_accuracy: 0.6157 - val_loss: 0.7067
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6276 - loss: 0.6569 - val_accuracy: 0.6157 - val_loss: 0.7015
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6244 - loss: 0.6562 - val_accuracy: 0.6157 - val_loss: 0.7039
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6244 - loss: 0.6558 - val_accuracy: 0.6157 - val_loss: 0.7091
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6244 - loss: 0.6575 - val_accuracy: 0.6157 - val_loss: 0.7022
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6292 - loss: 0.6556 - val_accuracy: 0.6194 - val_loss: 0.7028
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6244 - loss: 0.6570 - val_accuracy: 0.6231 - val_loss: 0.7027
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6260 - loss: 0.6566 - val_accuracy: 0.6157 - val_loss: 0.7007
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6292 - loss: 0.6561 - val_accuracy: 0.6157 - val_loss: 0.6995
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6260 - loss: 0.6565 - val_accuracy: 0.6194 - val_loss: 0.6993
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6194 - val_loss: 0.7070
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6308 - loss: 0.6548 - val_accuracy: 0.6194 - val_loss: 0.7190
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6244 - loss: 0.6569 - val_accuracy: 0.6157 - val_loss: 0.7108
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 798us/step - accuracy: 0.6244 - loss: 0.6557 - val_accuracy: 0.6194 - val_loss: 0.7067
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6231 - val_loss: 0.7121
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6244 - loss: 0.6564 - val_accuracy: 0.6194 - val_loss: 0.7093
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6260 - loss: 0.6562 - val_accuracy: 0.6194 - val_loss: 0.7067
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6276 - loss: 0.6561 - val_accuracy: 0.6194 - val_loss: 0.7079
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6276 - loss: 0.6558 - val_accuracy: 0.6194 - val_loss: 0.7047
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6228 - loss: 0.6554 - val_accuracy: 0.6194 - val_loss: 0.7059
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6260 - loss: 0.6549 - val_accuracy: 0.6157 - val_loss: 0.7127
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6308 - loss: 0.6552 - val_accuracy: 0.6157 - val_loss: 0.7052
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6276 - loss: 0.6549 - val_accuracy: 0.6157 - val_loss: 0.7070
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6228 - loss: 0.6547 - val_accuracy: 0.6157 - val_loss: 0.7193
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6276 - loss: 0.6545 - val_accuracy: 0.6269 - val_loss: 0.7058
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6560 - val_accuracy: 0.6194 - val_loss: 0.7039
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6276 - loss: 0.6552 - val_accuracy: 0.6157 - val_loss: 0.7108
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6276 - loss: 0.6535 - val_accuracy: 0.6194 - val_loss: 0.7095
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6260 - loss: 0.6554 - val_accuracy: 0.6194 - val_loss: 0.7179
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6276 - loss: 0.6544 - val_accuracy: 0.6157 - val_loss: 0.7037
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6276 - loss: 0.6554 - val_accuracy: 0.6194 - val_loss: 0.7040
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6260 - loss: 0.6536 - val_accuracy: 0.6231 - val_loss: 0.7000
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6228 - loss: 0.6561 - val_accuracy: 0.6157 - val_loss: 0.7085
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6276 - loss: 0.6540 - val_accuracy: 0.6157 - val_loss: 0.7057
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6228 - loss: 0.6525 - val_accuracy: 0.6157 - val_loss: 0.7086
Epoch 129: early stopping

wandb: Agent Starting Run: j40ug1ln with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 9.7249 - val_accuracy: 0.6269 - val_loss: 0.8695
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.7637 - val_accuracy: 0.5709 - val_loss: 0.7341
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.7029 - val_accuracy: 0.4776 - val_loss: 0.7191
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6533 - loss: 0.6670 - val_accuracy: 0.7201 - val_loss: 0.5938
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6369 - val_accuracy: 0.7127 - val_loss: 0.5918
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.6758 - loss: 0.6271 - val_accuracy: 0.7313 - val_loss: 0.5463
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6758 - loss: 0.6139 - val_accuracy: 0.5522 - val_loss: 0.6546
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6130 - val_accuracy: 0.7201 - val_loss: 0.5483
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6758 - loss: 0.6009 - val_accuracy: 0.7015 - val_loss: 0.5610
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6151 - val_accuracy: 0.7388 - val_loss: 0.5664
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6822 - loss: 0.6022 - val_accuracy: 0.7500 - val_loss: 0.5620
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6870 - loss: 0.6022 - val_accuracy: 0.7239 - val_loss: 0.5927
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6693 - loss: 0.6032 - val_accuracy: 0.7388 - val_loss: 0.5510
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.5914 - val_accuracy: 0.7052 - val_loss: 0.6505
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.7063 - loss: 0.5906 - val_accuracy: 0.7164 - val_loss: 0.5324
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5968 - val_accuracy: 0.7052 - val_loss: 0.5697
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.5869 - val_accuracy: 0.7127 - val_loss: 0.5290
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6790 - loss: 0.5950 - val_accuracy: 0.7090 - val_loss: 0.5374
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.5935 - val_accuracy: 0.7127 - val_loss: 0.5913
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7207 - loss: 0.5764 - val_accuracy: 0.5746 - val_loss: 0.6553
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7014 - loss: 0.5799 - val_accuracy: 0.7500 - val_loss: 0.5483
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7143 - loss: 0.5729 - val_accuracy: 0.7388 - val_loss: 0.5323
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7127 - loss: 0.5676 - val_accuracy: 0.7164 - val_loss: 0.5740
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.7143 - loss: 0.5784 - val_accuracy: 0.7500 - val_loss: 0.5158
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5713 - val_accuracy: 0.7239 - val_loss: 0.5197
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5496 - val_accuracy: 0.7425 - val_loss: 0.5157
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5739 - val_accuracy: 0.7425 - val_loss: 0.5421
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.5686 - val_accuracy: 0.7425 - val_loss: 0.5655
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5512 - val_accuracy: 0.7463 - val_loss: 0.5052
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5554 - val_accuracy: 0.7351 - val_loss: 0.5072
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5613 - val_accuracy: 0.7537 - val_loss: 0.5216
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5630 - val_accuracy: 0.7463 - val_loss: 0.5143
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7223 - loss: 0.5718 - val_accuracy: 0.7313 - val_loss: 0.5004
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7143 - loss: 0.5536 - val_accuracy: 0.7500 - val_loss: 0.5387
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7207 - loss: 0.5543 - val_accuracy: 0.7276 - val_loss: 0.4973
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7271 - loss: 0.5519 - val_accuracy: 0.7649 - val_loss: 0.4987
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.7512 - loss: 0.5303 - val_accuracy: 0.7724 - val_loss: 0.5237
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5337 - val_accuracy: 0.7687 - val_loss: 0.4808
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7432 - loss: 0.5247 - val_accuracy: 0.7612 - val_loss: 0.4794
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7705 - loss: 0.5123 - val_accuracy: 0.7313 - val_loss: 0.4966
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7737 - loss: 0.5252 - val_accuracy: 0.7575 - val_loss: 0.5502
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.7753 - loss: 0.4998 - val_accuracy: 0.7612 - val_loss: 0.4792
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7753 - loss: 0.5226 - val_accuracy: 0.7761 - val_loss: 0.4925
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7673 - loss: 0.5055 - val_accuracy: 0.7425 - val_loss: 0.4865
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7705 - loss: 0.5009 - val_accuracy: 0.7313 - val_loss: 0.5001
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7673 - loss: 0.5084 - val_accuracy: 0.7425 - val_loss: 0.4797
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7769 - loss: 0.5000 - val_accuracy: 0.7649 - val_loss: 0.4717
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4974 - val_accuracy: 0.7575 - val_loss: 0.4741
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7897 - loss: 0.4991 - val_accuracy: 0.7649 - val_loss: 0.4737
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7865 - loss: 0.4861 - val_accuracy: 0.6493 - val_loss: 0.6595
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7801 - loss: 0.4873 - val_accuracy: 0.7351 - val_loss: 0.4938
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7705 - loss: 0.5017 - val_accuracy: 0.6903 - val_loss: 0.6175
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7913 - loss: 0.4861 - val_accuracy: 0.7239 - val_loss: 0.5195
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7961 - loss: 0.4691 - val_accuracy: 0.7799 - val_loss: 0.5485
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7785 - loss: 0.5038 - val_accuracy: 0.7052 - val_loss: 0.6133
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7785 - loss: 0.4908 - val_accuracy: 0.7761 - val_loss: 0.4949
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7865 - loss: 0.4896 - val_accuracy: 0.7313 - val_loss: 0.5910
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7929 - loss: 0.4861 - val_accuracy: 0.7313 - val_loss: 0.5299
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7753 - loss: 0.4894 - val_accuracy: 0.7239 - val_loss: 0.5457
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7769 - loss: 0.5044 - val_accuracy: 0.7351 - val_loss: 0.5206
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7865 - loss: 0.4788 - val_accuracy: 0.7649 - val_loss: 0.4860
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7849 - loss: 0.4953 - val_accuracy: 0.7388 - val_loss: 0.5074
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.7785 - loss: 0.4984 - val_accuracy: 0.7724 - val_loss: 0.4890
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7994 - loss: 0.4720 - val_accuracy: 0.7388 - val_loss: 0.5091
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7592 - loss: 0.5063 - val_accuracy: 0.7761 - val_loss: 0.5006
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7881 - loss: 0.4904 - val_accuracy: 0.7575 - val_loss: 0.4643
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4814 - val_accuracy: 0.7537 - val_loss: 0.4677
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4837 - val_accuracy: 0.7351 - val_loss: 0.5208
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5007 - val_accuracy: 0.7724 - val_loss: 0.4764
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7833 - loss: 0.5015 - val_accuracy: 0.7612 - val_loss: 0.4636
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.8026 - loss: 0.4726 - val_accuracy: 0.7761 - val_loss: 0.4719
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7737 - loss: 0.4950 - val_accuracy: 0.7649 - val_loss: 0.4643
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7881 - loss: 0.4844 - val_accuracy: 0.6642 - val_loss: 0.6559
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.8010 - loss: 0.4795 - val_accuracy: 0.7649 - val_loss: 0.4599
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7881 - loss: 0.4802 - val_accuracy: 0.7649 - val_loss: 0.4662
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7945 - loss: 0.4747 - val_accuracy: 0.7873 - val_loss: 0.5069
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7897 - loss: 0.4825 - val_accuracy: 0.7649 - val_loss: 0.4596
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7961 - loss: 0.4691 - val_accuracy: 0.7687 - val_loss: 0.4735
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8074 - loss: 0.4680 - val_accuracy: 0.7425 - val_loss: 0.5078
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8090 - loss: 0.4658 - val_accuracy: 0.7910 - val_loss: 0.4909
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7961 - loss: 0.4846 - val_accuracy: 0.7463 - val_loss: 0.5068
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7945 - loss: 0.4691 - val_accuracy: 0.7500 - val_loss: 0.5289
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7978 - loss: 0.4826 - val_accuracy: 0.7612 - val_loss: 0.4651
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7849 - loss: 0.4747 - val_accuracy: 0.7649 - val_loss: 0.4700
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8074 - loss: 0.4810 - val_accuracy: 0.7649 - val_loss: 0.4607
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.8122 - loss: 0.4506 - val_accuracy: 0.7575 - val_loss: 0.4831
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.8090 - loss: 0.4698 - val_accuracy: 0.7724 - val_loss: 0.4680
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4665 - val_accuracy: 0.7687 - val_loss: 0.4544
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.8010 - loss: 0.4825 - val_accuracy: 0.7649 - val_loss: 0.4744
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8042 - loss: 0.4718 - val_accuracy: 0.7687 - val_loss: 0.4737
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8010 - loss: 0.4613 - val_accuracy: 0.7463 - val_loss: 0.5522
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7994 - loss: 0.4742 - val_accuracy: 0.7612 - val_loss: 0.4630
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7897 - loss: 0.4900 - val_accuracy: 0.7687 - val_loss: 0.4672
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8074 - loss: 0.4602 - val_accuracy: 0.7575 - val_loss: 0.4610
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8010 - loss: 0.4671 - val_accuracy: 0.7687 - val_loss: 0.4600
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7978 - loss: 0.4633 - val_accuracy: 0.7425 - val_loss: 0.5237
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7945 - loss: 0.4681 - val_accuracy: 0.7836 - val_loss: 0.5639
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8010 - loss: 0.4679 - val_accuracy: 0.7836 - val_loss: 0.5546
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8122 - loss: 0.4575 - val_accuracy: 0.7500 - val_loss: 0.5167
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7945 - loss: 0.4803 - val_accuracy: 0.7836 - val_loss: 0.4787
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8042 - loss: 0.4569 - val_accuracy: 0.7799 - val_loss: 0.4889
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8074 - loss: 0.4630 - val_accuracy: 0.7873 - val_loss: 0.5044
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7978 - loss: 0.4596 - val_accuracy: 0.7612 - val_loss: 0.4609
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8058 - loss: 0.4720 - val_accuracy: 0.7687 - val_loss: 0.4627
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7945 - loss: 0.4578 - val_accuracy: 0.7649 - val_loss: 0.4726
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8026 - loss: 0.4493 - val_accuracy: 0.7687 - val_loss: 0.4573
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8090 - loss: 0.5105 - val_accuracy: 0.7575 - val_loss: 0.4717
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4596 - val_accuracy: 0.7612 - val_loss: 0.4605
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8090 - loss: 0.4609 - val_accuracy: 0.7575 - val_loss: 0.4656
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8106 - loss: 0.4576 - val_accuracy: 0.7836 - val_loss: 0.5040
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8074 - loss: 0.4521 - val_accuracy: 0.7836 - val_loss: 0.4772
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8058 - loss: 0.4741 - val_accuracy: 0.7612 - val_loss: 0.4591
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7994 - loss: 0.4610 - val_accuracy: 0.7836 - val_loss: 0.4796
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8042 - loss: 0.4543 - val_accuracy: 0.7649 - val_loss: 0.4809
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8074 - loss: 0.4563 - val_accuracy: 0.7724 - val_loss: 0.4716
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7865 - loss: 0.4640 - val_accuracy: 0.7537 - val_loss: 0.4966
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8074 - loss: 0.4476 - val_accuracy: 0.7537 - val_loss: 0.6051
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.8074 - loss: 0.4723 - val_accuracy: 0.7687 - val_loss: 0.4737
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8026 - loss: 0.4533 - val_accuracy: 0.7537 - val_loss: 0.5298
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7961 - loss: 0.4820 - val_accuracy: 0.7649 - val_loss: 0.4665
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8042 - loss: 0.4514 - val_accuracy: 0.7575 - val_loss: 0.5911
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.7913 - loss: 0.4581 - val_accuracy: 0.7687 - val_loss: 0.4647
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.8042 - loss: 0.4609 - val_accuracy: 0.7612 - val_loss: 0.4602
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8042 - loss: 0.4568 - val_accuracy: 0.7612 - val_loss: 0.4584
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4650 - val_accuracy: 0.7612 - val_loss: 0.4588
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8106 - loss: 0.4563 - val_accuracy: 0.7612 - val_loss: 0.5033
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7978 - loss: 0.4547 - val_accuracy: 0.7575 - val_loss: 0.4582
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7945 - loss: 0.4540 - val_accuracy: 0.7687 - val_loss: 0.4672
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8122 - loss: 0.4583 - val_accuracy: 0.7687 - val_loss: 0.4629
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8154 - loss: 0.4408 - val_accuracy: 0.7388 - val_loss: 0.5945
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7929 - loss: 0.4702 - val_accuracy: 0.7649 - val_loss: 0.4599
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8026 - loss: 0.4768 - val_accuracy: 0.7649 - val_loss: 0.4698
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8074 - loss: 0.4637 - val_accuracy: 0.7612 - val_loss: 0.4716
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.8026 - loss: 0.4558 - val_accuracy: 0.7836 - val_loss: 0.5194
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8058 - loss: 0.4509 - val_accuracy: 0.7910 - val_loss: 0.5002
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8058 - loss: 0.4611 - val_accuracy: 0.7687 - val_loss: 0.4658
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8010 - loss: 0.4601 - val_accuracy: 0.7687 - val_loss: 0.4671
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.8010 - loss: 0.4604 - val_accuracy: 0.7649 - val_loss: 0.4824
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8042 - loss: 0.4532 - val_accuracy: 0.7836 - val_loss: 0.4809
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8042 - loss: 0.4566 - val_accuracy: 0.7836 - val_loss: 0.5711
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8202 - loss: 0.4381 - val_accuracy: 0.7836 - val_loss: 0.4821
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4505 - val_accuracy: 0.7649 - val_loss: 0.4755
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7994 - loss: 0.4554 - val_accuracy: 0.7724 - val_loss: 0.4726
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8154 - loss: 0.4413 - val_accuracy: 0.7575 - val_loss: 0.4707
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8058 - loss: 0.4447 - val_accuracy: 0.7537 - val_loss: 0.5327
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.8202 - loss: 0.4423 - val_accuracy: 0.7910 - val_loss: 0.5192
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.8154 - loss: 0.4447 - val_accuracy: 0.7799 - val_loss: 0.4891
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8122 - loss: 0.4683 - val_accuracy: 0.7724 - val_loss: 0.4714
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.8042 - loss: 0.4520 - val_accuracy: 0.7649 - val_loss: 0.4742
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7865 - loss: 0.4557 - val_accuracy: 0.7687 - val_loss: 0.4702
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8138 - loss: 0.4542 - val_accuracy: 0.7164 - val_loss: 0.6381
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8026 - loss: 0.4570 - val_accuracy: 0.7276 - val_loss: 0.5667
Epoch 153/5000

wandb: Agent Starting Run: mklol2y9 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5730 - loss: 2.8067 - val_accuracy: 0.7052 - val_loss: 0.7107
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.7143 - val_accuracy: 0.6866 - val_loss: 0.6126
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6307 - val_accuracy: 0.6828 - val_loss: 0.6160
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6886 - loss: 0.6181 - val_accuracy: 0.6791 - val_loss: 0.6186
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6645 - loss: 0.6382 - val_accuracy: 0.6418 - val_loss: 0.6851
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6709 - loss: 0.6313 - val_accuracy: 0.7052 - val_loss: 0.6126
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5983 - val_accuracy: 0.6940 - val_loss: 0.6168
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5864 - val_accuracy: 0.6940 - val_loss: 0.5799
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.5732 - val_accuracy: 0.6754 - val_loss: 0.7151
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6806 - loss: 0.6698 - val_accuracy: 0.7052 - val_loss: 0.5800
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6998 - loss: 0.5633 - val_accuracy: 0.7164 - val_loss: 0.5798
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.7223 - loss: 0.5671 - val_accuracy: 0.7276 - val_loss: 0.5890
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7143 - loss: 0.5665 - val_accuracy: 0.7388 - val_loss: 0.5848
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.7111 - loss: 0.5710 - val_accuracy: 0.6978 - val_loss: 0.6292
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5677 - val_accuracy: 0.6754 - val_loss: 0.7110
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5292 - val_accuracy: 0.7276 - val_loss: 0.5399
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5136 - val_accuracy: 0.7313 - val_loss: 0.5368
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5553 - val_accuracy: 0.6978 - val_loss: 0.6558
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7047 - loss: 0.5966 - val_accuracy: 0.7276 - val_loss: 0.5639
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5214 - val_accuracy: 0.6828 - val_loss: 0.6953
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.7496 - loss: 0.5252 - val_accuracy: 0.7313 - val_loss: 0.5419
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.7352 - loss: 0.5431 - val_accuracy: 0.7351 - val_loss: 0.5339
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.4938 - val_accuracy: 0.7351 - val_loss: 0.5298
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7705 - loss: 0.4898 - val_accuracy: 0.7425 - val_loss: 0.5160
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.7817 - loss: 0.4795 - val_accuracy: 0.7164 - val_loss: 0.5671
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7737 - loss: 0.4802 - val_accuracy: 0.7500 - val_loss: 0.5194
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7769 - loss: 0.4800 - val_accuracy: 0.7500 - val_loss: 0.5117
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4943 - val_accuracy: 0.7500 - val_loss: 0.5255
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7560 - loss: 0.5088 - val_accuracy: 0.7425 - val_loss: 0.5221
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7480 - loss: 0.5301 - val_accuracy: 0.6791 - val_loss: 0.7902
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4846 - val_accuracy: 0.7351 - val_loss: 0.5332
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7994 - loss: 0.4662 - val_accuracy: 0.7612 - val_loss: 0.4991
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7994 - loss: 0.4738 - val_accuracy: 0.7313 - val_loss: 0.5742
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8010 - loss: 0.4927 - val_accuracy: 0.7388 - val_loss: 0.5343
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7785 - loss: 0.4824 - val_accuracy: 0.7761 - val_loss: 0.5106
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7929 - loss: 0.4669 - val_accuracy: 0.7724 - val_loss: 0.4971
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4744 - val_accuracy: 0.7687 - val_loss: 0.4997
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.7897 - loss: 0.4668 - val_accuracy: 0.7649 - val_loss: 0.4970
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7978 - loss: 0.4492 - val_accuracy: 0.7575 - val_loss: 0.4998
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7849 - loss: 0.4727 - val_accuracy: 0.7761 - val_loss: 0.5297
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7881 - loss: 0.5024 - val_accuracy: 0.7761 - val_loss: 0.4989
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7929 - loss: 0.4620 - val_accuracy: 0.7276 - val_loss: 0.6221
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7753 - loss: 0.4768 - val_accuracy: 0.7761 - val_loss: 0.5072
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7496 - loss: 0.5616 - val_accuracy: 0.7687 - val_loss: 0.4945
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.8010 - loss: 0.4594 - val_accuracy: 0.6045 - val_loss: 0.7410
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7721 - loss: 0.4849 - val_accuracy: 0.7761 - val_loss: 0.4874
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8010 - loss: 0.4624 - val_accuracy: 0.7836 - val_loss: 0.4902
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8026 - loss: 0.4519 - val_accuracy: 0.7687 - val_loss: 0.4945
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8122 - loss: 0.4352 - val_accuracy: 0.7425 - val_loss: 0.5352
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8010 - loss: 0.4677 - val_accuracy: 0.7836 - val_loss: 0.5115
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4585 - val_accuracy: 0.7724 - val_loss: 0.4981
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8186 - loss: 0.4485 - val_accuracy: 0.7761 - val_loss: 0.4906
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.8154 - loss: 0.4388 - val_accuracy: 0.7836 - val_loss: 0.4971
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7978 - loss: 0.4939 - val_accuracy: 0.5373 - val_loss: 0.8975
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7833 - loss: 0.4991 - val_accuracy: 0.7873 - val_loss: 0.5413
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7833 - loss: 0.4974 - val_accuracy: 0.7761 - val_loss: 0.4890
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8122 - loss: 0.4349 - val_accuracy: 0.7724 - val_loss: 0.4853
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7994 - loss: 0.4590 - val_accuracy: 0.7761 - val_loss: 0.4863
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4393 - val_accuracy: 0.7873 - val_loss: 0.5383
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.8042 - loss: 0.4527 - val_accuracy: 0.7836 - val_loss: 0.4863
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8154 - loss: 0.4258 - val_accuracy: 0.7612 - val_loss: 0.5107
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8026 - loss: 0.4433 - val_accuracy: 0.7761 - val_loss: 0.4918
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.8170 - loss: 0.4397 - val_accuracy: 0.7761 - val_loss: 0.5231
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.8138 - loss: 0.4376 - val_accuracy: 0.7761 - val_loss: 0.4941
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8090 - loss: 0.4315 - val_accuracy: 0.7948 - val_loss: 0.5319
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.8154 - loss: 0.4297 - val_accuracy: 0.7799 - val_loss: 0.5183
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8122 - loss: 0.4405 - val_accuracy: 0.7463 - val_loss: 0.5588
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8250 - loss: 0.4342 - val_accuracy: 0.7761 - val_loss: 0.4877
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7961 - loss: 0.4707 - val_accuracy: 0.7761 - val_loss: 0.5060
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8106 - loss: 0.4590 - val_accuracy: 0.7836 - val_loss: 0.5134
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8138 - loss: 0.4333 - val_accuracy: 0.7836 - val_loss: 0.4922
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8090 - loss: 0.4427 - val_accuracy: 0.7687 - val_loss: 0.5083
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.8058 - loss: 0.4573 - val_accuracy: 0.7761 - val_loss: 0.4916
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7673 - loss: 0.5444 - val_accuracy: 0.7649 - val_loss: 0.5013
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8042 - loss: 0.4678 - val_accuracy: 0.7948 - val_loss: 0.5357
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4215 - val_accuracy: 0.7836 - val_loss: 0.4896
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8042 - loss: 0.4349 - val_accuracy: 0.7463 - val_loss: 0.5456
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.8106 - loss: 0.4745 - val_accuracy: 0.7425 - val_loss: 0.5681
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7721 - loss: 0.5114 - val_accuracy: 0.7425 - val_loss: 0.6182
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7817 - loss: 0.5045 - val_accuracy: 0.7463 - val_loss: 0.5627
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8074 - loss: 0.4373 - val_accuracy: 0.7537 - val_loss: 0.5606
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7881 - loss: 0.4795 - val_accuracy: 0.7687 - val_loss: 0.5106
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4394 - val_accuracy: 0.7537 - val_loss: 0.5334
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8074 - loss: 0.4577 - val_accuracy: 0.7687 - val_loss: 0.4952
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7657 - loss: 0.5469 - val_accuracy: 0.7351 - val_loss: 0.6684
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8154 - loss: 0.4508 - val_accuracy: 0.7575 - val_loss: 0.5493
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.8202 - loss: 0.4572 - val_accuracy: 0.7985 - val_loss: 0.5105
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7929 - loss: 0.4845 - val_accuracy: 0.7388 - val_loss: 0.5751
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8106 - loss: 0.4365 - val_accuracy: 0.7761 - val_loss: 0.4938
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8122 - loss: 0.4418 - val_accuracy: 0.7873 - val_loss: 0.5630
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8202 - loss: 0.4304 - val_accuracy: 0.7985 - val_loss: 0.5280
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8170 - loss: 0.4305 - val_accuracy: 0.7836 - val_loss: 0.5017
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8202 - loss: 0.4197 - val_accuracy: 0.7948 - val_loss: 0.5599
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.8186 - loss: 0.4453 - val_accuracy: 0.7799 - val_loss: 0.5001
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8154 - loss: 0.4455 - val_accuracy: 0.7799 - val_loss: 0.4968
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8106 - loss: 0.4277 - val_accuracy: 0.7948 - val_loss: 0.5572
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7994 - loss: 0.4746 - val_accuracy: 0.7425 - val_loss: 0.6420
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8026 - loss: 0.4576 - val_accuracy: 0.7873 - val_loss: 0.4879
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7994 - loss: 0.4557 - val_accuracy: 0.7985 - val_loss: 0.5234
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8106 - loss: 0.4422 - val_accuracy: 0.7799 - val_loss: 0.5039
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4297 - val_accuracy: 0.7724 - val_loss: 0.5084
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4474 - val_accuracy: 0.7873 - val_loss: 0.4965
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7785 - loss: 0.4955 - val_accuracy: 0.7463 - val_loss: 0.5935
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8202 - loss: 0.4322 - val_accuracy: 0.7948 - val_loss: 0.5785
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8202 - loss: 0.4353 - val_accuracy: 0.7948 - val_loss: 0.5416
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7801 - loss: 0.4987 - val_accuracy: 0.7537 - val_loss: 0.5447
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7994 - loss: 0.4623 - val_accuracy: 0.7761 - val_loss: 0.5182
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.8090 - loss: 0.4515 - val_accuracy: 0.7761 - val_loss: 0.5003
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8154 - loss: 0.4200 - val_accuracy: 0.7948 - val_loss: 0.5192
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.8106 - loss: 0.4532 - val_accuracy: 0.7761 - val_loss: 0.5097
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.7929 - loss: 0.4799 - val_accuracy: 0.7687 - val_loss: 0.6191
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7865 - loss: 0.4707 - val_accuracy: 0.7612 - val_loss: 0.5488
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8106 - loss: 0.4282 - val_accuracy: 0.7799 - val_loss: 0.5258
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8250 - loss: 0.4334 - val_accuracy: 0.7799 - val_loss: 0.4940
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8234 - loss: 0.4084 - val_accuracy: 0.7836 - val_loss: 0.5049
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4375 - val_accuracy: 0.7724 - val_loss: 0.5073
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8266 - loss: 0.4149 - val_accuracy: 0.7761 - val_loss: 0.5078
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8090 - loss: 0.4393 - val_accuracy: 0.7724 - val_loss: 0.5003
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8058 - loss: 0.4509 - val_accuracy: 0.6604 - val_loss: 0.7432
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7994 - loss: 0.4538 - val_accuracy: 0.7799 - val_loss: 0.5060
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8138 - loss: 0.4496 - val_accuracy: 0.7761 - val_loss: 0.5028
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8202 - loss: 0.4470 - val_accuracy: 0.7463 - val_loss: 0.6160
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8058 - loss: 0.4389 - val_accuracy: 0.7537 - val_loss: 0.5467
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8234 - loss: 0.4381 - val_accuracy: 0.7575 - val_loss: 0.5297
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.8042 - loss: 0.4221 - val_accuracy: 0.7948 - val_loss: 0.5221
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7978 - loss: 0.4761 - val_accuracy: 0.7873 - val_loss: 0.4952
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8202 - loss: 0.4373 - val_accuracy: 0.7761 - val_loss: 0.5010
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8218 - loss: 0.4108 - val_accuracy: 0.7836 - val_loss: 0.5068
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7978 - loss: 0.4334 - val_accuracy: 0.7761 - val_loss: 0.5118
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8058 - loss: 0.4431 - val_accuracy: 0.7873 - val_loss: 0.4967
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.8010 - loss: 0.4273 - val_accuracy: 0.7500 - val_loss: 0.5964
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.8218 - loss: 0.4332 - val_accuracy: 0.7910 - val_loss: 0.5390
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4528 - val_accuracy: 0.7537 - val_loss: 0.5733
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8234 - loss: 0.4248 - val_accuracy: 0.7724 - val_loss: 0.5193
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8010 - loss: 0.4461 - val_accuracy: 0.7164 - val_loss: 0.6598
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7929 - loss: 0.4792 - val_accuracy: 0.7799 - val_loss: 0.4979
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8106 - loss: 0.4233 - val_accuracy: 0.7836 - val_loss: 0.5251
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8106 - loss: 0.4403 - val_accuracy: 0.7799 - val_loss: 0.5144
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8154 - loss: 0.4481 - val_accuracy: 0.7873 - val_loss: 0.5010
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8186 - loss: 0.4496 - val_accuracy: 0.7687 - val_loss: 0.5726
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8186 - loss: 0.4238 - val_accuracy: 0.7761 - val_loss: 0.5458
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.8106 - loss: 0.4437 - val_accuracy: 0.7836 - val_loss: 0.5312
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.8170 - loss: 0.4295 - val_accuracy: 0.7724 - val_loss: 0.5385
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8170 - loss: 0.4749 - val_accuracy: 0.7910 - val_loss: 0.6034
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8154 - loss: 0.4385 - val_accuracy: 0.7313 - val_loss: 0.6820
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8074 - loss: 0.4590 - val_accuracy: 0.7724 - val_loss: 0.5293
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8234 - loss: 0.4270 - val_accuracy: 0.7799 - val_loss: 0.5323
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8218 - loss: 0.4634 - val_accuracy: 0.7575 - val_loss: 0.5671
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8218 - loss: 0.4095 - val_accuracy: 0.7724 - val_loss: 0.5349
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8218 - loss: 0.4214 - val_accuracy: 0.7910 - val_loss: 0.5924
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8202 - loss: 0.4206 - val_accuracy: 0.7761 - val_loss: 0.5383
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8234 - loss: 0.4146 - val_accuracy: 0.7724 - val_loss: 0.5296
Epoch 153/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: o1qdn7ri with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 4.5363 - val_accuracy: 0.6269 - val_loss: 0.7237
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6968 - val_accuracy: 0.6306 - val_loss: 0.6803
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6116 - loss: 0.6880 - val_accuracy: 0.6231 - val_loss: 0.6853
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6148 - loss: 0.6833 - val_accuracy: 0.6306 - val_loss: 0.6695
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6116 - loss: 0.6799 - val_accuracy: 0.6231 - val_loss: 0.6741
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6083 - loss: 0.6778 - val_accuracy: 0.6269 - val_loss: 0.6835
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6148 - loss: 0.6731 - val_accuracy: 0.6306 - val_loss: 0.6628
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6132 - loss: 0.6744 - val_accuracy: 0.6306 - val_loss: 0.6607
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6132 - loss: 0.6712 - val_accuracy: 0.6343 - val_loss: 0.6599
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6698 - val_accuracy: 0.6343 - val_loss: 0.6590
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6688 - val_accuracy: 0.6343 - val_loss: 0.6584
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.6164 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6763
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6573
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6343 - val_loss: 0.6572
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6727
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6608
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6613
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6605
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.6720
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6606
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6719
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.6745
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6744
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6164 - loss: 0.6635 - val_accuracy: 0.6306 - val_loss: 0.6759
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6164 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6641
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6164 - loss: 0.6635 - val_accuracy: 0.6269 - val_loss: 0.6716
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6748
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6686
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6749
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6695
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6196 - loss: 0.6634 - val_accuracy: 0.6269 - val_loss: 0.6703
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6803
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6654
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6788
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6164 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6696
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6180 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6773
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6269 - val_loss: 0.6693
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.6821
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6658
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6196 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6794
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6826
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6180 - loss: 0.6627 - val_accuracy: 0.6269 - val_loss: 0.6803
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6269 - val_loss: 0.6722
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6269 - val_loss: 0.6816
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6269 - val_loss: 0.6820
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6718
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6269 - val_loss: 0.6746
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6801
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6734
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6180 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6798
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6180 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6792
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6805
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6741
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6753
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6775
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6765
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6823
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6834
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6180 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6825
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6269 - val_loss: 0.6806
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.6759
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6756
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6269 - val_loss: 0.6834
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6811
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6845
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6790
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.6777
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6827
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6811
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6771
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.6802
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6786
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6766
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6794
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6827
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6858
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6823
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6867
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6269 - val_loss: 0.6877
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6819
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6843
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6807
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6822
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6852
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6892
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6837
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6850
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6899
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6269 - val_loss: 0.6856
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6269 - val_loss: 0.6952
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6196 - loss: 0.6613 - val_accuracy: 0.6269 - val_loss: 0.6852
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6196 - loss: 0.6613 - val_accuracy: 0.6269 - val_loss: 0.6928
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6841
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6869
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6269 - val_loss: 0.6904
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6915
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6913
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6894
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6950
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.6947
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6880
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6196 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6933
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.6890
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6180 - loss: 0.6609 - val_accuracy: 0.6269 - val_loss: 0.6894
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6196 - loss: 0.6609 - val_accuracy: 0.6269 - val_loss: 0.6949
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.6887
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6959
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6864
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6953
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6876
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6609 - val_accuracy: 0.6269 - val_loss: 0.6941
Epoch 114: early stopping

wandb: Agent Starting Run: 1bov480g with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 29.5169 - val_accuracy: 0.6343 - val_loss: 8.8240
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 2.4076 - val_accuracy: 0.5597 - val_loss: 1.6168
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 1.3572 - val_accuracy: 0.7164 - val_loss: 1.0354
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6212 - loss: 1.1614 - val_accuracy: 0.6828 - val_loss: 1.0623
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 1.1323 - val_accuracy: 0.4142 - val_loss: 1.0130
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.9845 - val_accuracy: 0.4142 - val_loss: 1.1065
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6324 - loss: 0.9991 - val_accuracy: 0.7052 - val_loss: 0.8954
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.9365 - val_accuracy: 0.5075 - val_loss: 0.8259
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.9040 - val_accuracy: 0.6978 - val_loss: 0.7722
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.8893 - val_accuracy: 0.4590 - val_loss: 1.1101
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6998 - loss: 0.8176 - val_accuracy: 0.7015 - val_loss: 0.7923
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6790 - loss: 0.8570 - val_accuracy: 0.7127 - val_loss: 0.5955
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6629 - loss: 0.8650 - val_accuracy: 0.6381 - val_loss: 1.1602
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6645 - loss: 0.8135 - val_accuracy: 0.6381 - val_loss: 1.2221
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6661 - loss: 0.8176 - val_accuracy: 0.7500 - val_loss: 0.5725
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6870 - loss: 0.7729 - val_accuracy: 0.7052 - val_loss: 0.5680
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6822 - loss: 0.7956 - val_accuracy: 0.6045 - val_loss: 0.7575
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6581 - loss: 0.7892 - val_accuracy: 0.6716 - val_loss: 0.7320
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6838 - loss: 0.7423 - val_accuracy: 0.7500 - val_loss: 0.5331
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.6854 - loss: 0.7468 - val_accuracy: 0.7649 - val_loss: 0.5390
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7111 - loss: 0.7066 - val_accuracy: 0.4590 - val_loss: 1.1109
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6629 - loss: 0.7568 - val_accuracy: 0.6604 - val_loss: 0.7724
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7030 - loss: 0.7235 - val_accuracy: 0.4403 - val_loss: 1.3465
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6886 - loss: 0.7300 - val_accuracy: 0.6978 - val_loss: 0.5448
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7014 - loss: 0.7476 - val_accuracy: 0.6194 - val_loss: 1.1471
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6870 - loss: 0.7343 - val_accuracy: 0.7649 - val_loss: 0.5317
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6934 - loss: 0.6858 - val_accuracy: 0.6418 - val_loss: 0.9134
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7159 - loss: 0.6882 - val_accuracy: 0.7351 - val_loss: 0.5342
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7175 - loss: 0.6758 - val_accuracy: 0.7575 - val_loss: 0.5029
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.7111 - loss: 0.6888 - val_accuracy: 0.7313 - val_loss: 0.5529
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.6643 - val_accuracy: 0.6343 - val_loss: 0.9953
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7287 - loss: 0.6455 - val_accuracy: 0.5522 - val_loss: 0.8355
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6630 - val_accuracy: 0.7239 - val_loss: 0.5152
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6184 - val_accuracy: 0.7463 - val_loss: 0.5051
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7480 - loss: 0.6159 - val_accuracy: 0.4403 - val_loss: 1.8295
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.7191 - loss: 0.6589 - val_accuracy: 0.5709 - val_loss: 0.8301
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7271 - loss: 0.6556 - val_accuracy: 0.7052 - val_loss: 0.6043
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6753 - val_accuracy: 0.7201 - val_loss: 0.5258
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7271 - loss: 0.6240 - val_accuracy: 0.7090 - val_loss: 0.6748
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7207 - loss: 0.6529 - val_accuracy: 0.4776 - val_loss: 1.0628
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7303 - loss: 0.5928 - val_accuracy: 0.6418 - val_loss: 0.9967
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7480 - loss: 0.6469 - val_accuracy: 0.7276 - val_loss: 0.5452
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7191 - loss: 0.6976 - val_accuracy: 0.7276 - val_loss: 0.6357
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6687 - val_accuracy: 0.7537 - val_loss: 0.6018
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.7191 - loss: 0.6773 - val_accuracy: 0.7687 - val_loss: 0.4897
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6438 - val_accuracy: 0.7724 - val_loss: 0.5835
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7528 - loss: 0.5745 - val_accuracy: 0.6194 - val_loss: 1.3521
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7432 - loss: 0.6379 - val_accuracy: 0.7388 - val_loss: 0.5718
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6335 - val_accuracy: 0.4888 - val_loss: 1.0855
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7352 - loss: 0.6566 - val_accuracy: 0.7612 - val_loss: 0.4847
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5921 - val_accuracy: 0.7313 - val_loss: 0.6152
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7464 - loss: 0.6382 - val_accuracy: 0.7313 - val_loss: 0.6333
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6357 - val_accuracy: 0.7276 - val_loss: 0.5394
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7448 - loss: 0.5972 - val_accuracy: 0.7313 - val_loss: 0.5515
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.7368 - loss: 0.6176 - val_accuracy: 0.7649 - val_loss: 0.4694
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7464 - loss: 0.5960 - val_accuracy: 0.5112 - val_loss: 1.0275
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7335 - loss: 0.6316 - val_accuracy: 0.6754 - val_loss: 0.6678
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6189 - val_accuracy: 0.7351 - val_loss: 0.6647
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7496 - loss: 0.6257 - val_accuracy: 0.7724 - val_loss: 0.4738
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7432 - loss: 0.5857 - val_accuracy: 0.7276 - val_loss: 0.6468
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.7271 - loss: 0.6027 - val_accuracy: 0.7799 - val_loss: 0.5654
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7464 - loss: 0.6347 - val_accuracy: 0.7201 - val_loss: 0.7225
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7448 - loss: 0.5981 - val_accuracy: 0.7239 - val_loss: 0.5457
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7335 - loss: 0.6149 - val_accuracy: 0.7649 - val_loss: 0.4728
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7464 - loss: 0.6060 - val_accuracy: 0.7537 - val_loss: 0.4724
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7496 - loss: 0.5882 - val_accuracy: 0.7836 - val_loss: 0.4833
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7448 - loss: 0.5798 - val_accuracy: 0.6754 - val_loss: 0.8405
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7335 - loss: 0.6182 - val_accuracy: 0.7724 - val_loss: 0.4654
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7592 - loss: 0.6218 - val_accuracy: 0.7687 - val_loss: 0.4736
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7769 - loss: 0.5948 - val_accuracy: 0.6530 - val_loss: 0.9925
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7496 - loss: 0.5648 - val_accuracy: 0.7425 - val_loss: 0.5181
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6314 - val_accuracy: 0.7425 - val_loss: 0.5881
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 981us/step - accuracy: 0.7368 - loss: 0.5996 - val_accuracy: 0.7687 - val_loss: 0.4998
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7496 - loss: 0.5884 - val_accuracy: 0.7351 - val_loss: 0.6062
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7769 - loss: 0.5999 - val_accuracy: 0.6530 - val_loss: 0.9808
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7801 - loss: 0.5759 - val_accuracy: 0.7687 - val_loss: 0.4702
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7897 - loss: 0.5487 - val_accuracy: 0.6940 - val_loss: 0.7644
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7416 - loss: 0.5917 - val_accuracy: 0.6716 - val_loss: 0.6936
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7849 - loss: 0.5340 - val_accuracy: 0.7649 - val_loss: 0.4716
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7608 - loss: 0.6020 - val_accuracy: 0.5485 - val_loss: 0.9383
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.7640 - loss: 0.5910 - val_accuracy: 0.7687 - val_loss: 0.4707
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7817 - loss: 0.5573 - val_accuracy: 0.6940 - val_loss: 0.6617
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7560 - loss: 0.5803 - val_accuracy: 0.6418 - val_loss: 1.1566
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7592 - loss: 0.5670 - val_accuracy: 0.7500 - val_loss: 0.6224
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7753 - loss: 0.5791 - val_accuracy: 0.7799 - val_loss: 0.5360
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.7624 - loss: 0.6145 - val_accuracy: 0.7761 - val_loss: 0.5558
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7464 - loss: 0.5610 - val_accuracy: 0.7724 - val_loss: 0.4803
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7737 - loss: 0.5660 - val_accuracy: 0.7313 - val_loss: 0.6433
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.7528 - loss: 0.6116 - val_accuracy: 0.7612 - val_loss: 0.5366
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7592 - loss: 0.5786 - val_accuracy: 0.7313 - val_loss: 0.6160
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7689 - loss: 0.5697 - val_accuracy: 0.7575 - val_loss: 0.5868
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7608 - loss: 0.5813 - val_accuracy: 0.6716 - val_loss: 0.7062
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5491 - val_accuracy: 0.5000 - val_loss: 1.2381
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.7753 - loss: 0.6123 - val_accuracy: 0.6642 - val_loss: 0.7302
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7608 - loss: 0.5936 - val_accuracy: 0.6978 - val_loss: 0.8742
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7673 - loss: 0.5768 - val_accuracy: 0.5448 - val_loss: 0.9912
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7448 - loss: 0.6121 - val_accuracy: 0.7351 - val_loss: 0.6412
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7737 - loss: 0.5637 - val_accuracy: 0.7836 - val_loss: 0.4983
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7657 - loss: 0.5959 - val_accuracy: 0.7537 - val_loss: 0.5151
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7705 - loss: 0.5743 - val_accuracy: 0.5149 - val_loss: 1.1590
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7881 - loss: 0.5501 - val_accuracy: 0.7687 - val_loss: 0.4821
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7496 - loss: 0.6190 - val_accuracy: 0.7164 - val_loss: 0.6512
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7496 - loss: 0.5916 - val_accuracy: 0.7687 - val_loss: 0.4819
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.7528 - loss: 0.5868 - val_accuracy: 0.6381 - val_loss: 0.7556
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7480 - loss: 0.5925 - val_accuracy: 0.5634 - val_loss: 0.9640
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7737 - loss: 0.5862 - val_accuracy: 0.7575 - val_loss: 0.5159
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7608 - loss: 0.5619 - val_accuracy: 0.7761 - val_loss: 0.5550
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7769 - loss: 0.5312 - val_accuracy: 0.6269 - val_loss: 0.8046
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.7657 - loss: 0.5756 - val_accuracy: 0.5896 - val_loss: 0.9227
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7705 - loss: 0.5785 - val_accuracy: 0.7388 - val_loss: 0.6768
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5639 - val_accuracy: 0.7799 - val_loss: 0.4869
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5542 - val_accuracy: 0.6866 - val_loss: 0.7075
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7705 - loss: 0.6068 - val_accuracy: 0.7799 - val_loss: 0.5009
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8010 - loss: 0.4882 - val_accuracy: 0.7724 - val_loss: 0.4900
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7705 - loss: 0.5798 - val_accuracy: 0.7724 - val_loss: 0.4926
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7785 - loss: 0.5713 - val_accuracy: 0.7687 - val_loss: 0.4962
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7865 - loss: 0.5536 - val_accuracy: 0.7687 - val_loss: 0.5071
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7640 - loss: 0.5628 - val_accuracy: 0.7761 - val_loss: 0.4876
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7849 - loss: 0.5571 - val_accuracy: 0.7239 - val_loss: 0.7533
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7689 - loss: 0.5700 - val_accuracy: 0.6679 - val_loss: 0.8707
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7560 - loss: 0.5764 - val_accuracy: 0.7388 - val_loss: 0.6771
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7737 - loss: 0.5375 - val_accuracy: 0.7388 - val_loss: 0.6136
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7640 - loss: 0.5760 - val_accuracy: 0.7761 - val_loss: 0.4865
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7913 - loss: 0.5333 - val_accuracy: 0.7201 - val_loss: 0.6797
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7640 - loss: 0.5811 - val_accuracy: 0.7724 - val_loss: 0.5237
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7769 - loss: 0.5137 - val_accuracy: 0.7761 - val_loss: 0.5230
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.5074 - val_accuracy: 0.7799 - val_loss: 0.5560
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.7624 - loss: 0.5786 - val_accuracy: 0.7836 - val_loss: 0.5336
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7785 - loss: 0.5378 - val_accuracy: 0.7649 - val_loss: 0.4967
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7657 - loss: 0.5137 - val_accuracy: 0.7724 - val_loss: 0.4943
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7817 - loss: 0.5475 - val_accuracy: 0.7649 - val_loss: 0.5052
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7849 - loss: 0.5145 - val_accuracy: 0.7724 - val_loss: 0.5157
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.7801 - loss: 0.5714 - val_accuracy: 0.6903 - val_loss: 0.7081
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7673 - loss: 0.5510 - val_accuracy: 0.7761 - val_loss: 0.4848
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7881 - loss: 0.5201 - val_accuracy: 0.6978 - val_loss: 0.8350
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7865 - loss: 0.5624 - val_accuracy: 0.7612 - val_loss: 0.5891
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7737 - loss: 0.5340 - val_accuracy: 0.7127 - val_loss: 0.8020
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7849 - loss: 0.5450 - val_accuracy: 0.7090 - val_loss: 0.7921
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7753 - loss: 0.5441 - val_accuracy: 0.7612 - val_loss: 0.5258
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7753 - loss: 0.5303 - val_accuracy: 0.7537 - val_loss: 0.6144
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7833 - loss: 0.5273 - val_accuracy: 0.7201 - val_loss: 0.6531
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.7961 - loss: 0.5296 - val_accuracy: 0.7575 - val_loss: 0.4984
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5435 - val_accuracy: 0.7164 - val_loss: 0.7664
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7817 - loss: 0.5592 - val_accuracy: 0.6903 - val_loss: 0.8730
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7640 - loss: 0.5362 - val_accuracy: 0.7649 - val_loss: 0.4978
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7881 - loss: 0.5170 - val_accuracy: 0.7799 - val_loss: 0.4893
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7560 - loss: 0.5655 - val_accuracy: 0.7575 - val_loss: 0.5517
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7994 - loss: 0.4833 - val_accuracy: 0.6381 - val_loss: 0.7990
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7833 - loss: 0.5152 - val_accuracy: 0.7724 - val_loss: 0.4917
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7801 - loss: 0.5464 - val_accuracy: 0.7799 - val_loss: 0.4909
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7945 - loss: 0.5105 - val_accuracy: 0.7761 - val_loss: 0.5265
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7769 - loss: 0.5462 - val_accuracy: 0.7761 - val_loss: 0.4923
Epoch 153/5000

wandb: Agent Starting Run: r58skc4s with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5088 - loss: 4.7827 - val_accuracy: 0.4888 - val_loss: 2.8714
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5570 - loss: 2.5445 - val_accuracy: 0.4925 - val_loss: 2.2855
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5281 - loss: 1.3579 - val_accuracy: 0.5410 - val_loss: 1.2808
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.5682 - loss: 1.0161 - val_accuracy: 0.6269 - val_loss: 1.0418
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 0.8230 - val_accuracy: 0.6530 - val_loss: 0.8987
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6116 - loss: 0.7447 - val_accuracy: 0.6418 - val_loss: 0.9018
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5827 - loss: 0.7686 - val_accuracy: 0.6493 - val_loss: 0.7891
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6421 - loss: 0.7235 - val_accuracy: 0.6604 - val_loss: 0.8233
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.6989 - val_accuracy: 0.5821 - val_loss: 0.7480
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.5666 - loss: 0.8286 - val_accuracy: 0.6455 - val_loss: 1.0914
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6196 - loss: 0.7235 - val_accuracy: 0.6716 - val_loss: 0.6970
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6437 - loss: 0.6654 - val_accuracy: 0.7052 - val_loss: 0.6329
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.6816 - val_accuracy: 0.7052 - val_loss: 0.6192
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.6276 - loss: 0.8906 - val_accuracy: 0.6418 - val_loss: 1.1142
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6116 - loss: 0.8152 - val_accuracy: 0.7090 - val_loss: 0.6169
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6672 - val_accuracy: 0.6903 - val_loss: 0.6105
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6485 - loss: 0.6761 - val_accuracy: 0.6978 - val_loss: 0.6179
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6391 - val_accuracy: 0.6455 - val_loss: 0.8246
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.6777 - val_accuracy: 0.6940 - val_loss: 0.6434
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6351 - val_accuracy: 0.4813 - val_loss: 0.9446
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.7589 - val_accuracy: 0.4851 - val_loss: 0.9285
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6388 - loss: 0.7074 - val_accuracy: 0.6679 - val_loss: 0.6698
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6677 - loss: 0.6255 - val_accuracy: 0.6754 - val_loss: 0.6476
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6533 - loss: 0.6385 - val_accuracy: 0.7313 - val_loss: 0.6315
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6629 - loss: 0.6107 - val_accuracy: 0.6679 - val_loss: 0.6650
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6934 - loss: 0.6167 - val_accuracy: 0.7276 - val_loss: 0.6203
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6180 - loss: 0.7187 - val_accuracy: 0.7127 - val_loss: 0.6463
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6485 - loss: 0.6680 - val_accuracy: 0.6716 - val_loss: 0.6705
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6902 - loss: 0.6332 - val_accuracy: 0.6604 - val_loss: 0.7530
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6726 - loss: 0.6643 - val_accuracy: 0.7127 - val_loss: 0.6235
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6581 - loss: 0.6555 - val_accuracy: 0.4291 - val_loss: 1.2991
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.5987 - loss: 0.8982 - val_accuracy: 0.4963 - val_loss: 0.9028
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6276 - loss: 0.7940 - val_accuracy: 0.7351 - val_loss: 0.6133
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6902 - loss: 0.6225 - val_accuracy: 0.5784 - val_loss: 0.7503
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6822 - loss: 0.6321 - val_accuracy: 0.7164 - val_loss: 0.6171
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6709 - loss: 0.6612 - val_accuracy: 0.7313 - val_loss: 0.6075
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7143 - loss: 0.5682 - val_accuracy: 0.7537 - val_loss: 0.6401
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6902 - loss: 0.6346 - val_accuracy: 0.7201 - val_loss: 0.6015
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6982 - loss: 0.5894 - val_accuracy: 0.6604 - val_loss: 0.9191
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6902 - loss: 0.6335 - val_accuracy: 0.7164 - val_loss: 0.6041
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6950 - loss: 0.6115 - val_accuracy: 0.6828 - val_loss: 0.6420
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5679 - val_accuracy: 0.7463 - val_loss: 0.6099
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5833 - val_accuracy: 0.7649 - val_loss: 0.6376
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6677 - loss: 0.6337 - val_accuracy: 0.7463 - val_loss: 0.5995
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7303 - loss: 0.5621 - val_accuracy: 0.7575 - val_loss: 0.5963
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7271 - loss: 0.5510 - val_accuracy: 0.7276 - val_loss: 0.5976
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6581 - loss: 0.6840 - val_accuracy: 0.6679 - val_loss: 0.7419
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6838 - loss: 0.5817 - val_accuracy: 0.7537 - val_loss: 0.6289
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6645 - loss: 0.6888 - val_accuracy: 0.6866 - val_loss: 0.6417
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7368 - loss: 0.5612 - val_accuracy: 0.6866 - val_loss: 0.6299
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7255 - loss: 0.5610 - val_accuracy: 0.7612 - val_loss: 0.5951
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7335 - loss: 0.5518 - val_accuracy: 0.7724 - val_loss: 0.6071
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7319 - loss: 0.5411 - val_accuracy: 0.6903 - val_loss: 0.6229
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7287 - loss: 0.5654 - val_accuracy: 0.7724 - val_loss: 0.6168
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7528 - loss: 0.5407 - val_accuracy: 0.7724 - val_loss: 0.5954
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7592 - loss: 0.5325 - val_accuracy: 0.6269 - val_loss: 0.7297
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7223 - loss: 0.5693 - val_accuracy: 0.7724 - val_loss: 0.6095
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7560 - loss: 0.5360 - val_accuracy: 0.7201 - val_loss: 0.6087
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7528 - loss: 0.5280 - val_accuracy: 0.7201 - val_loss: 0.6116
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7384 - loss: 0.5583 - val_accuracy: 0.7761 - val_loss: 0.6162
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5701 - val_accuracy: 0.7687 - val_loss: 0.5921
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6950 - loss: 0.6182 - val_accuracy: 0.6828 - val_loss: 0.6807
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7416 - loss: 0.5405 - val_accuracy: 0.7724 - val_loss: 0.5905
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7576 - loss: 0.5452 - val_accuracy: 0.7388 - val_loss: 0.5955
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7624 - loss: 0.5123 - val_accuracy: 0.7612 - val_loss: 0.5893
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.7560 - loss: 0.5363 - val_accuracy: 0.7313 - val_loss: 0.6053
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.7368 - loss: 0.5819 - val_accuracy: 0.6791 - val_loss: 0.7128
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7544 - loss: 0.5174 - val_accuracy: 0.7463 - val_loss: 0.6076
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7753 - loss: 0.5321 - val_accuracy: 0.5224 - val_loss: 0.9117
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6539 - val_accuracy: 0.7687 - val_loss: 0.5831
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7705 - loss: 0.5190 - val_accuracy: 0.6754 - val_loss: 0.6959
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7945 - loss: 0.4930 - val_accuracy: 0.7649 - val_loss: 0.5913
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7929 - loss: 0.4923 - val_accuracy: 0.7687 - val_loss: 0.6354
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7608 - loss: 0.5285 - val_accuracy: 0.6754 - val_loss: 0.7743
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7673 - loss: 0.5145 - val_accuracy: 0.7649 - val_loss: 0.5927
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7528 - loss: 0.5288 - val_accuracy: 0.6642 - val_loss: 0.7044
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.7689 - loss: 0.5024 - val_accuracy: 0.7687 - val_loss: 0.5907
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7560 - loss: 0.5167 - val_accuracy: 0.6866 - val_loss: 0.7254
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7865 - loss: 0.5078 - val_accuracy: 0.7799 - val_loss: 0.6061
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5099 - val_accuracy: 0.6791 - val_loss: 0.7372
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7544 - loss: 0.5410 - val_accuracy: 0.7239 - val_loss: 0.6486
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7737 - loss: 0.4921 - val_accuracy: 0.7761 - val_loss: 0.5884
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7785 - loss: 0.5001 - val_accuracy: 0.7687 - val_loss: 0.5851
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7801 - loss: 0.4903 - val_accuracy: 0.7724 - val_loss: 0.5967
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7945 - loss: 0.4942 - val_accuracy: 0.7575 - val_loss: 0.5832
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7400 - loss: 0.5453 - val_accuracy: 0.7425 - val_loss: 0.6311
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7961 - loss: 0.4838 - val_accuracy: 0.7687 - val_loss: 0.5806
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7560 - loss: 0.5132 - val_accuracy: 0.7761 - val_loss: 0.6288
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7769 - loss: 0.5321 - val_accuracy: 0.7313 - val_loss: 0.6584
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7865 - loss: 0.4924 - val_accuracy: 0.7761 - val_loss: 0.5993
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7849 - loss: 0.4752 - val_accuracy: 0.7724 - val_loss: 0.5839
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7352 - loss: 0.5665 - val_accuracy: 0.7687 - val_loss: 0.5780
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.7432 - loss: 0.5542 - val_accuracy: 0.7761 - val_loss: 0.5866
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7913 - loss: 0.4776 - val_accuracy: 0.7799 - val_loss: 0.5989
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7881 - loss: 0.5081 - val_accuracy: 0.7836 - val_loss: 0.6192
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7994 - loss: 0.4853 - val_accuracy: 0.7351 - val_loss: 0.6694
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.7624 - loss: 0.5455 - val_accuracy: 0.6828 - val_loss: 0.8114
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.6133 - val_accuracy: 0.7575 - val_loss: 0.5776
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7769 - loss: 0.5017 - val_accuracy: 0.7425 - val_loss: 0.6547
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7705 - loss: 0.5175 - val_accuracy: 0.7687 - val_loss: 0.6336
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7881 - loss: 0.4724 - val_accuracy: 0.7687 - val_loss: 0.6150
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7143 - loss: 0.6085 - val_accuracy: 0.7799 - val_loss: 0.6033
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7865 - loss: 0.4787 - val_accuracy: 0.7836 - val_loss: 0.6106
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7978 - loss: 0.4785 - val_accuracy: 0.6866 - val_loss: 0.7933
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7817 - loss: 0.5221 - val_accuracy: 0.6716 - val_loss: 1.0018
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7560 - loss: 0.5429 - val_accuracy: 0.7761 - val_loss: 0.5848
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7673 - loss: 0.5200 - val_accuracy: 0.7351 - val_loss: 0.6791
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7833 - loss: 0.5043 - val_accuracy: 0.7873 - val_loss: 0.5872
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7929 - loss: 0.4839 - val_accuracy: 0.7500 - val_loss: 0.6600
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7849 - loss: 0.5360 - val_accuracy: 0.7761 - val_loss: 0.5833
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7913 - loss: 0.5011 - val_accuracy: 0.7799 - val_loss: 0.5969
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8122 - loss: 0.4501 - val_accuracy: 0.7761 - val_loss: 0.5954
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7865 - loss: 0.4865 - val_accuracy: 0.7649 - val_loss: 0.6297
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.7496 - loss: 0.5519 - val_accuracy: 0.7388 - val_loss: 0.6911
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.7994 - loss: 0.4766 - val_accuracy: 0.6567 - val_loss: 0.7673
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4523 - val_accuracy: 0.7799 - val_loss: 0.5909
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7833 - loss: 0.4714 - val_accuracy: 0.7052 - val_loss: 0.7142
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8122 - loss: 0.4730 - val_accuracy: 0.7761 - val_loss: 0.5911
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7913 - loss: 0.4645 - val_accuracy: 0.7836 - val_loss: 0.5919
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7929 - loss: 0.4633 - val_accuracy: 0.7799 - val_loss: 0.5892
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7737 - loss: 0.5103 - val_accuracy: 0.7836 - val_loss: 0.5824
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7657 - loss: 0.5500 - val_accuracy: 0.7463 - val_loss: 0.6882
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.8042 - loss: 0.4732 - val_accuracy: 0.7873 - val_loss: 0.6265
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8090 - loss: 0.4501 - val_accuracy: 0.7910 - val_loss: 0.5943
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7865 - loss: 0.4906 - val_accuracy: 0.7836 - val_loss: 0.5840
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.8010 - loss: 0.4581 - val_accuracy: 0.7201 - val_loss: 0.7444
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7705 - loss: 0.5090 - val_accuracy: 0.7201 - val_loss: 0.7151
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7929 - loss: 0.4903 - val_accuracy: 0.7799 - val_loss: 0.6011
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8042 - loss: 0.4808 - val_accuracy: 0.7127 - val_loss: 0.7097
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7945 - loss: 0.4739 - val_accuracy: 0.7873 - val_loss: 0.5943
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.7705 - loss: 0.5150 - val_accuracy: 0.7052 - val_loss: 0.7584
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8058 - loss: 0.4730 - val_accuracy: 0.7873 - val_loss: 0.6074
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.8122 - loss: 0.4570 - val_accuracy: 0.7873 - val_loss: 0.5853
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5036 - val_accuracy: 0.7388 - val_loss: 0.7205
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.7994 - loss: 0.4718 - val_accuracy: 0.6978 - val_loss: 0.7778
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.7624 - loss: 0.5340 - val_accuracy: 0.7500 - val_loss: 0.6717
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7705 - loss: 0.5292 - val_accuracy: 0.7836 - val_loss: 0.6019
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7801 - loss: 0.5229 - val_accuracy: 0.7687 - val_loss: 0.6395
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.8026 - loss: 0.4784 - val_accuracy: 0.7836 - val_loss: 0.6022
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8058 - loss: 0.4676 - val_accuracy: 0.7910 - val_loss: 0.6111
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.8138 - loss: 0.4572 - val_accuracy: 0.7575 - val_loss: 0.6352
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.7945 - loss: 0.4670 - val_accuracy: 0.7052 - val_loss: 0.7847
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7576 - loss: 0.5711 - val_accuracy: 0.7537 - val_loss: 0.6691
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7753 - loss: 0.5227 - val_accuracy: 0.7836 - val_loss: 0.5952
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4580 - val_accuracy: 0.7799 - val_loss: 0.6059
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7769 - loss: 0.4876 - val_accuracy: 0.7799 - val_loss: 0.5973
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4643 - val_accuracy: 0.7910 - val_loss: 0.5940
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6220 - val_accuracy: 0.6866 - val_loss: 0.8756
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4746 - val_accuracy: 0.7500 - val_loss: 0.7286
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.8074 - loss: 0.4533 - val_accuracy: 0.7873 - val_loss: 0.6282
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7913 - loss: 0.4628 - val_accuracy: 0.7799 - val_loss: 0.5916
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8042 - loss: 0.4673 - val_accuracy: 0.7836 - val_loss: 0.5916
Epoch 153/5000

wandb: Agent Starting Run: rg7qtack with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 79.0714 - val_accuracy: 0.6119 - val_loss: 0.8530
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.7061 - val_accuracy: 0.6269 - val_loss: 1.7031
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6116 - loss: 0.8273 - val_accuracy: 0.6231 - val_loss: 0.6908
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6116 - loss: 0.6723 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.6132 - loss: 0.6703 - val_accuracy: 0.6306 - val_loss: 0.6918
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6132 - loss: 0.6687 - val_accuracy: 0.6306 - val_loss: 0.6935
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6132 - loss: 0.6678 - val_accuracy: 0.6306 - val_loss: 0.6957
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6982
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.7012
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.7047
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.7084
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.7126
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.7168
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.7309
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.7371
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.7350
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.7460
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7521
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7567
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7606
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7638
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.7581
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7618
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7643
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7677
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7695
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7723
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7744
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.7636
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.7676
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7704
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7728
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7747
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7764
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7779
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7793
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7806
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.7720
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7748
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7770
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7789
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7806
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7820
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7833
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7845
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7736
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7766
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7791
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7812
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7829
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7845
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7860
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7872
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7884
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7895
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7782
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7810
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7834
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7853
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7870
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7886
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7900
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7913
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7925
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7935
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7945
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7827
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7853
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.7874
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7893
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7910
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7925
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7938
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7950
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7962
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7973
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.7982
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7991
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.8000
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.7897
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7918
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7936
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7953
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7967
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7981
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.7992
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.8003
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.8013
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.8023
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.8031
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.8040
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6132 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.7409
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7409
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7410
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7410
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7411
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7411
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.7411
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7412
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.7413
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7413
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.7414
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.7414
Epoch 103: early stopping

wandb: Agent Starting Run: q8ygkura with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5634 - loss: 1.8753 - val_accuracy: 0.6642 - val_loss: 0.9695
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5795 - loss: 0.9665 - val_accuracy: 0.4515 - val_loss: 0.8990
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6132 - loss: 0.7705 - val_accuracy: 0.6567 - val_loss: 1.0916
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6421 - loss: 0.7953 - val_accuracy: 0.7090 - val_loss: 0.6265
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6244 - loss: 0.7714 - val_accuracy: 0.6754 - val_loss: 0.6022
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.7679 - val_accuracy: 0.6642 - val_loss: 0.7441
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6324 - loss: 0.8079 - val_accuracy: 0.6866 - val_loss: 0.6042
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6260 - loss: 0.7544 - val_accuracy: 0.6866 - val_loss: 0.6475
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6501 - loss: 0.7313 - val_accuracy: 0.6940 - val_loss: 0.5968
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6388 - loss: 0.7494 - val_accuracy: 0.5821 - val_loss: 0.6805
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6100 - loss: 0.7476 - val_accuracy: 0.6828 - val_loss: 0.6760
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6308 - loss: 0.7341 - val_accuracy: 0.6903 - val_loss: 0.5836
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6469 - loss: 0.7227 - val_accuracy: 0.6754 - val_loss: 0.6233
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6453 - loss: 0.7322 - val_accuracy: 0.6716 - val_loss: 0.7571
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6292 - loss: 0.7290 - val_accuracy: 0.6754 - val_loss: 0.6076
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6421 - loss: 0.7349 - val_accuracy: 0.6716 - val_loss: 0.6762
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6661 - loss: 0.7199 - val_accuracy: 0.6940 - val_loss: 0.6021
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6244 - loss: 0.7077 - val_accuracy: 0.4440 - val_loss: 1.1724
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6437 - loss: 0.7412 - val_accuracy: 0.5112 - val_loss: 0.7358
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6324 - loss: 0.7138 - val_accuracy: 0.4590 - val_loss: 0.8768
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6533 - loss: 0.7085 - val_accuracy: 0.6791 - val_loss: 0.6814
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6003 - loss: 0.7459 - val_accuracy: 0.6530 - val_loss: 0.7194
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6437 - loss: 0.6983 - val_accuracy: 0.6418 - val_loss: 1.1289
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6517 - loss: 0.7249 - val_accuracy: 0.6045 - val_loss: 0.7207
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6292 - loss: 0.7059 - val_accuracy: 0.7090 - val_loss: 0.5936
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6469 - loss: 0.7101 - val_accuracy: 0.6530 - val_loss: 0.8652
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6388 - loss: 0.7237 - val_accuracy: 0.6903 - val_loss: 0.5607
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6565 - loss: 0.6695 - val_accuracy: 0.7090 - val_loss: 0.5729
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 808us/step - accuracy: 0.6549 - loss: 0.6941 - val_accuracy: 0.6530 - val_loss: 0.7994
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6661 - loss: 0.6837 - val_accuracy: 0.6828 - val_loss: 0.6003
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6449 - val_accuracy: 0.6567 - val_loss: 0.7405
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6565 - loss: 0.6633 - val_accuracy: 0.6903 - val_loss: 0.5776
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6758 - loss: 0.6669 - val_accuracy: 0.4963 - val_loss: 0.8110
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6340 - loss: 0.6995 - val_accuracy: 0.7015 - val_loss: 0.5662
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7030 - loss: 0.6183 - val_accuracy: 0.5299 - val_loss: 0.7395
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6645 - loss: 0.6975 - val_accuracy: 0.6903 - val_loss: 0.5955
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6469 - loss: 0.6620 - val_accuracy: 0.4627 - val_loss: 1.0013
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6613 - loss: 0.6844 - val_accuracy: 0.5037 - val_loss: 0.8211
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6549 - loss: 0.6654 - val_accuracy: 0.6493 - val_loss: 0.9448
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6886 - loss: 0.6395 - val_accuracy: 0.5112 - val_loss: 0.7852
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6437 - loss: 0.7141 - val_accuracy: 0.6903 - val_loss: 0.5859
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6838 - loss: 0.6286 - val_accuracy: 0.6493 - val_loss: 0.9308
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6966 - loss: 0.6293 - val_accuracy: 0.5858 - val_loss: 0.7025
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6774 - loss: 0.6415 - val_accuracy: 0.6791 - val_loss: 0.6299
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6854 - loss: 0.6554 - val_accuracy: 0.6493 - val_loss: 1.0068
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6613 - loss: 0.6481 - val_accuracy: 0.6157 - val_loss: 0.6805
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7063 - loss: 0.6341 - val_accuracy: 0.6978 - val_loss: 0.5850
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6742 - loss: 0.6516 - val_accuracy: 0.7463 - val_loss: 0.6001
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6934 - loss: 0.6076 - val_accuracy: 0.7127 - val_loss: 0.5384
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6677 - loss: 0.6967 - val_accuracy: 0.7090 - val_loss: 0.5484
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.6262 - val_accuracy: 0.7052 - val_loss: 0.5522
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6998 - loss: 0.6255 - val_accuracy: 0.6754 - val_loss: 0.7527
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7271 - loss: 0.6370 - val_accuracy: 0.7612 - val_loss: 0.5784
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6950 - loss: 0.6379 - val_accuracy: 0.7201 - val_loss: 0.5366
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7271 - loss: 0.5934 - val_accuracy: 0.6716 - val_loss: 0.8698
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7030 - loss: 0.6262 - val_accuracy: 0.7052 - val_loss: 0.6018
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7191 - loss: 0.6024 - val_accuracy: 0.6679 - val_loss: 0.8602
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7047 - loss: 0.6319 - val_accuracy: 0.6866 - val_loss: 0.6449
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7287 - loss: 0.5891 - val_accuracy: 0.7612 - val_loss: 0.5486
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7079 - loss: 0.6138 - val_accuracy: 0.7015 - val_loss: 0.6188
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7111 - loss: 0.5909 - val_accuracy: 0.7239 - val_loss: 0.5268
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7047 - loss: 0.6130 - val_accuracy: 0.7164 - val_loss: 0.5224
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7255 - loss: 0.5771 - val_accuracy: 0.7500 - val_loss: 0.5264
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7352 - loss: 0.5783 - val_accuracy: 0.7313 - val_loss: 0.5308
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7239 - loss: 0.6031 - val_accuracy: 0.5634 - val_loss: 0.7438
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7207 - loss: 0.5958 - val_accuracy: 0.7649 - val_loss: 0.5815
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7255 - loss: 0.6106 - val_accuracy: 0.7164 - val_loss: 0.5341
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7239 - loss: 0.5790 - val_accuracy: 0.7612 - val_loss: 0.5452
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6822 - loss: 0.6153 - val_accuracy: 0.7388 - val_loss: 0.5571
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7111 - loss: 0.6116 - val_accuracy: 0.6567 - val_loss: 0.6502
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7464 - loss: 0.5325 - val_accuracy: 0.6679 - val_loss: 0.8088
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7207 - loss: 0.5873 - val_accuracy: 0.7463 - val_loss: 0.5252
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7528 - loss: 0.5834 - val_accuracy: 0.7425 - val_loss: 0.5219
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6966 - loss: 0.5754 - val_accuracy: 0.7537 - val_loss: 0.6084
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7111 - loss: 0.5819 - val_accuracy: 0.7724 - val_loss: 0.5519
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7416 - loss: 0.5847 - val_accuracy: 0.6716 - val_loss: 0.6436
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7047 - loss: 0.5849 - val_accuracy: 0.7463 - val_loss: 0.5171
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7544 - loss: 0.5452 - val_accuracy: 0.7724 - val_loss: 0.5634
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7416 - loss: 0.5863 - val_accuracy: 0.7351 - val_loss: 0.5436
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7416 - loss: 0.5430 - val_accuracy: 0.6679 - val_loss: 0.7180
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7416 - loss: 0.5815 - val_accuracy: 0.7612 - val_loss: 0.5360
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7416 - loss: 0.5657 - val_accuracy: 0.6604 - val_loss: 0.9463
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7624 - loss: 0.5351 - val_accuracy: 0.6940 - val_loss: 0.6230
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7544 - loss: 0.5545 - val_accuracy: 0.6978 - val_loss: 0.6458
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7496 - loss: 0.5457 - val_accuracy: 0.7313 - val_loss: 0.5691
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7207 - loss: 0.6073 - val_accuracy: 0.7575 - val_loss: 0.5496
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.7335 - loss: 0.5452 - val_accuracy: 0.7799 - val_loss: 0.6086
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7480 - loss: 0.5357 - val_accuracy: 0.7164 - val_loss: 0.6330
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.7111 - loss: 0.5982 - val_accuracy: 0.7687 - val_loss: 0.5937
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7287 - loss: 0.5693 - val_accuracy: 0.6269 - val_loss: 0.7083
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7255 - loss: 0.5982 - val_accuracy: 0.7351 - val_loss: 0.5558
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5630 - val_accuracy: 0.6866 - val_loss: 0.7391
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7432 - loss: 0.5869 - val_accuracy: 0.7239 - val_loss: 0.5815
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7464 - loss: 0.5315 - val_accuracy: 0.7313 - val_loss: 0.6302
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7464 - loss: 0.5464 - val_accuracy: 0.7239 - val_loss: 0.6103
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7352 - loss: 0.5816 - val_accuracy: 0.7687 - val_loss: 0.5461
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7528 - loss: 0.5702 - val_accuracy: 0.7687 - val_loss: 0.5184
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7592 - loss: 0.5265 - val_accuracy: 0.7575 - val_loss: 0.5131
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7560 - loss: 0.5613 - val_accuracy: 0.7537 - val_loss: 0.5120
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7624 - loss: 0.5298 - val_accuracy: 0.7276 - val_loss: 0.6375
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7384 - loss: 0.5763 - val_accuracy: 0.7388 - val_loss: 0.5857
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7512 - loss: 0.5525 - val_accuracy: 0.7612 - val_loss: 0.5109
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7544 - loss: 0.5254 - val_accuracy: 0.7724 - val_loss: 0.5961
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7544 - loss: 0.5461 - val_accuracy: 0.7761 - val_loss: 0.5293
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7721 - loss: 0.5231 - val_accuracy: 0.7687 - val_loss: 0.5398
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7432 - loss: 0.5746 - val_accuracy: 0.7463 - val_loss: 0.5250
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7576 - loss: 0.5198 - val_accuracy: 0.4739 - val_loss: 1.2426
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7737 - loss: 0.5257 - val_accuracy: 0.7201 - val_loss: 0.6359
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7721 - loss: 0.5252 - val_accuracy: 0.7612 - val_loss: 0.5148
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7657 - loss: 0.5364 - val_accuracy: 0.5597 - val_loss: 0.8350
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5296 - val_accuracy: 0.7724 - val_loss: 0.5409
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7689 - loss: 0.5216 - val_accuracy: 0.7463 - val_loss: 0.5468
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7608 - loss: 0.5207 - val_accuracy: 0.7724 - val_loss: 0.5136
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7496 - loss: 0.5465 - val_accuracy: 0.7612 - val_loss: 0.5258
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.7384 - loss: 0.5494 - val_accuracy: 0.7649 - val_loss: 0.5107
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7608 - loss: 0.5552 - val_accuracy: 0.6828 - val_loss: 0.6720
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7657 - loss: 0.5228 - val_accuracy: 0.7724 - val_loss: 0.5611
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7496 - loss: 0.5364 - val_accuracy: 0.7612 - val_loss: 0.5209
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.7753 - loss: 0.5096 - val_accuracy: 0.7724 - val_loss: 0.5117
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7576 - loss: 0.5153 - val_accuracy: 0.4776 - val_loss: 1.2822
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7512 - loss: 0.5443 - val_accuracy: 0.7575 - val_loss: 0.5362
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7576 - loss: 0.5000 - val_accuracy: 0.7537 - val_loss: 0.5298
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7673 - loss: 0.5411 - val_accuracy: 0.7276 - val_loss: 0.5782
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7608 - loss: 0.5195 - val_accuracy: 0.7351 - val_loss: 0.6078
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7689 - loss: 0.5062 - val_accuracy: 0.7537 - val_loss: 0.5325
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7335 - loss: 0.5256 - val_accuracy: 0.7537 - val_loss: 0.5260
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7753 - loss: 0.5188 - val_accuracy: 0.7687 - val_loss: 0.5463
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7640 - loss: 0.5181 - val_accuracy: 0.6866 - val_loss: 0.7622
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5106 - val_accuracy: 0.7201 - val_loss: 0.6488
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7624 - loss: 0.5309 - val_accuracy: 0.7537 - val_loss: 0.6134
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7801 - loss: 0.4840 - val_accuracy: 0.4851 - val_loss: 1.2932
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7753 - loss: 0.5167 - val_accuracy: 0.7687 - val_loss: 0.5572
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7705 - loss: 0.5060 - val_accuracy: 0.7537 - val_loss: 0.5518
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7640 - loss: 0.5222 - val_accuracy: 0.7687 - val_loss: 0.5368
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7689 - loss: 0.5158 - val_accuracy: 0.7537 - val_loss: 0.5605
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7512 - loss: 0.5351 - val_accuracy: 0.7836 - val_loss: 0.6011
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7673 - loss: 0.5058 - val_accuracy: 0.7090 - val_loss: 0.6634
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7592 - loss: 0.5289 - val_accuracy: 0.7201 - val_loss: 0.6144
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7592 - loss: 0.5422 - val_accuracy: 0.7276 - val_loss: 0.5890
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7897 - loss: 0.4765 - val_accuracy: 0.6903 - val_loss: 0.8223
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7608 - loss: 0.5663 - val_accuracy: 0.7537 - val_loss: 0.5308
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.7640 - loss: 0.5286 - val_accuracy: 0.7537 - val_loss: 0.5256
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7560 - loss: 0.5332 - val_accuracy: 0.7687 - val_loss: 0.5490
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5321 - val_accuracy: 0.5634 - val_loss: 0.8826
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7737 - loss: 0.5139 - val_accuracy: 0.7687 - val_loss: 0.5406
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7673 - loss: 0.5078 - val_accuracy: 0.7612 - val_loss: 0.5407
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7753 - loss: 0.5147 - val_accuracy: 0.7537 - val_loss: 0.5585
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7608 - loss: 0.5323 - val_accuracy: 0.7388 - val_loss: 0.5837
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7753 - loss: 0.5178 - val_accuracy: 0.7687 - val_loss: 0.5428
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7945 - loss: 0.4868 - val_accuracy: 0.6791 - val_loss: 0.9157
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7913 - loss: 0.5137 - val_accuracy: 0.7575 - val_loss: 0.5323
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7929 - loss: 0.5109 - val_accuracy: 0.7575 - val_loss: 0.5340
Epoch 153/5000

wandb: Agent Starting Run: r6vm6995 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5490 - loss: 7.1058 - val_accuracy: 0.7052 - val_loss: 1.4296
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 1.4156 - val_accuracy: 0.7388 - val_loss: 0.9964
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 1.1606 - val_accuracy: 0.7164 - val_loss: 0.9056
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6693 - loss: 0.9988 - val_accuracy: 0.7276 - val_loss: 0.7746
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6758 - loss: 0.8399 - val_accuracy: 0.6940 - val_loss: 0.7845
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6950 - loss: 0.6985 - val_accuracy: 0.4739 - val_loss: 1.1246
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6726 - loss: 0.7615 - val_accuracy: 0.7313 - val_loss: 0.6244
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6998 - loss: 0.6867 - val_accuracy: 0.7127 - val_loss: 0.6389
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.6742 - loss: 0.7257 - val_accuracy: 0.7313 - val_loss: 0.6376
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6870 - loss: 0.6200 - val_accuracy: 0.7425 - val_loss: 0.5398
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.7255 - loss: 0.5698 - val_accuracy: 0.7388 - val_loss: 0.5962
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7223 - loss: 0.5976 - val_accuracy: 0.6866 - val_loss: 0.7412
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5695 - val_accuracy: 0.7500 - val_loss: 0.5181
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5533 - val_accuracy: 0.6940 - val_loss: 0.6819
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.6616 - val_accuracy: 0.7463 - val_loss: 0.5707
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 998us/step - accuracy: 0.7480 - loss: 0.5377 - val_accuracy: 0.7463 - val_loss: 0.5782
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7528 - loss: 0.5463 - val_accuracy: 0.7239 - val_loss: 0.5919
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5498 - val_accuracy: 0.7873 - val_loss: 0.5084
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5331 - val_accuracy: 0.7575 - val_loss: 0.5395
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5720 - val_accuracy: 0.7537 - val_loss: 0.5293
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.6966 - loss: 0.7220 - val_accuracy: 0.7463 - val_loss: 0.5986
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6934 - loss: 0.6744 - val_accuracy: 0.7015 - val_loss: 0.6892
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7945 - loss: 0.4987 - val_accuracy: 0.7463 - val_loss: 0.5396
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7737 - loss: 0.4988 - val_accuracy: 0.7612 - val_loss: 0.5036
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7801 - loss: 0.4898 - val_accuracy: 0.7425 - val_loss: 0.5653
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7640 - loss: 0.5262 - val_accuracy: 0.7649 - val_loss: 0.5247
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.7961 - loss: 0.4697 - val_accuracy: 0.7687 - val_loss: 0.5357
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7769 - loss: 0.4807 - val_accuracy: 0.6269 - val_loss: 0.7158
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7640 - loss: 0.5060 - val_accuracy: 0.7425 - val_loss: 0.5126
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7929 - loss: 0.4566 - val_accuracy: 0.7500 - val_loss: 0.5618
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7865 - loss: 0.5008 - val_accuracy: 0.7836 - val_loss: 0.5041
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7624 - loss: 0.5350 - val_accuracy: 0.7612 - val_loss: 0.5741
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7560 - loss: 0.5787 - val_accuracy: 0.7724 - val_loss: 0.5066
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7721 - loss: 0.5071 - val_accuracy: 0.6754 - val_loss: 0.7279
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7705 - loss: 0.4991 - val_accuracy: 0.7799 - val_loss: 0.5020
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7929 - loss: 0.4774 - val_accuracy: 0.7612 - val_loss: 0.5169
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7817 - loss: 0.4679 - val_accuracy: 0.7500 - val_loss: 0.5486
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7785 - loss: 0.4838 - val_accuracy: 0.7612 - val_loss: 0.5626
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7817 - loss: 0.5124 - val_accuracy: 0.7575 - val_loss: 0.5590
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7881 - loss: 0.4997 - val_accuracy: 0.7687 - val_loss: 0.5104
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7849 - loss: 0.4769 - val_accuracy: 0.7649 - val_loss: 0.5252
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4709 - val_accuracy: 0.7836 - val_loss: 0.5114
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7913 - loss: 0.4947 - val_accuracy: 0.7537 - val_loss: 0.5575
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7592 - loss: 0.5422 - val_accuracy: 0.7649 - val_loss: 0.5688
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7865 - loss: 0.4929 - val_accuracy: 0.7799 - val_loss: 0.5264
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7945 - loss: 0.4630 - val_accuracy: 0.7836 - val_loss: 0.5776
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7994 - loss: 0.4592 - val_accuracy: 0.7761 - val_loss: 0.5209
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7769 - loss: 0.5408 - val_accuracy: 0.7873 - val_loss: 0.5306
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7833 - loss: 0.4895 - val_accuracy: 0.7836 - val_loss: 0.5629
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7913 - loss: 0.4686 - val_accuracy: 0.7761 - val_loss: 0.5099
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8026 - loss: 0.4696 - val_accuracy: 0.7799 - val_loss: 0.5262
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7881 - loss: 0.4829 - val_accuracy: 0.7649 - val_loss: 0.5012
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8010 - loss: 0.4597 - val_accuracy: 0.7724 - val_loss: 0.5281
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.7978 - loss: 0.4600 - val_accuracy: 0.7649 - val_loss: 0.5110
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7929 - loss: 0.4444 - val_accuracy: 0.7799 - val_loss: 0.5734
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8138 - loss: 0.4635 - val_accuracy: 0.7836 - val_loss: 0.5320
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8090 - loss: 0.4860 - val_accuracy: 0.7873 - val_loss: 0.5549
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7352 - loss: 0.6175 - val_accuracy: 0.7910 - val_loss: 0.5409
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7913 - loss: 0.5246 - val_accuracy: 0.7836 - val_loss: 0.5535
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.7929 - loss: 0.4714 - val_accuracy: 0.7388 - val_loss: 0.5786
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7737 - loss: 0.5013 - val_accuracy: 0.7687 - val_loss: 0.5205
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7737 - loss: 0.4824 - val_accuracy: 0.7649 - val_loss: 0.5202
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.8154 - loss: 0.4546 - val_accuracy: 0.7799 - val_loss: 0.5172
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.8042 - loss: 0.4623 - val_accuracy: 0.7761 - val_loss: 0.5656
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5014 - val_accuracy: 0.7799 - val_loss: 0.5244
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7978 - loss: 0.4424 - val_accuracy: 0.7612 - val_loss: 0.6103
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.8074 - loss: 0.4548 - val_accuracy: 0.7761 - val_loss: 0.5675
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8122 - loss: 0.4442 - val_accuracy: 0.7649 - val_loss: 0.6045
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7865 - loss: 0.4704 - val_accuracy: 0.7724 - val_loss: 0.5301
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7978 - loss: 0.4484 - val_accuracy: 0.7910 - val_loss: 0.5732
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7865 - loss: 0.4793 - val_accuracy: 0.7612 - val_loss: 0.6367
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7994 - loss: 0.4777 - val_accuracy: 0.7649 - val_loss: 0.5587
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7994 - loss: 0.4677 - val_accuracy: 0.7649 - val_loss: 0.5928
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7994 - loss: 0.4906 - val_accuracy: 0.7873 - val_loss: 0.5597
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7705 - loss: 0.5036 - val_accuracy: 0.7575 - val_loss: 0.6111
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7978 - loss: 0.4979 - val_accuracy: 0.7575 - val_loss: 0.6266
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7865 - loss: 0.5257 - val_accuracy: 0.7687 - val_loss: 0.5353
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7978 - loss: 0.4402 - val_accuracy: 0.7761 - val_loss: 0.5484
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7881 - loss: 0.5346 - val_accuracy: 0.7761 - val_loss: 0.5285
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8170 - loss: 0.4635 - val_accuracy: 0.7799 - val_loss: 0.5606
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8058 - loss: 0.4516 - val_accuracy: 0.7463 - val_loss: 0.6368
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.7801 - loss: 0.5059 - val_accuracy: 0.7537 - val_loss: 0.5974
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7673 - loss: 0.5428 - val_accuracy: 0.7873 - val_loss: 0.5255
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4565 - val_accuracy: 0.7239 - val_loss: 0.6830
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7961 - loss: 0.5057 - val_accuracy: 0.7761 - val_loss: 0.6040
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8170 - loss: 0.4483 - val_accuracy: 0.7687 - val_loss: 0.5866
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8090 - loss: 0.4554 - val_accuracy: 0.7687 - val_loss: 0.5179
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7897 - loss: 0.4644 - val_accuracy: 0.7873 - val_loss: 0.5733
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7978 - loss: 0.4689 - val_accuracy: 0.7724 - val_loss: 0.5396
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7801 - loss: 0.4984 - val_accuracy: 0.7724 - val_loss: 0.5327
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.8090 - loss: 0.4588 - val_accuracy: 0.7687 - val_loss: 0.5616
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.8042 - loss: 0.4778 - val_accuracy: 0.7537 - val_loss: 0.6226
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5570 - val_accuracy: 0.7313 - val_loss: 0.7552
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7945 - loss: 0.5085 - val_accuracy: 0.7388 - val_loss: 0.7269
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7978 - loss: 0.4610 - val_accuracy: 0.7910 - val_loss: 0.5279
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7961 - loss: 0.4832 - val_accuracy: 0.7724 - val_loss: 0.5354
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8218 - loss: 0.4622 - val_accuracy: 0.7948 - val_loss: 0.5362
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.8042 - loss: 0.4530 - val_accuracy: 0.7724 - val_loss: 0.5175
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8074 - loss: 0.4634 - val_accuracy: 0.7724 - val_loss: 0.5328
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7801 - loss: 0.5185 - val_accuracy: 0.7910 - val_loss: 0.5482
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8106 - loss: 0.4721 - val_accuracy: 0.7799 - val_loss: 0.5346
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8026 - loss: 0.4697 - val_accuracy: 0.7724 - val_loss: 0.5186
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7994 - loss: 0.4567 - val_accuracy: 0.7799 - val_loss: 0.5479
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4336 - val_accuracy: 0.7724 - val_loss: 0.5362
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8106 - loss: 0.4464 - val_accuracy: 0.7649 - val_loss: 0.5972
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8058 - loss: 0.4428 - val_accuracy: 0.7724 - val_loss: 0.5332
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7753 - loss: 0.5367 - val_accuracy: 0.7015 - val_loss: 0.7081
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7881 - loss: 0.5506 - val_accuracy: 0.7761 - val_loss: 0.5486
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.8010 - loss: 0.5049 - val_accuracy: 0.7276 - val_loss: 0.7053
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7785 - loss: 0.5217 - val_accuracy: 0.7761 - val_loss: 0.5362
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7865 - loss: 0.4736 - val_accuracy: 0.7761 - val_loss: 0.5216
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7913 - loss: 0.4722 - val_accuracy: 0.7687 - val_loss: 0.5239
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8122 - loss: 0.4451 - val_accuracy: 0.7537 - val_loss: 0.6411
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8138 - loss: 0.4483 - val_accuracy: 0.7724 - val_loss: 0.5295
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.8026 - loss: 0.4377 - val_accuracy: 0.7799 - val_loss: 0.5317
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8138 - loss: 0.4554 - val_accuracy: 0.7761 - val_loss: 0.5686
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7929 - loss: 0.4674 - val_accuracy: 0.7761 - val_loss: 0.5676
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7785 - loss: 0.4976 - val_accuracy: 0.7052 - val_loss: 0.8065
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7673 - loss: 0.5228 - val_accuracy: 0.7799 - val_loss: 0.5459
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8154 - loss: 0.4461 - val_accuracy: 0.7687 - val_loss: 0.5265
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8074 - loss: 0.4382 - val_accuracy: 0.7612 - val_loss: 0.5235
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4633 - val_accuracy: 0.7799 - val_loss: 0.5540
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7994 - loss: 0.4699 - val_accuracy: 0.7724 - val_loss: 0.5390
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8090 - loss: 0.4481 - val_accuracy: 0.7799 - val_loss: 0.5603
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8218 - loss: 0.4317 - val_accuracy: 0.7799 - val_loss: 0.5801
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7913 - loss: 0.4735 - val_accuracy: 0.7836 - val_loss: 0.5272
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.8090 - loss: 0.4498 - val_accuracy: 0.7612 - val_loss: 0.5882
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7994 - loss: 0.4727 - val_accuracy: 0.7873 - val_loss: 0.5962
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8042 - loss: 0.4393 - val_accuracy: 0.7687 - val_loss: 0.5435
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8170 - loss: 0.4450 - val_accuracy: 0.7873 - val_loss: 0.5645
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8106 - loss: 0.4514 - val_accuracy: 0.7799 - val_loss: 0.5333
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7945 - loss: 0.4699 - val_accuracy: 0.7687 - val_loss: 0.5266
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8170 - loss: 0.4480 - val_accuracy: 0.7649 - val_loss: 0.6440
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.7657 - loss: 0.5359 - val_accuracy: 0.7910 - val_loss: 0.5381
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7801 - loss: 0.5774 - val_accuracy: 0.7724 - val_loss: 0.5653
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.7994 - loss: 0.4460 - val_accuracy: 0.7687 - val_loss: 0.5456
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7721 - loss: 0.5224 - val_accuracy: 0.7500 - val_loss: 0.7021
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.8074 - loss: 0.4625 - val_accuracy: 0.7761 - val_loss: 0.5885
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4420 - val_accuracy: 0.7910 - val_loss: 0.5586
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.7913 - loss: 0.4721 - val_accuracy: 0.7761 - val_loss: 0.5269
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8074 - loss: 0.4466 - val_accuracy: 0.7799 - val_loss: 0.5360
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8154 - loss: 0.4250 - val_accuracy: 0.7836 - val_loss: 0.5901
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8074 - loss: 0.4825 - val_accuracy: 0.7313 - val_loss: 0.6718
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8106 - loss: 0.4369 - val_accuracy: 0.7649 - val_loss: 0.5265
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8186 - loss: 0.4245 - val_accuracy: 0.7761 - val_loss: 0.5245
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7945 - loss: 0.4419 - val_accuracy: 0.7799 - val_loss: 0.5338
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.8042 - loss: 0.4354 - val_accuracy: 0.7799 - val_loss: 0.5270
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.8026 - loss: 0.4592 - val_accuracy: 0.7761 - val_loss: 0.5492
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.8074 - loss: 0.4439 - val_accuracy: 0.7836 - val_loss: 0.5739
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4620 - val_accuracy: 0.7687 - val_loss: 0.5746
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8106 - loss: 0.4412 - val_accuracy: 0.7836 - val_loss: 0.5410
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8154 - loss: 0.4336 - val_accuracy: 0.7799 - val_loss: 0.5550
Epoch 152: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 0xmzxlrc with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5923 - loss: 14.8114 - val_accuracy: 0.6269 - val_loss: 0.9868
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6892 - val_accuracy: 0.6269 - val_loss: 0.9865
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6132 - loss: 0.6837 - val_accuracy: 0.6269 - val_loss: 0.9847
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6804 - val_accuracy: 0.6269 - val_loss: 0.9791
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6148 - loss: 0.6777 - val_accuracy: 0.6306 - val_loss: 0.9744
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6148 - loss: 0.6754 - val_accuracy: 0.6306 - val_loss: 0.9704
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6148 - loss: 0.6734 - val_accuracy: 0.6306 - val_loss: 0.9672
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6717 - val_accuracy: 0.6306 - val_loss: 0.9656
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.6148 - loss: 0.6708 - val_accuracy: 0.6306 - val_loss: 0.9663
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6148 - loss: 0.6696 - val_accuracy: 0.6306 - val_loss: 0.9664
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6148 - loss: 0.6689 - val_accuracy: 0.6306 - val_loss: 0.9654
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6148 - loss: 0.6681 - val_accuracy: 0.6306 - val_loss: 0.9645
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6675 - val_accuracy: 0.6306 - val_loss: 0.9646
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 950us/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.9639
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.9644
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.9651
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.9647
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.9655
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.9652
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.9671
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.9681
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.9707
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.9713
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.9711
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.9733
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.9728
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.9754
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.9749
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.9772
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.9778
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.9801
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.9808
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.9818
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.9826
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9766
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.9793
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9789
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9815
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9810
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9822
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.9838
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9864
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9860
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9867
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9893
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.9906
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9900
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9907
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9917
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9928
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9954
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9962
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9895
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9890
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.9916
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9924
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9920
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9946
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9957
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9968
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9975
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9986
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9993
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 0.9988
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0013
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0023
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0030
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0041
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0049
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0042
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0053
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.9971
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.9997
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.9991
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6306 - val_loss: 1.0018
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0011
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0038
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0032
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0057
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0051
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0062
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0088
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0082
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0091
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0117
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 809us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0111
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0136
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0128
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0136
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0152
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0179
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0171
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0181
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0091
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0085
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0112
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0125
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0118
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0129
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 1.0138
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0149
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0160
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0168
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0177
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 1.0186
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 1.0197
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0206
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 1.0216
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0208
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0235
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0226
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 1.0253
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 1.0245
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 1.0253
Epoch 114: early stopping

wandb: Agent Starting Run: i10k5ugq with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4222 - loss: 41.8136 - val_accuracy: 0.4552 - val_loss: 4.3406
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5345 - loss: 2.7550 - val_accuracy: 0.4627 - val_loss: 2.0152
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.5746 - loss: 1.5732 - val_accuracy: 0.6269 - val_loss: 2.3709
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 1.3184 - val_accuracy: 0.6381 - val_loss: 2.2079
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 1.3220 - val_accuracy: 0.7127 - val_loss: 0.7752
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6340 - loss: 1.1638 - val_accuracy: 0.7201 - val_loss: 0.7323
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.6292 - loss: 1.1968 - val_accuracy: 0.6940 - val_loss: 0.8031
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6019 - loss: 1.1372 - val_accuracy: 0.6604 - val_loss: 1.0685
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6276 - loss: 1.1772 - val_accuracy: 0.7313 - val_loss: 0.6317
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6597 - loss: 1.0179 - val_accuracy: 0.7276 - val_loss: 0.7493
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 1.0680 - val_accuracy: 0.7052 - val_loss: 0.6798
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6613 - loss: 1.0280 - val_accuracy: 0.4478 - val_loss: 1.2665
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 1.1263 - val_accuracy: 0.6828 - val_loss: 1.2430
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6661 - loss: 0.9530 - val_accuracy: 0.4478 - val_loss: 1.5230
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 1.0904 - val_accuracy: 0.7537 - val_loss: 0.5598
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6501 - loss: 1.0691 - val_accuracy: 0.6642 - val_loss: 1.4178
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6228 - loss: 1.0710 - val_accuracy: 0.7351 - val_loss: 0.6745
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6597 - loss: 0.9121 - val_accuracy: 0.7425 - val_loss: 0.5855
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6774 - loss: 0.8904 - val_accuracy: 0.6978 - val_loss: 1.0234
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6886 - loss: 0.8381 - val_accuracy: 0.5746 - val_loss: 0.9603
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6902 - loss: 0.9276 - val_accuracy: 0.7463 - val_loss: 0.6634
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.8612 - val_accuracy: 0.7090 - val_loss: 0.7218
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6549 - loss: 0.9053 - val_accuracy: 0.4179 - val_loss: 2.4242
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6838 - loss: 0.8649 - val_accuracy: 0.6007 - val_loss: 0.9008
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6950 - loss: 0.9237 - val_accuracy: 0.7873 - val_loss: 0.4975
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7014 - loss: 0.8740 - val_accuracy: 0.7649 - val_loss: 0.5685
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6677 - loss: 0.9632 - val_accuracy: 0.7239 - val_loss: 0.6548
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7287 - loss: 0.8040 - val_accuracy: 0.7164 - val_loss: 0.7591
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6950 - loss: 0.9089 - val_accuracy: 0.7537 - val_loss: 0.5807
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6742 - loss: 0.9394 - val_accuracy: 0.7612 - val_loss: 0.5568
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6902 - loss: 0.8280 - val_accuracy: 0.7873 - val_loss: 0.4743
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6966 - loss: 0.8726 - val_accuracy: 0.7052 - val_loss: 0.9615
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7047 - loss: 0.8148 - val_accuracy: 0.7276 - val_loss: 0.7011
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7030 - loss: 0.8063 - val_accuracy: 0.7239 - val_loss: 0.6636
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7319 - loss: 0.7087 - val_accuracy: 0.6455 - val_loss: 1.5474
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7223 - loss: 0.8559 - val_accuracy: 0.7724 - val_loss: 0.5394
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7287 - loss: 0.7099 - val_accuracy: 0.7724 - val_loss: 0.5477
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 979us/step - accuracy: 0.7207 - loss: 0.8858 - val_accuracy: 0.7799 - val_loss: 0.5338
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7143 - loss: 0.7563 - val_accuracy: 0.6828 - val_loss: 0.7034
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7496 - loss: 0.7858 - val_accuracy: 0.7612 - val_loss: 0.5520
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7239 - loss: 0.7948 - val_accuracy: 0.6455 - val_loss: 1.4395
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6982 - loss: 0.8056 - val_accuracy: 0.6940 - val_loss: 0.7450
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7063 - loss: 0.8299 - val_accuracy: 0.7910 - val_loss: 0.4875
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7207 - loss: 0.7103 - val_accuracy: 0.7276 - val_loss: 0.7361
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7544 - loss: 0.6535 - val_accuracy: 0.7910 - val_loss: 0.5694
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7448 - loss: 0.7046 - val_accuracy: 0.7201 - val_loss: 0.6415
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.7318 - val_accuracy: 0.5112 - val_loss: 1.1038
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.6982 - loss: 0.7609 - val_accuracy: 0.5746 - val_loss: 1.0582
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7239 - loss: 0.7204 - val_accuracy: 0.7537 - val_loss: 0.5561
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.7255 - val_accuracy: 0.7649 - val_loss: 0.5118
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.7608 - loss: 0.6782 - val_accuracy: 0.7836 - val_loss: 0.6016
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7095 - loss: 0.7618 - val_accuracy: 0.6157 - val_loss: 0.8958
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7416 - loss: 0.6530 - val_accuracy: 0.7761 - val_loss: 0.5116
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.7047 - loss: 0.8335 - val_accuracy: 0.7500 - val_loss: 0.6369
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7608 - loss: 0.5930 - val_accuracy: 0.7761 - val_loss: 0.6126
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7480 - loss: 0.6952 - val_accuracy: 0.6866 - val_loss: 1.0545
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.7223 - loss: 0.7209 - val_accuracy: 0.7537 - val_loss: 0.5347
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7432 - loss: 0.6959 - val_accuracy: 0.7836 - val_loss: 0.4837
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7207 - loss: 0.6741 - val_accuracy: 0.7500 - val_loss: 0.5348
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7223 - loss: 0.6787 - val_accuracy: 0.7313 - val_loss: 0.6149
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7464 - loss: 0.6992 - val_accuracy: 0.7761 - val_loss: 0.5107
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7432 - loss: 0.6678 - val_accuracy: 0.7761 - val_loss: 0.5258
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7352 - loss: 0.7102 - val_accuracy: 0.7948 - val_loss: 0.4929
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7769 - loss: 0.6062 - val_accuracy: 0.7500 - val_loss: 0.5897
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7592 - loss: 0.6713 - val_accuracy: 0.7724 - val_loss: 0.5052
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7624 - loss: 0.5716 - val_accuracy: 0.7724 - val_loss: 0.5250
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7335 - loss: 0.6779 - val_accuracy: 0.7799 - val_loss: 0.4968
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7512 - loss: 0.6745 - val_accuracy: 0.7575 - val_loss: 0.5030
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6714 - val_accuracy: 0.6940 - val_loss: 0.8725
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7191 - loss: 0.6431 - val_accuracy: 0.7649 - val_loss: 0.5683
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7352 - loss: 0.6759 - val_accuracy: 0.7724 - val_loss: 0.5170
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7335 - loss: 0.6386 - val_accuracy: 0.7724 - val_loss: 0.5102
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7368 - loss: 0.6249 - val_accuracy: 0.7537 - val_loss: 0.5220
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7352 - loss: 0.6474 - val_accuracy: 0.7687 - val_loss: 0.5157
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7480 - loss: 0.6216 - val_accuracy: 0.7799 - val_loss: 0.5489
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7400 - loss: 0.6132 - val_accuracy: 0.7724 - val_loss: 0.4804
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7608 - loss: 0.6448 - val_accuracy: 0.7687 - val_loss: 0.6342
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7689 - loss: 0.5565 - val_accuracy: 0.5970 - val_loss: 0.8047
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.7352 - loss: 0.6705 - val_accuracy: 0.7799 - val_loss: 0.5151
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.6094 - val_accuracy: 0.7164 - val_loss: 0.7961
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7400 - loss: 0.6538 - val_accuracy: 0.7575 - val_loss: 0.4933
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7512 - loss: 0.5863 - val_accuracy: 0.7015 - val_loss: 0.6734
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7608 - loss: 0.5766 - val_accuracy: 0.7239 - val_loss: 0.6897
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7833 - loss: 0.5882 - val_accuracy: 0.7724 - val_loss: 0.5202
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7576 - loss: 0.5794 - val_accuracy: 0.7388 - val_loss: 0.5996
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7432 - loss: 0.6264 - val_accuracy: 0.7463 - val_loss: 0.5697
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7480 - loss: 0.5856 - val_accuracy: 0.7649 - val_loss: 0.5261
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7817 - loss: 0.5435 - val_accuracy: 0.7649 - val_loss: 0.4847
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7753 - loss: 0.6038 - val_accuracy: 0.7761 - val_loss: 0.6014
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7705 - loss: 0.5711 - val_accuracy: 0.7948 - val_loss: 0.5059
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7528 - loss: 0.5829 - val_accuracy: 0.7761 - val_loss: 0.5726
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7464 - loss: 0.5993 - val_accuracy: 0.6157 - val_loss: 0.7796
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7737 - loss: 0.5509 - val_accuracy: 0.7799 - val_loss: 0.5298
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7721 - loss: 0.5623 - val_accuracy: 0.7500 - val_loss: 0.6037
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7464 - loss: 0.6176 - val_accuracy: 0.7201 - val_loss: 0.6773
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7480 - loss: 0.5841 - val_accuracy: 0.6940 - val_loss: 0.7149
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7416 - loss: 0.5941 - val_accuracy: 0.7649 - val_loss: 0.4889
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.7624 - loss: 0.5796 - val_accuracy: 0.6978 - val_loss: 0.7918
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5897 - val_accuracy: 0.7575 - val_loss: 0.5510
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7657 - loss: 0.5723 - val_accuracy: 0.7799 - val_loss: 0.5015
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7657 - loss: 0.5496 - val_accuracy: 0.7276 - val_loss: 0.6772
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7737 - loss: 0.5815 - val_accuracy: 0.7500 - val_loss: 0.5893
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7560 - loss: 0.6283 - val_accuracy: 0.7799 - val_loss: 0.4857
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7528 - loss: 0.5752 - val_accuracy: 0.7575 - val_loss: 0.5452
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7721 - loss: 0.5433 - val_accuracy: 0.7649 - val_loss: 0.5231
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7640 - loss: 0.5640 - val_accuracy: 0.7761 - val_loss: 0.5456
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7849 - loss: 0.5818 - val_accuracy: 0.7201 - val_loss: 0.7028
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7544 - loss: 0.5871 - val_accuracy: 0.7836 - val_loss: 0.5215
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7817 - loss: 0.5125 - val_accuracy: 0.6866 - val_loss: 0.8574
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7801 - loss: 0.5506 - val_accuracy: 0.7351 - val_loss: 0.6566
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7464 - loss: 0.5777 - val_accuracy: 0.7388 - val_loss: 0.6600
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7689 - loss: 0.5566 - val_accuracy: 0.7761 - val_loss: 0.4831
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7576 - loss: 0.5853 - val_accuracy: 0.7687 - val_loss: 0.5212
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7801 - loss: 0.5423 - val_accuracy: 0.7164 - val_loss: 0.6553
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.7624 - loss: 0.5477 - val_accuracy: 0.7836 - val_loss: 0.4801
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7865 - loss: 0.5750 - val_accuracy: 0.5746 - val_loss: 0.8822
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7801 - loss: 0.5259 - val_accuracy: 0.7761 - val_loss: 0.5206
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7689 - loss: 0.5396 - val_accuracy: 0.6045 - val_loss: 0.8294
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7576 - loss: 0.5809 - val_accuracy: 0.8022 - val_loss: 0.5888
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5536 - val_accuracy: 0.7761 - val_loss: 0.5217
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7705 - loss: 0.5763 - val_accuracy: 0.7836 - val_loss: 0.5654
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7865 - loss: 0.5309 - val_accuracy: 0.8060 - val_loss: 0.5183
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5402 - val_accuracy: 0.4851 - val_loss: 1.3674
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7801 - loss: 0.5366 - val_accuracy: 0.7948 - val_loss: 0.5238
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7576 - loss: 0.5729 - val_accuracy: 0.7276 - val_loss: 0.7810
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.7657 - loss: 0.5389 - val_accuracy: 0.7463 - val_loss: 0.6413
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7865 - loss: 0.5082 - val_accuracy: 0.7276 - val_loss: 0.6664
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7689 - loss: 0.5374 - val_accuracy: 0.7537 - val_loss: 0.5619
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7737 - loss: 0.5571 - val_accuracy: 0.7687 - val_loss: 0.5221
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7592 - loss: 0.5471 - val_accuracy: 0.7612 - val_loss: 0.5542
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7881 - loss: 0.5232 - val_accuracy: 0.7127 - val_loss: 0.7841
Epoch 131: early stopping

wandb: Agent Starting Run: hi7fngwi with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.4767 - loss: 11.0054 - val_accuracy: 0.3731 - val_loss: 2.5461
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5313 - loss: 1.0043 - val_accuracy: 0.6679 - val_loss: 0.8142
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5313 - loss: 0.7771 - val_accuracy: 0.6791 - val_loss: 0.6862
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6902 - val_accuracy: 0.6791 - val_loss: 0.6263
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.7185 - val_accuracy: 0.7127 - val_loss: 0.6501
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6196 - loss: 0.7744 - val_accuracy: 0.6940 - val_loss: 0.6094
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6132 - loss: 0.7511 - val_accuracy: 0.7239 - val_loss: 0.6258
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6421 - loss: 0.6736 - val_accuracy: 0.6754 - val_loss: 0.5977
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6875 - val_accuracy: 0.6642 - val_loss: 0.6506
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.6677 - loss: 0.6235 - val_accuracy: 0.6903 - val_loss: 0.6027
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6388 - loss: 0.7198 - val_accuracy: 0.7090 - val_loss: 0.6513
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6440 - val_accuracy: 0.6231 - val_loss: 0.7408
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 996us/step - accuracy: 0.6629 - loss: 0.6495 - val_accuracy: 0.6530 - val_loss: 0.6854
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6351 - val_accuracy: 0.6828 - val_loss: 0.6161
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6645 - loss: 0.6185 - val_accuracy: 0.6754 - val_loss: 0.5952
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6966 - loss: 0.5890 - val_accuracy: 0.7575 - val_loss: 0.5788
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6886 - loss: 0.5876 - val_accuracy: 0.6940 - val_loss: 0.6153
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7143 - loss: 0.5671 - val_accuracy: 0.6940 - val_loss: 0.5716
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6661 - loss: 0.7092 - val_accuracy: 0.6716 - val_loss: 0.7330
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5621 - val_accuracy: 0.7239 - val_loss: 0.5501
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7448 - loss: 0.5665 - val_accuracy: 0.7537 - val_loss: 0.5541
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.6998 - loss: 0.5898 - val_accuracy: 0.6754 - val_loss: 0.6870
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.7159 - loss: 0.5720 - val_accuracy: 0.7015 - val_loss: 0.5887
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7319 - loss: 0.5429 - val_accuracy: 0.6567 - val_loss: 0.7191
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7223 - loss: 0.5961 - val_accuracy: 0.7201 - val_loss: 0.6260
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7576 - loss: 0.5355 - val_accuracy: 0.7239 - val_loss: 0.5389
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7464 - loss: 0.5450 - val_accuracy: 0.5448 - val_loss: 0.7161
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6854 - loss: 0.6662 - val_accuracy: 0.7761 - val_loss: 0.5638
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7673 - loss: 0.5154 - val_accuracy: 0.4925 - val_loss: 0.9751
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7175 - loss: 0.5859 - val_accuracy: 0.7537 - val_loss: 0.5628
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7512 - loss: 0.5415 - val_accuracy: 0.7463 - val_loss: 0.5266
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7785 - loss: 0.5054 - val_accuracy: 0.7649 - val_loss: 0.5646
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7785 - loss: 0.5072 - val_accuracy: 0.7575 - val_loss: 0.5264
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7624 - loss: 0.5258 - val_accuracy: 0.6679 - val_loss: 0.7684
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7400 - loss: 0.5420 - val_accuracy: 0.6679 - val_loss: 0.6213
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7528 - loss: 0.5509 - val_accuracy: 0.7425 - val_loss: 0.5537
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7576 - loss: 0.5118 - val_accuracy: 0.7463 - val_loss: 0.5284
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7175 - loss: 0.6445 - val_accuracy: 0.6754 - val_loss: 1.1372
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7352 - loss: 0.5977 - val_accuracy: 0.7575 - val_loss: 0.5161
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7689 - loss: 0.5224 - val_accuracy: 0.7575 - val_loss: 0.5178
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7721 - loss: 0.5027 - val_accuracy: 0.7649 - val_loss: 0.5321
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7624 - loss: 0.5101 - val_accuracy: 0.7425 - val_loss: 0.5565
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7576 - loss: 0.5243 - val_accuracy: 0.7052 - val_loss: 0.6195
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7640 - loss: 0.5227 - val_accuracy: 0.7761 - val_loss: 0.5413
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7769 - loss: 0.5348 - val_accuracy: 0.7724 - val_loss: 0.5140
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7560 - loss: 0.5294 - val_accuracy: 0.7090 - val_loss: 0.5960
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5542 - val_accuracy: 0.7649 - val_loss: 0.5285
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7897 - loss: 0.4820 - val_accuracy: 0.6679 - val_loss: 0.6993
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7640 - loss: 0.5039 - val_accuracy: 0.7724 - val_loss: 0.5317
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7897 - loss: 0.4691 - val_accuracy: 0.7351 - val_loss: 0.5695
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7608 - loss: 0.5295 - val_accuracy: 0.7649 - val_loss: 0.5298
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7576 - loss: 0.5799 - val_accuracy: 0.7649 - val_loss: 0.5139
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7721 - loss: 0.5052 - val_accuracy: 0.7537 - val_loss: 0.5164
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7705 - loss: 0.4855 - val_accuracy: 0.7052 - val_loss: 0.6280
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7721 - loss: 0.5148 - val_accuracy: 0.7649 - val_loss: 0.5335
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7384 - loss: 0.5829 - val_accuracy: 0.7575 - val_loss: 0.5170
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7849 - loss: 0.4906 - val_accuracy: 0.6978 - val_loss: 0.7376
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7592 - loss: 0.5124 - val_accuracy: 0.7575 - val_loss: 0.5371
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.7849 - loss: 0.5227 - val_accuracy: 0.7090 - val_loss: 0.6235
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7255 - loss: 0.6588 - val_accuracy: 0.7761 - val_loss: 0.5172
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7737 - loss: 0.5904 - val_accuracy: 0.7761 - val_loss: 0.5104
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7448 - loss: 0.6063 - val_accuracy: 0.7649 - val_loss: 0.5288
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7817 - loss: 0.4919 - val_accuracy: 0.7015 - val_loss: 0.8379
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.7384 - loss: 0.5763 - val_accuracy: 0.7649 - val_loss: 0.5263
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7175 - loss: 0.6404 - val_accuracy: 0.7313 - val_loss: 0.6353
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7817 - loss: 0.5079 - val_accuracy: 0.7724 - val_loss: 0.6065
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7689 - loss: 0.5298 - val_accuracy: 0.7239 - val_loss: 0.6550
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4784 - val_accuracy: 0.7351 - val_loss: 0.6206
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7833 - loss: 0.4729 - val_accuracy: 0.7873 - val_loss: 0.5593
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7737 - loss: 0.4863 - val_accuracy: 0.7724 - val_loss: 0.5491
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7689 - loss: 0.4950 - val_accuracy: 0.7463 - val_loss: 0.5812
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7801 - loss: 0.4928 - val_accuracy: 0.7537 - val_loss: 0.5408
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.7833 - loss: 0.4719 - val_accuracy: 0.7761 - val_loss: 0.5317
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7817 - loss: 0.4781 - val_accuracy: 0.7090 - val_loss: 0.6542
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7897 - loss: 0.4731 - val_accuracy: 0.7575 - val_loss: 0.5831
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7368 - loss: 0.5814 - val_accuracy: 0.7724 - val_loss: 0.5307
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7865 - loss: 0.4880 - val_accuracy: 0.7127 - val_loss: 0.7826
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7705 - loss: 0.5461 - val_accuracy: 0.7649 - val_loss: 0.5287
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7416 - loss: 0.5779 - val_accuracy: 0.6940 - val_loss: 0.9880
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7705 - loss: 0.5204 - val_accuracy: 0.7799 - val_loss: 0.6004
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7833 - loss: 0.4849 - val_accuracy: 0.7612 - val_loss: 0.5311
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7913 - loss: 0.4680 - val_accuracy: 0.7724 - val_loss: 0.5332
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7913 - loss: 0.4821 - val_accuracy: 0.7687 - val_loss: 0.5560
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7961 - loss: 0.4948 - val_accuracy: 0.7649 - val_loss: 0.5445
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7769 - loss: 0.4922 - val_accuracy: 0.7761 - val_loss: 0.5525
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.8106 - loss: 0.4514 - val_accuracy: 0.7612 - val_loss: 0.5581
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7881 - loss: 0.4860 - val_accuracy: 0.7761 - val_loss: 0.5313
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4802 - val_accuracy: 0.7724 - val_loss: 0.5362
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7865 - loss: 0.5133 - val_accuracy: 0.7052 - val_loss: 0.6940
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7721 - loss: 0.5147 - val_accuracy: 0.7500 - val_loss: 0.5869
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7833 - loss: 0.4871 - val_accuracy: 0.7836 - val_loss: 0.5267
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7624 - loss: 0.5070 - val_accuracy: 0.6866 - val_loss: 0.6674
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7897 - loss: 0.4778 - val_accuracy: 0.7724 - val_loss: 0.5250
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7849 - loss: 0.4724 - val_accuracy: 0.7724 - val_loss: 0.5437
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7785 - loss: 0.4954 - val_accuracy: 0.7537 - val_loss: 0.5790
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7913 - loss: 0.4668 - val_accuracy: 0.7201 - val_loss: 0.7170
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7913 - loss: 0.4828 - val_accuracy: 0.7724 - val_loss: 0.5647
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7849 - loss: 0.5026 - val_accuracy: 0.7724 - val_loss: 0.5276
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.7673 - loss: 0.4974 - val_accuracy: 0.7761 - val_loss: 0.5682
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7673 - loss: 0.5753 - val_accuracy: 0.6978 - val_loss: 0.8389
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7464 - loss: 0.5893 - val_accuracy: 0.6679 - val_loss: 0.7099
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7833 - loss: 0.4652 - val_accuracy: 0.7799 - val_loss: 0.5499
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8074 - loss: 0.4597 - val_accuracy: 0.7612 - val_loss: 0.5890
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7945 - loss: 0.4658 - val_accuracy: 0.7351 - val_loss: 0.6236
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7657 - loss: 0.5310 - val_accuracy: 0.7836 - val_loss: 0.6176
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7737 - loss: 0.5433 - val_accuracy: 0.7313 - val_loss: 0.6935
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7817 - loss: 0.5129 - val_accuracy: 0.7799 - val_loss: 0.5880
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7737 - loss: 0.5019 - val_accuracy: 0.7724 - val_loss: 0.5677
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7865 - loss: 0.5161 - val_accuracy: 0.7873 - val_loss: 0.5858
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4509 - val_accuracy: 0.7649 - val_loss: 0.5268
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7801 - loss: 0.4654 - val_accuracy: 0.7761 - val_loss: 0.5386
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8074 - loss: 0.4615 - val_accuracy: 0.7873 - val_loss: 0.5315
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7689 - loss: 0.5205 - val_accuracy: 0.7687 - val_loss: 0.5526
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.8154 - loss: 0.4481 - val_accuracy: 0.7836 - val_loss: 0.5339
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7753 - loss: 0.5565 - val_accuracy: 0.7761 - val_loss: 0.6059
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7897 - loss: 0.4783 - val_accuracy: 0.7799 - val_loss: 0.5566
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7881 - loss: 0.4705 - val_accuracy: 0.7836 - val_loss: 0.5369
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7913 - loss: 0.4649 - val_accuracy: 0.7873 - val_loss: 0.5333
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7978 - loss: 0.4512 - val_accuracy: 0.7687 - val_loss: 0.5195
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8170 - loss: 0.4397 - val_accuracy: 0.7761 - val_loss: 0.6079
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7785 - loss: 0.4719 - val_accuracy: 0.7836 - val_loss: 0.5403
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7624 - loss: 0.6036 - val_accuracy: 0.7873 - val_loss: 0.5710
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7801 - loss: 0.5345 - val_accuracy: 0.7836 - val_loss: 0.6574
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7817 - loss: 0.4872 - val_accuracy: 0.7799 - val_loss: 0.5372
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7833 - loss: 0.5153 - val_accuracy: 0.7724 - val_loss: 0.5232
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4737 - val_accuracy: 0.7873 - val_loss: 0.5411
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7913 - loss: 0.4876 - val_accuracy: 0.7761 - val_loss: 0.5678
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7929 - loss: 0.4526 - val_accuracy: 0.7761 - val_loss: 0.5559
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7833 - loss: 0.4734 - val_accuracy: 0.7799 - val_loss: 0.5491
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7945 - loss: 0.4565 - val_accuracy: 0.7687 - val_loss: 0.5337
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4796 - val_accuracy: 0.6567 - val_loss: 0.7391
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7705 - loss: 0.5241 - val_accuracy: 0.7612 - val_loss: 0.5940
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8154 - loss: 0.4614 - val_accuracy: 0.7724 - val_loss: 0.5650
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8170 - loss: 0.4494 - val_accuracy: 0.7537 - val_loss: 0.6084
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7817 - loss: 0.4891 - val_accuracy: 0.7761 - val_loss: 0.5156
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7994 - loss: 0.4718 - val_accuracy: 0.7649 - val_loss: 0.5890
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7945 - loss: 0.4697 - val_accuracy: 0.7612 - val_loss: 0.5226
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7801 - loss: 0.5222 - val_accuracy: 0.7799 - val_loss: 0.5365
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7945 - loss: 0.4572 - val_accuracy: 0.7761 - val_loss: 0.5178
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8074 - loss: 0.4416 - val_accuracy: 0.7761 - val_loss: 0.5611
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7881 - loss: 0.4798 - val_accuracy: 0.7799 - val_loss: 0.5332
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8090 - loss: 0.4572 - val_accuracy: 0.7687 - val_loss: 0.5364
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7785 - loss: 0.5156 - val_accuracy: 0.7799 - val_loss: 0.5916
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7464 - loss: 0.5810 - val_accuracy: 0.7351 - val_loss: 0.7117
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7849 - loss: 0.4807 - val_accuracy: 0.7724 - val_loss: 0.5284
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8026 - loss: 0.4603 - val_accuracy: 0.7873 - val_loss: 0.5957
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4581 - val_accuracy: 0.7687 - val_loss: 0.5882
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8042 - loss: 0.4439 - val_accuracy: 0.7836 - val_loss: 0.5320
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7769 - loss: 0.4849 - val_accuracy: 0.7836 - val_loss: 0.5630
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7897 - loss: 0.4881 - val_accuracy: 0.7612 - val_loss: 0.5276
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7817 - loss: 0.4624 - val_accuracy: 0.7873 - val_loss: 0.5600
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8138 - loss: 0.4373 - val_accuracy: 0.7761 - val_loss: 0.5938
Epoch 153/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ekpxor36 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 3.4993 - val_accuracy: 0.6045 - val_loss: 0.7793
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.7081 - val_accuracy: 0.6045 - val_loss: 0.7071
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6879 - val_accuracy: 0.6045 - val_loss: 0.6866
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6180 - loss: 0.6776 - val_accuracy: 0.6082 - val_loss: 0.6815
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6132 - loss: 0.6737 - val_accuracy: 0.6082 - val_loss: 0.6773
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6148 - loss: 0.6712 - val_accuracy: 0.6082 - val_loss: 0.6746
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6164 - loss: 0.6697 - val_accuracy: 0.6082 - val_loss: 0.6710
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6132 - loss: 0.6691 - val_accuracy: 0.6082 - val_loss: 0.6700
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 954us/step - accuracy: 0.6148 - loss: 0.6685 - val_accuracy: 0.6082 - val_loss: 0.6675
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6164 - loss: 0.6679 - val_accuracy: 0.6082 - val_loss: 0.6666
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6675 - val_accuracy: 0.6082 - val_loss: 0.6664
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6116 - loss: 0.6675 - val_accuracy: 0.6082 - val_loss: 0.6660
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6116 - loss: 0.6672 - val_accuracy: 0.6082 - val_loss: 0.6659
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6116 - loss: 0.6672 - val_accuracy: 0.6082 - val_loss: 0.6654
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6082 - val_loss: 0.6649
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6082 - val_loss: 0.6651
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.6116 - loss: 0.6669 - val_accuracy: 0.6082 - val_loss: 0.6649
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 955us/step - accuracy: 0.6100 - loss: 0.6668 - val_accuracy: 0.6082 - val_loss: 0.6649
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6082 - val_loss: 0.6646
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6082 - val_loss: 0.6646
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6667 - val_accuracy: 0.6082 - val_loss: 0.6644
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6082 - val_loss: 0.6646
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.6100 - loss: 0.6666 - val_accuracy: 0.6119 - val_loss: 0.6641
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6119 - val_loss: 0.6644
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6119 - val_loss: 0.6644
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6116 - loss: 0.6665 - val_accuracy: 0.6119 - val_loss: 0.6642
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6119 - val_loss: 0.6644
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6119 - val_loss: 0.6643
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6119 - val_loss: 0.6642
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6119 - val_loss: 0.6645
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6119 - val_loss: 0.6641
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6119 - val_loss: 0.6643
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6641
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6644
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6644
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6119 - val_loss: 0.6646
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6654
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6645
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6647
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6194 - val_loss: 0.6641
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6194 - val_loss: 0.6644
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6647
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6651
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.6647
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6628
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6194 - val_loss: 0.6630
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6180 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6631
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.6636
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6641
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6196 - loss: 0.6658 - val_accuracy: 0.6157 - val_loss: 0.6639
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6164 - loss: 0.6655 - val_accuracy: 0.6157 - val_loss: 0.6642
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6644
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6194 - val_loss: 0.6646
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6194 - val_loss: 0.6624
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6148 - loss: 0.6658 - val_accuracy: 0.6157 - val_loss: 0.6625
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6630
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6633
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6632
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6180 - loss: 0.6657 - val_accuracy: 0.6119 - val_loss: 0.6634
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6180 - loss: 0.6655 - val_accuracy: 0.6157 - val_loss: 0.6636
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6196 - loss: 0.6661 - val_accuracy: 0.6119 - val_loss: 0.6641
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6119 - val_loss: 0.6631
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6196 - loss: 0.6652 - val_accuracy: 0.6119 - val_loss: 0.6630
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6196 - loss: 0.6652 - val_accuracy: 0.6157 - val_loss: 0.6632
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6196 - loss: 0.6648 - val_accuracy: 0.6157 - val_loss: 0.6611
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6157 - val_loss: 0.6621
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6196 - loss: 0.6648 - val_accuracy: 0.6157 - val_loss: 0.6617
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6623
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6648 - val_accuracy: 0.6157 - val_loss: 0.6627
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6627
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.6633
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.6629
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6119 - val_loss: 0.6619
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6157 - val_loss: 0.6614
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6212 - loss: 0.6649 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6196 - loss: 0.6649 - val_accuracy: 0.6119 - val_loss: 0.6619
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.6623
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6196 - loss: 0.6650 - val_accuracy: 0.6119 - val_loss: 0.6624
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6648 - val_accuracy: 0.6157 - val_loss: 0.6625
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6119 - val_loss: 0.6632
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6119 - val_loss: 0.6640
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6157 - val_loss: 0.6622
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6617
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6212 - loss: 0.6649 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6157 - val_loss: 0.6614
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6119 - val_loss: 0.6624
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6630
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6119 - val_loss: 0.6630
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6082 - val_loss: 0.6632
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6196 - loss: 0.6650 - val_accuracy: 0.6119 - val_loss: 0.6620
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.6620
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6244 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6606
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6617
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6196 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.6620
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6196 - loss: 0.6646 - val_accuracy: 0.6194 - val_loss: 0.6611
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6608
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6605
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6194 - val_loss: 0.6603
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6119 - val_loss: 0.6616
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6196 - loss: 0.6641 - val_accuracy: 0.6119 - val_loss: 0.6610
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6612
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6212 - loss: 0.6644 - val_accuracy: 0.6157 - val_loss: 0.6618
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6627
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6119 - val_loss: 0.6619
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6616
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6196 - loss: 0.6642 - val_accuracy: 0.6119 - val_loss: 0.6630
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6212 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6621
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6196 - loss: 0.6641 - val_accuracy: 0.6119 - val_loss: 0.6628
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6212 - loss: 0.6644 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6631
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6119 - val_loss: 0.6614
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6212 - loss: 0.6643 - val_accuracy: 0.6157 - val_loss: 0.6604
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6604
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6608
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.6212 - loss: 0.6643 - val_accuracy: 0.6157 - val_loss: 0.6612
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6157 - val_loss: 0.6615
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6157 - val_loss: 0.6617
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6614
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6157 - val_loss: 0.6620
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6641 - val_accuracy: 0.6157 - val_loss: 0.6612
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6194 - val_loss: 0.6615
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6618
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6637 - val_accuracy: 0.6157 - val_loss: 0.6618
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6212 - loss: 0.6641 - val_accuracy: 0.6119 - val_loss: 0.6626
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6119 - val_loss: 0.6623
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6196 - loss: 0.6641 - val_accuracy: 0.6119 - val_loss: 0.6628
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6196 - loss: 0.6641 - val_accuracy: 0.6119 - val_loss: 0.6633
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6196 - loss: 0.6649 - val_accuracy: 0.6082 - val_loss: 0.6659
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6646 - val_accuracy: 0.6119 - val_loss: 0.6643
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6082 - val_loss: 0.6652
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6082 - val_loss: 0.6663
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6212 - loss: 0.6647 - val_accuracy: 0.6082 - val_loss: 0.6655
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6626
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6630
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6119 - val_loss: 0.6632
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6196 - loss: 0.6641 - val_accuracy: 0.6157 - val_loss: 0.6616
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6618
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6627
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6119 - val_loss: 0.6626
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6212 - loss: 0.6641 - val_accuracy: 0.6157 - val_loss: 0.6623
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6082 - val_loss: 0.6637
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6212 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6611
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6119 - val_loss: 0.6629
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6082 - val_loss: 0.6637
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6196 - loss: 0.6642 - val_accuracy: 0.6119 - val_loss: 0.6633
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6196 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6627
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6212 - loss: 0.6640 - val_accuracy: 0.6157 - val_loss: 0.6623
Epoch 153/5000

wandb: Agent Starting Run: u6bni10n with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4880 - loss: 2.1641 - val_accuracy: 0.5037 - val_loss: 1.6517
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5474 - loss: 1.2842 - val_accuracy: 0.3358 - val_loss: 1.4409
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.5361 - loss: 1.2103 - val_accuracy: 0.6157 - val_loss: 0.8549
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.5843 - loss: 1.0486 - val_accuracy: 0.6530 - val_loss: 0.8425
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5827 - loss: 1.0491 - val_accuracy: 0.6903 - val_loss: 0.6960
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.9887 - val_accuracy: 0.6866 - val_loss: 0.6584
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6035 - loss: 0.9298 - val_accuracy: 0.6679 - val_loss: 0.8641
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.5843 - loss: 0.9406 - val_accuracy: 0.6978 - val_loss: 0.6354
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6324 - loss: 0.8965 - val_accuracy: 0.5522 - val_loss: 0.7921
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.6212 - loss: 0.9555 - val_accuracy: 0.4627 - val_loss: 0.9819
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6404 - loss: 0.8741 - val_accuracy: 0.7127 - val_loss: 0.5938
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6212 - loss: 0.8898 - val_accuracy: 0.6978 - val_loss: 0.7603
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.8642 - val_accuracy: 0.4478 - val_loss: 1.5542
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.8416 - val_accuracy: 0.7090 - val_loss: 0.6436
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6324 - loss: 0.8567 - val_accuracy: 0.7276 - val_loss: 0.5463
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6244 - loss: 0.8944 - val_accuracy: 0.6306 - val_loss: 1.4658
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6356 - loss: 0.9211 - val_accuracy: 0.7127 - val_loss: 0.6059
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.6485 - loss: 0.8220 - val_accuracy: 0.7649 - val_loss: 0.5659
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6517 - loss: 0.7990 - val_accuracy: 0.7537 - val_loss: 0.5285
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.8253 - val_accuracy: 0.7388 - val_loss: 0.5451
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.8386 - val_accuracy: 0.6903 - val_loss: 0.6991
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.6629 - loss: 0.8265 - val_accuracy: 0.4776 - val_loss: 1.0566
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6421 - loss: 0.8475 - val_accuracy: 0.7836 - val_loss: 0.5536
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6677 - loss: 0.7329 - val_accuracy: 0.4552 - val_loss: 1.1933
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6517 - loss: 0.8434 - val_accuracy: 0.7463 - val_loss: 0.5166
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6212 - loss: 0.8545 - val_accuracy: 0.7201 - val_loss: 0.5989
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6613 - loss: 0.8159 - val_accuracy: 0.7201 - val_loss: 0.5980
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6693 - loss: 0.8014 - val_accuracy: 0.4515 - val_loss: 1.2420
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6581 - loss: 0.8974 - val_accuracy: 0.6642 - val_loss: 0.8658
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.6870 - loss: 0.7727 - val_accuracy: 0.7873 - val_loss: 0.5327
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6533 - loss: 0.8231 - val_accuracy: 0.4963 - val_loss: 1.0061
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6661 - loss: 0.8158 - val_accuracy: 0.7873 - val_loss: 0.5165
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6982 - loss: 0.7162 - val_accuracy: 0.7873 - val_loss: 0.5146
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6758 - loss: 0.7384 - val_accuracy: 0.5112 - val_loss: 0.9919
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6581 - loss: 0.7699 - val_accuracy: 0.4291 - val_loss: 2.1547
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6742 - loss: 0.8381 - val_accuracy: 0.5000 - val_loss: 1.0121
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6838 - loss: 0.7600 - val_accuracy: 0.6866 - val_loss: 0.7726
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6790 - loss: 0.7988 - val_accuracy: 0.6604 - val_loss: 0.9264
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6742 - loss: 0.7623 - val_accuracy: 0.4478 - val_loss: 1.7019
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6758 - loss: 0.8138 - val_accuracy: 0.7425 - val_loss: 0.5182
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7111 - loss: 0.7144 - val_accuracy: 0.7612 - val_loss: 0.4827
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.7858 - val_accuracy: 0.7612 - val_loss: 0.4850
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7127 - loss: 0.7337 - val_accuracy: 0.6343 - val_loss: 1.4014
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7014 - loss: 0.7518 - val_accuracy: 0.6903 - val_loss: 0.7659
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6918 - loss: 0.7708 - val_accuracy: 0.6866 - val_loss: 0.6240
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6822 - loss: 0.7856 - val_accuracy: 0.6381 - val_loss: 0.6898
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6950 - loss: 0.6921 - val_accuracy: 0.5000 - val_loss: 1.0549
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6661 - loss: 0.7359 - val_accuracy: 0.7015 - val_loss: 0.7159
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7175 - loss: 0.7179 - val_accuracy: 0.6455 - val_loss: 1.1266
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6774 - loss: 0.7477 - val_accuracy: 0.7313 - val_loss: 0.5646
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7352 - loss: 0.6833 - val_accuracy: 0.7724 - val_loss: 0.4923
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7063 - loss: 0.7102 - val_accuracy: 0.7761 - val_loss: 0.4832
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6758 - loss: 0.7370 - val_accuracy: 0.7425 - val_loss: 0.5280
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6758 - loss: 0.7271 - val_accuracy: 0.6716 - val_loss: 0.8334
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6966 - loss: 0.7604 - val_accuracy: 0.7836 - val_loss: 0.4748
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7111 - loss: 0.7047 - val_accuracy: 0.6381 - val_loss: 1.2193
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7127 - loss: 0.7435 - val_accuracy: 0.7313 - val_loss: 0.6019
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7271 - loss: 0.6653 - val_accuracy: 0.7687 - val_loss: 0.4823
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7127 - loss: 0.7195 - val_accuracy: 0.7687 - val_loss: 0.4993
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7223 - loss: 0.6989 - val_accuracy: 0.7090 - val_loss: 0.5980
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7207 - loss: 0.6983 - val_accuracy: 0.4515 - val_loss: 1.7599
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6966 - loss: 0.7866 - val_accuracy: 0.5970 - val_loss: 0.7626
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7127 - loss: 0.7538 - val_accuracy: 0.7612 - val_loss: 0.4664
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6836 - val_accuracy: 0.5299 - val_loss: 1.0164
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7095 - loss: 0.7485 - val_accuracy: 0.7649 - val_loss: 0.5191
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7271 - loss: 0.6463 - val_accuracy: 0.5410 - val_loss: 0.9720
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7127 - loss: 0.6796 - val_accuracy: 0.7537 - val_loss: 0.4930
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.7063 - loss: 0.6882 - val_accuracy: 0.7015 - val_loss: 0.8529
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7400 - loss: 0.6747 - val_accuracy: 0.7724 - val_loss: 0.4979
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7287 - loss: 0.6473 - val_accuracy: 0.7537 - val_loss: 0.4799
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7384 - loss: 0.6463 - val_accuracy: 0.6343 - val_loss: 0.7216
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7079 - loss: 0.6894 - val_accuracy: 0.7724 - val_loss: 0.4700
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7335 - loss: 0.6694 - val_accuracy: 0.7687 - val_loss: 0.4672
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - accuracy: 0.7352 - loss: 0.6703 - val_accuracy: 0.7313 - val_loss: 0.6514
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7448 - loss: 0.6694 - val_accuracy: 0.7724 - val_loss: 0.5045
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7239 - loss: 0.7188 - val_accuracy: 0.7799 - val_loss: 0.5560
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7255 - loss: 0.6384 - val_accuracy: 0.7687 - val_loss: 0.4629
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7287 - loss: 0.6586 - val_accuracy: 0.7724 - val_loss: 0.4853
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7400 - loss: 0.6560 - val_accuracy: 0.6306 - val_loss: 0.7332
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7255 - loss: 0.6893 - val_accuracy: 0.7575 - val_loss: 0.5870
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7368 - loss: 0.6314 - val_accuracy: 0.6866 - val_loss: 0.8663
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7223 - loss: 0.7049 - val_accuracy: 0.6978 - val_loss: 0.8818
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7335 - loss: 0.6387 - val_accuracy: 0.6642 - val_loss: 0.6849
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7480 - loss: 0.6722 - val_accuracy: 0.7687 - val_loss: 0.4824
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7448 - loss: 0.6122 - val_accuracy: 0.4851 - val_loss: 1.2622
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.7106 - val_accuracy: 0.7724 - val_loss: 0.4601
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7271 - loss: 0.6850 - val_accuracy: 0.7425 - val_loss: 0.5149
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7432 - loss: 0.6311 - val_accuracy: 0.6530 - val_loss: 0.7119
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7223 - loss: 0.6711 - val_accuracy: 0.6754 - val_loss: 0.8990
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7239 - loss: 0.6609 - val_accuracy: 0.7761 - val_loss: 0.4975
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7175 - loss: 0.6702 - val_accuracy: 0.7761 - val_loss: 0.4772
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7175 - loss: 0.6464 - val_accuracy: 0.7649 - val_loss: 0.4609
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7287 - loss: 0.6949 - val_accuracy: 0.7351 - val_loss: 0.6443
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7368 - loss: 0.6671 - val_accuracy: 0.7724 - val_loss: 0.4977
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7384 - loss: 0.6376 - val_accuracy: 0.6306 - val_loss: 1.2799
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7319 - loss: 0.6543 - val_accuracy: 0.7239 - val_loss: 0.7346
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7287 - loss: 0.6641 - val_accuracy: 0.7836 - val_loss: 0.4942
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.7496 - loss: 0.6255 - val_accuracy: 0.7649 - val_loss: 0.4749
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7689 - loss: 0.5870 - val_accuracy: 0.7724 - val_loss: 0.4608
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7496 - loss: 0.6541 - val_accuracy: 0.7500 - val_loss: 0.5455
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6980 - val_accuracy: 0.7463 - val_loss: 0.6214
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7608 - loss: 0.5906 - val_accuracy: 0.7612 - val_loss: 0.5067
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7673 - loss: 0.5796 - val_accuracy: 0.5672 - val_loss: 0.8897
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7432 - loss: 0.6372 - val_accuracy: 0.6940 - val_loss: 0.6596
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5919 - val_accuracy: 0.7463 - val_loss: 0.5487
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7464 - loss: 0.6361 - val_accuracy: 0.7612 - val_loss: 0.5205
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7721 - loss: 0.5881 - val_accuracy: 0.7724 - val_loss: 0.4696
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7592 - loss: 0.6455 - val_accuracy: 0.7836 - val_loss: 0.4830
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7448 - loss: 0.6231 - val_accuracy: 0.7799 - val_loss: 0.5082
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7496 - loss: 0.6595 - val_accuracy: 0.6007 - val_loss: 0.7954
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7352 - loss: 0.6658 - val_accuracy: 0.7463 - val_loss: 0.6341
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7689 - loss: 0.6042 - val_accuracy: 0.7351 - val_loss: 0.7528
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7207 - loss: 0.6345 - val_accuracy: 0.7015 - val_loss: 0.8040
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7608 - loss: 0.6433 - val_accuracy: 0.7463 - val_loss: 0.6043
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7705 - loss: 0.5884 - val_accuracy: 0.7910 - val_loss: 0.4793
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7191 - loss: 0.6898 - val_accuracy: 0.8097 - val_loss: 0.5293
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7785 - loss: 0.5690 - val_accuracy: 0.8022 - val_loss: 0.4784
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7608 - loss: 0.6404 - val_accuracy: 0.5000 - val_loss: 1.2674
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7592 - loss: 0.5993 - val_accuracy: 0.7239 - val_loss: 0.6366
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7608 - loss: 0.6002 - val_accuracy: 0.7873 - val_loss: 0.4780
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7496 - loss: 0.6205 - val_accuracy: 0.4776 - val_loss: 1.6075
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7496 - loss: 0.6122 - val_accuracy: 0.7873 - val_loss: 0.4845
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7721 - loss: 0.5790 - val_accuracy: 0.7985 - val_loss: 0.5468
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7191 - loss: 0.6504 - val_accuracy: 0.6343 - val_loss: 1.6314
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6294 - val_accuracy: 0.7276 - val_loss: 0.7598
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7560 - loss: 0.5823 - val_accuracy: 0.7910 - val_loss: 0.4757
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.7319 - loss: 0.6405 - val_accuracy: 0.5709 - val_loss: 0.8633
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6620 - val_accuracy: 0.6903 - val_loss: 0.6754
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7400 - loss: 0.6287 - val_accuracy: 0.7799 - val_loss: 0.4889
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7576 - loss: 0.6033 - val_accuracy: 0.7649 - val_loss: 0.5284
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7303 - loss: 0.6358 - val_accuracy: 0.4925 - val_loss: 1.3398
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7833 - loss: 0.5911 - val_accuracy: 0.7948 - val_loss: 0.4865
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7335 - loss: 0.6696 - val_accuracy: 0.7761 - val_loss: 0.4740
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7608 - loss: 0.5875 - val_accuracy: 0.7239 - val_loss: 0.8266
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7640 - loss: 0.5884 - val_accuracy: 0.6381 - val_loss: 0.7467
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7576 - loss: 0.6216 - val_accuracy: 0.6791 - val_loss: 0.8781
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7432 - loss: 0.6405 - val_accuracy: 0.7910 - val_loss: 0.4790
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7640 - loss: 0.5863 - val_accuracy: 0.7910 - val_loss: 0.4804
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7528 - loss: 0.6173 - val_accuracy: 0.7463 - val_loss: 0.6115
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7640 - loss: 0.5935 - val_accuracy: 0.6679 - val_loss: 0.6974
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7624 - loss: 0.5976 - val_accuracy: 0.7313 - val_loss: 0.6356
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.6214 - val_accuracy: 0.7052 - val_loss: 0.6926
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7432 - loss: 0.6442 - val_accuracy: 0.6082 - val_loss: 0.7880
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7817 - loss: 0.5654 - val_accuracy: 0.6828 - val_loss: 0.9408
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7689 - loss: 0.5913 - val_accuracy: 0.7761 - val_loss: 0.4705
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7737 - loss: 0.6016 - val_accuracy: 0.7537 - val_loss: 0.5841
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7335 - loss: 0.6526 - val_accuracy: 0.7276 - val_loss: 0.7435
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7737 - loss: 0.5907 - val_accuracy: 0.7687 - val_loss: 0.4787
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6332 - val_accuracy: 0.7948 - val_loss: 0.5094
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7496 - loss: 0.5982 - val_accuracy: 0.6455 - val_loss: 0.7692
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7640 - loss: 0.5944 - val_accuracy: 0.7873 - val_loss: 0.4938
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7448 - loss: 0.6605 - val_accuracy: 0.6157 - val_loss: 0.8135
Epoch 153/5000

wandb: Agent Starting Run: a0zt37th with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 27.9504 - val_accuracy: 0.6269 - val_loss: 19.0246
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 10.7964 - val_accuracy: 0.6418 - val_loss: 1.4518
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5570 - loss: 1.0833 - val_accuracy: 0.5821 - val_loss: 0.7990
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.5955 - loss: 0.7860 - val_accuracy: 0.6343 - val_loss: 0.7384
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 0.7101 - val_accuracy: 0.6269 - val_loss: 0.6919
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6388 - loss: 0.6510 - val_accuracy: 0.6679 - val_loss: 0.6318
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6514 - val_accuracy: 0.7090 - val_loss: 0.5948
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6144 - val_accuracy: 0.7090 - val_loss: 0.5923
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6438 - val_accuracy: 0.7239 - val_loss: 0.5808
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6030 - val_accuracy: 0.7052 - val_loss: 0.5862
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.5919 - val_accuracy: 0.7537 - val_loss: 0.5790
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.5919 - val_accuracy: 0.7015 - val_loss: 0.5751
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5856 - val_accuracy: 0.7164 - val_loss: 0.5677
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5752 - val_accuracy: 0.7425 - val_loss: 0.5668
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6142 - val_accuracy: 0.7164 - val_loss: 0.5730
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6966 - loss: 0.5890 - val_accuracy: 0.7649 - val_loss: 0.5941
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6661 - loss: 0.6074 - val_accuracy: 0.6978 - val_loss: 0.5894
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.7047 - loss: 0.6011 - val_accuracy: 0.7201 - val_loss: 0.5649
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.6966 - loss: 0.5738 - val_accuracy: 0.7127 - val_loss: 0.5610
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.6998 - loss: 0.5691 - val_accuracy: 0.7127 - val_loss: 0.5795
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.6870 - loss: 0.5911 - val_accuracy: 0.7500 - val_loss: 0.5580
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.6902 - loss: 0.6036 - val_accuracy: 0.7836 - val_loss: 0.5840
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5920 - val_accuracy: 0.7127 - val_loss: 0.5637
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7127 - loss: 0.5560 - val_accuracy: 0.7649 - val_loss: 0.5864
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7030 - loss: 0.5553 - val_accuracy: 0.7313 - val_loss: 0.5558
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6806 - loss: 0.6012 - val_accuracy: 0.6940 - val_loss: 0.6432
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7143 - loss: 0.5645 - val_accuracy: 0.6866 - val_loss: 0.6011
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7079 - loss: 0.5718 - val_accuracy: 0.6940 - val_loss: 0.6391
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7223 - loss: 0.5414 - val_accuracy: 0.6866 - val_loss: 0.6445
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7014 - loss: 0.5764 - val_accuracy: 0.7761 - val_loss: 0.5599
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7175 - loss: 0.5476 - val_accuracy: 0.7164 - val_loss: 0.5743
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7319 - loss: 0.5349 - val_accuracy: 0.7649 - val_loss: 0.5563
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.7352 - loss: 0.5429 - val_accuracy: 0.7500 - val_loss: 0.5639
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7159 - loss: 0.5414 - val_accuracy: 0.7201 - val_loss: 0.5743
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7512 - loss: 0.5417 - val_accuracy: 0.7351 - val_loss: 0.5678
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7368 - loss: 0.5312 - val_accuracy: 0.7313 - val_loss: 0.5597
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7319 - loss: 0.5699 - val_accuracy: 0.7500 - val_loss: 0.5493
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7303 - loss: 0.5737 - val_accuracy: 0.7724 - val_loss: 0.5437
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7352 - loss: 0.5293 - val_accuracy: 0.7910 - val_loss: 0.5716
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7335 - loss: 0.5233 - val_accuracy: 0.7575 - val_loss: 0.5442
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5087 - val_accuracy: 0.7351 - val_loss: 0.5537
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7512 - loss: 0.5337 - val_accuracy: 0.7351 - val_loss: 0.5648
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7657 - loss: 0.5197 - val_accuracy: 0.6940 - val_loss: 0.6495
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7576 - loss: 0.5222 - val_accuracy: 0.7351 - val_loss: 0.5522
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7480 - loss: 0.5181 - val_accuracy: 0.7799 - val_loss: 0.5448
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7657 - loss: 0.5099 - val_accuracy: 0.7463 - val_loss: 0.5701
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5236 - val_accuracy: 0.7873 - val_loss: 0.5764
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7705 - loss: 0.5036 - val_accuracy: 0.7649 - val_loss: 0.5594
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7705 - loss: 0.4973 - val_accuracy: 0.7425 - val_loss: 0.5714
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7785 - loss: 0.5033 - val_accuracy: 0.6567 - val_loss: 0.6817
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7512 - loss: 0.5263 - val_accuracy: 0.7724 - val_loss: 0.5411
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7769 - loss: 0.4957 - val_accuracy: 0.7687 - val_loss: 0.5546
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7657 - loss: 0.5022 - val_accuracy: 0.7873 - val_loss: 0.5661
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7512 - loss: 0.5302 - val_accuracy: 0.7724 - val_loss: 0.5409
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7705 - loss: 0.5003 - val_accuracy: 0.7724 - val_loss: 0.5408
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8026 - loss: 0.4752 - val_accuracy: 0.7612 - val_loss: 0.5442
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7737 - loss: 0.5054 - val_accuracy: 0.7649 - val_loss: 0.6152
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7705 - loss: 0.5034 - val_accuracy: 0.7687 - val_loss: 0.5480
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7929 - loss: 0.4898 - val_accuracy: 0.7836 - val_loss: 0.5937
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7929 - loss: 0.4773 - val_accuracy: 0.7537 - val_loss: 0.5417
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7881 - loss: 0.4726 - val_accuracy: 0.7612 - val_loss: 0.5410
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7753 - loss: 0.4852 - val_accuracy: 0.7724 - val_loss: 0.5477
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7608 - loss: 0.5384 - val_accuracy: 0.7761 - val_loss: 0.5464
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7865 - loss: 0.4918 - val_accuracy: 0.7649 - val_loss: 0.5501
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7978 - loss: 0.4720 - val_accuracy: 0.7724 - val_loss: 0.5501
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7929 - loss: 0.4866 - val_accuracy: 0.7799 - val_loss: 0.5509
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7897 - loss: 0.4719 - val_accuracy: 0.7687 - val_loss: 0.5356
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7753 - loss: 0.5127 - val_accuracy: 0.6903 - val_loss: 0.7044
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5038 - val_accuracy: 0.7463 - val_loss: 0.5905
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7737 - loss: 0.4784 - val_accuracy: 0.7388 - val_loss: 0.6529
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7945 - loss: 0.4741 - val_accuracy: 0.7761 - val_loss: 0.5840
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7833 - loss: 0.4943 - val_accuracy: 0.7575 - val_loss: 0.5765
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7833 - loss: 0.4724 - val_accuracy: 0.7724 - val_loss: 0.5708
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8042 - loss: 0.4568 - val_accuracy: 0.7649 - val_loss: 0.5543
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7961 - loss: 0.4732 - val_accuracy: 0.7575 - val_loss: 0.5496
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7881 - loss: 0.4805 - val_accuracy: 0.7724 - val_loss: 0.5583
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7865 - loss: 0.4593 - val_accuracy: 0.7649 - val_loss: 0.5631
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7945 - loss: 0.4552 - val_accuracy: 0.7687 - val_loss: 0.5680
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7961 - loss: 0.4620 - val_accuracy: 0.7799 - val_loss: 0.5641
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7817 - loss: 0.4870 - val_accuracy: 0.7612 - val_loss: 0.5636
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8010 - loss: 0.4736 - val_accuracy: 0.7649 - val_loss: 0.6201
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7961 - loss: 0.4676 - val_accuracy: 0.7761 - val_loss: 0.5584
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8042 - loss: 0.4545 - val_accuracy: 0.7612 - val_loss: 0.5691
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7753 - loss: 0.4906 - val_accuracy: 0.7799 - val_loss: 0.5896
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7721 - loss: 0.5230 - val_accuracy: 0.7612 - val_loss: 0.6792
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7721 - loss: 0.5012 - val_accuracy: 0.7463 - val_loss: 0.6183
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7897 - loss: 0.4805 - val_accuracy: 0.7500 - val_loss: 0.5979
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7945 - loss: 0.4728 - val_accuracy: 0.7761 - val_loss: 0.5907
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7978 - loss: 0.4463 - val_accuracy: 0.7649 - val_loss: 0.5732
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4758 - val_accuracy: 0.7463 - val_loss: 0.6277
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7961 - loss: 0.4467 - val_accuracy: 0.7724 - val_loss: 0.5617
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7945 - loss: 0.4418 - val_accuracy: 0.7836 - val_loss: 0.5965
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7817 - loss: 0.4656 - val_accuracy: 0.7724 - val_loss: 0.5787
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7785 - loss: 0.4702 - val_accuracy: 0.7649 - val_loss: 0.5860
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7865 - loss: 0.4651 - val_accuracy: 0.7799 - val_loss: 0.5757
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.8090 - loss: 0.4437 - val_accuracy: 0.7649 - val_loss: 0.5689
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7961 - loss: 0.4417 - val_accuracy: 0.7910 - val_loss: 0.5801
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7978 - loss: 0.4750 - val_accuracy: 0.7612 - val_loss: 0.5727
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.8122 - loss: 0.4459 - val_accuracy: 0.7836 - val_loss: 0.6058
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.8042 - loss: 0.4370 - val_accuracy: 0.7575 - val_loss: 0.6060
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8074 - loss: 0.4510 - val_accuracy: 0.7836 - val_loss: 0.5931
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8090 - loss: 0.4416 - val_accuracy: 0.7649 - val_loss: 0.5723
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7961 - loss: 0.4441 - val_accuracy: 0.7649 - val_loss: 0.5758
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7913 - loss: 0.4496 - val_accuracy: 0.7687 - val_loss: 0.5813
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.7705 - loss: 0.4954 - val_accuracy: 0.7761 - val_loss: 0.5713
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7897 - loss: 0.5001 - val_accuracy: 0.7388 - val_loss: 0.6666
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7978 - loss: 0.5092 - val_accuracy: 0.7687 - val_loss: 0.6035
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7849 - loss: 0.4688 - val_accuracy: 0.7649 - val_loss: 0.5854
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4594 - val_accuracy: 0.7612 - val_loss: 0.6882
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7978 - loss: 0.4574 - val_accuracy: 0.7537 - val_loss: 0.5769
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7849 - loss: 0.4560 - val_accuracy: 0.7687 - val_loss: 0.6109
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7978 - loss: 0.4506 - val_accuracy: 0.7612 - val_loss: 0.6787
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7897 - loss: 0.4601 - val_accuracy: 0.7687 - val_loss: 0.6320
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8186 - loss: 0.4254 - val_accuracy: 0.7649 - val_loss: 0.6280
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7849 - loss: 0.4453 - val_accuracy: 0.7687 - val_loss: 0.6111
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8026 - loss: 0.4413 - val_accuracy: 0.7799 - val_loss: 0.5972
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8058 - loss: 0.4468 - val_accuracy: 0.7537 - val_loss: 0.6707
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7785 - loss: 0.4992 - val_accuracy: 0.7799 - val_loss: 0.6090
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7833 - loss: 0.4693 - val_accuracy: 0.7799 - val_loss: 0.6332
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.7994 - loss: 0.4392 - val_accuracy: 0.7799 - val_loss: 0.6004
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7961 - loss: 0.4387 - val_accuracy: 0.7649 - val_loss: 0.6019
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8026 - loss: 0.4584 - val_accuracy: 0.7799 - val_loss: 0.6001
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7961 - loss: 0.4744 - val_accuracy: 0.7575 - val_loss: 0.5952
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.7978 - loss: 0.4432 - val_accuracy: 0.7761 - val_loss: 0.6015
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4468 - val_accuracy: 0.7649 - val_loss: 0.6040
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4464 - val_accuracy: 0.7799 - val_loss: 0.5982
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.7978 - loss: 0.4432 - val_accuracy: 0.7761 - val_loss: 0.6257
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7961 - loss: 0.4651 - val_accuracy: 0.7799 - val_loss: 0.6187
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8090 - loss: 0.4545 - val_accuracy: 0.7836 - val_loss: 0.6143
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8074 - loss: 0.4453 - val_accuracy: 0.7799 - val_loss: 0.6208
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.8074 - loss: 0.4290 - val_accuracy: 0.7537 - val_loss: 0.6104
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.7961 - loss: 0.4419 - val_accuracy: 0.7761 - val_loss: 0.6137
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8026 - loss: 0.4401 - val_accuracy: 0.7836 - val_loss: 0.6091
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7817 - loss: 0.4883 - val_accuracy: 0.7649 - val_loss: 0.6333
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.7897 - loss: 0.4546 - val_accuracy: 0.7612 - val_loss: 0.6151
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7978 - loss: 0.4712 - val_accuracy: 0.7276 - val_loss: 0.7342
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7961 - loss: 0.4762 - val_accuracy: 0.7761 - val_loss: 0.6701
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.7961 - loss: 0.4588 - val_accuracy: 0.7724 - val_loss: 0.6218
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.8042 - loss: 0.4337 - val_accuracy: 0.7761 - val_loss: 0.6139
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.7961 - loss: 0.4396 - val_accuracy: 0.7836 - val_loss: 0.6371
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4437 - val_accuracy: 0.7612 - val_loss: 0.6247
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7994 - loss: 0.4276 - val_accuracy: 0.7575 - val_loss: 0.6235
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.8154 - loss: 0.4465 - val_accuracy: 0.7724 - val_loss: 0.6535
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7833 - loss: 0.4720 - val_accuracy: 0.7799 - val_loss: 0.6377
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8106 - loss: 0.4488 - val_accuracy: 0.7687 - val_loss: 0.6308
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4423 - val_accuracy: 0.7761 - val_loss: 0.6968
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.7865 - loss: 0.4835 - val_accuracy: 0.7612 - val_loss: 0.6924
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.7945 - loss: 0.4444 - val_accuracy: 0.7687 - val_loss: 0.6836
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.7929 - loss: 0.4583 - val_accuracy: 0.7612 - val_loss: 0.6508
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7994 - loss: 0.4393 - val_accuracy: 0.7799 - val_loss: 0.6562
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7994 - loss: 0.4416 - val_accuracy: 0.6903 - val_loss: 0.9539
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7849 - loss: 0.4846 - val_accuracy: 0.7761 - val_loss: 0.6984
Epoch 153/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: axpy2lj2 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 11.0616 - val_accuracy: 0.6306 - val_loss: 0.7473
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.7196 - val_accuracy: 0.6194 - val_loss: 0.7200
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6907 - val_accuracy: 0.6194 - val_loss: 0.7086
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.6871 - val_accuracy: 0.6157 - val_loss: 0.7472
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.6853 - val_accuracy: 0.6231 - val_loss: 0.7421
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6164 - loss: 0.6877 - val_accuracy: 0.6194 - val_loss: 0.7091
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6132 - loss: 0.6777 - val_accuracy: 0.6157 - val_loss: 0.7216
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.6180 - loss: 0.6762 - val_accuracy: 0.6119 - val_loss: 0.7068
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6708 - val_accuracy: 0.6157 - val_loss: 0.7301
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6132 - loss: 0.6782 - val_accuracy: 0.6157 - val_loss: 0.7250
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6767 - val_accuracy: 0.6119 - val_loss: 0.7174
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.6164 - loss: 0.6693 - val_accuracy: 0.6082 - val_loss: 0.7164
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6196 - loss: 0.6687 - val_accuracy: 0.6082 - val_loss: 0.7148
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6691 - val_accuracy: 0.6119 - val_loss: 0.7201
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6180 - loss: 0.6698 - val_accuracy: 0.6082 - val_loss: 0.7156
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6119 - val_loss: 0.7236
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.6212 - loss: 0.6662 - val_accuracy: 0.6119 - val_loss: 0.7237
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6653 - val_accuracy: 0.6082 - val_loss: 0.7189
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.6212 - loss: 0.6649 - val_accuracy: 0.6119 - val_loss: 0.7183
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6082 - val_loss: 0.7174
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6119 - val_loss: 0.7191
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 952us/step - accuracy: 0.6228 - loss: 0.6658 - val_accuracy: 0.6119 - val_loss: 0.7293
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6212 - loss: 0.6655 - val_accuracy: 0.6119 - val_loss: 0.7205
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6119 - val_loss: 0.7239
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6196 - loss: 0.6651 - val_accuracy: 0.6119 - val_loss: 0.7219
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6082 - val_loss: 0.7161
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6180 - loss: 0.6660 - val_accuracy: 0.6082 - val_loss: 0.7134
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6157 - val_loss: 0.7127
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 939us/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6157 - val_loss: 0.7159
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6164 - loss: 0.6655 - val_accuracy: 0.6119 - val_loss: 0.7189
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6196 - loss: 0.6649 - val_accuracy: 0.6157 - val_loss: 0.7168
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6196 - loss: 0.6672 - val_accuracy: 0.6119 - val_loss: 0.7188
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6212 - loss: 0.6634 - val_accuracy: 0.6119 - val_loss: 0.7236
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6082 - val_loss: 0.7180
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7199
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.6212 - loss: 0.6648 - val_accuracy: 0.6119 - val_loss: 0.7195
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7222
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6196 - loss: 0.6635 - val_accuracy: 0.6119 - val_loss: 0.7226
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6212 - loss: 0.6642 - val_accuracy: 0.6119 - val_loss: 0.7171
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6119 - val_loss: 0.7181
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6180 - loss: 0.6627 - val_accuracy: 0.6082 - val_loss: 0.7168
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6212 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7217
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6119 - val_loss: 0.7226
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6228 - loss: 0.6633 - val_accuracy: 0.6119 - val_loss: 0.7211
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6082 - val_loss: 0.7179
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6082 - val_loss: 0.7286
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6212 - loss: 0.6634 - val_accuracy: 0.6119 - val_loss: 0.7217
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6196 - loss: 0.6631 - val_accuracy: 0.6082 - val_loss: 0.7246
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6212 - loss: 0.6626 - val_accuracy: 0.6082 - val_loss: 0.7212
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6228 - loss: 0.6626 - val_accuracy: 0.6082 - val_loss: 0.7193
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6635 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6082 - val_loss: 0.7270
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6119 - val_loss: 0.7273
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6228 - loss: 0.6626 - val_accuracy: 0.6082 - val_loss: 0.7187
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6212 - loss: 0.6636 - val_accuracy: 0.6119 - val_loss: 0.7212
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6082 - val_loss: 0.7272
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6244 - loss: 0.6635 - val_accuracy: 0.6045 - val_loss: 0.7250
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6212 - loss: 0.6628 - val_accuracy: 0.6082 - val_loss: 0.7211
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.6212 - loss: 0.6628 - val_accuracy: 0.6082 - val_loss: 0.7234
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6082 - val_loss: 0.7238
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6196 - loss: 0.6619 - val_accuracy: 0.6082 - val_loss: 0.7279
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6196 - loss: 0.6627 - val_accuracy: 0.6082 - val_loss: 0.7262
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6228 - loss: 0.6619 - val_accuracy: 0.6082 - val_loss: 0.7200
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.6212 - loss: 0.6622 - val_accuracy: 0.6045 - val_loss: 0.7233
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6082 - val_loss: 0.7248
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 947us/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6082 - val_loss: 0.7195
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6180 - loss: 0.6628 - val_accuracy: 0.6082 - val_loss: 0.7326
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6212 - loss: 0.6628 - val_accuracy: 0.6082 - val_loss: 0.7189
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6260 - loss: 0.6619 - val_accuracy: 0.6082 - val_loss: 0.7261
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6228 - loss: 0.6616 - val_accuracy: 0.6082 - val_loss: 0.7213
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6244 - loss: 0.6618 - val_accuracy: 0.6082 - val_loss: 0.7256
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 805us/step - accuracy: 0.6228 - loss: 0.6623 - val_accuracy: 0.6082 - val_loss: 0.7181
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6082 - val_loss: 0.7170
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6082 - val_loss: 0.7234
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6082 - val_loss: 0.7274
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6082 - val_loss: 0.7230
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6276 - loss: 0.6613 - val_accuracy: 0.6045 - val_loss: 0.7228
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6119 - val_loss: 0.7119
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6119 - val_loss: 0.7296
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6082 - val_loss: 0.7189
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6244 - loss: 0.6627 - val_accuracy: 0.6082 - val_loss: 0.7257
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6244 - loss: 0.6614 - val_accuracy: 0.6082 - val_loss: 0.7241
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6228 - loss: 0.6612 - val_accuracy: 0.6082 - val_loss: 0.7243
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6244 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7232
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.6260 - loss: 0.6614 - val_accuracy: 0.6082 - val_loss: 0.7240
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6082 - val_loss: 0.7215
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6082 - val_loss: 0.7262
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7194
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.6196 - loss: 0.6612 - val_accuracy: 0.6082 - val_loss: 0.7231
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6228 - loss: 0.6608 - val_accuracy: 0.6082 - val_loss: 0.7226
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6082 - val_loss: 0.7202
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6244 - loss: 0.6605 - val_accuracy: 0.6082 - val_loss: 0.7248
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6212 - loss: 0.6601 - val_accuracy: 0.6045 - val_loss: 0.7245
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6609 - val_accuracy: 0.6082 - val_loss: 0.7193
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6212 - loss: 0.6604 - val_accuracy: 0.6119 - val_loss: 0.7293
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.6260 - loss: 0.6608 - val_accuracy: 0.6082 - val_loss: 0.7245
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.6212 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7284
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6082 - val_loss: 0.7238
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7194
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6082 - val_loss: 0.7198
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6260 - loss: 0.6604 - val_accuracy: 0.6082 - val_loss: 0.7295
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6244 - loss: 0.6605 - val_accuracy: 0.6082 - val_loss: 0.7234
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6212 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7250
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6244 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7248
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6244 - loss: 0.6611 - val_accuracy: 0.6082 - val_loss: 0.7300
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6228 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.7189
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6212 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.7258
Epoch 108: early stopping

wandb: Agent Starting Run: aqrlphlb with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5185 - loss: 1.7734 - val_accuracy: 0.5597 - val_loss: 1.1576
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5409 - loss: 1.2140 - val_accuracy: 0.5933 - val_loss: 0.8188
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5714 - loss: 1.0418 - val_accuracy: 0.5672 - val_loss: 0.8332
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5522 - loss: 1.0632 - val_accuracy: 0.6567 - val_loss: 0.8917
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.5650 - loss: 1.0114 - val_accuracy: 0.6493 - val_loss: 0.6912
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6019 - loss: 0.9714 - val_accuracy: 0.5933 - val_loss: 1.4187
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.9139 - val_accuracy: 0.4478 - val_loss: 0.9786
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6035 - loss: 0.9341 - val_accuracy: 0.5410 - val_loss: 0.7572
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.5939 - loss: 0.8647 - val_accuracy: 0.3731 - val_loss: 1.3046
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6132 - loss: 0.9105 - val_accuracy: 0.6343 - val_loss: 0.7133
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.6100 - loss: 0.8892 - val_accuracy: 0.7090 - val_loss: 0.6077
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6228 - loss: 0.8518 - val_accuracy: 0.6157 - val_loss: 1.2709
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6372 - loss: 0.8666 - val_accuracy: 0.6903 - val_loss: 0.5835
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6100 - loss: 0.8902 - val_accuracy: 0.6754 - val_loss: 0.6956
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 988us/step - accuracy: 0.6421 - loss: 0.8163 - val_accuracy: 0.6754 - val_loss: 0.6027
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.9097 - val_accuracy: 0.7090 - val_loss: 0.5682
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.6324 - loss: 0.7905 - val_accuracy: 0.6343 - val_loss: 0.8877
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6356 - loss: 0.8286 - val_accuracy: 0.6306 - val_loss: 1.2710
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.6677 - loss: 0.7920 - val_accuracy: 0.6418 - val_loss: 0.7998
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6276 - loss: 0.8682 - val_accuracy: 0.4030 - val_loss: 1.9137
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.6356 - loss: 0.8164 - val_accuracy: 0.5970 - val_loss: 0.7195
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6806 - loss: 0.7818 - val_accuracy: 0.6493 - val_loss: 0.7176
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.6324 - loss: 0.8311 - val_accuracy: 0.7164 - val_loss: 0.5513
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6501 - loss: 0.7603 - val_accuracy: 0.4515 - val_loss: 1.5426
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6228 - loss: 0.8326 - val_accuracy: 0.6828 - val_loss: 0.6828
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.6469 - loss: 0.7822 - val_accuracy: 0.7090 - val_loss: 0.5837
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.6742 - loss: 0.7424 - val_accuracy: 0.7052 - val_loss: 0.5783
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6629 - loss: 0.7269 - val_accuracy: 0.7164 - val_loss: 0.5352
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.6709 - loss: 0.7689 - val_accuracy: 0.4440 - val_loss: 1.3585
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6661 - loss: 0.7676 - val_accuracy: 0.7537 - val_loss: 0.5752
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6838 - loss: 0.7449 - val_accuracy: 0.6381 - val_loss: 0.8347
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.6645 - loss: 0.7350 - val_accuracy: 0.7052 - val_loss: 0.5965
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6677 - loss: 0.7279 - val_accuracy: 0.7388 - val_loss: 0.5075
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6517 - loss: 0.7126 - val_accuracy: 0.6455 - val_loss: 0.7658
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6629 - loss: 0.7102 - val_accuracy: 0.7500 - val_loss: 0.5866
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6934 - loss: 0.7007 - val_accuracy: 0.7425 - val_loss: 0.5987
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6742 - loss: 0.7257 - val_accuracy: 0.7388 - val_loss: 0.5883
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6693 - loss: 0.7388 - val_accuracy: 0.7537 - val_loss: 0.5131
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 803us/step - accuracy: 0.6854 - loss: 0.6937 - val_accuracy: 0.4963 - val_loss: 0.9218
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.6950 - loss: 0.6938 - val_accuracy: 0.7537 - val_loss: 0.5051
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.6597 - loss: 0.7334 - val_accuracy: 0.7649 - val_loss: 0.5007
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6886 - loss: 0.6713 - val_accuracy: 0.7799 - val_loss: 0.5256
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6950 - loss: 0.6490 - val_accuracy: 0.6231 - val_loss: 0.6729
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6870 - loss: 0.6701 - val_accuracy: 0.7612 - val_loss: 0.5067
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6709 - loss: 0.6781 - val_accuracy: 0.7500 - val_loss: 0.5112
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7095 - loss: 0.6417 - val_accuracy: 0.6604 - val_loss: 0.8071
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6854 - loss: 0.6541 - val_accuracy: 0.6604 - val_loss: 0.7682
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6806 - loss: 0.6730 - val_accuracy: 0.7537 - val_loss: 0.5528
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7223 - loss: 0.6420 - val_accuracy: 0.7351 - val_loss: 0.5384
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6966 - loss: 0.6336 - val_accuracy: 0.6940 - val_loss: 0.5682
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7047 - loss: 0.6447 - val_accuracy: 0.7500 - val_loss: 0.5056
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6677 - loss: 0.6896 - val_accuracy: 0.6866 - val_loss: 0.5817
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7143 - loss: 0.6416 - val_accuracy: 0.7425 - val_loss: 0.5178
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7095 - loss: 0.6231 - val_accuracy: 0.7612 - val_loss: 0.4967
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7207 - loss: 0.6286 - val_accuracy: 0.5448 - val_loss: 0.8423
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7255 - loss: 0.6175 - val_accuracy: 0.6343 - val_loss: 0.6610
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7143 - loss: 0.6818 - val_accuracy: 0.7388 - val_loss: 0.5174
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7175 - loss: 0.6267 - val_accuracy: 0.6343 - val_loss: 0.6538
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7079 - loss: 0.6398 - val_accuracy: 0.7537 - val_loss: 0.5055
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7448 - loss: 0.6013 - val_accuracy: 0.7799 - val_loss: 0.5130
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7496 - loss: 0.5747 - val_accuracy: 0.7239 - val_loss: 0.6445
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7303 - loss: 0.6367 - val_accuracy: 0.7425 - val_loss: 0.5307
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7063 - loss: 0.6129 - val_accuracy: 0.6343 - val_loss: 0.9114
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7159 - loss: 0.6069 - val_accuracy: 0.5336 - val_loss: 0.8498
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5839 - val_accuracy: 0.6007 - val_loss: 0.7302
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7287 - loss: 0.6029 - val_accuracy: 0.7201 - val_loss: 0.5883
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7319 - loss: 0.5971 - val_accuracy: 0.7649 - val_loss: 0.4980
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7416 - loss: 0.5670 - val_accuracy: 0.6978 - val_loss: 0.7414
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7384 - loss: 0.5775 - val_accuracy: 0.7687 - val_loss: 0.4874
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7319 - loss: 0.6108 - val_accuracy: 0.7873 - val_loss: 0.4874
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7512 - loss: 0.5633 - val_accuracy: 0.7761 - val_loss: 0.5217
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7576 - loss: 0.5497 - val_accuracy: 0.6194 - val_loss: 0.7249
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7159 - loss: 0.5992 - val_accuracy: 0.7910 - val_loss: 0.4904
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7319 - loss: 0.5889 - val_accuracy: 0.7649 - val_loss: 0.4977
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7191 - loss: 0.5893 - val_accuracy: 0.6642 - val_loss: 0.9079
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7223 - loss: 0.6044 - val_accuracy: 0.7649 - val_loss: 0.4963
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7368 - loss: 0.5854 - val_accuracy: 0.7164 - val_loss: 0.6333
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7400 - loss: 0.5825 - val_accuracy: 0.7687 - val_loss: 0.4858
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7640 - loss: 0.5710 - val_accuracy: 0.7537 - val_loss: 0.5375
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7592 - loss: 0.5456 - val_accuracy: 0.7873 - val_loss: 0.5146
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7368 - loss: 0.5961 - val_accuracy: 0.6194 - val_loss: 0.7037
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7769 - loss: 0.5642 - val_accuracy: 0.6604 - val_loss: 0.6287
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.7705 - loss: 0.5271 - val_accuracy: 0.6119 - val_loss: 0.7758
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7400 - loss: 0.5659 - val_accuracy: 0.6679 - val_loss: 0.8740
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7801 - loss: 0.5515 - val_accuracy: 0.7500 - val_loss: 0.5829
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7673 - loss: 0.5327 - val_accuracy: 0.6866 - val_loss: 0.7038
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7544 - loss: 0.5468 - val_accuracy: 0.7351 - val_loss: 0.6408
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5887 - val_accuracy: 0.7799 - val_loss: 0.4857
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.7560 - loss: 0.5511 - val_accuracy: 0.7687 - val_loss: 0.5021
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7624 - loss: 0.5645 - val_accuracy: 0.7761 - val_loss: 0.4869
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7721 - loss: 0.5527 - val_accuracy: 0.7724 - val_loss: 0.5132
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7528 - loss: 0.5418 - val_accuracy: 0.7724 - val_loss: 0.5421
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7689 - loss: 0.5455 - val_accuracy: 0.7463 - val_loss: 0.5474
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7673 - loss: 0.5539 - val_accuracy: 0.7724 - val_loss: 0.6046
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7673 - loss: 0.5598 - val_accuracy: 0.7649 - val_loss: 0.5092
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.7689 - loss: 0.5224 - val_accuracy: 0.7724 - val_loss: 0.4970
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7560 - loss: 0.5434 - val_accuracy: 0.7799 - val_loss: 0.5301
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7673 - loss: 0.5393 - val_accuracy: 0.7575 - val_loss: 0.5274
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7640 - loss: 0.5507 - val_accuracy: 0.7687 - val_loss: 0.5006
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7705 - loss: 0.5434 - val_accuracy: 0.7388 - val_loss: 0.5457
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7624 - loss: 0.5460 - val_accuracy: 0.7836 - val_loss: 0.5380
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7592 - loss: 0.5536 - val_accuracy: 0.7724 - val_loss: 0.5009
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7769 - loss: 0.5241 - val_accuracy: 0.7537 - val_loss: 0.5446
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7833 - loss: 0.5146 - val_accuracy: 0.7724 - val_loss: 0.5347
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7657 - loss: 0.5479 - val_accuracy: 0.7351 - val_loss: 0.5862
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7657 - loss: 0.5211 - val_accuracy: 0.6642 - val_loss: 1.0530
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7753 - loss: 0.5270 - val_accuracy: 0.7799 - val_loss: 0.5040
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5236 - val_accuracy: 0.7836 - val_loss: 0.5731
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7576 - loss: 0.5281 - val_accuracy: 0.6828 - val_loss: 0.8358
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7721 - loss: 0.5435 - val_accuracy: 0.7687 - val_loss: 0.5423
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7929 - loss: 0.4797 - val_accuracy: 0.7612 - val_loss: 0.5256
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7657 - loss: 0.5224 - val_accuracy: 0.7836 - val_loss: 0.5000
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7945 - loss: 0.5130 - val_accuracy: 0.5336 - val_loss: 0.8524
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7978 - loss: 0.4962 - val_accuracy: 0.7873 - val_loss: 0.5246
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7849 - loss: 0.5293 - val_accuracy: 0.7687 - val_loss: 0.5146
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7833 - loss: 0.5163 - val_accuracy: 0.7463 - val_loss: 0.5737
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7785 - loss: 0.5315 - val_accuracy: 0.7724 - val_loss: 0.5279
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.7624 - loss: 0.5302 - val_accuracy: 0.7761 - val_loss: 0.5227
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7865 - loss: 0.5204 - val_accuracy: 0.7724 - val_loss: 0.5073
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7721 - loss: 0.5155 - val_accuracy: 0.7799 - val_loss: 0.5189
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7737 - loss: 0.5330 - val_accuracy: 0.7873 - val_loss: 0.5280
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7528 - loss: 0.5475 - val_accuracy: 0.7836 - val_loss: 0.5330
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7881 - loss: 0.5204 - val_accuracy: 0.7836 - val_loss: 0.5442
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7881 - loss: 0.5106 - val_accuracy: 0.7276 - val_loss: 0.6376
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.5106 - val_accuracy: 0.7985 - val_loss: 0.5366
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7865 - loss: 0.5111 - val_accuracy: 0.7351 - val_loss: 0.6610
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7689 - loss: 0.5021 - val_accuracy: 0.6828 - val_loss: 0.8570
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7705 - loss: 0.5123 - val_accuracy: 0.7799 - val_loss: 0.5446
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7945 - loss: 0.4952 - val_accuracy: 0.7687 - val_loss: 0.5170
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7945 - loss: 0.4829 - val_accuracy: 0.7351 - val_loss: 0.6594
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7769 - loss: 0.5103 - val_accuracy: 0.7649 - val_loss: 0.5516
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7961 - loss: 0.4904 - val_accuracy: 0.7537 - val_loss: 0.5699
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.7705 - loss: 0.5270 - val_accuracy: 0.7575 - val_loss: 0.5479
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7961 - loss: 0.5028 - val_accuracy: 0.7537 - val_loss: 0.5885
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7865 - loss: 0.5275 - val_accuracy: 0.7724 - val_loss: 0.6228
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7897 - loss: 0.4991 - val_accuracy: 0.7761 - val_loss: 0.5555
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7721 - loss: 0.5161 - val_accuracy: 0.6978 - val_loss: 0.7131
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7849 - loss: 0.4962 - val_accuracy: 0.7276 - val_loss: 0.6676
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7753 - loss: 0.5211 - val_accuracy: 0.7873 - val_loss: 0.5363
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4815 - val_accuracy: 0.7873 - val_loss: 0.5362
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7897 - loss: 0.4985 - val_accuracy: 0.7873 - val_loss: 0.5452
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7913 - loss: 0.4904 - val_accuracy: 0.7687 - val_loss: 0.5267
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7945 - loss: 0.4832 - val_accuracy: 0.7649 - val_loss: 0.5436
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7881 - loss: 0.5020 - val_accuracy: 0.7537 - val_loss: 0.5927
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7785 - loss: 0.5123 - val_accuracy: 0.7761 - val_loss: 0.5777
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 945us/step - accuracy: 0.7881 - loss: 0.4997 - val_accuracy: 0.7425 - val_loss: 0.6200
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7978 - loss: 0.4763 - val_accuracy: 0.7687 - val_loss: 0.6383
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7865 - loss: 0.4930 - val_accuracy: 0.7724 - val_loss: 0.5158
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7753 - loss: 0.4899 - val_accuracy: 0.6978 - val_loss: 0.6911
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7833 - loss: 0.5033 - val_accuracy: 0.7463 - val_loss: 0.6170
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7769 - loss: 0.4982 - val_accuracy: 0.7724 - val_loss: 0.5285
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7978 - loss: 0.4927 - val_accuracy: 0.7388 - val_loss: 0.6857
Epoch 153/5000

wandb: Agent Starting Run: f1x4xa2i with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4783 - loss: 9.2366 - val_accuracy: 0.3769 - val_loss: 1.1028
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5345 - loss: 1.0706 - val_accuracy: 0.4813 - val_loss: 0.8128
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.7234 - val_accuracy: 0.6866 - val_loss: 0.7202
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.6019 - loss: 0.7254 - val_accuracy: 0.6754 - val_loss: 0.7113
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6437 - loss: 0.6790 - val_accuracy: 0.7127 - val_loss: 0.6970
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6376 - val_accuracy: 0.6978 - val_loss: 0.6702
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6164 - loss: 0.7075 - val_accuracy: 0.6642 - val_loss: 0.8512
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6693 - loss: 0.6193 - val_accuracy: 0.5933 - val_loss: 0.7123
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.6758 - loss: 0.6273 - val_accuracy: 0.7313 - val_loss: 0.6147
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.5904 - val_accuracy: 0.6791 - val_loss: 0.6701
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6323 - val_accuracy: 0.7351 - val_loss: 0.6017
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.5772 - val_accuracy: 0.7500 - val_loss: 0.5973
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6398 - val_accuracy: 0.7537 - val_loss: 0.5872
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5668 - val_accuracy: 0.7090 - val_loss: 0.5923
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.5770 - val_accuracy: 0.7351 - val_loss: 0.5799
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5603 - val_accuracy: 0.6866 - val_loss: 0.6152
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 932us/step - accuracy: 0.7127 - loss: 0.5517 - val_accuracy: 0.6828 - val_loss: 0.6312
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7095 - loss: 0.5454 - val_accuracy: 0.7015 - val_loss: 0.5907
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6732 - val_accuracy: 0.7761 - val_loss: 0.5935
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 966us/step - accuracy: 0.7014 - loss: 0.5959 - val_accuracy: 0.6791 - val_loss: 0.6610
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.6998 - loss: 0.5548 - val_accuracy: 0.6791 - val_loss: 0.6564
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7175 - loss: 0.5378 - val_accuracy: 0.6828 - val_loss: 0.6059
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5244 - val_accuracy: 0.7276 - val_loss: 0.5581
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6998 - loss: 0.5367 - val_accuracy: 0.6866 - val_loss: 0.6083
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7079 - loss: 0.5655 - val_accuracy: 0.6903 - val_loss: 0.6002
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6838 - loss: 0.5982 - val_accuracy: 0.7090 - val_loss: 0.5887
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7030 - loss: 0.5667 - val_accuracy: 0.7425 - val_loss: 0.6226
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6998 - loss: 0.5759 - val_accuracy: 0.5896 - val_loss: 0.7202
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7014 - loss: 0.5538 - val_accuracy: 0.7425 - val_loss: 0.5502
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7384 - loss: 0.5159 - val_accuracy: 0.7463 - val_loss: 0.5698
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6966 - loss: 0.5933 - val_accuracy: 0.6604 - val_loss: 0.6842
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7207 - loss: 0.5726 - val_accuracy: 0.7313 - val_loss: 0.5522
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7352 - loss: 0.5476 - val_accuracy: 0.6866 - val_loss: 0.6469
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7319 - loss: 0.5118 - val_accuracy: 0.7015 - val_loss: 0.5718
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7464 - loss: 0.5071 - val_accuracy: 0.7015 - val_loss: 0.5783
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7432 - loss: 0.5201 - val_accuracy: 0.5485 - val_loss: 0.8332
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7030 - loss: 0.6400 - val_accuracy: 0.6940 - val_loss: 0.6402
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7207 - loss: 0.5474 - val_accuracy: 0.6418 - val_loss: 0.8050
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7384 - loss: 0.5991 - val_accuracy: 0.7687 - val_loss: 0.5311
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7624 - loss: 0.5307 - val_accuracy: 0.7612 - val_loss: 0.5288
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7640 - loss: 0.5193 - val_accuracy: 0.7239 - val_loss: 0.5540
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7785 - loss: 0.5170 - val_accuracy: 0.7500 - val_loss: 0.5320
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7624 - loss: 0.5223 - val_accuracy: 0.6903 - val_loss: 0.6395
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5332 - val_accuracy: 0.7799 - val_loss: 0.5612
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7657 - loss: 0.5060 - val_accuracy: 0.7276 - val_loss: 0.5702
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7994 - loss: 0.4755 - val_accuracy: 0.7649 - val_loss: 0.5338
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7785 - loss: 0.5024 - val_accuracy: 0.6604 - val_loss: 0.7896
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5510 - val_accuracy: 0.7537 - val_loss: 0.5244
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7801 - loss: 0.4994 - val_accuracy: 0.7724 - val_loss: 0.5460
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7897 - loss: 0.4795 - val_accuracy: 0.7612 - val_loss: 0.5258
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7929 - loss: 0.4747 - val_accuracy: 0.7164 - val_loss: 0.5836
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7721 - loss: 0.4875 - val_accuracy: 0.7239 - val_loss: 0.5744
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7576 - loss: 0.5118 - val_accuracy: 0.7164 - val_loss: 0.5704
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7592 - loss: 0.5148 - val_accuracy: 0.7724 - val_loss: 0.5213
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7753 - loss: 0.5132 - val_accuracy: 0.7612 - val_loss: 0.5180
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7978 - loss: 0.4891 - val_accuracy: 0.7649 - val_loss: 0.6367
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7689 - loss: 0.5161 - val_accuracy: 0.7761 - val_loss: 0.5683
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7512 - loss: 0.5920 - val_accuracy: 0.7052 - val_loss: 0.6482
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7705 - loss: 0.5192 - val_accuracy: 0.7537 - val_loss: 0.5195
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7689 - loss: 0.5056 - val_accuracy: 0.7239 - val_loss: 0.6461
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7785 - loss: 0.4947 - val_accuracy: 0.7687 - val_loss: 0.5337
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7673 - loss: 0.5049 - val_accuracy: 0.7575 - val_loss: 0.5252
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7721 - loss: 0.4827 - val_accuracy: 0.7761 - val_loss: 0.5519
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7833 - loss: 0.4734 - val_accuracy: 0.7276 - val_loss: 0.6033
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7865 - loss: 0.4683 - val_accuracy: 0.7761 - val_loss: 0.6046
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7785 - loss: 0.5027 - val_accuracy: 0.7612 - val_loss: 0.5297
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7769 - loss: 0.4940 - val_accuracy: 0.7724 - val_loss: 0.5449
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7785 - loss: 0.4921 - val_accuracy: 0.7761 - val_loss: 0.5844
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7897 - loss: 0.4824 - val_accuracy: 0.7612 - val_loss: 0.5293
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8026 - loss: 0.4643 - val_accuracy: 0.7575 - val_loss: 0.5211
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4900 - val_accuracy: 0.7612 - val_loss: 0.5335
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 990us/step - accuracy: 0.7544 - loss: 0.5215 - val_accuracy: 0.7425 - val_loss: 0.6281
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7881 - loss: 0.5277 - val_accuracy: 0.7612 - val_loss: 0.5292
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8042 - loss: 0.4583 - val_accuracy: 0.7649 - val_loss: 0.5146
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7480 - loss: 0.5283 - val_accuracy: 0.7612 - val_loss: 0.5258
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7945 - loss: 0.4775 - val_accuracy: 0.7649 - val_loss: 0.5337
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.7881 - loss: 0.4754 - val_accuracy: 0.7463 - val_loss: 0.5415
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7881 - loss: 0.4653 - val_accuracy: 0.7687 - val_loss: 0.5155
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7913 - loss: 0.4651 - val_accuracy: 0.7687 - val_loss: 0.5193
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7865 - loss: 0.4729 - val_accuracy: 0.7649 - val_loss: 0.5108
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7785 - loss: 0.4735 - val_accuracy: 0.7799 - val_loss: 0.5814
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7865 - loss: 0.4733 - val_accuracy: 0.7649 - val_loss: 0.5143
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7689 - loss: 0.5148 - val_accuracy: 0.7687 - val_loss: 0.5163
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7705 - loss: 0.4816 - val_accuracy: 0.7836 - val_loss: 0.5806
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7994 - loss: 0.4773 - val_accuracy: 0.7500 - val_loss: 0.5669
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7400 - loss: 0.5833 - val_accuracy: 0.7276 - val_loss: 0.6709
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.7673 - loss: 0.4940 - val_accuracy: 0.7612 - val_loss: 0.5272
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7897 - loss: 0.4543 - val_accuracy: 0.7537 - val_loss: 0.6343
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8074 - loss: 0.4667 - val_accuracy: 0.7463 - val_loss: 0.5893
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.8042 - loss: 0.4882 - val_accuracy: 0.7761 - val_loss: 0.5458
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7753 - loss: 0.5279 - val_accuracy: 0.7388 - val_loss: 0.6541
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7978 - loss: 0.4859 - val_accuracy: 0.7612 - val_loss: 0.5190
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7945 - loss: 0.4659 - val_accuracy: 0.7351 - val_loss: 0.6184
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5061 - val_accuracy: 0.7761 - val_loss: 0.5303
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8026 - loss: 0.4536 - val_accuracy: 0.7575 - val_loss: 0.5257
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7528 - loss: 0.6167 - val_accuracy: 0.7463 - val_loss: 0.6567
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7849 - loss: 0.4954 - val_accuracy: 0.7575 - val_loss: 0.5692
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7978 - loss: 0.4623 - val_accuracy: 0.7649 - val_loss: 0.5320
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7785 - loss: 0.5322 - val_accuracy: 0.7799 - val_loss: 0.5446
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7737 - loss: 0.4932 - val_accuracy: 0.7836 - val_loss: 0.5612
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7945 - loss: 0.4723 - val_accuracy: 0.7575 - val_loss: 0.5147
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.8154 - loss: 0.4658 - val_accuracy: 0.7687 - val_loss: 0.5285
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7737 - loss: 0.5335 - val_accuracy: 0.7612 - val_loss: 0.5552
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7881 - loss: 0.5000 - val_accuracy: 0.7649 - val_loss: 0.5069
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7817 - loss: 0.4886 - val_accuracy: 0.7799 - val_loss: 0.5521
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7994 - loss: 0.4648 - val_accuracy: 0.7649 - val_loss: 0.5125
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7945 - loss: 0.4555 - val_accuracy: 0.7724 - val_loss: 0.5134
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7849 - loss: 0.4851 - val_accuracy: 0.7649 - val_loss: 0.5136
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8074 - loss: 0.4505 - val_accuracy: 0.7724 - val_loss: 0.5195
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7913 - loss: 0.4581 - val_accuracy: 0.7649 - val_loss: 0.5451
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7897 - loss: 0.4896 - val_accuracy: 0.7612 - val_loss: 0.5194
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7640 - loss: 0.5413 - val_accuracy: 0.7761 - val_loss: 0.5355
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7769 - loss: 0.5102 - val_accuracy: 0.7276 - val_loss: 0.6486
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7817 - loss: 0.4999 - val_accuracy: 0.7649 - val_loss: 0.5566
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4716 - val_accuracy: 0.7836 - val_loss: 0.5734
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7881 - loss: 0.4521 - val_accuracy: 0.7649 - val_loss: 0.5551
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7929 - loss: 0.4664 - val_accuracy: 0.6567 - val_loss: 0.7504
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7929 - loss: 0.4770 - val_accuracy: 0.7127 - val_loss: 0.7510
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7929 - loss: 0.4911 - val_accuracy: 0.7612 - val_loss: 0.5249
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.8026 - loss: 0.4713 - val_accuracy: 0.7873 - val_loss: 0.5200
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8010 - loss: 0.4645 - val_accuracy: 0.7873 - val_loss: 0.5158
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7961 - loss: 0.4630 - val_accuracy: 0.7761 - val_loss: 0.5181
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7978 - loss: 0.4792 - val_accuracy: 0.7724 - val_loss: 0.5302
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8010 - loss: 0.4502 - val_accuracy: 0.7052 - val_loss: 0.6805
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7961 - loss: 0.4962 - val_accuracy: 0.7761 - val_loss: 0.5373
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7769 - loss: 0.5258 - val_accuracy: 0.7724 - val_loss: 0.5400
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8010 - loss: 0.4534 - val_accuracy: 0.7313 - val_loss: 0.6785
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7897 - loss: 0.5078 - val_accuracy: 0.7649 - val_loss: 0.5456
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8122 - loss: 0.4439 - val_accuracy: 0.7799 - val_loss: 0.5606
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7833 - loss: 0.5303 - val_accuracy: 0.7724 - val_loss: 0.5284
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7961 - loss: 0.4547 - val_accuracy: 0.7090 - val_loss: 0.7299
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7721 - loss: 0.5098 - val_accuracy: 0.7761 - val_loss: 0.5421
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7913 - loss: 0.4586 - val_accuracy: 0.7761 - val_loss: 0.5678
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8010 - loss: 0.4494 - val_accuracy: 0.6493 - val_loss: 0.7708
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4694 - val_accuracy: 0.7649 - val_loss: 0.5910
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8074 - loss: 0.4856 - val_accuracy: 0.7799 - val_loss: 0.5291
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8074 - loss: 0.4495 - val_accuracy: 0.7612 - val_loss: 0.5902
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8042 - loss: 0.4588 - val_accuracy: 0.7612 - val_loss: 0.6424
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7978 - loss: 0.4859 - val_accuracy: 0.7687 - val_loss: 0.5248
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7913 - loss: 0.4848 - val_accuracy: 0.7799 - val_loss: 0.5237
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 999us/step - accuracy: 0.8122 - loss: 0.4410 - val_accuracy: 0.7910 - val_loss: 0.5861
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.8186 - loss: 0.4565 - val_accuracy: 0.7724 - val_loss: 0.5371
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8186 - loss: 0.4314 - val_accuracy: 0.7799 - val_loss: 0.5260
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8170 - loss: 0.4460 - val_accuracy: 0.7724 - val_loss: 0.5509
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8042 - loss: 0.4801 - val_accuracy: 0.7761 - val_loss: 0.5319
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.8074 - loss: 0.4480 - val_accuracy: 0.7799 - val_loss: 0.5283
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7994 - loss: 0.4645 - val_accuracy: 0.7687 - val_loss: 0.5359
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4451 - val_accuracy: 0.7687 - val_loss: 0.5401
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8026 - loss: 0.4492 - val_accuracy: 0.7799 - val_loss: 0.5454
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8234 - loss: 0.4639 - val_accuracy: 0.7575 - val_loss: 0.6081
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8042 - loss: 0.4651 - val_accuracy: 0.7687 - val_loss: 0.5641
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8122 - loss: 0.4532 - val_accuracy: 0.7649 - val_loss: 0.6484
Epoch 153/5000

wandb: Agent Starting Run: dnhzuwek with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 11.5186 - val_accuracy: 0.6231 - val_loss: 0.8067
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.7142 - val_accuracy: 0.6231 - val_loss: 0.6980
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.6051 - loss: 0.6903 - val_accuracy: 0.6194 - val_loss: 0.6991
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6865 - val_accuracy: 0.6231 - val_loss: 0.6995
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6116 - loss: 0.6823 - val_accuracy: 0.6194 - val_loss: 0.6994
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6745 - val_accuracy: 0.6194 - val_loss: 0.6886
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6148 - loss: 0.6772 - val_accuracy: 0.6194 - val_loss: 0.6891
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6148 - loss: 0.6708 - val_accuracy: 0.6194 - val_loss: 0.6940
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.6148 - loss: 0.6698 - val_accuracy: 0.6194 - val_loss: 0.6886
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - accuracy: 0.6164 - loss: 0.6692 - val_accuracy: 0.6082 - val_loss: 0.6949
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.6148 - loss: 0.6677 - val_accuracy: 0.6082 - val_loss: 0.6982
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.6164 - loss: 0.6676 - val_accuracy: 0.6082 - val_loss: 0.6984
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6838
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 982us/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6082 - val_loss: 0.6898
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 963us/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6082 - val_loss: 0.7025
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6045 - val_loss: 0.6972
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6007 - val_loss: 0.7013
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6196 - loss: 0.6652 - val_accuracy: 0.6194 - val_loss: 0.6900
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6654 - val_accuracy: 0.6082 - val_loss: 0.7129
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6869
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6194 - val_loss: 0.6909
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.6196 - loss: 0.6633 - val_accuracy: 0.6119 - val_loss: 0.7089
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6180 - loss: 0.6663 - val_accuracy: 0.6082 - val_loss: 0.7085
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6196 - loss: 0.6656 - val_accuracy: 0.6119 - val_loss: 0.7007
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6119 - val_loss: 0.7000
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6082 - val_loss: 0.6975
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6007 - val_loss: 0.7153
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 830us/step - accuracy: 0.6228 - loss: 0.6648 - val_accuracy: 0.6082 - val_loss: 0.7085
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6119 - val_loss: 0.7044
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6119 - val_loss: 0.7104
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6157 - val_loss: 0.6975
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.7009
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6119 - val_loss: 0.7085
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6082 - val_loss: 0.7146
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6196 - loss: 0.6640 - val_accuracy: 0.6119 - val_loss: 0.7099
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6082 - val_loss: 0.7158
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6622 - val_accuracy: 0.6119 - val_loss: 0.7024
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6212 - loss: 0.6622 - val_accuracy: 0.6082 - val_loss: 0.7082
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.7090
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6082 - val_loss: 0.7095
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6082 - val_loss: 0.7167
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6196 - loss: 0.6622 - val_accuracy: 0.6119 - val_loss: 0.7061
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6082 - val_loss: 0.7138
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6082 - val_loss: 0.7174
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6119 - val_loss: 0.7113
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.7121
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.7094
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.6196 - loss: 0.6611 - val_accuracy: 0.6082 - val_loss: 0.7156
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6194 - val_loss: 0.7078
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6228 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7152
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6244 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7186
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6045 - val_loss: 0.7180
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6196 - loss: 0.6609 - val_accuracy: 0.6045 - val_loss: 0.7118
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6228 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.7157
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6082 - val_loss: 0.7220
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6007 - val_loss: 0.7206
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6157 - val_loss: 0.7093
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.7193
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7091
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6212 - loss: 0.6620 - val_accuracy: 0.6082 - val_loss: 0.7240
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6244 - loss: 0.6599 - val_accuracy: 0.6194 - val_loss: 0.7074
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6007 - val_loss: 0.7203
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 810us/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6082 - val_loss: 0.7256
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6119 - val_loss: 0.7204
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6228 - loss: 0.6602 - val_accuracy: 0.6045 - val_loss: 0.7292
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 815us/step - accuracy: 0.6244 - loss: 0.6600 - val_accuracy: 0.6045 - val_loss: 0.7316
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6228 - loss: 0.6590 - val_accuracy: 0.6157 - val_loss: 0.7230
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.6260 - loss: 0.6576 - val_accuracy: 0.6194 - val_loss: 0.7219
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6244 - loss: 0.6575 - val_accuracy: 0.6157 - val_loss: 0.7291
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6194 - val_loss: 0.7214
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.6292 - loss: 0.6571 - val_accuracy: 0.6194 - val_loss: 0.7207
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6276 - loss: 0.6576 - val_accuracy: 0.6119 - val_loss: 0.7199
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6276 - loss: 0.6571 - val_accuracy: 0.6082 - val_loss: 0.7234
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6260 - loss: 0.6556 - val_accuracy: 0.6082 - val_loss: 0.7254
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6244 - loss: 0.6567 - val_accuracy: 0.6119 - val_loss: 0.7318
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6292 - loss: 0.6553 - val_accuracy: 0.6157 - val_loss: 0.7236
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6276 - loss: 0.6562 - val_accuracy: 0.6194 - val_loss: 0.7251
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.6324 - loss: 0.6554 - val_accuracy: 0.6157 - val_loss: 0.7293
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.6308 - loss: 0.6559 - val_accuracy: 0.6119 - val_loss: 0.7334
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 977us/step - accuracy: 0.6308 - loss: 0.6556 - val_accuracy: 0.6231 - val_loss: 0.7197
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6557 - val_accuracy: 0.6157 - val_loss: 0.7311
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6276 - loss: 0.6555 - val_accuracy: 0.6082 - val_loss: 0.7360
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 812us/step - accuracy: 0.6292 - loss: 0.6550 - val_accuracy: 0.6231 - val_loss: 0.7225
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6212 - loss: 0.6588 - val_accuracy: 0.6231 - val_loss: 0.7168
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6260 - loss: 0.6554 - val_accuracy: 0.6157 - val_loss: 0.7227
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.6260 - loss: 0.6554 - val_accuracy: 0.6119 - val_loss: 0.7271
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 797us/step - accuracy: 0.6276 - loss: 0.6551 - val_accuracy: 0.6119 - val_loss: 0.7282
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.6260 - loss: 0.6549 - val_accuracy: 0.6082 - val_loss: 0.7317
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.6308 - loss: 0.6544 - val_accuracy: 0.6157 - val_loss: 0.7242
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6244 - loss: 0.6565 - val_accuracy: 0.6157 - val_loss: 0.7319
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 819us/step - accuracy: 0.6260 - loss: 0.6575 - val_accuracy: 0.6157 - val_loss: 0.7381
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6260 - loss: 0.6550 - val_accuracy: 0.6082 - val_loss: 0.7364
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.6308 - loss: 0.6545 - val_accuracy: 0.6194 - val_loss: 0.7291
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6260 - loss: 0.6545 - val_accuracy: 0.6119 - val_loss: 0.7358
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6260 - loss: 0.6560 - val_accuracy: 0.6082 - val_loss: 0.7330
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6244 - loss: 0.6560 - val_accuracy: 0.6157 - val_loss: 0.7329
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.6260 - loss: 0.6561 - val_accuracy: 0.6119 - val_loss: 0.7388
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6276 - loss: 0.6556 - val_accuracy: 0.6194 - val_loss: 0.7321
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.6276 - loss: 0.6539 - val_accuracy: 0.6119 - val_loss: 0.7427
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.6292 - loss: 0.6548 - val_accuracy: 0.6194 - val_loss: 0.7201
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6292 - loss: 0.6543 - val_accuracy: 0.6119 - val_loss: 0.7312
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.6260 - loss: 0.6541 - val_accuracy: 0.6157 - val_loss: 0.7335
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.6538 - val_accuracy: 0.6157 - val_loss: 0.7299
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6260 - loss: 0.6542 - val_accuracy: 0.6231 - val_loss: 0.7244
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.6260 - loss: 0.6559 - val_accuracy: 0.6119 - val_loss: 0.7323
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6212 - loss: 0.6583 - val_accuracy: 0.6119 - val_loss: 0.7364
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.6292 - loss: 0.6551 - val_accuracy: 0.6194 - val_loss: 0.7325
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.6260 - loss: 0.6554 - val_accuracy: 0.6157 - val_loss: 0.7395
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.6260 - loss: 0.6550 - val_accuracy: 0.6194 - val_loss: 0.7357
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - accuracy: 0.6260 - loss: 0.6569 - val_accuracy: 0.6194 - val_loss: 0.7447
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.6276 - loss: 0.6570 - val_accuracy: 0.6119 - val_loss: 0.7344
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.6308 - loss: 0.6545 - val_accuracy: 0.6119 - val_loss: 0.7320
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.6292 - loss: 0.6537 - val_accuracy: 0.6231 - val_loss: 0.7301
Epoch 113: early stopping

wandb: Agent Starting Run: dxlos305 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4928 - loss: 8.0350 - val_accuracy: 0.6716 - val_loss: 0.8489
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5955 - loss: 1.1530 - val_accuracy: 0.7127 - val_loss: 0.6649
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 1.0691 - val_accuracy: 0.7239 - val_loss: 0.6404
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step - accuracy: 0.6228 - loss: 0.9841 - val_accuracy: 0.6381 - val_loss: 0.8161
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6244 - loss: 0.9622 - val_accuracy: 0.4776 - val_loss: 1.1418
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 969us/step - accuracy: 0.6196 - loss: 1.0530 - val_accuracy: 0.6866 - val_loss: 0.6829
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.9467 - val_accuracy: 0.7164 - val_loss: 0.5933
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.9923 - val_accuracy: 0.4440 - val_loss: 1.4215
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6324 - loss: 0.8712 - val_accuracy: 0.6828 - val_loss: 1.0207
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6083 - loss: 1.0159 - val_accuracy: 0.6828 - val_loss: 0.7679
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.9058 - val_accuracy: 0.4478 - val_loss: 1.4553
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.6437 - loss: 0.9673 - val_accuracy: 0.7425 - val_loss: 0.5657
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 985us/step - accuracy: 0.6533 - loss: 0.8284 - val_accuracy: 0.7537 - val_loss: 0.5456
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 980us/step - accuracy: 0.6581 - loss: 0.9039 - val_accuracy: 0.7649 - val_loss: 0.5312
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.8225 - val_accuracy: 0.4216 - val_loss: 1.8829
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.6453 - loss: 0.9270 - val_accuracy: 0.6940 - val_loss: 0.6233
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.6854 - loss: 0.8359 - val_accuracy: 0.6567 - val_loss: 0.7504
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6581 - loss: 0.9285 - val_accuracy: 0.7239 - val_loss: 0.6132
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.6966 - loss: 0.8079 - val_accuracy: 0.6567 - val_loss: 0.7371
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 964us/step - accuracy: 0.6934 - loss: 0.8184 - val_accuracy: 0.4515 - val_loss: 1.3110
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6934 - loss: 0.7526 - val_accuracy: 0.7276 - val_loss: 0.5835
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.6902 - loss: 0.7613 - val_accuracy: 0.7761 - val_loss: 0.4963
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7223 - loss: 0.7280 - val_accuracy: 0.7463 - val_loss: 0.4972
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7111 - loss: 0.7891 - val_accuracy: 0.6418 - val_loss: 1.3939
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.6838 - loss: 0.7785 - val_accuracy: 0.7052 - val_loss: 0.6104
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.6950 - loss: 0.7591 - val_accuracy: 0.6754 - val_loss: 0.8116
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.7853 - val_accuracy: 0.7313 - val_loss: 0.5729
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.6950 - loss: 0.8080 - val_accuracy: 0.7612 - val_loss: 0.5098
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6966 - loss: 0.7818 - val_accuracy: 0.7612 - val_loss: 0.5235
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7175 - loss: 0.7507 - val_accuracy: 0.7687 - val_loss: 0.4912
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.6806 - loss: 0.8008 - val_accuracy: 0.6940 - val_loss: 0.6411
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7047 - loss: 0.7124 - val_accuracy: 0.6306 - val_loss: 1.1923
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.6966 - loss: 0.7518 - val_accuracy: 0.7015 - val_loss: 0.5882
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.6709 - loss: 0.7282 - val_accuracy: 0.7724 - val_loss: 0.4935
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.6902 - loss: 0.7467 - val_accuracy: 0.7313 - val_loss: 0.5953
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7079 - loss: 0.7434 - val_accuracy: 0.6866 - val_loss: 0.8401
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7255 - loss: 0.7143 - val_accuracy: 0.7164 - val_loss: 0.6339
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 821us/step - accuracy: 0.7111 - loss: 0.7426 - val_accuracy: 0.6343 - val_loss: 0.9996
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7030 - loss: 0.7430 - val_accuracy: 0.6604 - val_loss: 0.8614
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7432 - loss: 0.6859 - val_accuracy: 0.5709 - val_loss: 0.8889
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7143 - loss: 0.7155 - val_accuracy: 0.6679 - val_loss: 0.9554
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 958us/step - accuracy: 0.7014 - loss: 0.7322 - val_accuracy: 0.7537 - val_loss: 0.4795
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7239 - loss: 0.6872 - val_accuracy: 0.6866 - val_loss: 0.7186
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.6902 - loss: 0.7670 - val_accuracy: 0.6306 - val_loss: 1.6548
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7496 - loss: 0.6688 - val_accuracy: 0.7463 - val_loss: 0.5417
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7480 - loss: 0.6249 - val_accuracy: 0.6791 - val_loss: 0.7020
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.7340 - val_accuracy: 0.6866 - val_loss: 0.9176
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7335 - loss: 0.6780 - val_accuracy: 0.6828 - val_loss: 0.6519
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7271 - loss: 0.7049 - val_accuracy: 0.7276 - val_loss: 0.5887
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7384 - loss: 0.6305 - val_accuracy: 0.7537 - val_loss: 0.4987
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7191 - loss: 0.6914 - val_accuracy: 0.7687 - val_loss: 0.4696
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7239 - loss: 0.6720 - val_accuracy: 0.7052 - val_loss: 0.6240
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7480 - loss: 0.6408 - val_accuracy: 0.7313 - val_loss: 0.6396
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7287 - loss: 0.7215 - val_accuracy: 0.7761 - val_loss: 0.4798
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7400 - loss: 0.5970 - val_accuracy: 0.7500 - val_loss: 0.5456
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7400 - loss: 0.6754 - val_accuracy: 0.7463 - val_loss: 0.5534
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7464 - loss: 0.6576 - val_accuracy: 0.6679 - val_loss: 0.7624
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7384 - loss: 0.6543 - val_accuracy: 0.7090 - val_loss: 0.8179
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7416 - loss: 0.5959 - val_accuracy: 0.6530 - val_loss: 1.0799
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7271 - loss: 0.6745 - val_accuracy: 0.7052 - val_loss: 0.6487
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7432 - loss: 0.6244 - val_accuracy: 0.5000 - val_loss: 1.2325
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7223 - loss: 0.6539 - val_accuracy: 0.7351 - val_loss: 0.5648
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7464 - loss: 0.6196 - val_accuracy: 0.7836 - val_loss: 0.4895
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7512 - loss: 0.5825 - val_accuracy: 0.7463 - val_loss: 0.5367
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7223 - loss: 0.6574 - val_accuracy: 0.7836 - val_loss: 0.4958
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7592 - loss: 0.6589 - val_accuracy: 0.7799 - val_loss: 0.5144
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7448 - loss: 0.6494 - val_accuracy: 0.7015 - val_loss: 0.8320
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7480 - loss: 0.6381 - val_accuracy: 0.6754 - val_loss: 1.0128
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7576 - loss: 0.6106 - val_accuracy: 0.5560 - val_loss: 0.9011
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6536 - val_accuracy: 0.7799 - val_loss: 0.4567
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7448 - loss: 0.6224 - val_accuracy: 0.7873 - val_loss: 0.4818
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7432 - loss: 0.6213 - val_accuracy: 0.7500 - val_loss: 0.5136
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7303 - loss: 0.6608 - val_accuracy: 0.7313 - val_loss: 0.5796
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7464 - loss: 0.6259 - val_accuracy: 0.7799 - val_loss: 0.4630
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7624 - loss: 0.6068 - val_accuracy: 0.7724 - val_loss: 0.4607
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7223 - loss: 0.6443 - val_accuracy: 0.7649 - val_loss: 0.4898
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7528 - loss: 0.5650 - val_accuracy: 0.7687 - val_loss: 0.4805
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7480 - loss: 0.6301 - val_accuracy: 0.7873 - val_loss: 0.4631
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7480 - loss: 0.5881 - val_accuracy: 0.7873 - val_loss: 0.4620
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7480 - loss: 0.6109 - val_accuracy: 0.7575 - val_loss: 0.5056
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7624 - loss: 0.5465 - val_accuracy: 0.7799 - val_loss: 0.5151
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7159 - loss: 0.6319 - val_accuracy: 0.6343 - val_loss: 1.1639
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7608 - loss: 0.6208 - val_accuracy: 0.4925 - val_loss: 1.3667
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7496 - loss: 0.5901 - val_accuracy: 0.7724 - val_loss: 0.4786
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7721 - loss: 0.5580 - val_accuracy: 0.7761 - val_loss: 0.4824
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7640 - loss: 0.6206 - val_accuracy: 0.7799 - val_loss: 0.4654
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7673 - loss: 0.5665 - val_accuracy: 0.7239 - val_loss: 0.6230
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7368 - loss: 0.5871 - val_accuracy: 0.7649 - val_loss: 0.5202
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7544 - loss: 0.5818 - val_accuracy: 0.7873 - val_loss: 0.4775
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7544 - loss: 0.5957 - val_accuracy: 0.7836 - val_loss: 0.5606
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7657 - loss: 0.5589 - val_accuracy: 0.7575 - val_loss: 0.5392
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5832 - val_accuracy: 0.7239 - val_loss: 0.6118
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7352 - loss: 0.5896 - val_accuracy: 0.7575 - val_loss: 0.5274
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7432 - loss: 0.5931 - val_accuracy: 0.7052 - val_loss: 0.7985
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.7817 - loss: 0.5343 - val_accuracy: 0.7761 - val_loss: 0.5135
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7657 - loss: 0.5479 - val_accuracy: 0.7910 - val_loss: 0.4873
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7881 - loss: 0.5121 - val_accuracy: 0.6381 - val_loss: 0.7334
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 817us/step - accuracy: 0.7721 - loss: 0.5954 - val_accuracy: 0.7463 - val_loss: 0.6176
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7673 - loss: 0.5610 - val_accuracy: 0.7836 - val_loss: 0.4771
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 816us/step - accuracy: 0.7560 - loss: 0.5777 - val_accuracy: 0.6754 - val_loss: 0.8968
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7689 - loss: 0.5424 - val_accuracy: 0.7649 - val_loss: 0.5021
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 973us/step - accuracy: 0.7737 - loss: 0.5762 - val_accuracy: 0.7761 - val_loss: 0.4812
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 802us/step - accuracy: 0.7673 - loss: 0.5410 - val_accuracy: 0.6940 - val_loss: 0.7518
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7592 - loss: 0.6056 - val_accuracy: 0.7761 - val_loss: 0.4922
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 811us/step - accuracy: 0.7769 - loss: 0.5219 - val_accuracy: 0.7724 - val_loss: 0.4772
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7657 - loss: 0.5610 - val_accuracy: 0.7537 - val_loss: 0.5766
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7544 - loss: 0.5918 - val_accuracy: 0.7910 - val_loss: 0.5042
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7849 - loss: 0.5386 - val_accuracy: 0.7761 - val_loss: 0.5138
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7881 - loss: 0.5063 - val_accuracy: 0.6679 - val_loss: 0.7272
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7384 - loss: 0.6022 - val_accuracy: 0.7873 - val_loss: 0.5096
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7785 - loss: 0.5577 - val_accuracy: 0.7724 - val_loss: 0.4818
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7721 - loss: 0.5486 - val_accuracy: 0.7836 - val_loss: 0.4805
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5682 - val_accuracy: 0.7276 - val_loss: 0.6631
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7657 - loss: 0.5520 - val_accuracy: 0.7910 - val_loss: 0.4935
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7576 - loss: 0.5533 - val_accuracy: 0.7910 - val_loss: 0.5003
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7801 - loss: 0.5259 - val_accuracy: 0.7687 - val_loss: 0.4908
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7849 - loss: 0.5246 - val_accuracy: 0.7836 - val_loss: 0.4899
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 806us/step - accuracy: 0.7560 - loss: 0.5545 - val_accuracy: 0.6866 - val_loss: 0.7425
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7512 - loss: 0.5687 - val_accuracy: 0.7500 - val_loss: 0.5721
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - accuracy: 0.7673 - loss: 0.5372 - val_accuracy: 0.6604 - val_loss: 0.7185
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 820us/step - accuracy: 0.7528 - loss: 0.5811 - val_accuracy: 0.7687 - val_loss: 0.4887
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 831us/step - accuracy: 0.7833 - loss: 0.5076 - val_accuracy: 0.7799 - val_loss: 0.5038
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7560 - loss: 0.5339 - val_accuracy: 0.7537 - val_loss: 0.5359
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7817 - loss: 0.5277 - val_accuracy: 0.7799 - val_loss: 0.5109
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7544 - loss: 0.5693 - val_accuracy: 0.7799 - val_loss: 0.5034
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7897 - loss: 0.5253 - val_accuracy: 0.7761 - val_loss: 0.4896
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.7881 - loss: 0.4969 - val_accuracy: 0.7836 - val_loss: 0.4860
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.7528 - loss: 0.5356 - val_accuracy: 0.7388 - val_loss: 0.6087
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7817 - loss: 0.5091 - val_accuracy: 0.7873 - val_loss: 0.5155
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7737 - loss: 0.5305 - val_accuracy: 0.7873 - val_loss: 0.4986
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7560 - loss: 0.5654 - val_accuracy: 0.5634 - val_loss: 0.8848
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 825us/step - accuracy: 0.7624 - loss: 0.5191 - val_accuracy: 0.7090 - val_loss: 0.7536
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5148 - val_accuracy: 0.7724 - val_loss: 0.4886
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7913 - loss: 0.5279 - val_accuracy: 0.7761 - val_loss: 0.5065
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.7705 - loss: 0.5498 - val_accuracy: 0.7910 - val_loss: 0.5230
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 824us/step - accuracy: 0.7849 - loss: 0.4968 - val_accuracy: 0.7761 - val_loss: 0.4849
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7608 - loss: 0.5519 - val_accuracy: 0.7799 - val_loss: 0.5048
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7897 - loss: 0.4848 - val_accuracy: 0.8022 - val_loss: 0.5120
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.7833 - loss: 0.5272 - val_accuracy: 0.7836 - val_loss: 0.4989
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 829us/step - accuracy: 0.7849 - loss: 0.5150 - val_accuracy: 0.7351 - val_loss: 0.6634
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7849 - loss: 0.5443 - val_accuracy: 0.7836 - val_loss: 0.5158
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7657 - loss: 0.5223 - val_accuracy: 0.7799 - val_loss: 0.5135
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7897 - loss: 0.4790 - val_accuracy: 0.6642 - val_loss: 0.9946
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.7849 - loss: 0.5472 - val_accuracy: 0.7948 - val_loss: 0.5389
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7801 - loss: 0.5042 - val_accuracy: 0.7575 - val_loss: 0.5449
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7769 - loss: 0.4858 - val_accuracy: 0.7910 - val_loss: 0.5552
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7737 - loss: 0.5361 - val_accuracy: 0.7873 - val_loss: 0.5021
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 813us/step - accuracy: 0.7657 - loss: 0.5363 - val_accuracy: 0.7500 - val_loss: 0.5587
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7673 - loss: 0.5210 - val_accuracy: 0.6828 - val_loss: 0.7585
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 823us/step - accuracy: 0.7785 - loss: 0.5206 - val_accuracy: 0.7799 - val_loss: 0.4970
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7849 - loss: 0.4865 - val_accuracy: 0.7724 - val_loss: 0.5043
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5185 - val_accuracy: 0.7761 - val_loss: 0.5760
Epoch 153/5000

wandb: Agent Starting Run: awm3ywi7 with config:
wandb: 	batch_size: 16
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4478 - loss: 5.0916 - val_accuracy: 0.2985 - val_loss: 3.5250
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4382 - loss: 1.9280 - val_accuracy: 0.5373 - val_loss: 1.1480
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.9116 - val_accuracy: 0.7015 - val_loss: 0.6073
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.7175 - loss: 0.6331 - val_accuracy: 0.8172 - val_loss: 0.5682
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.6421 - loss: 0.7160 - val_accuracy: 0.6791 - val_loss: 0.8376
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.7107 - val_accuracy: 0.7500 - val_loss: 0.5390
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5858 - val_accuracy: 0.6940 - val_loss: 0.6576
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6206 - val_accuracy: 0.5858 - val_loss: 0.7484
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5759 - val_accuracy: 0.6791 - val_loss: 0.6488
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.6854 - loss: 0.6433 - val_accuracy: 0.6679 - val_loss: 0.9021
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5692 - val_accuracy: 0.7910 - val_loss: 0.5627
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 986us/step - accuracy: 0.7432 - loss: 0.5608 - val_accuracy: 0.7836 - val_loss: 0.5391
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 997us/step - accuracy: 0.6886 - loss: 0.8402 - val_accuracy: 0.7351 - val_loss: 0.5532
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 978us/step - accuracy: 0.6501 - loss: 0.9112 - val_accuracy: 0.7388 - val_loss: 0.5661
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6030 - val_accuracy: 0.6940 - val_loss: 0.7886
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5710 - val_accuracy: 0.7500 - val_loss: 0.5606
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.7223 - loss: 0.5997 - val_accuracy: 0.6866 - val_loss: 0.6377
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 962us/step - accuracy: 0.7223 - loss: 0.5759 - val_accuracy: 0.7425 - val_loss: 0.5875
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.7432 - loss: 0.5789 - val_accuracy: 0.7873 - val_loss: 0.5769
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7721 - loss: 0.5311 - val_accuracy: 0.7388 - val_loss: 0.5680
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.7464 - loss: 0.6020 - val_accuracy: 0.6903 - val_loss: 0.6443
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 993us/step - accuracy: 0.7127 - loss: 0.6296 - val_accuracy: 0.7351 - val_loss: 0.5632
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7737 - loss: 0.5202 - val_accuracy: 0.6940 - val_loss: 0.6711
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7175 - loss: 0.6038 - val_accuracy: 0.6754 - val_loss: 0.9653
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 848us/step - accuracy: 0.7014 - loss: 0.6771 - val_accuracy: 0.6828 - val_loss: 0.6607
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7608 - loss: 0.5479 - val_accuracy: 0.7164 - val_loss: 0.6245
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7319 - loss: 0.5797 - val_accuracy: 0.5000 - val_loss: 1.0603
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7464 - loss: 0.5585 - val_accuracy: 0.7836 - val_loss: 0.6071
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7608 - loss: 0.5282 - val_accuracy: 0.6119 - val_loss: 0.7857
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7014 - loss: 0.7544 - val_accuracy: 0.7724 - val_loss: 0.5362
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7673 - loss: 0.4954 - val_accuracy: 0.7276 - val_loss: 0.6023
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.7287 - loss: 0.6908 - val_accuracy: 0.7761 - val_loss: 0.5590
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7705 - loss: 0.5781 - val_accuracy: 0.7537 - val_loss: 0.5962
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7833 - loss: 0.5094 - val_accuracy: 0.7276 - val_loss: 0.6254
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7769 - loss: 0.5289 - val_accuracy: 0.7724 - val_loss: 0.5512
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7576 - loss: 0.5480 - val_accuracy: 0.7015 - val_loss: 0.6500
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7865 - loss: 0.4959 - val_accuracy: 0.6530 - val_loss: 0.6996
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7721 - loss: 0.5237 - val_accuracy: 0.7463 - val_loss: 0.5793
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7544 - loss: 0.5666 - val_accuracy: 0.7687 - val_loss: 0.5474
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7881 - loss: 0.4926 - val_accuracy: 0.7687 - val_loss: 0.5343
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7512 - loss: 0.5602 - val_accuracy: 0.7836 - val_loss: 0.5914
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7897 - loss: 0.5022 - val_accuracy: 0.7761 - val_loss: 0.5624
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 991us/step - accuracy: 0.7769 - loss: 0.5254 - val_accuracy: 0.7575 - val_loss: 0.5789
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7400 - loss: 0.5847 - val_accuracy: 0.7649 - val_loss: 0.5414
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7287 - loss: 0.6430 - val_accuracy: 0.6493 - val_loss: 0.7160
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7191 - loss: 0.6836 - val_accuracy: 0.7015 - val_loss: 0.7659
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.7865 - loss: 0.5066 - val_accuracy: 0.7687 - val_loss: 0.5261
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 974us/step - accuracy: 0.7127 - loss: 0.6997 - val_accuracy: 0.7052 - val_loss: 0.6770
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7544 - loss: 0.5643 - val_accuracy: 0.7388 - val_loss: 0.6047
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 839us/step - accuracy: 0.7448 - loss: 0.6035 - val_accuracy: 0.7761 - val_loss: 0.5771
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7737 - loss: 0.5783 - val_accuracy: 0.7649 - val_loss: 0.6147
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.7897 - loss: 0.4749 - val_accuracy: 0.7649 - val_loss: 0.5445
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.7448 - loss: 0.6389 - val_accuracy: 0.7724 - val_loss: 0.5468
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.7785 - loss: 0.5152 - val_accuracy: 0.7537 - val_loss: 0.6245
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7881 - loss: 0.4976 - val_accuracy: 0.7649 - val_loss: 0.5325
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7689 - loss: 0.5445 - val_accuracy: 0.7052 - val_loss: 0.6697
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7448 - loss: 0.5864 - val_accuracy: 0.7687 - val_loss: 0.5360
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7592 - loss: 0.5457 - val_accuracy: 0.6940 - val_loss: 0.7068
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7576 - loss: 0.5470 - val_accuracy: 0.5522 - val_loss: 1.0121
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7127 - loss: 0.6807 - val_accuracy: 0.7724 - val_loss: 0.5298
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7352 - loss: 0.6609 - val_accuracy: 0.7612 - val_loss: 0.5472
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.7737 - loss: 0.4983 - val_accuracy: 0.7015 - val_loss: 0.6685
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7464 - loss: 0.5897 - val_accuracy: 0.7537 - val_loss: 0.6116
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7673 - loss: 0.5546 - val_accuracy: 0.7649 - val_loss: 0.5337
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7929 - loss: 0.4792 - val_accuracy: 0.7649 - val_loss: 0.5566
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7929 - loss: 0.4904 - val_accuracy: 0.6978 - val_loss: 0.6997
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.7801 - loss: 0.5102 - val_accuracy: 0.7388 - val_loss: 0.6475
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.8010 - loss: 0.4745 - val_accuracy: 0.7649 - val_loss: 0.5491
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.7785 - loss: 0.5546 - val_accuracy: 0.7649 - val_loss: 0.5387
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.7897 - loss: 0.4860 - val_accuracy: 0.7090 - val_loss: 0.7108
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7769 - loss: 0.5365 - val_accuracy: 0.7612 - val_loss: 0.5824
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5401 - val_accuracy: 0.7649 - val_loss: 0.5489
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8010 - loss: 0.4831 - val_accuracy: 0.7687 - val_loss: 0.6152
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7945 - loss: 0.4868 - val_accuracy: 0.7724 - val_loss: 0.5390
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 832us/step - accuracy: 0.8026 - loss: 0.4836 - val_accuracy: 0.7687 - val_loss: 0.6272
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.7945 - loss: 0.4807 - val_accuracy: 0.7649 - val_loss: 0.5530
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7271 - loss: 0.7084 - val_accuracy: 0.5858 - val_loss: 0.8565
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.7512 - loss: 0.5903 - val_accuracy: 0.7575 - val_loss: 0.5422
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 818us/step - accuracy: 0.7576 - loss: 0.6766 - val_accuracy: 0.7836 - val_loss: 0.5942
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.7721 - loss: 0.5253 - val_accuracy: 0.7612 - val_loss: 0.5799
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7801 - loss: 0.5081 - val_accuracy: 0.7799 - val_loss: 0.5944
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7400 - loss: 0.6030 - val_accuracy: 0.5858 - val_loss: 0.9667
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.7159 - loss: 0.7088 - val_accuracy: 0.7612 - val_loss: 0.6431
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7608 - loss: 0.5345 - val_accuracy: 0.7687 - val_loss: 0.5427
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7689 - loss: 0.5369 - val_accuracy: 0.7388 - val_loss: 0.6660
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.7544 - loss: 0.5613 - val_accuracy: 0.7537 - val_loss: 0.6471
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7785 - loss: 0.4970 - val_accuracy: 0.7388 - val_loss: 0.6285
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7849 - loss: 0.5092 - val_accuracy: 0.7649 - val_loss: 0.5678
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8154 - loss: 0.4529 - val_accuracy: 0.7612 - val_loss: 0.5763
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.7496 - loss: 0.6026 - val_accuracy: 0.7201 - val_loss: 0.6833
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7865 - loss: 0.5315 - val_accuracy: 0.7687 - val_loss: 0.5534
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7721 - loss: 0.4941 - val_accuracy: 0.7799 - val_loss: 0.5994
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.7881 - loss: 0.5096 - val_accuracy: 0.7575 - val_loss: 0.5802
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5510 - val_accuracy: 0.7201 - val_loss: 0.7024
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.7961 - loss: 0.4629 - val_accuracy: 0.7724 - val_loss: 0.6317
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7929 - loss: 0.4784 - val_accuracy: 0.7687 - val_loss: 0.5770
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7705 - loss: 0.5442 - val_accuracy: 0.7687 - val_loss: 0.5688
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 968us/step - accuracy: 0.7239 - loss: 0.6442 - val_accuracy: 0.7761 - val_loss: 0.5641
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7945 - loss: 0.4833 - val_accuracy: 0.7687 - val_loss: 0.7022
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7560 - loss: 0.5497 - val_accuracy: 0.7537 - val_loss: 0.6286
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7785 - loss: 0.5269 - val_accuracy: 0.7239 - val_loss: 0.6933
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7833 - loss: 0.5437 - val_accuracy: 0.7649 - val_loss: 0.5837
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 941us/step - accuracy: 0.7817 - loss: 0.5505 - val_accuracy: 0.7015 - val_loss: 0.7852
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.7335 - loss: 0.6850 - val_accuracy: 0.7425 - val_loss: 0.6789
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7640 - loss: 0.5603 - val_accuracy: 0.6866 - val_loss: 0.7106
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7865 - loss: 0.4863 - val_accuracy: 0.7687 - val_loss: 0.6406
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7063 - loss: 0.7119 - val_accuracy: 0.7687 - val_loss: 0.5779
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7913 - loss: 0.5250 - val_accuracy: 0.7313 - val_loss: 0.7039
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.7833 - loss: 0.5068 - val_accuracy: 0.7687 - val_loss: 0.6183
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8026 - loss: 0.4764 - val_accuracy: 0.7724 - val_loss: 0.6074
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.7801 - loss: 0.5380 - val_accuracy: 0.6231 - val_loss: 1.8403
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6902 - loss: 0.9324 - val_accuracy: 0.7164 - val_loss: 0.7751
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7400 - loss: 0.5875 - val_accuracy: 0.7649 - val_loss: 0.6405
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7785 - loss: 0.5241 - val_accuracy: 0.7612 - val_loss: 0.6089
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4765 - val_accuracy: 0.7575 - val_loss: 0.5931
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 894us/step - accuracy: 0.7978 - loss: 0.4738 - val_accuracy: 0.7761 - val_loss: 0.6466
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7753 - loss: 0.5212 - val_accuracy: 0.7127 - val_loss: 0.7751
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7913 - loss: 0.4871 - val_accuracy: 0.7687 - val_loss: 0.5911
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7785 - loss: 0.5351 - val_accuracy: 0.7649 - val_loss: 0.5919
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7753 - loss: 0.5395 - val_accuracy: 0.7276 - val_loss: 0.7233
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7673 - loss: 0.4955 - val_accuracy: 0.6269 - val_loss: 0.8843
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4908 - val_accuracy: 0.7687 - val_loss: 0.5920
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.7913 - loss: 0.5010 - val_accuracy: 0.7612 - val_loss: 0.6009
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7833 - loss: 0.4910 - val_accuracy: 0.7761 - val_loss: 0.6792
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8042 - loss: 0.4737 - val_accuracy: 0.7687 - val_loss: 0.6374
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8026 - loss: 0.4499 - val_accuracy: 0.7649 - val_loss: 0.6073
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7817 - loss: 0.4945 - val_accuracy: 0.7724 - val_loss: 0.6026
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8154 - loss: 0.4618 - val_accuracy: 0.7687 - val_loss: 0.6790
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.7897 - loss: 0.4859 - val_accuracy: 0.7687 - val_loss: 0.6064
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.7994 - loss: 0.4688 - val_accuracy: 0.7761 - val_loss: 0.6064
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8058 - loss: 0.4668 - val_accuracy: 0.7612 - val_loss: 0.6545
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7978 - loss: 0.4607 - val_accuracy: 0.7575 - val_loss: 0.6309
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - accuracy: 0.7913 - loss: 0.4798 - val_accuracy: 0.7761 - val_loss: 0.6128
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.7913 - loss: 0.4855 - val_accuracy: 0.7649 - val_loss: 0.6162
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5060 - val_accuracy: 0.7687 - val_loss: 0.6331
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.7945 - loss: 0.4831 - val_accuracy: 0.7090 - val_loss: 0.7269
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7753 - loss: 0.5326 - val_accuracy: 0.7015 - val_loss: 0.8023
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.7753 - loss: 0.5097 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7560 - loss: 0.5611 - val_accuracy: 0.7799 - val_loss: 0.6897
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7833 - loss: 0.4988 - val_accuracy: 0.7575 - val_loss: 0.6452
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8074 - loss: 0.4568 - val_accuracy: 0.7575 - val_loss: 0.6324
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7785 - loss: 0.5438 - val_accuracy: 0.7836 - val_loss: 0.6864
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 853us/step - accuracy: 0.7544 - loss: 0.5558 - val_accuracy: 0.7500 - val_loss: 0.6864
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7865 - loss: 0.4838 - val_accuracy: 0.7537 - val_loss: 0.6909
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 886us/step - accuracy: 0.7881 - loss: 0.4738 - val_accuracy: 0.7612 - val_loss: 0.6266
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8138 - loss: 0.4699 - val_accuracy: 0.7537 - val_loss: 0.6845
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.7849 - loss: 0.4842 - val_accuracy: 0.7239 - val_loss: 0.7978
Epoch 147: early stopping

wandb: Agent Starting Run: 1aibgnse with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5859 - loss: 5.5675 - val_accuracy: 0.6269 - val_loss: 0.7063
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.7153 - val_accuracy: 0.6269 - val_loss: 0.6983
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.7081 - val_accuracy: 0.6343 - val_loss: 0.6922
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.7022 - val_accuracy: 0.6343 - val_loss: 0.6877
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6974 - val_accuracy: 0.6343 - val_loss: 0.6843
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6927 - val_accuracy: 0.6343 - val_loss: 0.6811
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6891 - val_accuracy: 0.6343 - val_loss: 0.6785
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6863 - val_accuracy: 0.6343 - val_loss: 0.6763
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6843 - val_accuracy: 0.6306 - val_loss: 0.6748
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6828 - val_accuracy: 0.6306 - val_loss: 0.6733
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6816 - val_accuracy: 0.6306 - val_loss: 0.6718
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6802 - val_accuracy: 0.6306 - val_loss: 0.6705
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6791 - val_accuracy: 0.6306 - val_loss: 0.6695
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6782 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6773 - val_accuracy: 0.6306 - val_loss: 0.6673
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6765 - val_accuracy: 0.6306 - val_loss: 0.6665
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6758 - val_accuracy: 0.6306 - val_loss: 0.6658
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6751 - val_accuracy: 0.6306 - val_loss: 0.6651
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6746 - val_accuracy: 0.6306 - val_loss: 0.6645
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6740 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6736 - val_accuracy: 0.6306 - val_loss: 0.6634
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6732 - val_accuracy: 0.6306 - val_loss: 0.6629
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6728 - val_accuracy: 0.6306 - val_loss: 0.6628
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6724 - val_accuracy: 0.6306 - val_loss: 0.6622
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6721 - val_accuracy: 0.6306 - val_loss: 0.6617
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6716 - val_accuracy: 0.6306 - val_loss: 0.6612
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6715 - val_accuracy: 0.6306 - val_loss: 0.6608
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6712 - val_accuracy: 0.6343 - val_loss: 0.6604
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6709 - val_accuracy: 0.6343 - val_loss: 0.6601
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6707 - val_accuracy: 0.6343 - val_loss: 0.6597
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6704 - val_accuracy: 0.6343 - val_loss: 0.6593
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6702 - val_accuracy: 0.6343 - val_loss: 0.6590
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6700 - val_accuracy: 0.6343 - val_loss: 0.6589
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6699 - val_accuracy: 0.6343 - val_loss: 0.6586
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6697 - val_accuracy: 0.6343 - val_loss: 0.6583
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6695 - val_accuracy: 0.6343 - val_loss: 0.6580
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6694 - val_accuracy: 0.6343 - val_loss: 0.6577
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6693 - val_accuracy: 0.6343 - val_loss: 0.6576
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6692 - val_accuracy: 0.6343 - val_loss: 0.6574
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6690 - val_accuracy: 0.6343 - val_loss: 0.6571
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6688 - val_accuracy: 0.6343 - val_loss: 0.6570
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6688 - val_accuracy: 0.6343 - val_loss: 0.6569
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6343 - val_loss: 0.6565
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6343 - val_loss: 0.6564
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6685 - val_accuracy: 0.6343 - val_loss: 0.6564
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6343 - val_loss: 0.6562
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6343 - val_loss: 0.6561
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6343 - val_loss: 0.6559
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6343 - val_loss: 0.6559
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6681 - val_accuracy: 0.6343 - val_loss: 0.6558
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6680 - val_accuracy: 0.6343 - val_loss: 0.6557
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6680 - val_accuracy: 0.6343 - val_loss: 0.6554
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6680 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6679 - val_accuracy: 0.6343 - val_loss: 0.6557
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6679 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6554
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6554
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6553
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6676 - val_accuracy: 0.6343 - val_loss: 0.6551
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6343 - val_loss: 0.6551
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6343 - val_loss: 0.6547
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6675 - val_accuracy: 0.6343 - val_loss: 0.6547
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6674 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6674 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6673 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6673 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6672 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6671 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6672 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6671 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6671 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6669 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6669 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6343 - val_loss: 0.6542
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6343 - val_loss: 0.6542
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6543
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6343 - val_loss: 0.6544
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6545
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6343 - val_loss: 0.6546
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6547
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6343 - val_loss: 0.6548
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6548
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6548
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6549
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6549
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6550
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6550
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6551
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6552
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6552
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6553
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6553
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.6556
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6557
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6558
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6559
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6560
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6561
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6562
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6562
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6562
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6563
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6343 - val_loss: 0.6566
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.6343 - val_loss: 0.6566
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6565
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6566
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6568
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.6569
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.6570
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6571
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6572
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6574
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.6571
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6574
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6574
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6575
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6575
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6577
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6579
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6575
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6575
Epoch 155/5000

wandb: Agent Starting Run: 7gntnqss with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6116 - loss: 10.4972 - val_accuracy: 0.6082 - val_loss: 4.9394
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4350 - loss: 3.5203 - val_accuracy: 0.5373 - val_loss: 3.6301
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4013 - loss: 3.1083 - val_accuracy: 0.5560 - val_loss: 3.4313
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4077 - loss: 2.8082 - val_accuracy: 0.4440 - val_loss: 2.8975
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3965 - loss: 2.4895 - val_accuracy: 0.5336 - val_loss: 2.7007
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4238 - loss: 2.1941 - val_accuracy: 0.4366 - val_loss: 2.2547
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4173 - loss: 1.9500 - val_accuracy: 0.4440 - val_loss: 1.9892
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4125 - loss: 1.7507 - val_accuracy: 0.4963 - val_loss: 1.7942
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4494 - loss: 1.5625 - val_accuracy: 0.2799 - val_loss: 1.6006
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4254 - loss: 1.3871 - val_accuracy: 0.2799 - val_loss: 1.5668
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4366 - loss: 1.2454 - val_accuracy: 0.5224 - val_loss: 1.2458
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4430 - loss: 1.0878 - val_accuracy: 0.4701 - val_loss: 1.0608
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4430 - loss: 0.9928 - val_accuracy: 0.3731 - val_loss: 0.9545
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4831 - loss: 0.8631 - val_accuracy: 0.5634 - val_loss: 0.8910
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5185 - loss: 0.8085 - val_accuracy: 0.5896 - val_loss: 0.8162
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5570 - loss: 0.7477 - val_accuracy: 0.5933 - val_loss: 0.7144
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 0.7270 - val_accuracy: 0.4216 - val_loss: 0.8324
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5714 - loss: 0.7147 - val_accuracy: 0.4291 - val_loss: 0.8427
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 0.6961 - val_accuracy: 0.6903 - val_loss: 0.6350
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6792 - val_accuracy: 0.4216 - val_loss: 0.8366
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6484 - val_accuracy: 0.6567 - val_loss: 0.6568
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6873 - val_accuracy: 0.7090 - val_loss: 0.6466
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6333 - val_accuracy: 0.6828 - val_loss: 0.5822
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6523 - val_accuracy: 0.6679 - val_loss: 0.5874
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.6329 - val_accuracy: 0.4739 - val_loss: 0.7388
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6394 - val_accuracy: 0.6679 - val_loss: 0.5872
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6349 - val_accuracy: 0.6455 - val_loss: 0.7526
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6395 - val_accuracy: 0.6455 - val_loss: 0.8541
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6187 - val_accuracy: 0.6791 - val_loss: 0.6183
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.6426 - val_accuracy: 0.7201 - val_loss: 0.5678
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6292 - val_accuracy: 0.5672 - val_loss: 0.6760
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6263 - val_accuracy: 0.6530 - val_loss: 0.6997
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6114 - val_accuracy: 0.5709 - val_loss: 0.6709
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.5994 - val_accuracy: 0.6567 - val_loss: 0.7120
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6226 - val_accuracy: 0.6455 - val_loss: 0.7498
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6186 - val_accuracy: 0.7164 - val_loss: 0.5502
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6187 - val_accuracy: 0.6306 - val_loss: 0.6329
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5871 - val_accuracy: 0.7127 - val_loss: 0.5411
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6129 - val_accuracy: 0.6455 - val_loss: 0.6219
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5957 - val_accuracy: 0.6455 - val_loss: 0.7654
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6148 - val_accuracy: 0.6567 - val_loss: 0.6479
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5902 - val_accuracy: 0.6530 - val_loss: 0.6674
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5922 - val_accuracy: 0.7239 - val_loss: 0.5297
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5926 - val_accuracy: 0.6791 - val_loss: 0.5792
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5982 - val_accuracy: 0.7351 - val_loss: 0.5256
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.5984 - val_accuracy: 0.7313 - val_loss: 0.5244
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5947 - val_accuracy: 0.7351 - val_loss: 0.5251
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5680 - val_accuracy: 0.5784 - val_loss: 0.6791
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6042 - val_accuracy: 0.6903 - val_loss: 0.5684
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5650 - val_accuracy: 0.6567 - val_loss: 0.6382
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.5807 - val_accuracy: 0.7575 - val_loss: 0.5298
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5923 - val_accuracy: 0.5187 - val_loss: 0.7107
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5890 - val_accuracy: 0.7425 - val_loss: 0.5188
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5638 - val_accuracy: 0.6903 - val_loss: 0.5727
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5767 - val_accuracy: 0.6866 - val_loss: 0.5680
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5695 - val_accuracy: 0.4888 - val_loss: 0.8231
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5981 - val_accuracy: 0.6567 - val_loss: 0.6079
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5618 - val_accuracy: 0.5634 - val_loss: 0.7000
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5738 - val_accuracy: 0.4888 - val_loss: 0.8050
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5734 - val_accuracy: 0.6791 - val_loss: 0.5657
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5743 - val_accuracy: 0.6530 - val_loss: 0.6677
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5880 - val_accuracy: 0.7276 - val_loss: 0.5159
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5507 - val_accuracy: 0.6642 - val_loss: 0.5990
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5660 - val_accuracy: 0.7537 - val_loss: 0.5047
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5640 - val_accuracy: 0.6866 - val_loss: 0.5425
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5597 - val_accuracy: 0.7575 - val_loss: 0.5072
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5427 - val_accuracy: 0.6343 - val_loss: 0.6123
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5752 - val_accuracy: 0.6716 - val_loss: 0.5860
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5580 - val_accuracy: 0.6642 - val_loss: 0.6153
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5495 - val_accuracy: 0.6828 - val_loss: 0.5641
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5588 - val_accuracy: 0.6567 - val_loss: 0.6671
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5638 - val_accuracy: 0.5896 - val_loss: 0.6914
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5470 - val_accuracy: 0.7687 - val_loss: 0.5472
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5349 - val_accuracy: 0.6903 - val_loss: 0.5352
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5563 - val_accuracy: 0.6754 - val_loss: 0.5857
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5636 - val_accuracy: 0.7164 - val_loss: 0.5170
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5460 - val_accuracy: 0.7687 - val_loss: 0.4961
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5429 - val_accuracy: 0.7463 - val_loss: 0.4966
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5499 - val_accuracy: 0.5672 - val_loss: 0.7041
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5462 - val_accuracy: 0.7724 - val_loss: 0.5205
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5322 - val_accuracy: 0.6903 - val_loss: 0.6002
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5606 - val_accuracy: 0.7612 - val_loss: 0.5057
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5439 - val_accuracy: 0.7612 - val_loss: 0.5053
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5328 - val_accuracy: 0.6940 - val_loss: 0.5821
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5582 - val_accuracy: 0.7687 - val_loss: 0.5003
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5515 - val_accuracy: 0.7761 - val_loss: 0.5266
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5147 - val_accuracy: 0.7015 - val_loss: 0.5304
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5388 - val_accuracy: 0.7388 - val_loss: 0.4984
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5283 - val_accuracy: 0.7463 - val_loss: 0.4953
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5295 - val_accuracy: 0.5672 - val_loss: 0.7199
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5602 - val_accuracy: 0.7239 - val_loss: 0.5109
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5421 - val_accuracy: 0.7090 - val_loss: 0.5232
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5111 - val_accuracy: 0.7127 - val_loss: 0.5193
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5362 - val_accuracy: 0.7649 - val_loss: 0.4846
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5265 - val_accuracy: 0.6493 - val_loss: 0.6047
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5272 - val_accuracy: 0.7724 - val_loss: 0.5271
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5298 - val_accuracy: 0.7164 - val_loss: 0.5146
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5363 - val_accuracy: 0.7575 - val_loss: 0.4827
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5229 - val_accuracy: 0.6716 - val_loss: 0.5904
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5218 - val_accuracy: 0.7388 - val_loss: 0.4998
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5345 - val_accuracy: 0.7612 - val_loss: 0.4799
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5071 - val_accuracy: 0.7052 - val_loss: 0.5666
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5182 - val_accuracy: 0.7761 - val_loss: 0.5069
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5205 - val_accuracy: 0.7687 - val_loss: 0.4763
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5050 - val_accuracy: 0.7425 - val_loss: 0.5007
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5054 - val_accuracy: 0.7649 - val_loss: 0.4724
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5342 - val_accuracy: 0.7127 - val_loss: 0.5363
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5035 - val_accuracy: 0.7537 - val_loss: 0.5558
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5239 - val_accuracy: 0.7687 - val_loss: 0.4869
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5194 - val_accuracy: 0.5933 - val_loss: 0.6882
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5419 - val_accuracy: 0.7649 - val_loss: 0.4807
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5306 - val_accuracy: 0.7724 - val_loss: 0.4782
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4996 - val_accuracy: 0.7649 - val_loss: 0.4840
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5375 - val_accuracy: 0.7649 - val_loss: 0.4793
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5238 - val_accuracy: 0.6791 - val_loss: 0.6749
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4965 - val_accuracy: 0.7351 - val_loss: 0.5027
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4881 - val_accuracy: 0.7127 - val_loss: 0.5696
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5083 - val_accuracy: 0.7388 - val_loss: 0.5042
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5113 - val_accuracy: 0.7276 - val_loss: 0.5125
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5203 - val_accuracy: 0.7612 - val_loss: 0.4692
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5043 - val_accuracy: 0.7649 - val_loss: 0.4764
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5025 - val_accuracy: 0.7388 - val_loss: 0.5121
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5094 - val_accuracy: 0.7687 - val_loss: 0.4687
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5222 - val_accuracy: 0.7500 - val_loss: 0.4888
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5325 - val_accuracy: 0.7687 - val_loss: 0.4845
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5096 - val_accuracy: 0.7687 - val_loss: 0.4807
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5086 - val_accuracy: 0.7612 - val_loss: 0.4782
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4981 - val_accuracy: 0.7612 - val_loss: 0.4744
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5152 - val_accuracy: 0.7687 - val_loss: 0.4695
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5178 - val_accuracy: 0.7090 - val_loss: 0.5557
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5118 - val_accuracy: 0.5187 - val_loss: 0.8711
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5038 - val_accuracy: 0.7127 - val_loss: 0.5729
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5145 - val_accuracy: 0.6866 - val_loss: 0.5897
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5107 - val_accuracy: 0.7649 - val_loss: 0.4800
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5057 - val_accuracy: 0.7649 - val_loss: 0.4752
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4894 - val_accuracy: 0.7575 - val_loss: 0.5410
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5158 - val_accuracy: 0.7799 - val_loss: 0.5215
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5018 - val_accuracy: 0.7799 - val_loss: 0.5032
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5066 - val_accuracy: 0.7276 - val_loss: 0.5698
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5008 - val_accuracy: 0.7687 - val_loss: 0.4675
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4898 - val_accuracy: 0.7612 - val_loss: 0.4823
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5287 - val_accuracy: 0.7500 - val_loss: 0.5141
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4934 - val_accuracy: 0.7724 - val_loss: 0.4664
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5019 - val_accuracy: 0.7687 - val_loss: 0.4662
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4847 - val_accuracy: 0.6978 - val_loss: 0.5884
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5077 - val_accuracy: 0.6754 - val_loss: 0.6003
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4839 - val_accuracy: 0.7575 - val_loss: 0.4927
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5126 - val_accuracy: 0.7612 - val_loss: 0.4711
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5087 - val_accuracy: 0.7463 - val_loss: 0.5089
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5143 - val_accuracy: 0.7015 - val_loss: 0.6565
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.5125 - val_accuracy: 0.7649 - val_loss: 0.4659
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4844 - val_accuracy: 0.7612 - val_loss: 0.4675
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4716 - val_accuracy: 0.7687 - val_loss: 0.4616
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5066 - val_accuracy: 0.6866 - val_loss: 0.6066
Epoch 155/5000

wandb: Agent Starting Run: 886o1bf0 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5474 - loss: 3.6848 - val_accuracy: 0.6642 - val_loss: 1.4553
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5538 - loss: 1.5583 - val_accuracy: 0.6567 - val_loss: 1.0953
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5955 - loss: 1.2094 - val_accuracy: 0.6045 - val_loss: 1.0628
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 1.0752 - val_accuracy: 0.6866 - val_loss: 0.9759
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.9997 - val_accuracy: 0.6007 - val_loss: 0.9733
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5939 - loss: 0.9977 - val_accuracy: 0.6828 - val_loss: 0.8691
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.8981 - val_accuracy: 0.5821 - val_loss: 0.9250
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.8769 - val_accuracy: 0.6866 - val_loss: 0.7975
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 0.8565 - val_accuracy: 0.6903 - val_loss: 0.7685
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7753 - val_accuracy: 0.6791 - val_loss: 0.7756
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.8049 - val_accuracy: 0.5896 - val_loss: 0.8323
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.7491 - val_accuracy: 0.6791 - val_loss: 0.7473
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.7248 - val_accuracy: 0.6940 - val_loss: 0.6883
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6765 - val_accuracy: 0.7313 - val_loss: 0.6462
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6476 - val_accuracy: 0.7164 - val_loss: 0.6408
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.6328 - val_accuracy: 0.7164 - val_loss: 0.6191
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6329 - val_accuracy: 0.7201 - val_loss: 0.6043
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6308 - val_accuracy: 0.7351 - val_loss: 0.6189
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5831 - val_accuracy: 0.6978 - val_loss: 0.6034
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5991 - val_accuracy: 0.6866 - val_loss: 0.6556
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5954 - val_accuracy: 0.7425 - val_loss: 0.5966
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5634 - val_accuracy: 0.7351 - val_loss: 0.5641
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5555 - val_accuracy: 0.7015 - val_loss: 0.5922
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5426 - val_accuracy: 0.7425 - val_loss: 0.5715
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5603 - val_accuracy: 0.7276 - val_loss: 0.5547
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5286 - val_accuracy: 0.7388 - val_loss: 0.5468
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5402 - val_accuracy: 0.7500 - val_loss: 0.5593
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5199 - val_accuracy: 0.7313 - val_loss: 0.5618
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5260 - val_accuracy: 0.7425 - val_loss: 0.5330
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5236 - val_accuracy: 0.7201 - val_loss: 0.5501
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5107 - val_accuracy: 0.6045 - val_loss: 0.7073
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6156 - val_accuracy: 0.7463 - val_loss: 0.5350
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5256 - val_accuracy: 0.7500 - val_loss: 0.5199
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4957 - val_accuracy: 0.7463 - val_loss: 0.5257
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4969 - val_accuracy: 0.7463 - val_loss: 0.5172
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5429 - val_accuracy: 0.7164 - val_loss: 0.6111
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5316 - val_accuracy: 0.7351 - val_loss: 0.5440
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5232 - val_accuracy: 0.7575 - val_loss: 0.5208
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4922 - val_accuracy: 0.7537 - val_loss: 0.5106
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5011 - val_accuracy: 0.7463 - val_loss: 0.5149
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4920 - val_accuracy: 0.7500 - val_loss: 0.5349
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4852 - val_accuracy: 0.7388 - val_loss: 0.5556
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5601 - val_accuracy: 0.7612 - val_loss: 0.5299
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4994 - val_accuracy: 0.7649 - val_loss: 0.5062
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4988 - val_accuracy: 0.7873 - val_loss: 0.5367
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4804 - val_accuracy: 0.7761 - val_loss: 0.5168
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4840 - val_accuracy: 0.7537 - val_loss: 0.5081
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4863 - val_accuracy: 0.7575 - val_loss: 0.5000
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4845 - val_accuracy: 0.7090 - val_loss: 0.6233
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4975 - val_accuracy: 0.7425 - val_loss: 0.4956
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4747 - val_accuracy: 0.7463 - val_loss: 0.5047
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4869 - val_accuracy: 0.7351 - val_loss: 0.5166
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5321 - val_accuracy: 0.7687 - val_loss: 0.5178
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4713 - val_accuracy: 0.7388 - val_loss: 0.5490
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5266 - val_accuracy: 0.7612 - val_loss: 0.4927
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5069 - val_accuracy: 0.7724 - val_loss: 0.5110
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4593 - val_accuracy: 0.7463 - val_loss: 0.5375
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4683 - val_accuracy: 0.7500 - val_loss: 0.4953
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4596 - val_accuracy: 0.7687 - val_loss: 0.5270
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5238 - val_accuracy: 0.7687 - val_loss: 0.5379
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5167 - val_accuracy: 0.7612 - val_loss: 0.4960
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4806 - val_accuracy: 0.7612 - val_loss: 0.5029
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4693 - val_accuracy: 0.7649 - val_loss: 0.4953
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4572 - val_accuracy: 0.7649 - val_loss: 0.5051
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4666 - val_accuracy: 0.7425 - val_loss: 0.5134
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4622 - val_accuracy: 0.7649 - val_loss: 0.5559
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4742 - val_accuracy: 0.7463 - val_loss: 0.5092
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4819 - val_accuracy: 0.7351 - val_loss: 0.5319
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4720 - val_accuracy: 0.7500 - val_loss: 0.5037
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4745 - val_accuracy: 0.7537 - val_loss: 0.5043
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4523 - val_accuracy: 0.7687 - val_loss: 0.5187
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4613 - val_accuracy: 0.7649 - val_loss: 0.5054
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4580 - val_accuracy: 0.7612 - val_loss: 0.5307
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4533 - val_accuracy: 0.7612 - val_loss: 0.5060
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4593 - val_accuracy: 0.7724 - val_loss: 0.5615
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4577 - val_accuracy: 0.7649 - val_loss: 0.5296
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4527 - val_accuracy: 0.7612 - val_loss: 0.5009
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4752 - val_accuracy: 0.7239 - val_loss: 0.6166
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5100 - val_accuracy: 0.7649 - val_loss: 0.5198
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4588 - val_accuracy: 0.7649 - val_loss: 0.5027
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5177 - val_accuracy: 0.7015 - val_loss: 0.6444
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4998 - val_accuracy: 0.7612 - val_loss: 0.5034
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4922 - val_accuracy: 0.7500 - val_loss: 0.5118
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4745 - val_accuracy: 0.7463 - val_loss: 0.5262
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4675 - val_accuracy: 0.7500 - val_loss: 0.5170
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4560 - val_accuracy: 0.7649 - val_loss: 0.5075
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4477 - val_accuracy: 0.7463 - val_loss: 0.5067
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4713 - val_accuracy: 0.7500 - val_loss: 0.5227
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4778 - val_accuracy: 0.7687 - val_loss: 0.5065
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4517 - val_accuracy: 0.7537 - val_loss: 0.5087
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4406 - val_accuracy: 0.7761 - val_loss: 0.5099
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4458 - val_accuracy: 0.7612 - val_loss: 0.5083
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4478 - val_accuracy: 0.7575 - val_loss: 0.5046
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4487 - val_accuracy: 0.7724 - val_loss: 0.5090
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4465 - val_accuracy: 0.7612 - val_loss: 0.5102
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4574 - val_accuracy: 0.7500 - val_loss: 0.5448
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4561 - val_accuracy: 0.7761 - val_loss: 0.5341
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4665 - val_accuracy: 0.7687 - val_loss: 0.5491
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4435 - val_accuracy: 0.7687 - val_loss: 0.5027
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4597 - val_accuracy: 0.7687 - val_loss: 0.5119
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5080 - val_accuracy: 0.7463 - val_loss: 0.5447
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4938 - val_accuracy: 0.7313 - val_loss: 0.5773
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5087 - val_accuracy: 0.7649 - val_loss: 0.5112
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4512 - val_accuracy: 0.7687 - val_loss: 0.5283
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4656 - val_accuracy: 0.6903 - val_loss: 0.6621
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5114 - val_accuracy: 0.7799 - val_loss: 0.5102
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4479 - val_accuracy: 0.7575 - val_loss: 0.5383
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4687 - val_accuracy: 0.7724 - val_loss: 0.5210
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4703 - val_accuracy: 0.7687 - val_loss: 0.5064
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4441 - val_accuracy: 0.7799 - val_loss: 0.5219
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4501 - val_accuracy: 0.7687 - val_loss: 0.5233
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4496 - val_accuracy: 0.7649 - val_loss: 0.5124
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4775 - val_accuracy: 0.7537 - val_loss: 0.5354
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4489 - val_accuracy: 0.7388 - val_loss: 0.5812
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4723 - val_accuracy: 0.7761 - val_loss: 0.5388
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4479 - val_accuracy: 0.7649 - val_loss: 0.5077
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4370 - val_accuracy: 0.7537 - val_loss: 0.5492
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4675 - val_accuracy: 0.7724 - val_loss: 0.5236
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4353 - val_accuracy: 0.7649 - val_loss: 0.5121
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4571 - val_accuracy: 0.7537 - val_loss: 0.6055
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4572 - val_accuracy: 0.7724 - val_loss: 0.5320
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4445 - val_accuracy: 0.7649 - val_loss: 0.5139
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4477 - val_accuracy: 0.7687 - val_loss: 0.5118
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4619 - val_accuracy: 0.7649 - val_loss: 0.5109
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4765 - val_accuracy: 0.7687 - val_loss: 0.5508
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4764 - val_accuracy: 0.7649 - val_loss: 0.5149
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4554 - val_accuracy: 0.7649 - val_loss: 0.5118
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4388 - val_accuracy: 0.7687 - val_loss: 0.5294
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4445 - val_accuracy: 0.7612 - val_loss: 0.5407
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4463 - val_accuracy: 0.7687 - val_loss: 0.5247
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4371 - val_accuracy: 0.7724 - val_loss: 0.5224
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4495 - val_accuracy: 0.7724 - val_loss: 0.5485
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4672 - val_accuracy: 0.7649 - val_loss: 0.5080
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4637 - val_accuracy: 0.7537 - val_loss: 0.5535
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5438 - val_accuracy: 0.7687 - val_loss: 0.5144
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4718 - val_accuracy: 0.7612 - val_loss: 0.5158
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8170 - loss: 0.4446 - val_accuracy: 0.7761 - val_loss: 0.5230
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4468 - val_accuracy: 0.7724 - val_loss: 0.5213
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4393 - val_accuracy: 0.7649 - val_loss: 0.5142
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4398 - val_accuracy: 0.7687 - val_loss: 0.5315
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4996 - val_accuracy: 0.7425 - val_loss: 0.5927
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8138 - loss: 0.4595 - val_accuracy: 0.7687 - val_loss: 0.5224
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4599 - val_accuracy: 0.7649 - val_loss: 0.5217
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4490 - val_accuracy: 0.7649 - val_loss: 0.5310
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4474 - val_accuracy: 0.7649 - val_loss: 0.5145
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8202 - loss: 0.4476 - val_accuracy: 0.7761 - val_loss: 0.5555
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4479 - val_accuracy: 0.7724 - val_loss: 0.5215
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4525 - val_accuracy: 0.7687 - val_loss: 0.5224
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4328 - val_accuracy: 0.7761 - val_loss: 0.5814
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4552 - val_accuracy: 0.7724 - val_loss: 0.5286
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4526 - val_accuracy: 0.7649 - val_loss: 0.5497
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4815 - val_accuracy: 0.7761 - val_loss: 0.5137
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5047 - val_accuracy: 0.7799 - val_loss: 0.5555
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4780 - val_accuracy: 0.7799 - val_loss: 0.5895
Epoch 155/5000

wandb: Agent Starting Run: rwkdxo70 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5843 - loss: 18.1427 - val_accuracy: 0.6082 - val_loss: 0.8083
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.7168 - val_accuracy: 0.6007 - val_loss: 0.7619
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6961 - val_accuracy: 0.6082 - val_loss: 0.7243
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6880 - val_accuracy: 0.6045 - val_loss: 0.7172
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6861 - val_accuracy: 0.6119 - val_loss: 0.7099
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6830 - val_accuracy: 0.6157 - val_loss: 0.7034
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6817 - val_accuracy: 0.6194 - val_loss: 0.6982
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6785 - val_accuracy: 0.6194 - val_loss: 0.6939
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6768 - val_accuracy: 0.6119 - val_loss: 0.6908
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6757 - val_accuracy: 0.6269 - val_loss: 0.6887
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6743 - val_accuracy: 0.6231 - val_loss: 0.6877
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6725 - val_accuracy: 0.6231 - val_loss: 0.6870
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6717 - val_accuracy: 0.6269 - val_loss: 0.6859
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6704 - val_accuracy: 0.6269 - val_loss: 0.6850
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6698 - val_accuracy: 0.6269 - val_loss: 0.6847
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.6836
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6680 - val_accuracy: 0.6194 - val_loss: 0.6838
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6822
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6668 - val_accuracy: 0.6231 - val_loss: 0.6816
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6803
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6658 - val_accuracy: 0.6194 - val_loss: 0.6812
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6803
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6231 - val_loss: 0.6799
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6787
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6778
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6782
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6231 - val_loss: 0.6771
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.6779
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6637 - val_accuracy: 0.6194 - val_loss: 0.6781
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6633 - val_accuracy: 0.6231 - val_loss: 0.6789
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6754
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6639 - val_accuracy: 0.6194 - val_loss: 0.6779
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.6775
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.6785
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6231 - val_loss: 0.6757
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6231 - val_loss: 0.6781
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6792
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6231 - val_loss: 0.6784
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6788
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6779
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6774
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6231 - val_loss: 0.6771
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6772
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.6774
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6612 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6609 - val_accuracy: 0.6231 - val_loss: 0.6756
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6269 - val_loss: 0.6757
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6231 - val_loss: 0.6771
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.6775
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6194 - val_loss: 0.6777
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6605 - val_accuracy: 0.6231 - val_loss: 0.6788
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6605 - val_accuracy: 0.6231 - val_loss: 0.6768
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6607 - val_accuracy: 0.6269 - val_loss: 0.6752
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6194 - val_loss: 0.6768
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6603 - val_accuracy: 0.6269 - val_loss: 0.6757
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6775
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6606 - val_accuracy: 0.6194 - val_loss: 0.6766
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6604 - val_accuracy: 0.6231 - val_loss: 0.6764
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6603 - val_accuracy: 0.6269 - val_loss: 0.6813
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6603 - val_accuracy: 0.6269 - val_loss: 0.6824
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6600 - val_accuracy: 0.6194 - val_loss: 0.6849
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6596 - val_accuracy: 0.6194 - val_loss: 0.6842
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6599 - val_accuracy: 0.6194 - val_loss: 0.6858
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6603 - val_accuracy: 0.6231 - val_loss: 0.6840
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6600 - val_accuracy: 0.6194 - val_loss: 0.6855
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6597 - val_accuracy: 0.6194 - val_loss: 0.6862
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6600 - val_accuracy: 0.6194 - val_loss: 0.6875
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.6780
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6598 - val_accuracy: 0.6231 - val_loss: 0.6795
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6598 - val_accuracy: 0.6231 - val_loss: 0.6800
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.6790
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6596 - val_accuracy: 0.6269 - val_loss: 0.6793
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6594 - val_accuracy: 0.6231 - val_loss: 0.6802
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.6815
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6596 - val_accuracy: 0.6194 - val_loss: 0.6808
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.6809
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6599 - val_accuracy: 0.6343 - val_loss: 0.6754
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6788
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.6791
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6592 - val_accuracy: 0.6194 - val_loss: 0.6809
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6592 - val_accuracy: 0.6194 - val_loss: 0.6812
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6593 - val_accuracy: 0.6194 - val_loss: 0.6815
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.6827
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6592 - val_accuracy: 0.6194 - val_loss: 0.6823
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.6827
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6604 - val_accuracy: 0.6194 - val_loss: 0.6799
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.6806
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6592 - val_accuracy: 0.6231 - val_loss: 0.6795
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6596 - val_accuracy: 0.6194 - val_loss: 0.6824
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6590 - val_accuracy: 0.6194 - val_loss: 0.6812
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6591 - val_accuracy: 0.6194 - val_loss: 0.6818
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6832
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6585 - val_accuracy: 0.6231 - val_loss: 0.6805
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6597 - val_accuracy: 0.6194 - val_loss: 0.6827
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6589 - val_accuracy: 0.6119 - val_loss: 0.6838
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.6815
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.6833
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6589 - val_accuracy: 0.6157 - val_loss: 0.6828
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6829
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6842
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6585 - val_accuracy: 0.6269 - val_loss: 0.6787
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6598 - val_accuracy: 0.6157 - val_loss: 0.6822
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6194 - val_loss: 0.6831
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6842
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6590 - val_accuracy: 0.6157 - val_loss: 0.6839
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6589 - val_accuracy: 0.6157 - val_loss: 0.6857
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6852
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.6583 - val_accuracy: 0.6157 - val_loss: 0.6870
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6852
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6840
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6583 - val_accuracy: 0.6194 - val_loss: 0.6829
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6841
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6878
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6875
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6871
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6584 - val_accuracy: 0.6194 - val_loss: 0.6882
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6904
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6885
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6898
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6903
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6584 - val_accuracy: 0.6157 - val_loss: 0.6834
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6584 - val_accuracy: 0.6157 - val_loss: 0.6850
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6583 - val_accuracy: 0.6157 - val_loss: 0.6857
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6853
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.6859
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6584 - val_accuracy: 0.6194 - val_loss: 0.6844
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.6840
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6584 - val_accuracy: 0.6194 - val_loss: 0.6853
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6585 - val_accuracy: 0.6194 - val_loss: 0.6852
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6583 - val_accuracy: 0.6157 - val_loss: 0.6857
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.6900
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.6911
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6579 - val_accuracy: 0.6157 - val_loss: 0.6906
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6583 - val_accuracy: 0.6194 - val_loss: 0.6924
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6581 - val_accuracy: 0.6194 - val_loss: 0.6827
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6581 - val_accuracy: 0.6157 - val_loss: 0.6841
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6581 - val_accuracy: 0.6157 - val_loss: 0.6844
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6157 - val_loss: 0.6832
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6582 - val_accuracy: 0.6157 - val_loss: 0.6838
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6584 - val_accuracy: 0.6157 - val_loss: 0.6842
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6584 - val_accuracy: 0.6157 - val_loss: 0.6850
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.6858
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6157 - val_loss: 0.6875
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6858
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6582 - val_accuracy: 0.6157 - val_loss: 0.6869
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.6576 - val_accuracy: 0.6231 - val_loss: 0.6840
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6589 - val_accuracy: 0.6157 - val_loss: 0.6864
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6580 - val_accuracy: 0.6157 - val_loss: 0.6869
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.6880
Epoch 155/5000

wandb: Agent Starting Run: 3so7kduq with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3852 - loss: 37.9937 - val_accuracy: 0.3619 - val_loss: 16.9698
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4093 - loss: 6.0512 - val_accuracy: 0.4888 - val_loss: 2.8032
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4350 - loss: 2.1818 - val_accuracy: 0.5634 - val_loss: 2.4775
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4896 - loss: 1.4305 - val_accuracy: 0.5597 - val_loss: 1.0949
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5345 - loss: 1.0719 - val_accuracy: 0.5224 - val_loss: 0.9722
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5506 - loss: 1.0711 - val_accuracy: 0.6381 - val_loss: 0.9591
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5955 - loss: 0.9117 - val_accuracy: 0.6082 - val_loss: 0.8206
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5634 - loss: 0.9367 - val_accuracy: 0.6493 - val_loss: 0.8701
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5586 - loss: 0.9711 - val_accuracy: 0.5784 - val_loss: 0.7537
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5843 - loss: 0.8855 - val_accuracy: 0.4104 - val_loss: 0.9891
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5762 - loss: 0.9201 - val_accuracy: 0.6530 - val_loss: 0.6713
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.8302 - val_accuracy: 0.6791 - val_loss: 0.6581
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.7492 - val_accuracy: 0.6455 - val_loss: 0.7165
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7873 - val_accuracy: 0.6791 - val_loss: 0.6437
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.8024 - val_accuracy: 0.7052 - val_loss: 0.5903
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7142 - val_accuracy: 0.7164 - val_loss: 0.5769
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.8180 - val_accuracy: 0.7388 - val_loss: 0.5887
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6708 - val_accuracy: 0.7313 - val_loss: 0.5551
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.7103 - val_accuracy: 0.6866 - val_loss: 0.6694
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6610 - val_accuracy: 0.7276 - val_loss: 0.6104
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.6651 - val_accuracy: 0.7351 - val_loss: 0.5292
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.6910 - val_accuracy: 0.7388 - val_loss: 0.6091
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6832 - val_accuracy: 0.7649 - val_loss: 0.5452
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.6543 - val_accuracy: 0.7201 - val_loss: 0.5497
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.7167 - val_accuracy: 0.7463 - val_loss: 0.5389
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6956 - val_accuracy: 0.4627 - val_loss: 0.9953
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6023 - val_accuracy: 0.6679 - val_loss: 0.7775
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7089 - val_accuracy: 0.7425 - val_loss: 0.5212
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.6084 - val_accuracy: 0.7052 - val_loss: 0.6536
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6658 - val_accuracy: 0.7500 - val_loss: 0.4928
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6542 - val_accuracy: 0.7201 - val_loss: 0.5728
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6020 - val_accuracy: 0.7164 - val_loss: 0.5213
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6236 - val_accuracy: 0.6493 - val_loss: 1.2436
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6876 - val_accuracy: 0.7612 - val_loss: 0.4925
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5939 - val_accuracy: 0.5970 - val_loss: 0.7051
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6108 - val_accuracy: 0.7090 - val_loss: 0.6270
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6239 - val_accuracy: 0.6493 - val_loss: 1.0423
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6340 - val_accuracy: 0.7276 - val_loss: 0.5114
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.6621 - val_accuracy: 0.7575 - val_loss: 0.5347
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6342 - val_accuracy: 0.6530 - val_loss: 0.9926
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5789 - val_accuracy: 0.7052 - val_loss: 0.6125
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.6139 - val_accuracy: 0.7201 - val_loss: 0.5894
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6442 - val_accuracy: 0.6493 - val_loss: 0.9275
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5450 - val_accuracy: 0.7164 - val_loss: 0.6150
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6209 - val_accuracy: 0.7612 - val_loss: 0.4703
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6101 - val_accuracy: 0.7201 - val_loss: 0.5984
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5772 - val_accuracy: 0.6493 - val_loss: 0.6635
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5979 - val_accuracy: 0.7836 - val_loss: 0.4879
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5747 - val_accuracy: 0.5075 - val_loss: 0.8842
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5972 - val_accuracy: 0.7313 - val_loss: 0.5203
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6260 - val_accuracy: 0.7052 - val_loss: 0.6176
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6106 - val_accuracy: 0.7201 - val_loss: 0.5445
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5902 - val_accuracy: 0.7985 - val_loss: 0.4691
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5869 - val_accuracy: 0.6866 - val_loss: 0.6965
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5207 - val_accuracy: 0.6940 - val_loss: 0.7040
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6309 - val_accuracy: 0.7201 - val_loss: 0.5683
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.6195 - val_accuracy: 0.7015 - val_loss: 0.6926
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5393 - val_accuracy: 0.7164 - val_loss: 0.6199
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.6246 - val_accuracy: 0.7239 - val_loss: 0.6017
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5903 - val_accuracy: 0.6903 - val_loss: 0.6270
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5909 - val_accuracy: 0.7164 - val_loss: 0.6335
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.6093 - val_accuracy: 0.7127 - val_loss: 0.6782
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5530 - val_accuracy: 0.7164 - val_loss: 0.5634
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5556 - val_accuracy: 0.4627 - val_loss: 1.0755
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6320 - val_accuracy: 0.7836 - val_loss: 0.4540
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5601 - val_accuracy: 0.6567 - val_loss: 0.6697
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6139 - val_accuracy: 0.7836 - val_loss: 0.4776
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6108 - val_accuracy: 0.7836 - val_loss: 0.4697
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5979 - val_accuracy: 0.7724 - val_loss: 0.4714
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4981 - val_accuracy: 0.7425 - val_loss: 0.5328
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5593 - val_accuracy: 0.5485 - val_loss: 0.8334
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6292 - val_accuracy: 0.7388 - val_loss: 0.5408
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5232 - val_accuracy: 0.7425 - val_loss: 0.5945
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5474 - val_accuracy: 0.6493 - val_loss: 1.0239
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.6189 - val_accuracy: 0.7799 - val_loss: 0.4577
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5249 - val_accuracy: 0.7724 - val_loss: 0.4700
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5707 - val_accuracy: 0.7724 - val_loss: 0.4870
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5770 - val_accuracy: 0.7537 - val_loss: 0.5064
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5330 - val_accuracy: 0.7239 - val_loss: 0.6054
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.6285 - val_accuracy: 0.4963 - val_loss: 1.0669
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5911 - val_accuracy: 0.7164 - val_loss: 0.6596
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5353 - val_accuracy: 0.7910 - val_loss: 0.4445
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6152 - val_accuracy: 0.7873 - val_loss: 0.4769
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4930 - val_accuracy: 0.6679 - val_loss: 0.9743
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5591 - val_accuracy: 0.6866 - val_loss: 0.8172
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5781 - val_accuracy: 0.7164 - val_loss: 0.6714
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5605 - val_accuracy: 0.7687 - val_loss: 0.4503
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5361 - val_accuracy: 0.7910 - val_loss: 0.4640
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5523 - val_accuracy: 0.6866 - val_loss: 0.6537
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6130 - val_accuracy: 0.6455 - val_loss: 0.7129
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5838 - val_accuracy: 0.7724 - val_loss: 0.4688
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5458 - val_accuracy: 0.7948 - val_loss: 0.4489
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5242 - val_accuracy: 0.4440 - val_loss: 1.6413
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6191 - val_accuracy: 0.7948 - val_loss: 0.4653
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5796 - val_accuracy: 0.7910 - val_loss: 0.4506
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5077 - val_accuracy: 0.7239 - val_loss: 0.6081
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5914 - val_accuracy: 0.7052 - val_loss: 0.7526
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5306 - val_accuracy: 0.7836 - val_loss: 0.4560
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5440 - val_accuracy: 0.7500 - val_loss: 0.5285
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5348 - val_accuracy: 0.7015 - val_loss: 0.7609
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5720 - val_accuracy: 0.7910 - val_loss: 0.4522
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5328 - val_accuracy: 0.5709 - val_loss: 0.8359
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5494 - val_accuracy: 0.7836 - val_loss: 0.4452
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5547 - val_accuracy: 0.7276 - val_loss: 0.6219
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5221 - val_accuracy: 0.7575 - val_loss: 0.5053
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5675 - val_accuracy: 0.4851 - val_loss: 1.1297
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5578 - val_accuracy: 0.7910 - val_loss: 0.4478
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5312 - val_accuracy: 0.7836 - val_loss: 0.4484
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5503 - val_accuracy: 0.7612 - val_loss: 0.4945
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5756 - val_accuracy: 0.6716 - val_loss: 0.8924
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5487 - val_accuracy: 0.7164 - val_loss: 0.7236
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5901 - val_accuracy: 0.4739 - val_loss: 1.1874
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5681 - val_accuracy: 0.7015 - val_loss: 0.7819
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5103 - val_accuracy: 0.7910 - val_loss: 0.4511
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5161 - val_accuracy: 0.4776 - val_loss: 1.3536
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5882 - val_accuracy: 0.7239 - val_loss: 0.5984
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5649 - val_accuracy: 0.7836 - val_loss: 0.4789
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5361 - val_accuracy: 0.7948 - val_loss: 0.4531
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5112 - val_accuracy: 0.7985 - val_loss: 0.4644
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5831 - val_accuracy: 0.7575 - val_loss: 0.5586
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5565 - val_accuracy: 0.7873 - val_loss: 0.4900
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5332 - val_accuracy: 0.7910 - val_loss: 0.4397
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4858 - val_accuracy: 0.6679 - val_loss: 1.0960
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5855 - val_accuracy: 0.7873 - val_loss: 0.5032
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5322 - val_accuracy: 0.7500 - val_loss: 0.5469
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5073 - val_accuracy: 0.7799 - val_loss: 0.5174
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5176 - val_accuracy: 0.4627 - val_loss: 1.4382
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5803 - val_accuracy: 0.7873 - val_loss: 0.4528
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5869 - val_accuracy: 0.6903 - val_loss: 0.6623
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4747 - val_accuracy: 0.7612 - val_loss: 0.5132
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5308 - val_accuracy: 0.7500 - val_loss: 0.5252
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5759 - val_accuracy: 0.7724 - val_loss: 0.4977
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5103 - val_accuracy: 0.7836 - val_loss: 0.4446
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5019 - val_accuracy: 0.7127 - val_loss: 0.7271
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5793 - val_accuracy: 0.7575 - val_loss: 0.5576
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5018 - val_accuracy: 0.7090 - val_loss: 0.7697
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5676 - val_accuracy: 0.7910 - val_loss: 0.5046
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5250 - val_accuracy: 0.7873 - val_loss: 0.4421
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5085 - val_accuracy: 0.7873 - val_loss: 0.4512
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5858 - val_accuracy: 0.8060 - val_loss: 0.4526
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4783 - val_accuracy: 0.7687 - val_loss: 0.5799
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5307 - val_accuracy: 0.7836 - val_loss: 0.5169
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4923 - val_accuracy: 0.6866 - val_loss: 0.9292
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5847 - val_accuracy: 0.7761 - val_loss: 0.4375
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4693 - val_accuracy: 0.7948 - val_loss: 0.4846
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5597 - val_accuracy: 0.8060 - val_loss: 0.4590
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4797 - val_accuracy: 0.7500 - val_loss: 0.5905
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5337 - val_accuracy: 0.7873 - val_loss: 0.4462
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5514 - val_accuracy: 0.6940 - val_loss: 0.8708
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5469 - val_accuracy: 0.7425 - val_loss: 0.6184
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5260 - val_accuracy: 0.7873 - val_loss: 0.4693
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5585 - val_accuracy: 0.7575 - val_loss: 0.5095
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5183 - val_accuracy: 0.7948 - val_loss: 0.4496
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5171 - val_accuracy: 0.7910 - val_loss: 0.4476
Epoch 155/5000

wandb: Agent Starting Run: svbxlw7t with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4430 - loss: 7.6389 - val_accuracy: 0.5000 - val_loss: 4.4160
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5185 - loss: 3.4518 - val_accuracy: 0.3097 - val_loss: 3.3745
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4526 - loss: 2.5308 - val_accuracy: 0.4216 - val_loss: 2.6086
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4526 - loss: 1.9784 - val_accuracy: 0.4739 - val_loss: 2.0970
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4783 - loss: 1.5280 - val_accuracy: 0.5149 - val_loss: 1.6476
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5313 - loss: 1.2346 - val_accuracy: 0.5522 - val_loss: 1.1992
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5714 - loss: 0.9299 - val_accuracy: 0.6045 - val_loss: 0.9367
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.7578 - val_accuracy: 0.6567 - val_loss: 0.7605
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6424 - val_accuracy: 0.6828 - val_loss: 0.7541
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6156 - val_accuracy: 0.7090 - val_loss: 0.6346
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5925 - val_accuracy: 0.7276 - val_loss: 0.6259
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5834 - val_accuracy: 0.7164 - val_loss: 0.6713
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5872 - val_accuracy: 0.7201 - val_loss: 0.6203
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5591 - val_accuracy: 0.7388 - val_loss: 0.6078
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5635 - val_accuracy: 0.7873 - val_loss: 0.6142
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5516 - val_accuracy: 0.7239 - val_loss: 0.6064
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5553 - val_accuracy: 0.7799 - val_loss: 0.5967
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5719 - val_accuracy: 0.7575 - val_loss: 0.5911
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5389 - val_accuracy: 0.7201 - val_loss: 0.6308
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5580 - val_accuracy: 0.7873 - val_loss: 0.6123
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5450 - val_accuracy: 0.7724 - val_loss: 0.5838
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5167 - val_accuracy: 0.7873 - val_loss: 0.5930
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5241 - val_accuracy: 0.7239 - val_loss: 0.5961
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5306 - val_accuracy: 0.7612 - val_loss: 0.5776
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5163 - val_accuracy: 0.7276 - val_loss: 0.5910
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5187 - val_accuracy: 0.7910 - val_loss: 0.5727
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5432 - val_accuracy: 0.7313 - val_loss: 0.5877
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5477 - val_accuracy: 0.7761 - val_loss: 0.6045
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5299 - val_accuracy: 0.7836 - val_loss: 0.5640
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.4983 - val_accuracy: 0.7873 - val_loss: 0.5909
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5185 - val_accuracy: 0.7799 - val_loss: 0.5683
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5171 - val_accuracy: 0.7724 - val_loss: 0.5967
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5022 - val_accuracy: 0.7724 - val_loss: 0.5863
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4928 - val_accuracy: 0.7575 - val_loss: 0.5534
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4865 - val_accuracy: 0.7836 - val_loss: 0.5672
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4924 - val_accuracy: 0.7836 - val_loss: 0.5731
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5001 - val_accuracy: 0.7836 - val_loss: 0.5637
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4896 - val_accuracy: 0.7799 - val_loss: 0.6016
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5358 - val_accuracy: 0.7463 - val_loss: 0.5622
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4869 - val_accuracy: 0.7612 - val_loss: 0.5564
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4921 - val_accuracy: 0.7836 - val_loss: 0.5551
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4762 - val_accuracy: 0.7799 - val_loss: 0.5487
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4767 - val_accuracy: 0.7164 - val_loss: 0.6198
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.4946 - val_accuracy: 0.7799 - val_loss: 0.5509
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4701 - val_accuracy: 0.7873 - val_loss: 0.5496
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4943 - val_accuracy: 0.7463 - val_loss: 0.5651
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4754 - val_accuracy: 0.7687 - val_loss: 0.5510
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4739 - val_accuracy: 0.7425 - val_loss: 0.5671
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5069 - val_accuracy: 0.6903 - val_loss: 0.6840
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5978 - val_accuracy: 0.7463 - val_loss: 0.5792
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4725 - val_accuracy: 0.7537 - val_loss: 0.5725
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5037 - val_accuracy: 0.7052 - val_loss: 0.6667
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5488 - val_accuracy: 0.7910 - val_loss: 0.5616
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5161 - val_accuracy: 0.7761 - val_loss: 0.5369
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4749 - val_accuracy: 0.7612 - val_loss: 0.5642
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4720 - val_accuracy: 0.7724 - val_loss: 0.5522
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4667 - val_accuracy: 0.7836 - val_loss: 0.5630
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4698 - val_accuracy: 0.7836 - val_loss: 0.5479
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4595 - val_accuracy: 0.7687 - val_loss: 0.5435
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.4850 - val_accuracy: 0.6903 - val_loss: 0.6755
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5434 - val_accuracy: 0.7724 - val_loss: 0.5574
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4713 - val_accuracy: 0.7836 - val_loss: 0.5663
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4656 - val_accuracy: 0.7836 - val_loss: 0.5361
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4538 - val_accuracy: 0.7799 - val_loss: 0.5356
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4745 - val_accuracy: 0.7799 - val_loss: 0.5407
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4637 - val_accuracy: 0.7425 - val_loss: 0.5827
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4716 - val_accuracy: 0.7873 - val_loss: 0.5537
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5033 - val_accuracy: 0.7687 - val_loss: 0.5669
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4901 - val_accuracy: 0.7724 - val_loss: 0.5327
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4825 - val_accuracy: 0.7649 - val_loss: 0.6292
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4601 - val_accuracy: 0.7687 - val_loss: 0.5637
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4567 - val_accuracy: 0.7836 - val_loss: 0.5346
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4495 - val_accuracy: 0.7910 - val_loss: 0.5913
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4851 - val_accuracy: 0.7724 - val_loss: 0.5366
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4859 - val_accuracy: 0.7500 - val_loss: 0.6213
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4715 - val_accuracy: 0.7687 - val_loss: 0.5302
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4719 - val_accuracy: 0.7612 - val_loss: 0.5786
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4982 - val_accuracy: 0.7761 - val_loss: 0.5373
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4606 - val_accuracy: 0.7799 - val_loss: 0.5611
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4608 - val_accuracy: 0.7724 - val_loss: 0.5565
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4602 - val_accuracy: 0.7836 - val_loss: 0.5417
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4517 - val_accuracy: 0.7761 - val_loss: 0.5323
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4513 - val_accuracy: 0.7799 - val_loss: 0.5361
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4691 - val_accuracy: 0.7761 - val_loss: 0.5404
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4481 - val_accuracy: 0.7687 - val_loss: 0.5325
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4583 - val_accuracy: 0.7799 - val_loss: 0.5425
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4509 - val_accuracy: 0.7463 - val_loss: 0.6032
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4811 - val_accuracy: 0.7910 - val_loss: 0.5984
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4518 - val_accuracy: 0.7799 - val_loss: 0.5350
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4487 - val_accuracy: 0.7836 - val_loss: 0.5676
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4809 - val_accuracy: 0.7687 - val_loss: 0.5320
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4479 - val_accuracy: 0.7761 - val_loss: 0.5491
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4509 - val_accuracy: 0.7873 - val_loss: 0.5966
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4715 - val_accuracy: 0.7761 - val_loss: 0.5437
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4609 - val_accuracy: 0.7799 - val_loss: 0.5452
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4546 - val_accuracy: 0.7836 - val_loss: 0.5834
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4573 - val_accuracy: 0.7724 - val_loss: 0.5366
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4629 - val_accuracy: 0.7910 - val_loss: 0.5844
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4962 - val_accuracy: 0.7500 - val_loss: 0.5883
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4831 - val_accuracy: 0.7724 - val_loss: 0.5322
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4425 - val_accuracy: 0.7836 - val_loss: 0.5719
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4445 - val_accuracy: 0.7761 - val_loss: 0.5339
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4593 - val_accuracy: 0.7687 - val_loss: 0.5600
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4794 - val_accuracy: 0.7687 - val_loss: 0.5341
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4667 - val_accuracy: 0.7799 - val_loss: 0.5429
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4710 - val_accuracy: 0.7724 - val_loss: 0.5321
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4744 - val_accuracy: 0.7836 - val_loss: 0.5743
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4579 - val_accuracy: 0.7724 - val_loss: 0.5404
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4620 - val_accuracy: 0.7836 - val_loss: 0.5686
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4743 - val_accuracy: 0.7761 - val_loss: 0.5460
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4821 - val_accuracy: 0.7575 - val_loss: 0.5742
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4628 - val_accuracy: 0.7649 - val_loss: 0.6390
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4475 - val_accuracy: 0.7687 - val_loss: 0.5381
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4547 - val_accuracy: 0.7761 - val_loss: 0.5382
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4535 - val_accuracy: 0.7799 - val_loss: 0.5457
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4533 - val_accuracy: 0.7724 - val_loss: 0.5342
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4428 - val_accuracy: 0.7836 - val_loss: 0.5903
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4383 - val_accuracy: 0.7761 - val_loss: 0.5531
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4547 - val_accuracy: 0.7761 - val_loss: 0.5431
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4356 - val_accuracy: 0.7687 - val_loss: 0.5390
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4714 - val_accuracy: 0.7799 - val_loss: 0.5490
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4464 - val_accuracy: 0.7761 - val_loss: 0.5356
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4593 - val_accuracy: 0.7724 - val_loss: 0.5364
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4483 - val_accuracy: 0.7724 - val_loss: 0.5358
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4437 - val_accuracy: 0.7761 - val_loss: 0.5391
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4433 - val_accuracy: 0.7687 - val_loss: 0.5354
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4537 - val_accuracy: 0.7761 - val_loss: 0.5430
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4601 - val_accuracy: 0.7724 - val_loss: 0.5442
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4424 - val_accuracy: 0.7649 - val_loss: 0.5368
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4466 - val_accuracy: 0.7724 - val_loss: 0.5385
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4485 - val_accuracy: 0.7724 - val_loss: 0.5369
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4710 - val_accuracy: 0.7761 - val_loss: 0.5565
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4570 - val_accuracy: 0.7687 - val_loss: 0.5373
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8138 - loss: 0.4359 - val_accuracy: 0.7799 - val_loss: 0.5522
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4395 - val_accuracy: 0.7836 - val_loss: 0.5813
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4561 - val_accuracy: 0.7649 - val_loss: 0.5377
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4456 - val_accuracy: 0.7761 - val_loss: 0.5353
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4488 - val_accuracy: 0.7761 - val_loss: 0.5590
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4632 - val_accuracy: 0.7761 - val_loss: 0.5372
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4795 - val_accuracy: 0.7388 - val_loss: 0.6573
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4962 - val_accuracy: 0.7687 - val_loss: 0.5391
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4413 - val_accuracy: 0.7799 - val_loss: 0.5653
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4442 - val_accuracy: 0.7687 - val_loss: 0.5401
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4419 - val_accuracy: 0.7761 - val_loss: 0.5645
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4411 - val_accuracy: 0.7799 - val_loss: 0.5549
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4486 - val_accuracy: 0.7724 - val_loss: 0.5416
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4491 - val_accuracy: 0.7687 - val_loss: 0.5432
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4423 - val_accuracy: 0.7799 - val_loss: 0.5451
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4412 - val_accuracy: 0.7761 - val_loss: 0.5431
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4416 - val_accuracy: 0.7687 - val_loss: 0.5394
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4543 - val_accuracy: 0.7873 - val_loss: 0.5788
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4651 - val_accuracy: 0.7836 - val_loss: 0.5882
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4615 - val_accuracy: 0.7612 - val_loss: 0.5436
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4382 - val_accuracy: 0.7836 - val_loss: 0.5779
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 85hsbm0w with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5907 - loss: 12.3077 - val_accuracy: 0.6082 - val_loss: 0.6798
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6003 - loss: 0.6780 - val_accuracy: 0.6194 - val_loss: 0.6834
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6003 - loss: 0.6796 - val_accuracy: 0.6194 - val_loss: 0.6764
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6791 - val_accuracy: 0.6194 - val_loss: 0.6763
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6772 - val_accuracy: 0.6343 - val_loss: 0.6727
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6770 - val_accuracy: 0.6343 - val_loss: 0.6732
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6778 - val_accuracy: 0.6343 - val_loss: 0.6718
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6743 - val_accuracy: 0.6343 - val_loss: 0.6709
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6730 - val_accuracy: 0.6269 - val_loss: 0.6751
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6724 - val_accuracy: 0.6269 - val_loss: 0.6779
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6758 - val_accuracy: 0.6306 - val_loss: 0.6728
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6743 - val_accuracy: 0.6455 - val_loss: 0.6631
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6746 - val_accuracy: 0.6455 - val_loss: 0.6673
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6723 - val_accuracy: 0.6306 - val_loss: 0.6712
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6721 - val_accuracy: 0.6343 - val_loss: 0.6698
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6733 - val_accuracy: 0.6455 - val_loss: 0.6648
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6735 - val_accuracy: 0.6455 - val_loss: 0.6634
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6708 - val_accuracy: 0.6343 - val_loss: 0.6668
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6700 - val_accuracy: 0.6381 - val_loss: 0.6671
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6678 - val_accuracy: 0.6455 - val_loss: 0.6608
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6693 - val_accuracy: 0.6604 - val_loss: 0.6520
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6642 - val_accuracy: 0.6343 - val_loss: 0.6724
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6585 - val_accuracy: 0.7090 - val_loss: 0.6302
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6546 - val_accuracy: 0.4104 - val_loss: 1.0752
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5811 - loss: 0.7242 - val_accuracy: 0.6269 - val_loss: 0.6681
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6682 - val_accuracy: 0.6306 - val_loss: 0.6617
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6609 - val_accuracy: 0.6306 - val_loss: 0.6526
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6560 - val_accuracy: 0.6306 - val_loss: 0.6494
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6551 - val_accuracy: 0.6306 - val_loss: 0.6463
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6588 - val_accuracy: 0.6455 - val_loss: 0.6459
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6554 - val_accuracy: 0.6530 - val_loss: 0.6413
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6506 - val_accuracy: 0.6828 - val_loss: 0.6589
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.6537 - val_accuracy: 0.6791 - val_loss: 0.6299
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6488 - val_accuracy: 0.7239 - val_loss: 0.6294
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6514 - val_accuracy: 0.7127 - val_loss: 0.6156
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6423 - val_accuracy: 0.7090 - val_loss: 0.6123
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6536 - val_accuracy: 0.7090 - val_loss: 0.6362
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6426 - val_accuracy: 0.5448 - val_loss: 0.6712
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6521 - val_accuracy: 0.7127 - val_loss: 0.6239
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6491 - val_accuracy: 0.7388 - val_loss: 0.6556
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6476 - val_accuracy: 0.7463 - val_loss: 0.6401
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6499 - val_accuracy: 0.6604 - val_loss: 0.6494
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6466 - val_accuracy: 0.6828 - val_loss: 0.6416
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.6520 - val_accuracy: 0.7164 - val_loss: 0.6171
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6332 - val_accuracy: 0.6828 - val_loss: 0.6296
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.6421 - val_accuracy: 0.7239 - val_loss: 0.6294
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6334 - val_accuracy: 0.6940 - val_loss: 0.6224
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6424 - val_accuracy: 0.6940 - val_loss: 0.6251
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6542 - val_accuracy: 0.7164 - val_loss: 0.6230
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6346 - val_accuracy: 0.7164 - val_loss: 0.6116
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6504 - val_accuracy: 0.7164 - val_loss: 0.6188
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6404 - val_accuracy: 0.7313 - val_loss: 0.6254
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6375 - val_accuracy: 0.7052 - val_loss: 0.6092
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6435 - val_accuracy: 0.7164 - val_loss: 0.6063
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6416 - val_accuracy: 0.7313 - val_loss: 0.6122
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6412 - val_accuracy: 0.7090 - val_loss: 0.6076
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.6502 - val_accuracy: 0.7090 - val_loss: 0.6122
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6272 - val_accuracy: 0.4851 - val_loss: 0.7529
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6519 - val_accuracy: 0.7090 - val_loss: 0.6136
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6379 - val_accuracy: 0.7164 - val_loss: 0.6050
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6454 - val_accuracy: 0.7239 - val_loss: 0.6331
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6423 - val_accuracy: 0.7127 - val_loss: 0.6085
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6409 - val_accuracy: 0.7127 - val_loss: 0.6115
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6419 - val_accuracy: 0.7127 - val_loss: 0.6088
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6317 - val_accuracy: 0.7127 - val_loss: 0.6077
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6311 - val_accuracy: 0.7201 - val_loss: 0.6389
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.6453 - val_accuracy: 0.7015 - val_loss: 0.6192
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6282 - val_accuracy: 0.7388 - val_loss: 0.6403
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6446 - val_accuracy: 0.6418 - val_loss: 0.6524
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.6390 - val_accuracy: 0.7052 - val_loss: 0.6110
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6338 - val_accuracy: 0.7127 - val_loss: 0.6042
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6375 - val_accuracy: 0.6604 - val_loss: 0.6369
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6323 - val_accuracy: 0.6978 - val_loss: 0.6170
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6384 - val_accuracy: 0.6791 - val_loss: 0.6443
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6231 - val_accuracy: 0.6194 - val_loss: 0.6513
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6403 - val_accuracy: 0.7313 - val_loss: 0.6193
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6289 - val_accuracy: 0.7127 - val_loss: 0.6059
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6311 - val_accuracy: 0.7239 - val_loss: 0.6122
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6292 - val_accuracy: 0.7276 - val_loss: 0.6227
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6316 - val_accuracy: 0.7090 - val_loss: 0.6241
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6351 - val_accuracy: 0.7090 - val_loss: 0.6024
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6453 - val_accuracy: 0.6604 - val_loss: 0.6225
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6290 - val_accuracy: 0.7313 - val_loss: 0.6019
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6356 - val_accuracy: 0.7127 - val_loss: 0.6250
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6316 - val_accuracy: 0.6642 - val_loss: 0.6780
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6298 - val_accuracy: 0.6978 - val_loss: 0.6277
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6275 - val_accuracy: 0.6940 - val_loss: 0.6069
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6357 - val_accuracy: 0.7052 - val_loss: 0.6078
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6297 - val_accuracy: 0.7090 - val_loss: 0.6014
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6272 - val_accuracy: 0.7276 - val_loss: 0.6250
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6311 - val_accuracy: 0.7127 - val_loss: 0.6018
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6362 - val_accuracy: 0.7052 - val_loss: 0.6041
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6414 - val_accuracy: 0.6493 - val_loss: 0.6285
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6333 - val_accuracy: 0.6866 - val_loss: 0.6285
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6241 - val_accuracy: 0.7276 - val_loss: 0.6185
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6339 - val_accuracy: 0.7127 - val_loss: 0.6068
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6314 - val_accuracy: 0.6903 - val_loss: 0.6271
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6317 - val_accuracy: 0.7313 - val_loss: 0.6213
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6442 - val_accuracy: 0.6903 - val_loss: 0.6172
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6249 - val_accuracy: 0.7090 - val_loss: 0.6275
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6307 - val_accuracy: 0.7463 - val_loss: 0.6284
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6297 - val_accuracy: 0.7015 - val_loss: 0.6098
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6369 - val_accuracy: 0.7127 - val_loss: 0.6024
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6274 - val_accuracy: 0.7164 - val_loss: 0.6006
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6324 - val_accuracy: 0.6978 - val_loss: 0.6442
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6349 - val_accuracy: 0.6679 - val_loss: 0.6326
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6253 - val_accuracy: 0.7090 - val_loss: 0.6025
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6289 - val_accuracy: 0.7015 - val_loss: 0.6098
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6305 - val_accuracy: 0.7090 - val_loss: 0.5920
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6268 - val_accuracy: 0.6530 - val_loss: 0.6939
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6367 - val_accuracy: 0.7090 - val_loss: 0.6000
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6315 - val_accuracy: 0.7127 - val_loss: 0.6085
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6459 - val_accuracy: 0.6978 - val_loss: 0.6203
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6335 - val_accuracy: 0.7015 - val_loss: 0.6258
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.6334 - val_accuracy: 0.7015 - val_loss: 0.6117
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6263 - val_accuracy: 0.7313 - val_loss: 0.6168
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6293 - val_accuracy: 0.7015 - val_loss: 0.6127
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6218 - val_accuracy: 0.7052 - val_loss: 0.6104
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6367 - val_accuracy: 0.7090 - val_loss: 0.6067
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6240 - val_accuracy: 0.6567 - val_loss: 0.6504
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6282 - val_accuracy: 0.7015 - val_loss: 0.6079
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6190 - val_accuracy: 0.7276 - val_loss: 0.6004
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6415 - val_accuracy: 0.6903 - val_loss: 0.6258
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6231 - val_accuracy: 0.7090 - val_loss: 0.6037
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6242 - val_accuracy: 0.7201 - val_loss: 0.6158
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6344 - val_accuracy: 0.7090 - val_loss: 0.6060
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6270 - val_accuracy: 0.6828 - val_loss: 0.6593
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6394 - val_accuracy: 0.6978 - val_loss: 0.6081
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6233 - val_accuracy: 0.7276 - val_loss: 0.6122
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.6355 - val_accuracy: 0.7164 - val_loss: 0.6002
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6295 - val_accuracy: 0.7239 - val_loss: 0.5988
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6368 - val_accuracy: 0.6903 - val_loss: 0.6154
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6167 - val_accuracy: 0.7313 - val_loss: 0.6166
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6305 - val_accuracy: 0.7052 - val_loss: 0.6053
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6316 - val_accuracy: 0.6791 - val_loss: 0.6384
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6258 - val_accuracy: 0.6567 - val_loss: 0.6366
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6214 - val_accuracy: 0.7090 - val_loss: 0.5938
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6274 - val_accuracy: 0.7276 - val_loss: 0.6002
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6233 - val_accuracy: 0.6978 - val_loss: 0.6434
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6290 - val_accuracy: 0.6978 - val_loss: 0.6288
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6277 - val_accuracy: 0.7127 - val_loss: 0.6039
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6220 - val_accuracy: 0.7276 - val_loss: 0.5894
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6230 - val_accuracy: 0.7276 - val_loss: 0.6046
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6184 - val_accuracy: 0.6716 - val_loss: 0.6553
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6324 - val_accuracy: 0.7201 - val_loss: 0.6032
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6196 - val_accuracy: 0.5112 - val_loss: 0.7416
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6340 - val_accuracy: 0.6791 - val_loss: 0.6336
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6179 - val_accuracy: 0.6866 - val_loss: 0.6370
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6284 - val_accuracy: 0.6754 - val_loss: 0.6190
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6235 - val_accuracy: 0.7127 - val_loss: 0.5994
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6214 - val_accuracy: 0.7090 - val_loss: 0.5992
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6315 - val_accuracy: 0.7127 - val_loss: 0.6044
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6204 - val_accuracy: 0.5933 - val_loss: 0.6703
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6215 - val_accuracy: 0.6642 - val_loss: 0.6517
Epoch 155/5000

wandb: Agent Starting Run: iptjq574 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3884 - loss: 39.9782 - val_accuracy: 0.4552 - val_loss: 2.3721
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 1.5327 - val_accuracy: 0.6604 - val_loss: 1.4158
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5746 - loss: 1.6930 - val_accuracy: 0.6716 - val_loss: 1.2048
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 1.4115 - val_accuracy: 0.6269 - val_loss: 2.8199
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 1.5866 - val_accuracy: 0.4664 - val_loss: 1.6745
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 1.2606 - val_accuracy: 0.6493 - val_loss: 1.6087
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5955 - loss: 1.2951 - val_accuracy: 0.5000 - val_loss: 1.2359
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.9883 - val_accuracy: 0.6716 - val_loss: 0.9541
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 1.3536 - val_accuracy: 0.6679 - val_loss: 1.0018
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 1.1627 - val_accuracy: 0.5000 - val_loss: 1.1653
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 1.1561 - val_accuracy: 0.4851 - val_loss: 1.1955
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5746 - loss: 1.2089 - val_accuracy: 0.5037 - val_loss: 1.1182
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.9672 - val_accuracy: 0.6903 - val_loss: 0.7913
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 1.1876 - val_accuracy: 0.6754 - val_loss: 0.7812
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 1.0674 - val_accuracy: 0.7090 - val_loss: 0.7253
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 1.0986 - val_accuracy: 0.7127 - val_loss: 0.7137
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.9980 - val_accuracy: 0.6978 - val_loss: 0.7202
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 1.0230 - val_accuracy: 0.7127 - val_loss: 0.6347
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.9186 - val_accuracy: 0.7090 - val_loss: 0.7137
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 1.1069 - val_accuracy: 0.5709 - val_loss: 0.8874
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.9213 - val_accuracy: 0.4963 - val_loss: 1.0594
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 1.1268 - val_accuracy: 0.7276 - val_loss: 0.6244
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 1.0569 - val_accuracy: 0.6716 - val_loss: 1.1485
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 1.0237 - val_accuracy: 0.4142 - val_loss: 1.4476
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.8497 - val_accuracy: 0.7313 - val_loss: 0.5544
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 1.0357 - val_accuracy: 0.6530 - val_loss: 1.1806
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.9833 - val_accuracy: 0.6306 - val_loss: 1.6541
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.9077 - val_accuracy: 0.6866 - val_loss: 0.8446
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.8747 - val_accuracy: 0.7575 - val_loss: 0.6071
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.8875 - val_accuracy: 0.7015 - val_loss: 0.8195
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.9730 - val_accuracy: 0.6530 - val_loss: 1.3246
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.9963 - val_accuracy: 0.6679 - val_loss: 1.0971
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.7944 - val_accuracy: 0.7425 - val_loss: 0.5198
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 1.0432 - val_accuracy: 0.6940 - val_loss: 0.7751
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.8727 - val_accuracy: 0.7239 - val_loss: 0.6439
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.9172 - val_accuracy: 0.7649 - val_loss: 0.6085
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.8020 - val_accuracy: 0.6119 - val_loss: 1.9842
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 1.0866 - val_accuracy: 0.7537 - val_loss: 0.6574
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.8318 - val_accuracy: 0.6455 - val_loss: 1.5006
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.9663 - val_accuracy: 0.6791 - val_loss: 1.0282
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.9295 - val_accuracy: 0.7425 - val_loss: 0.5162
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.7680 - val_accuracy: 0.7015 - val_loss: 0.7286
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.7886 - val_accuracy: 0.6343 - val_loss: 1.4187
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.9956 - val_accuracy: 0.6231 - val_loss: 1.7726
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.7666 - val_accuracy: 0.7090 - val_loss: 0.8081
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.9389 - val_accuracy: 0.7127 - val_loss: 0.6450
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.8603 - val_accuracy: 0.7724 - val_loss: 0.5334
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.8204 - val_accuracy: 0.7910 - val_loss: 0.5428
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.8400 - val_accuracy: 0.7090 - val_loss: 0.7204
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.8329 - val_accuracy: 0.6231 - val_loss: 1.8474
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.8701 - val_accuracy: 0.7500 - val_loss: 0.5122
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.9090 - val_accuracy: 0.7201 - val_loss: 0.8465
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.7942 - val_accuracy: 0.7836 - val_loss: 0.5458
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.9358 - val_accuracy: 0.4813 - val_loss: 1.4751
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.9177 - val_accuracy: 0.7015 - val_loss: 0.7937
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.8281 - val_accuracy: 0.4515 - val_loss: 2.3280
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.9323 - val_accuracy: 0.7724 - val_loss: 0.5193
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.8585 - val_accuracy: 0.7724 - val_loss: 0.6451
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.8307 - val_accuracy: 0.6455 - val_loss: 1.3383
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.7475 - val_accuracy: 0.7799 - val_loss: 0.5213
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.9000 - val_accuracy: 0.5560 - val_loss: 0.9157
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.8431 - val_accuracy: 0.7090 - val_loss: 0.7824
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.9856 - val_accuracy: 0.7612 - val_loss: 0.5115
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.7819 - val_accuracy: 0.5522 - val_loss: 0.9624
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.8638 - val_accuracy: 0.7575 - val_loss: 0.5682
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.8503 - val_accuracy: 0.7910 - val_loss: 0.5911
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.8291 - val_accuracy: 0.6530 - val_loss: 1.3448
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.8318 - val_accuracy: 0.6866 - val_loss: 1.1002
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.7023 - val_accuracy: 0.7276 - val_loss: 0.5664
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.8184 - val_accuracy: 0.7724 - val_loss: 0.5028
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.9398 - val_accuracy: 0.7836 - val_loss: 0.6599
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.6887 - val_accuracy: 0.6978 - val_loss: 0.8572
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.8864 - val_accuracy: 0.5746 - val_loss: 0.9071
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.9334 - val_accuracy: 0.7649 - val_loss: 0.5119
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6962 - val_accuracy: 0.6567 - val_loss: 1.2783
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.7983 - val_accuracy: 0.7836 - val_loss: 0.5379
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6271 - val_accuracy: 0.6642 - val_loss: 1.3782
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.9070 - val_accuracy: 0.7239 - val_loss: 0.6759
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6843 - val_accuracy: 0.4851 - val_loss: 1.7115
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.9268 - val_accuracy: 0.7537 - val_loss: 0.5740
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.8956 - val_accuracy: 0.7724 - val_loss: 0.4977
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.7662 - val_accuracy: 0.5112 - val_loss: 1.2154
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.7526 - val_accuracy: 0.5000 - val_loss: 1.3846
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7538 - val_accuracy: 0.7761 - val_loss: 0.5487
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.8511 - val_accuracy: 0.6978 - val_loss: 0.7734
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.7667 - val_accuracy: 0.7537 - val_loss: 0.5419
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.8515 - val_accuracy: 0.7761 - val_loss: 0.5117
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.7880 - val_accuracy: 0.5970 - val_loss: 0.8979
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.6296 - val_accuracy: 0.7873 - val_loss: 0.5887
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.8711 - val_accuracy: 0.4925 - val_loss: 1.4762
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.7333 - val_accuracy: 0.7687 - val_loss: 0.5172
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.8751 - val_accuracy: 0.7090 - val_loss: 0.7564
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6971 - val_accuracy: 0.4701 - val_loss: 2.0860
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.7548 - val_accuracy: 0.6493 - val_loss: 0.7971
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.7427 - val_accuracy: 0.7127 - val_loss: 0.9152
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.7757 - val_accuracy: 0.7687 - val_loss: 0.5070
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.8247 - val_accuracy: 0.5261 - val_loss: 1.1315
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6836 - val_accuracy: 0.6306 - val_loss: 1.9146
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.7048 - val_accuracy: 0.6716 - val_loss: 1.3460
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.6555 - val_accuracy: 0.7388 - val_loss: 0.6593
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.8119 - val_accuracy: 0.7687 - val_loss: 0.5292
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.8595 - val_accuracy: 0.7873 - val_loss: 0.6343
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.7751 - val_accuracy: 0.7873 - val_loss: 0.6039
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.6980 - val_accuracy: 0.7164 - val_loss: 0.7186
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6936 - val_accuracy: 0.7687 - val_loss: 0.5426
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.7744 - val_accuracy: 0.7836 - val_loss: 0.5827
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.7741 - val_accuracy: 0.7537 - val_loss: 0.5605
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.7739 - val_accuracy: 0.7425 - val_loss: 0.5745
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.7306 - val_accuracy: 0.7687 - val_loss: 0.5550
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.8297 - val_accuracy: 0.7201 - val_loss: 0.7241
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.6266 - val_accuracy: 0.7500 - val_loss: 0.5947
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.7950 - val_accuracy: 0.6231 - val_loss: 0.8728
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.6992 - val_accuracy: 0.7388 - val_loss: 0.6765
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.6097 - val_accuracy: 0.6231 - val_loss: 2.2166
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.8197 - val_accuracy: 0.6567 - val_loss: 1.4673
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.7674 - val_accuracy: 0.7687 - val_loss: 0.5249
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.6611 - val_accuracy: 0.5187 - val_loss: 1.1820
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.8770 - val_accuracy: 0.4963 - val_loss: 1.5106
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6729 - val_accuracy: 0.7724 - val_loss: 0.5474
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.8566 - val_accuracy: 0.7724 - val_loss: 0.5367
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6841 - val_accuracy: 0.7313 - val_loss: 0.7611
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.7935 - val_accuracy: 0.7799 - val_loss: 0.6627
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.7476 - val_accuracy: 0.7537 - val_loss: 0.6025
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.6927 - val_accuracy: 0.4776 - val_loss: 1.9793
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.7074 - val_accuracy: 0.6381 - val_loss: 1.7745
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.7571 - val_accuracy: 0.7724 - val_loss: 0.5693
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.7580 - val_accuracy: 0.7388 - val_loss: 0.7554
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.6845 - val_accuracy: 0.7799 - val_loss: 0.5371
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.7552 - val_accuracy: 0.7388 - val_loss: 0.6936
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.7749 - val_accuracy: 0.7873 - val_loss: 0.6390
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.6032 - val_accuracy: 0.6903 - val_loss: 1.1194
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.7303 - val_accuracy: 0.5373 - val_loss: 1.1571
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6674 - val_accuracy: 0.5896 - val_loss: 0.9721
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.8053 - val_accuracy: 0.7910 - val_loss: 0.6083
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.6996 - val_accuracy: 0.7687 - val_loss: 0.5419
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6750 - val_accuracy: 0.6978 - val_loss: 0.7815
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.7317 - val_accuracy: 0.7724 - val_loss: 0.5628
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.7278 - val_accuracy: 0.7836 - val_loss: 0.5514
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6933 - val_accuracy: 0.7724 - val_loss: 0.5591
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.6543 - val_accuracy: 0.7687 - val_loss: 0.5456
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.6902 - val_accuracy: 0.5522 - val_loss: 1.0684
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.7690 - val_accuracy: 0.6679 - val_loss: 1.2923
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.7541 - val_accuracy: 0.7388 - val_loss: 0.7480
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6450 - val_accuracy: 0.6530 - val_loss: 1.5554
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.8361 - val_accuracy: 0.7351 - val_loss: 0.7238
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.6573 - val_accuracy: 0.7164 - val_loss: 0.8795
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.6937 - val_accuracy: 0.7649 - val_loss: 0.5534
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.6693 - val_accuracy: 0.7276 - val_loss: 0.7289
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.6991 - val_accuracy: 0.6791 - val_loss: 1.4695
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.7072 - val_accuracy: 0.7724 - val_loss: 0.5540
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.6314 - val_accuracy: 0.6642 - val_loss: 0.8113
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.7229 - val_accuracy: 0.7015 - val_loss: 0.8497
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.8331 - val_accuracy: 0.7724 - val_loss: 0.5653
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.6597 - val_accuracy: 0.6828 - val_loss: 1.2070
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: cvwk74rb with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6116 - loss: 28.3056 - val_accuracy: 0.6269 - val_loss: 19.3265
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 13.5134 - val_accuracy: 0.6231 - val_loss: 7.0656
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5393 - loss: 3.0971 - val_accuracy: 0.3694 - val_loss: 0.7012
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6996 - val_accuracy: 0.3731 - val_loss: 0.7002
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6990 - val_accuracy: 0.3731 - val_loss: 0.6992
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6981 - val_accuracy: 0.3731 - val_loss: 0.6981
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6970 - val_accuracy: 0.3731 - val_loss: 0.6969
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6959 - val_accuracy: 0.3731 - val_loss: 0.6956
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6948 - val_accuracy: 0.3731 - val_loss: 0.6945
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 0.6938 - val_accuracy: 0.6269 - val_loss: 0.6931
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6927 - val_accuracy: 0.6269 - val_loss: 0.6919
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6916 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6905 - val_accuracy: 0.6269 - val_loss: 0.6894
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6895 - val_accuracy: 0.6269 - val_loss: 0.6883
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6885 - val_accuracy: 0.6269 - val_loss: 0.6871
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6875 - val_accuracy: 0.6269 - val_loss: 0.6860
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6865 - val_accuracy: 0.6269 - val_loss: 0.6849
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6856 - val_accuracy: 0.6269 - val_loss: 0.6839
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6847 - val_accuracy: 0.6269 - val_loss: 0.6828
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6838 - val_accuracy: 0.6269 - val_loss: 0.6818
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6830 - val_accuracy: 0.6269 - val_loss: 0.6808
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6821 - val_accuracy: 0.6269 - val_loss: 0.6799
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6813 - val_accuracy: 0.6269 - val_loss: 0.6790
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6806 - val_accuracy: 0.6269 - val_loss: 0.6781
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6799 - val_accuracy: 0.6269 - val_loss: 0.6772
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6792 - val_accuracy: 0.6269 - val_loss: 0.6765
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6785 - val_accuracy: 0.6269 - val_loss: 0.6757
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6779 - val_accuracy: 0.6269 - val_loss: 0.6749
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6773 - val_accuracy: 0.6269 - val_loss: 0.6742
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6768 - val_accuracy: 0.6269 - val_loss: 0.6734
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6762 - val_accuracy: 0.6269 - val_loss: 0.6729
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6757 - val_accuracy: 0.6269 - val_loss: 0.6723
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6753 - val_accuracy: 0.6269 - val_loss: 0.6717
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6748 - val_accuracy: 0.6269 - val_loss: 0.6711
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6744 - val_accuracy: 0.6269 - val_loss: 0.6707
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6740 - val_accuracy: 0.6269 - val_loss: 0.6701
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6736 - val_accuracy: 0.6269 - val_loss: 0.6697
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6733 - val_accuracy: 0.6269 - val_loss: 0.6693
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6729 - val_accuracy: 0.6269 - val_loss: 0.6688
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6726 - val_accuracy: 0.6269 - val_loss: 0.6684
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6722 - val_accuracy: 0.6269 - val_loss: 0.6680
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6720 - val_accuracy: 0.6269 - val_loss: 0.6676
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6717 - val_accuracy: 0.6269 - val_loss: 0.6671
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6714 - val_accuracy: 0.6269 - val_loss: 0.6668
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6712 - val_accuracy: 0.6269 - val_loss: 0.6665
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6710 - val_accuracy: 0.6269 - val_loss: 0.6664
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6708 - val_accuracy: 0.6269 - val_loss: 0.6660
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6706 - val_accuracy: 0.6269 - val_loss: 0.6657
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6704 - val_accuracy: 0.6269 - val_loss: 0.6654
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6702 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6701 - val_accuracy: 0.6269 - val_loss: 0.6650
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6700 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6697 - val_accuracy: 0.6269 - val_loss: 0.6645
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6696 - val_accuracy: 0.6269 - val_loss: 0.6644
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6695 - val_accuracy: 0.6269 - val_loss: 0.6641
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6694 - val_accuracy: 0.6269 - val_loss: 0.6640
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6693 - val_accuracy: 0.6269 - val_loss: 0.6638
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6692 - val_accuracy: 0.6269 - val_loss: 0.6637
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6691 - val_accuracy: 0.6269 - val_loss: 0.6636
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6691 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.6633
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6689 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6689 - val_accuracy: 0.6269 - val_loss: 0.6631
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6688 - val_accuracy: 0.6269 - val_loss: 0.6630
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6628
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6625
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6624
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6622
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6618
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6619
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6618
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6682 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6616
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6615
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6614
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6613
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6611
Epoch 155/5000

wandb: Agent Starting Run: 7hbwkhai with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5714 - loss: 2.4513 - val_accuracy: 0.6119 - val_loss: 0.6989
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6894 - val_accuracy: 0.6119 - val_loss: 0.6906
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6860 - val_accuracy: 0.6082 - val_loss: 0.6869
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6838 - val_accuracy: 0.6157 - val_loss: 0.6813
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6817 - val_accuracy: 0.6157 - val_loss: 0.6803
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6798 - val_accuracy: 0.6157 - val_loss: 0.6776
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6783 - val_accuracy: 0.6194 - val_loss: 0.6753
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6768 - val_accuracy: 0.6157 - val_loss: 0.6770
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6755 - val_accuracy: 0.6157 - val_loss: 0.6736
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6743 - val_accuracy: 0.6194 - val_loss: 0.6717
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6733 - val_accuracy: 0.6157 - val_loss: 0.6727
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6729 - val_accuracy: 0.6157 - val_loss: 0.6722
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6720 - val_accuracy: 0.6157 - val_loss: 0.6712
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6714 - val_accuracy: 0.6194 - val_loss: 0.6689
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6711 - val_accuracy: 0.6231 - val_loss: 0.6688
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6704 - val_accuracy: 0.6157 - val_loss: 0.6706
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6698 - val_accuracy: 0.6157 - val_loss: 0.6682
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6695 - val_accuracy: 0.6231 - val_loss: 0.6677
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6690 - val_accuracy: 0.6231 - val_loss: 0.6672
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6685 - val_accuracy: 0.6157 - val_loss: 0.6685
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6687 - val_accuracy: 0.6157 - val_loss: 0.6676
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6682 - val_accuracy: 0.6157 - val_loss: 0.6692
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6677 - val_accuracy: 0.6157 - val_loss: 0.6672
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6678 - val_accuracy: 0.6157 - val_loss: 0.6674
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6157 - val_loss: 0.6691
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6675 - val_accuracy: 0.6157 - val_loss: 0.6674
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6157 - val_loss: 0.6666
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6673 - val_accuracy: 0.6231 - val_loss: 0.6658
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6673 - val_accuracy: 0.6231 - val_loss: 0.6655
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6231 - val_loss: 0.6652
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6669 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6668 - val_accuracy: 0.6157 - val_loss: 0.6685
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6669 - val_accuracy: 0.6157 - val_loss: 0.6671
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6668 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6157 - val_loss: 0.6666
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6157 - val_loss: 0.6667
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6157 - val_loss: 0.6661
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6665 - val_accuracy: 0.6157 - val_loss: 0.6662
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6674
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6667 - val_accuracy: 0.6157 - val_loss: 0.6666
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6658
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6651
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6652
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6650
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6658
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6665 - val_accuracy: 0.6157 - val_loss: 0.6663
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6651
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6651
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6650
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6666 - val_accuracy: 0.6194 - val_loss: 0.6652
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6194 - val_loss: 0.6640
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6644
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6650
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6666
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6654
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6656
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6665 - val_accuracy: 0.6194 - val_loss: 0.6652
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6663 - val_accuracy: 0.6194 - val_loss: 0.6652
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6649
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6638
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6665 - val_accuracy: 0.6194 - val_loss: 0.6640
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6637
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6638
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6637
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6651
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6649
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6643
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6651
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6194 - val_loss: 0.6652
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6661
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6644
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6630
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6648
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6643
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6643
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6194 - val_loss: 0.6654
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6194 - val_loss: 0.6653
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6658
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6655
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6649
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6659
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6659
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6659
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6644
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6656
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6672
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6667 - val_accuracy: 0.6231 - val_loss: 0.6650
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6641
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6663
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6662
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6662
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6659
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6663
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6654
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6639
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6665 - val_accuracy: 0.6157 - val_loss: 0.6653
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6665 - val_accuracy: 0.6231 - val_loss: 0.6649
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6665 - val_accuracy: 0.6231 - val_loss: 0.6649
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6648
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6658 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6656
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6668
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6683
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6675
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6655
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6157 - val_loss: 0.6661
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6651
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6639
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6659 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6653
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6654
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6194 - val_loss: 0.6641
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6656
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6660
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6657
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6666
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6647
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6194 - val_loss: 0.6643
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6648
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6648
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6659 - val_accuracy: 0.6194 - val_loss: 0.6641
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6660 - val_accuracy: 0.6194 - val_loss: 0.6643
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6652
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.6654
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6658 - val_accuracy: 0.6157 - val_loss: 0.6661
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6664 - val_accuracy: 0.6157 - val_loss: 0.6653
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6651
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6636
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: piwnatuu with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4880 - loss: 9.6930 - val_accuracy: 0.2985 - val_loss: 5.6370
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3965 - loss: 4.9355 - val_accuracy: 0.3657 - val_loss: 4.6042
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4045 - loss: 3.9877 - val_accuracy: 0.3433 - val_loss: 3.1724
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4061 - loss: 3.0310 - val_accuracy: 0.5000 - val_loss: 2.8183
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4302 - loss: 2.7122 - val_accuracy: 0.5373 - val_loss: 2.7203
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4591 - loss: 2.4378 - val_accuracy: 0.3284 - val_loss: 2.1987
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4238 - loss: 2.1928 - val_accuracy: 0.5299 - val_loss: 2.1441
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4334 - loss: 2.0109 - val_accuracy: 0.5448 - val_loss: 1.9094
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4350 - loss: 1.7558 - val_accuracy: 0.3321 - val_loss: 1.7085
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4526 - loss: 1.5382 - val_accuracy: 0.4963 - val_loss: 1.1948
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4623 - loss: 1.2972 - val_accuracy: 0.5709 - val_loss: 1.3126
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4735 - loss: 1.1930 - val_accuracy: 0.3993 - val_loss: 1.4355
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4751 - loss: 1.1035 - val_accuracy: 0.5485 - val_loss: 0.8734
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.4976 - loss: 1.0958 - val_accuracy: 0.6157 - val_loss: 0.8688
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5217 - loss: 0.9651 - val_accuracy: 0.6343 - val_loss: 0.9001
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5104 - loss: 0.9786 - val_accuracy: 0.5858 - val_loss: 0.7118
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5329 - loss: 0.9368 - val_accuracy: 0.6231 - val_loss: 1.2854
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5522 - loss: 0.9256 - val_accuracy: 0.3881 - val_loss: 0.9042
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5570 - loss: 0.8288 - val_accuracy: 0.6269 - val_loss: 1.3702
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 0.8146 - val_accuracy: 0.6493 - val_loss: 0.9916
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5811 - loss: 0.8014 - val_accuracy: 0.6418 - val_loss: 1.0849
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5907 - loss: 0.8158 - val_accuracy: 0.7052 - val_loss: 0.6190
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6067 - loss: 0.7757 - val_accuracy: 0.6828 - val_loss: 0.6098
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5939 - loss: 0.8526 - val_accuracy: 0.6455 - val_loss: 0.7579
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5650 - loss: 0.8350 - val_accuracy: 0.6679 - val_loss: 0.6273
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5827 - loss: 0.7991 - val_accuracy: 0.6231 - val_loss: 1.2118
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5602 - loss: 0.8686 - val_accuracy: 0.6716 - val_loss: 0.6211
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.6881 - val_accuracy: 0.7015 - val_loss: 0.5847
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 0.8560 - val_accuracy: 0.6381 - val_loss: 0.8853
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.7441 - val_accuracy: 0.4963 - val_loss: 0.7378
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5762 - loss: 0.7570 - val_accuracy: 0.4701 - val_loss: 1.0407
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.7812 - val_accuracy: 0.6119 - val_loss: 0.6705
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.7417 - val_accuracy: 0.6978 - val_loss: 0.5929
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.7098 - val_accuracy: 0.6754 - val_loss: 0.5916
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5971 - loss: 0.8130 - val_accuracy: 0.4478 - val_loss: 1.1455
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7274 - val_accuracy: 0.4515 - val_loss: 1.1545
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 0.7773 - val_accuracy: 0.6754 - val_loss: 0.5846
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.7724 - val_accuracy: 0.6791 - val_loss: 0.5826
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.7338 - val_accuracy: 0.4627 - val_loss: 0.8249
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.6943 - val_accuracy: 0.6231 - val_loss: 1.1472
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.7246 - val_accuracy: 0.6716 - val_loss: 0.6420
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.7573 - val_accuracy: 0.6866 - val_loss: 0.5788
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6938 - val_accuracy: 0.6493 - val_loss: 0.7634
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.7090 - val_accuracy: 0.6418 - val_loss: 0.6626
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6979 - val_accuracy: 0.6269 - val_loss: 0.9853
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.7201 - val_accuracy: 0.6381 - val_loss: 0.8888
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.6904 - val_accuracy: 0.7164 - val_loss: 0.5481
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.7063 - val_accuracy: 0.6940 - val_loss: 0.5503
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.7376 - val_accuracy: 0.6269 - val_loss: 0.9363
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6932 - val_accuracy: 0.6604 - val_loss: 0.6216
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6722 - val_accuracy: 0.7575 - val_loss: 0.5638
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.7214 - val_accuracy: 0.7015 - val_loss: 0.5497
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.6906 - val_accuracy: 0.7052 - val_loss: 0.5488
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.7127 - val_accuracy: 0.6343 - val_loss: 1.2415
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.7170 - val_accuracy: 0.7276 - val_loss: 0.5972
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.7215 - val_accuracy: 0.7612 - val_loss: 0.5599
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6306 - val_accuracy: 0.4552 - val_loss: 0.9418
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.7580 - val_accuracy: 0.7537 - val_loss: 0.5478
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6810 - val_accuracy: 0.7687 - val_loss: 0.5640
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.6673 - val_accuracy: 0.6604 - val_loss: 0.5715
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6380 - val_accuracy: 0.4478 - val_loss: 1.3037
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6850 - val_accuracy: 0.7239 - val_loss: 0.6096
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.7009 - val_accuracy: 0.7090 - val_loss: 0.5332
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6814 - val_accuracy: 0.7090 - val_loss: 0.5374
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6500 - val_accuracy: 0.7201 - val_loss: 0.5367
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.7026 - val_accuracy: 0.6828 - val_loss: 0.6006
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.6839 - val_accuracy: 0.6791 - val_loss: 0.5763
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6479 - val_accuracy: 0.4664 - val_loss: 1.0856
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.7044 - val_accuracy: 0.6754 - val_loss: 0.6258
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6819 - val_accuracy: 0.5224 - val_loss: 0.8028
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6668 - val_accuracy: 0.7425 - val_loss: 0.5326
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6727 - val_accuracy: 0.5336 - val_loss: 0.7678
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6520 - val_accuracy: 0.6716 - val_loss: 0.5899
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6438 - val_accuracy: 0.7239 - val_loss: 0.5238
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6482 - val_accuracy: 0.5373 - val_loss: 0.7926
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6713 - val_accuracy: 0.7612 - val_loss: 0.5480
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6366 - val_accuracy: 0.6381 - val_loss: 0.8514
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6882 - val_accuracy: 0.7649 - val_loss: 0.5404
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.5987 - val_accuracy: 0.4851 - val_loss: 0.9159
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6707 - val_accuracy: 0.7090 - val_loss: 0.5257
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6344 - val_accuracy: 0.7201 - val_loss: 0.5969
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6348 - val_accuracy: 0.4701 - val_loss: 1.3651
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6878 - val_accuracy: 0.7201 - val_loss: 0.5228
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6322 - val_accuracy: 0.7015 - val_loss: 0.5399
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6710 - val_accuracy: 0.6306 - val_loss: 0.9888
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6474 - val_accuracy: 0.7276 - val_loss: 0.5203
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.6258 - val_accuracy: 0.6754 - val_loss: 0.7055
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6705 - val_accuracy: 0.7537 - val_loss: 0.5420
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5756 - val_accuracy: 0.6978 - val_loss: 0.6114
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6513 - val_accuracy: 0.6903 - val_loss: 0.5635
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.6707 - val_accuracy: 0.6940 - val_loss: 0.5607
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6327 - val_accuracy: 0.6866 - val_loss: 0.5785
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6413 - val_accuracy: 0.7612 - val_loss: 0.5317
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6014 - val_accuracy: 0.6455 - val_loss: 0.8252
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6468 - val_accuracy: 0.7575 - val_loss: 0.5148
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6528 - val_accuracy: 0.6866 - val_loss: 0.6299
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6242 - val_accuracy: 0.6903 - val_loss: 0.6268
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5874 - val_accuracy: 0.6903 - val_loss: 0.6405
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6582 - val_accuracy: 0.7127 - val_loss: 0.5940
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5908 - val_accuracy: 0.7015 - val_loss: 0.5288
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.6162 - val_accuracy: 0.6642 - val_loss: 0.7388
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6249 - val_accuracy: 0.6940 - val_loss: 0.5575
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6687 - val_accuracy: 0.6866 - val_loss: 0.6257
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6269 - val_accuracy: 0.4776 - val_loss: 0.9643
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5783 - val_accuracy: 0.6903 - val_loss: 0.5737
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.6387 - val_accuracy: 0.6530 - val_loss: 0.8823
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6197 - val_accuracy: 0.6828 - val_loss: 0.6898
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6299 - val_accuracy: 0.6381 - val_loss: 0.9581
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5804 - val_accuracy: 0.5821 - val_loss: 0.7267
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5995 - val_accuracy: 0.6791 - val_loss: 0.6875
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.6253 - val_accuracy: 0.4739 - val_loss: 1.0758
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5592 - val_accuracy: 0.7052 - val_loss: 0.5550
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6506 - val_accuracy: 0.6679 - val_loss: 0.6230
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5768 - val_accuracy: 0.4776 - val_loss: 1.0458
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5988 - val_accuracy: 0.7687 - val_loss: 0.5282
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5944 - val_accuracy: 0.7463 - val_loss: 0.4893
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6455 - val_accuracy: 0.7425 - val_loss: 0.4915
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5393 - val_accuracy: 0.6604 - val_loss: 0.7577
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6259 - val_accuracy: 0.6716 - val_loss: 0.6197
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.6229 - val_accuracy: 0.4851 - val_loss: 1.0533
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6020 - val_accuracy: 0.5522 - val_loss: 0.8210
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5846 - val_accuracy: 0.7687 - val_loss: 0.4955
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5757 - val_accuracy: 0.7052 - val_loss: 0.5279
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6157 - val_accuracy: 0.7015 - val_loss: 0.5546
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5691 - val_accuracy: 0.6567 - val_loss: 0.9010
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5983 - val_accuracy: 0.7425 - val_loss: 0.4920
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6142 - val_accuracy: 0.7201 - val_loss: 0.5243
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5785 - val_accuracy: 0.7649 - val_loss: 0.4928
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5656 - val_accuracy: 0.7313 - val_loss: 0.4992
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.6496 - val_accuracy: 0.6828 - val_loss: 0.6879
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5837 - val_accuracy: 0.6642 - val_loss: 0.8022
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5533 - val_accuracy: 0.5933 - val_loss: 0.7595
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5800 - val_accuracy: 0.6679 - val_loss: 0.6987
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5443 - val_accuracy: 0.5373 - val_loss: 0.8706
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5903 - val_accuracy: 0.6828 - val_loss: 0.6163
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6375 - val_accuracy: 0.5821 - val_loss: 0.8108
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5670 - val_accuracy: 0.6306 - val_loss: 1.0147
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6078 - val_accuracy: 0.5858 - val_loss: 0.7669
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5771 - val_accuracy: 0.4963 - val_loss: 1.1270
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6085 - val_accuracy: 0.7090 - val_loss: 0.6032
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5786 - val_accuracy: 0.7164 - val_loss: 0.5464
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5620 - val_accuracy: 0.7761 - val_loss: 0.5388
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5811 - val_accuracy: 0.7799 - val_loss: 0.5303
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6091 - val_accuracy: 0.6455 - val_loss: 0.6523
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5462 - val_accuracy: 0.7687 - val_loss: 0.4779
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5971 - val_accuracy: 0.7090 - val_loss: 0.6243
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5305 - val_accuracy: 0.4925 - val_loss: 1.0686
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6334 - val_accuracy: 0.7761 - val_loss: 0.4880
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5684 - val_accuracy: 0.7537 - val_loss: 0.4777
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5477 - val_accuracy: 0.7799 - val_loss: 0.4841
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5453 - val_accuracy: 0.7761 - val_loss: 0.4957
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5993 - val_accuracy: 0.6679 - val_loss: 0.7655
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5387 - val_accuracy: 0.5261 - val_loss: 0.9499
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5660 - val_accuracy: 0.7649 - val_loss: 0.5597
Epoch 155/5000

wandb: Agent Starting Run: j8wkbdwg with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5185 - loss: 5.0796 - val_accuracy: 0.6306 - val_loss: 2.8016
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5538 - loss: 1.2097 - val_accuracy: 0.6306 - val_loss: 0.9116
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5811 - loss: 0.7257 - val_accuracy: 0.6716 - val_loss: 0.6928
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5939 - loss: 0.6776 - val_accuracy: 0.6642 - val_loss: 0.6920
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6752 - val_accuracy: 0.7090 - val_loss: 0.6741
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.6708 - val_accuracy: 0.6716 - val_loss: 0.6873
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6490 - val_accuracy: 0.6903 - val_loss: 0.6739
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6384 - val_accuracy: 0.6978 - val_loss: 0.6766
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.6382 - val_accuracy: 0.6791 - val_loss: 0.6856
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6347 - val_accuracy: 0.6940 - val_loss: 0.6695
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6342 - val_accuracy: 0.7201 - val_loss: 0.6688
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6435 - val_accuracy: 0.7201 - val_loss: 0.6819
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6641 - val_accuracy: 0.6642 - val_loss: 0.6944
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6412 - val_accuracy: 0.6754 - val_loss: 0.6867
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6378 - val_accuracy: 0.6716 - val_loss: 0.6977
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6454 - val_accuracy: 0.6604 - val_loss: 0.8092
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.6704 - val_accuracy: 0.7351 - val_loss: 0.6733
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6309 - val_accuracy: 0.6978 - val_loss: 0.6611
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6400 - val_accuracy: 0.6754 - val_loss: 0.6931
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.6581 - val_accuracy: 0.7276 - val_loss: 0.6638
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6354 - val_accuracy: 0.6940 - val_loss: 0.6575
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6282 - val_accuracy: 0.6716 - val_loss: 0.7104
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6710 - val_accuracy: 0.6978 - val_loss: 0.6525
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6175 - val_accuracy: 0.6940 - val_loss: 0.6724
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6701 - val_accuracy: 0.6754 - val_loss: 0.7021
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6346 - val_accuracy: 0.6903 - val_loss: 0.6773
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.6239 - val_accuracy: 0.7201 - val_loss: 0.6467
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6156 - val_accuracy: 0.7500 - val_loss: 0.6665
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.6552 - val_accuracy: 0.5970 - val_loss: 0.7282
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6343 - val_accuracy: 0.6716 - val_loss: 0.7093
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.6329 - val_accuracy: 0.6791 - val_loss: 0.7043
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6705 - val_accuracy: 0.6119 - val_loss: 0.7265
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6392 - val_accuracy: 0.6119 - val_loss: 0.7220
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6206 - val_accuracy: 0.7090 - val_loss: 0.6417
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.5993 - val_accuracy: 0.7313 - val_loss: 0.6376
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5968 - val_accuracy: 0.7575 - val_loss: 0.6417
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6021 - val_accuracy: 0.6866 - val_loss: 0.6762
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.5952 - val_accuracy: 0.6978 - val_loss: 0.6737
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6120 - val_accuracy: 0.6940 - val_loss: 0.6762
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6330 - val_accuracy: 0.6978 - val_loss: 0.6572
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6557 - val_accuracy: 0.6791 - val_loss: 0.7508
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.6298 - val_accuracy: 0.6791 - val_loss: 0.7405
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6315 - val_accuracy: 0.6754 - val_loss: 0.7208
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.7070 - val_accuracy: 0.7276 - val_loss: 0.6261
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6072 - val_accuracy: 0.6754 - val_loss: 0.7284
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6093 - val_accuracy: 0.7649 - val_loss: 0.6328
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5850 - val_accuracy: 0.7649 - val_loss: 0.6436
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.5863 - val_accuracy: 0.6791 - val_loss: 0.7632
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6338 - val_accuracy: 0.6866 - val_loss: 0.6823
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5735 - val_accuracy: 0.7388 - val_loss: 0.6489
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5825 - val_accuracy: 0.7761 - val_loss: 0.6418
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5947 - val_accuracy: 0.7313 - val_loss: 0.6605
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6337 - val_accuracy: 0.6828 - val_loss: 0.7252
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.5782 - val_accuracy: 0.7463 - val_loss: 0.6158
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5609 - val_accuracy: 0.7873 - val_loss: 0.6323
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5772 - val_accuracy: 0.7388 - val_loss: 0.6154
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6003 - val_accuracy: 0.6679 - val_loss: 0.8049
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6128 - val_accuracy: 0.7537 - val_loss: 0.6110
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5695 - val_accuracy: 0.7500 - val_loss: 0.6087
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5603 - val_accuracy: 0.7575 - val_loss: 0.6066
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5499 - val_accuracy: 0.7425 - val_loss: 0.6134
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5556 - val_accuracy: 0.7948 - val_loss: 0.6291
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.5793 - val_accuracy: 0.7836 - val_loss: 0.6069
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5454 - val_accuracy: 0.7463 - val_loss: 0.6091
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5542 - val_accuracy: 0.7575 - val_loss: 0.6075
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5388 - val_accuracy: 0.7127 - val_loss: 0.6225
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5505 - val_accuracy: 0.7351 - val_loss: 0.6124
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5555 - val_accuracy: 0.7463 - val_loss: 0.6086
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5414 - val_accuracy: 0.6828 - val_loss: 0.7188
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5505 - val_accuracy: 0.7239 - val_loss: 0.6130
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6088 - val_accuracy: 0.6791 - val_loss: 0.7061
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5590 - val_accuracy: 0.7575 - val_loss: 0.6006
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5391 - val_accuracy: 0.7127 - val_loss: 0.6261
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5503 - val_accuracy: 0.5970 - val_loss: 0.7691
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5499 - val_accuracy: 0.7649 - val_loss: 0.6291
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5739 - val_accuracy: 0.7127 - val_loss: 0.6401
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5378 - val_accuracy: 0.7799 - val_loss: 0.5886
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5395 - val_accuracy: 0.7799 - val_loss: 0.5907
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5258 - val_accuracy: 0.7537 - val_loss: 0.5969
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5359 - val_accuracy: 0.7873 - val_loss: 0.5844
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5501 - val_accuracy: 0.7127 - val_loss: 0.6541
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5363 - val_accuracy: 0.7649 - val_loss: 0.6298
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5172 - val_accuracy: 0.7799 - val_loss: 0.5816
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5152 - val_accuracy: 0.7836 - val_loss: 0.5893
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5394 - val_accuracy: 0.8022 - val_loss: 0.6038
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5168 - val_accuracy: 0.7090 - val_loss: 0.6281
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5254 - val_accuracy: 0.7575 - val_loss: 0.5898
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5137 - val_accuracy: 0.7799 - val_loss: 0.5800
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5531 - val_accuracy: 0.8022 - val_loss: 0.5996
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5298 - val_accuracy: 0.7948 - val_loss: 0.5883
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5530 - val_accuracy: 0.7799 - val_loss: 0.6287
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5965 - val_accuracy: 0.7799 - val_loss: 0.6165
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5208 - val_accuracy: 0.8060 - val_loss: 0.5957
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6095 - val_accuracy: 0.8097 - val_loss: 0.6009
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5628 - val_accuracy: 0.7127 - val_loss: 0.6572
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5366 - val_accuracy: 0.7948 - val_loss: 0.6084
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4906 - val_accuracy: 0.6903 - val_loss: 0.7125
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5486 - val_accuracy: 0.7799 - val_loss: 0.5723
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4966 - val_accuracy: 0.7799 - val_loss: 0.5730
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5196 - val_accuracy: 0.7575 - val_loss: 0.5819
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4892 - val_accuracy: 0.7799 - val_loss: 0.5689
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4848 - val_accuracy: 0.7873 - val_loss: 0.5750
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4979 - val_accuracy: 0.7873 - val_loss: 0.5796
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4980 - val_accuracy: 0.7724 - val_loss: 0.6184
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4920 - val_accuracy: 0.7687 - val_loss: 0.5784
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4864 - val_accuracy: 0.7537 - val_loss: 0.5898
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4902 - val_accuracy: 0.7836 - val_loss: 0.5736
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5056 - val_accuracy: 0.7612 - val_loss: 0.6349
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5098 - val_accuracy: 0.7649 - val_loss: 0.5828
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4942 - val_accuracy: 0.7799 - val_loss: 0.5773
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5115 - val_accuracy: 0.7799 - val_loss: 0.5738
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5381 - val_accuracy: 0.7724 - val_loss: 0.5829
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5002 - val_accuracy: 0.7201 - val_loss: 0.6334
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4940 - val_accuracy: 0.7873 - val_loss: 0.5744
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4882 - val_accuracy: 0.7948 - val_loss: 0.5877
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4888 - val_accuracy: 0.7873 - val_loss: 0.5697
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4849 - val_accuracy: 0.7724 - val_loss: 0.5727
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5042 - val_accuracy: 0.7910 - val_loss: 0.5754
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4741 - val_accuracy: 0.7836 - val_loss: 0.5683
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4706 - val_accuracy: 0.7799 - val_loss: 0.5693
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4779 - val_accuracy: 0.7799 - val_loss: 0.5731
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4790 - val_accuracy: 0.7761 - val_loss: 0.5702
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4769 - val_accuracy: 0.7799 - val_loss: 0.5674
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4754 - val_accuracy: 0.7425 - val_loss: 0.6126
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4679 - val_accuracy: 0.7761 - val_loss: 0.5672
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4762 - val_accuracy: 0.7910 - val_loss: 0.5793
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4978 - val_accuracy: 0.7873 - val_loss: 0.5686
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4723 - val_accuracy: 0.7799 - val_loss: 0.5751
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4784 - val_accuracy: 0.7873 - val_loss: 0.5793
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4649 - val_accuracy: 0.7761 - val_loss: 0.5707
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4981 - val_accuracy: 0.7724 - val_loss: 0.6217
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5324 - val_accuracy: 0.6119 - val_loss: 0.8187
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5275 - val_accuracy: 0.7575 - val_loss: 0.6330
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4791 - val_accuracy: 0.7761 - val_loss: 0.6179
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5202 - val_accuracy: 0.7873 - val_loss: 0.5781
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4677 - val_accuracy: 0.7873 - val_loss: 0.5845
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4938 - val_accuracy: 0.7761 - val_loss: 0.5709
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4731 - val_accuracy: 0.7910 - val_loss: 0.6005
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5002 - val_accuracy: 0.7948 - val_loss: 0.6049
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5202 - val_accuracy: 0.6866 - val_loss: 0.6983
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5119 - val_accuracy: 0.6903 - val_loss: 0.6997
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5115 - val_accuracy: 0.7873 - val_loss: 0.5791
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4728 - val_accuracy: 0.7537 - val_loss: 0.6389
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4983 - val_accuracy: 0.7761 - val_loss: 0.5696
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5898 - val_accuracy: 0.7351 - val_loss: 0.6623
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4842 - val_accuracy: 0.7873 - val_loss: 0.5848
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5222 - val_accuracy: 0.7425 - val_loss: 0.6439
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5081 - val_accuracy: 0.7799 - val_loss: 0.6047
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5053 - val_accuracy: 0.7836 - val_loss: 0.5693
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4688 - val_accuracy: 0.7799 - val_loss: 0.5756
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4762 - val_accuracy: 0.7761 - val_loss: 0.5740
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4771 - val_accuracy: 0.7687 - val_loss: 0.6312
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4750 - val_accuracy: 0.7799 - val_loss: 0.5759
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4782 - val_accuracy: 0.7799 - val_loss: 0.6022
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 0mgg5wqi with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5987 - loss: 28.6030 - val_accuracy: 0.6269 - val_loss: 0.8765
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7310 - val_accuracy: 0.6269 - val_loss: 0.8563
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7165 - val_accuracy: 0.6269 - val_loss: 0.7704
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6980 - val_accuracy: 0.6269 - val_loss: 0.7628
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6916 - val_accuracy: 0.6269 - val_loss: 0.7521
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6906 - val_accuracy: 0.6269 - val_loss: 0.7100
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6883 - val_accuracy: 0.6269 - val_loss: 0.7017
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6847 - val_accuracy: 0.6269 - val_loss: 0.7068
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6817 - val_accuracy: 0.6269 - val_loss: 0.7074
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6794 - val_accuracy: 0.6269 - val_loss: 0.7086
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6776 - val_accuracy: 0.6269 - val_loss: 0.7126
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6762 - val_accuracy: 0.6269 - val_loss: 0.7126
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6752 - val_accuracy: 0.6269 - val_loss: 0.7125
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6743 - val_accuracy: 0.6269 - val_loss: 0.7129
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6735 - val_accuracy: 0.6269 - val_loss: 0.7127
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6735 - val_accuracy: 0.6269 - val_loss: 0.6773
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6750 - val_accuracy: 0.6269 - val_loss: 0.6769
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6729 - val_accuracy: 0.6269 - val_loss: 0.6979
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6710 - val_accuracy: 0.6269 - val_loss: 0.6986
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6704 - val_accuracy: 0.6269 - val_loss: 0.6998
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6699 - val_accuracy: 0.6269 - val_loss: 0.7007
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6695 - val_accuracy: 0.6269 - val_loss: 0.7016
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.7021
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6686 - val_accuracy: 0.6269 - val_loss: 0.7024
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.7028
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.7034
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.7040
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.7042
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.7042
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6668 - val_accuracy: 0.6343 - val_loss: 0.7044
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.7044
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6662 - val_accuracy: 0.6343 - val_loss: 0.7048
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6343 - val_loss: 0.7049
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.7048
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6655 - val_accuracy: 0.6343 - val_loss: 0.7049
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6652 - val_accuracy: 0.6343 - val_loss: 0.7051
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6343 - val_loss: 0.7050
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6343 - val_loss: 0.7050
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6343 - val_loss: 0.7052
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.7052
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7049
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7049
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.7053
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.7057
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6231 - val_loss: 0.7060
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6231 - val_loss: 0.7064
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6635 - val_accuracy: 0.6231 - val_loss: 0.7066
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6634 - val_accuracy: 0.6231 - val_loss: 0.7070
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.7077
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.7073
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.7080
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.7079
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6629 - val_accuracy: 0.6194 - val_loss: 0.7079
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6194 - val_loss: 0.7080
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6627 - val_accuracy: 0.6194 - val_loss: 0.7066
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6627 - val_accuracy: 0.6194 - val_loss: 0.7077
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.7070
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.7063
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.7075
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.7078
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.7077
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.7087
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.7084
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.7084
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6194 - val_loss: 0.7086
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6194 - val_loss: 0.7080
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7084
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7088
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7087
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6194 - val_loss: 0.7096
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6194 - val_loss: 0.7090
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6194 - val_loss: 0.7094
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.7094
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.7095
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.7097
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.7096
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.7106
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.7111
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.7105
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.7100
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.7111
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.7105
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.7109
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.7111
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.7121
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.7122
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.7125
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6615 - val_accuracy: 0.6157 - val_loss: 0.7127
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6119 - val_loss: 0.7121
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6119 - val_loss: 0.7121
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.7126
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.7128
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.7125
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7129
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7136
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7137
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7140
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7148
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.7150
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7150
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7158
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7158
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7165
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.7148
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.7157
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.7169
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7176
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7189
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7192
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7193
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.7193
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.7209
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.7216
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.7236
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.7243
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.7234
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.7232
Epoch 117: early stopping

wandb: Agent Starting Run: xml1e8iz with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5393 - loss: 3.0523 - val_accuracy: 0.5000 - val_loss: 1.8528
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4992 - loss: 1.7925 - val_accuracy: 0.5485 - val_loss: 1.4756
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5313 - loss: 1.4077 - val_accuracy: 0.3619 - val_loss: 1.5346
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5313 - loss: 1.1956 - val_accuracy: 0.3993 - val_loss: 1.2829
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5297 - loss: 1.1590 - val_accuracy: 0.4030 - val_loss: 1.9442
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5345 - loss: 1.0519 - val_accuracy: 0.5634 - val_loss: 0.9983
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5329 - loss: 1.0642 - val_accuracy: 0.6007 - val_loss: 1.1304
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5361 - loss: 1.0432 - val_accuracy: 0.6045 - val_loss: 0.7972
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5698 - loss: 0.8963 - val_accuracy: 0.6082 - val_loss: 0.9871
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5666 - loss: 0.9335 - val_accuracy: 0.6082 - val_loss: 0.7385
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5859 - loss: 0.8771 - val_accuracy: 0.6604 - val_loss: 0.8643
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5907 - loss: 0.8485 - val_accuracy: 0.6493 - val_loss: 0.6927
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.7615 - val_accuracy: 0.3993 - val_loss: 1.0055
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 0.8568 - val_accuracy: 0.6530 - val_loss: 0.8150
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5955 - loss: 0.7845 - val_accuracy: 0.4030 - val_loss: 1.1515
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5859 - loss: 0.8335 - val_accuracy: 0.6567 - val_loss: 0.8344
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.7625 - val_accuracy: 0.4254 - val_loss: 0.8308
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 0.7811 - val_accuracy: 0.6567 - val_loss: 0.7787
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.7807 - val_accuracy: 0.4291 - val_loss: 1.2663
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.8037 - val_accuracy: 0.7164 - val_loss: 0.6194
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.8199 - val_accuracy: 0.6940 - val_loss: 0.5770
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.7752 - val_accuracy: 0.6828 - val_loss: 0.5827
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.7684 - val_accuracy: 0.6978 - val_loss: 0.5690
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.7977 - val_accuracy: 0.6978 - val_loss: 0.6195
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.7405 - val_accuracy: 0.6866 - val_loss: 0.5937
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.7466 - val_accuracy: 0.6269 - val_loss: 1.3065
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.7394 - val_accuracy: 0.7127 - val_loss: 0.6210
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.7130 - val_accuracy: 0.6716 - val_loss: 0.7051
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.7120 - val_accuracy: 0.6940 - val_loss: 0.6380
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.7031 - val_accuracy: 0.4366 - val_loss: 0.8853
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.7453 - val_accuracy: 0.4403 - val_loss: 0.8554
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.7169 - val_accuracy: 0.6530 - val_loss: 0.8567
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6953 - val_accuracy: 0.6231 - val_loss: 1.0457
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6021 - val_accuracy: 0.4254 - val_loss: 2.2492
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.7593 - val_accuracy: 0.7127 - val_loss: 0.6118
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6715 - val_accuracy: 0.7313 - val_loss: 0.6176
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.7202 - val_accuracy: 0.4813 - val_loss: 0.8149
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6361 - val_accuracy: 0.6530 - val_loss: 0.9274
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6685 - val_accuracy: 0.7388 - val_loss: 0.5471
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6599 - val_accuracy: 0.4478 - val_loss: 1.2450
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.7412 - val_accuracy: 0.6866 - val_loss: 0.5983
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.6347 - val_accuracy: 0.6903 - val_loss: 0.5696
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6735 - val_accuracy: 0.7276 - val_loss: 0.5953
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.7294 - val_accuracy: 0.7537 - val_loss: 0.5568
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5743 - val_accuracy: 0.6306 - val_loss: 1.1555
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6884 - val_accuracy: 0.6903 - val_loss: 0.5875
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6262 - val_accuracy: 0.7164 - val_loss: 0.5448
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6296 - val_accuracy: 0.7351 - val_loss: 0.6066
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6840 - val_accuracy: 0.5970 - val_loss: 0.7105
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6786 - val_accuracy: 0.6978 - val_loss: 0.5902
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6123 - val_accuracy: 0.7537 - val_loss: 0.6022
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5979 - val_accuracy: 0.7351 - val_loss: 0.5538
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.6843 - val_accuracy: 0.6866 - val_loss: 0.6185
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6032 - val_accuracy: 0.7425 - val_loss: 0.5465
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6170 - val_accuracy: 0.7351 - val_loss: 0.5974
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.6457 - val_accuracy: 0.6791 - val_loss: 0.7173
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.6328 - val_accuracy: 0.7537 - val_loss: 0.5913
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6206 - val_accuracy: 0.6306 - val_loss: 1.0652
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6551 - val_accuracy: 0.7537 - val_loss: 0.5829
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6515 - val_accuracy: 0.7425 - val_loss: 0.5957
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5813 - val_accuracy: 0.7239 - val_loss: 0.5517
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5548 - val_accuracy: 0.6306 - val_loss: 1.0597
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6222 - val_accuracy: 0.6716 - val_loss: 0.7475
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.6532 - val_accuracy: 0.7612 - val_loss: 0.5834
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6623 - val_accuracy: 0.6716 - val_loss: 0.7701
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6214 - val_accuracy: 0.7799 - val_loss: 0.5308
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5952 - val_accuracy: 0.6679 - val_loss: 0.7009
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6149 - val_accuracy: 0.4813 - val_loss: 0.9774
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.6322 - val_accuracy: 0.6418 - val_loss: 0.9785
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6457 - val_accuracy: 0.7799 - val_loss: 0.5538
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5823 - val_accuracy: 0.6642 - val_loss: 0.7750
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6217 - val_accuracy: 0.5075 - val_loss: 0.8587
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6320 - val_accuracy: 0.7687 - val_loss: 0.5536
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6420 - val_accuracy: 0.7500 - val_loss: 0.6123
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6484 - val_accuracy: 0.7090 - val_loss: 0.5607
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5856 - val_accuracy: 0.7313 - val_loss: 0.5430
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6112 - val_accuracy: 0.7201 - val_loss: 0.6124
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5986 - val_accuracy: 0.6231 - val_loss: 0.6972
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6222 - val_accuracy: 0.7313 - val_loss: 0.5478
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6613 - val_accuracy: 0.6791 - val_loss: 0.6499
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5895 - val_accuracy: 0.7425 - val_loss: 0.5329
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.6206 - val_accuracy: 0.7388 - val_loss: 0.5381
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5636 - val_accuracy: 0.4552 - val_loss: 1.6090
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6636 - val_accuracy: 0.7351 - val_loss: 0.5387
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5211 - val_accuracy: 0.6791 - val_loss: 0.9243
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6012 - val_accuracy: 0.7500 - val_loss: 0.5186
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6336 - val_accuracy: 0.7351 - val_loss: 0.5219
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5729 - val_accuracy: 0.7425 - val_loss: 0.5308
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5921 - val_accuracy: 0.7463 - val_loss: 0.5291
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6057 - val_accuracy: 0.6604 - val_loss: 0.9222
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5569 - val_accuracy: 0.6754 - val_loss: 0.8968
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5469 - val_accuracy: 0.6119 - val_loss: 0.6973
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6056 - val_accuracy: 0.6231 - val_loss: 0.7178
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6092 - val_accuracy: 0.6866 - val_loss: 0.6993
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5695 - val_accuracy: 0.6642 - val_loss: 0.8736
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5739 - val_accuracy: 0.7761 - val_loss: 0.4982
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5997 - val_accuracy: 0.7724 - val_loss: 0.5007
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5882 - val_accuracy: 0.7799 - val_loss: 0.5163
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5829 - val_accuracy: 0.7649 - val_loss: 0.5029
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6120 - val_accuracy: 0.7425 - val_loss: 0.5566
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5560 - val_accuracy: 0.7612 - val_loss: 0.5008
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6072 - val_accuracy: 0.7313 - val_loss: 0.5778
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6491 - val_accuracy: 0.7239 - val_loss: 0.5536
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5114 - val_accuracy: 0.6940 - val_loss: 0.7457
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.6065 - val_accuracy: 0.5560 - val_loss: 0.8852
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6286 - val_accuracy: 0.7761 - val_loss: 0.5964
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5267 - val_accuracy: 0.7537 - val_loss: 0.5125
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5702 - val_accuracy: 0.7687 - val_loss: 0.5891
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6583 - val_accuracy: 0.6866 - val_loss: 0.7957
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5890 - val_accuracy: 0.6791 - val_loss: 0.8665
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6010 - val_accuracy: 0.6791 - val_loss: 0.9376
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5797 - val_accuracy: 0.7799 - val_loss: 0.5366
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5638 - val_accuracy: 0.7276 - val_loss: 0.5959
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6055 - val_accuracy: 0.7015 - val_loss: 0.6799
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5426 - val_accuracy: 0.7575 - val_loss: 0.4911
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5755 - val_accuracy: 0.4925 - val_loss: 1.1151
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6483 - val_accuracy: 0.7090 - val_loss: 0.6189
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4968 - val_accuracy: 0.7052 - val_loss: 0.6513
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5712 - val_accuracy: 0.7164 - val_loss: 0.6007
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5560 - val_accuracy: 0.7761 - val_loss: 0.5132
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5143 - val_accuracy: 0.7463 - val_loss: 0.5104
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6121 - val_accuracy: 0.6791 - val_loss: 0.9253
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5424 - val_accuracy: 0.7724 - val_loss: 0.5052
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5994 - val_accuracy: 0.5746 - val_loss: 0.7782
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5560 - val_accuracy: 0.7276 - val_loss: 0.6085
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5809 - val_accuracy: 0.7687 - val_loss: 0.4914
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5587 - val_accuracy: 0.7425 - val_loss: 0.5379
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5602 - val_accuracy: 0.7649 - val_loss: 0.5192
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5202 - val_accuracy: 0.4813 - val_loss: 1.2278
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6346 - val_accuracy: 0.6530 - val_loss: 1.1413
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5438 - val_accuracy: 0.7239 - val_loss: 0.5700
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5721 - val_accuracy: 0.7761 - val_loss: 0.5183
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5893 - val_accuracy: 0.7276 - val_loss: 0.6110
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5052 - val_accuracy: 0.7090 - val_loss: 0.7292
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5724 - val_accuracy: 0.7687 - val_loss: 0.4916
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5606 - val_accuracy: 0.7649 - val_loss: 0.5088
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5402 - val_accuracy: 0.7500 - val_loss: 0.5271
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5502 - val_accuracy: 0.7649 - val_loss: 0.5467
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4919 - val_accuracy: 0.6866 - val_loss: 0.8956
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5527 - val_accuracy: 0.7799 - val_loss: 0.5578
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5810 - val_accuracy: 0.7537 - val_loss: 0.5249
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5685 - val_accuracy: 0.7090 - val_loss: 0.6630
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5605 - val_accuracy: 0.7687 - val_loss: 0.5913
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5632 - val_accuracy: 0.7687 - val_loss: 0.5101
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5660 - val_accuracy: 0.7164 - val_loss: 0.6657
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5818 - val_accuracy: 0.7313 - val_loss: 0.6498
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4989 - val_accuracy: 0.6716 - val_loss: 1.1134
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5878 - val_accuracy: 0.5149 - val_loss: 0.9955
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5693 - val_accuracy: 0.7425 - val_loss: 0.5422
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5756 - val_accuracy: 0.7463 - val_loss: 0.5244
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5096 - val_accuracy: 0.7276 - val_loss: 0.6237
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5385 - val_accuracy: 0.6194 - val_loss: 0.7565
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4964 - val_accuracy: 0.4776 - val_loss: 1.4856
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6051 - val_accuracy: 0.7575 - val_loss: 0.5276
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: stg736xr with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5233 - loss: 8.2716 - val_accuracy: 0.6679 - val_loss: 3.7905
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 2.8654 - val_accuracy: 0.6903 - val_loss: 1.5007
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 2.2185 - val_accuracy: 0.6940 - val_loss: 1.2818
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 1.8840 - val_accuracy: 0.6791 - val_loss: 1.0915
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 1.5500 - val_accuracy: 0.6940 - val_loss: 0.8748
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 1.2408 - val_accuracy: 0.7090 - val_loss: 0.8719
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 1.0554 - val_accuracy: 0.7127 - val_loss: 0.7103
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.8023 - val_accuracy: 0.6978 - val_loss: 0.6019
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.7075 - val_accuracy: 0.7351 - val_loss: 0.6002
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.6969 - val_accuracy: 0.6194 - val_loss: 0.6850
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6958 - val_accuracy: 0.6530 - val_loss: 0.8514
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7136 - val_accuracy: 0.6493 - val_loss: 1.0212
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6782 - val_accuracy: 0.7052 - val_loss: 0.6659
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6897 - val_accuracy: 0.6343 - val_loss: 1.0589
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7052 - val_accuracy: 0.7388 - val_loss: 0.5129
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5455 - val_accuracy: 0.7239 - val_loss: 0.5191
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5536 - val_accuracy: 0.7090 - val_loss: 0.5817
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5381 - val_accuracy: 0.7425 - val_loss: 0.5075
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5179 - val_accuracy: 0.7761 - val_loss: 0.5235
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5401 - val_accuracy: 0.7127 - val_loss: 0.5288
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5236 - val_accuracy: 0.7239 - val_loss: 0.5449
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5365 - val_accuracy: 0.7724 - val_loss: 0.5443
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5204 - val_accuracy: 0.7463 - val_loss: 0.4956
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5046 - val_accuracy: 0.7388 - val_loss: 0.4941
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5189 - val_accuracy: 0.7239 - val_loss: 0.5823
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5345 - val_accuracy: 0.7910 - val_loss: 0.4941
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5264 - val_accuracy: 0.7873 - val_loss: 0.5117
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5039 - val_accuracy: 0.7799 - val_loss: 0.4935
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5225 - val_accuracy: 0.7015 - val_loss: 0.5776
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.6394 - val_accuracy: 0.7799 - val_loss: 0.4796
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6091 - val_accuracy: 0.7948 - val_loss: 0.5185
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5175 - val_accuracy: 0.7463 - val_loss: 0.5731
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4983 - val_accuracy: 0.7537 - val_loss: 0.4990
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4759 - val_accuracy: 0.7537 - val_loss: 0.4918
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4852 - val_accuracy: 0.7910 - val_loss: 0.5128
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4927 - val_accuracy: 0.7612 - val_loss: 0.4843
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5757 - val_accuracy: 0.7500 - val_loss: 0.5090
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5416 - val_accuracy: 0.7799 - val_loss: 0.5334
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5019 - val_accuracy: 0.7687 - val_loss: 0.4782
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4832 - val_accuracy: 0.7836 - val_loss: 0.4968
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5132 - val_accuracy: 0.7649 - val_loss: 0.4960
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4983 - val_accuracy: 0.7724 - val_loss: 0.5427
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4666 - val_accuracy: 0.7761 - val_loss: 0.4790
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4798 - val_accuracy: 0.7687 - val_loss: 0.4779
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5814 - val_accuracy: 0.7425 - val_loss: 0.5731
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5153 - val_accuracy: 0.7537 - val_loss: 0.4750
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4835 - val_accuracy: 0.7687 - val_loss: 0.4772
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5122 - val_accuracy: 0.7575 - val_loss: 0.4819
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4915 - val_accuracy: 0.7799 - val_loss: 0.5116
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4830 - val_accuracy: 0.7127 - val_loss: 0.5947
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4697 - val_accuracy: 0.7836 - val_loss: 0.4832
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4880 - val_accuracy: 0.7575 - val_loss: 0.4998
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4758 - val_accuracy: 0.7649 - val_loss: 0.4765
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4858 - val_accuracy: 0.7836 - val_loss: 0.5283
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4605 - val_accuracy: 0.7687 - val_loss: 0.4787
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4752 - val_accuracy: 0.7649 - val_loss: 0.5611
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4744 - val_accuracy: 0.7649 - val_loss: 0.4850
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5013 - val_accuracy: 0.7761 - val_loss: 0.4761
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4834 - val_accuracy: 0.7687 - val_loss: 0.4749
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4456 - val_accuracy: 0.7687 - val_loss: 0.4812
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4683 - val_accuracy: 0.7425 - val_loss: 0.5745
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4601 - val_accuracy: 0.7761 - val_loss: 0.4765
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4830 - val_accuracy: 0.7724 - val_loss: 0.4896
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5367 - val_accuracy: 0.5448 - val_loss: 0.9038
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.7078 - val_accuracy: 0.7425 - val_loss: 0.5632
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5242 - val_accuracy: 0.7164 - val_loss: 0.6343
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4763 - val_accuracy: 0.7500 - val_loss: 0.5019
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4758 - val_accuracy: 0.7052 - val_loss: 0.6716
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.6452 - val_accuracy: 0.7612 - val_loss: 0.4730
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5038 - val_accuracy: 0.7649 - val_loss: 0.4777
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4669 - val_accuracy: 0.7575 - val_loss: 0.4874
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5551 - val_accuracy: 0.7575 - val_loss: 0.4744
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4462 - val_accuracy: 0.7313 - val_loss: 0.5774
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4648 - val_accuracy: 0.7836 - val_loss: 0.4886
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5288 - val_accuracy: 0.6866 - val_loss: 0.7268
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5848 - val_accuracy: 0.7836 - val_loss: 0.4787
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4764 - val_accuracy: 0.7724 - val_loss: 0.4900
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4762 - val_accuracy: 0.6679 - val_loss: 0.8202
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5621 - val_accuracy: 0.7164 - val_loss: 0.6632
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5137 - val_accuracy: 0.6754 - val_loss: 0.6682
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4837 - val_accuracy: 0.7388 - val_loss: 0.5530
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5424 - val_accuracy: 0.7761 - val_loss: 0.5013
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5474 - val_accuracy: 0.7799 - val_loss: 0.4910
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4843 - val_accuracy: 0.7388 - val_loss: 0.5726
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4681 - val_accuracy: 0.7649 - val_loss: 0.4922
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4797 - val_accuracy: 0.7873 - val_loss: 0.4846
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4591 - val_accuracy: 0.7649 - val_loss: 0.4803
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4643 - val_accuracy: 0.7873 - val_loss: 0.4896
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4471 - val_accuracy: 0.7612 - val_loss: 0.4789
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4856 - val_accuracy: 0.7799 - val_loss: 0.4744
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4505 - val_accuracy: 0.7948 - val_loss: 0.4867
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4457 - val_accuracy: 0.7724 - val_loss: 0.4801
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4385 - val_accuracy: 0.7799 - val_loss: 0.4832
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4554 - val_accuracy: 0.7612 - val_loss: 0.5107
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4422 - val_accuracy: 0.7836 - val_loss: 0.5337
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4598 - val_accuracy: 0.7724 - val_loss: 0.4724
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4805 - val_accuracy: 0.7090 - val_loss: 0.6536
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4754 - val_accuracy: 0.7649 - val_loss: 0.5121
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4602 - val_accuracy: 0.7537 - val_loss: 0.5452
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4753 - val_accuracy: 0.7873 - val_loss: 0.4894
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4468 - val_accuracy: 0.7537 - val_loss: 0.5930
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4399 - val_accuracy: 0.7836 - val_loss: 0.5028
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4519 - val_accuracy: 0.7910 - val_loss: 0.5013
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4583 - val_accuracy: 0.7649 - val_loss: 0.4877
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4914 - val_accuracy: 0.7873 - val_loss: 0.5337
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4630 - val_accuracy: 0.7761 - val_loss: 0.4910
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4691 - val_accuracy: 0.7537 - val_loss: 0.5287
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5118 - val_accuracy: 0.7910 - val_loss: 0.4890
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4874 - val_accuracy: 0.7910 - val_loss: 0.5437
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4719 - val_accuracy: 0.7612 - val_loss: 0.5432
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5619 - val_accuracy: 0.7724 - val_loss: 0.5130
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4396 - val_accuracy: 0.7649 - val_loss: 0.4898
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4396 - val_accuracy: 0.7873 - val_loss: 0.5007
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4629 - val_accuracy: 0.7015 - val_loss: 0.6766
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.5063 - val_accuracy: 0.7687 - val_loss: 0.4802
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4990 - val_accuracy: 0.6119 - val_loss: 0.8050
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4892 - val_accuracy: 0.7687 - val_loss: 0.4972
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.5046 - val_accuracy: 0.7761 - val_loss: 0.4961
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4918 - val_accuracy: 0.7649 - val_loss: 0.5872
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5518 - val_accuracy: 0.7724 - val_loss: 0.5812
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4394 - val_accuracy: 0.7649 - val_loss: 0.5056
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4958 - val_accuracy: 0.7687 - val_loss: 0.5821
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5517 - val_accuracy: 0.7687 - val_loss: 0.4846
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4410 - val_accuracy: 0.7724 - val_loss: 0.4924
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4339 - val_accuracy: 0.7575 - val_loss: 0.5443
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4759 - val_accuracy: 0.7612 - val_loss: 0.5278
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.5000 - val_accuracy: 0.7799 - val_loss: 0.5735
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4971 - val_accuracy: 0.7612 - val_loss: 0.5577
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4849 - val_accuracy: 0.7649 - val_loss: 0.4893
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4892 - val_accuracy: 0.7575 - val_loss: 0.6117
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5330 - val_accuracy: 0.7015 - val_loss: 0.7072
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5427 - val_accuracy: 0.7612 - val_loss: 0.5757
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4891 - val_accuracy: 0.7873 - val_loss: 0.5213
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5616 - val_accuracy: 0.6940 - val_loss: 0.6743
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5830 - val_accuracy: 0.7687 - val_loss: 0.5108
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5717 - val_accuracy: 0.7649 - val_loss: 0.5184
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8234 - loss: 0.4391 - val_accuracy: 0.7687 - val_loss: 0.4929
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4623 - val_accuracy: 0.7687 - val_loss: 0.4967
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8154 - loss: 0.4649 - val_accuracy: 0.7612 - val_loss: 0.5075
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4355 - val_accuracy: 0.7724 - val_loss: 0.5199
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4343 - val_accuracy: 0.7873 - val_loss: 0.5307
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5532 - val_accuracy: 0.7724 - val_loss: 0.5067
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4414 - val_accuracy: 0.7799 - val_loss: 0.4967
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4637 - val_accuracy: 0.7910 - val_loss: 0.5147
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5517 - val_accuracy: 0.7388 - val_loss: 0.6075
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5470 - val_accuracy: 0.6007 - val_loss: 0.8285
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4854 - val_accuracy: 0.7761 - val_loss: 0.4927
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4516 - val_accuracy: 0.7836 - val_loss: 0.5558
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5460 - val_accuracy: 0.5560 - val_loss: 0.9252
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5816 - val_accuracy: 0.7836 - val_loss: 0.5222
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4402 - val_accuracy: 0.7761 - val_loss: 0.4936
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8218 - loss: 0.4357 - val_accuracy: 0.7724 - val_loss: 0.4972
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4582 - val_accuracy: 0.7910 - val_loss: 0.5215
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4399 - val_accuracy: 0.7687 - val_loss: 0.5446
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: whz998d5 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6083 - loss: 12.7898 - val_accuracy: 0.6306 - val_loss: 0.6786
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6862 - val_accuracy: 0.6343 - val_loss: 0.6833
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6794 - val_accuracy: 0.6306 - val_loss: 0.6824
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6797 - val_accuracy: 0.6306 - val_loss: 0.6811
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6790 - val_accuracy: 0.6343 - val_loss: 0.6757
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6783 - val_accuracy: 0.6306 - val_loss: 0.6773
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6784 - val_accuracy: 0.6306 - val_loss: 0.6748
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6776 - val_accuracy: 0.6306 - val_loss: 0.6775
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6756 - val_accuracy: 0.6306 - val_loss: 0.6759
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6762 - val_accuracy: 0.6343 - val_loss: 0.6740
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6745 - val_accuracy: 0.6306 - val_loss: 0.6771
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6745 - val_accuracy: 0.6306 - val_loss: 0.6755
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6747 - val_accuracy: 0.6306 - val_loss: 0.6769
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6739 - val_accuracy: 0.6306 - val_loss: 0.6751
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6743 - val_accuracy: 0.6343 - val_loss: 0.6729
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6741 - val_accuracy: 0.6343 - val_loss: 0.6730
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6750 - val_accuracy: 0.6306 - val_loss: 0.6766
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6732 - val_accuracy: 0.6306 - val_loss: 0.6749
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6748 - val_accuracy: 0.6306 - val_loss: 0.6733
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6721 - val_accuracy: 0.6306 - val_loss: 0.6733
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6721 - val_accuracy: 0.6306 - val_loss: 0.6722
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6718 - val_accuracy: 0.6306 - val_loss: 0.6710
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6716 - val_accuracy: 0.6306 - val_loss: 0.6709
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6722 - val_accuracy: 0.6269 - val_loss: 0.6736
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6715 - val_accuracy: 0.6269 - val_loss: 0.6724
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6717 - val_accuracy: 0.6343 - val_loss: 0.6711
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6706 - val_accuracy: 0.6343 - val_loss: 0.6699
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6714 - val_accuracy: 0.6343 - val_loss: 0.6694
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6707 - val_accuracy: 0.6343 - val_loss: 0.6687
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6710 - val_accuracy: 0.6306 - val_loss: 0.6723
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6697 - val_accuracy: 0.6269 - val_loss: 0.6712
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6707 - val_accuracy: 0.6269 - val_loss: 0.6705
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6709 - val_accuracy: 0.6306 - val_loss: 0.6702
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6697 - val_accuracy: 0.6306 - val_loss: 0.6694
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6696 - val_accuracy: 0.6306 - val_loss: 0.6693
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6698 - val_accuracy: 0.6306 - val_loss: 0.6692
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6696 - val_accuracy: 0.6269 - val_loss: 0.6714
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.6712
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6705 - val_accuracy: 0.6269 - val_loss: 0.6705
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6693 - val_accuracy: 0.6306 - val_loss: 0.6695
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6686 - val_accuracy: 0.6343 - val_loss: 0.6686
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6698 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6681
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6306 - val_loss: 0.6678
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6685 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6687 - val_accuracy: 0.6306 - val_loss: 0.6672
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6701
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6688 - val_accuracy: 0.6269 - val_loss: 0.6688
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6700
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6306 - val_loss: 0.6689
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6684 - val_accuracy: 0.6306 - val_loss: 0.6673
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6680 - val_accuracy: 0.6306 - val_loss: 0.6669
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6674
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6682 - val_accuracy: 0.6306 - val_loss: 0.6663
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6680 - val_accuracy: 0.6306 - val_loss: 0.6662
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6269 - val_loss: 0.6684
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6676 - val_accuracy: 0.6306 - val_loss: 0.6691
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6681 - val_accuracy: 0.6306 - val_loss: 0.6671
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6669
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6679 - val_accuracy: 0.6343 - val_loss: 0.6668
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6343 - val_loss: 0.6661
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6654
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6662
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6655
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6306 - val_loss: 0.6658
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6676
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6668
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6677 - val_accuracy: 0.6343 - val_loss: 0.6667
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6343 - val_loss: 0.6663
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6343 - val_loss: 0.6659
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6654
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6652
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6651
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6649
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6655
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6654
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6654
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6667
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6663
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6343 - val_loss: 0.6658
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6343 - val_loss: 0.6655
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6653
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6651
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6649
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6648
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6645
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.6652
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6649
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6648
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6647
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6646
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6645
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6642
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6636
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6655
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6649
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6343 - val_loss: 0.6645
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6645
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6644
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6634
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6343 - val_loss: 0.6629
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6629
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6631
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6694
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6694
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6694
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6655 - val_accuracy: 0.6306 - val_loss: 0.6693
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6692
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6690
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6687
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6651 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6682
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6685
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6684
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6683
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6306 - val_loss: 0.6686
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ke57pilx with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4719 - loss: 6.0252 - val_accuracy: 0.5149 - val_loss: 1.8750
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5682 - loss: 1.7095 - val_accuracy: 0.5149 - val_loss: 1.4297
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5762 - loss: 1.5209 - val_accuracy: 0.5149 - val_loss: 1.3080
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6035 - loss: 1.3438 - val_accuracy: 0.6978 - val_loss: 0.8803
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 1.1018 - val_accuracy: 0.6567 - val_loss: 1.4343
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.9368 - val_accuracy: 0.5112 - val_loss: 1.2492
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5891 - loss: 0.9721 - val_accuracy: 0.7090 - val_loss: 0.6275
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.8222 - val_accuracy: 0.6940 - val_loss: 0.6959
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 0.9470 - val_accuracy: 0.7276 - val_loss: 0.5925
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 0.9130 - val_accuracy: 0.7164 - val_loss: 0.5980
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.8182 - val_accuracy: 0.6866 - val_loss: 0.6752
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8166 - val_accuracy: 0.6903 - val_loss: 0.7204
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.8425 - val_accuracy: 0.6866 - val_loss: 0.6947
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.7848 - val_accuracy: 0.6940 - val_loss: 0.6325
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7576 - val_accuracy: 0.7090 - val_loss: 0.6072
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.8934 - val_accuracy: 0.7015 - val_loss: 0.6490
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.8624 - val_accuracy: 0.6306 - val_loss: 0.7386
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.7184 - val_accuracy: 0.6567 - val_loss: 0.9911
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7238 - val_accuracy: 0.4701 - val_loss: 1.0692
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7826 - val_accuracy: 0.6754 - val_loss: 0.6314
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.8215 - val_accuracy: 0.5709 - val_loss: 0.8359
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.6627 - val_accuracy: 0.4851 - val_loss: 1.1320
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7687 - val_accuracy: 0.7164 - val_loss: 0.6146
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.8735 - val_accuracy: 0.6343 - val_loss: 0.7364
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6218 - val_accuracy: 0.7201 - val_loss: 0.6084
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7337 - val_accuracy: 0.5560 - val_loss: 0.7955
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.7749 - val_accuracy: 0.7500 - val_loss: 0.5850
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.7049 - val_accuracy: 0.6754 - val_loss: 0.7448
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.7358 - val_accuracy: 0.7015 - val_loss: 0.5957
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.7811 - val_accuracy: 0.4851 - val_loss: 0.8970
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6694 - val_accuracy: 0.6493 - val_loss: 1.0317
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.6886 - val_accuracy: 0.6940 - val_loss: 0.6180
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8083 - val_accuracy: 0.6306 - val_loss: 1.4768
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7075 - val_accuracy: 0.5261 - val_loss: 0.9102
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6521 - val_accuracy: 0.6754 - val_loss: 0.6579
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7463 - val_accuracy: 0.6343 - val_loss: 0.6837
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.6668 - val_accuracy: 0.7388 - val_loss: 0.5405
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.7538 - val_accuracy: 0.4888 - val_loss: 1.0172
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.6740 - val_accuracy: 0.7090 - val_loss: 0.6068
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6545 - val_accuracy: 0.6381 - val_loss: 1.2731
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6269 - val_accuracy: 0.6828 - val_loss: 0.6492
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.7038 - val_accuracy: 0.7388 - val_loss: 0.5363
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5999 - val_accuracy: 0.5336 - val_loss: 0.8620
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6963 - val_accuracy: 0.7463 - val_loss: 0.6069
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.7440 - val_accuracy: 0.7612 - val_loss: 0.5045
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6513 - val_accuracy: 0.7612 - val_loss: 0.5049
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6074 - val_accuracy: 0.7575 - val_loss: 0.5039
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6498 - val_accuracy: 0.5075 - val_loss: 0.9586
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6871 - val_accuracy: 0.6940 - val_loss: 0.6457
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6536 - val_accuracy: 0.7313 - val_loss: 0.6143
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6902 - val_accuracy: 0.7724 - val_loss: 0.5222
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5474 - val_accuracy: 0.6679 - val_loss: 0.8697
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7126 - val_accuracy: 0.6604 - val_loss: 0.9399
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6055 - val_accuracy: 0.7836 - val_loss: 0.5620
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6519 - val_accuracy: 0.6493 - val_loss: 0.9672
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5985 - val_accuracy: 0.7799 - val_loss: 0.5424
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6600 - val_accuracy: 0.7052 - val_loss: 0.6490
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6442 - val_accuracy: 0.6940 - val_loss: 0.8669
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6017 - val_accuracy: 0.7463 - val_loss: 0.5223
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6573 - val_accuracy: 0.7015 - val_loss: 0.7898
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.6928 - val_accuracy: 0.7799 - val_loss: 0.5076
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6135 - val_accuracy: 0.7500 - val_loss: 0.5025
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6085 - val_accuracy: 0.7836 - val_loss: 0.5192
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6770 - val_accuracy: 0.7724 - val_loss: 0.5077
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5585 - val_accuracy: 0.7612 - val_loss: 0.5134
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6199 - val_accuracy: 0.6679 - val_loss: 1.0547
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5651 - val_accuracy: 0.6978 - val_loss: 0.6915
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5927 - val_accuracy: 0.7500 - val_loss: 0.5209
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6137 - val_accuracy: 0.7537 - val_loss: 0.5100
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6986 - val_accuracy: 0.7500 - val_loss: 0.5429
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5339 - val_accuracy: 0.6493 - val_loss: 1.2303
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6608 - val_accuracy: 0.7836 - val_loss: 0.5400
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5869 - val_accuracy: 0.7724 - val_loss: 0.5145
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6372 - val_accuracy: 0.6642 - val_loss: 1.0106
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5390 - val_accuracy: 0.7948 - val_loss: 0.5989
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6129 - val_accuracy: 0.4813 - val_loss: 1.3274
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5655 - val_accuracy: 0.7948 - val_loss: 0.5711
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6197 - val_accuracy: 0.7313 - val_loss: 0.5594
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5667 - val_accuracy: 0.7575 - val_loss: 0.5265
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6221 - val_accuracy: 0.7090 - val_loss: 0.7593
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5999 - val_accuracy: 0.6791 - val_loss: 0.8896
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5870 - val_accuracy: 0.7052 - val_loss: 0.7784
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5830 - val_accuracy: 0.7948 - val_loss: 0.5832
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6416 - val_accuracy: 0.6866 - val_loss: 0.8350
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5921 - val_accuracy: 0.7799 - val_loss: 0.6337
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6002 - val_accuracy: 0.6642 - val_loss: 0.7640
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5674 - val_accuracy: 0.5149 - val_loss: 1.0177
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5999 - val_accuracy: 0.7649 - val_loss: 0.5349
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5971 - val_accuracy: 0.7090 - val_loss: 0.7145
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5380 - val_accuracy: 0.4590 - val_loss: 1.5066
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5825 - val_accuracy: 0.7649 - val_loss: 0.5157
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5691 - val_accuracy: 0.7425 - val_loss: 0.6898
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6077 - val_accuracy: 0.7500 - val_loss: 0.5585
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5215 - val_accuracy: 0.6791 - val_loss: 0.9058
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5920 - val_accuracy: 0.6343 - val_loss: 1.4061
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5824 - val_accuracy: 0.6642 - val_loss: 1.0192
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6006 - val_accuracy: 0.7649 - val_loss: 0.5302
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5840 - val_accuracy: 0.7463 - val_loss: 0.5711
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.5528 - val_accuracy: 0.6567 - val_loss: 0.8734
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6159 - val_accuracy: 0.7687 - val_loss: 0.5199
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5073 - val_accuracy: 0.5672 - val_loss: 1.0139
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.6512 - val_accuracy: 0.7201 - val_loss: 0.7068
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5261 - val_accuracy: 0.7500 - val_loss: 0.5834
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5798 - val_accuracy: 0.7500 - val_loss: 0.5787
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6029 - val_accuracy: 0.4627 - val_loss: 1.5997
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5881 - val_accuracy: 0.5672 - val_loss: 0.9783
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5881 - val_accuracy: 0.6530 - val_loss: 1.2192
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6004 - val_accuracy: 0.7276 - val_loss: 0.6532
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5325 - val_accuracy: 0.7724 - val_loss: 0.6563
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5717 - val_accuracy: 0.6567 - val_loss: 1.0623
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5451 - val_accuracy: 0.7687 - val_loss: 0.5585
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5486 - val_accuracy: 0.6978 - val_loss: 0.8975
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5383 - val_accuracy: 0.7836 - val_loss: 0.5369
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5946 - val_accuracy: 0.7052 - val_loss: 0.7958
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5623 - val_accuracy: 0.7164 - val_loss: 0.7022
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5479 - val_accuracy: 0.7724 - val_loss: 0.5350
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5610 - val_accuracy: 0.7836 - val_loss: 0.5792
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5540 - val_accuracy: 0.7724 - val_loss: 0.5337
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5528 - val_accuracy: 0.7090 - val_loss: 0.7330
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5212 - val_accuracy: 0.7649 - val_loss: 0.5277
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5823 - val_accuracy: 0.7761 - val_loss: 0.6416
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5076 - val_accuracy: 0.7388 - val_loss: 0.6909
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5936 - val_accuracy: 0.7388 - val_loss: 0.5925
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5248 - val_accuracy: 0.7761 - val_loss: 0.5289
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.5045 - val_accuracy: 0.6828 - val_loss: 0.8680
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5598 - val_accuracy: 0.7873 - val_loss: 0.5329
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5252 - val_accuracy: 0.7836 - val_loss: 0.5497
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5654 - val_accuracy: 0.7649 - val_loss: 0.6673
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5046 - val_accuracy: 0.7836 - val_loss: 0.5908
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5552 - val_accuracy: 0.7836 - val_loss: 0.5783
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5029 - val_accuracy: 0.7910 - val_loss: 0.5947
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4767 - val_accuracy: 0.7948 - val_loss: 0.5698
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5173 - val_accuracy: 0.6940 - val_loss: 0.7811
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5071 - val_accuracy: 0.7761 - val_loss: 0.6336
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5504 - val_accuracy: 0.7948 - val_loss: 0.5643
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5057 - val_accuracy: 0.7351 - val_loss: 0.6919
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.5201 - val_accuracy: 0.7575 - val_loss: 0.5761
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4943 - val_accuracy: 0.6604 - val_loss: 1.1654
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.5254 - val_accuracy: 0.7015 - val_loss: 0.7119
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4824 - val_accuracy: 0.7761 - val_loss: 0.5394
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5009 - val_accuracy: 0.6866 - val_loss: 0.9798
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5177 - val_accuracy: 0.7649 - val_loss: 0.5492
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4936 - val_accuracy: 0.7425 - val_loss: 0.6087
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5145 - val_accuracy: 0.7425 - val_loss: 0.6585
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5074 - val_accuracy: 0.7500 - val_loss: 0.6335
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5126 - val_accuracy: 0.7687 - val_loss: 0.5628
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5589 - val_accuracy: 0.7836 - val_loss: 0.5478
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5352 - val_accuracy: 0.7351 - val_loss: 0.7253
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5177 - val_accuracy: 0.7351 - val_loss: 0.6999
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.5196 - val_accuracy: 0.7799 - val_loss: 0.6829
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.5006 - val_accuracy: 0.7687 - val_loss: 0.5650
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4655 - val_accuracy: 0.7351 - val_loss: 0.6682
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5802 - val_accuracy: 0.7910 - val_loss: 0.5742
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4697 - val_accuracy: 0.7873 - val_loss: 0.6019
Epoch 155/5000

wandb: Agent Starting Run: lsxjbjf5 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4575 - loss: 14.6309 - val_accuracy: 0.6567 - val_loss: 4.4738
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5746 - loss: 3.8372 - val_accuracy: 0.4142 - val_loss: 1.5629
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 1.2618 - val_accuracy: 0.7015 - val_loss: 0.7664
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.8836 - val_accuracy: 0.7164 - val_loss: 0.6816
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6852 - val_accuracy: 0.6866 - val_loss: 0.7334
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.7455 - val_accuracy: 0.7015 - val_loss: 0.6659
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6800 - val_accuracy: 0.7164 - val_loss: 0.6657
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6143 - val_accuracy: 0.6978 - val_loss: 0.6620
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6405 - val_accuracy: 0.6978 - val_loss: 0.6420
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6288 - val_accuracy: 0.6940 - val_loss: 0.6473
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6189 - val_accuracy: 0.7090 - val_loss: 0.6318
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5832 - val_accuracy: 0.6866 - val_loss: 0.6665
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6236 - val_accuracy: 0.6679 - val_loss: 0.6903
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.6579 - val_accuracy: 0.6530 - val_loss: 0.7912
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.7498 - val_accuracy: 0.7276 - val_loss: 0.6129
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.6114 - val_accuracy: 0.7201 - val_loss: 0.6096
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5763 - val_accuracy: 0.7201 - val_loss: 0.5923
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5639 - val_accuracy: 0.7127 - val_loss: 0.5940
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5641 - val_accuracy: 0.6978 - val_loss: 0.6056
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5589 - val_accuracy: 0.7313 - val_loss: 0.5878
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5599 - val_accuracy: 0.7351 - val_loss: 0.6106
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5927 - val_accuracy: 0.7164 - val_loss: 0.5722
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5319 - val_accuracy: 0.7201 - val_loss: 0.5645
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5356 - val_accuracy: 0.7463 - val_loss: 0.5812
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5406 - val_accuracy: 0.6866 - val_loss: 0.5911
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5512 - val_accuracy: 0.6716 - val_loss: 0.6172
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5305 - val_accuracy: 0.7164 - val_loss: 0.5585
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5470 - val_accuracy: 0.7127 - val_loss: 0.5665
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6377 - val_accuracy: 0.6455 - val_loss: 0.7637
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5587 - val_accuracy: 0.7164 - val_loss: 0.5529
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5306 - val_accuracy: 0.7090 - val_loss: 0.5685
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5321 - val_accuracy: 0.7388 - val_loss: 0.5953
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5412 - val_accuracy: 0.7164 - val_loss: 0.5518
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5326 - val_accuracy: 0.7351 - val_loss: 0.6132
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5263 - val_accuracy: 0.7239 - val_loss: 0.5509
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5094 - val_accuracy: 0.7388 - val_loss: 0.5449
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4951 - val_accuracy: 0.7500 - val_loss: 0.5580
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4940 - val_accuracy: 0.6903 - val_loss: 0.5694
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4980 - val_accuracy: 0.7463 - val_loss: 0.5488
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5318 - val_accuracy: 0.7649 - val_loss: 0.5412
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5205 - val_accuracy: 0.7575 - val_loss: 0.6024
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4918 - val_accuracy: 0.6866 - val_loss: 0.5934
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5055 - val_accuracy: 0.7276 - val_loss: 0.5339
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4796 - val_accuracy: 0.7687 - val_loss: 0.5714
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4810 - val_accuracy: 0.7463 - val_loss: 0.6045
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5537 - val_accuracy: 0.7276 - val_loss: 0.5251
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5146 - val_accuracy: 0.7276 - val_loss: 0.5282
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5041 - val_accuracy: 0.7425 - val_loss: 0.5289
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4757 - val_accuracy: 0.7500 - val_loss: 0.5384
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4774 - val_accuracy: 0.7537 - val_loss: 0.5344
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4884 - val_accuracy: 0.7649 - val_loss: 0.5593
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5366 - val_accuracy: 0.7052 - val_loss: 0.5732
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5023 - val_accuracy: 0.7425 - val_loss: 0.5278
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4627 - val_accuracy: 0.7500 - val_loss: 0.5148
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4759 - val_accuracy: 0.7575 - val_loss: 0.5697
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5641 - val_accuracy: 0.7799 - val_loss: 0.5606
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4925 - val_accuracy: 0.7090 - val_loss: 0.5991
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4747 - val_accuracy: 0.7463 - val_loss: 0.5189
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4640 - val_accuracy: 0.7164 - val_loss: 0.6153
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4915 - val_accuracy: 0.7612 - val_loss: 0.5282
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4725 - val_accuracy: 0.7575 - val_loss: 0.5381
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4671 - val_accuracy: 0.7463 - val_loss: 0.5176
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4901 - val_accuracy: 0.7388 - val_loss: 0.5336
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4558 - val_accuracy: 0.7425 - val_loss: 0.5321
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5604 - val_accuracy: 0.6978 - val_loss: 0.6428
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5136 - val_accuracy: 0.7649 - val_loss: 0.5381
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4618 - val_accuracy: 0.7463 - val_loss: 0.5116
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4892 - val_accuracy: 0.7201 - val_loss: 0.5978
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4801 - val_accuracy: 0.7724 - val_loss: 0.5623
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4838 - val_accuracy: 0.7537 - val_loss: 0.5108
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4713 - val_accuracy: 0.7276 - val_loss: 0.5426
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4655 - val_accuracy: 0.7537 - val_loss: 0.5056
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5020 - val_accuracy: 0.7388 - val_loss: 0.5247
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4806 - val_accuracy: 0.7127 - val_loss: 0.5832
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4711 - val_accuracy: 0.7500 - val_loss: 0.5091
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4887 - val_accuracy: 0.7388 - val_loss: 0.5136
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4605 - val_accuracy: 0.7239 - val_loss: 0.5363
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4588 - val_accuracy: 0.7687 - val_loss: 0.5502
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5497 - val_accuracy: 0.5336 - val_loss: 0.9007
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5468 - val_accuracy: 0.7649 - val_loss: 0.5090
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5041 - val_accuracy: 0.7500 - val_loss: 0.5061
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4859 - val_accuracy: 0.7612 - val_loss: 0.5202
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4718 - val_accuracy: 0.7537 - val_loss: 0.5286
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4587 - val_accuracy: 0.7351 - val_loss: 0.5289
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4981 - val_accuracy: 0.7537 - val_loss: 0.5024
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5486 - val_accuracy: 0.7575 - val_loss: 0.5105
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4862 - val_accuracy: 0.7201 - val_loss: 0.6431
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4994 - val_accuracy: 0.7649 - val_loss: 0.5317
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6731 - val_accuracy: 0.7313 - val_loss: 0.5859
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5697 - val_accuracy: 0.7276 - val_loss: 0.5255
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5087 - val_accuracy: 0.7649 - val_loss: 0.5133
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4946 - val_accuracy: 0.7649 - val_loss: 0.5480
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4701 - val_accuracy: 0.6866 - val_loss: 0.6655
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5549 - val_accuracy: 0.5485 - val_loss: 0.8785
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.6404 - val_accuracy: 0.7761 - val_loss: 0.5704
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5737 - val_accuracy: 0.7575 - val_loss: 0.4982
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4524 - val_accuracy: 0.7724 - val_loss: 0.5580
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4569 - val_accuracy: 0.7463 - val_loss: 0.5105
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4539 - val_accuracy: 0.7239 - val_loss: 0.6374
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4641 - val_accuracy: 0.7537 - val_loss: 0.5176
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4577 - val_accuracy: 0.7575 - val_loss: 0.5010
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4721 - val_accuracy: 0.7239 - val_loss: 0.5627
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4592 - val_accuracy: 0.7425 - val_loss: 0.5280
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4513 - val_accuracy: 0.7724 - val_loss: 0.5412
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5231 - val_accuracy: 0.7724 - val_loss: 0.5489
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5139 - val_accuracy: 0.7649 - val_loss: 0.5905
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4756 - val_accuracy: 0.7687 - val_loss: 0.5438
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4545 - val_accuracy: 0.7612 - val_loss: 0.5183
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4576 - val_accuracy: 0.7201 - val_loss: 0.6355
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4693 - val_accuracy: 0.7537 - val_loss: 0.5291
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4950 - val_accuracy: 0.7127 - val_loss: 0.6054
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5414 - val_accuracy: 0.7500 - val_loss: 0.5203
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4793 - val_accuracy: 0.7127 - val_loss: 0.6057
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5221 - val_accuracy: 0.7649 - val_loss: 0.5079
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4646 - val_accuracy: 0.7649 - val_loss: 0.5983
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4915 - val_accuracy: 0.7463 - val_loss: 0.6218
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5447 - val_accuracy: 0.7164 - val_loss: 0.6519
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.5010 - val_accuracy: 0.5970 - val_loss: 0.8179
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5186 - val_accuracy: 0.7761 - val_loss: 0.5417
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4724 - val_accuracy: 0.7575 - val_loss: 0.4959
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5312 - val_accuracy: 0.7164 - val_loss: 0.6042
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4510 - val_accuracy: 0.7687 - val_loss: 0.5305
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4388 - val_accuracy: 0.7575 - val_loss: 0.5255
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4428 - val_accuracy: 0.7537 - val_loss: 0.5171
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4372 - val_accuracy: 0.7575 - val_loss: 0.5278
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4414 - val_accuracy: 0.7761 - val_loss: 0.5217
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4538 - val_accuracy: 0.7612 - val_loss: 0.5191
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4545 - val_accuracy: 0.7687 - val_loss: 0.5225
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4493 - val_accuracy: 0.6269 - val_loss: 0.7426
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5011 - val_accuracy: 0.7687 - val_loss: 0.5095
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4576 - val_accuracy: 0.7575 - val_loss: 0.5074
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4542 - val_accuracy: 0.7500 - val_loss: 0.5352
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4208 - val_accuracy: 0.7500 - val_loss: 0.5130
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4569 - val_accuracy: 0.7649 - val_loss: 0.5091
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4681 - val_accuracy: 0.7463 - val_loss: 0.5371
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4372 - val_accuracy: 0.7425 - val_loss: 0.5479
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4825 - val_accuracy: 0.7575 - val_loss: 0.5360
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4911 - val_accuracy: 0.7463 - val_loss: 0.5254
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5093 - val_accuracy: 0.7500 - val_loss: 0.5447
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4765 - val_accuracy: 0.7761 - val_loss: 0.5300
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4724 - val_accuracy: 0.7649 - val_loss: 0.5356
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4498 - val_accuracy: 0.7463 - val_loss: 0.5526
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4361 - val_accuracy: 0.7537 - val_loss: 0.5244
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4409 - val_accuracy: 0.7500 - val_loss: 0.5166
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4437 - val_accuracy: 0.7575 - val_loss: 0.5309
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4543 - val_accuracy: 0.7575 - val_loss: 0.5181
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4766 - val_accuracy: 0.7649 - val_loss: 0.5329
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4706 - val_accuracy: 0.6940 - val_loss: 0.6772
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4810 - val_accuracy: 0.7575 - val_loss: 0.5160
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4411 - val_accuracy: 0.7537 - val_loss: 0.5386
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4391 - val_accuracy: 0.7500 - val_loss: 0.5486
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5449 - val_accuracy: 0.7687 - val_loss: 0.5318
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5054 - val_accuracy: 0.7649 - val_loss: 0.5219
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4393 - val_accuracy: 0.7537 - val_loss: 0.5460
Epoch 155/5000

wandb: Agent Starting Run: nmgy7kro with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5859 - loss: 6.6971 - val_accuracy: 0.6269 - val_loss: 0.7162
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.7032 - val_accuracy: 0.6231 - val_loss: 0.7146
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6946 - val_accuracy: 0.6306 - val_loss: 0.7107
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6918 - val_accuracy: 0.6306 - val_loss: 0.7635
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6978 - val_accuracy: 0.6306 - val_loss: 0.7066
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6799 - val_accuracy: 0.6306 - val_loss: 0.6888
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6811 - val_accuracy: 0.6194 - val_loss: 0.6774
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6760 - val_accuracy: 0.6306 - val_loss: 0.6735
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6748 - val_accuracy: 0.6306 - val_loss: 0.6759
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6736 - val_accuracy: 0.6269 - val_loss: 0.6735
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6732 - val_accuracy: 0.6306 - val_loss: 0.6693
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6721 - val_accuracy: 0.6269 - val_loss: 0.6706
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6716 - val_accuracy: 0.6269 - val_loss: 0.6738
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6692 - val_accuracy: 0.6269 - val_loss: 0.7155
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6706 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6676 - val_accuracy: 0.6194 - val_loss: 0.6710
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6684 - val_accuracy: 0.6269 - val_loss: 0.6642
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6669 - val_accuracy: 0.6343 - val_loss: 0.6593
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.6748
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6381 - val_loss: 0.6687
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6343 - val_loss: 0.6592
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6343 - val_loss: 0.6582
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6343 - val_loss: 0.6631
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6679 - val_accuracy: 0.6343 - val_loss: 0.6626
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6601
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6381 - val_loss: 0.6665
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6654 - val_accuracy: 0.6306 - val_loss: 0.6612
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6667 - val_accuracy: 0.6269 - val_loss: 0.6612
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.7170
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6684 - val_accuracy: 0.6343 - val_loss: 0.6574
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6657 - val_accuracy: 0.6343 - val_loss: 0.6571
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6381 - val_loss: 0.6802
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6711 - val_accuracy: 0.6306 - val_loss: 0.6597
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6578
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6343 - val_loss: 0.6561
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6600
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6642 - val_accuracy: 0.6381 - val_loss: 0.6612
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6634 - val_accuracy: 0.6306 - val_loss: 0.6583
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6602
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6590
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6585
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6343 - val_loss: 0.6568
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6343 - val_loss: 0.6720
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6654 - val_accuracy: 0.6381 - val_loss: 0.6624
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.7077
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6695 - val_accuracy: 0.6306 - val_loss: 0.6577
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6343 - val_loss: 0.6584
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6635 - val_accuracy: 0.6343 - val_loss: 0.6567
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6343 - val_loss: 0.6574
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6343 - val_loss: 0.6732
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6343 - val_loss: 0.6554
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6631 - val_accuracy: 0.6381 - val_loss: 0.6726
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6681 - val_accuracy: 0.6343 - val_loss: 0.6601
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6231 - val_loss: 0.6554
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6633 - val_accuracy: 0.6269 - val_loss: 0.7283
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6711 - val_accuracy: 0.6306 - val_loss: 0.6588
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6343 - val_loss: 0.6575
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6613 - val_accuracy: 0.7015 - val_loss: 0.6364
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6626 - val_accuracy: 0.6343 - val_loss: 0.6568
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6578
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6637 - val_accuracy: 0.6343 - val_loss: 0.6606
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6635 - val_accuracy: 0.6343 - val_loss: 0.6566
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6581
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6381 - val_loss: 0.6594
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6343 - val_loss: 0.6554
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6381 - val_loss: 0.6624
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6343 - val_loss: 0.6583
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6613 - val_accuracy: 0.6306 - val_loss: 0.6598
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6673 - val_accuracy: 0.6269 - val_loss: 0.6562
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.6562
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6568
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6568
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6570
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6629 - val_accuracy: 0.6343 - val_loss: 0.6572
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6574
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6635 - val_accuracy: 0.6343 - val_loss: 0.6601
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6343 - val_loss: 0.6616
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6343 - val_loss: 0.6589
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6343 - val_loss: 0.6563
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6343 - val_loss: 0.6597
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6634 - val_accuracy: 0.6343 - val_loss: 0.6560
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6343 - val_loss: 0.6596
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6269 - val_loss: 0.6617
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.6538 - val_accuracy: 0.3806 - val_loss: 1.0609
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 0.6860 - val_accuracy: 0.6343 - val_loss: 0.6621
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6608
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6644 - val_accuracy: 0.6343 - val_loss: 0.6574
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.6605
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6635 - val_accuracy: 0.6306 - val_loss: 0.6663
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6306 - val_loss: 0.6556
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6231 - val_loss: 0.6566
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6644 - val_accuracy: 0.6343 - val_loss: 0.6563
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6605 - val_accuracy: 0.6269 - val_loss: 0.6628
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.6736 - val_accuracy: 0.6455 - val_loss: 0.6458
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6614 - val_accuracy: 0.6343 - val_loss: 0.6556
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6655 - val_accuracy: 0.6343 - val_loss: 0.6553
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6343 - val_loss: 0.6561
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.6572
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6343 - val_loss: 0.6555
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6630 - val_accuracy: 0.6381 - val_loss: 0.6616
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6381 - val_loss: 0.6560
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6343 - val_loss: 0.6618
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6572
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6663
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6577
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6632 - val_accuracy: 0.6381 - val_loss: 0.6620
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6343 - val_loss: 0.6563
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6634 - val_accuracy: 0.6381 - val_loss: 0.6601
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6577
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6585
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.6570
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.6586
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6573
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6343 - val_loss: 0.6577
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.6660
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6343 - val_loss: 0.6559
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6534
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 0.6953 - val_accuracy: 0.6306 - val_loss: 0.6687
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6603
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6602
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.6601
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6343 - val_loss: 0.6650
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6651 - val_accuracy: 0.6381 - val_loss: 0.6636
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6343 - val_loss: 0.6633
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6631
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6343 - val_loss: 0.6580
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.7067
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6650 - val_accuracy: 0.6343 - val_loss: 0.6600
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.6770
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6604
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6343 - val_loss: 0.6581
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6343 - val_loss: 0.6590
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6343 - val_loss: 0.6581
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7140
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6674 - val_accuracy: 0.6343 - val_loss: 0.6583
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.6973
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6681 - val_accuracy: 0.6343 - val_loss: 0.6602
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6343 - val_loss: 0.6829
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6269 - val_loss: 0.6588
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6606
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6343 - val_loss: 0.6606
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6675
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6596
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6343 - val_loss: 0.6582
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6612 - val_accuracy: 0.6343 - val_loss: 0.6750
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6653 - val_accuracy: 0.6642 - val_loss: 0.6429
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6610 - val_accuracy: 0.6455 - val_loss: 0.6459
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6381 - val_loss: 0.6536
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6583
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6530 - val_loss: 0.6489
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6626 - val_accuracy: 0.6642 - val_loss: 0.6362
Epoch 155/5000

wandb: Agent Starting Run: uako4cnx with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4944 - loss: 4.5226 - val_accuracy: 0.4851 - val_loss: 1.6520
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5714 - loss: 1.4090 - val_accuracy: 0.5485 - val_loss: 1.1436
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 1.3555 - val_accuracy: 0.5299 - val_loss: 1.3292
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5859 - loss: 1.4192 - val_accuracy: 0.5672 - val_loss: 1.0144
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 1.2513 - val_accuracy: 0.6343 - val_loss: 1.8690
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6035 - loss: 1.1250 - val_accuracy: 0.5149 - val_loss: 1.4047
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5843 - loss: 1.2680 - val_accuracy: 0.4813 - val_loss: 1.9033
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5714 - loss: 1.3120 - val_accuracy: 0.4739 - val_loss: 2.1739
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 1.2126 - val_accuracy: 0.4963 - val_loss: 1.5087
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5843 - loss: 1.1378 - val_accuracy: 0.6381 - val_loss: 1.4256
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5827 - loss: 1.1948 - val_accuracy: 0.6455 - val_loss: 1.2612
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5811 - loss: 1.1536 - val_accuracy: 0.6604 - val_loss: 0.7824
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 1.0540 - val_accuracy: 0.6343 - val_loss: 1.5474
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.9832 - val_accuracy: 0.5709 - val_loss: 0.8587
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 1.0752 - val_accuracy: 0.6903 - val_loss: 0.7107
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6035 - loss: 1.0671 - val_accuracy: 0.5821 - val_loss: 0.8162
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 1.0150 - val_accuracy: 0.7090 - val_loss: 0.6862
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 1.0667 - val_accuracy: 0.6343 - val_loss: 0.7674
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.9518 - val_accuracy: 0.6828 - val_loss: 0.6907
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5971 - loss: 1.0730 - val_accuracy: 0.6679 - val_loss: 0.8341
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 1.0114 - val_accuracy: 0.6940 - val_loss: 0.6674
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.9737 - val_accuracy: 0.6455 - val_loss: 0.7385
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 0.9715 - val_accuracy: 0.6493 - val_loss: 1.1524
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.9732 - val_accuracy: 0.6791 - val_loss: 0.6770
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 1.1158 - val_accuracy: 0.6343 - val_loss: 1.2630
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5875 - loss: 1.0518 - val_accuracy: 0.6493 - val_loss: 1.2445
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.9714 - val_accuracy: 0.6754 - val_loss: 0.7110
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.9461 - val_accuracy: 0.5858 - val_loss: 0.8286
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.9874 - val_accuracy: 0.6231 - val_loss: 1.5511
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.9435 - val_accuracy: 0.4664 - val_loss: 1.1634
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 1.1286 - val_accuracy: 0.5149 - val_loss: 0.9549
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.8825 - val_accuracy: 0.6530 - val_loss: 1.0161
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.9975 - val_accuracy: 0.6381 - val_loss: 1.3549
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6003 - loss: 1.0140 - val_accuracy: 0.6978 - val_loss: 0.6496
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 1.0164 - val_accuracy: 0.6903 - val_loss: 0.6337
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.8482 - val_accuracy: 0.6455 - val_loss: 1.1524
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5939 - loss: 1.0221 - val_accuracy: 0.6642 - val_loss: 0.9538
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.9026 - val_accuracy: 0.6940 - val_loss: 0.6115
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.9056 - val_accuracy: 0.6903 - val_loss: 0.6574
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.9455 - val_accuracy: 0.6940 - val_loss: 0.6619
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.9141 - val_accuracy: 0.6642 - val_loss: 0.9199
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.9107 - val_accuracy: 0.6903 - val_loss: 0.6577
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.8373 - val_accuracy: 0.5597 - val_loss: 0.8488
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 1.0129 - val_accuracy: 0.4776 - val_loss: 1.0328
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.8436 - val_accuracy: 0.3955 - val_loss: 2.8814
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 1.0682 - val_accuracy: 0.6754 - val_loss: 0.7985
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.8639 - val_accuracy: 0.7164 - val_loss: 0.6435
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 1.0441 - val_accuracy: 0.5000 - val_loss: 0.9810
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.9401 - val_accuracy: 0.6194 - val_loss: 1.6003
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.8654 - val_accuracy: 0.6269 - val_loss: 1.4605
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.8546 - val_accuracy: 0.5896 - val_loss: 0.7959
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.8755 - val_accuracy: 0.6493 - val_loss: 1.1834
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.9182 - val_accuracy: 0.6493 - val_loss: 1.0362
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.9388 - val_accuracy: 0.6716 - val_loss: 0.8296
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.8691 - val_accuracy: 0.6903 - val_loss: 0.7020
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.9178 - val_accuracy: 0.6679 - val_loss: 0.8636
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.9837 - val_accuracy: 0.7127 - val_loss: 0.5843
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.9568 - val_accuracy: 0.6493 - val_loss: 1.0659
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.8911 - val_accuracy: 0.7201 - val_loss: 0.5776
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.7797 - val_accuracy: 0.7313 - val_loss: 0.5878
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.9046 - val_accuracy: 0.7015 - val_loss: 0.6915
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 1.0650 - val_accuracy: 0.6343 - val_loss: 1.2311
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.8781 - val_accuracy: 0.6567 - val_loss: 0.7473
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7239 - val_accuracy: 0.4104 - val_loss: 2.1626
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.9973 - val_accuracy: 0.6679 - val_loss: 0.8738
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.8571 - val_accuracy: 0.7239 - val_loss: 0.5760
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.8167 - val_accuracy: 0.6455 - val_loss: 0.9570
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.9138 - val_accuracy: 0.6418 - val_loss: 0.7269
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.9372 - val_accuracy: 0.7201 - val_loss: 0.5556
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.7541 - val_accuracy: 0.5187 - val_loss: 0.9827
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.9386 - val_accuracy: 0.7351 - val_loss: 0.6382
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.9267 - val_accuracy: 0.4142 - val_loss: 1.9164
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.8905 - val_accuracy: 0.6194 - val_loss: 1.8768
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.8994 - val_accuracy: 0.7388 - val_loss: 0.6344
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7915 - val_accuracy: 0.4701 - val_loss: 1.2271
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.8736 - val_accuracy: 0.7239 - val_loss: 0.5550
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.7502 - val_accuracy: 0.5448 - val_loss: 0.9270
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.9519 - val_accuracy: 0.6493 - val_loss: 0.7884
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.8187 - val_accuracy: 0.7239 - val_loss: 0.6022
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.7043 - val_accuracy: 0.6269 - val_loss: 2.1279
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.8226 - val_accuracy: 0.7425 - val_loss: 0.6239
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.9029 - val_accuracy: 0.6716 - val_loss: 0.8302
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.9422 - val_accuracy: 0.5634 - val_loss: 0.8580
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7558 - val_accuracy: 0.6716 - val_loss: 0.9266
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.9327 - val_accuracy: 0.7500 - val_loss: 0.5616
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7304 - val_accuracy: 0.7276 - val_loss: 0.6409
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.8949 - val_accuracy: 0.6381 - val_loss: 1.0794
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.8255 - val_accuracy: 0.7239 - val_loss: 0.6676
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.7856 - val_accuracy: 0.7276 - val_loss: 0.5776
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.8552 - val_accuracy: 0.6866 - val_loss: 0.6828
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.8629 - val_accuracy: 0.6231 - val_loss: 1.3850
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.7487 - val_accuracy: 0.5000 - val_loss: 1.1000
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.8335 - val_accuracy: 0.7276 - val_loss: 0.6349
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.8924 - val_accuracy: 0.7612 - val_loss: 0.5664
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.8681 - val_accuracy: 0.6903 - val_loss: 0.8610
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.7762 - val_accuracy: 0.6194 - val_loss: 1.4442
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.8126 - val_accuracy: 0.6343 - val_loss: 1.1899
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.8021 - val_accuracy: 0.5000 - val_loss: 1.1598
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.9034 - val_accuracy: 0.7500 - val_loss: 0.5455
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6996 - val_accuracy: 0.7239 - val_loss: 0.5533
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.9049 - val_accuracy: 0.7388 - val_loss: 0.5264
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.8742 - val_accuracy: 0.7836 - val_loss: 0.5549
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.7420 - val_accuracy: 0.7537 - val_loss: 0.5676
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.8503 - val_accuracy: 0.7239 - val_loss: 0.6449
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.8331 - val_accuracy: 0.7500 - val_loss: 0.5520
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.8231 - val_accuracy: 0.5485 - val_loss: 0.9601
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.8610 - val_accuracy: 0.7612 - val_loss: 0.5337
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6947 - val_accuracy: 0.6604 - val_loss: 0.7421
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.9865 - val_accuracy: 0.7575 - val_loss: 0.5551
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.8156 - val_accuracy: 0.7463 - val_loss: 0.5457
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.7934 - val_accuracy: 0.7463 - val_loss: 0.5738
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.7844 - val_accuracy: 0.7015 - val_loss: 0.6804
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.8326 - val_accuracy: 0.7799 - val_loss: 0.5498
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.7603 - val_accuracy: 0.6381 - val_loss: 0.7628
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.8091 - val_accuracy: 0.7090 - val_loss: 0.6866
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.8104 - val_accuracy: 0.6530 - val_loss: 1.1773
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.8328 - val_accuracy: 0.7052 - val_loss: 0.7699
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.8399 - val_accuracy: 0.7239 - val_loss: 0.6278
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.8075 - val_accuracy: 0.5522 - val_loss: 0.9272
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6589 - val_accuracy: 0.7164 - val_loss: 0.6203
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.7169 - val_accuracy: 0.7761 - val_loss: 0.5297
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.7059 - val_accuracy: 0.6679 - val_loss: 0.9831
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.8083 - val_accuracy: 0.7463 - val_loss: 0.6466
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7388 - val_accuracy: 0.6754 - val_loss: 1.1035
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.6574 - val_accuracy: 0.7351 - val_loss: 0.6120
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.7992 - val_accuracy: 0.6754 - val_loss: 1.1736
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6957 - val_accuracy: 0.4328 - val_loss: 2.0850
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.9083 - val_accuracy: 0.7239 - val_loss: 0.7272
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.6328 - val_accuracy: 0.7313 - val_loss: 0.6403
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.8059 - val_accuracy: 0.4590 - val_loss: 1.5230
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.7757 - val_accuracy: 0.4440 - val_loss: 1.5867
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.7451 - val_accuracy: 0.7761 - val_loss: 0.5508
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.8521 - val_accuracy: 0.5336 - val_loss: 1.0686
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.7349 - val_accuracy: 0.7463 - val_loss: 0.6545
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.8278 - val_accuracy: 0.7500 - val_loss: 0.5937
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7116 - val_accuracy: 0.7761 - val_loss: 0.5373
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.8212 - val_accuracy: 0.4813 - val_loss: 1.2932
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7741 - val_accuracy: 0.7276 - val_loss: 0.6995
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.7570 - val_accuracy: 0.6754 - val_loss: 0.8992
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.8189 - val_accuracy: 0.5522 - val_loss: 0.9546
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6914 - val_accuracy: 0.6269 - val_loss: 2.1941
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.8048 - val_accuracy: 0.6343 - val_loss: 1.5994
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6373 - val_accuracy: 0.7724 - val_loss: 0.5292
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.7594 - val_accuracy: 0.6791 - val_loss: 0.8341
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.7551 - val_accuracy: 0.7910 - val_loss: 0.5277
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.7825 - val_accuracy: 0.7351 - val_loss: 0.7319
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6225 - val_accuracy: 0.6306 - val_loss: 1.5817
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7986 - val_accuracy: 0.8060 - val_loss: 0.5504
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6912 - val_accuracy: 0.7612 - val_loss: 0.5337
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.7475 - val_accuracy: 0.6343 - val_loss: 1.9867
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.7687 - val_accuracy: 0.7313 - val_loss: 0.7077
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.6808 - val_accuracy: 0.7575 - val_loss: 0.6516
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.7630 - val_accuracy: 0.7687 - val_loss: 0.5740
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6884 - val_accuracy: 0.4291 - val_loss: 2.3503
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: wffpmsk7 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6116 - loss: 10.7816 - val_accuracy: 0.6269 - val_loss: 5.5894
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 2.3008 - val_accuracy: 0.5485 - val_loss: 1.5042
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 1.1684 - val_accuracy: 0.6866 - val_loss: 1.1034
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.9541 - val_accuracy: 0.6754 - val_loss: 0.9891
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.8801 - val_accuracy: 0.6791 - val_loss: 0.8842
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.7978 - val_accuracy: 0.6791 - val_loss: 0.8110
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.7590 - val_accuracy: 0.6791 - val_loss: 0.7629
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.7492 - val_accuracy: 0.6791 - val_loss: 0.7184
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7226 - val_accuracy: 0.6791 - val_loss: 0.6933
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.7103 - val_accuracy: 0.6791 - val_loss: 0.6758
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.6970 - val_accuracy: 0.6679 - val_loss: 0.7030
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6976 - val_accuracy: 0.6791 - val_loss: 0.6385
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.6821 - val_accuracy: 0.6828 - val_loss: 0.6499
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6927 - val_accuracy: 0.6903 - val_loss: 0.6097
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6600 - val_accuracy: 0.6903 - val_loss: 0.6034
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.6528 - val_accuracy: 0.6866 - val_loss: 0.6067
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6453 - val_accuracy: 0.6866 - val_loss: 0.5897
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6438 - val_accuracy: 0.6791 - val_loss: 0.6158
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6400 - val_accuracy: 0.6978 - val_loss: 0.5909
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6485 - loss: 0.6353 - val_accuracy: 0.7127 - val_loss: 0.5883
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.6306 - val_accuracy: 0.6940 - val_loss: 0.5966
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6354 - val_accuracy: 0.6903 - val_loss: 0.6278
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.6512 - val_accuracy: 0.6940 - val_loss: 0.5969
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.6339 - val_accuracy: 0.6978 - val_loss: 0.5965
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.6217 - val_accuracy: 0.6940 - val_loss: 0.6054
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.6190 - val_accuracy: 0.7052 - val_loss: 0.5935
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6113 - val_accuracy: 0.6866 - val_loss: 0.6200
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6517 - loss: 0.6108 - val_accuracy: 0.7127 - val_loss: 0.5954
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.6044 - val_accuracy: 0.6978 - val_loss: 0.6231
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6202 - val_accuracy: 0.7127 - val_loss: 0.5875
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6175 - val_accuracy: 0.7052 - val_loss: 0.5955
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.6132 - val_accuracy: 0.7276 - val_loss: 0.5914
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6102 - val_accuracy: 0.6978 - val_loss: 0.6009
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.6166 - val_accuracy: 0.7201 - val_loss: 0.5959
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6217 - val_accuracy: 0.6828 - val_loss: 0.6106
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.6029 - val_accuracy: 0.7015 - val_loss: 0.6086
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6202 - val_accuracy: 0.6940 - val_loss: 0.6113
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6015 - val_accuracy: 0.7276 - val_loss: 0.5912
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.6145 - val_accuracy: 0.6679 - val_loss: 0.6484
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6182 - val_accuracy: 0.7164 - val_loss: 0.5886
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5883 - val_accuracy: 0.7052 - val_loss: 0.5996
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.6294 - val_accuracy: 0.7351 - val_loss: 0.5810
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.5948 - val_accuracy: 0.6828 - val_loss: 0.6811
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.6165 - val_accuracy: 0.7090 - val_loss: 0.6073
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6037 - val_accuracy: 0.6940 - val_loss: 0.6009
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5828 - val_accuracy: 0.7313 - val_loss: 0.5870
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.5890 - val_accuracy: 0.7313 - val_loss: 0.5825
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.5874 - val_accuracy: 0.7201 - val_loss: 0.5868
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.5829 - val_accuracy: 0.7201 - val_loss: 0.5870
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.5821 - val_accuracy: 0.7164 - val_loss: 0.5922
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.5987 - val_accuracy: 0.7201 - val_loss: 0.5812
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.5963 - val_accuracy: 0.6940 - val_loss: 0.5902
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.5775 - val_accuracy: 0.7164 - val_loss: 0.5862
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6758 - loss: 0.5775 - val_accuracy: 0.7164 - val_loss: 0.5813
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.5777 - val_accuracy: 0.7239 - val_loss: 0.5890
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.5701 - val_accuracy: 0.7313 - val_loss: 0.5745
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5861 - val_accuracy: 0.7090 - val_loss: 0.5881
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5681 - val_accuracy: 0.7052 - val_loss: 0.5828
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.5657 - val_accuracy: 0.6866 - val_loss: 0.6339
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.5871 - val_accuracy: 0.7239 - val_loss: 0.5755
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.5627 - val_accuracy: 0.7164 - val_loss: 0.5656
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.5598 - val_accuracy: 0.7164 - val_loss: 0.5785
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.5585 - val_accuracy: 0.7388 - val_loss: 0.5668
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.5589 - val_accuracy: 0.7127 - val_loss: 0.6178
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.5619 - val_accuracy: 0.7313 - val_loss: 0.5711
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.5645 - val_accuracy: 0.7276 - val_loss: 0.5941
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5581 - val_accuracy: 0.7351 - val_loss: 0.5666
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.5477 - val_accuracy: 0.7388 - val_loss: 0.5583
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5554 - val_accuracy: 0.7388 - val_loss: 0.5661
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7030 - loss: 0.5693 - val_accuracy: 0.7313 - val_loss: 0.5644
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.5802 - val_accuracy: 0.7388 - val_loss: 0.5758
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.5455 - val_accuracy: 0.7239 - val_loss: 0.5710
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5402 - val_accuracy: 0.7276 - val_loss: 0.6035
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.5701 - val_accuracy: 0.7537 - val_loss: 0.5670
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5436 - val_accuracy: 0.7239 - val_loss: 0.5774
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5682 - val_accuracy: 0.7201 - val_loss: 0.5891
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5400 - val_accuracy: 0.7425 - val_loss: 0.5651
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5469 - val_accuracy: 0.7500 - val_loss: 0.5570
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5491 - val_accuracy: 0.7425 - val_loss: 0.5695
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.5694 - val_accuracy: 0.7463 - val_loss: 0.5491
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5291 - val_accuracy: 0.7500 - val_loss: 0.5586
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5183 - val_accuracy: 0.7612 - val_loss: 0.5489
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5253 - val_accuracy: 0.7537 - val_loss: 0.5619
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5251 - val_accuracy: 0.7649 - val_loss: 0.5433
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5596 - val_accuracy: 0.6940 - val_loss: 0.6321
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.5707 - val_accuracy: 0.7463 - val_loss: 0.5708
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5212 - val_accuracy: 0.7463 - val_loss: 0.5583
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5173 - val_accuracy: 0.7649 - val_loss: 0.5460
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5182 - val_accuracy: 0.7612 - val_loss: 0.5821
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5327 - val_accuracy: 0.7500 - val_loss: 0.5496
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5140 - val_accuracy: 0.7687 - val_loss: 0.5343
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5326 - val_accuracy: 0.7425 - val_loss: 0.5532
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5079 - val_accuracy: 0.7500 - val_loss: 0.5393
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5222 - val_accuracy: 0.6642 - val_loss: 0.7280
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.5748 - val_accuracy: 0.7239 - val_loss: 0.5945
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5196 - val_accuracy: 0.7612 - val_loss: 0.5359
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5050 - val_accuracy: 0.7388 - val_loss: 0.5585
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.4982 - val_accuracy: 0.7799 - val_loss: 0.5306
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5171 - val_accuracy: 0.7575 - val_loss: 0.5377
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.4989 - val_accuracy: 0.7799 - val_loss: 0.5224
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.4998 - val_accuracy: 0.7761 - val_loss: 0.5196
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5108 - val_accuracy: 0.7537 - val_loss: 0.5467
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.4990 - val_accuracy: 0.7313 - val_loss: 0.5685
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5229 - val_accuracy: 0.7724 - val_loss: 0.5371
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5022 - val_accuracy: 0.7687 - val_loss: 0.5199
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4896 - val_accuracy: 0.7761 - val_loss: 0.5278
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4789 - val_accuracy: 0.7649 - val_loss: 0.5180
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.4927 - val_accuracy: 0.7687 - val_loss: 0.5467
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5034 - val_accuracy: 0.7276 - val_loss: 0.5566
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4949 - val_accuracy: 0.7836 - val_loss: 0.5182
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.4922 - val_accuracy: 0.7687 - val_loss: 0.5151
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5095 - val_accuracy: 0.7724 - val_loss: 0.5210
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4801 - val_accuracy: 0.7537 - val_loss: 0.5097
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4821 - val_accuracy: 0.7761 - val_loss: 0.5114
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.4799 - val_accuracy: 0.7761 - val_loss: 0.5127
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4725 - val_accuracy: 0.7799 - val_loss: 0.5439
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4923 - val_accuracy: 0.7724 - val_loss: 0.5070
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4677 - val_accuracy: 0.7463 - val_loss: 0.5288
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4911 - val_accuracy: 0.7687 - val_loss: 0.5045
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4754 - val_accuracy: 0.7799 - val_loss: 0.5085
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4819 - val_accuracy: 0.7537 - val_loss: 0.5008
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4781 - val_accuracy: 0.7612 - val_loss: 0.5110
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4833 - val_accuracy: 0.7537 - val_loss: 0.5060
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4669 - val_accuracy: 0.7761 - val_loss: 0.5045
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4714 - val_accuracy: 0.7836 - val_loss: 0.5300
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4695 - val_accuracy: 0.7612 - val_loss: 0.5026
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4607 - val_accuracy: 0.7687 - val_loss: 0.5112
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4842 - val_accuracy: 0.7873 - val_loss: 0.5157
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4768 - val_accuracy: 0.7873 - val_loss: 0.5108
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4710 - val_accuracy: 0.7910 - val_loss: 0.5108
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4657 - val_accuracy: 0.7500 - val_loss: 0.5258
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4703 - val_accuracy: 0.7724 - val_loss: 0.4922
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4553 - val_accuracy: 0.7836 - val_loss: 0.5082
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4690 - val_accuracy: 0.7425 - val_loss: 0.5173
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4733 - val_accuracy: 0.7425 - val_loss: 0.5330
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4638 - val_accuracy: 0.7948 - val_loss: 0.5054
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4700 - val_accuracy: 0.7351 - val_loss: 0.5262
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4764 - val_accuracy: 0.7687 - val_loss: 0.4945
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4533 - val_accuracy: 0.7537 - val_loss: 0.5121
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4833 - val_accuracy: 0.7687 - val_loss: 0.5511
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.4861 - val_accuracy: 0.7500 - val_loss: 0.5226
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4560 - val_accuracy: 0.7799 - val_loss: 0.4974
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4542 - val_accuracy: 0.7799 - val_loss: 0.5092
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4553 - val_accuracy: 0.7687 - val_loss: 0.5296
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4613 - val_accuracy: 0.7500 - val_loss: 0.5263
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4752 - val_accuracy: 0.7575 - val_loss: 0.5014
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4709 - val_accuracy: 0.7724 - val_loss: 0.5383
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4634 - val_accuracy: 0.7836 - val_loss: 0.4919
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4664 - val_accuracy: 0.7724 - val_loss: 0.5037
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4619 - val_accuracy: 0.7687 - val_loss: 0.5088
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.4638 - val_accuracy: 0.7836 - val_loss: 0.5164
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4778 - val_accuracy: 0.7799 - val_loss: 0.5209
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4753 - val_accuracy: 0.7799 - val_loss: 0.4946
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4435 - val_accuracy: 0.7799 - val_loss: 0.5043
Epoch 155/5000

wandb: Agent Starting Run: 9ln3zxyh with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5987 - loss: 14.7304 - val_accuracy: 0.6231 - val_loss: 0.7577
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6998 - val_accuracy: 0.6119 - val_loss: 0.7603
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6880 - val_accuracy: 0.6045 - val_loss: 0.7554
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6835 - val_accuracy: 0.6045 - val_loss: 0.7547
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6798 - val_accuracy: 0.6045 - val_loss: 0.7615
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6772 - val_accuracy: 0.6045 - val_loss: 0.7428
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6751 - val_accuracy: 0.6045 - val_loss: 0.7329
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6738 - val_accuracy: 0.6045 - val_loss: 0.7415
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6711 - val_accuracy: 0.6082 - val_loss: 0.7454
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6704 - val_accuracy: 0.6082 - val_loss: 0.7388
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6682 - val_accuracy: 0.6082 - val_loss: 0.7351
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6671 - val_accuracy: 0.6045 - val_loss: 0.7346
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6660 - val_accuracy: 0.6082 - val_loss: 0.7298
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6646 - val_accuracy: 0.6082 - val_loss: 0.7259
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6642 - val_accuracy: 0.6082 - val_loss: 0.7241
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6082 - val_loss: 0.7236
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6620 - val_accuracy: 0.6082 - val_loss: 0.7224
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6626 - val_accuracy: 0.6082 - val_loss: 0.7210
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6624 - val_accuracy: 0.6082 - val_loss: 0.7191
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6082 - val_loss: 0.7212
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6608 - val_accuracy: 0.6082 - val_loss: 0.7225
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6606 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6601 - val_accuracy: 0.6082 - val_loss: 0.7195
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6601 - val_accuracy: 0.6082 - val_loss: 0.7173
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6082 - val_loss: 0.7198
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6595 - val_accuracy: 0.6082 - val_loss: 0.7185
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6082 - val_loss: 0.7134
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6594 - val_accuracy: 0.6082 - val_loss: 0.7159
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6587 - val_accuracy: 0.6082 - val_loss: 0.7177
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6587 - val_accuracy: 0.6082 - val_loss: 0.7155
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6590 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6585 - val_accuracy: 0.6082 - val_loss: 0.7076
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6588 - val_accuracy: 0.6045 - val_loss: 0.7143
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6586 - val_accuracy: 0.6082 - val_loss: 0.7127
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6579 - val_accuracy: 0.6082 - val_loss: 0.7098
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6591 - val_accuracy: 0.6082 - val_loss: 0.7133
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6585 - val_accuracy: 0.6045 - val_loss: 0.7139
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6045 - val_loss: 0.7120
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6581 - val_accuracy: 0.6082 - val_loss: 0.7150
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6580 - val_accuracy: 0.6045 - val_loss: 0.7124
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6583 - val_accuracy: 0.6082 - val_loss: 0.7121
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6583 - val_accuracy: 0.6045 - val_loss: 0.7119
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6045 - val_loss: 0.7163
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6082 - val_loss: 0.7098
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6045 - val_loss: 0.7081
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6045 - val_loss: 0.7151
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6045 - val_loss: 0.7142
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6580 - val_accuracy: 0.6045 - val_loss: 0.7134
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6587 - val_accuracy: 0.6045 - val_loss: 0.7104
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6045 - val_loss: 0.7130
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6580 - val_accuracy: 0.6045 - val_loss: 0.7131
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6045 - val_loss: 0.7174
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7163
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6581 - val_accuracy: 0.6082 - val_loss: 0.7077
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6582 - val_accuracy: 0.6082 - val_loss: 0.7084
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6583 - val_accuracy: 0.6045 - val_loss: 0.7121
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6569 - val_accuracy: 0.6082 - val_loss: 0.7183
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6577 - val_accuracy: 0.6045 - val_loss: 0.7177
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6580 - val_accuracy: 0.6045 - val_loss: 0.7240
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6583 - val_accuracy: 0.6082 - val_loss: 0.7157
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6045 - val_loss: 0.7106
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6574 - val_accuracy: 0.6045 - val_loss: 0.7154
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6576 - val_accuracy: 0.6082 - val_loss: 0.7176
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6577 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7168
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6082 - val_loss: 0.7048
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6045 - val_loss: 0.7114
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7138
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6045 - val_loss: 0.7111
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6583 - val_accuracy: 0.6045 - val_loss: 0.7152
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7163
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6578 - val_accuracy: 0.6082 - val_loss: 0.7135
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6581 - val_accuracy: 0.6082 - val_loss: 0.7140
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6575 - val_accuracy: 0.6045 - val_loss: 0.7096
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6584 - val_accuracy: 0.6045 - val_loss: 0.7127
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7135
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6588 - val_accuracy: 0.6045 - val_loss: 0.7087
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7132
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6575 - val_accuracy: 0.6045 - val_loss: 0.7131
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6577 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6585 - val_accuracy: 0.6007 - val_loss: 0.7173
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7099
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7106
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6584 - val_accuracy: 0.6045 - val_loss: 0.7153
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7156
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6576 - val_accuracy: 0.6007 - val_loss: 0.7174
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7279
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6586 - val_accuracy: 0.6045 - val_loss: 0.7220
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6082 - val_loss: 0.7184
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7126
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6570 - val_accuracy: 0.6045 - val_loss: 0.7197
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7118
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6045 - val_loss: 0.7148
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7128
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6574 - val_accuracy: 0.6007 - val_loss: 0.7191
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6575 - val_accuracy: 0.6007 - val_loss: 0.7201
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7228
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7355
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6594 - val_accuracy: 0.6007 - val_loss: 0.7247
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6583 - val_accuracy: 0.6045 - val_loss: 0.7227
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6579 - val_accuracy: 0.6045 - val_loss: 0.7135
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7191
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6571 - val_accuracy: 0.6045 - val_loss: 0.7152
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6579 - val_accuracy: 0.6045 - val_loss: 0.7141
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7202
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6569 - val_accuracy: 0.6045 - val_loss: 0.7137
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6574 - val_accuracy: 0.6007 - val_loss: 0.7068
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6581 - val_accuracy: 0.6045 - val_loss: 0.7110
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6569 - val_accuracy: 0.6007 - val_loss: 0.7179
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6572 - val_accuracy: 0.6007 - val_loss: 0.7089
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7188
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6580 - val_accuracy: 0.6045 - val_loss: 0.7077
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6574 - val_accuracy: 0.6007 - val_loss: 0.7093
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7157
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7121
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6571 - val_accuracy: 0.6045 - val_loss: 0.7072
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7111
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6562 - val_accuracy: 0.6045 - val_loss: 0.7067
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6578 - val_accuracy: 0.6045 - val_loss: 0.7091
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6571 - val_accuracy: 0.6007 - val_loss: 0.7182
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7121
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7079
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6572 - val_accuracy: 0.6007 - val_loss: 0.7151
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7159
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6570 - val_accuracy: 0.6007 - val_loss: 0.7220
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6575 - val_accuracy: 0.6007 - val_loss: 0.7168
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7102
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7158
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6569 - val_accuracy: 0.6045 - val_loss: 0.7140
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7161
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7100
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7150
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6571 - val_accuracy: 0.6045 - val_loss: 0.7156
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6045 - val_loss: 0.7186
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6570 - val_accuracy: 0.6045 - val_loss: 0.7115
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6576 - val_accuracy: 0.6045 - val_loss: 0.7105
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6569 - val_accuracy: 0.6007 - val_loss: 0.7172
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6567 - val_accuracy: 0.6045 - val_loss: 0.7233
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6572 - val_accuracy: 0.6007 - val_loss: 0.7206
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7247
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7224
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6571 - val_accuracy: 0.6007 - val_loss: 0.7180
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7149
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6571 - val_accuracy: 0.6007 - val_loss: 0.7195
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7133
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6572 - val_accuracy: 0.6045 - val_loss: 0.7142
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6565 - val_accuracy: 0.6045 - val_loss: 0.7138
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6570 - val_accuracy: 0.6045 - val_loss: 0.7142
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7251
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6276 - loss: 0.6568 - val_accuracy: 0.6045 - val_loss: 0.7154
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.6570 - val_accuracy: 0.6045 - val_loss: 0.7227
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6566 - val_accuracy: 0.6045 - val_loss: 0.7161
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6567 - val_accuracy: 0.6045 - val_loss: 0.7111
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6569 - val_accuracy: 0.6045 - val_loss: 0.7149
Epoch 155/5000

wandb: Agent Starting Run: 2y6ethru with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4446 - loss: 16.9619 - val_accuracy: 0.6866 - val_loss: 0.7954
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5939 - loss: 1.0687 - val_accuracy: 0.6828 - val_loss: 0.7445
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 1.0217 - val_accuracy: 0.6269 - val_loss: 1.7792
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.9626 - val_accuracy: 0.5336 - val_loss: 0.9198
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6003 - loss: 0.9959 - val_accuracy: 0.6866 - val_loss: 0.6949
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6019 - loss: 0.9397 - val_accuracy: 0.4478 - val_loss: 1.3754
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 0.9776 - val_accuracy: 0.6679 - val_loss: 0.7662
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.8481 - val_accuracy: 0.6231 - val_loss: 0.9892
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6083 - loss: 0.9559 - val_accuracy: 0.6978 - val_loss: 0.6369
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.8581 - val_accuracy: 0.4366 - val_loss: 1.5030
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5987 - loss: 0.9595 - val_accuracy: 0.4963 - val_loss: 0.9079
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.9126 - val_accuracy: 0.6418 - val_loss: 0.8419
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.9133 - val_accuracy: 0.6679 - val_loss: 0.6985
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.8303 - val_accuracy: 0.4739 - val_loss: 1.0083
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.8359 - val_accuracy: 0.7127 - val_loss: 0.6399
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6228 - loss: 0.8384 - val_accuracy: 0.6231 - val_loss: 0.9228
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.8556 - val_accuracy: 0.7015 - val_loss: 0.6449
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.9368 - val_accuracy: 0.7090 - val_loss: 0.6457
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.8199 - val_accuracy: 0.7090 - val_loss: 0.5875
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.8940 - val_accuracy: 0.6866 - val_loss: 0.6574
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.8346 - val_accuracy: 0.6828 - val_loss: 0.5960
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6549 - loss: 0.8467 - val_accuracy: 0.5336 - val_loss: 0.7775
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.8827 - val_accuracy: 0.4216 - val_loss: 1.7068
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6404 - loss: 0.8353 - val_accuracy: 0.7201 - val_loss: 0.5899
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7883 - val_accuracy: 0.6493 - val_loss: 0.9573
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.8422 - val_accuracy: 0.6343 - val_loss: 1.0878
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.8054 - val_accuracy: 0.7276 - val_loss: 0.5886
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.7685 - val_accuracy: 0.7313 - val_loss: 0.5752
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6437 - loss: 0.7828 - val_accuracy: 0.4701 - val_loss: 0.9575
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.7153 - val_accuracy: 0.7015 - val_loss: 0.6167
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6469 - loss: 0.7967 - val_accuracy: 0.7351 - val_loss: 0.5643
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.8294 - val_accuracy: 0.6940 - val_loss: 0.6617
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6196 - loss: 0.8265 - val_accuracy: 0.7276 - val_loss: 0.5609
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.7114 - val_accuracy: 0.4813 - val_loss: 0.9243
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.7313 - val_accuracy: 0.6828 - val_loss: 0.7179
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.7487 - val_accuracy: 0.6231 - val_loss: 1.5206
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6421 - loss: 0.7951 - val_accuracy: 0.7388 - val_loss: 0.5553
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6966 - loss: 0.6536 - val_accuracy: 0.7276 - val_loss: 0.5659
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.8076 - val_accuracy: 0.5522 - val_loss: 0.7415
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.6902 - val_accuracy: 0.6269 - val_loss: 0.6834
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.7291 - val_accuracy: 0.4328 - val_loss: 1.7769
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7722 - val_accuracy: 0.4851 - val_loss: 0.9607
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.7583 - val_accuracy: 0.6754 - val_loss: 0.7633
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6554 - val_accuracy: 0.7612 - val_loss: 0.5593
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.8116 - val_accuracy: 0.7687 - val_loss: 0.5571
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6497 - val_accuracy: 0.6791 - val_loss: 0.7961
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.6877 - val_accuracy: 0.6269 - val_loss: 1.2557
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.6600 - val_accuracy: 0.7463 - val_loss: 0.5359
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7308 - val_accuracy: 0.6791 - val_loss: 0.6772
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.7307 - val_accuracy: 0.5485 - val_loss: 0.7676
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.6852 - val_accuracy: 0.6567 - val_loss: 0.8636
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.7852 - val_accuracy: 0.7724 - val_loss: 0.5725
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6447 - val_accuracy: 0.7388 - val_loss: 0.5502
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6077 - val_accuracy: 0.6343 - val_loss: 1.2410
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6645 - loss: 0.8178 - val_accuracy: 0.6455 - val_loss: 1.0894
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6390 - val_accuracy: 0.5299 - val_loss: 0.8462
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.7611 - val_accuracy: 0.7687 - val_loss: 0.5425
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6375 - val_accuracy: 0.7052 - val_loss: 0.6467
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6303 - val_accuracy: 0.6493 - val_loss: 1.0564
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.6989 - val_accuracy: 0.6306 - val_loss: 1.5735
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.6611 - val_accuracy: 0.4963 - val_loss: 0.9378
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6276 - val_accuracy: 0.6754 - val_loss: 0.8293
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6708 - val_accuracy: 0.6754 - val_loss: 0.8067
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.6684 - val_accuracy: 0.7799 - val_loss: 0.5690
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.6616 - val_accuracy: 0.7575 - val_loss: 0.5376
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6365 - val_accuracy: 0.6642 - val_loss: 0.9114
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.6672 - val_accuracy: 0.7127 - val_loss: 0.6534
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6174 - val_accuracy: 0.7575 - val_loss: 0.5372
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6246 - val_accuracy: 0.6791 - val_loss: 0.8470
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6640 - val_accuracy: 0.7127 - val_loss: 0.6607
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5901 - val_accuracy: 0.7537 - val_loss: 0.5565
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7307 - val_accuracy: 0.6940 - val_loss: 0.7562
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5914 - val_accuracy: 0.7836 - val_loss: 0.6056
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.7118 - val_accuracy: 0.6343 - val_loss: 1.7082
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6373 - val_accuracy: 0.7612 - val_loss: 0.5368
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5875 - val_accuracy: 0.7799 - val_loss: 0.5586
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6212 - val_accuracy: 0.5149 - val_loss: 0.9695
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6368 - val_accuracy: 0.7500 - val_loss: 0.5522
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5920 - val_accuracy: 0.6716 - val_loss: 0.8069
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6374 - val_accuracy: 0.5373 - val_loss: 0.9556
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6687 - val_accuracy: 0.7724 - val_loss: 0.5498
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6363 - val_accuracy: 0.5672 - val_loss: 0.8141
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6586 - val_accuracy: 0.7537 - val_loss: 0.5668
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5786 - val_accuracy: 0.6306 - val_loss: 0.7600
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6015 - val_accuracy: 0.6903 - val_loss: 0.7957
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.7020 - val_accuracy: 0.6754 - val_loss: 0.9261
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6178 - val_accuracy: 0.7127 - val_loss: 0.7136
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5985 - val_accuracy: 0.7052 - val_loss: 0.7226
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.6050 - val_accuracy: 0.6567 - val_loss: 0.7498
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.6261 - val_accuracy: 0.7649 - val_loss: 0.5550
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.6673 - val_accuracy: 0.7612 - val_loss: 0.5556
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5542 - val_accuracy: 0.7015 - val_loss: 0.7487
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5643 - val_accuracy: 0.7612 - val_loss: 0.6583
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5338 - val_accuracy: 0.6343 - val_loss: 1.3520
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6382 - val_accuracy: 0.4776 - val_loss: 1.3619
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5603 - val_accuracy: 0.7276 - val_loss: 0.7249
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.6082 - val_accuracy: 0.6642 - val_loss: 0.9375
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5932 - val_accuracy: 0.7500 - val_loss: 0.6818
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.6007 - val_accuracy: 0.6642 - val_loss: 1.0097
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5515 - val_accuracy: 0.7612 - val_loss: 0.5730
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5967 - val_accuracy: 0.5560 - val_loss: 0.8770
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5918 - val_accuracy: 0.6530 - val_loss: 1.1030
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5761 - val_accuracy: 0.6343 - val_loss: 1.3923
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.6289 - val_accuracy: 0.7799 - val_loss: 0.5946
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5550 - val_accuracy: 0.4627 - val_loss: 1.6264
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.6477 - val_accuracy: 0.7612 - val_loss: 0.5960
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5986 - val_accuracy: 0.7761 - val_loss: 0.5831
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5755 - val_accuracy: 0.7724 - val_loss: 0.5749
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5524 - val_accuracy: 0.6082 - val_loss: 0.8407
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5873 - val_accuracy: 0.7052 - val_loss: 0.8068
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5539 - val_accuracy: 0.6679 - val_loss: 1.0097
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5977 - val_accuracy: 0.5373 - val_loss: 0.9678
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6324 - val_accuracy: 0.7799 - val_loss: 0.6114
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.6198 - val_accuracy: 0.7388 - val_loss: 0.7461
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.5713 - val_accuracy: 0.5187 - val_loss: 1.0189
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.6394 - val_accuracy: 0.7687 - val_loss: 0.5976
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5597 - val_accuracy: 0.7463 - val_loss: 0.7359
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5463 - val_accuracy: 0.7500 - val_loss: 0.7007
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.6181 - val_accuracy: 0.7575 - val_loss: 0.6889
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5966 - val_accuracy: 0.7612 - val_loss: 0.6010
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4769 - val_accuracy: 0.7649 - val_loss: 0.5947
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5906 - val_accuracy: 0.7575 - val_loss: 0.6168
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5695 - val_accuracy: 0.4776 - val_loss: 1.4094
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5517 - val_accuracy: 0.7015 - val_loss: 0.8702
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5533 - val_accuracy: 0.7724 - val_loss: 0.5904
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5838 - val_accuracy: 0.7799 - val_loss: 0.6143
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5590 - val_accuracy: 0.7649 - val_loss: 0.6086
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5190 - val_accuracy: 0.6791 - val_loss: 1.0324
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5742 - val_accuracy: 0.7201 - val_loss: 0.7850
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5711 - val_accuracy: 0.7836 - val_loss: 0.6144
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5488 - val_accuracy: 0.7425 - val_loss: 0.7335
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.6353 - val_accuracy: 0.7649 - val_loss: 0.6146
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4875 - val_accuracy: 0.7015 - val_loss: 0.9038
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.6354 - val_accuracy: 0.7836 - val_loss: 0.6522
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.6215 - val_accuracy: 0.7799 - val_loss: 0.6450
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5364 - val_accuracy: 0.6903 - val_loss: 0.8217
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5721 - val_accuracy: 0.7612 - val_loss: 0.7114
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5949 - val_accuracy: 0.6791 - val_loss: 1.0053
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6264 - val_accuracy: 0.7463 - val_loss: 0.7572
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5671 - val_accuracy: 0.6343 - val_loss: 1.5415
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5662 - val_accuracy: 0.7612 - val_loss: 0.7376
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5579 - val_accuracy: 0.7351 - val_loss: 0.8032
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5770 - val_accuracy: 0.7649 - val_loss: 0.6425
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.5150 - val_accuracy: 0.7724 - val_loss: 0.6393
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.5561 - val_accuracy: 0.7425 - val_loss: 0.7707
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5483 - val_accuracy: 0.5336 - val_loss: 1.1902
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6132 - val_accuracy: 0.7761 - val_loss: 0.6297
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5875 - val_accuracy: 0.7351 - val_loss: 0.7936
Epoch 148: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 29fs4ag0 with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3868 - loss: 27.4381 - val_accuracy: 0.3843 - val_loss: 17.7530
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3852 - loss: 10.1743 - val_accuracy: 0.5149 - val_loss: 1.2127
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 1.8799 - val_accuracy: 0.6679 - val_loss: 1.6266
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 1.2812 - val_accuracy: 0.6194 - val_loss: 0.8249
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.9612 - val_accuracy: 0.6455 - val_loss: 0.7284
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5923 - loss: 0.8406 - val_accuracy: 0.6418 - val_loss: 0.6844
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.7355 - val_accuracy: 0.6679 - val_loss: 0.6626
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.6862 - val_accuracy: 0.6791 - val_loss: 0.6406
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6308 - loss: 0.6428 - val_accuracy: 0.6903 - val_loss: 0.6609
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6565 - loss: 0.6115 - val_accuracy: 0.7090 - val_loss: 0.6438
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.6117 - val_accuracy: 0.6903 - val_loss: 0.6469
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.6025 - val_accuracy: 0.7127 - val_loss: 0.6334
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6629 - loss: 0.6060 - val_accuracy: 0.7090 - val_loss: 0.6317
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6902 - loss: 0.5910 - val_accuracy: 0.7090 - val_loss: 0.6279
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.5848 - val_accuracy: 0.7201 - val_loss: 0.6290
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6661 - loss: 0.5958 - val_accuracy: 0.6903 - val_loss: 0.6584
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.6064 - val_accuracy: 0.7239 - val_loss: 0.6245
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5802 - val_accuracy: 0.7090 - val_loss: 0.6242
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5771 - val_accuracy: 0.7201 - val_loss: 0.6220
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.5791 - val_accuracy: 0.7276 - val_loss: 0.6196
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5768 - val_accuracy: 0.7127 - val_loss: 0.6298
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5659 - val_accuracy: 0.7164 - val_loss: 0.6152
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.5756 - val_accuracy: 0.7164 - val_loss: 0.6147
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.5842 - val_accuracy: 0.6866 - val_loss: 0.6796
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.5960 - val_accuracy: 0.7351 - val_loss: 0.6096
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5613 - val_accuracy: 0.7164 - val_loss: 0.6145
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5584 - val_accuracy: 0.7276 - val_loss: 0.6026
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5477 - val_accuracy: 0.7164 - val_loss: 0.6074
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5492 - val_accuracy: 0.7164 - val_loss: 0.6062
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5488 - val_accuracy: 0.7015 - val_loss: 0.6129
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5506 - val_accuracy: 0.7164 - val_loss: 0.6006
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5448 - val_accuracy: 0.7276 - val_loss: 0.6015
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.5668 - val_accuracy: 0.7313 - val_loss: 0.5947
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5526 - val_accuracy: 0.6978 - val_loss: 0.6159
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.5357 - val_accuracy: 0.7052 - val_loss: 0.6144
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5521 - val_accuracy: 0.6978 - val_loss: 0.6280
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5393 - val_accuracy: 0.7052 - val_loss: 0.5919
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5528 - val_accuracy: 0.7351 - val_loss: 0.5900
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.5453 - val_accuracy: 0.7239 - val_loss: 0.5938
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5339 - val_accuracy: 0.7052 - val_loss: 0.5992
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.5728 - val_accuracy: 0.7052 - val_loss: 0.6555
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.5528 - val_accuracy: 0.7388 - val_loss: 0.5881
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.5410 - val_accuracy: 0.7388 - val_loss: 0.5912
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5320 - val_accuracy: 0.7015 - val_loss: 0.5899
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7223 - loss: 0.5368 - val_accuracy: 0.7201 - val_loss: 0.5846
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.5269 - val_accuracy: 0.7313 - val_loss: 0.5804
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5456 - val_accuracy: 0.7351 - val_loss: 0.5771
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5288 - val_accuracy: 0.7276 - val_loss: 0.5778
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.5159 - val_accuracy: 0.7127 - val_loss: 0.5784
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5167 - val_accuracy: 0.7090 - val_loss: 0.5886
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.5200 - val_accuracy: 0.7276 - val_loss: 0.5808
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5286 - val_accuracy: 0.7052 - val_loss: 0.5917
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5090 - val_accuracy: 0.7575 - val_loss: 0.5888
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5034 - val_accuracy: 0.7799 - val_loss: 0.5811
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.5367 - val_accuracy: 0.7164 - val_loss: 0.5939
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.5060 - val_accuracy: 0.7537 - val_loss: 0.5773
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5178 - val_accuracy: 0.7687 - val_loss: 0.5829
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5006 - val_accuracy: 0.7276 - val_loss: 0.5690
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5041 - val_accuracy: 0.7351 - val_loss: 0.5644
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5002 - val_accuracy: 0.7201 - val_loss: 0.5735
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5059 - val_accuracy: 0.7724 - val_loss: 0.5818
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.5539 - val_accuracy: 0.6828 - val_loss: 0.6080
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5091 - val_accuracy: 0.7612 - val_loss: 0.5764
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5074 - val_accuracy: 0.7276 - val_loss: 0.5528
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.4887 - val_accuracy: 0.6940 - val_loss: 0.6124
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4892 - val_accuracy: 0.7425 - val_loss: 0.5705
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.4900 - val_accuracy: 0.7463 - val_loss: 0.5552
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.4866 - val_accuracy: 0.7687 - val_loss: 0.5662
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.4850 - val_accuracy: 0.6978 - val_loss: 0.5992
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.5267 - val_accuracy: 0.7612 - val_loss: 0.5885
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5081 - val_accuracy: 0.7201 - val_loss: 0.5890
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4867 - val_accuracy: 0.7687 - val_loss: 0.5607
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4936 - val_accuracy: 0.7388 - val_loss: 0.5752
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5058 - val_accuracy: 0.7612 - val_loss: 0.5537
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.4953 - val_accuracy: 0.7687 - val_loss: 0.5355
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.4899 - val_accuracy: 0.7575 - val_loss: 0.5460
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.4845 - val_accuracy: 0.7537 - val_loss: 0.5499
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7608 - loss: 0.4987 - val_accuracy: 0.7687 - val_loss: 0.5473
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4811 - val_accuracy: 0.7687 - val_loss: 0.5441
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4739 - val_accuracy: 0.7500 - val_loss: 0.5513
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5283 - val_accuracy: 0.7463 - val_loss: 0.5698
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5442 - val_accuracy: 0.7649 - val_loss: 0.5691
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.4690 - val_accuracy: 0.7575 - val_loss: 0.5639
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4737 - val_accuracy: 0.7351 - val_loss: 0.5779
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4837 - val_accuracy: 0.7799 - val_loss: 0.5651
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4719 - val_accuracy: 0.7313 - val_loss: 0.5778
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4798 - val_accuracy: 0.7127 - val_loss: 0.6522
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5028 - val_accuracy: 0.7425 - val_loss: 0.5978
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4931 - val_accuracy: 0.7425 - val_loss: 0.5804
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5076 - val_accuracy: 0.7351 - val_loss: 0.6175
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4742 - val_accuracy: 0.7500 - val_loss: 0.6046
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.4899 - val_accuracy: 0.7575 - val_loss: 0.5510
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4670 - val_accuracy: 0.7575 - val_loss: 0.5575
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.4712 - val_accuracy: 0.7425 - val_loss: 0.5531
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4707 - val_accuracy: 0.7425 - val_loss: 0.5511
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4722 - val_accuracy: 0.7500 - val_loss: 0.5540
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4628 - val_accuracy: 0.7537 - val_loss: 0.5598
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4646 - val_accuracy: 0.7425 - val_loss: 0.5728
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.4964 - val_accuracy: 0.7612 - val_loss: 0.5659
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4598 - val_accuracy: 0.7463 - val_loss: 0.5886
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4534 - val_accuracy: 0.7649 - val_loss: 0.5630
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4591 - val_accuracy: 0.7537 - val_loss: 0.5745
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4650 - val_accuracy: 0.7537 - val_loss: 0.5550
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4467 - val_accuracy: 0.7612 - val_loss: 0.5690
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4447 - val_accuracy: 0.7388 - val_loss: 0.5562
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4546 - val_accuracy: 0.7724 - val_loss: 0.5850
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.4870 - val_accuracy: 0.7388 - val_loss: 0.6163
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4606 - val_accuracy: 0.7687 - val_loss: 0.5414
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4451 - val_accuracy: 0.7649 - val_loss: 0.5654
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4568 - val_accuracy: 0.7276 - val_loss: 0.5753
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4548 - val_accuracy: 0.7351 - val_loss: 0.5546
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4482 - val_accuracy: 0.7687 - val_loss: 0.5524
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4699 - val_accuracy: 0.7351 - val_loss: 0.5713
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4691 - val_accuracy: 0.7575 - val_loss: 0.5518
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4712 - val_accuracy: 0.7575 - val_loss: 0.5611
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4434 - val_accuracy: 0.7313 - val_loss: 0.6226
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4436 - val_accuracy: 0.7537 - val_loss: 0.5458
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4759 - val_accuracy: 0.7425 - val_loss: 0.5622
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4675 - val_accuracy: 0.7649 - val_loss: 0.5616
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4525 - val_accuracy: 0.7612 - val_loss: 0.5706
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5026 - val_accuracy: 0.7351 - val_loss: 0.5927
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4356 - val_accuracy: 0.7612 - val_loss: 0.5504
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4418 - val_accuracy: 0.7649 - val_loss: 0.5584
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4394 - val_accuracy: 0.7500 - val_loss: 0.5601
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4649 - val_accuracy: 0.7724 - val_loss: 0.6015
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4670 - val_accuracy: 0.7537 - val_loss: 0.5904
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4511 - val_accuracy: 0.7687 - val_loss: 0.5824
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4349 - val_accuracy: 0.7463 - val_loss: 0.5714
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.4798 - val_accuracy: 0.7351 - val_loss: 0.6014
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4979 - val_accuracy: 0.7575 - val_loss: 0.5673
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4823 - val_accuracy: 0.7612 - val_loss: 0.5599
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4629 - val_accuracy: 0.7612 - val_loss: 0.5653
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4776 - val_accuracy: 0.7612 - val_loss: 0.5724
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4425 - val_accuracy: 0.7575 - val_loss: 0.5631
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4359 - val_accuracy: 0.7687 - val_loss: 0.5564
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4348 - val_accuracy: 0.7575 - val_loss: 0.5591
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4383 - val_accuracy: 0.7612 - val_loss: 0.5639
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4602 - val_accuracy: 0.7687 - val_loss: 0.5952
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4547 - val_accuracy: 0.7537 - val_loss: 0.5604
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8266 - loss: 0.4386 - val_accuracy: 0.6679 - val_loss: 0.7368
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.4759 - val_accuracy: 0.7463 - val_loss: 0.5895
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4383 - val_accuracy: 0.7537 - val_loss: 0.5709
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4346 - val_accuracy: 0.7425 - val_loss: 0.5725
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4507 - val_accuracy: 0.7724 - val_loss: 0.6019
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4414 - val_accuracy: 0.7575 - val_loss: 0.5607
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4393 - val_accuracy: 0.7463 - val_loss: 0.5593
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.4523 - val_accuracy: 0.7313 - val_loss: 0.6094
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4737 - val_accuracy: 0.7649 - val_loss: 0.5831
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8202 - loss: 0.4493 - val_accuracy: 0.7388 - val_loss: 0.5790
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4607 - val_accuracy: 0.7612 - val_loss: 0.5811
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4443 - val_accuracy: 0.7612 - val_loss: 0.5952
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4343 - val_accuracy: 0.7575 - val_loss: 0.5950
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4501 - val_accuracy: 0.7799 - val_loss: 0.6615
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4340 - val_accuracy: 0.7649 - val_loss: 0.5942
Epoch 155/5000

wandb: Agent Starting Run: g74e8nue with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5843 - loss: 24.1926 - val_accuracy: 0.6269 - val_loss: 0.9394
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7587 - val_accuracy: 0.6269 - val_loss: 0.8343
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7254 - val_accuracy: 0.6269 - val_loss: 0.8015
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7110 - val_accuracy: 0.6269 - val_loss: 0.7706
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.7042 - val_accuracy: 0.6269 - val_loss: 0.7514
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6947 - val_accuracy: 0.6269 - val_loss: 0.7347
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6886 - val_accuracy: 0.6269 - val_loss: 0.7205
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6843 - val_accuracy: 0.6269 - val_loss: 0.7127
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6815 - val_accuracy: 0.6269 - val_loss: 0.7036
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6791 - val_accuracy: 0.6269 - val_loss: 0.6996
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6773 - val_accuracy: 0.6269 - val_loss: 0.7032
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6761 - val_accuracy: 0.6269 - val_loss: 0.6985
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6116 - loss: 0.6748 - val_accuracy: 0.6269 - val_loss: 0.6968
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6738 - val_accuracy: 0.6269 - val_loss: 0.6934
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6727 - val_accuracy: 0.6269 - val_loss: 0.6950
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6720 - val_accuracy: 0.6269 - val_loss: 0.6932
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6712 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6705 - val_accuracy: 0.6306 - val_loss: 0.6888
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6697 - val_accuracy: 0.6306 - val_loss: 0.6878
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6306 - val_loss: 0.6881
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6686 - val_accuracy: 0.6306 - val_loss: 0.6868
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6680 - val_accuracy: 0.6306 - val_loss: 0.6828
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6677 - val_accuracy: 0.6306 - val_loss: 0.6875
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6880
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6872
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6861
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6866
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6856
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6864
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6855
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6306 - val_loss: 0.6865
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6868
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6306 - val_loss: 0.6859
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6860
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6849
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6306 - val_loss: 0.6853
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6647 - val_accuracy: 0.6306 - val_loss: 0.6851
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6306 - val_loss: 0.6854
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6644 - val_accuracy: 0.6306 - val_loss: 0.6852
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6853
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6842
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6642 - val_accuracy: 0.6306 - val_loss: 0.6849
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6852
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6640 - val_accuracy: 0.6306 - val_loss: 0.6852
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6639 - val_accuracy: 0.6306 - val_loss: 0.6847
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6850
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6853
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.6841
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6636 - val_accuracy: 0.6306 - val_loss: 0.6843
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6635 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6635 - val_accuracy: 0.6306 - val_loss: 0.6841
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6634 - val_accuracy: 0.6306 - val_loss: 0.6844
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6633 - val_accuracy: 0.6306 - val_loss: 0.6843
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6634 - val_accuracy: 0.6306 - val_loss: 0.6838
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6633 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6633 - val_accuracy: 0.6306 - val_loss: 0.6841
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6306 - val_loss: 0.6842
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6631 - val_accuracy: 0.6306 - val_loss: 0.6842
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6306 - val_loss: 0.6832
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6631 - val_accuracy: 0.6306 - val_loss: 0.6831
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6631 - val_accuracy: 0.6306 - val_loss: 0.6835
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6306 - val_loss: 0.6838
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6306 - val_loss: 0.6840
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6629 - val_accuracy: 0.6306 - val_loss: 0.6843
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6306 - val_loss: 0.6834
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6629 - val_accuracy: 0.6306 - val_loss: 0.6836
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6629 - val_accuracy: 0.6306 - val_loss: 0.6834
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6836
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6839
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6842
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6833
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6627 - val_accuracy: 0.6306 - val_loss: 0.6841
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6627 - val_accuracy: 0.6306 - val_loss: 0.6843
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6850
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6822
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6306 - val_loss: 0.6825
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 0.6627 - val_accuracy: 0.6306 - val_loss: 0.6827
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6627 - val_accuracy: 0.6306 - val_loss: 0.6825
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6832
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6831
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6830
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6306 - val_loss: 0.6833
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6306 - val_loss: 0.6837
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6841
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6850
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6854
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6861
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6306 - val_loss: 0.6836
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6306 - val_loss: 0.6842
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6845
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6851
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6859
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6863
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6867
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6306 - val_loss: 0.6852
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6859
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6865
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6869
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6875
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6846
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6853
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6859
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6868
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6620 - val_accuracy: 0.6306 - val_loss: 0.6875
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6850
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6306 - val_loss: 0.6854
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6620 - val_accuracy: 0.6306 - val_loss: 0.6861
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6620 - val_accuracy: 0.6306 - val_loss: 0.6867
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6620 - val_accuracy: 0.6306 - val_loss: 0.6873
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6619 - val_accuracy: 0.6306 - val_loss: 0.6882
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6306 - val_loss: 0.6889
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6306 - val_loss: 0.6859
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6306 - val_loss: 0.6866
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6872
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6878
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6884
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6891
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6306 - val_loss: 0.6874
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6882
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6887
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6895
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6880
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6886
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6891
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6900
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6909
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6880
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.6884
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6891
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6897
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6911
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6880
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6887
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6895
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6902
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6910
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6921
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6931
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6900
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6909
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6917
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: vbf45nuw with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5217 - loss: 2.8981 - val_accuracy: 0.6007 - val_loss: 3.1300
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5169 - loss: 1.7224 - val_accuracy: 0.6343 - val_loss: 0.7461
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5329 - loss: 1.3988 - val_accuracy: 0.4590 - val_loss: 0.8305
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5522 - loss: 1.1607 - val_accuracy: 0.6716 - val_loss: 0.7672
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6148 - loss: 1.0225 - val_accuracy: 0.4216 - val_loss: 2.0192
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6003 - loss: 1.1580 - val_accuracy: 0.6194 - val_loss: 1.6066
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5795 - loss: 1.1849 - val_accuracy: 0.6157 - val_loss: 2.3294
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5875 - loss: 1.1619 - val_accuracy: 0.6866 - val_loss: 0.7226
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.8436 - val_accuracy: 0.4067 - val_loss: 2.9372
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6100 - loss: 1.1031 - val_accuracy: 0.7201 - val_loss: 0.6470
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5955 - loss: 1.1870 - val_accuracy: 0.6269 - val_loss: 1.3575
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6051 - loss: 1.1420 - val_accuracy: 0.7090 - val_loss: 0.5891
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.9534 - val_accuracy: 0.5112 - val_loss: 0.7257
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5746 - loss: 1.1365 - val_accuracy: 0.6679 - val_loss: 0.8321
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6388 - loss: 0.9640 - val_accuracy: 0.6381 - val_loss: 1.3341
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 1.0467 - val_accuracy: 0.6978 - val_loss: 0.5854
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.5762 - loss: 1.1225 - val_accuracy: 0.4552 - val_loss: 0.9248
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.9221 - val_accuracy: 0.7015 - val_loss: 0.6460
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6356 - loss: 0.9579 - val_accuracy: 0.6716 - val_loss: 0.7822
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6324 - loss: 0.9226 - val_accuracy: 0.7351 - val_loss: 0.5577
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8562 - val_accuracy: 0.4142 - val_loss: 2.9268
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.9415 - val_accuracy: 0.6231 - val_loss: 1.8964
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.9499 - val_accuracy: 0.4552 - val_loss: 0.9940
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6453 - loss: 0.9038 - val_accuracy: 0.6418 - val_loss: 1.1986
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.9416 - val_accuracy: 0.4142 - val_loss: 2.3372
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.9361 - val_accuracy: 0.7463 - val_loss: 0.5804
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6180 - loss: 0.9753 - val_accuracy: 0.4851 - val_loss: 0.9203
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6372 - loss: 0.8714 - val_accuracy: 0.6306 - val_loss: 1.5420
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6597 - loss: 0.8848 - val_accuracy: 0.7015 - val_loss: 0.6470
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6693 - loss: 0.9092 - val_accuracy: 0.6903 - val_loss: 0.6860
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8887 - val_accuracy: 0.7537 - val_loss: 0.5308
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6934 - loss: 0.8580 - val_accuracy: 0.6231 - val_loss: 1.6137
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.9309 - val_accuracy: 0.7388 - val_loss: 0.5061
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6774 - loss: 0.7932 - val_accuracy: 0.4664 - val_loss: 1.2370
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.7955 - val_accuracy: 0.4627 - val_loss: 1.3159
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6340 - loss: 0.9278 - val_accuracy: 0.6343 - val_loss: 1.5763
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6726 - loss: 0.8406 - val_accuracy: 0.5000 - val_loss: 0.8728
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6581 - loss: 0.8367 - val_accuracy: 0.7500 - val_loss: 0.5727
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6870 - loss: 0.8907 - val_accuracy: 0.7500 - val_loss: 0.5982
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6854 - loss: 0.8348 - val_accuracy: 0.7575 - val_loss: 0.5608
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6838 - loss: 0.8632 - val_accuracy: 0.7537 - val_loss: 0.5591
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6613 - loss: 0.8638 - val_accuracy: 0.7239 - val_loss: 0.5258
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.7188 - val_accuracy: 0.7164 - val_loss: 0.5622
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6742 - loss: 0.8486 - val_accuracy: 0.7500 - val_loss: 0.5088
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6822 - loss: 0.7950 - val_accuracy: 0.4590 - val_loss: 1.3786
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6709 - loss: 0.8910 - val_accuracy: 0.7201 - val_loss: 0.5391
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7036 - val_accuracy: 0.6194 - val_loss: 2.3610
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6677 - loss: 0.9483 - val_accuracy: 0.7052 - val_loss: 0.6675
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.7869 - val_accuracy: 0.6903 - val_loss: 0.6338
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6533 - loss: 0.9171 - val_accuracy: 0.6194 - val_loss: 1.7286
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.8031 - val_accuracy: 0.6978 - val_loss: 0.7477
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.8305 - val_accuracy: 0.7500 - val_loss: 0.5120
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6998 - loss: 0.8245 - val_accuracy: 0.7537 - val_loss: 0.5135
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7111 - loss: 0.7566 - val_accuracy: 0.4739 - val_loss: 1.0827
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.8229 - val_accuracy: 0.4552 - val_loss: 1.5633
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.7426 - val_accuracy: 0.4627 - val_loss: 1.6060
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.8662 - val_accuracy: 0.6754 - val_loss: 0.9807
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.8316 - val_accuracy: 0.6791 - val_loss: 0.8541
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.7822 - val_accuracy: 0.7090 - val_loss: 0.6056
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.7515 - val_accuracy: 0.7836 - val_loss: 0.5275
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7014 - loss: 0.7480 - val_accuracy: 0.6903 - val_loss: 0.8515
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6950 - loss: 0.8170 - val_accuracy: 0.7649 - val_loss: 0.4968
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.7833 - val_accuracy: 0.7799 - val_loss: 0.5028
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6644 - val_accuracy: 0.6343 - val_loss: 1.2825
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7340 - val_accuracy: 0.6231 - val_loss: 1.8297
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.8370 - val_accuracy: 0.7127 - val_loss: 0.6276
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6598 - val_accuracy: 0.5037 - val_loss: 0.9472
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.6990 - val_accuracy: 0.7799 - val_loss: 0.5179
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.7866 - val_accuracy: 0.4776 - val_loss: 1.3650
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7048 - val_accuracy: 0.4963 - val_loss: 0.9471
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7079 - loss: 0.7555 - val_accuracy: 0.7201 - val_loss: 0.5799
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6790 - loss: 0.7644 - val_accuracy: 0.7015 - val_loss: 0.6357
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7284 - val_accuracy: 0.7239 - val_loss: 0.5589
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.7216 - val_accuracy: 0.6381 - val_loss: 1.2725
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7239 - loss: 0.7683 - val_accuracy: 0.7164 - val_loss: 0.5609
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7127 - loss: 0.8065 - val_accuracy: 0.7500 - val_loss: 0.5045
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6982 - loss: 0.7874 - val_accuracy: 0.7761 - val_loss: 0.5297
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.7792 - val_accuracy: 0.7761 - val_loss: 0.5157
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.7492 - val_accuracy: 0.6642 - val_loss: 0.7125
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.7852 - val_accuracy: 0.7164 - val_loss: 0.6592
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.7192 - val_accuracy: 0.7239 - val_loss: 0.6585
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.6898 - val_accuracy: 0.6530 - val_loss: 0.9980
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6792 - val_accuracy: 0.7724 - val_loss: 0.5583
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6906 - val_accuracy: 0.7127 - val_loss: 0.7027
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.6361 - val_accuracy: 0.6418 - val_loss: 1.4048
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.7074 - val_accuracy: 0.4888 - val_loss: 1.1102
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7063 - loss: 0.7113 - val_accuracy: 0.6269 - val_loss: 1.6026
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.6066 - val_accuracy: 0.7575 - val_loss: 0.4993
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6852 - val_accuracy: 0.7351 - val_loss: 0.5426
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6635 - val_accuracy: 0.6754 - val_loss: 1.0114
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6722 - val_accuracy: 0.7761 - val_loss: 0.5856
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6984 - val_accuracy: 0.6231 - val_loss: 1.8664
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6900 - val_accuracy: 0.5896 - val_loss: 0.8311
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.6245 - val_accuracy: 0.7276 - val_loss: 0.6121
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7303 - loss: 0.8172 - val_accuracy: 0.7052 - val_loss: 0.6841
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6574 - val_accuracy: 0.7687 - val_loss: 0.5535
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7207 - loss: 0.7143 - val_accuracy: 0.7425 - val_loss: 0.5368
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6484 - val_accuracy: 0.5485 - val_loss: 0.9177
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6925 - val_accuracy: 0.7537 - val_loss: 0.5160
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.7551 - val_accuracy: 0.6716 - val_loss: 0.7338
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.7268 - val_accuracy: 0.7015 - val_loss: 0.7362
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.7044 - val_accuracy: 0.4739 - val_loss: 1.5557
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.7825 - val_accuracy: 0.7351 - val_loss: 0.5752
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.6448 - val_accuracy: 0.7313 - val_loss: 0.5696
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.7545 - val_accuracy: 0.7687 - val_loss: 0.5484
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6469 - val_accuracy: 0.7425 - val_loss: 0.5716
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7287 - loss: 0.6519 - val_accuracy: 0.6754 - val_loss: 0.7413
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.6590 - val_accuracy: 0.7761 - val_loss: 0.5612
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6516 - val_accuracy: 0.6903 - val_loss: 0.9078
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.6550 - val_accuracy: 0.7164 - val_loss: 0.6678
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6451 - val_accuracy: 0.7500 - val_loss: 0.5456
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.6142 - val_accuracy: 0.4366 - val_loss: 2.4502
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.7310 - val_accuracy: 0.6903 - val_loss: 0.7989
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.7004 - val_accuracy: 0.7687 - val_loss: 0.5436
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6436 - val_accuracy: 0.6866 - val_loss: 0.8411
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7352 - loss: 0.6511 - val_accuracy: 0.6530 - val_loss: 1.2382
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6407 - val_accuracy: 0.7687 - val_loss: 0.5356
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7271 - loss: 0.7253 - val_accuracy: 0.7164 - val_loss: 0.7065
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5603 - val_accuracy: 0.7239 - val_loss: 0.6577
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.5982 - val_accuracy: 0.5784 - val_loss: 0.8666
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6433 - val_accuracy: 0.5448 - val_loss: 0.9847
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6529 - val_accuracy: 0.7276 - val_loss: 0.6358
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.6693 - val_accuracy: 0.4403 - val_loss: 2.5027
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6206 - val_accuracy: 0.4888 - val_loss: 1.2261
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7464 - loss: 0.6535 - val_accuracy: 0.7761 - val_loss: 0.5666
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.6168 - val_accuracy: 0.7799 - val_loss: 0.5902
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7335 - loss: 0.6539 - val_accuracy: 0.7575 - val_loss: 0.5315
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.6462 - val_accuracy: 0.5149 - val_loss: 1.1150
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7496 - loss: 0.5907 - val_accuracy: 0.4925 - val_loss: 1.2242
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.6577 - val_accuracy: 0.7612 - val_loss: 0.5308
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5552 - val_accuracy: 0.7836 - val_loss: 0.5923
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7143 - loss: 0.7929 - val_accuracy: 0.7575 - val_loss: 0.5459
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7576 - loss: 0.5733 - val_accuracy: 0.6418 - val_loss: 0.8047
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.6023 - val_accuracy: 0.5709 - val_loss: 0.9179
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5950 - val_accuracy: 0.6791 - val_loss: 1.0233
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.6272 - val_accuracy: 0.7425 - val_loss: 0.5716
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7047 - loss: 0.7155 - val_accuracy: 0.7799 - val_loss: 0.5984
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7817 - loss: 0.5925 - val_accuracy: 0.7687 - val_loss: 0.5306
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6646 - val_accuracy: 0.7090 - val_loss: 0.7247
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6413 - val_accuracy: 0.7090 - val_loss: 0.7188
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7753 - loss: 0.6021 - val_accuracy: 0.6530 - val_loss: 1.0721
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.6549 - val_accuracy: 0.7201 - val_loss: 0.6950
Epoch 143/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7512 - loss: 0.5609 - val_accuracy: 0.6866 - val_loss: 1.0640
Epoch 144/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6027 - val_accuracy: 0.6679 - val_loss: 1.0236
Epoch 145/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5645 - val_accuracy: 0.7761 - val_loss: 0.6230
Epoch 146/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.6532 - val_accuracy: 0.6866 - val_loss: 1.0843
Epoch 147/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7432 - loss: 0.6048 - val_accuracy: 0.7687 - val_loss: 0.5356
Epoch 148/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5845 - val_accuracy: 0.6866 - val_loss: 0.8891
Epoch 149/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.6021 - val_accuracy: 0.7313 - val_loss: 0.6270
Epoch 150/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5400 - val_accuracy: 0.4776 - val_loss: 1.6006
Epoch 151/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.6428 - val_accuracy: 0.7612 - val_loss: 0.5873
Epoch 152/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.5478 - val_accuracy: 0.7724 - val_loss: 0.5537
Epoch 153/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7191 - loss: 0.6830 - val_accuracy: 0.7873 - val_loss: 0.5763
Epoch 154/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7592 - loss: 0.5503 - val_accuracy: 0.7425 - val_loss: 0.6435
Epoch 155/5000

wandb: Agent Starting Run: lpqfxk1i with config:
wandb: 	batch_size: 32
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.4880 - loss: 23.8447 - val_accuracy: 0.6306 - val_loss: 9.3592
Epoch 2/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 4.3002 - val_accuracy: 0.7127 - val_loss: 1.6162
Epoch 3/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 1.8779 - val_accuracy: 0.7127 - val_loss: 1.4424
Epoch 4/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 1.4530 - val_accuracy: 0.5634 - val_loss: 1.4645
Epoch 5/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 1.2225 - val_accuracy: 0.7015 - val_loss: 1.3005
Epoch 6/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.8730 - val_accuracy: 0.6866 - val_loss: 0.7916
Epoch 7/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6501 - loss: 0.7053 - val_accuracy: 0.6903 - val_loss: 0.6775
Epoch 8/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6783 - val_accuracy: 0.5746 - val_loss: 0.7493
Epoch 9/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6039 - val_accuracy: 0.4963 - val_loss: 0.8693
Epoch 10/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.7664 - val_accuracy: 0.6940 - val_loss: 0.7266
Epoch 11/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6458 - val_accuracy: 0.7276 - val_loss: 0.6335
Epoch 12/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5746 - val_accuracy: 0.6567 - val_loss: 0.8821
Epoch 13/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6806 - loss: 0.6545 - val_accuracy: 0.7463 - val_loss: 0.6006
Epoch 14/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7368 - loss: 0.5502 - val_accuracy: 0.7463 - val_loss: 0.5761
Epoch 15/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6918 - loss: 0.6523 - val_accuracy: 0.6978 - val_loss: 0.6452
Epoch 16/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7175 - loss: 0.5779 - val_accuracy: 0.6754 - val_loss: 0.6961
Epoch 17/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5743 - val_accuracy: 0.6716 - val_loss: 0.6919
Epoch 18/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7319 - loss: 0.5687 - val_accuracy: 0.6791 - val_loss: 0.6922
Epoch 19/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7384 - loss: 0.5333 - val_accuracy: 0.7799 - val_loss: 0.5420
Epoch 20/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5068 - val_accuracy: 0.7052 - val_loss: 0.6576
Epoch 21/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5104 - val_accuracy: 0.7313 - val_loss: 0.5617
Epoch 22/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.4869 - val_accuracy: 0.7687 - val_loss: 0.5416
Epoch 23/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5281 - val_accuracy: 0.7201 - val_loss: 0.6287
Epoch 24/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4884 - val_accuracy: 0.7724 - val_loss: 0.5250
Epoch 25/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5141 - val_accuracy: 0.7687 - val_loss: 0.5136
Epoch 26/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4880 - val_accuracy: 0.7948 - val_loss: 0.5102
Epoch 27/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4532 - val_accuracy: 0.7127 - val_loss: 0.6309
Epoch 28/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4738 - val_accuracy: 0.7090 - val_loss: 0.6478
Epoch 29/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5517 - val_accuracy: 0.7127 - val_loss: 0.6484
Epoch 30/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4777 - val_accuracy: 0.7799 - val_loss: 0.5253
Epoch 31/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4591 - val_accuracy: 0.7612 - val_loss: 0.5375
Epoch 32/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5222 - val_accuracy: 0.7351 - val_loss: 0.5788
Epoch 33/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4726 - val_accuracy: 0.7799 - val_loss: 0.5537
Epoch 34/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4503 - val_accuracy: 0.7575 - val_loss: 0.5429
Epoch 35/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4495 - val_accuracy: 0.7463 - val_loss: 0.5605
Epoch 36/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7624 - loss: 0.5129 - val_accuracy: 0.7500 - val_loss: 0.5669
Epoch 37/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5316 - val_accuracy: 0.7836 - val_loss: 0.5626
Epoch 38/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4882 - val_accuracy: 0.7575 - val_loss: 0.6451
Epoch 39/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.6063 - val_accuracy: 0.7575 - val_loss: 0.5542
Epoch 40/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7448 - loss: 0.6215 - val_accuracy: 0.7201 - val_loss: 0.7583
Epoch 41/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7159 - loss: 0.6915 - val_accuracy: 0.6866 - val_loss: 0.9577
Epoch 42/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5572 - val_accuracy: 0.7799 - val_loss: 0.5099
Epoch 43/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5514 - val_accuracy: 0.7500 - val_loss: 0.6058
Epoch 44/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.5020 - val_accuracy: 0.7463 - val_loss: 0.6068
Epoch 45/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5305 - val_accuracy: 0.7388 - val_loss: 0.6462
Epoch 46/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5084 - val_accuracy: 0.7799 - val_loss: 0.5232
Epoch 47/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4383 - val_accuracy: 0.6567 - val_loss: 0.7648
Epoch 48/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4899 - val_accuracy: 0.7724 - val_loss: 0.5319
Epoch 49/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4375 - val_accuracy: 0.7948 - val_loss: 0.5577
Epoch 50/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7673 - loss: 0.6522 - val_accuracy: 0.6940 - val_loss: 0.9822
Epoch 51/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.5095 - val_accuracy: 0.7910 - val_loss: 0.5898
Epoch 52/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4703 - val_accuracy: 0.7910 - val_loss: 0.5824
Epoch 53/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5188 - val_accuracy: 0.7836 - val_loss: 0.5718
Epoch 54/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.4557 - val_accuracy: 0.6642 - val_loss: 1.0361
Epoch 55/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.5456 - val_accuracy: 0.7799 - val_loss: 0.5161
Epoch 56/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5040 - val_accuracy: 0.7724 - val_loss: 0.6223
Epoch 57/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4494 - val_accuracy: 0.7873 - val_loss: 0.5722
Epoch 58/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4434 - val_accuracy: 0.7425 - val_loss: 0.6806
Epoch 59/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.5768 - val_accuracy: 0.7910 - val_loss: 0.5330
Epoch 60/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4773 - val_accuracy: 0.7276 - val_loss: 0.7305
Epoch 61/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.5305 - val_accuracy: 0.7910 - val_loss: 0.5479
Epoch 62/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4647 - val_accuracy: 0.6679 - val_loss: 0.7657
Epoch 63/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7416 - loss: 0.5947 - val_accuracy: 0.6828 - val_loss: 0.7655
Epoch 64/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7528 - loss: 0.5846 - val_accuracy: 0.6791 - val_loss: 1.2231
Epoch 65/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7255 - loss: 0.8540 - val_accuracy: 0.7761 - val_loss: 0.5571
Epoch 66/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7640 - loss: 0.6234 - val_accuracy: 0.7724 - val_loss: 0.6431
Epoch 67/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5277 - val_accuracy: 0.7388 - val_loss: 0.7238
Epoch 68/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4479 - val_accuracy: 0.6231 - val_loss: 0.8559
Epoch 69/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5667 - val_accuracy: 0.7463 - val_loss: 0.6705
Epoch 70/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7833 - loss: 0.5519 - val_accuracy: 0.7537 - val_loss: 0.6182
Epoch 71/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7560 - loss: 0.5614 - val_accuracy: 0.7836 - val_loss: 0.5376
Epoch 72/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7737 - loss: 0.5373 - val_accuracy: 0.7910 - val_loss: 0.5705
Epoch 73/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4369 - val_accuracy: 0.7351 - val_loss: 0.7379
Epoch 74/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5121 - val_accuracy: 0.7500 - val_loss: 0.6930
Epoch 75/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8234 - loss: 0.4506 - val_accuracy: 0.7724 - val_loss: 0.6056
Epoch 76/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4429 - val_accuracy: 0.7761 - val_loss: 0.5462
Epoch 77/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4737 - val_accuracy: 0.7873 - val_loss: 0.5544
Epoch 78/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4280 - val_accuracy: 0.7799 - val_loss: 0.6083
Epoch 79/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8250 - loss: 0.4229 - val_accuracy: 0.7799 - val_loss: 0.5566
Epoch 80/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8218 - loss: 0.4496 - val_accuracy: 0.7724 - val_loss: 0.5759
Epoch 81/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4819 - val_accuracy: 0.7761 - val_loss: 0.6662
Epoch 82/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4475 - val_accuracy: 0.7724 - val_loss: 0.5803
Epoch 83/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8186 - loss: 0.4312 - val_accuracy: 0.7873 - val_loss: 0.5464
Epoch 84/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.4608 - val_accuracy: 0.7910 - val_loss: 0.5727
Epoch 85/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.5195 - val_accuracy: 0.7836 - val_loss: 0.6252
Epoch 86/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4548 - val_accuracy: 0.7799 - val_loss: 0.5585
Epoch 87/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4562 - val_accuracy: 0.7910 - val_loss: 0.5850
Epoch 88/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4732 - val_accuracy: 0.7761 - val_loss: 0.6515
Epoch 89/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7689 - loss: 0.5788 - val_accuracy: 0.7687 - val_loss: 0.5916
Epoch 90/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7801 - loss: 0.5269 - val_accuracy: 0.7649 - val_loss: 0.5895
Epoch 91/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7721 - loss: 0.6034 - val_accuracy: 0.7649 - val_loss: 0.5901
Epoch 92/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7400 - loss: 0.6941 - val_accuracy: 0.6157 - val_loss: 0.8894
Epoch 93/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7978 - loss: 0.4777 - val_accuracy: 0.7910 - val_loss: 0.5692
Epoch 94/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4335 - val_accuracy: 0.7351 - val_loss: 0.6870
Epoch 95/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4694 - val_accuracy: 0.7239 - val_loss: 0.7291
Epoch 96/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.5003 - val_accuracy: 0.7836 - val_loss: 0.5467
Epoch 97/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8106 - loss: 0.4750 - val_accuracy: 0.7388 - val_loss: 0.6636
Epoch 98/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7994 - loss: 0.5055 - val_accuracy: 0.7985 - val_loss: 0.5650
Epoch 99/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7945 - loss: 0.5060 - val_accuracy: 0.7910 - val_loss: 0.5680
Epoch 100/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8234 - loss: 0.4301 - val_accuracy: 0.8022 - val_loss: 0.5921
Epoch 101/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4842 - val_accuracy: 0.7687 - val_loss: 0.5884
Epoch 102/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4967 - val_accuracy: 0.7537 - val_loss: 0.6247
Epoch 103/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4569 - val_accuracy: 0.7724 - val_loss: 0.5964
Epoch 104/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4610 - val_accuracy: 0.7761 - val_loss: 0.5685
Epoch 105/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4662 - val_accuracy: 0.7799 - val_loss: 0.6491
Epoch 106/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4814 - val_accuracy: 0.6754 - val_loss: 0.7843
Epoch 107/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4568 - val_accuracy: 0.7836 - val_loss: 0.5698
Epoch 108/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8154 - loss: 0.4524 - val_accuracy: 0.7537 - val_loss: 0.6214
Epoch 109/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5357 - val_accuracy: 0.7649 - val_loss: 0.5984
Epoch 110/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4657 - val_accuracy: 0.7799 - val_loss: 0.5651
Epoch 111/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4654 - val_accuracy: 0.7836 - val_loss: 0.5536
Epoch 112/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4572 - val_accuracy: 0.7873 - val_loss: 0.5782
Epoch 113/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4441 - val_accuracy: 0.7948 - val_loss: 0.5961
Epoch 114/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8090 - loss: 0.4359 - val_accuracy: 0.7351 - val_loss: 0.6869
Epoch 115/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7480 - loss: 0.5499 - val_accuracy: 0.7090 - val_loss: 0.8659
Epoch 116/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5296 - val_accuracy: 0.7761 - val_loss: 0.5853
Epoch 117/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8042 - loss: 0.4519 - val_accuracy: 0.7799 - val_loss: 0.5624
Epoch 118/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4398 - val_accuracy: 0.7873 - val_loss: 0.5618
Epoch 119/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8074 - loss: 0.4805 - val_accuracy: 0.7649 - val_loss: 0.6868
Epoch 120/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7865 - loss: 0.5281 - val_accuracy: 0.7687 - val_loss: 0.5770
Epoch 121/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8234 - loss: 0.4629 - val_accuracy: 0.7948 - val_loss: 0.5951
Epoch 122/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4393 - val_accuracy: 0.7948 - val_loss: 0.5960
Epoch 123/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4726 - val_accuracy: 0.7873 - val_loss: 0.5830
Epoch 124/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4368 - val_accuracy: 0.7910 - val_loss: 0.5881
Epoch 125/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4657 - val_accuracy: 0.7761 - val_loss: 0.6109
Epoch 126/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7705 - loss: 0.5747 - val_accuracy: 0.5896 - val_loss: 0.9511
Epoch 127/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7785 - loss: 0.5757 - val_accuracy: 0.7873 - val_loss: 0.5597
Epoch 128/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7769 - loss: 0.5510 - val_accuracy: 0.7836 - val_loss: 0.5832
Epoch 129/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8170 - loss: 0.4826 - val_accuracy: 0.7687 - val_loss: 0.6276
Epoch 130/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7929 - loss: 0.4780 - val_accuracy: 0.7836 - val_loss: 0.5987
Epoch 131/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4968 - val_accuracy: 0.7761 - val_loss: 0.5828
Epoch 132/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8138 - loss: 0.4402 - val_accuracy: 0.7761 - val_loss: 0.5758
Epoch 133/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8026 - loss: 0.5017 - val_accuracy: 0.7761 - val_loss: 0.5771
Epoch 134/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.5286 - val_accuracy: 0.7388 - val_loss: 0.6664
Epoch 135/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8122 - loss: 0.4235 - val_accuracy: 0.7948 - val_loss: 0.6068
Epoch 136/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8010 - loss: 0.4951 - val_accuracy: 0.7500 - val_loss: 0.6597
Epoch 137/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8218 - loss: 0.4650 - val_accuracy: 0.7388 - val_loss: 0.6677
Epoch 138/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7657 - loss: 0.5964 - val_accuracy: 0.7313 - val_loss: 0.7511
Epoch 139/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7913 - loss: 0.4881 - val_accuracy: 0.7910 - val_loss: 0.6308
Epoch 140/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7897 - loss: 0.5239 - val_accuracy: 0.7910 - val_loss: 0.5891
Epoch 141/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4716 - val_accuracy: 0.7724 - val_loss: 0.6704
Epoch 142/5000
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8234 - loss: 0.4558 - val_accuracy: 0.7948 - val_loss: 0.5970
Epoch 142: early stopping

wandb: Agent Starting Run: a70b180b with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5987 - loss: 64.6362 - val_accuracy: 0.6194 - val_loss: 0.9821
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.8060 - val_accuracy: 0.6119 - val_loss: 0.8156
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7536 - val_accuracy: 0.6119 - val_loss: 0.7492
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7227 - val_accuracy: 0.6119 - val_loss: 0.7020
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7003 - val_accuracy: 0.6157 - val_loss: 0.6837
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6881 - val_accuracy: 0.6343 - val_loss: 0.6783
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6855 - val_accuracy: 0.6306 - val_loss: 0.6783
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6808 - val_accuracy: 0.6194 - val_loss: 0.6782
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6798 - val_accuracy: 0.6119 - val_loss: 0.6860
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6776 - val_accuracy: 0.6269 - val_loss: 0.6745
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6750 - val_accuracy: 0.6119 - val_loss: 0.6838
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6748 - val_accuracy: 0.6231 - val_loss: 0.6818
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6736 - val_accuracy: 0.6231 - val_loss: 0.6816
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6732 - val_accuracy: 0.6269 - val_loss: 0.6801
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6723 - val_accuracy: 0.6269 - val_loss: 0.6807
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6715 - val_accuracy: 0.6269 - val_loss: 0.6754
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6715 - val_accuracy: 0.6269 - val_loss: 0.6811
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6704 - val_accuracy: 0.6306 - val_loss: 0.6854
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6702 - val_accuracy: 0.6306 - val_loss: 0.6879
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6695 - val_accuracy: 0.6306 - val_loss: 0.6852
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6703 - val_accuracy: 0.6269 - val_loss: 0.6784
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6695 - val_accuracy: 0.6306 - val_loss: 0.6873
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6306 - val_loss: 0.6892
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6681 - val_accuracy: 0.6306 - val_loss: 0.6886
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6894
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6677 - val_accuracy: 0.6306 - val_loss: 0.6897
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6672 - val_accuracy: 0.6306 - val_loss: 0.6945
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6988
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6306 - val_loss: 0.6945
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6269 - val_loss: 0.6993
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6665 - val_accuracy: 0.6269 - val_loss: 0.7030
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.7018
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6664 - val_accuracy: 0.6269 - val_loss: 0.7016
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.6306 - val_loss: 0.7000
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7098
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.7100
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.7097
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.7088
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.7081
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7038
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.7034
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7115
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.7108
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7210
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7172
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.7130
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6655 - val_accuracy: 0.6269 - val_loss: 0.7158
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.7174
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.7235
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6269 - val_loss: 0.7263
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7207
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7208
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.7284
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7271
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7242
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.7268
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.7261
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7255
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7260
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.7273
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7303
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7326
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6652 - val_accuracy: 0.6269 - val_loss: 0.7239
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7272
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.7263
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7312
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7306
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7254
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7309
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7308
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.7243
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.7286
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7304
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.7309
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.7351
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7332
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.7388
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7375
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.7318
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7382
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7340
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7357
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.7345
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7427
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7386
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7398
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7416
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7434
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.7411
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6269 - val_loss: 0.7420
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.7433
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.7454
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7457
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6640 - val_accuracy: 0.6269 - val_loss: 0.7420
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7430
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7474
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7422
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.7506
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7526
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7561
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7617
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6643 - val_accuracy: 0.6269 - val_loss: 0.7559
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7544
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6637 - val_accuracy: 0.6269 - val_loss: 0.7547
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.7537
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.7533
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7612
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7644
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6640 - val_accuracy: 0.6231 - val_loss: 0.7704
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6642 - val_accuracy: 0.6269 - val_loss: 0.7615
Epoch 110: early stopping

wandb: Agent Starting Run: wupyg5h5 with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6116 - loss: 77.9809 - val_accuracy: 0.6269 - val_loss: 69.7225
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 67.7587 - val_accuracy: 0.6231 - val_loss: 62.3506
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 60.8685 - val_accuracy: 0.6231 - val_loss: 56.1406
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 55.0806 - val_accuracy: 0.6269 - val_loss: 50.8408
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 49.9169 - val_accuracy: 0.6194 - val_loss: 46.0076
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 45.1915 - val_accuracy: 0.6119 - val_loss: 41.6669
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 40.8136 - val_accuracy: 0.6045 - val_loss: 37.4746
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 36.6929 - val_accuracy: 0.6082 - val_loss: 33.6619
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 32.9877 - val_accuracy: 0.6119 - val_loss: 30.2619
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 29.5540 - val_accuracy: 0.6119 - val_loss: 27.0038
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 26.3067 - val_accuracy: 0.6007 - val_loss: 23.9673
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 23.3182 - val_accuracy: 0.6045 - val_loss: 21.2135
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 20.6077 - val_accuracy: 0.6119 - val_loss: 18.7326
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 18.1162 - val_accuracy: 0.6082 - val_loss: 16.4466
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 15.8585 - val_accuracy: 0.6119 - val_loss: 14.3249
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 13.7550 - val_accuracy: 0.6157 - val_loss: 12.4165
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 11.8711 - val_accuracy: 0.6231 - val_loss: 10.6814
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6019 - loss: 10.2228 - val_accuracy: 0.6231 - val_loss: 9.2167
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 8.8016 - val_accuracy: 0.6082 - val_loss: 7.9333
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6035 - loss: 7.5699 - val_accuracy: 0.6119 - val_loss: 6.7762
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5923 - loss: 6.4397 - val_accuracy: 0.6045 - val_loss: 5.7086
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 5.4039 - val_accuracy: 0.6045 - val_loss: 4.7656
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 4.4452 - val_accuracy: 0.6045 - val_loss: 3.8822
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5811 - loss: 3.6083 - val_accuracy: 0.6045 - val_loss: 3.1638
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5827 - loss: 2.9133 - val_accuracy: 0.5896 - val_loss: 2.5488
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5778 - loss: 2.3309 - val_accuracy: 0.5896 - val_loss: 2.0395
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 1.8448 - val_accuracy: 0.5821 - val_loss: 1.6221
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5714 - loss: 1.4547 - val_accuracy: 0.5746 - val_loss: 1.2745
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5811 - loss: 1.1483 - val_accuracy: 0.5896 - val_loss: 1.0330
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5506 - loss: 0.9388 - val_accuracy: 0.5522 - val_loss: 0.8745
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5441 - loss: 0.8119 - val_accuracy: 0.5485 - val_loss: 0.7894
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5136 - loss: 0.7492 - val_accuracy: 0.4963 - val_loss: 0.7491
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4831 - loss: 0.7202 - val_accuracy: 0.5075 - val_loss: 0.7306
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4992 - loss: 0.7074 - val_accuracy: 0.4888 - val_loss: 0.7186
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4992 - loss: 0.6978 - val_accuracy: 0.4925 - val_loss: 0.7109
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5120 - loss: 0.6943 - val_accuracy: 0.4851 - val_loss: 0.7065
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5233 - loss: 0.6929 - val_accuracy: 0.4963 - val_loss: 0.7039
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5329 - loss: 0.6898 - val_accuracy: 0.5336 - val_loss: 0.7012
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5265 - loss: 0.6903 - val_accuracy: 0.5485 - val_loss: 0.6990
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5441 - loss: 0.6863 - val_accuracy: 0.5821 - val_loss: 0.6965
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5522 - loss: 0.6832 - val_accuracy: 0.5896 - val_loss: 0.6933
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5762 - loss: 0.6845 - val_accuracy: 0.6007 - val_loss: 0.6917
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 0.6811 - val_accuracy: 0.6045 - val_loss: 0.6863
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 0.6798 - val_accuracy: 0.6157 - val_loss: 0.6842
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 0.6792 - val_accuracy: 0.6194 - val_loss: 0.6838
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5923 - loss: 0.6793 - val_accuracy: 0.6194 - val_loss: 0.6813
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5939 - loss: 0.6781 - val_accuracy: 0.6194 - val_loss: 0.6802
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 0.6736 - val_accuracy: 0.6231 - val_loss: 0.6780
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 0.6738 - val_accuracy: 0.6194 - val_loss: 0.6752
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 0.6727 - val_accuracy: 0.6269 - val_loss: 0.6740
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5923 - loss: 0.6697 - val_accuracy: 0.6269 - val_loss: 0.6717
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5955 - loss: 0.6703 - val_accuracy: 0.6269 - val_loss: 0.6711
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 0.6673 - val_accuracy: 0.6269 - val_loss: 0.6680
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6652
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6659 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6003 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.6608
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6616 - val_accuracy: 0.6306 - val_loss: 0.6592
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.6569
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6035 - loss: 0.6552 - val_accuracy: 0.6269 - val_loss: 0.6578
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6579 - val_accuracy: 0.6231 - val_loss: 0.6530
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6556 - val_accuracy: 0.6269 - val_loss: 0.6499
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6544 - val_accuracy: 0.6381 - val_loss: 0.6500
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6518 - val_accuracy: 0.6381 - val_loss: 0.6468
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6506 - val_accuracy: 0.6418 - val_loss: 0.6438
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6492 - val_accuracy: 0.6381 - val_loss: 0.6418
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6489 - val_accuracy: 0.6343 - val_loss: 0.6426
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6475 - val_accuracy: 0.6343 - val_loss: 0.6396
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6462 - val_accuracy: 0.6381 - val_loss: 0.6381
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6470 - val_accuracy: 0.6343 - val_loss: 0.6361
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6452 - val_accuracy: 0.6343 - val_loss: 0.6360
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6441 - val_accuracy: 0.6343 - val_loss: 0.6360
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6418 - val_accuracy: 0.6343 - val_loss: 0.6352
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6430 - val_accuracy: 0.6306 - val_loss: 0.6336
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6416 - val_accuracy: 0.6381 - val_loss: 0.6319
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6407 - val_accuracy: 0.6418 - val_loss: 0.6311
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6388 - val_accuracy: 0.6418 - val_loss: 0.6291
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6390 - val_accuracy: 0.6493 - val_loss: 0.6282
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6373 - val_accuracy: 0.6418 - val_loss: 0.6276
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6349 - val_accuracy: 0.6493 - val_loss: 0.6263
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.6346 - val_accuracy: 0.6418 - val_loss: 0.6246
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6336 - val_accuracy: 0.6455 - val_loss: 0.6240
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6337 - val_accuracy: 0.6418 - val_loss: 0.6256
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6322 - val_accuracy: 0.6493 - val_loss: 0.6239
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6306 - val_accuracy: 0.6455 - val_loss: 0.6223
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6295 - val_accuracy: 0.6455 - val_loss: 0.6224
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6303 - val_accuracy: 0.6455 - val_loss: 0.6189
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6270 - val_accuracy: 0.6455 - val_loss: 0.6178
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6256 - val_accuracy: 0.6493 - val_loss: 0.6189
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6253 - val_accuracy: 0.6493 - val_loss: 0.6176
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6263 - val_accuracy: 0.6418 - val_loss: 0.6176
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.6238 - val_accuracy: 0.6455 - val_loss: 0.6143
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6255 - val_accuracy: 0.6455 - val_loss: 0.6138
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6208 - val_accuracy: 0.6455 - val_loss: 0.6125
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.6205 - val_accuracy: 0.6455 - val_loss: 0.6114
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.6192 - val_accuracy: 0.6530 - val_loss: 0.6105
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6191 - val_accuracy: 0.6493 - val_loss: 0.6080
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6187 - val_accuracy: 0.6493 - val_loss: 0.6085
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.6179 - val_accuracy: 0.6493 - val_loss: 0.6093
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6149 - val_accuracy: 0.6530 - val_loss: 0.6064
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.6154 - val_accuracy: 0.6530 - val_loss: 0.6039
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6148 - val_accuracy: 0.6530 - val_loss: 0.6007
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6112 - val_accuracy: 0.6493 - val_loss: 0.6006
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.6132 - val_accuracy: 0.6493 - val_loss: 0.5983
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6107 - val_accuracy: 0.6530 - val_loss: 0.5971
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6080 - val_accuracy: 0.6530 - val_loss: 0.5949
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6093 - val_accuracy: 0.6530 - val_loss: 0.5960
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6071 - val_accuracy: 0.6567 - val_loss: 0.5953
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6041 - val_accuracy: 0.6530 - val_loss: 0.5938
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6083 - val_accuracy: 0.6530 - val_loss: 0.5929
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6045 - val_accuracy: 0.6567 - val_loss: 0.5906
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6030 - val_accuracy: 0.6567 - val_loss: 0.5931
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6021 - val_accuracy: 0.6493 - val_loss: 0.5910
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6022 - val_accuracy: 0.6567 - val_loss: 0.5930
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6012 - val_accuracy: 0.6567 - val_loss: 0.5895
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6027 - val_accuracy: 0.6567 - val_loss: 0.5887
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.5985 - val_accuracy: 0.6493 - val_loss: 0.5893
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.5998 - val_accuracy: 0.6455 - val_loss: 0.5858
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.5984 - val_accuracy: 0.6455 - val_loss: 0.5874
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.5986 - val_accuracy: 0.6530 - val_loss: 0.5836
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.5994 - val_accuracy: 0.6530 - val_loss: 0.5828
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.5986 - val_accuracy: 0.6493 - val_loss: 0.5830
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.5964 - val_accuracy: 0.6493 - val_loss: 0.5828
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.5965 - val_accuracy: 0.6493 - val_loss: 0.5822
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5926 - val_accuracy: 0.6530 - val_loss: 0.5921
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5956 - val_accuracy: 0.6493 - val_loss: 0.5821
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5931 - val_accuracy: 0.6567 - val_loss: 0.5793
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5956 - val_accuracy: 0.6493 - val_loss: 0.5783
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5927 - val_accuracy: 0.6567 - val_loss: 0.5797
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5921 - val_accuracy: 0.6530 - val_loss: 0.5783
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5911 - val_accuracy: 0.6530 - val_loss: 0.5789
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5917 - val_accuracy: 0.6530 - val_loss: 0.5823
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5876 - val_accuracy: 0.6530 - val_loss: 0.5780
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.5919 - val_accuracy: 0.6530 - val_loss: 0.5778
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5877 - val_accuracy: 0.6530 - val_loss: 0.5767
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.5883 - val_accuracy: 0.6530 - val_loss: 0.5780
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.5880 - val_accuracy: 0.6530 - val_loss: 0.5754
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5871 - val_accuracy: 0.6493 - val_loss: 0.5765
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.5887 - val_accuracy: 0.6530 - val_loss: 0.5770
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.5835 - val_accuracy: 0.6493 - val_loss: 0.5822
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5886 - val_accuracy: 0.6530 - val_loss: 0.5746
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5861 - val_accuracy: 0.6530 - val_loss: 0.5743
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.5855 - val_accuracy: 0.6530 - val_loss: 0.5765
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.5866 - val_accuracy: 0.6493 - val_loss: 0.5759
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.5868 - val_accuracy: 0.6530 - val_loss: 0.5767
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5833 - val_accuracy: 0.6493 - val_loss: 0.5752
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.5827 - val_accuracy: 0.6530 - val_loss: 0.5748
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.5836 - val_accuracy: 0.6493 - val_loss: 0.5753
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.5859 - val_accuracy: 0.6604 - val_loss: 0.5746
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.5812 - val_accuracy: 0.6604 - val_loss: 0.5771
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.5819 - val_accuracy: 0.6493 - val_loss: 0.5748
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.5824 - val_accuracy: 0.6828 - val_loss: 0.5864
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.5817 - val_accuracy: 0.6828 - val_loss: 0.5800
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.5820 - val_accuracy: 0.6791 - val_loss: 0.5749
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.5799 - val_accuracy: 0.6828 - val_loss: 0.5760
Epoch 155/5000

wandb: Agent Starting Run: t0lpuqph with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4157 - loss: 1.2836 - val_accuracy: 0.3694 - val_loss: 1.2660
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4607 - loss: 1.1316 - val_accuracy: 0.4403 - val_loss: 1.1566
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4446 - loss: 1.0562 - val_accuracy: 0.4627 - val_loss: 1.0754
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4591 - loss: 0.9892 - val_accuracy: 0.5000 - val_loss: 1.0077
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4864 - loss: 0.9284 - val_accuracy: 0.4701 - val_loss: 0.9539
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4703 - loss: 0.8803 - val_accuracy: 0.5448 - val_loss: 0.8979
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5201 - loss: 0.8492 - val_accuracy: 0.4925 - val_loss: 0.8559
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5217 - loss: 0.7912 - val_accuracy: 0.5746 - val_loss: 0.7977
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5746 - loss: 0.7624 - val_accuracy: 0.5821 - val_loss: 0.7584
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5907 - loss: 0.7202 - val_accuracy: 0.6119 - val_loss: 0.7247
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5971 - loss: 0.7012 - val_accuracy: 0.6269 - val_loss: 0.7135
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.7011 - val_accuracy: 0.6269 - val_loss: 0.7088
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 0.6888 - val_accuracy: 0.6231 - val_loss: 0.7042
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6865 - val_accuracy: 0.6082 - val_loss: 0.7014
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6851 - val_accuracy: 0.6269 - val_loss: 0.7015
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6803 - val_accuracy: 0.6231 - val_loss: 0.6939
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6735 - val_accuracy: 0.6231 - val_loss: 0.6902
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6703 - val_accuracy: 0.6157 - val_loss: 0.6888
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.6747 - val_accuracy: 0.6455 - val_loss: 0.6973
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6699 - val_accuracy: 0.6381 - val_loss: 0.6812
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6630 - val_accuracy: 0.6455 - val_loss: 0.6816
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.6577 - val_accuracy: 0.6269 - val_loss: 0.6775
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6573 - val_accuracy: 0.6493 - val_loss: 0.6761
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.6576 - val_accuracy: 0.6306 - val_loss: 0.6744
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6567 - val_loss: 0.6723
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6562 - val_accuracy: 0.6642 - val_loss: 0.6670
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6487 - val_accuracy: 0.6530 - val_loss: 0.6645
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6475 - val_accuracy: 0.6418 - val_loss: 0.6614
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6471 - val_accuracy: 0.6455 - val_loss: 0.6601
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6434 - val_accuracy: 0.6642 - val_loss: 0.6601
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.6513 - val_accuracy: 0.6567 - val_loss: 0.6604
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6493 - val_accuracy: 0.6604 - val_loss: 0.6563
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6424 - val_accuracy: 0.6679 - val_loss: 0.6609
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6424 - val_accuracy: 0.6567 - val_loss: 0.6556
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.6421 - val_accuracy: 0.6679 - val_loss: 0.6502
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6413 - val_accuracy: 0.6567 - val_loss: 0.6484
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6430 - val_accuracy: 0.6642 - val_loss: 0.6459
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6380 - val_accuracy: 0.6679 - val_loss: 0.6449
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6397 - val_accuracy: 0.6604 - val_loss: 0.6446
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6382 - val_accuracy: 0.6679 - val_loss: 0.6403
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6374 - val_accuracy: 0.6866 - val_loss: 0.6421
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6438 - val_accuracy: 0.6716 - val_loss: 0.6465
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6368 - val_accuracy: 0.6828 - val_loss: 0.6401
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6377 - val_accuracy: 0.6754 - val_loss: 0.6424
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6395 - val_accuracy: 0.6716 - val_loss: 0.6463
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6406 - val_accuracy: 0.6828 - val_loss: 0.6367
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6320 - val_accuracy: 0.6716 - val_loss: 0.6341
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6347 - val_accuracy: 0.6679 - val_loss: 0.6358
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6413 - val_accuracy: 0.6642 - val_loss: 0.6484
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6376 - val_accuracy: 0.6866 - val_loss: 0.6482
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6343 - val_accuracy: 0.6791 - val_loss: 0.6333
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6385 - val_accuracy: 0.6791 - val_loss: 0.6381
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6320 - val_accuracy: 0.6679 - val_loss: 0.6292
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6276 - val_accuracy: 0.6716 - val_loss: 0.6287
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6295 - val_accuracy: 0.6754 - val_loss: 0.6280
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6290 - val_accuracy: 0.6866 - val_loss: 0.6299
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6284 - val_accuracy: 0.6791 - val_loss: 0.6268
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6256 - val_accuracy: 0.6866 - val_loss: 0.6299
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6268 - val_accuracy: 0.6866 - val_loss: 0.6284
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6239 - val_accuracy: 0.6903 - val_loss: 0.6286
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6270 - val_accuracy: 0.6716 - val_loss: 0.6300
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6302 - val_accuracy: 0.6679 - val_loss: 0.6405
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6226 - val_accuracy: 0.6866 - val_loss: 0.6338
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.6292 - val_accuracy: 0.6828 - val_loss: 0.6313
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6206 - val_accuracy: 0.6828 - val_loss: 0.6252
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6197 - val_accuracy: 0.6791 - val_loss: 0.6315
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6298 - val_accuracy: 0.6754 - val_loss: 0.6315
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6250 - val_accuracy: 0.6828 - val_loss: 0.6243
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6219 - val_accuracy: 0.6754 - val_loss: 0.6236
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6182 - val_accuracy: 0.6866 - val_loss: 0.6259
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6175 - val_accuracy: 0.6866 - val_loss: 0.6229
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6195 - val_accuracy: 0.6828 - val_loss: 0.6226
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6233 - val_accuracy: 0.6791 - val_loss: 0.6316
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6270 - val_accuracy: 0.6754 - val_loss: 0.6227
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6247 - val_accuracy: 0.6903 - val_loss: 0.6196
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6193 - val_accuracy: 0.6903 - val_loss: 0.6193
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6132 - val_accuracy: 0.6903 - val_loss: 0.6191
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6166 - val_accuracy: 0.6903 - val_loss: 0.6183
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6174 - val_accuracy: 0.6828 - val_loss: 0.6275
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6169 - val_accuracy: 0.6754 - val_loss: 0.6229
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6181 - val_accuracy: 0.6940 - val_loss: 0.6166
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6126 - val_accuracy: 0.6903 - val_loss: 0.6158
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6197 - val_accuracy: 0.6791 - val_loss: 0.6291
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6154 - val_accuracy: 0.6791 - val_loss: 0.6229
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6120 - val_accuracy: 0.6940 - val_loss: 0.6184
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6134 - val_accuracy: 0.6940 - val_loss: 0.6149
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6120 - val_accuracy: 0.6866 - val_loss: 0.6183
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6342 - val_accuracy: 0.6679 - val_loss: 0.6401
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6211 - val_accuracy: 0.6903 - val_loss: 0.6160
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6128 - val_accuracy: 0.6903 - val_loss: 0.6146
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6082 - val_accuracy: 0.6866 - val_loss: 0.6104
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6098 - val_accuracy: 0.6903 - val_loss: 0.6090
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6141 - val_accuracy: 0.6903 - val_loss: 0.6149
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6062 - val_accuracy: 0.6903 - val_loss: 0.6114
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6055 - val_accuracy: 0.6903 - val_loss: 0.6109
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6067 - val_accuracy: 0.6903 - val_loss: 0.6106
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6059 - val_accuracy: 0.6903 - val_loss: 0.6095
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6035 - val_accuracy: 0.6903 - val_loss: 0.6101
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.6035 - val_accuracy: 0.6903 - val_loss: 0.6099
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6047 - val_accuracy: 0.6903 - val_loss: 0.6081
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6110 - val_accuracy: 0.6866 - val_loss: 0.6212
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6074 - val_accuracy: 0.6903 - val_loss: 0.6086
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6028 - val_accuracy: 0.6903 - val_loss: 0.6084
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6039 - val_accuracy: 0.6978 - val_loss: 0.6122
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6043 - val_accuracy: 0.6866 - val_loss: 0.6139
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6124 - val_accuracy: 0.6940 - val_loss: 0.6167
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5999 - val_accuracy: 0.6940 - val_loss: 0.6093
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5989 - val_accuracy: 0.6903 - val_loss: 0.6083
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.5981 - val_accuracy: 0.6940 - val_loss: 0.6081
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5978 - val_accuracy: 0.6903 - val_loss: 0.6073
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.5996 - val_accuracy: 0.6903 - val_loss: 0.6062
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.5977 - val_accuracy: 0.6903 - val_loss: 0.6087
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5983 - val_accuracy: 0.6940 - val_loss: 0.6089
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.5978 - val_accuracy: 0.6940 - val_loss: 0.6068
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5956 - val_accuracy: 0.6978 - val_loss: 0.6102
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5944 - val_accuracy: 0.6978 - val_loss: 0.6113
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6043 - val_accuracy: 0.6866 - val_loss: 0.6190
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5926 - val_accuracy: 0.6978 - val_loss: 0.6149
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6009 - val_accuracy: 0.6940 - val_loss: 0.6102
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5958 - val_accuracy: 0.6903 - val_loss: 0.6068
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.5927 - val_accuracy: 0.6903 - val_loss: 0.6068
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.5916 - val_accuracy: 0.6866 - val_loss: 0.6056
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5949 - val_accuracy: 0.6903 - val_loss: 0.6063
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5919 - val_accuracy: 0.6903 - val_loss: 0.6047
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5909 - val_accuracy: 0.6903 - val_loss: 0.6038
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5935 - val_accuracy: 0.6903 - val_loss: 0.6022
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5950 - val_accuracy: 0.6978 - val_loss: 0.6072
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5927 - val_accuracy: 0.6940 - val_loss: 0.6028
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5886 - val_accuracy: 0.6940 - val_loss: 0.6081
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5899 - val_accuracy: 0.6940 - val_loss: 0.6005
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.5880 - val_accuracy: 0.6903 - val_loss: 0.6005
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5906 - val_accuracy: 0.6940 - val_loss: 0.6042
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5862 - val_accuracy: 0.6978 - val_loss: 0.6026
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5850 - val_accuracy: 0.6940 - val_loss: 0.6019
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5887 - val_accuracy: 0.6940 - val_loss: 0.5962
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5841 - val_accuracy: 0.6940 - val_loss: 0.5958
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5857 - val_accuracy: 0.6978 - val_loss: 0.5955
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5860 - val_accuracy: 0.6940 - val_loss: 0.5963
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5902 - val_accuracy: 0.7052 - val_loss: 0.6002
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5844 - val_accuracy: 0.6791 - val_loss: 0.6145
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5871 - val_accuracy: 0.7239 - val_loss: 0.6048
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5882 - val_accuracy: 0.6940 - val_loss: 0.5968
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5845 - val_accuracy: 0.6940 - val_loss: 0.5960
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.5807 - val_accuracy: 0.6940 - val_loss: 0.5941
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7143 - loss: 0.5795 - val_accuracy: 0.6940 - val_loss: 0.5978
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5790 - val_accuracy: 0.6940 - val_loss: 0.5927
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5788 - val_accuracy: 0.6940 - val_loss: 0.5925
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5778 - val_accuracy: 0.6940 - val_loss: 0.5929
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5814 - val_accuracy: 0.6940 - val_loss: 0.5923
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5771 - val_accuracy: 0.6940 - val_loss: 0.5923
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5781 - val_accuracy: 0.6940 - val_loss: 0.5898
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5764 - val_accuracy: 0.6978 - val_loss: 0.5898
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5782 - val_accuracy: 0.6978 - val_loss: 0.5947
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5774 - val_accuracy: 0.6940 - val_loss: 0.5869
Epoch 155/5000

wandb: Agent Starting Run: dnmrvald with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5778 - loss: 10.8878 - val_accuracy: 0.6194 - val_loss: 0.7273
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7135 - val_accuracy: 0.6194 - val_loss: 0.7153
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.7041 - val_accuracy: 0.6194 - val_loss: 0.7051
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6958 - val_accuracy: 0.6194 - val_loss: 0.6976
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6928 - val_accuracy: 0.6194 - val_loss: 0.6952
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6912 - val_accuracy: 0.6231 - val_loss: 0.6928
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6897 - val_accuracy: 0.6231 - val_loss: 0.6911
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6885 - val_accuracy: 0.6231 - val_loss: 0.6895
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6872 - val_accuracy: 0.6194 - val_loss: 0.6879
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6859 - val_accuracy: 0.6231 - val_loss: 0.6864
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6848 - val_accuracy: 0.6231 - val_loss: 0.6845
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6836 - val_accuracy: 0.6231 - val_loss: 0.6830
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6826 - val_accuracy: 0.6231 - val_loss: 0.6828
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6817 - val_accuracy: 0.6231 - val_loss: 0.6824
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6809 - val_accuracy: 0.6231 - val_loss: 0.6810
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6802 - val_accuracy: 0.6269 - val_loss: 0.6797
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6793 - val_accuracy: 0.6231 - val_loss: 0.6793
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6786 - val_accuracy: 0.6231 - val_loss: 0.6786
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6781 - val_accuracy: 0.6269 - val_loss: 0.6782
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6773 - val_accuracy: 0.6269 - val_loss: 0.6774
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6766 - val_accuracy: 0.6269 - val_loss: 0.6768
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6760 - val_accuracy: 0.6269 - val_loss: 0.6763
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6755 - val_accuracy: 0.6269 - val_loss: 0.6764
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6750 - val_accuracy: 0.6231 - val_loss: 0.6755
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6745 - val_accuracy: 0.6269 - val_loss: 0.6745
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6740 - val_accuracy: 0.6269 - val_loss: 0.6742
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6735 - val_accuracy: 0.6231 - val_loss: 0.6745
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6732 - val_accuracy: 0.6231 - val_loss: 0.6737
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6727 - val_accuracy: 0.6231 - val_loss: 0.6734
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6723 - val_accuracy: 0.6269 - val_loss: 0.6730
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6719 - val_accuracy: 0.6269 - val_loss: 0.6727
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6714 - val_accuracy: 0.6269 - val_loss: 0.6725
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6711 - val_accuracy: 0.6269 - val_loss: 0.6721
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6708 - val_accuracy: 0.6269 - val_loss: 0.6721
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6702 - val_accuracy: 0.6269 - val_loss: 0.6726
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6700 - val_accuracy: 0.6269 - val_loss: 0.6727
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6696 - val_accuracy: 0.6194 - val_loss: 0.6731
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6694 - val_accuracy: 0.6157 - val_loss: 0.6734
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6691 - val_accuracy: 0.6194 - val_loss: 0.6727
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6688 - val_accuracy: 0.6157 - val_loss: 0.6725
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6686 - val_accuracy: 0.6194 - val_loss: 0.6719
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6683 - val_accuracy: 0.6194 - val_loss: 0.6716
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6682 - val_accuracy: 0.6231 - val_loss: 0.6708
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6678 - val_accuracy: 0.6194 - val_loss: 0.6718
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6678 - val_accuracy: 0.6194 - val_loss: 0.6718
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6194 - val_loss: 0.6715
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6674 - val_accuracy: 0.6194 - val_loss: 0.6711
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6673 - val_accuracy: 0.6194 - val_loss: 0.6707
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6194 - val_loss: 0.6706
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6194 - val_loss: 0.6702
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6194 - val_loss: 0.6699
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6666 - val_accuracy: 0.6231 - val_loss: 0.6697
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6664 - val_accuracy: 0.6231 - val_loss: 0.6694
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6691
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6231 - val_loss: 0.6689
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.6688
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6690
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6686
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6687
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6231 - val_loss: 0.6688
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6684
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6654 - val_accuracy: 0.6231 - val_loss: 0.6684
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6684
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6231 - val_loss: 0.6687
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6652 - val_accuracy: 0.6231 - val_loss: 0.6683
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6231 - val_loss: 0.6683
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6682
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6683
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6651 - val_accuracy: 0.6194 - val_loss: 0.6680
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6648 - val_accuracy: 0.6231 - val_loss: 0.6681
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6682
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6231 - val_loss: 0.6685
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6648 - val_accuracy: 0.6231 - val_loss: 0.6681
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6194 - val_loss: 0.6680
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6194 - val_loss: 0.6677
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.6678
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.6680
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6682
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6682
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6643 - val_accuracy: 0.6194 - val_loss: 0.6685
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 0.7131 - val_accuracy: 0.6269 - val_loss: 0.6658
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6676 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6674 - val_accuracy: 0.6269 - val_loss: 0.6653
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6673 - val_accuracy: 0.6269 - val_loss: 0.6651
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6269 - val_loss: 0.6650
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6672 - val_accuracy: 0.6269 - val_loss: 0.6648
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6671 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6671 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6646
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6670 - val_accuracy: 0.6306 - val_loss: 0.6645
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6644
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6306 - val_loss: 0.6642
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6667 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6637
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6637
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6636
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6635
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6636
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6636
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6637
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6637
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6661 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6639
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6640
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6641
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6642
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6306 - val_loss: 0.6643
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6269 - val_loss: 0.6644
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6659 - val_accuracy: 0.6269 - val_loss: 0.6644
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6645
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6645
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6646
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6648
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6649
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6650
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6650
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6651
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6653
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6653
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6654
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6656
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6656
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6657
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6657 - val_accuracy: 0.6269 - val_loss: 0.6657
Epoch 155/5000

wandb: Agent Starting Run: 5f1f2wlj with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3884 - loss: 60.3667 - val_accuracy: 0.3731 - val_loss: 48.1132
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3884 - loss: 42.6717 - val_accuracy: 0.3731 - val_loss: 34.1274
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3884 - loss: 29.4801 - val_accuracy: 0.3731 - val_loss: 21.9944
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3884 - loss: 17.2565 - val_accuracy: 0.3731 - val_loss: 10.1270
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4478 - loss: 5.8484 - val_accuracy: 0.6231 - val_loss: 2.2582
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 2.2480 - val_accuracy: 0.6269 - val_loss: 2.0124
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 2.0479 - val_accuracy: 0.6754 - val_loss: 1.8586
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 1.8360 - val_accuracy: 0.5634 - val_loss: 1.7630
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 1.6393 - val_accuracy: 0.5373 - val_loss: 1.7559
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 1.5937 - val_accuracy: 0.6082 - val_loss: 1.3515
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5939 - loss: 1.4807 - val_accuracy: 0.6418 - val_loss: 1.2415
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 1.4055 - val_accuracy: 0.6604 - val_loss: 1.1447
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5971 - loss: 1.2517 - val_accuracy: 0.6828 - val_loss: 1.0751
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5827 - loss: 1.2378 - val_accuracy: 0.7052 - val_loss: 1.0579
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 1.1478 - val_accuracy: 0.6903 - val_loss: 0.9220
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 1.1528 - val_accuracy: 0.7201 - val_loss: 0.9830
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.9819 - val_accuracy: 0.6455 - val_loss: 0.8138
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.8969 - val_accuracy: 0.5187 - val_loss: 1.1088
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.9011 - val_accuracy: 0.7127 - val_loss: 0.7240
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6003 - loss: 0.8683 - val_accuracy: 0.7239 - val_loss: 0.6948
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.7746 - val_accuracy: 0.6679 - val_loss: 0.9147
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.7936 - val_accuracy: 0.6940 - val_loss: 0.6402
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.7553 - val_accuracy: 0.6903 - val_loss: 0.6386
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5650 - loss: 0.8737 - val_accuracy: 0.5149 - val_loss: 0.7751
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.7856 - val_accuracy: 0.7090 - val_loss: 0.6202
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.7085 - val_accuracy: 0.4739 - val_loss: 1.0237
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6019 - loss: 0.7799 - val_accuracy: 0.5485 - val_loss: 0.7092
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.7777 - val_accuracy: 0.6567 - val_loss: 0.8665
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6929 - val_accuracy: 0.7052 - val_loss: 0.6176
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6758 - val_accuracy: 0.6716 - val_loss: 0.6357
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.7619 - val_accuracy: 0.6642 - val_loss: 0.8274
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.7304 - val_accuracy: 0.7313 - val_loss: 0.5998
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6927 - val_accuracy: 0.6716 - val_loss: 0.7489
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.7004 - val_accuracy: 0.6642 - val_loss: 0.7226
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6781 - val_accuracy: 0.4440 - val_loss: 1.1207
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.7167 - val_accuracy: 0.7090 - val_loss: 0.5947
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.7024 - val_accuracy: 0.7276 - val_loss: 0.5887
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.7289 - val_accuracy: 0.6604 - val_loss: 0.7033
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6502 - val_accuracy: 0.6716 - val_loss: 0.6743
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.7084 - val_accuracy: 0.6343 - val_loss: 0.9670
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6988 - val_accuracy: 0.6828 - val_loss: 0.6405
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6746 - val_accuracy: 0.7575 - val_loss: 0.5827
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6475 - val_accuracy: 0.6679 - val_loss: 0.6862
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.7098 - val_accuracy: 0.7612 - val_loss: 0.5792
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6040 - val_accuracy: 0.6493 - val_loss: 0.8201
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6982 - loss: 0.6315 - val_accuracy: 0.7649 - val_loss: 0.5794
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.7016 - val_accuracy: 0.7687 - val_loss: 0.5859
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.6715 - val_accuracy: 0.6567 - val_loss: 0.8001
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6086 - val_accuracy: 0.7276 - val_loss: 0.5727
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6915 - val_accuracy: 0.7052 - val_loss: 0.5858
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6571 - val_accuracy: 0.7575 - val_loss: 0.5629
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6255 - val_accuracy: 0.4627 - val_loss: 0.8158
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6157 - val_accuracy: 0.7239 - val_loss: 0.5572
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6993 - val_accuracy: 0.7351 - val_loss: 0.5547
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6375 - val_accuracy: 0.6642 - val_loss: 0.7078
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.7250 - val_accuracy: 0.6530 - val_loss: 0.8033
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6233 - val_accuracy: 0.7127 - val_loss: 0.6167
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6356 - val_accuracy: 0.7276 - val_loss: 0.5473
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6464 - val_accuracy: 0.7724 - val_loss: 0.5512
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6253 - val_accuracy: 0.7537 - val_loss: 0.5976
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6242 - val_accuracy: 0.7164 - val_loss: 0.5630
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5725 - val_accuracy: 0.6269 - val_loss: 1.1078
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6654 - val_accuracy: 0.6978 - val_loss: 0.5715
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.6501 - val_accuracy: 0.6940 - val_loss: 0.5824
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5941 - val_accuracy: 0.7500 - val_loss: 0.6021
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6674 - val_accuracy: 0.7836 - val_loss: 0.5426
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5593 - val_accuracy: 0.6343 - val_loss: 0.6443
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6317 - val_accuracy: 0.4664 - val_loss: 0.8494
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5665 - val_accuracy: 0.4478 - val_loss: 1.0303
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.7078 - val_accuracy: 0.7164 - val_loss: 0.5519
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6351 - val_accuracy: 0.7052 - val_loss: 0.6108
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5811 - val_accuracy: 0.7649 - val_loss: 0.5151
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5538 - val_accuracy: 0.7537 - val_loss: 0.5218
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6293 - val_accuracy: 0.7388 - val_loss: 0.5295
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5873 - val_accuracy: 0.6866 - val_loss: 0.6847
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5595 - val_accuracy: 0.7388 - val_loss: 0.5206
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6111 - val_accuracy: 0.4776 - val_loss: 0.8575
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6312 - val_accuracy: 0.7649 - val_loss: 0.5158
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5659 - val_accuracy: 0.7612 - val_loss: 0.5077
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5323 - val_accuracy: 0.7873 - val_loss: 0.5234
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6543 - val_accuracy: 0.7537 - val_loss: 0.5893
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5447 - val_accuracy: 0.6604 - val_loss: 0.7654
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.6346 - val_accuracy: 0.7276 - val_loss: 0.5216
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5956 - val_accuracy: 0.7799 - val_loss: 0.5353
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5421 - val_accuracy: 0.6866 - val_loss: 0.6363
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5223 - val_accuracy: 0.5149 - val_loss: 0.7875
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5978 - val_accuracy: 0.7649 - val_loss: 0.5210
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5485 - val_accuracy: 0.5299 - val_loss: 0.7615
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5914 - val_accuracy: 0.7425 - val_loss: 0.5913
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5564 - val_accuracy: 0.7724 - val_loss: 0.5553
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6288 - val_accuracy: 0.7836 - val_loss: 0.5018
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5815 - val_accuracy: 0.6828 - val_loss: 0.7808
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5403 - val_accuracy: 0.6604 - val_loss: 0.8708
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5610 - val_accuracy: 0.6045 - val_loss: 0.7037
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5754 - val_accuracy: 0.6978 - val_loss: 0.6536
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5359 - val_accuracy: 0.7425 - val_loss: 0.5067
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6340 - val_accuracy: 0.7575 - val_loss: 0.4865
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5373 - val_accuracy: 0.7687 - val_loss: 0.5152
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5620 - val_accuracy: 0.6567 - val_loss: 0.8908
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5600 - val_accuracy: 0.7313 - val_loss: 0.5275
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5447 - val_accuracy: 0.7612 - val_loss: 0.4993
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6573 - val_accuracy: 0.7724 - val_loss: 0.4901
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.4904 - val_accuracy: 0.7537 - val_loss: 0.5005
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5877 - val_accuracy: 0.7500 - val_loss: 0.6120
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5437 - val_accuracy: 0.7313 - val_loss: 0.5208
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5767 - val_accuracy: 0.7687 - val_loss: 0.4903
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4692 - val_accuracy: 0.6493 - val_loss: 0.9090
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5555 - val_accuracy: 0.6418 - val_loss: 0.6743
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5808 - val_accuracy: 0.7724 - val_loss: 0.5121
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5389 - val_accuracy: 0.7090 - val_loss: 0.6361
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5347 - val_accuracy: 0.6045 - val_loss: 0.7212
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5540 - val_accuracy: 0.7724 - val_loss: 0.5617
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5889 - val_accuracy: 0.7575 - val_loss: 0.5005
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4800 - val_accuracy: 0.7761 - val_loss: 0.4887
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5762 - val_accuracy: 0.7164 - val_loss: 0.6331
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5712 - val_accuracy: 0.7537 - val_loss: 0.5931
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5409 - val_accuracy: 0.7836 - val_loss: 0.5062
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5341 - val_accuracy: 0.7090 - val_loss: 0.6276
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5867 - val_accuracy: 0.7239 - val_loss: 0.5586
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5254 - val_accuracy: 0.7873 - val_loss: 0.4794
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4923 - val_accuracy: 0.6269 - val_loss: 0.7027
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5496 - val_accuracy: 0.7687 - val_loss: 0.5079
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5824 - val_accuracy: 0.7761 - val_loss: 0.5002
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5463 - val_accuracy: 0.7761 - val_loss: 0.5281
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5087 - val_accuracy: 0.7537 - val_loss: 0.5178
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5504 - val_accuracy: 0.7873 - val_loss: 0.4867
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5156 - val_accuracy: 0.7463 - val_loss: 0.5176
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5081 - val_accuracy: 0.7761 - val_loss: 0.4989
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5439 - val_accuracy: 0.7052 - val_loss: 0.6905
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5450 - val_accuracy: 0.7948 - val_loss: 0.4841
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5793 - val_accuracy: 0.6754 - val_loss: 0.7544
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4742 - val_accuracy: 0.7276 - val_loss: 0.6011
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5298 - val_accuracy: 0.7799 - val_loss: 0.4784
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5265 - val_accuracy: 0.5187 - val_loss: 0.9116
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5238 - val_accuracy: 0.7500 - val_loss: 0.5244
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5086 - val_accuracy: 0.7724 - val_loss: 0.4967
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5109 - val_accuracy: 0.7910 - val_loss: 0.5320
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5590 - val_accuracy: 0.7724 - val_loss: 0.4866
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5738 - val_accuracy: 0.7724 - val_loss: 0.5028
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4904 - val_accuracy: 0.6679 - val_loss: 0.6569
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5506 - val_accuracy: 0.7425 - val_loss: 0.5616
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5397 - val_accuracy: 0.7052 - val_loss: 0.6371
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5433 - val_accuracy: 0.7761 - val_loss: 0.4888
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5084 - val_accuracy: 0.7351 - val_loss: 0.6009
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5261 - val_accuracy: 0.6866 - val_loss: 0.6416
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5435 - val_accuracy: 0.7276 - val_loss: 0.6187
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4745 - val_accuracy: 0.7127 - val_loss: 0.6238
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5901 - val_accuracy: 0.7649 - val_loss: 0.4859
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5178 - val_accuracy: 0.7836 - val_loss: 0.5523
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5638 - val_accuracy: 0.7575 - val_loss: 0.4803
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4502 - val_accuracy: 0.7612 - val_loss: 0.5168
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5308 - val_accuracy: 0.7687 - val_loss: 0.4815
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5457 - val_accuracy: 0.7873 - val_loss: 0.4827
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5242 - val_accuracy: 0.7910 - val_loss: 0.4782
Epoch 155/5000

wandb: Agent Starting Run: ee5e6mw6 with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4238 - loss: 8.4573 - val_accuracy: 0.4030 - val_loss: 4.0832
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5377 - loss: 3.1167 - val_accuracy: 0.6082 - val_loss: 3.1856
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 2.7532 - val_accuracy: 0.4963 - val_loss: 2.0274
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4912 - loss: 1.9250 - val_accuracy: 0.4030 - val_loss: 1.7639
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5185 - loss: 1.3779 - val_accuracy: 0.5970 - val_loss: 1.1211
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5104 - loss: 1.0855 - val_accuracy: 0.4627 - val_loss: 0.9924
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5441 - loss: 1.0025 - val_accuracy: 0.5187 - val_loss: 0.9046
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5297 - loss: 0.9494 - val_accuracy: 0.6194 - val_loss: 0.8473
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5297 - loss: 0.9040 - val_accuracy: 0.5597 - val_loss: 0.8237
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5778 - loss: 0.8726 - val_accuracy: 0.5485 - val_loss: 0.7914
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5634 - loss: 0.8482 - val_accuracy: 0.6754 - val_loss: 0.7578
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5634 - loss: 0.8244 - val_accuracy: 0.6791 - val_loss: 0.7327
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.8099 - val_accuracy: 0.5000 - val_loss: 0.7508
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5923 - loss: 0.7753 - val_accuracy: 0.6754 - val_loss: 0.7006
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.7534 - val_accuracy: 0.6493 - val_loss: 0.6927
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.7411 - val_accuracy: 0.6716 - val_loss: 0.6776
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.7173 - val_accuracy: 0.6716 - val_loss: 0.6751
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.7114 - val_accuracy: 0.6754 - val_loss: 0.6680
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.7079 - val_accuracy: 0.6754 - val_loss: 0.6526
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.6887 - val_accuracy: 0.6642 - val_loss: 0.6751
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.6849 - val_accuracy: 0.6903 - val_loss: 0.6488
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6630 - val_accuracy: 0.6866 - val_loss: 0.6318
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.6565 - val_accuracy: 0.6978 - val_loss: 0.6322
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.6689 - val_accuracy: 0.6828 - val_loss: 0.6198
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6586 - val_accuracy: 0.6903 - val_loss: 0.6160
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6349 - val_accuracy: 0.6940 - val_loss: 0.6138
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6356 - val_accuracy: 0.7052 - val_loss: 0.6065
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6307 - val_accuracy: 0.7090 - val_loss: 0.6257
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6283 - val_accuracy: 0.7015 - val_loss: 0.6030
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6148 - val_accuracy: 0.6828 - val_loss: 0.5941
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6134 - val_accuracy: 0.6940 - val_loss: 0.5923
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6068 - val_accuracy: 0.6978 - val_loss: 0.5981
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6061 - val_accuracy: 0.6866 - val_loss: 0.6162
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6087 - val_accuracy: 0.6866 - val_loss: 0.5938
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6037 - val_accuracy: 0.7090 - val_loss: 0.5905
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.5949 - val_accuracy: 0.6940 - val_loss: 0.5828
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.5915 - val_accuracy: 0.7015 - val_loss: 0.5864
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5823 - val_accuracy: 0.6866 - val_loss: 0.5826
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5833 - val_accuracy: 0.7090 - val_loss: 0.5796
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5890 - val_accuracy: 0.7276 - val_loss: 0.5994
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5833 - val_accuracy: 0.7015 - val_loss: 0.5810
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5728 - val_accuracy: 0.6866 - val_loss: 0.5813
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5701 - val_accuracy: 0.7276 - val_loss: 0.5831
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5702 - val_accuracy: 0.6940 - val_loss: 0.5797
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5703 - val_accuracy: 0.7052 - val_loss: 0.5806
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5674 - val_accuracy: 0.7276 - val_loss: 0.5690
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5625 - val_accuracy: 0.7127 - val_loss: 0.5637
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5779 - val_accuracy: 0.7015 - val_loss: 0.5662
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.5626 - val_accuracy: 0.6903 - val_loss: 0.5737
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5644 - val_accuracy: 0.6791 - val_loss: 0.5871
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5615 - val_accuracy: 0.7090 - val_loss: 0.5629
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5563 - val_accuracy: 0.7164 - val_loss: 0.5617
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5522 - val_accuracy: 0.6791 - val_loss: 0.5746
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5503 - val_accuracy: 0.7351 - val_loss: 0.5881
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5505 - val_accuracy: 0.6866 - val_loss: 0.5729
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5663 - val_accuracy: 0.6903 - val_loss: 0.5654
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5699 - val_accuracy: 0.7351 - val_loss: 0.5620
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.5478 - val_accuracy: 0.7239 - val_loss: 0.5499
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5423 - val_accuracy: 0.7127 - val_loss: 0.5512
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5442 - val_accuracy: 0.7201 - val_loss: 0.5482
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5486 - val_accuracy: 0.7425 - val_loss: 0.5571
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5427 - val_accuracy: 0.7201 - val_loss: 0.5491
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5452 - val_accuracy: 0.7276 - val_loss: 0.5451
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5389 - val_accuracy: 0.7388 - val_loss: 0.5465
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5599 - val_accuracy: 0.6754 - val_loss: 0.5893
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5430 - val_accuracy: 0.7090 - val_loss: 0.5437
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5351 - val_accuracy: 0.7425 - val_loss: 0.5432
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5356 - val_accuracy: 0.7276 - val_loss: 0.5372
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5368 - val_accuracy: 0.7463 - val_loss: 0.5885
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5676 - val_accuracy: 0.7537 - val_loss: 0.5437
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5401 - val_accuracy: 0.7612 - val_loss: 0.5529
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5363 - val_accuracy: 0.7351 - val_loss: 0.5282
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5307 - val_accuracy: 0.7127 - val_loss: 0.5316
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5275 - val_accuracy: 0.7164 - val_loss: 0.5316
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5249 - val_accuracy: 0.7425 - val_loss: 0.5278
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5241 - val_accuracy: 0.7276 - val_loss: 0.5290
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5317 - val_accuracy: 0.7015 - val_loss: 0.5410
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5558 - val_accuracy: 0.7537 - val_loss: 0.5277
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5274 - val_accuracy: 0.7388 - val_loss: 0.5291
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5222 - val_accuracy: 0.7612 - val_loss: 0.5376
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5214 - val_accuracy: 0.7649 - val_loss: 0.5318
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5189 - val_accuracy: 0.7388 - val_loss: 0.5221
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5141 - val_accuracy: 0.7687 - val_loss: 0.5349
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5135 - val_accuracy: 0.7239 - val_loss: 0.5216
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5279 - val_accuracy: 0.7351 - val_loss: 0.5152
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5420 - val_accuracy: 0.7761 - val_loss: 0.5452
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5265 - val_accuracy: 0.7612 - val_loss: 0.5547
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5248 - val_accuracy: 0.7276 - val_loss: 0.5145
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5138 - val_accuracy: 0.7313 - val_loss: 0.5118
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5219 - val_accuracy: 0.7388 - val_loss: 0.5119
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5154 - val_accuracy: 0.7687 - val_loss: 0.5312
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5178 - val_accuracy: 0.7612 - val_loss: 0.5178
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5108 - val_accuracy: 0.7873 - val_loss: 0.5508
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5186 - val_accuracy: 0.7612 - val_loss: 0.5145
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5144 - val_accuracy: 0.7388 - val_loss: 0.5091
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5154 - val_accuracy: 0.7351 - val_loss: 0.5137
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5032 - val_accuracy: 0.6978 - val_loss: 0.5529
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5161 - val_accuracy: 0.7164 - val_loss: 0.5287
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5073 - val_accuracy: 0.7500 - val_loss: 0.5100
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4971 - val_accuracy: 0.7388 - val_loss: 0.5048
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.4996 - val_accuracy: 0.7649 - val_loss: 0.5043
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.4998 - val_accuracy: 0.7649 - val_loss: 0.5046
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5056 - val_accuracy: 0.7463 - val_loss: 0.5051
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4900 - val_accuracy: 0.7463 - val_loss: 0.5015
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4914 - val_accuracy: 0.7425 - val_loss: 0.5014
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5049 - val_accuracy: 0.7276 - val_loss: 0.5217
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5133 - val_accuracy: 0.7164 - val_loss: 0.5406
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5078 - val_accuracy: 0.6903 - val_loss: 0.5502
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5043 - val_accuracy: 0.7687 - val_loss: 0.4981
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4909 - val_accuracy: 0.7612 - val_loss: 0.4982
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.4944 - val_accuracy: 0.7873 - val_loss: 0.5266
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4946 - val_accuracy: 0.7761 - val_loss: 0.5009
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.4852 - val_accuracy: 0.7500 - val_loss: 0.4964
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.4924 - val_accuracy: 0.7612 - val_loss: 0.4912
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5151 - val_accuracy: 0.7575 - val_loss: 0.5618
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5004 - val_accuracy: 0.7687 - val_loss: 0.4900
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4854 - val_accuracy: 0.7799 - val_loss: 0.4962
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4770 - val_accuracy: 0.7425 - val_loss: 0.5033
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.4981 - val_accuracy: 0.7276 - val_loss: 0.5191
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5013 - val_accuracy: 0.7537 - val_loss: 0.4969
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4771 - val_accuracy: 0.7873 - val_loss: 0.5185
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.4973 - val_accuracy: 0.7537 - val_loss: 0.4943
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4766 - val_accuracy: 0.7612 - val_loss: 0.4941
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4800 - val_accuracy: 0.7799 - val_loss: 0.4968
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4752 - val_accuracy: 0.7687 - val_loss: 0.4886
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4720 - val_accuracy: 0.7537 - val_loss: 0.4961
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4839 - val_accuracy: 0.7799 - val_loss: 0.4850
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4774 - val_accuracy: 0.7724 - val_loss: 0.4967
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4798 - val_accuracy: 0.7761 - val_loss: 0.4975
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5093 - val_accuracy: 0.7649 - val_loss: 0.4896
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4764 - val_accuracy: 0.7724 - val_loss: 0.4916
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4673 - val_accuracy: 0.7649 - val_loss: 0.4862
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4686 - val_accuracy: 0.7575 - val_loss: 0.4820
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.4862 - val_accuracy: 0.7388 - val_loss: 0.5053
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4725 - val_accuracy: 0.7649 - val_loss: 0.4858
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4722 - val_accuracy: 0.7425 - val_loss: 0.4967
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4637 - val_accuracy: 0.7724 - val_loss: 0.4897
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4737 - val_accuracy: 0.7612 - val_loss: 0.4955
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4750 - val_accuracy: 0.7575 - val_loss: 0.4803
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4706 - val_accuracy: 0.7351 - val_loss: 0.5067
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4792 - val_accuracy: 0.7537 - val_loss: 0.4808
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4645 - val_accuracy: 0.7724 - val_loss: 0.4830
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4775 - val_accuracy: 0.7612 - val_loss: 0.4921
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4714 - val_accuracy: 0.7276 - val_loss: 0.5281
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4883 - val_accuracy: 0.7537 - val_loss: 0.4783
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4668 - val_accuracy: 0.7575 - val_loss: 0.4824
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4633 - val_accuracy: 0.7724 - val_loss: 0.4779
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4638 - val_accuracy: 0.7724 - val_loss: 0.4809
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4646 - val_accuracy: 0.7687 - val_loss: 0.4867
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4636 - val_accuracy: 0.7724 - val_loss: 0.4844
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4580 - val_accuracy: 0.7612 - val_loss: 0.4803
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4580 - val_accuracy: 0.7649 - val_loss: 0.4775
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4577 - val_accuracy: 0.7649 - val_loss: 0.4854
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4807 - val_accuracy: 0.7090 - val_loss: 0.5566
Epoch 155/5000

wandb: Agent Starting Run: 0copboek with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5056 - loss: 26.9164 - val_accuracy: 0.6269 - val_loss: 0.8931
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.7690 - val_accuracy: 0.6269 - val_loss: 0.7275
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7250 - val_accuracy: 0.6231 - val_loss: 0.7033
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7098 - val_accuracy: 0.6269 - val_loss: 0.6908
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.7023 - val_accuracy: 0.6269 - val_loss: 0.6898
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6991 - val_accuracy: 0.6269 - val_loss: 0.6902
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6972 - val_accuracy: 0.6269 - val_loss: 0.6904
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6947 - val_accuracy: 0.6269 - val_loss: 0.6907
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6935 - val_accuracy: 0.6269 - val_loss: 0.6840
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6932 - val_accuracy: 0.6231 - val_loss: 0.6848
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6910 - val_accuracy: 0.6269 - val_loss: 0.6846
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6887 - val_accuracy: 0.6269 - val_loss: 0.6852
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6879 - val_accuracy: 0.6269 - val_loss: 0.6845
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6858 - val_accuracy: 0.6306 - val_loss: 0.6843
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6852 - val_accuracy: 0.6306 - val_loss: 0.6835
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6839 - val_accuracy: 0.6306 - val_loss: 0.6830
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6843 - val_accuracy: 0.6269 - val_loss: 0.6844
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6834 - val_accuracy: 0.6306 - val_loss: 0.6819
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6818 - val_accuracy: 0.6269 - val_loss: 0.6819
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6815 - val_accuracy: 0.6269 - val_loss: 0.6828
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6802 - val_accuracy: 0.6269 - val_loss: 0.6829
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6797 - val_accuracy: 0.6269 - val_loss: 0.6823
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6791 - val_accuracy: 0.6306 - val_loss: 0.6819
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6785 - val_accuracy: 0.6306 - val_loss: 0.6812
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6782 - val_accuracy: 0.6306 - val_loss: 0.6816
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6772 - val_accuracy: 0.6306 - val_loss: 0.6829
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6765 - val_accuracy: 0.6231 - val_loss: 0.6765
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6761 - val_accuracy: 0.6231 - val_loss: 0.6766
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6763 - val_accuracy: 0.6231 - val_loss: 0.6768
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6743 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6769 - val_accuracy: 0.6231 - val_loss: 0.6764
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6743 - val_accuracy: 0.6306 - val_loss: 0.6770
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6743 - val_accuracy: 0.6194 - val_loss: 0.6783
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6727 - val_accuracy: 0.6231 - val_loss: 0.6783
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6722 - val_accuracy: 0.6194 - val_loss: 0.6778
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6722 - val_accuracy: 0.6231 - val_loss: 0.6774
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6725 - val_accuracy: 0.6194 - val_loss: 0.6781
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6716 - val_accuracy: 0.6157 - val_loss: 0.6807
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6715 - val_accuracy: 0.6194 - val_loss: 0.6788
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6713 - val_accuracy: 0.6194 - val_loss: 0.6787
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6706 - val_accuracy: 0.6231 - val_loss: 0.6784
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6700 - val_accuracy: 0.6231 - val_loss: 0.6781
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6699 - val_accuracy: 0.6306 - val_loss: 0.6767
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6707 - val_accuracy: 0.6231 - val_loss: 0.6790
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6697 - val_accuracy: 0.6306 - val_loss: 0.6773
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6694 - val_accuracy: 0.6269 - val_loss: 0.6775
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6691 - val_accuracy: 0.6231 - val_loss: 0.6779
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6690 - val_accuracy: 0.6231 - val_loss: 0.6785
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6678 - val_accuracy: 0.6306 - val_loss: 0.6772
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6688 - val_accuracy: 0.6306 - val_loss: 0.6773
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6683 - val_accuracy: 0.6269 - val_loss: 0.6777
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6769
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6674 - val_accuracy: 0.6306 - val_loss: 0.6764
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6670 - val_accuracy: 0.6231 - val_loss: 0.6775
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6675 - val_accuracy: 0.6269 - val_loss: 0.6773
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6671 - val_accuracy: 0.6269 - val_loss: 0.6770
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6670 - val_accuracy: 0.6269 - val_loss: 0.6765
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6663 - val_accuracy: 0.6231 - val_loss: 0.6770
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6663 - val_accuracy: 0.6306 - val_loss: 0.6768
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6664 - val_accuracy: 0.6306 - val_loss: 0.6757
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6674 - val_accuracy: 0.6269 - val_loss: 0.6766
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6665 - val_accuracy: 0.6306 - val_loss: 0.6761
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6666 - val_accuracy: 0.6269 - val_loss: 0.6761
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6660 - val_accuracy: 0.6306 - val_loss: 0.6748
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6757
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6269 - val_loss: 0.6759
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6665 - val_accuracy: 0.6231 - val_loss: 0.6763
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6650 - val_accuracy: 0.6306 - val_loss: 0.6750
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6269 - val_loss: 0.6750
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6652 - val_accuracy: 0.6231 - val_loss: 0.6763
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6752
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6757
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6648 - val_accuracy: 0.6231 - val_loss: 0.6762
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.6748
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6758
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6231 - val_loss: 0.6768
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6768
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6753
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6766
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6653 - val_accuracy: 0.6231 - val_loss: 0.6773
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6772
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.6752
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6637 - val_accuracy: 0.6269 - val_loss: 0.6747
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.6763
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6756
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.6758
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6637 - val_accuracy: 0.6231 - val_loss: 0.6768
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6768
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.6769
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.6745
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.6752
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6633 - val_accuracy: 0.6269 - val_loss: 0.6741
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6633 - val_accuracy: 0.6269 - val_loss: 0.6745
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6637 - val_accuracy: 0.6231 - val_loss: 0.6752
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.6747
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6756
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6749
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.6755
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6751
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.6746
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6760
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6634 - val_accuracy: 0.6231 - val_loss: 0.6762
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6758
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6751
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6756
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6622 - val_accuracy: 0.6231 - val_loss: 0.6762
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6625 - val_accuracy: 0.6231 - val_loss: 0.6758
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6746
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6625 - val_accuracy: 0.6269 - val_loss: 0.6749
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6754
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6231 - val_loss: 0.6761
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6269 - val_loss: 0.6753
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.6750
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6269 - val_loss: 0.6754
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.6763
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6769
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6622 - val_accuracy: 0.6231 - val_loss: 0.6763
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6760
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.6759
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6781
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.6763
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6784
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6779
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6789
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6779
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6771
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6269 - val_loss: 0.6772
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6269 - val_loss: 0.6774
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6231 - val_loss: 0.6783
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6269 - val_loss: 0.6770
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6231 - val_loss: 0.6776
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6194 - val_loss: 0.6796
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6231 - val_loss: 0.6776
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6788
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6794
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6194 - val_loss: 0.6787
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.6773
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6231 - val_loss: 0.6790
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.6794
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6194 - val_loss: 0.6799
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6194 - val_loss: 0.6792
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6231 - val_loss: 0.6785
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.6776
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6609 - val_accuracy: 0.6231 - val_loss: 0.6777
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6231 - val_loss: 0.6783
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6613 - val_accuracy: 0.6194 - val_loss: 0.6798
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6609 - val_accuracy: 0.6194 - val_loss: 0.6780
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6771
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.6788
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6607 - val_accuracy: 0.6194 - val_loss: 0.6794
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6609 - val_accuracy: 0.6231 - val_loss: 0.6798
Epoch 155/5000

wandb: Agent Starting Run: 7oivnbqh with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3884 - loss: 75.7382 - val_accuracy: 0.3731 - val_loss: 53.4703
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3884 - loss: 42.0367 - val_accuracy: 0.3731 - val_loss: 28.4973
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3884 - loss: 20.6777 - val_accuracy: 0.3731 - val_loss: 13.6041
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3884 - loss: 10.3262 - val_accuracy: 0.3731 - val_loss: 6.4763
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3949 - loss: 3.9096 - val_accuracy: 0.4216 - val_loss: 1.7759
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5313 - loss: 1.4459 - val_accuracy: 0.5896 - val_loss: 1.3632
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 1.2349 - val_accuracy: 0.6007 - val_loss: 1.2382
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 1.0966 - val_accuracy: 0.6194 - val_loss: 1.1524
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.9796 - val_accuracy: 0.6679 - val_loss: 1.0847
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.8948 - val_accuracy: 0.6604 - val_loss: 1.0354
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.8229 - val_accuracy: 0.6866 - val_loss: 0.9807
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.7802 - val_accuracy: 0.6791 - val_loss: 0.9333
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 0.7272 - val_accuracy: 0.6567 - val_loss: 0.8429
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6852 - val_accuracy: 0.6418 - val_loss: 0.8123
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6904 - val_accuracy: 0.6604 - val_loss: 0.7734
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6697 - val_accuracy: 0.6679 - val_loss: 0.7468
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6554 - val_accuracy: 0.6903 - val_loss: 0.7170
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6435 - val_accuracy: 0.6567 - val_loss: 0.7050
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6485 - val_accuracy: 0.6903 - val_loss: 0.6884
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6326 - val_accuracy: 0.6940 - val_loss: 0.6824
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6362 - val_accuracy: 0.6903 - val_loss: 0.6727
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6298 - val_accuracy: 0.6754 - val_loss: 0.6665
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.6143 - val_accuracy: 0.6940 - val_loss: 0.6676
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6344 - val_accuracy: 0.7015 - val_loss: 0.6540
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6109 - val_accuracy: 0.6791 - val_loss: 0.6519
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6168 - val_accuracy: 0.6866 - val_loss: 0.6449
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6070 - val_accuracy: 0.7015 - val_loss: 0.6507
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.6044 - val_accuracy: 0.7239 - val_loss: 0.6754
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6134 - val_accuracy: 0.7239 - val_loss: 0.6508
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.6035 - val_accuracy: 0.6791 - val_loss: 0.6373
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.5992 - val_accuracy: 0.6791 - val_loss: 0.6342
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.5877 - val_accuracy: 0.7313 - val_loss: 0.6388
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6014 - val_accuracy: 0.7052 - val_loss: 0.6147
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.5925 - val_accuracy: 0.6978 - val_loss: 0.6106
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5861 - val_accuracy: 0.7351 - val_loss: 0.6219
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6089 - val_accuracy: 0.6828 - val_loss: 0.6110
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5833 - val_accuracy: 0.7239 - val_loss: 0.6100
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6023 - val_accuracy: 0.6866 - val_loss: 0.6062
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5836 - val_accuracy: 0.7201 - val_loss: 0.5938
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5838 - val_accuracy: 0.6866 - val_loss: 0.6060
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5857 - val_accuracy: 0.6940 - val_loss: 0.6170
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5844 - val_accuracy: 0.6567 - val_loss: 0.6144
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.5954 - val_accuracy: 0.7276 - val_loss: 0.5937
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.5870 - val_accuracy: 0.7276 - val_loss: 0.5901
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.5899 - val_accuracy: 0.7052 - val_loss: 0.5979
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5852 - val_accuracy: 0.6866 - val_loss: 0.6010
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.5853 - val_accuracy: 0.6978 - val_loss: 0.5952
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5800 - val_accuracy: 0.7313 - val_loss: 0.6488
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5812 - val_accuracy: 0.6828 - val_loss: 0.5980
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.5740 - val_accuracy: 0.6866 - val_loss: 0.5948
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.5715 - val_accuracy: 0.6866 - val_loss: 0.5997
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.5763 - val_accuracy: 0.7164 - val_loss: 0.5959
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5804 - val_accuracy: 0.6866 - val_loss: 0.5953
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5676 - val_accuracy: 0.7090 - val_loss: 0.5852
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5681 - val_accuracy: 0.7127 - val_loss: 0.6203
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5774 - val_accuracy: 0.7276 - val_loss: 0.5861
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5733 - val_accuracy: 0.6604 - val_loss: 0.6144
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.5738 - val_accuracy: 0.6940 - val_loss: 0.5898
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5772 - val_accuracy: 0.6791 - val_loss: 0.5946
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.5774 - val_accuracy: 0.7276 - val_loss: 0.5739
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5649 - val_accuracy: 0.7351 - val_loss: 0.5808
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5789 - val_accuracy: 0.7276 - val_loss: 0.5761
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5664 - val_accuracy: 0.7276 - val_loss: 0.5704
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5646 - val_accuracy: 0.7313 - val_loss: 0.5917
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5766 - val_accuracy: 0.7090 - val_loss: 0.5742
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5678 - val_accuracy: 0.7313 - val_loss: 0.5724
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5609 - val_accuracy: 0.7127 - val_loss: 0.5679
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.5779 - val_accuracy: 0.7052 - val_loss: 0.5725
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.5768 - val_accuracy: 0.6940 - val_loss: 0.5839
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5666 - val_accuracy: 0.7276 - val_loss: 0.5737
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5658 - val_accuracy: 0.7313 - val_loss: 0.5650
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5600 - val_accuracy: 0.6940 - val_loss: 0.5742
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5589 - val_accuracy: 0.7276 - val_loss: 0.6122
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5606 - val_accuracy: 0.7015 - val_loss: 0.5998
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5594 - val_accuracy: 0.7313 - val_loss: 0.5736
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5482 - val_accuracy: 0.7276 - val_loss: 0.5906
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.5714 - val_accuracy: 0.7313 - val_loss: 0.5680
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5581 - val_accuracy: 0.7276 - val_loss: 0.5596
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5568 - val_accuracy: 0.6828 - val_loss: 0.5882
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5606 - val_accuracy: 0.7239 - val_loss: 0.5938
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5570 - val_accuracy: 0.7276 - val_loss: 0.5571
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5528 - val_accuracy: 0.7276 - val_loss: 0.5835
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5521 - val_accuracy: 0.7052 - val_loss: 0.5696
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5560 - val_accuracy: 0.7201 - val_loss: 0.5531
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5533 - val_accuracy: 0.6716 - val_loss: 0.5690
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5541 - val_accuracy: 0.7090 - val_loss: 0.5540
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5481 - val_accuracy: 0.7351 - val_loss: 0.5501
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5500 - val_accuracy: 0.7276 - val_loss: 0.5663
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5476 - val_accuracy: 0.7090 - val_loss: 0.5555
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5517 - val_accuracy: 0.7276 - val_loss: 0.5440
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5420 - val_accuracy: 0.7425 - val_loss: 0.5632
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5435 - val_accuracy: 0.7201 - val_loss: 0.5484
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5471 - val_accuracy: 0.7276 - val_loss: 0.6124
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5561 - val_accuracy: 0.7313 - val_loss: 0.5422
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5423 - val_accuracy: 0.6866 - val_loss: 0.5741
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5480 - val_accuracy: 0.7388 - val_loss: 0.5519
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5492 - val_accuracy: 0.7351 - val_loss: 0.5576
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7175 - loss: 0.5430 - val_accuracy: 0.7425 - val_loss: 0.5401
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6982 - loss: 0.5449 - val_accuracy: 0.7351 - val_loss: 0.5818
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5418 - val_accuracy: 0.7388 - val_loss: 0.5530
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5450 - val_accuracy: 0.7425 - val_loss: 0.5421
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5334 - val_accuracy: 0.7313 - val_loss: 0.6552
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5525 - val_accuracy: 0.7351 - val_loss: 0.5399
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5300 - val_accuracy: 0.7500 - val_loss: 0.5396
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5431 - val_accuracy: 0.7052 - val_loss: 0.5652
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5395 - val_accuracy: 0.7313 - val_loss: 0.5415
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5248 - val_accuracy: 0.7388 - val_loss: 0.5674
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5300 - val_accuracy: 0.7313 - val_loss: 0.5837
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5432 - val_accuracy: 0.7425 - val_loss: 0.5714
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5529 - val_accuracy: 0.6903 - val_loss: 0.5655
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5355 - val_accuracy: 0.7425 - val_loss: 0.5503
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5330 - val_accuracy: 0.7127 - val_loss: 0.5835
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5284 - val_accuracy: 0.7388 - val_loss: 0.5325
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5401 - val_accuracy: 0.7164 - val_loss: 0.5789
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5396 - val_accuracy: 0.7164 - val_loss: 0.5488
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5321 - val_accuracy: 0.7425 - val_loss: 0.5542
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5368 - val_accuracy: 0.7388 - val_loss: 0.5423
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5288 - val_accuracy: 0.7351 - val_loss: 0.5587
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5274 - val_accuracy: 0.7052 - val_loss: 0.5646
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5324 - val_accuracy: 0.7425 - val_loss: 0.5304
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7127 - loss: 0.5152 - val_accuracy: 0.7351 - val_loss: 0.5502
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5321 - val_accuracy: 0.7351 - val_loss: 0.5430
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5347 - val_accuracy: 0.7425 - val_loss: 0.5250
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5242 - val_accuracy: 0.7425 - val_loss: 0.5332
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5311 - val_accuracy: 0.6940 - val_loss: 0.5589
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5300 - val_accuracy: 0.7052 - val_loss: 0.5371
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.5264 - val_accuracy: 0.7127 - val_loss: 0.5546
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5238 - val_accuracy: 0.7463 - val_loss: 0.5254
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5293 - val_accuracy: 0.7425 - val_loss: 0.5262
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5152 - val_accuracy: 0.7463 - val_loss: 0.5254
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5298 - val_accuracy: 0.7463 - val_loss: 0.5229
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5127 - val_accuracy: 0.7425 - val_loss: 0.5570
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5210 - val_accuracy: 0.6791 - val_loss: 0.5472
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.5167 - val_accuracy: 0.7463 - val_loss: 0.5238
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5285 - val_accuracy: 0.7463 - val_loss: 0.5339
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5106 - val_accuracy: 0.7463 - val_loss: 0.5644
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5228 - val_accuracy: 0.7239 - val_loss: 0.5610
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5190 - val_accuracy: 0.7463 - val_loss: 0.5439
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5129 - val_accuracy: 0.7463 - val_loss: 0.5242
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5164 - val_accuracy: 0.7500 - val_loss: 0.5259
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7143 - loss: 0.5178 - val_accuracy: 0.7052 - val_loss: 0.5321
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5108 - val_accuracy: 0.7239 - val_loss: 0.5277
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5056 - val_accuracy: 0.7313 - val_loss: 0.5291
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5250 - val_accuracy: 0.7388 - val_loss: 0.5301
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5177 - val_accuracy: 0.7425 - val_loss: 0.5415
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5106 - val_accuracy: 0.7351 - val_loss: 0.5753
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5139 - val_accuracy: 0.7575 - val_loss: 0.5452
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5122 - val_accuracy: 0.7463 - val_loss: 0.5243
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5061 - val_accuracy: 0.7388 - val_loss: 0.5345
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5102 - val_accuracy: 0.7500 - val_loss: 0.5340
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5172 - val_accuracy: 0.7239 - val_loss: 0.5310
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.4958 - val_accuracy: 0.7687 - val_loss: 0.5506
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5143 - val_accuracy: 0.7537 - val_loss: 0.5102
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.5047 - val_accuracy: 0.7351 - val_loss: 0.5200
Epoch 155/5000

wandb: Agent Starting Run: 53884smm with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 8
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6100 - loss: 69.4812 - val_accuracy: 0.6306 - val_loss: 55.9817
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 47.7782 - val_accuracy: 0.6306 - val_loss: 35.7711
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 26.3003 - val_accuracy: 0.6343 - val_loss: 13.4253
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5811 - loss: 6.6395 - val_accuracy: 0.3731 - val_loss: 5.1800
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4478 - loss: 4.1601 - val_accuracy: 0.6530 - val_loss: 2.6920
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 2.8318 - val_accuracy: 0.6716 - val_loss: 1.2600
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5586 - loss: 1.6796 - val_accuracy: 0.6791 - val_loss: 1.3295
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 1.3840 - val_accuracy: 0.6493 - val_loss: 1.0632
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 1.2059 - val_accuracy: 0.6978 - val_loss: 0.9539
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 1.0235 - val_accuracy: 0.6978 - val_loss: 1.0052
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.9388 - val_accuracy: 0.6642 - val_loss: 0.8927
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.9082 - val_accuracy: 0.6082 - val_loss: 0.8818
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.8968 - val_accuracy: 0.5970 - val_loss: 0.8665
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.8709 - val_accuracy: 0.5896 - val_loss: 0.8671
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5971 - loss: 0.8776 - val_accuracy: 0.5634 - val_loss: 0.8839
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.8538 - val_accuracy: 0.6530 - val_loss: 0.8164
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.8061 - val_accuracy: 0.6604 - val_loss: 0.8090
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.7835 - val_accuracy: 0.5410 - val_loss: 0.8781
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7981 - val_accuracy: 0.6157 - val_loss: 0.8117
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7625 - val_accuracy: 0.6716 - val_loss: 0.7975
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.7533 - val_accuracy: 0.6791 - val_loss: 0.8084
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.7466 - val_accuracy: 0.6828 - val_loss: 0.8076
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.7412 - val_accuracy: 0.6903 - val_loss: 0.7839
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.7120 - val_accuracy: 0.6903 - val_loss: 0.7545
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7083 - val_accuracy: 0.5933 - val_loss: 0.7747
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.7412 - val_accuracy: 0.6940 - val_loss: 0.7252
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6835 - val_accuracy: 0.6940 - val_loss: 0.7340
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.6805 - val_accuracy: 0.6978 - val_loss: 0.7127
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6616 - val_accuracy: 0.6828 - val_loss: 0.7112
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6681 - val_accuracy: 0.5784 - val_loss: 0.7625
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6930 - val_accuracy: 0.5634 - val_loss: 0.7507
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.6625 - val_accuracy: 0.6866 - val_loss: 0.6952
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6442 - val_accuracy: 0.6903 - val_loss: 0.7276
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6440 - val_accuracy: 0.6940 - val_loss: 0.6783
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6695 - val_accuracy: 0.5709 - val_loss: 0.7169
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6606 - val_accuracy: 0.6903 - val_loss: 0.6514
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6175 - val_accuracy: 0.6940 - val_loss: 0.7227
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6213 - val_accuracy: 0.6828 - val_loss: 0.7629
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6327 - val_accuracy: 0.6642 - val_loss: 0.6528
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6150 - val_accuracy: 0.5858 - val_loss: 0.7346
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6669 - val_accuracy: 0.7052 - val_loss: 0.6504
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6287 - val_accuracy: 0.6679 - val_loss: 0.7392
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.5904 - val_accuracy: 0.7052 - val_loss: 0.6377
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5920 - val_accuracy: 0.7090 - val_loss: 0.6090
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5703 - val_accuracy: 0.7164 - val_loss: 0.6144
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5658 - val_accuracy: 0.6269 - val_loss: 0.6633
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5670 - val_accuracy: 0.7015 - val_loss: 0.6578
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5704 - val_accuracy: 0.6940 - val_loss: 0.5990
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.5887 - val_accuracy: 0.7015 - val_loss: 0.6385
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6240 - val_accuracy: 0.7164 - val_loss: 0.6056
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5677 - val_accuracy: 0.7239 - val_loss: 0.6022
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.5971 - val_accuracy: 0.7090 - val_loss: 0.6114
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5762 - val_accuracy: 0.6978 - val_loss: 0.6284
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6021 - val_accuracy: 0.7313 - val_loss: 0.5859
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5933 - val_accuracy: 0.7127 - val_loss: 0.6022
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5504 - val_accuracy: 0.7127 - val_loss: 0.5943
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5657 - val_accuracy: 0.7351 - val_loss: 0.5683
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5247 - val_accuracy: 0.7015 - val_loss: 0.5843
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5310 - val_accuracy: 0.7388 - val_loss: 0.5682
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5321 - val_accuracy: 0.7090 - val_loss: 0.5726
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5210 - val_accuracy: 0.6978 - val_loss: 0.6097
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5440 - val_accuracy: 0.7500 - val_loss: 0.5598
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5722 - val_accuracy: 0.7015 - val_loss: 0.6569
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7207 - loss: 0.5785 - val_accuracy: 0.7388 - val_loss: 0.6060
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5521 - val_accuracy: 0.7164 - val_loss: 0.6195
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5552 - val_accuracy: 0.7575 - val_loss: 0.5779
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5280 - val_accuracy: 0.7313 - val_loss: 0.5510
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.5023 - val_accuracy: 0.7313 - val_loss: 0.5442
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5092 - val_accuracy: 0.7649 - val_loss: 0.5718
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5023 - val_accuracy: 0.7276 - val_loss: 0.5606
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5152 - val_accuracy: 0.7239 - val_loss: 0.5490
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5450 - val_accuracy: 0.7164 - val_loss: 0.6421
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5683 - val_accuracy: 0.7313 - val_loss: 0.5674
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5028 - val_accuracy: 0.7276 - val_loss: 0.5399
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4880 - val_accuracy: 0.7239 - val_loss: 0.5354
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4818 - val_accuracy: 0.7724 - val_loss: 0.5590
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4970 - val_accuracy: 0.7164 - val_loss: 0.6076
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5311 - val_accuracy: 0.7425 - val_loss: 0.5369
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7544 - loss: 0.5218 - val_accuracy: 0.6082 - val_loss: 0.7331
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6161 - val_accuracy: 0.7575 - val_loss: 0.5845
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5591 - val_accuracy: 0.7239 - val_loss: 0.5763
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4828 - val_accuracy: 0.7575 - val_loss: 0.5395
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4736 - val_accuracy: 0.7500 - val_loss: 0.5278
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4899 - val_accuracy: 0.7649 - val_loss: 0.5786
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5172 - val_accuracy: 0.7687 - val_loss: 0.5860
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4913 - val_accuracy: 0.7313 - val_loss: 0.5350
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4731 - val_accuracy: 0.7425 - val_loss: 0.5282
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4654 - val_accuracy: 0.7537 - val_loss: 0.5268
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4685 - val_accuracy: 0.7463 - val_loss: 0.5324
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4662 - val_accuracy: 0.7351 - val_loss: 0.5400
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.4992 - val_accuracy: 0.7612 - val_loss: 0.5314
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4932 - val_accuracy: 0.7164 - val_loss: 0.6622
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5339 - val_accuracy: 0.7425 - val_loss: 0.5337
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4830 - val_accuracy: 0.6866 - val_loss: 0.6871
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5112 - val_accuracy: 0.7425 - val_loss: 0.5354
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4846 - val_accuracy: 0.7649 - val_loss: 0.5316
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4646 - val_accuracy: 0.7500 - val_loss: 0.5303
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4757 - val_accuracy: 0.7687 - val_loss: 0.5270
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4682 - val_accuracy: 0.7575 - val_loss: 0.5200
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7865 - loss: 0.4867 - val_accuracy: 0.7239 - val_loss: 0.5838
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5025 - val_accuracy: 0.7575 - val_loss: 0.5290
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4658 - val_accuracy: 0.7463 - val_loss: 0.5308
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4650 - val_accuracy: 0.7463 - val_loss: 0.5537
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4532 - val_accuracy: 0.7575 - val_loss: 0.5347
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4777 - val_accuracy: 0.7351 - val_loss: 0.5705
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4956 - val_accuracy: 0.7724 - val_loss: 0.5822
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4803 - val_accuracy: 0.7612 - val_loss: 0.5268
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.4769 - val_accuracy: 0.7313 - val_loss: 0.5505
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4612 - val_accuracy: 0.7799 - val_loss: 0.5729
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4708 - val_accuracy: 0.7687 - val_loss: 0.5283
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4571 - val_accuracy: 0.7649 - val_loss: 0.5358
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4476 - val_accuracy: 0.7687 - val_loss: 0.5405
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4691 - val_accuracy: 0.7724 - val_loss: 0.6207
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4805 - val_accuracy: 0.7612 - val_loss: 0.5414
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4728 - val_accuracy: 0.7724 - val_loss: 0.5199
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4627 - val_accuracy: 0.7649 - val_loss: 0.5386
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4633 - val_accuracy: 0.7612 - val_loss: 0.5238
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4549 - val_accuracy: 0.7649 - val_loss: 0.5267
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4679 - val_accuracy: 0.7724 - val_loss: 0.5273
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5110 - val_accuracy: 0.7425 - val_loss: 0.5899
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4776 - val_accuracy: 0.7687 - val_loss: 0.5667
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4813 - val_accuracy: 0.7761 - val_loss: 0.6127
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4680 - val_accuracy: 0.7687 - val_loss: 0.5381
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4485 - val_accuracy: 0.7612 - val_loss: 0.5296
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5040 - val_accuracy: 0.7724 - val_loss: 0.5896
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4867 - val_accuracy: 0.7687 - val_loss: 0.5592
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4419 - val_accuracy: 0.7612 - val_loss: 0.5270
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4434 - val_accuracy: 0.7687 - val_loss: 0.5494
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4601 - val_accuracy: 0.7612 - val_loss: 0.5250
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4426 - val_accuracy: 0.7612 - val_loss: 0.5346
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4872 - val_accuracy: 0.7687 - val_loss: 0.5385
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5046 - val_accuracy: 0.6194 - val_loss: 0.8074
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4972 - val_accuracy: 0.7612 - val_loss: 0.5273
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4464 - val_accuracy: 0.7649 - val_loss: 0.5281
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4417 - val_accuracy: 0.7687 - val_loss: 0.5439
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4448 - val_accuracy: 0.7687 - val_loss: 0.5393
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4606 - val_accuracy: 0.7612 - val_loss: 0.5454
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4510 - val_accuracy: 0.7761 - val_loss: 0.6084
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4713 - val_accuracy: 0.7724 - val_loss: 0.5264
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4434 - val_accuracy: 0.7687 - val_loss: 0.5619
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4536 - val_accuracy: 0.7575 - val_loss: 0.5373
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8154 - loss: 0.4370 - val_accuracy: 0.7649 - val_loss: 0.5559
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4676 - val_accuracy: 0.7313 - val_loss: 0.5960
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5223 - val_accuracy: 0.7276 - val_loss: 0.6165
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4902 - val_accuracy: 0.7612 - val_loss: 0.5345
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4499 - val_accuracy: 0.7575 - val_loss: 0.5406
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4555 - val_accuracy: 0.7537 - val_loss: 0.5352
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5785 - val_accuracy: 0.7276 - val_loss: 0.6716
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.5005 - val_accuracy: 0.7575 - val_loss: 0.5479
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4468 - val_accuracy: 0.7575 - val_loss: 0.5506
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4443 - val_accuracy: 0.7687 - val_loss: 0.5843
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4518 - val_accuracy: 0.7164 - val_loss: 0.6579
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4889 - val_accuracy: 0.7537 - val_loss: 0.5572
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4424 - val_accuracy: 0.7649 - val_loss: 0.5474
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: fvfsb66i with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5698 - loss: 7.9015 - val_accuracy: 0.6231 - val_loss: 0.7252
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.7021 - val_accuracy: 0.6381 - val_loss: 0.7063
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6951 - val_accuracy: 0.6493 - val_loss: 0.6947
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6924 - val_accuracy: 0.6530 - val_loss: 0.6880
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6898 - val_accuracy: 0.6604 - val_loss: 0.6873
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6870 - val_accuracy: 0.6754 - val_loss: 0.6819
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.6858 - val_accuracy: 0.6679 - val_loss: 0.6798
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6828 - val_accuracy: 0.6642 - val_loss: 0.6749
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6799 - val_accuracy: 0.6604 - val_loss: 0.6765
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6766 - val_accuracy: 0.6978 - val_loss: 0.6613
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6732 - val_accuracy: 0.4701 - val_loss: 0.7014
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5971 - loss: 0.6814 - val_accuracy: 0.6679 - val_loss: 0.6646
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6723 - val_accuracy: 0.6343 - val_loss: 0.7028
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6682 - val_accuracy: 0.7090 - val_loss: 0.6513
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6770 - val_accuracy: 0.6269 - val_loss: 0.7080
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6710 - val_accuracy: 0.6567 - val_loss: 0.6662
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6726 - val_accuracy: 0.6604 - val_loss: 0.6663
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6678 - val_accuracy: 0.6791 - val_loss: 0.6534
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6630 - val_accuracy: 0.6716 - val_loss: 0.6551
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6624 - val_accuracy: 0.6679 - val_loss: 0.6661
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.6637 - val_accuracy: 0.6493 - val_loss: 0.7010
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.6712 - val_accuracy: 0.6754 - val_loss: 0.6491
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6605 - val_accuracy: 0.7090 - val_loss: 0.6338
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6616 - val_accuracy: 0.6866 - val_loss: 0.6532
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.6693 - val_accuracy: 0.6269 - val_loss: 0.7093
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.6634 - val_accuracy: 0.6567 - val_loss: 0.6748
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.6609
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6512 - val_accuracy: 0.6866 - val_loss: 0.6469
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6548 - val_accuracy: 0.6716 - val_loss: 0.6453
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6562 - val_accuracy: 0.6567 - val_loss: 0.6540
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6539 - val_accuracy: 0.6567 - val_loss: 0.6732
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6502 - val_accuracy: 0.6604 - val_loss: 0.6587
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6608 - val_accuracy: 0.6679 - val_loss: 0.6628
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.6556 - val_accuracy: 0.6642 - val_loss: 0.6564
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.6697 - val_accuracy: 0.6269 - val_loss: 0.7794
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6836 - val_accuracy: 0.6231 - val_loss: 0.6921
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 0.6792 - val_accuracy: 0.6231 - val_loss: 0.6640
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6649 - val_accuracy: 0.6157 - val_loss: 0.6642
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6663 - val_accuracy: 0.6157 - val_loss: 0.6674
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6673 - val_accuracy: 0.6194 - val_loss: 0.6651
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6582
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6632 - val_accuracy: 0.6455 - val_loss: 0.6555
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.6568 - val_accuracy: 0.6567 - val_loss: 0.6411
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.6585 - val_accuracy: 0.6381 - val_loss: 0.6592
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6552 - val_accuracy: 0.6903 - val_loss: 0.6253
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.6553 - val_accuracy: 0.7015 - val_loss: 0.6257
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5987 - loss: 0.7108 - val_accuracy: 0.6269 - val_loss: 0.6678
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6658 - val_accuracy: 0.6157 - val_loss: 0.6745
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.6755
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6656 - val_accuracy: 0.6157 - val_loss: 0.6706
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6645 - val_accuracy: 0.6194 - val_loss: 0.6642
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6228 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.6670
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6631 - val_accuracy: 0.6157 - val_loss: 0.6630
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6636 - val_accuracy: 0.6231 - val_loss: 0.6691
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6730
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6642 - val_accuracy: 0.6157 - val_loss: 0.6671
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6627 - val_accuracy: 0.6231 - val_loss: 0.6781
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6657 - val_accuracy: 0.6157 - val_loss: 0.6648
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6608 - val_accuracy: 0.6157 - val_loss: 0.6621
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6157 - val_loss: 0.6646
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6157 - val_loss: 0.6729
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6634 - val_accuracy: 0.6231 - val_loss: 0.6709
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.6676
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6664
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6737
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6194 - val_loss: 0.6640
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.6616
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6638 - val_accuracy: 0.6194 - val_loss: 0.6647
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.6633
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6634 - val_accuracy: 0.6194 - val_loss: 0.6673
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.6640
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.6631
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.6758
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6637 - val_accuracy: 0.6194 - val_loss: 0.6614
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6619 - val_accuracy: 0.6231 - val_loss: 0.6659
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6640 - val_accuracy: 0.6231 - val_loss: 0.6635
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6621 - val_accuracy: 0.6231 - val_loss: 0.6648
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6194 - val_loss: 0.6627
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6194 - val_loss: 0.6716
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6231 - val_loss: 0.6615
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6649
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6659
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6231 - val_loss: 0.6614
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.6659
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6194 - val_loss: 0.6676
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.6656
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6739
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6157 - val_loss: 0.6674
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6157 - val_loss: 0.6695
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6645 - val_accuracy: 0.6194 - val_loss: 0.6628
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.6667
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6613 - val_accuracy: 0.6231 - val_loss: 0.6664
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6623
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6661
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6269 - val_loss: 0.6669
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6679
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.6706
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.6612
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.6692
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6612
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6628 - val_accuracy: 0.6194 - val_loss: 0.6676
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6618 - val_accuracy: 0.6231 - val_loss: 0.6621
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6228 - loss: 0.6602 - val_accuracy: 0.6231 - val_loss: 0.6629
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6672
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6194 - val_loss: 0.6621
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6194 - val_loss: 0.6685
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6640 - val_accuracy: 0.6194 - val_loss: 0.6627
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.6663
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.6657
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6627 - val_accuracy: 0.6269 - val_loss: 0.6727
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6622 - val_accuracy: 0.6194 - val_loss: 0.6619
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6614 - val_accuracy: 0.6231 - val_loss: 0.6674
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.6644
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6231 - val_loss: 0.6645
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6776
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.6660
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6634 - val_accuracy: 0.6194 - val_loss: 0.6664
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6635 - val_accuracy: 0.6194 - val_loss: 0.6727
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6642 - val_accuracy: 0.6194 - val_loss: 0.6664
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6194 - val_loss: 0.6645
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6610 - val_accuracy: 0.6231 - val_loss: 0.6643
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6231 - val_loss: 0.6677
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.6700
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.6648
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6612 - val_accuracy: 0.6194 - val_loss: 0.6658
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6603 - val_accuracy: 0.6231 - val_loss: 0.6633
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6618 - val_accuracy: 0.6231 - val_loss: 0.6642
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6231 - val_loss: 0.6642
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6606 - val_accuracy: 0.6231 - val_loss: 0.6633
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6600 - val_accuracy: 0.6194 - val_loss: 0.6651
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6601 - val_accuracy: 0.6231 - val_loss: 0.6668
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6611 - val_accuracy: 0.6194 - val_loss: 0.6646
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6620 - val_accuracy: 0.6231 - val_loss: 0.6636
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6609 - val_accuracy: 0.6194 - val_loss: 0.6625
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6624 - val_accuracy: 0.6231 - val_loss: 0.6615
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6231 - val_loss: 0.6639
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6615 - val_accuracy: 0.6194 - val_loss: 0.6645
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6603 - val_accuracy: 0.6231 - val_loss: 0.6625
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6194 - val_loss: 0.6620
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.6632
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6615 - val_accuracy: 0.6194 - val_loss: 0.6664
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.6656
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.6664
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6196 - loss: 0.6636 - val_accuracy: 0.6231 - val_loss: 0.6698
Epoch 145: early stopping

wandb: Agent Starting Run: 90odfmaa with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4205 - loss: 3.7549 - val_accuracy: 0.3321 - val_loss: 3.0759
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4446 - loss: 2.4200 - val_accuracy: 0.3134 - val_loss: 2.8367
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4446 - loss: 1.5441 - val_accuracy: 0.3918 - val_loss: 1.0189
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5104 - loss: 1.1030 - val_accuracy: 0.4963 - val_loss: 0.8823
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4944 - loss: 1.1565 - val_accuracy: 0.4328 - val_loss: 0.8757
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4735 - loss: 0.9835 - val_accuracy: 0.5448 - val_loss: 0.7686
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5104 - loss: 1.0956 - val_accuracy: 0.6082 - val_loss: 1.0204
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5522 - loss: 0.9830 - val_accuracy: 0.3843 - val_loss: 0.9715
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5457 - loss: 0.9206 - val_accuracy: 0.6194 - val_loss: 0.8682
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5201 - loss: 1.0026 - val_accuracy: 0.5970 - val_loss: 0.6782
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5281 - loss: 1.0599 - val_accuracy: 0.6082 - val_loss: 0.6639
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5393 - loss: 0.9541 - val_accuracy: 0.5037 - val_loss: 0.7482
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5217 - loss: 0.9365 - val_accuracy: 0.6045 - val_loss: 0.6726
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5281 - loss: 0.9498 - val_accuracy: 0.6493 - val_loss: 0.8186
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5409 - loss: 1.0548 - val_accuracy: 0.6567 - val_loss: 0.6593
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5778 - loss: 0.7638 - val_accuracy: 0.6381 - val_loss: 0.9956
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5602 - loss: 0.9474 - val_accuracy: 0.6455 - val_loss: 0.6266
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5618 - loss: 1.0005 - val_accuracy: 0.3881 - val_loss: 1.1509
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5730 - loss: 0.8807 - val_accuracy: 0.6828 - val_loss: 0.6003
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5522 - loss: 0.9589 - val_accuracy: 0.6269 - val_loss: 1.1967
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5602 - loss: 0.9303 - val_accuracy: 0.6306 - val_loss: 1.5812
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5859 - loss: 0.9017 - val_accuracy: 0.6866 - val_loss: 0.6069
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5778 - loss: 0.9047 - val_accuracy: 0.4963 - val_loss: 0.7664
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5843 - loss: 0.8972 - val_accuracy: 0.6754 - val_loss: 0.6835
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5666 - loss: 0.9630 - val_accuracy: 0.6940 - val_loss: 0.6077
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5682 - loss: 0.9076 - val_accuracy: 0.6866 - val_loss: 0.5968
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.8937 - val_accuracy: 0.6194 - val_loss: 0.6383
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.8490 - val_accuracy: 0.6866 - val_loss: 0.6192
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.9133 - val_accuracy: 0.6418 - val_loss: 0.9768
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.7796 - val_accuracy: 0.4328 - val_loss: 1.1345
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5971 - loss: 0.9169 - val_accuracy: 0.6567 - val_loss: 0.7334
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5329 - loss: 1.0524 - val_accuracy: 0.6119 - val_loss: 0.6619
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.7471 - val_accuracy: 0.5261 - val_loss: 0.7401
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5682 - loss: 1.0030 - val_accuracy: 0.6903 - val_loss: 0.5682
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5891 - loss: 0.8326 - val_accuracy: 0.6828 - val_loss: 0.5679
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.7679 - val_accuracy: 0.5448 - val_loss: 0.7216
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5618 - loss: 0.9893 - val_accuracy: 0.6903 - val_loss: 0.6545
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5827 - loss: 0.8710 - val_accuracy: 0.6828 - val_loss: 0.5852
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5522 - loss: 1.0072 - val_accuracy: 0.6530 - val_loss: 1.0080
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.7223 - val_accuracy: 0.7090 - val_loss: 0.5609
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.8446 - val_accuracy: 0.7090 - val_loss: 0.5956
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.8569 - val_accuracy: 0.6493 - val_loss: 1.1952
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.9037 - val_accuracy: 0.7127 - val_loss: 0.5718
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.7209 - val_accuracy: 0.7015 - val_loss: 0.5563
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.9328 - val_accuracy: 0.7127 - val_loss: 0.5930
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6844 - val_accuracy: 0.6343 - val_loss: 1.2399
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5795 - loss: 0.9985 - val_accuracy: 0.6567 - val_loss: 0.9646
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7328 - val_accuracy: 0.5037 - val_loss: 0.7766
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.8545 - val_accuracy: 0.4403 - val_loss: 1.0738
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 0.8521 - val_accuracy: 0.6642 - val_loss: 0.7286
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.7410 - val_accuracy: 0.6493 - val_loss: 1.0972
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.8728 - val_accuracy: 0.7090 - val_loss: 0.5409
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.8317 - val_accuracy: 0.7052 - val_loss: 0.5879
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7568 - val_accuracy: 0.6493 - val_loss: 1.0250
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6710 - val_accuracy: 0.4403 - val_loss: 1.1711
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.8726 - val_accuracy: 0.7351 - val_loss: 0.5654
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.8243 - val_accuracy: 0.7090 - val_loss: 0.6114
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.8603 - val_accuracy: 0.6940 - val_loss: 0.5451
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6249 - val_accuracy: 0.4142 - val_loss: 1.9568
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.9015 - val_accuracy: 0.6903 - val_loss: 0.6726
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.8423 - val_accuracy: 0.7425 - val_loss: 0.5375
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.7726 - val_accuracy: 0.7015 - val_loss: 0.6633
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6825 - val_accuracy: 0.7201 - val_loss: 0.5517
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7735 - val_accuracy: 0.7276 - val_loss: 0.5496
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.9044 - val_accuracy: 0.6306 - val_loss: 0.6638
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6865 - val_accuracy: 0.7313 - val_loss: 0.5724
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.7363 - val_accuracy: 0.5112 - val_loss: 0.7718
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.9132 - val_accuracy: 0.6866 - val_loss: 0.7092
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.7867 - val_accuracy: 0.6567 - val_loss: 1.0384
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6982 - loss: 0.6624 - val_accuracy: 0.6381 - val_loss: 0.6617
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.8586 - val_accuracy: 0.7052 - val_loss: 0.6249
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6993 - val_accuracy: 0.6418 - val_loss: 1.2069
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.8480 - val_accuracy: 0.6940 - val_loss: 0.5452
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6557 - val_accuracy: 0.7052 - val_loss: 0.5236
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.8104 - val_accuracy: 0.7127 - val_loss: 0.5817
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.7860 - val_accuracy: 0.7090 - val_loss: 0.5742
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.7707 - val_accuracy: 0.7090 - val_loss: 0.5240
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.7440 - val_accuracy: 0.7090 - val_loss: 0.6007
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.8900 - val_accuracy: 0.4366 - val_loss: 1.2795
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6924 - val_accuracy: 0.7463 - val_loss: 0.5229
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6765 - val_accuracy: 0.4963 - val_loss: 0.8198
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.9163 - val_accuracy: 0.7537 - val_loss: 0.5217
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.7676 - val_accuracy: 0.7575 - val_loss: 0.5146
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7197 - val_accuracy: 0.6940 - val_loss: 0.6655
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7293 - val_accuracy: 0.6493 - val_loss: 1.1755
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.7719 - val_accuracy: 0.6343 - val_loss: 1.8200
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.7126 - val_accuracy: 0.7612 - val_loss: 0.5196
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.8936 - val_accuracy: 0.6343 - val_loss: 0.6428
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.8882 - val_accuracy: 0.6828 - val_loss: 0.5991
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6121 - val_accuracy: 0.6754 - val_loss: 0.8294
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7982 - val_accuracy: 0.6978 - val_loss: 0.5890
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.7298 - val_accuracy: 0.6642 - val_loss: 1.1430
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7661 - val_accuracy: 0.6828 - val_loss: 0.6052
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6838 - loss: 0.7139 - val_accuracy: 0.7575 - val_loss: 0.5347
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.7823 - val_accuracy: 0.5597 - val_loss: 0.7493
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.7278 - val_accuracy: 0.6604 - val_loss: 0.6358
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 0.7201 - val_accuracy: 0.6642 - val_loss: 0.8524
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.7965 - val_accuracy: 0.6642 - val_loss: 0.9350
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6912 - val_accuracy: 0.7687 - val_loss: 0.5131
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6869 - val_accuracy: 0.5410 - val_loss: 0.7925
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.7424 - val_accuracy: 0.5746 - val_loss: 0.7372
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7755 - val_accuracy: 0.4627 - val_loss: 1.0827
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.7768 - val_accuracy: 0.7537 - val_loss: 0.5106
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.8365 - val_accuracy: 0.6455 - val_loss: 1.0105
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6845 - val_accuracy: 0.5784 - val_loss: 0.7428
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.7071 - val_accuracy: 0.6940 - val_loss: 0.6080
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.7915 - val_accuracy: 0.6455 - val_loss: 0.6604
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.8361 - val_accuracy: 0.7724 - val_loss: 0.5135
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7366 - val_accuracy: 0.6828 - val_loss: 0.6088
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7118 - val_accuracy: 0.5299 - val_loss: 0.8429
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6740 - val_accuracy: 0.7948 - val_loss: 0.5240
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6446 - val_accuracy: 0.7500 - val_loss: 0.4980
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.8346 - val_accuracy: 0.5261 - val_loss: 0.8380
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7560 - val_accuracy: 0.7724 - val_loss: 0.5074
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.7332 - val_accuracy: 0.7799 - val_loss: 0.4978
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7143 - loss: 0.6446 - val_accuracy: 0.6978 - val_loss: 0.5756
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7895 - val_accuracy: 0.6530 - val_loss: 0.9750
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6472 - val_accuracy: 0.7313 - val_loss: 0.5054
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.8012 - val_accuracy: 0.6493 - val_loss: 1.0936
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.6490 - val_accuracy: 0.5746 - val_loss: 0.7570
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.8188 - val_accuracy: 0.7612 - val_loss: 0.5059
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6522 - val_accuracy: 0.6194 - val_loss: 0.6950
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.7363 - val_accuracy: 0.6716 - val_loss: 0.8930
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6349 - val_accuracy: 0.7127 - val_loss: 0.5436
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6618 - val_accuracy: 0.7537 - val_loss: 0.5684
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.7956 - val_accuracy: 0.6716 - val_loss: 0.8805
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6782 - val_accuracy: 0.6567 - val_loss: 1.1938
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.7400 - val_accuracy: 0.7090 - val_loss: 0.5296
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7419 - val_accuracy: 0.6754 - val_loss: 0.8627
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.7395 - val_accuracy: 0.7612 - val_loss: 0.4947
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6910 - val_accuracy: 0.6716 - val_loss: 0.9437
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.7589 - val_accuracy: 0.7090 - val_loss: 0.5608
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6459 - val_accuracy: 0.6754 - val_loss: 0.6182
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7091 - val_accuracy: 0.7463 - val_loss: 0.4921
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6580 - val_accuracy: 0.6567 - val_loss: 1.0424
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.7327 - val_accuracy: 0.6418 - val_loss: 1.4479
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.7531 - val_accuracy: 0.6978 - val_loss: 0.5890
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.7604 - val_accuracy: 0.5597 - val_loss: 0.7874
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7114 - val_accuracy: 0.7537 - val_loss: 0.4919
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4954 - val_accuracy: 0.7985 - val_loss: 0.5156
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.8711 - val_accuracy: 0.4851 - val_loss: 0.9897
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5916 - val_accuracy: 0.5933 - val_loss: 0.7338
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7513 - val_accuracy: 0.6978 - val_loss: 0.6081
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6079 - val_accuracy: 0.7537 - val_loss: 0.4892
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.6851 - val_accuracy: 0.6754 - val_loss: 0.6370
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7366 - val_accuracy: 0.7910 - val_loss: 0.5163
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.7668 - val_accuracy: 0.6754 - val_loss: 0.8804
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.6776 - val_accuracy: 0.6978 - val_loss: 0.6086
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.6874 - val_accuracy: 0.7575 - val_loss: 0.4906
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.6361 - val_accuracy: 0.6828 - val_loss: 0.8223
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.7379 - val_accuracy: 0.6940 - val_loss: 0.6424
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6723 - val_accuracy: 0.4851 - val_loss: 1.0219
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7688 - val_accuracy: 0.6642 - val_loss: 0.6371
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5855 - val_accuracy: 0.7761 - val_loss: 0.5471
Epoch 155/5000

wandb: Agent Starting Run: e5sbx1al with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6116 - loss: 20.3240 - val_accuracy: 0.6269 - val_loss: 15.4710
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 12.1498 - val_accuracy: 0.6269 - val_loss: 7.7175
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5939 - loss: 4.5900 - val_accuracy: 0.4216 - val_loss: 1.4132
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3884 - loss: 2.3381 - val_accuracy: 0.2761 - val_loss: 1.6016
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5056 - loss: 1.4233 - val_accuracy: 0.4888 - val_loss: 1.6037
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4462 - loss: 1.3082 - val_accuracy: 0.2836 - val_loss: 1.3678
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4510 - loss: 1.1634 - val_accuracy: 0.4701 - val_loss: 1.1700
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4222 - loss: 1.0371 - val_accuracy: 0.4291 - val_loss: 1.0670
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4623 - loss: 0.9492 - val_accuracy: 0.4515 - val_loss: 1.0023
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4575 - loss: 0.9025 - val_accuracy: 0.4590 - val_loss: 0.9407
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4655 - loss: 0.8571 - val_accuracy: 0.4813 - val_loss: 0.8893
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4735 - loss: 0.8083 - val_accuracy: 0.3881 - val_loss: 0.8609
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4783 - loss: 0.7771 - val_accuracy: 0.4813 - val_loss: 0.8084
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4944 - loss: 0.7558 - val_accuracy: 0.4925 - val_loss: 0.7617
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5281 - loss: 0.7257 - val_accuracy: 0.4925 - val_loss: 0.7334
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5361 - loss: 0.7009 - val_accuracy: 0.5261 - val_loss: 0.7094
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5746 - loss: 0.6847 - val_accuracy: 0.5560 - val_loss: 0.6921
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.6816 - val_accuracy: 0.6157 - val_loss: 0.6767
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6657
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6570 - val_accuracy: 0.6194 - val_loss: 0.6583
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.6570 - val_accuracy: 0.6343 - val_loss: 0.6510
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.6544 - val_accuracy: 0.6903 - val_loss: 0.6562
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.6525 - val_accuracy: 0.6306 - val_loss: 0.6411
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.6464 - val_accuracy: 0.6381 - val_loss: 0.6383
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6439 - val_accuracy: 0.5672 - val_loss: 0.6690
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6626 - val_accuracy: 0.5224 - val_loss: 0.6980
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.6761 - val_accuracy: 0.6455 - val_loss: 0.6329
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6444 - val_accuracy: 0.6828 - val_loss: 0.6313
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.6398 - val_accuracy: 0.6306 - val_loss: 0.6408
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.6472 - val_accuracy: 0.6306 - val_loss: 0.6379
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.6466 - val_accuracy: 0.6679 - val_loss: 0.6296
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6425 - val_accuracy: 0.6754 - val_loss: 0.6288
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6392 - val_accuracy: 0.6231 - val_loss: 0.6527
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.6511 - val_accuracy: 0.6978 - val_loss: 0.6329
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6466 - val_accuracy: 0.6716 - val_loss: 0.6271
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6440 - val_accuracy: 0.6306 - val_loss: 0.6397
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6390 - val_accuracy: 0.6903 - val_loss: 0.6293
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6426 - val_accuracy: 0.6716 - val_loss: 0.6419
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6406 - val_accuracy: 0.6418 - val_loss: 0.6466
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.6505 - val_accuracy: 0.6306 - val_loss: 0.6410
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6595 - val_accuracy: 0.6343 - val_loss: 0.6397
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.6525 - val_accuracy: 0.6455 - val_loss: 0.6451
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.6425 - val_accuracy: 0.6978 - val_loss: 0.6263
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6374 - val_accuracy: 0.6828 - val_loss: 0.6262
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6375 - val_accuracy: 0.6940 - val_loss: 0.6278
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.6436 - val_accuracy: 0.5597 - val_loss: 0.6674
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6606 - val_accuracy: 0.5746 - val_loss: 0.6594
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6774 - val_accuracy: 0.5634 - val_loss: 0.6659
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.6410 - val_accuracy: 0.6754 - val_loss: 0.6371
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6372 - val_accuracy: 0.6493 - val_loss: 0.6361
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6679 - val_accuracy: 0.6978 - val_loss: 0.6240
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6363 - val_accuracy: 0.6604 - val_loss: 0.6288
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6397 - val_accuracy: 0.6978 - val_loss: 0.6230
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.6410 - val_accuracy: 0.6978 - val_loss: 0.6246
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6346 - val_accuracy: 0.6604 - val_loss: 0.6300
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6376 - val_accuracy: 0.6940 - val_loss: 0.6238
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.6378 - val_accuracy: 0.7015 - val_loss: 0.6247
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6316 - val_accuracy: 0.5560 - val_loss: 0.6718
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.6650 - val_accuracy: 0.6754 - val_loss: 0.6358
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6468 - val_accuracy: 0.6978 - val_loss: 0.6221
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6581 - loss: 0.6349 - val_accuracy: 0.6978 - val_loss: 0.6230
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6346 - val_accuracy: 0.6866 - val_loss: 0.6200
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6334 - val_accuracy: 0.7015 - val_loss: 0.6247
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6399 - val_accuracy: 0.6978 - val_loss: 0.6220
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6411 - val_accuracy: 0.6455 - val_loss: 0.6424
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.6374 - val_accuracy: 0.7015 - val_loss: 0.6233
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6335 - val_accuracy: 0.6978 - val_loss: 0.6224
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6329 - val_accuracy: 0.6604 - val_loss: 0.6301
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6386 - val_accuracy: 0.6754 - val_loss: 0.6246
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6394 - val_accuracy: 0.6866 - val_loss: 0.6198
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.6353 - val_accuracy: 0.6828 - val_loss: 0.6236
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.6344 - val_accuracy: 0.6903 - val_loss: 0.6212
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6352 - val_accuracy: 0.6903 - val_loss: 0.6218
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6399 - val_accuracy: 0.6940 - val_loss: 0.6215
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6371 - val_accuracy: 0.6791 - val_loss: 0.6186
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.6451 - val_accuracy: 0.6381 - val_loss: 0.6451
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6404 - loss: 0.6534 - val_accuracy: 0.6567 - val_loss: 0.6342
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6346 - val_accuracy: 0.6866 - val_loss: 0.6182
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6418 - val_accuracy: 0.6903 - val_loss: 0.6189
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6300 - val_accuracy: 0.6791 - val_loss: 0.6331
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.6448 - val_accuracy: 0.6903 - val_loss: 0.6209
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.6491 - val_accuracy: 0.6604 - val_loss: 0.6301
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.6558 - val_accuracy: 0.6604 - val_loss: 0.6308
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.6426 - val_accuracy: 0.6418 - val_loss: 0.6561
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6435 - val_accuracy: 0.6381 - val_loss: 0.6598
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6675 - val_accuracy: 0.6754 - val_loss: 0.6266
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6588 - val_accuracy: 0.6679 - val_loss: 0.6350
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6896 - val_accuracy: 0.6306 - val_loss: 0.6450
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6378 - val_accuracy: 0.6903 - val_loss: 0.6159
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.6319 - val_accuracy: 0.6978 - val_loss: 0.6178
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6344 - val_accuracy: 0.6903 - val_loss: 0.6232
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.6481 - val_accuracy: 0.7052 - val_loss: 0.6207
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 0.6299 - val_accuracy: 0.6866 - val_loss: 0.6163
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.6309 - val_accuracy: 0.6866 - val_loss: 0.6158
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.6276 - val_accuracy: 0.6866 - val_loss: 0.6161
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6269 - val_accuracy: 0.6978 - val_loss: 0.6173
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6424 - val_accuracy: 0.6343 - val_loss: 0.6434
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.6617 - val_accuracy: 0.6791 - val_loss: 0.6276
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6485 - loss: 0.6390 - val_accuracy: 0.7015 - val_loss: 0.6157
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6347 - val_accuracy: 0.6940 - val_loss: 0.6221
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6303 - val_accuracy: 0.6343 - val_loss: 0.6426
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6439 - val_accuracy: 0.6978 - val_loss: 0.6181
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6421 - val_accuracy: 0.6903 - val_loss: 0.6228
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6326 - val_accuracy: 0.6604 - val_loss: 0.6360
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6317 - val_accuracy: 0.6940 - val_loss: 0.6200
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.6272 - val_accuracy: 0.7015 - val_loss: 0.6154
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.6281 - val_accuracy: 0.6493 - val_loss: 0.6376
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.6325 - val_accuracy: 0.6903 - val_loss: 0.6127
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6385 - val_accuracy: 0.6903 - val_loss: 0.6264
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6394 - val_accuracy: 0.6978 - val_loss: 0.6238
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6415 - val_accuracy: 0.6679 - val_loss: 0.6341
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6421 - val_accuracy: 0.6940 - val_loss: 0.6171
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.6400 - val_accuracy: 0.7015 - val_loss: 0.6157
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 0.6293 - val_accuracy: 0.6903 - val_loss: 0.6216
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6257 - val_accuracy: 0.6903 - val_loss: 0.6276
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.6261 - val_accuracy: 0.5746 - val_loss: 0.6644
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6375 - val_accuracy: 0.7052 - val_loss: 0.6124
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.6539 - val_accuracy: 0.6791 - val_loss: 0.6207
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6581 - loss: 0.6360 - val_accuracy: 0.6940 - val_loss: 0.6129
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.6326 - val_accuracy: 0.6866 - val_loss: 0.6173
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6402 - val_accuracy: 0.7052 - val_loss: 0.6117
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6330 - val_accuracy: 0.6940 - val_loss: 0.6195
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.6232 - val_accuracy: 0.6866 - val_loss: 0.6169
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.6476 - val_accuracy: 0.6418 - val_loss: 0.7193
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6915 - val_accuracy: 0.6381 - val_loss: 0.7390
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.6502 - val_accuracy: 0.6567 - val_loss: 0.6485
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.6432 - val_accuracy: 0.6493 - val_loss: 0.6614
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6563 - val_accuracy: 0.6642 - val_loss: 0.6349
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6521 - val_accuracy: 0.6493 - val_loss: 0.6749
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6979 - val_accuracy: 0.6642 - val_loss: 0.6366
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6485 - val_accuracy: 0.7090 - val_loss: 0.6122
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.6377 - val_accuracy: 0.6978 - val_loss: 0.6249
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6315 - val_accuracy: 0.7090 - val_loss: 0.6093
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.6240 - val_accuracy: 0.6679 - val_loss: 0.6315
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.6309 - val_accuracy: 0.7090 - val_loss: 0.6124
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.6548 - val_accuracy: 0.6567 - val_loss: 0.6471
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6465 - val_accuracy: 0.6679 - val_loss: 0.6346
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6645 - loss: 0.6268 - val_accuracy: 0.6866 - val_loss: 0.6178
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.6373 - val_accuracy: 0.6978 - val_loss: 0.6177
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.6259 - val_accuracy: 0.6679 - val_loss: 0.6316
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.6276 - val_accuracy: 0.6642 - val_loss: 0.6329
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6291 - val_accuracy: 0.6567 - val_loss: 0.6436
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.6248 - val_accuracy: 0.6903 - val_loss: 0.6064
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6218 - val_accuracy: 0.6978 - val_loss: 0.6207
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.6269 - val_accuracy: 0.6269 - val_loss: 0.6431
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6325 - val_accuracy: 0.6418 - val_loss: 0.6360
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6422 - val_accuracy: 0.5821 - val_loss: 0.6648
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6213 - val_accuracy: 0.5970 - val_loss: 0.6489
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6369 - val_accuracy: 0.6119 - val_loss: 0.6434
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6387 - val_accuracy: 0.6306 - val_loss: 0.6395
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.6266 - val_accuracy: 0.6940 - val_loss: 0.6026
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.6122 - val_accuracy: 0.6940 - val_loss: 0.6024
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.6137 - val_accuracy: 0.6978 - val_loss: 0.6023
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6148 - val_accuracy: 0.7090 - val_loss: 0.6032
Epoch 155/5000

wandb: Agent Starting Run: v682rl1e with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6116 - loss: 55.0465 - val_accuracy: 0.6269 - val_loss: 0.8594
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7892 - val_accuracy: 0.6269 - val_loss: 0.7533
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7277 - val_accuracy: 0.6269 - val_loss: 0.7210
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7130 - val_accuracy: 0.6269 - val_loss: 0.7033
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.7037 - val_accuracy: 0.6269 - val_loss: 0.6889
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6957 - val_accuracy: 0.6269 - val_loss: 0.6769
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6897 - val_accuracy: 0.6269 - val_loss: 0.6688
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6870 - val_accuracy: 0.6306 - val_loss: 0.6572
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6888 - val_accuracy: 0.6269 - val_loss: 0.6666
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6791 - val_accuracy: 0.6231 - val_loss: 0.6556
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6803 - val_accuracy: 0.6269 - val_loss: 0.6527
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6765 - val_accuracy: 0.6269 - val_loss: 0.6549
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6752 - val_accuracy: 0.6269 - val_loss: 0.6626
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6739 - val_accuracy: 0.6269 - val_loss: 0.6533
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6729 - val_accuracy: 0.6306 - val_loss: 0.6554
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6719 - val_accuracy: 0.6343 - val_loss: 0.6532
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6779 - val_accuracy: 0.6343 - val_loss: 0.6682
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6772 - val_accuracy: 0.6306 - val_loss: 0.6669
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6760 - val_accuracy: 0.6306 - val_loss: 0.6663
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6751 - val_accuracy: 0.6269 - val_loss: 0.6673
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6745 - val_accuracy: 0.6269 - val_loss: 0.6652
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6736 - val_accuracy: 0.6306 - val_loss: 0.6648
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6729 - val_accuracy: 0.6306 - val_loss: 0.6625
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6100 - loss: 0.6724 - val_accuracy: 0.6269 - val_loss: 0.6632
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6718 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6712 - val_accuracy: 0.6306 - val_loss: 0.6632
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6706 - val_accuracy: 0.6269 - val_loss: 0.6635
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6702 - val_accuracy: 0.6269 - val_loss: 0.6623
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6696 - val_accuracy: 0.6269 - val_loss: 0.6628
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6693 - val_accuracy: 0.6269 - val_loss: 0.6627
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6687 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.6628
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6681 - val_accuracy: 0.6269 - val_loss: 0.6638
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6083 - loss: 0.6679 - val_accuracy: 0.6269 - val_loss: 0.6620
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6677 - val_accuracy: 0.6269 - val_loss: 0.6629
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6673 - val_accuracy: 0.6269 - val_loss: 0.6635
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6669 - val_accuracy: 0.6306 - val_loss: 0.6649
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6669 - val_accuracy: 0.6269 - val_loss: 0.6621
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.6643
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6662 - val_accuracy: 0.6306 - val_loss: 0.6644
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.6656
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.6655
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6083 - loss: 0.6656 - val_accuracy: 0.6269 - val_loss: 0.6653
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6653 - val_accuracy: 0.6231 - val_loss: 0.6625
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6652 - val_accuracy: 0.6231 - val_loss: 0.6637
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.6646
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.6649
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6641
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6646 - val_accuracy: 0.6269 - val_loss: 0.6649
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6644 - val_accuracy: 0.6269 - val_loss: 0.6649
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6621
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6639 - val_accuracy: 0.6269 - val_loss: 0.6634
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.6605
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6640 - val_accuracy: 0.6231 - val_loss: 0.6623
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6637 - val_accuracy: 0.6231 - val_loss: 0.6620
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6635 - val_accuracy: 0.6231 - val_loss: 0.6631
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6132 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.6622
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6635 - val_accuracy: 0.6231 - val_loss: 0.6622
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6633 - val_accuracy: 0.6269 - val_loss: 0.6639
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.6640
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6647
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6231 - val_loss: 0.6588
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.6606
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6269 - val_loss: 0.6605
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6269 - val_loss: 0.6606
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6627 - val_accuracy: 0.6231 - val_loss: 0.6605
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6628 - val_accuracy: 0.6231 - val_loss: 0.6618
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6629 - val_accuracy: 0.6231 - val_loss: 0.6599
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.6590
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6628 - val_accuracy: 0.6194 - val_loss: 0.6597
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6157 - val_loss: 0.6599
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.6605
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.6611
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.6607
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6194 - val_loss: 0.6610
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6119 - val_loss: 0.6600
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6157 - val_loss: 0.6611
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6623 - val_accuracy: 0.6157 - val_loss: 0.6609
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.6611
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.6612
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6157 - val_loss: 0.6616
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.6618
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6623
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6119 - val_loss: 0.6612
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6619
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6626
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6119 - val_loss: 0.6611
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6119 - val_loss: 0.6614
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.6615
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.6620
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.6620
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6157 - val_loss: 0.6628
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6628
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6157 - val_loss: 0.6622
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6621
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.6622
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6615 - val_accuracy: 0.6119 - val_loss: 0.6618
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.6619
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6611 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6613 - val_accuracy: 0.6119 - val_loss: 0.6621
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6612 - val_accuracy: 0.6157 - val_loss: 0.6624
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6624
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6157 - val_loss: 0.6623
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6594 - val_accuracy: 0.6157 - val_loss: 0.6611
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6577 - val_accuracy: 0.6157 - val_loss: 0.6601
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6574 - val_accuracy: 0.6119 - val_loss: 0.6564
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6574 - val_accuracy: 0.6119 - val_loss: 0.6584
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6576 - val_accuracy: 0.6119 - val_loss: 0.6572
Epoch 111: early stopping

wandb: Agent Starting Run: 3o8xautx with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5971 - loss: 2.5343 - val_accuracy: 0.6978 - val_loss: 1.4800
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 1.8075 - val_accuracy: 0.6940 - val_loss: 1.1898
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 1.6843 - val_accuracy: 0.7015 - val_loss: 1.0760
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 1.4218 - val_accuracy: 0.5784 - val_loss: 1.1571
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 1.3216 - val_accuracy: 0.6903 - val_loss: 1.0077
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 1.1998 - val_accuracy: 0.6978 - val_loss: 0.8232
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 1.0975 - val_accuracy: 0.7015 - val_loss: 0.7749
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.9137 - val_accuracy: 0.7090 - val_loss: 0.7115
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.9906 - val_accuracy: 0.7015 - val_loss: 0.6623
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.8265 - val_accuracy: 0.6716 - val_loss: 1.1098
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.8592 - val_accuracy: 0.6903 - val_loss: 0.6613
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.8564 - val_accuracy: 0.6866 - val_loss: 0.6423
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.8059 - val_accuracy: 0.4328 - val_loss: 1.1204
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.8033 - val_accuracy: 0.7015 - val_loss: 0.6128
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.8090 - val_accuracy: 0.6940 - val_loss: 0.6289
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.7776 - val_accuracy: 0.7090 - val_loss: 0.6607
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.7742 - val_accuracy: 0.6978 - val_loss: 0.6148
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.7333 - val_accuracy: 0.6455 - val_loss: 0.9725
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.8131 - val_accuracy: 0.6530 - val_loss: 0.9884
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.8064 - val_accuracy: 0.5187 - val_loss: 0.7518
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6533 - loss: 0.7219 - val_accuracy: 0.7164 - val_loss: 0.5718
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.7772 - val_accuracy: 0.7127 - val_loss: 0.5844
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.7503 - val_accuracy: 0.7201 - val_loss: 0.5641
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.7151 - val_accuracy: 0.6866 - val_loss: 0.6773
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.7712 - val_accuracy: 0.4328 - val_loss: 0.8721
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.7117 - val_accuracy: 0.6642 - val_loss: 0.7338
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.7303 - val_accuracy: 0.6381 - val_loss: 0.9934
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.7154 - val_accuracy: 0.7201 - val_loss: 0.5551
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.8016 - val_accuracy: 0.7052 - val_loss: 0.6167
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6565 - val_accuracy: 0.7351 - val_loss: 0.5488
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.7347 - val_accuracy: 0.7500 - val_loss: 0.5796
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.6847 - val_accuracy: 0.7127 - val_loss: 0.5568
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.6953 - val_accuracy: 0.6381 - val_loss: 0.8610
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.7422 - val_accuracy: 0.7351 - val_loss: 0.5605
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.6682 - val_accuracy: 0.7463 - val_loss: 0.5645
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.7324 - val_accuracy: 0.7090 - val_loss: 0.5930
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.6895 - val_accuracy: 0.7537 - val_loss: 0.5707
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6469 - loss: 0.7605 - val_accuracy: 0.7201 - val_loss: 0.5534
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6906 - val_accuracy: 0.6642 - val_loss: 0.6493
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.7515 - val_accuracy: 0.7052 - val_loss: 0.5843
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.6819 - val_accuracy: 0.6418 - val_loss: 0.7347
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5955 - loss: 0.7842 - val_accuracy: 0.6567 - val_loss: 0.7104
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.6771 - val_accuracy: 0.7500 - val_loss: 0.5622
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6613 - val_accuracy: 0.4179 - val_loss: 1.1044
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.7163 - val_accuracy: 0.7500 - val_loss: 0.5429
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.7257 - val_accuracy: 0.7463 - val_loss: 0.5744
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.7114 - val_accuracy: 0.7500 - val_loss: 0.5509
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6502 - val_accuracy: 0.7500 - val_loss: 0.5602
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7597 - val_accuracy: 0.4925 - val_loss: 0.7912
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6581 - loss: 0.6869 - val_accuracy: 0.6754 - val_loss: 0.6378
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.6954 - val_accuracy: 0.6306 - val_loss: 0.8915
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.7480 - val_accuracy: 0.6940 - val_loss: 0.6016
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6698 - val_accuracy: 0.7276 - val_loss: 0.5329
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.6153 - val_accuracy: 0.6306 - val_loss: 0.8589
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.6881 - val_accuracy: 0.6493 - val_loss: 0.6882
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.7915 - val_accuracy: 0.6343 - val_loss: 0.7545
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.5961 - val_accuracy: 0.6231 - val_loss: 0.9304
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6434 - val_accuracy: 0.4254 - val_loss: 1.2904
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7097 - val_accuracy: 0.4366 - val_loss: 0.9748
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.7576 - val_accuracy: 0.7463 - val_loss: 0.5252
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5565 - val_accuracy: 0.7127 - val_loss: 0.5220
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.7658 - val_accuracy: 0.7276 - val_loss: 0.5180
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.6449 - val_accuracy: 0.7127 - val_loss: 0.5635
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6254 - val_accuracy: 0.7090 - val_loss: 0.5716
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6123 - val_accuracy: 0.7388 - val_loss: 0.5251
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6399 - val_accuracy: 0.6530 - val_loss: 0.6710
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6377 - val_accuracy: 0.7500 - val_loss: 0.5824
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6365 - val_accuracy: 0.6791 - val_loss: 0.6430
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6132 - val_accuracy: 0.6231 - val_loss: 0.9286
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6967 - val_accuracy: 0.7537 - val_loss: 0.5391
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.7281 - val_accuracy: 0.6978 - val_loss: 0.6397
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6202 - val_accuracy: 0.7052 - val_loss: 0.6312
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7005 - val_accuracy: 0.7425 - val_loss: 0.5086
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7368 - loss: 0.5388 - val_accuracy: 0.6455 - val_loss: 0.6852
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6356 - loss: 0.7847 - val_accuracy: 0.7351 - val_loss: 0.5128
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5595 - val_accuracy: 0.6231 - val_loss: 0.8534
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.6858 - val_accuracy: 0.6493 - val_loss: 0.7142
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6523 - val_accuracy: 0.4478 - val_loss: 1.0331
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5953 - val_accuracy: 0.7388 - val_loss: 0.6099
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.6166 - val_accuracy: 0.6381 - val_loss: 0.6707
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.6641 - val_accuracy: 0.7649 - val_loss: 0.5426
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6532 - val_accuracy: 0.7537 - val_loss: 0.5034
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7308 - val_accuracy: 0.7463 - val_loss: 0.5796
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6292 - val_accuracy: 0.6194 - val_loss: 0.8360
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.6692 - val_accuracy: 0.6903 - val_loss: 0.6306
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6739 - val_accuracy: 0.7276 - val_loss: 0.5150
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5340 - val_accuracy: 0.6231 - val_loss: 1.0909
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.7703 - val_accuracy: 0.7575 - val_loss: 0.5700
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5521 - val_accuracy: 0.7612 - val_loss: 0.4993
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6629 - val_accuracy: 0.7463 - val_loss: 0.5736
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6719 - val_accuracy: 0.7351 - val_loss: 0.5000
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5230 - val_accuracy: 0.7201 - val_loss: 0.5385
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6656 - val_accuracy: 0.6604 - val_loss: 0.6647
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.6719 - val_accuracy: 0.7276 - val_loss: 0.5412
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6260 - val_accuracy: 0.7351 - val_loss: 0.5060
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5545 - val_accuracy: 0.6716 - val_loss: 0.6922
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6982 - loss: 0.6999 - val_accuracy: 0.7612 - val_loss: 0.5020
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5544 - val_accuracy: 0.6940 - val_loss: 0.6388
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6575 - val_accuracy: 0.7537 - val_loss: 0.5474
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6393 - val_accuracy: 0.7239 - val_loss: 0.5264
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5893 - val_accuracy: 0.7276 - val_loss: 0.5207
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5821 - val_accuracy: 0.7612 - val_loss: 0.5491
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.6835 - val_accuracy: 0.7799 - val_loss: 0.5000
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5425 - val_accuracy: 0.7612 - val_loss: 0.4876
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.6748 - val_accuracy: 0.6642 - val_loss: 0.6906
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5555 - val_accuracy: 0.7612 - val_loss: 0.5208
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5718 - val_accuracy: 0.7239 - val_loss: 0.5365
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5676 - val_accuracy: 0.7351 - val_loss: 0.5003
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.6517 - val_accuracy: 0.7276 - val_loss: 0.5357
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6634 - val_accuracy: 0.7313 - val_loss: 0.5400
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5889 - val_accuracy: 0.6343 - val_loss: 0.7894
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5897 - val_accuracy: 0.6269 - val_loss: 0.8075
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5624 - val_accuracy: 0.7873 - val_loss: 0.4983
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6024 - val_accuracy: 0.6530 - val_loss: 0.7881
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5753 - val_accuracy: 0.7612 - val_loss: 0.5178
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5991 - val_accuracy: 0.6231 - val_loss: 0.9366
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.6243 - val_accuracy: 0.7351 - val_loss: 0.5408
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5726 - val_accuracy: 0.7388 - val_loss: 0.5703
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7496 - loss: 0.5812 - val_accuracy: 0.6754 - val_loss: 0.6866
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5046 - val_accuracy: 0.7276 - val_loss: 0.5543
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.6261 - val_accuracy: 0.6754 - val_loss: 0.6846
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6010 - val_accuracy: 0.7351 - val_loss: 0.5083
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5774 - val_accuracy: 0.7463 - val_loss: 0.5572
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5524 - val_accuracy: 0.6530 - val_loss: 0.7680
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5685 - val_accuracy: 0.7351 - val_loss: 0.5046
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5363 - val_accuracy: 0.7388 - val_loss: 0.5789
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5969 - val_accuracy: 0.7127 - val_loss: 0.6374
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5527 - val_accuracy: 0.7500 - val_loss: 0.5000
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5749 - val_accuracy: 0.6903 - val_loss: 0.6277
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6347 - val_accuracy: 0.7836 - val_loss: 0.4998
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4615 - val_accuracy: 0.4701 - val_loss: 1.1526
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.6902 - val_accuracy: 0.7351 - val_loss: 0.5783
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.6053 - val_accuracy: 0.7948 - val_loss: 0.4853
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5234 - val_accuracy: 0.7799 - val_loss: 0.5233
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6079 - val_accuracy: 0.7649 - val_loss: 0.5482
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5478 - val_accuracy: 0.7873 - val_loss: 0.5033
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5825 - val_accuracy: 0.7910 - val_loss: 0.4908
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5621 - val_accuracy: 0.7575 - val_loss: 0.5604
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5385 - val_accuracy: 0.7649 - val_loss: 0.4850
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5145 - val_accuracy: 0.7761 - val_loss: 0.5255
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6370 - val_accuracy: 0.7799 - val_loss: 0.5309
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5201 - val_accuracy: 0.7649 - val_loss: 0.5527
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5489 - val_accuracy: 0.7985 - val_loss: 0.4865
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5375 - val_accuracy: 0.7127 - val_loss: 0.6465
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7721 - loss: 0.5184 - val_accuracy: 0.7836 - val_loss: 0.4954
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5970 - val_accuracy: 0.7836 - val_loss: 0.5110
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5306 - val_accuracy: 0.7463 - val_loss: 0.5884
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5361 - val_accuracy: 0.5410 - val_loss: 0.9115
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.6132 - val_accuracy: 0.7537 - val_loss: 0.5763
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4954 - val_accuracy: 0.7724 - val_loss: 0.5552
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.6067 - val_accuracy: 0.7463 - val_loss: 0.5624
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5272 - val_accuracy: 0.6306 - val_loss: 0.8887
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5538 - val_accuracy: 0.7910 - val_loss: 0.4997
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.6243 - val_accuracy: 0.6567 - val_loss: 0.7947
Epoch 155/5000

wandb: Agent Starting Run: 6sesb2mp with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5345 - loss: 2.7933 - val_accuracy: 0.4067 - val_loss: 1.7773
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4607 - loss: 1.7508 - val_accuracy: 0.6343 - val_loss: 1.7081
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4719 - loss: 1.4885 - val_accuracy: 0.6493 - val_loss: 1.3971
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5217 - loss: 1.3731 - val_accuracy: 0.4701 - val_loss: 1.1874
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5538 - loss: 1.1031 - val_accuracy: 0.4701 - val_loss: 1.0911
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5104 - loss: 0.9973 - val_accuracy: 0.4963 - val_loss: 0.8920
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5265 - loss: 0.8799 - val_accuracy: 0.6567 - val_loss: 0.8047
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5650 - loss: 0.8014 - val_accuracy: 0.6530 - val_loss: 0.7307
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5939 - loss: 0.7306 - val_accuracy: 0.7090 - val_loss: 0.6943
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.6855 - val_accuracy: 0.7015 - val_loss: 0.6597
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6563 - val_accuracy: 0.6530 - val_loss: 0.6846
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6317 - val_accuracy: 0.7127 - val_loss: 0.6274
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6301 - val_accuracy: 0.6828 - val_loss: 0.6386
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.6015 - val_accuracy: 0.6754 - val_loss: 0.6600
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.6065 - val_accuracy: 0.7164 - val_loss: 0.6363
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.6098 - val_accuracy: 0.7090 - val_loss: 0.6334
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.5866 - val_accuracy: 0.7313 - val_loss: 0.6270
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.5868 - val_accuracy: 0.7015 - val_loss: 0.6734
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.5798 - val_accuracy: 0.7052 - val_loss: 0.6329
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.5872 - val_accuracy: 0.6903 - val_loss: 0.6535
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6091 - val_accuracy: 0.7425 - val_loss: 0.6604
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6165 - val_accuracy: 0.7351 - val_loss: 0.6658
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6790 - loss: 0.5992 - val_accuracy: 0.6716 - val_loss: 0.7407
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.6135 - val_accuracy: 0.6940 - val_loss: 0.6835
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.5837 - val_accuracy: 0.7239 - val_loss: 0.6396
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.5539 - val_accuracy: 0.7090 - val_loss: 0.6444
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7047 - loss: 0.5688 - val_accuracy: 0.7201 - val_loss: 0.6287
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.5544 - val_accuracy: 0.7425 - val_loss: 0.6336
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7400 - loss: 0.5452 - val_accuracy: 0.7127 - val_loss: 0.6347
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5399 - val_accuracy: 0.7276 - val_loss: 0.6308
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5490 - val_accuracy: 0.7127 - val_loss: 0.6325
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5401 - val_accuracy: 0.7351 - val_loss: 0.6257
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5759 - val_accuracy: 0.6903 - val_loss: 0.6892
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.5984 - val_accuracy: 0.7201 - val_loss: 0.6183
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5437 - val_accuracy: 0.6716 - val_loss: 0.6921
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5519 - val_accuracy: 0.7388 - val_loss: 0.6270
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5301 - val_accuracy: 0.7649 - val_loss: 0.6362
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5413 - val_accuracy: 0.7500 - val_loss: 0.6084
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5486 - val_accuracy: 0.7351 - val_loss: 0.6001
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5335 - val_accuracy: 0.6231 - val_loss: 0.7115
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5816 - val_accuracy: 0.7090 - val_loss: 0.6159
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5327 - val_accuracy: 0.7313 - val_loss: 0.6081
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5196 - val_accuracy: 0.7351 - val_loss: 0.6613
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5477 - val_accuracy: 0.7500 - val_loss: 0.6044
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5190 - val_accuracy: 0.7537 - val_loss: 0.6100
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5380 - val_accuracy: 0.6642 - val_loss: 0.7362
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5574 - val_accuracy: 0.7575 - val_loss: 0.6020
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5384 - val_accuracy: 0.6604 - val_loss: 0.7182
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5442 - val_accuracy: 0.7463 - val_loss: 0.6081
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7432 - loss: 0.5276 - val_accuracy: 0.7351 - val_loss: 0.5822
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5166 - val_accuracy: 0.7425 - val_loss: 0.6171
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.5018 - val_accuracy: 0.6978 - val_loss: 0.6279
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5522 - val_accuracy: 0.6754 - val_loss: 0.6772
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5157 - val_accuracy: 0.7463 - val_loss: 0.6016
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5195 - val_accuracy: 0.7463 - val_loss: 0.5879
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.4953 - val_accuracy: 0.7015 - val_loss: 0.6262
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.4917 - val_accuracy: 0.7239 - val_loss: 0.5996
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.4923 - val_accuracy: 0.7425 - val_loss: 0.5972
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5055 - val_accuracy: 0.7836 - val_loss: 0.6351
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5077 - val_accuracy: 0.7127 - val_loss: 0.6154
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5172 - val_accuracy: 0.7201 - val_loss: 0.6098
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5092 - val_accuracy: 0.7575 - val_loss: 0.5834
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5239 - val_accuracy: 0.7873 - val_loss: 0.6269
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5281 - val_accuracy: 0.7090 - val_loss: 0.6110
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5143 - val_accuracy: 0.7388 - val_loss: 0.5941
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5277 - val_accuracy: 0.7761 - val_loss: 0.6279
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4931 - val_accuracy: 0.7500 - val_loss: 0.5851
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4951 - val_accuracy: 0.7313 - val_loss: 0.6003
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5074 - val_accuracy: 0.6791 - val_loss: 0.6822
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5063 - val_accuracy: 0.7388 - val_loss: 0.5886
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5120 - val_accuracy: 0.7500 - val_loss: 0.5780
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5219 - val_accuracy: 0.7836 - val_loss: 0.5949
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5403 - val_accuracy: 0.6604 - val_loss: 0.7942
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.6024 - val_accuracy: 0.7575 - val_loss: 0.5835
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5470 - val_accuracy: 0.6530 - val_loss: 0.7133
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5751 - val_accuracy: 0.7425 - val_loss: 0.5901
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7576 - loss: 0.4993 - val_accuracy: 0.7127 - val_loss: 0.6269
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5143 - val_accuracy: 0.7575 - val_loss: 0.5809
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4854 - val_accuracy: 0.7761 - val_loss: 0.6168
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.5068 - val_accuracy: 0.7761 - val_loss: 0.5844
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4717 - val_accuracy: 0.7799 - val_loss: 0.6255
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5076 - val_accuracy: 0.7724 - val_loss: 0.5810
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5042 - val_accuracy: 0.7425 - val_loss: 0.5948
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5115 - val_accuracy: 0.7463 - val_loss: 0.5895
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5351 - val_accuracy: 0.7537 - val_loss: 0.6472
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5276 - val_accuracy: 0.7761 - val_loss: 0.5883
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5201 - val_accuracy: 0.7239 - val_loss: 0.6224
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5261 - val_accuracy: 0.7164 - val_loss: 0.6443
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5143 - val_accuracy: 0.7724 - val_loss: 0.5847
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4698 - val_accuracy: 0.7910 - val_loss: 0.5721
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4930 - val_accuracy: 0.7724 - val_loss: 0.5697
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4669 - val_accuracy: 0.7761 - val_loss: 0.5805
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4598 - val_accuracy: 0.7649 - val_loss: 0.5752
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4682 - val_accuracy: 0.7724 - val_loss: 0.5792
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4770 - val_accuracy: 0.7463 - val_loss: 0.6456
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5035 - val_accuracy: 0.7612 - val_loss: 0.5807
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4764 - val_accuracy: 0.7388 - val_loss: 0.6051
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4749 - val_accuracy: 0.7463 - val_loss: 0.6030
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4972 - val_accuracy: 0.7425 - val_loss: 0.6517
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5196 - val_accuracy: 0.7612 - val_loss: 0.5826
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4651 - val_accuracy: 0.7687 - val_loss: 0.5641
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4576 - val_accuracy: 0.7761 - val_loss: 0.5864
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5031 - val_accuracy: 0.7500 - val_loss: 0.5727
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4908 - val_accuracy: 0.7500 - val_loss: 0.6027
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.4675 - val_accuracy: 0.7724 - val_loss: 0.5722
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4555 - val_accuracy: 0.7649 - val_loss: 0.5737
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4577 - val_accuracy: 0.7724 - val_loss: 0.5645
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4590 - val_accuracy: 0.7724 - val_loss: 0.5710
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4613 - val_accuracy: 0.7687 - val_loss: 0.5711
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4745 - val_accuracy: 0.7687 - val_loss: 0.5781
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4528 - val_accuracy: 0.7388 - val_loss: 0.5735
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4454 - val_accuracy: 0.7649 - val_loss: 0.5706
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4457 - val_accuracy: 0.7687 - val_loss: 0.5716
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4474 - val_accuracy: 0.7612 - val_loss: 0.5703
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4469 - val_accuracy: 0.7537 - val_loss: 0.6482
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4522 - val_accuracy: 0.7836 - val_loss: 0.5577
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4584 - val_accuracy: 0.7537 - val_loss: 0.5842
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4582 - val_accuracy: 0.7799 - val_loss: 0.5743
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4533 - val_accuracy: 0.7687 - val_loss: 0.5818
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4485 - val_accuracy: 0.7575 - val_loss: 0.5855
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4583 - val_accuracy: 0.7761 - val_loss: 0.5847
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4882 - val_accuracy: 0.7836 - val_loss: 0.5913
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4955 - val_accuracy: 0.7687 - val_loss: 0.5845
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4515 - val_accuracy: 0.7537 - val_loss: 0.5810
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4473 - val_accuracy: 0.7649 - val_loss: 0.5704
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4457 - val_accuracy: 0.7687 - val_loss: 0.5862
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4621 - val_accuracy: 0.7649 - val_loss: 0.5735
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8186 - loss: 0.4432 - val_accuracy: 0.7351 - val_loss: 0.6094
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4618 - val_accuracy: 0.7724 - val_loss: 0.5856
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.4988 - val_accuracy: 0.7836 - val_loss: 0.5805
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4506 - val_accuracy: 0.7724 - val_loss: 0.5686
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4543 - val_accuracy: 0.7575 - val_loss: 0.5985
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4448 - val_accuracy: 0.7612 - val_loss: 0.5689
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4493 - val_accuracy: 0.7724 - val_loss: 0.5699
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4385 - val_accuracy: 0.7649 - val_loss: 0.5692
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4449 - val_accuracy: 0.7612 - val_loss: 0.5936
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4605 - val_accuracy: 0.7537 - val_loss: 0.5849
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8186 - loss: 0.4379 - val_accuracy: 0.7761 - val_loss: 0.5988
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4493 - val_accuracy: 0.7612 - val_loss: 0.5760
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4567 - val_accuracy: 0.7575 - val_loss: 0.5916
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4497 - val_accuracy: 0.7836 - val_loss: 0.5802
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4529 - val_accuracy: 0.7687 - val_loss: 0.5772
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.4932 - val_accuracy: 0.7127 - val_loss: 0.6840
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4557 - val_accuracy: 0.7687 - val_loss: 0.5666
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8234 - loss: 0.4337 - val_accuracy: 0.7687 - val_loss: 0.5818
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4482 - val_accuracy: 0.7799 - val_loss: 0.6051
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4363 - val_accuracy: 0.7463 - val_loss: 0.5973
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8074 - loss: 0.4401 - val_accuracy: 0.7612 - val_loss: 0.5701
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4369 - val_accuracy: 0.7537 - val_loss: 0.5776
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4345 - val_accuracy: 0.7537 - val_loss: 0.5687
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4427 - val_accuracy: 0.7761 - val_loss: 0.5595
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4345 - val_accuracy: 0.7687 - val_loss: 0.5877
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4464 - val_accuracy: 0.7799 - val_loss: 0.5963
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4501 - val_accuracy: 0.7612 - val_loss: 0.5691
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: el2jv1ew with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5875 - loss: 12.5571 - val_accuracy: 0.6119 - val_loss: 0.7683
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.7240 - val_accuracy: 0.6045 - val_loss: 0.7379
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6995 - val_accuracy: 0.6082 - val_loss: 0.7168
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6953 - val_accuracy: 0.6119 - val_loss: 0.7110
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6923 - val_accuracy: 0.6119 - val_loss: 0.7019
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6891 - val_accuracy: 0.6194 - val_loss: 0.6985
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6880 - val_accuracy: 0.6157 - val_loss: 0.6961
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6857 - val_accuracy: 0.6082 - val_loss: 0.6948
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6837 - val_accuracy: 0.6119 - val_loss: 0.6918
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6831 - val_accuracy: 0.6119 - val_loss: 0.6906
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6814 - val_accuracy: 0.6157 - val_loss: 0.6890
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6805 - val_accuracy: 0.6194 - val_loss: 0.6867
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6802 - val_accuracy: 0.6194 - val_loss: 0.6857
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6785 - val_accuracy: 0.6194 - val_loss: 0.6841
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6771 - val_accuracy: 0.6157 - val_loss: 0.6825
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6751 - val_accuracy: 0.6157 - val_loss: 0.6816
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6752 - val_accuracy: 0.6157 - val_loss: 0.6799
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6750 - val_accuracy: 0.6194 - val_loss: 0.6793
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6730 - val_accuracy: 0.6157 - val_loss: 0.6778
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6718 - val_accuracy: 0.6157 - val_loss: 0.6770
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6718 - val_accuracy: 0.6119 - val_loss: 0.6799
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6714 - val_accuracy: 0.6157 - val_loss: 0.6753
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6708 - val_accuracy: 0.6157 - val_loss: 0.6744
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6698 - val_accuracy: 0.6157 - val_loss: 0.6739
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6691 - val_accuracy: 0.6082 - val_loss: 0.6762
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6689 - val_accuracy: 0.6082 - val_loss: 0.6756
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6681 - val_accuracy: 0.6119 - val_loss: 0.6737
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6665 - val_accuracy: 0.6119 - val_loss: 0.6727
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6539 - val_accuracy: 0.6231 - val_loss: 0.6689
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6500 - val_accuracy: 0.6231 - val_loss: 0.6419
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6525 - val_accuracy: 0.6231 - val_loss: 0.6711
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6659 - val_accuracy: 0.6231 - val_loss: 0.6706
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6637 - val_accuracy: 0.6194 - val_loss: 0.6772
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6531 - val_accuracy: 0.6231 - val_loss: 0.6705
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6649 - val_accuracy: 0.6157 - val_loss: 0.6642
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6653 - val_accuracy: 0.6231 - val_loss: 0.6719
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6673 - val_accuracy: 0.6231 - val_loss: 0.6710
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6666 - val_accuracy: 0.6231 - val_loss: 0.6709
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6656 - val_accuracy: 0.6231 - val_loss: 0.6706
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6657 - val_accuracy: 0.6231 - val_loss: 0.6702
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6654 - val_accuracy: 0.6231 - val_loss: 0.6698
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6653 - val_accuracy: 0.6231 - val_loss: 0.6698
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.6693
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6647 - val_accuracy: 0.6194 - val_loss: 0.6699
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.6691
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6640 - val_accuracy: 0.6194 - val_loss: 0.6688
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6634 - val_accuracy: 0.6194 - val_loss: 0.6691
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6636 - val_accuracy: 0.6194 - val_loss: 0.6689
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6636 - val_accuracy: 0.6157 - val_loss: 0.6709
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6635 - val_accuracy: 0.6194 - val_loss: 0.6684
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6633 - val_accuracy: 0.6157 - val_loss: 0.6697
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6231 - val_loss: 0.6690
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6629 - val_accuracy: 0.6194 - val_loss: 0.6704
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6631 - val_accuracy: 0.6231 - val_loss: 0.6682
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6194 - val_loss: 0.6683
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.6688
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6628 - val_accuracy: 0.6194 - val_loss: 0.6689
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.6688
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.6690
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6119 - val_loss: 0.6731
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6624 - val_accuracy: 0.6157 - val_loss: 0.6700
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6701
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.6694
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6619 - val_accuracy: 0.6194 - val_loss: 0.6695
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6194 - val_loss: 0.6710
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.6705
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.6714
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6615 - val_accuracy: 0.6194 - val_loss: 0.6709
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6614 - val_accuracy: 0.6119 - val_loss: 0.6704
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6612 - val_accuracy: 0.6157 - val_loss: 0.6708
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6613 - val_accuracy: 0.6194 - val_loss: 0.6715
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6615 - val_accuracy: 0.6157 - val_loss: 0.6717
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6610 - val_accuracy: 0.6157 - val_loss: 0.6721
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.6724
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6194 - val_loss: 0.6729
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6739
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.6738
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6606 - val_accuracy: 0.6194 - val_loss: 0.6739
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.6744
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6606 - val_accuracy: 0.6119 - val_loss: 0.6763
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6157 - val_loss: 0.6757
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.6757
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.6757
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6194 - val_loss: 0.6771
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6606 - val_accuracy: 0.6119 - val_loss: 0.6767
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.6769
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6602 - val_accuracy: 0.6119 - val_loss: 0.6773
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6602 - val_accuracy: 0.6157 - val_loss: 0.6789
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6603 - val_accuracy: 0.6119 - val_loss: 0.6790
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6601 - val_accuracy: 0.6157 - val_loss: 0.6790
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.6785
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6597 - val_accuracy: 0.6119 - val_loss: 0.6798
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6597 - val_accuracy: 0.6119 - val_loss: 0.6820
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6594 - val_accuracy: 0.6119 - val_loss: 0.6817
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6595 - val_accuracy: 0.6119 - val_loss: 0.6823
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6593 - val_accuracy: 0.6119 - val_loss: 0.6871
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6624 - val_accuracy: 0.6119 - val_loss: 0.6846
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6260 - loss: 0.6594 - val_accuracy: 0.6119 - val_loss: 0.6830
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6593 - val_accuracy: 0.6119 - val_loss: 0.6847
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6588 - val_accuracy: 0.6119 - val_loss: 0.6847
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6591 - val_accuracy: 0.6119 - val_loss: 0.6850
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.6857
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6586 - val_accuracy: 0.6157 - val_loss: 0.6847
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6119 - val_loss: 0.6846
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6588 - val_accuracy: 0.6119 - val_loss: 0.6845
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6587 - val_accuracy: 0.6119 - val_loss: 0.6849
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6587 - val_accuracy: 0.6119 - val_loss: 0.6859
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6119 - val_loss: 0.6849
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6588 - val_accuracy: 0.6119 - val_loss: 0.6850
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6587 - val_accuracy: 0.6119 - val_loss: 0.6857
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6585 - val_accuracy: 0.6119 - val_loss: 0.6865
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6862
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6583 - val_accuracy: 0.6119 - val_loss: 0.6851
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6585 - val_accuracy: 0.6119 - val_loss: 0.6868
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6586 - val_accuracy: 0.6119 - val_loss: 0.6862
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6586 - val_accuracy: 0.6119 - val_loss: 0.6871
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6583 - val_accuracy: 0.6119 - val_loss: 0.6876
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6582 - val_accuracy: 0.6119 - val_loss: 0.6875
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6292 - loss: 0.6580 - val_accuracy: 0.6119 - val_loss: 0.6868
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6574 - val_accuracy: 0.6119 - val_loss: 0.6861
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.6553 - val_accuracy: 0.6119 - val_loss: 0.6808
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.8466 - val_accuracy: 0.6119 - val_loss: 0.6924
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6624 - val_accuracy: 0.6119 - val_loss: 0.6905
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6618 - val_accuracy: 0.6119 - val_loss: 0.6900
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6616 - val_accuracy: 0.6119 - val_loss: 0.6909
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6616 - val_accuracy: 0.6119 - val_loss: 0.6902
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.6896
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.6888
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.6892
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6892
Epoch 130: early stopping

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: mrlg7iuh with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5698 - loss: 1.9409 - val_accuracy: 0.6194 - val_loss: 0.9253
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5955 - loss: 0.9310 - val_accuracy: 0.4590 - val_loss: 0.9845
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.8347 - val_accuracy: 0.6530 - val_loss: 0.8531
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5939 - loss: 0.8466 - val_accuracy: 0.6530 - val_loss: 1.0366
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.7301 - val_accuracy: 0.4590 - val_loss: 1.0606
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.8295 - val_accuracy: 0.5597 - val_loss: 0.9171
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.7231 - val_accuracy: 0.6828 - val_loss: 0.8029
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.7192 - val_accuracy: 0.6940 - val_loss: 0.7616
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6565 - loss: 0.7471 - val_accuracy: 0.6567 - val_loss: 0.8875
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.7499 - val_accuracy: 0.6828 - val_loss: 0.7753
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.7166 - val_accuracy: 0.6455 - val_loss: 0.9167
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.7271 - val_accuracy: 0.6978 - val_loss: 0.7711
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7047 - loss: 0.6538 - val_accuracy: 0.6082 - val_loss: 0.8340
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.7081 - val_accuracy: 0.6455 - val_loss: 1.1069
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.7573 - val_accuracy: 0.6455 - val_loss: 1.1088
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.6686 - val_accuracy: 0.6754 - val_loss: 0.7752
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.6796 - val_accuracy: 0.6791 - val_loss: 0.7608
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6613 - loss: 0.7277 - val_accuracy: 0.6679 - val_loss: 0.8000
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.7427 - val_accuracy: 0.6455 - val_loss: 1.0938
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6806 - loss: 0.6683 - val_accuracy: 0.6493 - val_loss: 0.9263
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.6434 - val_accuracy: 0.6940 - val_loss: 0.7615
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.6431 - val_accuracy: 0.6567 - val_loss: 0.8268
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.6320 - val_accuracy: 0.6530 - val_loss: 0.8540
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.7421 - val_accuracy: 0.5821 - val_loss: 0.8439
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6336 - val_accuracy: 0.7090 - val_loss: 0.7067
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.6923 - val_accuracy: 0.6493 - val_loss: 0.8596
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.6765 - val_accuracy: 0.7127 - val_loss: 0.7004
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6998 - loss: 0.6334 - val_accuracy: 0.6866 - val_loss: 0.7150
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7432 - loss: 0.5818 - val_accuracy: 0.6679 - val_loss: 0.7862
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6998 - val_accuracy: 0.6791 - val_loss: 0.7534
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6540 - val_accuracy: 0.7201 - val_loss: 0.7224
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.6742 - val_accuracy: 0.7127 - val_loss: 0.6926
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7047 - loss: 0.6940 - val_accuracy: 0.6791 - val_loss: 0.7641
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.6083 - val_accuracy: 0.6642 - val_loss: 0.7982
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6115 - val_accuracy: 0.6418 - val_loss: 0.9960
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6320 - val_accuracy: 0.7201 - val_loss: 0.6829
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7134 - val_accuracy: 0.7164 - val_loss: 0.7324
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.6068 - val_accuracy: 0.5970 - val_loss: 0.8512
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.6554 - val_accuracy: 0.4851 - val_loss: 1.0443
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6366 - val_accuracy: 0.6754 - val_loss: 0.7434
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6360 - val_accuracy: 0.6679 - val_loss: 0.7747
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6555 - val_accuracy: 0.7201 - val_loss: 0.7100
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5886 - val_accuracy: 0.5522 - val_loss: 0.8764
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6376 - val_accuracy: 0.7313 - val_loss: 0.6677
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6037 - val_accuracy: 0.7201 - val_loss: 0.7211
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6986 - val_accuracy: 0.6231 - val_loss: 1.0147
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5527 - val_accuracy: 0.7313 - val_loss: 0.6710
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6304 - val_accuracy: 0.7201 - val_loss: 0.6669
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.6307 - val_accuracy: 0.7239 - val_loss: 0.6745
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6258 - val_accuracy: 0.7090 - val_loss: 0.6638
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5879 - val_accuracy: 0.6791 - val_loss: 0.7502
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6213 - val_accuracy: 0.7239 - val_loss: 0.6731
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6242 - val_accuracy: 0.6381 - val_loss: 0.9016
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5676 - val_accuracy: 0.7351 - val_loss: 0.6652
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5581 - val_accuracy: 0.6642 - val_loss: 0.7711
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5849 - val_accuracy: 0.6940 - val_loss: 0.7328
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.6483 - val_accuracy: 0.7537 - val_loss: 0.6708
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5639 - val_accuracy: 0.7313 - val_loss: 0.6616
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5926 - val_accuracy: 0.6828 - val_loss: 0.7957
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5987 - val_accuracy: 0.7313 - val_loss: 0.6763
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5478 - val_accuracy: 0.7127 - val_loss: 0.7491
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5896 - val_accuracy: 0.7537 - val_loss: 0.6984
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5645 - val_accuracy: 0.5746 - val_loss: 0.8822
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7175 - loss: 0.6426 - val_accuracy: 0.7500 - val_loss: 0.6709
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7271 - loss: 0.6039 - val_accuracy: 0.7351 - val_loss: 0.6654
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7560 - loss: 0.5454 - val_accuracy: 0.6157 - val_loss: 1.1106
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5602 - val_accuracy: 0.4888 - val_loss: 1.1437
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5365 - val_accuracy: 0.7164 - val_loss: 0.6991
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5925 - val_accuracy: 0.6716 - val_loss: 0.8233
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6035 - val_accuracy: 0.6940 - val_loss: 0.7492
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5622 - val_accuracy: 0.7201 - val_loss: 0.7377
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5855 - val_accuracy: 0.7276 - val_loss: 0.6569
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6011 - val_accuracy: 0.6082 - val_loss: 0.8610
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5776 - val_accuracy: 0.7463 - val_loss: 0.6718
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5407 - val_accuracy: 0.7612 - val_loss: 0.6601
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5767 - val_accuracy: 0.7164 - val_loss: 0.7069
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6091 - val_accuracy: 0.6493 - val_loss: 0.9042
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5093 - val_accuracy: 0.7425 - val_loss: 0.7069
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.6494 - val_accuracy: 0.7612 - val_loss: 0.6715
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5612 - val_accuracy: 0.6343 - val_loss: 1.0014
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5531 - val_accuracy: 0.7500 - val_loss: 0.7160
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5955 - val_accuracy: 0.7239 - val_loss: 0.6541
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4982 - val_accuracy: 0.6604 - val_loss: 0.8548
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5900 - val_accuracy: 0.7612 - val_loss: 0.6799
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5569 - val_accuracy: 0.6418 - val_loss: 1.0049
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5307 - val_accuracy: 0.6903 - val_loss: 0.7842
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5594 - val_accuracy: 0.7351 - val_loss: 0.6459
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7576 - loss: 0.5383 - val_accuracy: 0.7649 - val_loss: 0.6586
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6341 - val_accuracy: 0.7537 - val_loss: 0.6507
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4752 - val_accuracy: 0.6940 - val_loss: 0.7648
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4921 - val_accuracy: 0.6642 - val_loss: 0.8119
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.6370 - val_accuracy: 0.7500 - val_loss: 0.6466
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4729 - val_accuracy: 0.5821 - val_loss: 0.9126
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7239 - loss: 0.6240 - val_accuracy: 0.6679 - val_loss: 0.8084
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5829 - val_accuracy: 0.7313 - val_loss: 0.6550
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5327 - val_accuracy: 0.7276 - val_loss: 0.7331
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4701 - val_accuracy: 0.7425 - val_loss: 0.6934
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.6404 - val_accuracy: 0.7612 - val_loss: 0.6950
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5118 - val_accuracy: 0.6716 - val_loss: 0.8378
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4791 - val_accuracy: 0.6343 - val_loss: 0.8465
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5895 - val_accuracy: 0.6082 - val_loss: 0.9156
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5476 - val_accuracy: 0.7687 - val_loss: 0.6899
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5485 - val_accuracy: 0.7687 - val_loss: 0.6800
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5220 - val_accuracy: 0.7015 - val_loss: 0.8184
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5054 - val_accuracy: 0.7575 - val_loss: 0.7573
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5534 - val_accuracy: 0.7612 - val_loss: 0.6738
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5123 - val_accuracy: 0.7612 - val_loss: 0.7582
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5962 - val_accuracy: 0.7575 - val_loss: 0.6642
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4662 - val_accuracy: 0.7463 - val_loss: 0.6952
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7448 - loss: 0.5616 - val_accuracy: 0.6493 - val_loss: 0.9855
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.5404 - val_accuracy: 0.6828 - val_loss: 0.8278
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7223 - loss: 0.5952 - val_accuracy: 0.7313 - val_loss: 0.6713
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4579 - val_accuracy: 0.7313 - val_loss: 0.7178
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5871 - val_accuracy: 0.7537 - val_loss: 0.7248
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5159 - val_accuracy: 0.7500 - val_loss: 0.6753
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5697 - val_accuracy: 0.7649 - val_loss: 0.6932
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5643 - val_accuracy: 0.6679 - val_loss: 0.9266
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5326 - val_accuracy: 0.7239 - val_loss: 0.7520
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5089 - val_accuracy: 0.6343 - val_loss: 1.1499
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5801 - val_accuracy: 0.6866 - val_loss: 0.8988
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5246 - val_accuracy: 0.7425 - val_loss: 0.7759
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.5102 - val_accuracy: 0.7612 - val_loss: 0.7295
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5544 - val_accuracy: 0.7724 - val_loss: 0.6827
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5387 - val_accuracy: 0.7463 - val_loss: 0.6730
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.5089 - val_accuracy: 0.6455 - val_loss: 0.8617
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5034 - val_accuracy: 0.6381 - val_loss: 1.1231
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5505 - val_accuracy: 0.7612 - val_loss: 0.6707
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5993 - val_accuracy: 0.7425 - val_loss: 0.6966
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4924 - val_accuracy: 0.6306 - val_loss: 1.2887
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5421 - val_accuracy: 0.7724 - val_loss: 0.7104
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5896 - val_accuracy: 0.7687 - val_loss: 0.7289
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5431 - val_accuracy: 0.7612 - val_loss: 0.6788
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4602 - val_accuracy: 0.7575 - val_loss: 0.6833
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5753 - val_accuracy: 0.7425 - val_loss: 0.6642
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5297 - val_accuracy: 0.7276 - val_loss: 0.7682
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4980 - val_accuracy: 0.7388 - val_loss: 0.7256
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5159 - val_accuracy: 0.7351 - val_loss: 0.7758
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5326 - val_accuracy: 0.6381 - val_loss: 0.8847
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5090 - val_accuracy: 0.7351 - val_loss: 0.7322
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4966 - val_accuracy: 0.7388 - val_loss: 0.7334
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5769 - val_accuracy: 0.6716 - val_loss: 0.8515
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4917 - val_accuracy: 0.7612 - val_loss: 0.6993
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5234 - val_accuracy: 0.5784 - val_loss: 0.9999
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5267 - val_accuracy: 0.7649 - val_loss: 0.6989
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4694 - val_accuracy: 0.7239 - val_loss: 0.8225
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5523 - val_accuracy: 0.7425 - val_loss: 0.7156
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4613 - val_accuracy: 0.7276 - val_loss: 0.7659
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5230 - val_accuracy: 0.7537 - val_loss: 0.6872
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5244 - val_accuracy: 0.7575 - val_loss: 0.6962
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4973 - val_accuracy: 0.7052 - val_loss: 0.8761
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5248 - val_accuracy: 0.7463 - val_loss: 0.7246
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4620 - val_accuracy: 0.6866 - val_loss: 0.8686
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7689 - loss: 0.5476 - val_accuracy: 0.7649 - val_loss: 0.6982
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5462 - val_accuracy: 0.7313 - val_loss: 0.7747
Epoch 155/5000

wandb: Agent Starting Run: aj0kxjec with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 16
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 43ms/step - accuracy: 0.6148 - loss: 15.7693 - val_accuracy: 0.6194 - val_loss: 9.4746
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 4.7164 - val_accuracy: 0.3731 - val_loss: 2.0622
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4061 - loss: 2.5476 - val_accuracy: 0.6306 - val_loss: 1.1766
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5987 - loss: 1.5087 - val_accuracy: 0.6194 - val_loss: 0.9517
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4944 - loss: 0.9087 - val_accuracy: 0.6269 - val_loss: 0.8392
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.8037 - val_accuracy: 0.5112 - val_loss: 0.7968
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5666 - loss: 0.7284 - val_accuracy: 0.6381 - val_loss: 0.6861
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.6782 - val_accuracy: 0.6642 - val_loss: 0.6504
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.6545 - val_accuracy: 0.6791 - val_loss: 0.6642
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6802 - val_accuracy: 0.6978 - val_loss: 0.6196
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.6488 - val_accuracy: 0.7127 - val_loss: 0.6246
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.6272 - val_accuracy: 0.6978 - val_loss: 0.6094
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.6256 - val_accuracy: 0.6940 - val_loss: 0.6020
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.6285 - val_accuracy: 0.6903 - val_loss: 0.5988
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6806 - loss: 0.6146 - val_accuracy: 0.7127 - val_loss: 0.6008
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6822 - loss: 0.6104 - val_accuracy: 0.7090 - val_loss: 0.5937
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.6076 - val_accuracy: 0.6978 - val_loss: 0.6113
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.5988 - val_accuracy: 0.7127 - val_loss: 0.5862
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6822 - loss: 0.5971 - val_accuracy: 0.7164 - val_loss: 0.5872
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.5919 - val_accuracy: 0.7127 - val_loss: 0.5841
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.5852 - val_accuracy: 0.6940 - val_loss: 0.6237
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.5897 - val_accuracy: 0.6903 - val_loss: 0.5865
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.5822 - val_accuracy: 0.7127 - val_loss: 0.5806
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5740 - val_accuracy: 0.7090 - val_loss: 0.5827
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5731 - val_accuracy: 0.7351 - val_loss: 0.5881
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 0.6089 - val_accuracy: 0.6530 - val_loss: 0.6507
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.6108 - val_accuracy: 0.7388 - val_loss: 0.5804
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 0.5774 - val_accuracy: 0.7164 - val_loss: 0.5934
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5849 - val_accuracy: 0.7388 - val_loss: 0.5829
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.5905 - val_accuracy: 0.7015 - val_loss: 0.5796
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6918 - loss: 0.5855 - val_accuracy: 0.6978 - val_loss: 0.5950
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7047 - loss: 0.6043 - val_accuracy: 0.7090 - val_loss: 0.5752
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.5693 - val_accuracy: 0.7201 - val_loss: 0.5680
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7095 - loss: 0.5556 - val_accuracy: 0.7239 - val_loss: 0.5669
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7223 - loss: 0.5530 - val_accuracy: 0.7313 - val_loss: 0.5624
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7223 - loss: 0.5506 - val_accuracy: 0.7164 - val_loss: 0.5558
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5427 - val_accuracy: 0.7201 - val_loss: 0.5583
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.5501 - val_accuracy: 0.7276 - val_loss: 0.5585
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7255 - loss: 0.5516 - val_accuracy: 0.7127 - val_loss: 0.5538
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5393 - val_accuracy: 0.7164 - val_loss: 0.5541
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7271 - loss: 0.5365 - val_accuracy: 0.7201 - val_loss: 0.5610
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.5632 - val_accuracy: 0.7201 - val_loss: 0.5717
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.5543 - val_accuracy: 0.7239 - val_loss: 0.5495
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7319 - loss: 0.5370 - val_accuracy: 0.7127 - val_loss: 0.5597
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7368 - loss: 0.5359 - val_accuracy: 0.6828 - val_loss: 0.6063
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7271 - loss: 0.5542 - val_accuracy: 0.6978 - val_loss: 0.5746
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7368 - loss: 0.5449 - val_accuracy: 0.7351 - val_loss: 0.5497
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7384 - loss: 0.5340 - val_accuracy: 0.7164 - val_loss: 0.5573
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7464 - loss: 0.5240 - val_accuracy: 0.7090 - val_loss: 0.5612
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5496 - val_accuracy: 0.6754 - val_loss: 0.6281
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5511 - val_accuracy: 0.7276 - val_loss: 0.5493
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5824 - val_accuracy: 0.7388 - val_loss: 0.5787
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5360 - val_accuracy: 0.6940 - val_loss: 0.5907
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7255 - loss: 0.5615 - val_accuracy: 0.6978 - val_loss: 0.5768
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5269 - val_accuracy: 0.7463 - val_loss: 0.5410
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7480 - loss: 0.5138 - val_accuracy: 0.7313 - val_loss: 0.5382
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5104 - val_accuracy: 0.7351 - val_loss: 0.5429
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5114 - val_accuracy: 0.7388 - val_loss: 0.5418
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.5090 - val_accuracy: 0.7388 - val_loss: 0.5395
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5082 - val_accuracy: 0.7388 - val_loss: 0.5415
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7480 - loss: 0.5085 - val_accuracy: 0.7351 - val_loss: 0.5322
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7592 - loss: 0.5088 - val_accuracy: 0.7276 - val_loss: 0.5356
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5088 - val_accuracy: 0.7276 - val_loss: 0.5336
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5037 - val_accuracy: 0.7388 - val_loss: 0.5427
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5010 - val_accuracy: 0.7649 - val_loss: 0.5691
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5092 - val_accuracy: 0.7687 - val_loss: 0.5514
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5143 - val_accuracy: 0.7425 - val_loss: 0.5447
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5285 - val_accuracy: 0.7425 - val_loss: 0.5413
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.4931 - val_accuracy: 0.7687 - val_loss: 0.5405
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5048 - val_accuracy: 0.7351 - val_loss: 0.5371
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5091 - val_accuracy: 0.7463 - val_loss: 0.5301
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4961 - val_accuracy: 0.7612 - val_loss: 0.5347
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5037 - val_accuracy: 0.7612 - val_loss: 0.5340
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.4952 - val_accuracy: 0.7612 - val_loss: 0.5645
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7400 - loss: 0.5339 - val_accuracy: 0.7127 - val_loss: 0.5703
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5217 - val_accuracy: 0.7351 - val_loss: 0.5412
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4847 - val_accuracy: 0.7649 - val_loss: 0.5381
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7640 - loss: 0.4912 - val_accuracy: 0.7388 - val_loss: 0.5323
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.4935 - val_accuracy: 0.7351 - val_loss: 0.5249
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7592 - loss: 0.4947 - val_accuracy: 0.7761 - val_loss: 0.5472
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5332 - val_accuracy: 0.6604 - val_loss: 0.6493
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7576 - loss: 0.4964 - val_accuracy: 0.7761 - val_loss: 0.5295
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5108 - val_accuracy: 0.7649 - val_loss: 0.5869
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5131 - val_accuracy: 0.7799 - val_loss: 0.5412
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7657 - loss: 0.5099 - val_accuracy: 0.7351 - val_loss: 0.5284
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7737 - loss: 0.4855 - val_accuracy: 0.7239 - val_loss: 0.5216
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4818 - val_accuracy: 0.7201 - val_loss: 0.5774
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7608 - loss: 0.5055 - val_accuracy: 0.7761 - val_loss: 0.5349
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.4800 - val_accuracy: 0.7724 - val_loss: 0.5612
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5050 - val_accuracy: 0.7351 - val_loss: 0.5405
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7416 - loss: 0.5343 - val_accuracy: 0.7127 - val_loss: 0.5821
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7608 - loss: 0.5037 - val_accuracy: 0.7425 - val_loss: 0.5289
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4784 - val_accuracy: 0.7799 - val_loss: 0.5439
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7753 - loss: 0.4721 - val_accuracy: 0.7425 - val_loss: 0.5201
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7881 - loss: 0.4729 - val_accuracy: 0.7537 - val_loss: 0.5186
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4823 - val_accuracy: 0.7799 - val_loss: 0.5420
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7865 - loss: 0.4712 - val_accuracy: 0.7724 - val_loss: 0.5404
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4728 - val_accuracy: 0.7351 - val_loss: 0.5410
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4707 - val_accuracy: 0.7463 - val_loss: 0.5287
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4787 - val_accuracy: 0.7388 - val_loss: 0.5472
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.4809 - val_accuracy: 0.7649 - val_loss: 0.5280
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4874 - val_accuracy: 0.7724 - val_loss: 0.5364
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7753 - loss: 0.4706 - val_accuracy: 0.7537 - val_loss: 0.5243
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4623 - val_accuracy: 0.7500 - val_loss: 0.5184
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7769 - loss: 0.4716 - val_accuracy: 0.7463 - val_loss: 0.5306
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8186 - loss: 0.4674 - val_accuracy: 0.7761 - val_loss: 0.5701
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8026 - loss: 0.4675 - val_accuracy: 0.7351 - val_loss: 0.6177
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5597 - val_accuracy: 0.7761 - val_loss: 0.5899
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5702 - val_accuracy: 0.7724 - val_loss: 0.5229
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.5376 - val_accuracy: 0.7724 - val_loss: 0.5210
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4857 - val_accuracy: 0.7612 - val_loss: 0.5146
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4611 - val_accuracy: 0.7388 - val_loss: 0.5311
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4585 - val_accuracy: 0.7500 - val_loss: 0.5204
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4739 - val_accuracy: 0.7351 - val_loss: 0.5606
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4802 - val_accuracy: 0.7463 - val_loss: 0.5169
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5034 - val_accuracy: 0.7799 - val_loss: 0.5449
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4923 - val_accuracy: 0.7388 - val_loss: 0.5441
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7865 - loss: 0.4791 - val_accuracy: 0.7463 - val_loss: 0.5419
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7897 - loss: 0.4724 - val_accuracy: 0.7612 - val_loss: 0.5190
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4656 - val_accuracy: 0.7687 - val_loss: 0.5228
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4772 - val_accuracy: 0.7463 - val_loss: 0.6180
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5310 - val_accuracy: 0.7761 - val_loss: 0.5185
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7753 - loss: 0.4736 - val_accuracy: 0.7351 - val_loss: 0.5297
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4627 - val_accuracy: 0.7724 - val_loss: 0.5297
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8058 - loss: 0.4530 - val_accuracy: 0.7761 - val_loss: 0.5183
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4538 - val_accuracy: 0.7351 - val_loss: 0.5282
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4517 - val_accuracy: 0.7724 - val_loss: 0.5159
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8042 - loss: 0.4612 - val_accuracy: 0.7724 - val_loss: 0.5149
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4854 - val_accuracy: 0.7575 - val_loss: 0.6081
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4800 - val_accuracy: 0.7799 - val_loss: 0.5190
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4556 - val_accuracy: 0.7575 - val_loss: 0.5202
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4620 - val_accuracy: 0.7761 - val_loss: 0.5161
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4549 - val_accuracy: 0.7799 - val_loss: 0.5437
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4717 - val_accuracy: 0.7761 - val_loss: 0.5807
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4711 - val_accuracy: 0.7799 - val_loss: 0.5541
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4562 - val_accuracy: 0.7761 - val_loss: 0.5172
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8154 - loss: 0.4519 - val_accuracy: 0.7425 - val_loss: 0.5304
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4599 - val_accuracy: 0.7799 - val_loss: 0.5179
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4433 - val_accuracy: 0.7649 - val_loss: 0.5205
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8090 - loss: 0.4469 - val_accuracy: 0.7463 - val_loss: 0.5302
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4567 - val_accuracy: 0.7649 - val_loss: 0.5211
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8250 - loss: 0.4460 - val_accuracy: 0.7313 - val_loss: 0.6368
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.4840 - val_accuracy: 0.7761 - val_loss: 0.5806
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.4702 - val_accuracy: 0.7724 - val_loss: 0.5187
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4624 - val_accuracy: 0.7575 - val_loss: 0.5248
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4501 - val_accuracy: 0.7724 - val_loss: 0.5203
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4471 - val_accuracy: 0.7761 - val_loss: 0.5227
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4433 - val_accuracy: 0.7724 - val_loss: 0.5244
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8170 - loss: 0.4467 - val_accuracy: 0.7836 - val_loss: 0.5724
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4533 - val_accuracy: 0.7724 - val_loss: 0.5170
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7961 - loss: 0.4502 - val_accuracy: 0.7351 - val_loss: 0.5580
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8106 - loss: 0.4500 - val_accuracy: 0.7761 - val_loss: 0.5218
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4534 - val_accuracy: 0.7761 - val_loss: 0.5232
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4449 - val_accuracy: 0.7425 - val_loss: 0.5381
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: cnq1x23s with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5827 - loss: 2.6225 - val_accuracy: 0.6007 - val_loss: 0.7725
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.7069 - val_accuracy: 0.6045 - val_loss: 0.7210
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6951 - val_accuracy: 0.6119 - val_loss: 0.7047
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6910 - val_accuracy: 0.6157 - val_loss: 0.7003
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6877 - val_accuracy: 0.6119 - val_loss: 0.7010
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6846 - val_accuracy: 0.6119 - val_loss: 0.6954
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6824 - val_accuracy: 0.6119 - val_loss: 0.6928
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6810 - val_accuracy: 0.6119 - val_loss: 0.6926
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6797 - val_accuracy: 0.6119 - val_loss: 0.6936
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6783 - val_accuracy: 0.6157 - val_loss: 0.6949
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6768 - val_accuracy: 0.6119 - val_loss: 0.6922
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6752 - val_accuracy: 0.6119 - val_loss: 0.6887
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6739 - val_accuracy: 0.6119 - val_loss: 0.6903
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6728 - val_accuracy: 0.6157 - val_loss: 0.6915
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6718 - val_accuracy: 0.6157 - val_loss: 0.6917
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6713 - val_accuracy: 0.6157 - val_loss: 0.6891
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6705 - val_accuracy: 0.6157 - val_loss: 0.6858
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6703 - val_accuracy: 0.6157 - val_loss: 0.6898
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6690 - val_accuracy: 0.6157 - val_loss: 0.6847
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6697 - val_accuracy: 0.6157 - val_loss: 0.6854
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6679 - val_accuracy: 0.6157 - val_loss: 0.6897
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6674 - val_accuracy: 0.6157 - val_loss: 0.6914
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6667 - val_accuracy: 0.6157 - val_loss: 0.6917
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6668 - val_accuracy: 0.6157 - val_loss: 0.6902
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6660 - val_accuracy: 0.6157 - val_loss: 0.6902
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6661 - val_accuracy: 0.6157 - val_loss: 0.6868
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6196 - loss: 0.6655 - val_accuracy: 0.6157 - val_loss: 0.6893
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6653 - val_accuracy: 0.6157 - val_loss: 0.6891
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6648 - val_accuracy: 0.6194 - val_loss: 0.6851
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6157 - val_loss: 0.6881
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6639 - val_accuracy: 0.6157 - val_loss: 0.6895
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6639 - val_accuracy: 0.6157 - val_loss: 0.6882
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6640 - val_accuracy: 0.6157 - val_loss: 0.6875
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.6859
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.6858
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.6844
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6632 - val_accuracy: 0.6157 - val_loss: 0.6864
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6623 - val_accuracy: 0.6157 - val_loss: 0.6854
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6627 - val_accuracy: 0.6119 - val_loss: 0.6890
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6157 - val_loss: 0.6856
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6626 - val_accuracy: 0.6157 - val_loss: 0.6834
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.6841
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6851
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6837
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.6872
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6617 - val_accuracy: 0.6119 - val_loss: 0.6883
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.6853
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.6778
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.6795
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6612 - val_accuracy: 0.6157 - val_loss: 0.6845
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6611 - val_accuracy: 0.6119 - val_loss: 0.6872
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6609 - val_accuracy: 0.6119 - val_loss: 0.6867
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6896
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6786
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6860
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.6879
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6612 - val_accuracy: 0.6119 - val_loss: 0.6855
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.6869
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.6865
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6604 - val_accuracy: 0.6119 - val_loss: 0.6853
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6607 - val_accuracy: 0.6119 - val_loss: 0.6915
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.6610 - val_accuracy: 0.6119 - val_loss: 0.6885
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6600 - val_accuracy: 0.6119 - val_loss: 0.6882
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6608 - val_accuracy: 0.6119 - val_loss: 0.6871
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6596 - val_accuracy: 0.6157 - val_loss: 0.6820
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6599 - val_accuracy: 0.6119 - val_loss: 0.6850
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6597 - val_accuracy: 0.6157 - val_loss: 0.6795
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6596 - val_accuracy: 0.6157 - val_loss: 0.6818
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6587 - val_accuracy: 0.6157 - val_loss: 0.6844
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6590 - val_accuracy: 0.6157 - val_loss: 0.6847
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6590 - val_accuracy: 0.6194 - val_loss: 0.6861
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6586 - val_accuracy: 0.6157 - val_loss: 0.6814
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6588 - val_accuracy: 0.6157 - val_loss: 0.6852
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6585 - val_accuracy: 0.6157 - val_loss: 0.6810
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6576 - val_accuracy: 0.6157 - val_loss: 0.6848
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6569 - val_accuracy: 0.6194 - val_loss: 0.6855
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6542 - val_accuracy: 0.6194 - val_loss: 0.6705
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6589 - val_accuracy: 0.6157 - val_loss: 0.6775
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6548 - val_accuracy: 0.6157 - val_loss: 0.6787
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6543 - val_accuracy: 0.6194 - val_loss: 0.6830
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6546 - val_accuracy: 0.6194 - val_loss: 0.6772
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6544 - val_accuracy: 0.6194 - val_loss: 0.6776
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6543 - val_accuracy: 0.6194 - val_loss: 0.6824
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6544 - val_accuracy: 0.6157 - val_loss: 0.6753
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6541 - val_accuracy: 0.6157 - val_loss: 0.6709
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6566 - val_accuracy: 0.6157 - val_loss: 0.6744
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6534 - val_accuracy: 0.6157 - val_loss: 0.6845
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6557 - val_accuracy: 0.6157 - val_loss: 0.6755
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6539 - val_accuracy: 0.6194 - val_loss: 0.6787
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6551 - val_accuracy: 0.6157 - val_loss: 0.6743
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6534 - val_accuracy: 0.6157 - val_loss: 0.6779
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6539 - val_accuracy: 0.6119 - val_loss: 0.6818
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6539 - val_accuracy: 0.6157 - val_loss: 0.6781
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6533 - val_accuracy: 0.6157 - val_loss: 0.6776
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6536 - val_accuracy: 0.6157 - val_loss: 0.6769
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6541 - val_accuracy: 0.6157 - val_loss: 0.6800
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6540 - val_accuracy: 0.6119 - val_loss: 0.6786
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6527 - val_accuracy: 0.6157 - val_loss: 0.6764
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6535 - val_accuracy: 0.6194 - val_loss: 0.6774
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6538 - val_accuracy: 0.6157 - val_loss: 0.6760
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6531 - val_accuracy: 0.6082 - val_loss: 0.6830
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6532 - val_accuracy: 0.6119 - val_loss: 0.6756
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6533 - val_accuracy: 0.6157 - val_loss: 0.6706
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6560 - val_accuracy: 0.6119 - val_loss: 0.6798
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6549 - val_accuracy: 0.6082 - val_loss: 0.6792
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6547 - val_accuracy: 0.6082 - val_loss: 0.6814
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6534 - val_accuracy: 0.6119 - val_loss: 0.6773
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6534 - val_accuracy: 0.6082 - val_loss: 0.6840
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6533 - val_accuracy: 0.6157 - val_loss: 0.6759
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6529 - val_accuracy: 0.6157 - val_loss: 0.6747
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6521 - val_accuracy: 0.6119 - val_loss: 0.6769
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6534 - val_accuracy: 0.6157 - val_loss: 0.6742
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6527 - val_accuracy: 0.6157 - val_loss: 0.6750
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6531 - val_accuracy: 0.6082 - val_loss: 0.6837
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6525 - val_accuracy: 0.6157 - val_loss: 0.6744
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6537 - val_accuracy: 0.6119 - val_loss: 0.6784
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6595 - val_accuracy: 0.6082 - val_loss: 0.6800
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6526 - val_accuracy: 0.6082 - val_loss: 0.6789
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6530 - val_accuracy: 0.6082 - val_loss: 0.6804
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6531 - val_accuracy: 0.6119 - val_loss: 0.6842
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6534 - val_accuracy: 0.6119 - val_loss: 0.6903
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6007 - val_loss: 0.7017
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6630 - val_accuracy: 0.6045 - val_loss: 0.6875
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6599 - val_accuracy: 0.6119 - val_loss: 0.6850
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6594 - val_accuracy: 0.6119 - val_loss: 0.6892
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6584 - val_accuracy: 0.6119 - val_loss: 0.6890
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6584 - val_accuracy: 0.6119 - val_loss: 0.6900
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6578 - val_accuracy: 0.6082 - val_loss: 0.6933
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6579 - val_accuracy: 0.6119 - val_loss: 0.6890
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6565 - val_accuracy: 0.6119 - val_loss: 0.6893
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6563 - val_accuracy: 0.6157 - val_loss: 0.6848
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6543 - val_accuracy: 0.6157 - val_loss: 0.6858
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6244 - loss: 0.6534 - val_accuracy: 0.6157 - val_loss: 0.6843
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6529 - val_accuracy: 0.6157 - val_loss: 0.6834
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6534 - val_accuracy: 0.6157 - val_loss: 0.6784
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6530 - val_accuracy: 0.6157 - val_loss: 0.6753
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6803 - val_accuracy: 0.6045 - val_loss: 0.6977
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6622 - val_accuracy: 0.6045 - val_loss: 0.6914
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6605 - val_accuracy: 0.6119 - val_loss: 0.6916
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6597 - val_accuracy: 0.6119 - val_loss: 0.6892
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6595 - val_accuracy: 0.6119 - val_loss: 0.6895
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6593 - val_accuracy: 0.6119 - val_loss: 0.6885
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6591 - val_accuracy: 0.6119 - val_loss: 0.6931
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6588 - val_accuracy: 0.6119 - val_loss: 0.6939
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6589 - val_accuracy: 0.6082 - val_loss: 0.6965
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6586 - val_accuracy: 0.6119 - val_loss: 0.6934
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6586 - val_accuracy: 0.6119 - val_loss: 0.6921
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6580 - val_accuracy: 0.6119 - val_loss: 0.6927
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.6582 - val_accuracy: 0.6157 - val_loss: 0.6868
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6573 - val_accuracy: 0.6157 - val_loss: 0.6914
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6573 - val_accuracy: 0.6157 - val_loss: 0.6896
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6573 - val_accuracy: 0.6157 - val_loss: 0.6900
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6260 - loss: 0.6576 - val_accuracy: 0.6157 - val_loss: 0.6900
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.6573 - val_accuracy: 0.6119 - val_loss: 0.6915
Epoch 155/5000

wandb: Agent Starting Run: 9qczp7jx with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5008 - loss: 2.1432 - val_accuracy: 0.5373 - val_loss: 1.2280
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5313 - loss: 1.2366 - val_accuracy: 0.5709 - val_loss: 0.9794
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5329 - loss: 1.1279 - val_accuracy: 0.5634 - val_loss: 1.2300
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5217 - loss: 1.0133 - val_accuracy: 0.6007 - val_loss: 1.7106
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5650 - loss: 1.1404 - val_accuracy: 0.5075 - val_loss: 0.8953
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5586 - loss: 1.0412 - val_accuracy: 0.3918 - val_loss: 1.3719
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5891 - loss: 0.8837 - val_accuracy: 0.4366 - val_loss: 1.0544
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5666 - loss: 1.0532 - val_accuracy: 0.6791 - val_loss: 0.7280
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.8649 - val_accuracy: 0.6530 - val_loss: 0.7376
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5650 - loss: 0.9869 - val_accuracy: 0.6157 - val_loss: 1.4443
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.8775 - val_accuracy: 0.4590 - val_loss: 1.0363
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5650 - loss: 0.9716 - val_accuracy: 0.4776 - val_loss: 0.9289
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.8756 - val_accuracy: 0.6007 - val_loss: 0.7887
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.9384 - val_accuracy: 0.6978 - val_loss: 0.6968
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 0.9958 - val_accuracy: 0.6828 - val_loss: 0.7805
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.8279 - val_accuracy: 0.6231 - val_loss: 2.0701
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 0.9786 - val_accuracy: 0.4664 - val_loss: 0.9659
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.7880 - val_accuracy: 0.6903 - val_loss: 0.7280
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6019 - loss: 0.8849 - val_accuracy: 0.5261 - val_loss: 0.8214
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5634 - loss: 0.9896 - val_accuracy: 0.6791 - val_loss: 0.9084
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.8339 - val_accuracy: 0.6940 - val_loss: 0.6773
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.8826 - val_accuracy: 0.6828 - val_loss: 0.6956
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5923 - loss: 0.9657 - val_accuracy: 0.6530 - val_loss: 1.1004
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.8084 - val_accuracy: 0.6306 - val_loss: 1.2229
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5907 - loss: 0.9744 - val_accuracy: 0.6940 - val_loss: 0.7635
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.8815 - val_accuracy: 0.6194 - val_loss: 1.4155
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.8119 - val_accuracy: 0.6642 - val_loss: 0.9632
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.8719 - val_accuracy: 0.5597 - val_loss: 0.8087
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.7169 - val_accuracy: 0.6194 - val_loss: 1.8582
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6035 - loss: 1.0578 - val_accuracy: 0.6642 - val_loss: 0.9659
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5923 - loss: 1.0223 - val_accuracy: 0.6903 - val_loss: 0.8943
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6244 - loss: 0.8160 - val_accuracy: 0.6978 - val_loss: 0.8134
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.8377 - val_accuracy: 0.4925 - val_loss: 0.9369
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.8978 - val_accuracy: 0.6903 - val_loss: 0.7298
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.8230 - val_accuracy: 0.6940 - val_loss: 0.7374
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7300 - val_accuracy: 0.6157 - val_loss: 1.3110
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.9773 - val_accuracy: 0.5858 - val_loss: 0.7788
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.7192 - val_accuracy: 0.5970 - val_loss: 0.7504
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.9022 - val_accuracy: 0.6791 - val_loss: 0.7036
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.8259 - val_accuracy: 0.4254 - val_loss: 1.9604
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.8745 - val_accuracy: 0.7015 - val_loss: 0.6522
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.8853 - val_accuracy: 0.7052 - val_loss: 0.6335
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.9140 - val_accuracy: 0.7015 - val_loss: 0.7489
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.7344 - val_accuracy: 0.6082 - val_loss: 1.6801
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.8178 - val_accuracy: 0.5410 - val_loss: 0.8146
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.8650 - val_accuracy: 0.7015 - val_loss: 0.6482
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.8985 - val_accuracy: 0.6940 - val_loss: 0.7006
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.7357 - val_accuracy: 0.6082 - val_loss: 1.6171
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.8717 - val_accuracy: 0.5410 - val_loss: 0.8141
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5939 - loss: 0.9246 - val_accuracy: 0.7015 - val_loss: 0.6497
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.7932 - val_accuracy: 0.5522 - val_loss: 0.7868
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.7712 - val_accuracy: 0.4739 - val_loss: 0.9880
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.8561 - val_accuracy: 0.7052 - val_loss: 0.7098
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.8395 - val_accuracy: 0.7201 - val_loss: 0.6204
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.7983 - val_accuracy: 0.6940 - val_loss: 0.7212
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.8706 - val_accuracy: 0.7015 - val_loss: 0.6781
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.8157 - val_accuracy: 0.6679 - val_loss: 0.8741
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.7168 - val_accuracy: 0.7239 - val_loss: 0.6175
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.8070 - val_accuracy: 0.4813 - val_loss: 1.0120
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.8476 - val_accuracy: 0.7351 - val_loss: 0.6032
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.8144 - val_accuracy: 0.6082 - val_loss: 1.3275
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6372 - loss: 0.9103 - val_accuracy: 0.7276 - val_loss: 0.6098
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 0.8353 - val_accuracy: 0.5410 - val_loss: 0.8115
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.8484 - val_accuracy: 0.7052 - val_loss: 0.7476
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.7644 - val_accuracy: 0.7127 - val_loss: 0.6456
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.7689 - val_accuracy: 0.6679 - val_loss: 0.9358
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.8961 - val_accuracy: 0.6866 - val_loss: 0.8152
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6774 - loss: 0.7687 - val_accuracy: 0.5634 - val_loss: 0.7712
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.9434 - val_accuracy: 0.6679 - val_loss: 0.9458
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6392 - val_accuracy: 0.5187 - val_loss: 0.8726
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.8759 - val_accuracy: 0.7127 - val_loss: 0.6108
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.8244 - val_accuracy: 0.7425 - val_loss: 0.5852
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.7131 - val_accuracy: 0.7425 - val_loss: 0.5816
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6372 - loss: 0.8689 - val_accuracy: 0.6418 - val_loss: 1.1258
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.7383 - val_accuracy: 0.4813 - val_loss: 1.1172
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.7515 - val_accuracy: 0.7388 - val_loss: 0.6016
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.6585 - val_accuracy: 0.4739 - val_loss: 1.1367
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.8652 - val_accuracy: 0.6231 - val_loss: 1.0778
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.8319 - val_accuracy: 0.6343 - val_loss: 1.1128
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7533 - val_accuracy: 0.7500 - val_loss: 0.5736
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.6790 - val_accuracy: 0.7239 - val_loss: 0.5877
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.7239 - val_accuracy: 0.7388 - val_loss: 0.6138
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.7570 - val_accuracy: 0.6493 - val_loss: 0.9423
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6581 - loss: 0.7583 - val_accuracy: 0.7425 - val_loss: 0.5743
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6469 - loss: 0.8053 - val_accuracy: 0.6679 - val_loss: 0.8664
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.6493 - val_accuracy: 0.6269 - val_loss: 1.0646
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.7819 - val_accuracy: 0.7239 - val_loss: 0.6215
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.8058 - val_accuracy: 0.7500 - val_loss: 0.5583
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.6824 - val_accuracy: 0.7276 - val_loss: 0.6155
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7548 - val_accuracy: 0.7500 - val_loss: 0.5536
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.7177 - val_accuracy: 0.6530 - val_loss: 1.0338
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.7893 - val_accuracy: 0.6978 - val_loss: 0.6675
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.7137 - val_accuracy: 0.6791 - val_loss: 0.8841
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.6951 - val_accuracy: 0.7127 - val_loss: 0.6512
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7416 - val_accuracy: 0.6455 - val_loss: 0.9982
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.7858 - val_accuracy: 0.4963 - val_loss: 0.9355
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6987 - val_accuracy: 0.4627 - val_loss: 1.5097
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6437 - loss: 0.8738 - val_accuracy: 0.7761 - val_loss: 0.5532
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6958 - val_accuracy: 0.7239 - val_loss: 0.5691
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7087 - val_accuracy: 0.5187 - val_loss: 0.8767
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7189 - val_accuracy: 0.7351 - val_loss: 0.6262
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.8065 - val_accuracy: 0.6642 - val_loss: 0.8267
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5673 - val_accuracy: 0.4627 - val_loss: 1.4794
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.8678 - val_accuracy: 0.7575 - val_loss: 0.5417
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6998 - val_accuracy: 0.7201 - val_loss: 0.5880
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6384 - val_accuracy: 0.7687 - val_loss: 0.5704
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7299 - val_accuracy: 0.6306 - val_loss: 1.0365
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.7708 - val_accuracy: 0.6493 - val_loss: 0.9475
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6485 - loss: 0.8575 - val_accuracy: 0.7313 - val_loss: 0.5460
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6822 - loss: 0.7366 - val_accuracy: 0.6978 - val_loss: 0.7225
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6344 - val_accuracy: 0.6679 - val_loss: 0.8921
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.6258 - val_accuracy: 0.4701 - val_loss: 1.1050
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6941 - val_accuracy: 0.7090 - val_loss: 0.6067
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.7979 - val_accuracy: 0.6343 - val_loss: 1.0411
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.6308 - val_accuracy: 0.6306 - val_loss: 1.0695
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.7872 - val_accuracy: 0.7463 - val_loss: 0.5307
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.7222 - val_accuracy: 0.6157 - val_loss: 1.2149
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.6944 - val_accuracy: 0.5410 - val_loss: 0.8082
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.6878 - val_accuracy: 0.6194 - val_loss: 1.1841
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.7018 - val_accuracy: 0.6455 - val_loss: 0.6934
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.7160 - val_accuracy: 0.7724 - val_loss: 0.5293
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7715 - val_accuracy: 0.7649 - val_loss: 0.5240
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6784 - val_accuracy: 0.6903 - val_loss: 0.6572
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6864 - val_accuracy: 0.7201 - val_loss: 0.5664
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.7133 - val_accuracy: 0.7724 - val_loss: 0.5200
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.7868 - val_accuracy: 0.6642 - val_loss: 0.9385
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5597 - val_accuracy: 0.7351 - val_loss: 0.5535
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.7768 - val_accuracy: 0.6828 - val_loss: 0.6487
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.7478 - val_accuracy: 0.6119 - val_loss: 1.3733
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.7487 - val_accuracy: 0.6642 - val_loss: 0.9529
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6535 - val_accuracy: 0.6642 - val_loss: 0.9215
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.7921 - val_accuracy: 0.7388 - val_loss: 0.5364
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.6437 - val_accuracy: 0.6119 - val_loss: 1.4742
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.7346 - val_accuracy: 0.6381 - val_loss: 0.7023
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.6638 - val_accuracy: 0.6119 - val_loss: 0.7108
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7368 - loss: 0.5983 - val_accuracy: 0.7836 - val_loss: 0.5474
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.7420 - val_accuracy: 0.6903 - val_loss: 0.7977
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6622 - val_accuracy: 0.7873 - val_loss: 0.5487
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5887 - val_accuracy: 0.7500 - val_loss: 0.5236
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7652 - val_accuracy: 0.7612 - val_loss: 0.5114
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.7542 - val_accuracy: 0.7090 - val_loss: 0.6328
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.6561 - val_accuracy: 0.6940 - val_loss: 0.6447
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7319 - loss: 0.6053 - val_accuracy: 0.7313 - val_loss: 0.5412
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.6656 - val_accuracy: 0.5187 - val_loss: 0.8661
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.8005 - val_accuracy: 0.5858 - val_loss: 0.7442
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5899 - val_accuracy: 0.6418 - val_loss: 0.6906
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6742 - loss: 0.8306 - val_accuracy: 0.7276 - val_loss: 0.5362
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.5304 - val_accuracy: 0.7799 - val_loss: 0.5319
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6355 - val_accuracy: 0.5410 - val_loss: 0.8401
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.7573 - val_accuracy: 0.7425 - val_loss: 0.6073
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6629 - loss: 0.7645 - val_accuracy: 0.6381 - val_loss: 1.1726
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6952 - val_accuracy: 0.7127 - val_loss: 0.6091
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6951 - val_accuracy: 0.7276 - val_loss: 0.5354
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6675 - val_accuracy: 0.7799 - val_loss: 0.5043
Epoch 155/5000

wandb: Agent Starting Run: 8syv90n6 with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 8
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5474 - loss: 3.2967 - val_accuracy: 0.3955 - val_loss: 2.0908
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5891 - loss: 1.4526 - val_accuracy: 0.6493 - val_loss: 1.0909
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 1.0635 - val_accuracy: 0.6754 - val_loss: 0.7199
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6388 - loss: 0.8777 - val_accuracy: 0.6642 - val_loss: 0.6933
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.7688 - val_accuracy: 0.5858 - val_loss: 0.7460
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.7637 - val_accuracy: 0.6866 - val_loss: 0.6853
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.7134 - val_accuracy: 0.6940 - val_loss: 0.6568
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6890 - val_accuracy: 0.7015 - val_loss: 0.6775
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.6639 - val_accuracy: 0.6716 - val_loss: 0.6611
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6593 - val_accuracy: 0.6978 - val_loss: 0.6312
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6292 - loss: 0.6896 - val_accuracy: 0.6791 - val_loss: 0.6458
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.6885 - val_accuracy: 0.6791 - val_loss: 0.6328
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6308 - loss: 0.6588 - val_accuracy: 0.6791 - val_loss: 0.6346
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6680 - val_accuracy: 0.6754 - val_loss: 0.6278
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6207 - val_accuracy: 0.7090 - val_loss: 0.6026
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.6134 - val_accuracy: 0.7127 - val_loss: 0.5980
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6099 - val_accuracy: 0.7090 - val_loss: 0.5914
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.6146 - val_accuracy: 0.6903 - val_loss: 0.5889
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6693 - loss: 0.6015 - val_accuracy: 0.6903 - val_loss: 0.5903
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6854 - loss: 0.6176 - val_accuracy: 0.7015 - val_loss: 0.5954
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6354 - val_accuracy: 0.7015 - val_loss: 0.5852
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6412 - val_accuracy: 0.7015 - val_loss: 0.6117
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.5836 - val_accuracy: 0.6978 - val_loss: 0.5559
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6870 - loss: 0.5733 - val_accuracy: 0.6940 - val_loss: 0.5755
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.5787 - val_accuracy: 0.7090 - val_loss: 0.5764
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.5883 - val_accuracy: 0.7015 - val_loss: 0.5502
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.5656 - val_accuracy: 0.7052 - val_loss: 0.5574
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.5735 - val_accuracy: 0.7052 - val_loss: 0.5687
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.5920 - val_accuracy: 0.6530 - val_loss: 0.6419
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.6165 - val_accuracy: 0.7015 - val_loss: 0.5507
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.5501 - val_accuracy: 0.7015 - val_loss: 0.6122
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.5739 - val_accuracy: 0.7164 - val_loss: 0.5469
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.5495 - val_accuracy: 0.7090 - val_loss: 0.5565
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.5466 - val_accuracy: 0.7239 - val_loss: 0.5445
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7335 - loss: 0.5407 - val_accuracy: 0.7201 - val_loss: 0.5603
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.5443 - val_accuracy: 0.7201 - val_loss: 0.5436
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.5656 - val_accuracy: 0.5896 - val_loss: 0.6752
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.5777 - val_accuracy: 0.7276 - val_loss: 0.5596
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5475 - val_accuracy: 0.7164 - val_loss: 0.5367
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.5470 - val_accuracy: 0.7239 - val_loss: 0.5371
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7207 - loss: 0.5356 - val_accuracy: 0.7313 - val_loss: 0.5544
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5500 - val_accuracy: 0.7388 - val_loss: 0.5833
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5312 - val_accuracy: 0.7425 - val_loss: 0.5716
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6998 - loss: 0.5652 - val_accuracy: 0.7276 - val_loss: 0.5342
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.5529 - val_accuracy: 0.7276 - val_loss: 0.5425
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5283 - val_accuracy: 0.7239 - val_loss: 0.5308
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.5507 - val_accuracy: 0.7537 - val_loss: 0.5738
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5579 - val_accuracy: 0.7164 - val_loss: 0.5603
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5327 - val_accuracy: 0.6903 - val_loss: 0.6476
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7352 - loss: 0.5393 - val_accuracy: 0.7463 - val_loss: 0.5373
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5317 - val_accuracy: 0.7127 - val_loss: 0.5672
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5246 - val_accuracy: 0.7127 - val_loss: 0.5658
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5250 - val_accuracy: 0.7276 - val_loss: 0.5234
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5258 - val_accuracy: 0.7761 - val_loss: 0.5670
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5427 - val_accuracy: 0.7276 - val_loss: 0.5346
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7352 - loss: 0.5204 - val_accuracy: 0.7127 - val_loss: 0.5689
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5239 - val_accuracy: 0.7276 - val_loss: 0.5240
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5029 - val_accuracy: 0.7313 - val_loss: 0.5232
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5131 - val_accuracy: 0.7687 - val_loss: 0.5708
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5364 - val_accuracy: 0.7127 - val_loss: 0.5749
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5306 - val_accuracy: 0.7201 - val_loss: 0.5457
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5339 - val_accuracy: 0.7239 - val_loss: 0.5208
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5695 - val_accuracy: 0.6791 - val_loss: 0.6156
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5277 - val_accuracy: 0.7649 - val_loss: 0.5341
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5014 - val_accuracy: 0.7761 - val_loss: 0.5406
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5153 - val_accuracy: 0.7351 - val_loss: 0.5147
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5027 - val_accuracy: 0.7388 - val_loss: 0.5217
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.5047 - val_accuracy: 0.7500 - val_loss: 0.5190
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5109 - val_accuracy: 0.7500 - val_loss: 0.5119
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7608 - loss: 0.4938 - val_accuracy: 0.7500 - val_loss: 0.5156
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.4966 - val_accuracy: 0.7575 - val_loss: 0.5207
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.5117 - val_accuracy: 0.7276 - val_loss: 0.5341
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.4943 - val_accuracy: 0.7388 - val_loss: 0.5140
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.4907 - val_accuracy: 0.7500 - val_loss: 0.5107
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7673 - loss: 0.5024 - val_accuracy: 0.7388 - val_loss: 0.5187
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5118 - val_accuracy: 0.7313 - val_loss: 0.5203
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5088 - val_accuracy: 0.7201 - val_loss: 0.5897
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5084 - val_accuracy: 0.7724 - val_loss: 0.5319
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5343 - val_accuracy: 0.7500 - val_loss: 0.5020
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5017 - val_accuracy: 0.7276 - val_loss: 0.5078
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4930 - val_accuracy: 0.7724 - val_loss: 0.5158
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4851 - val_accuracy: 0.7388 - val_loss: 0.5150
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.4933 - val_accuracy: 0.6940 - val_loss: 0.6378
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5063 - val_accuracy: 0.7276 - val_loss: 0.5347
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7608 - loss: 0.4975 - val_accuracy: 0.7575 - val_loss: 0.5154
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4961 - val_accuracy: 0.7724 - val_loss: 0.5266
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.4893 - val_accuracy: 0.7425 - val_loss: 0.5071
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7817 - loss: 0.4767 - val_accuracy: 0.7351 - val_loss: 0.5009
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7817 - loss: 0.5075 - val_accuracy: 0.7201 - val_loss: 0.5931
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7496 - loss: 0.5415 - val_accuracy: 0.7836 - val_loss: 0.5413
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7849 - loss: 0.4874 - val_accuracy: 0.7388 - val_loss: 0.5044
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7753 - loss: 0.4798 - val_accuracy: 0.7164 - val_loss: 0.5566
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.5373 - val_accuracy: 0.6940 - val_loss: 0.6638
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5372 - val_accuracy: 0.7649 - val_loss: 0.5042
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7673 - loss: 0.5108 - val_accuracy: 0.7612 - val_loss: 0.5170
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.4691 - val_accuracy: 0.7537 - val_loss: 0.5057
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.4736 - val_accuracy: 0.7351 - val_loss: 0.5065
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7849 - loss: 0.4714 - val_accuracy: 0.7425 - val_loss: 0.5089
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4758 - val_accuracy: 0.7873 - val_loss: 0.5300
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.4800 - val_accuracy: 0.7836 - val_loss: 0.5285
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7737 - loss: 0.5030 - val_accuracy: 0.7649 - val_loss: 0.5197
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7592 - loss: 0.4927 - val_accuracy: 0.7649 - val_loss: 0.4938
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4877 - val_accuracy: 0.7388 - val_loss: 0.5099
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4869 - val_accuracy: 0.7127 - val_loss: 0.5710
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5015 - val_accuracy: 0.7351 - val_loss: 0.5158
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5149 - val_accuracy: 0.7612 - val_loss: 0.5751
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5031 - val_accuracy: 0.7500 - val_loss: 0.4925
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4763 - val_accuracy: 0.7500 - val_loss: 0.5032
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5007 - val_accuracy: 0.7239 - val_loss: 0.5381
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4673 - val_accuracy: 0.7575 - val_loss: 0.4940
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4773 - val_accuracy: 0.7313 - val_loss: 0.5442
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4823 - val_accuracy: 0.7575 - val_loss: 0.5065
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4729 - val_accuracy: 0.7500 - val_loss: 0.5046
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4730 - val_accuracy: 0.7575 - val_loss: 0.5077
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4771 - val_accuracy: 0.6940 - val_loss: 0.6158
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4926 - val_accuracy: 0.7687 - val_loss: 0.5057
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4801 - val_accuracy: 0.7388 - val_loss: 0.5222
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4722 - val_accuracy: 0.7724 - val_loss: 0.5214
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8058 - loss: 0.4628 - val_accuracy: 0.7612 - val_loss: 0.5078
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4635 - val_accuracy: 0.7649 - val_loss: 0.4983
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7881 - loss: 0.4710 - val_accuracy: 0.7500 - val_loss: 0.5017
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4619 - val_accuracy: 0.7463 - val_loss: 0.5018
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4627 - val_accuracy: 0.7836 - val_loss: 0.5552
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4628 - val_accuracy: 0.7500 - val_loss: 0.4973
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4667 - val_accuracy: 0.7388 - val_loss: 0.5239
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7801 - loss: 0.4889 - val_accuracy: 0.7276 - val_loss: 0.5701
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4561 - val_accuracy: 0.7463 - val_loss: 0.5049
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4660 - val_accuracy: 0.7500 - val_loss: 0.5080
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4536 - val_accuracy: 0.7500 - val_loss: 0.4962
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4624 - val_accuracy: 0.7575 - val_loss: 0.5206
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4629 - val_accuracy: 0.7388 - val_loss: 0.5446
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.4973 - val_accuracy: 0.6866 - val_loss: 0.7100
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5241 - val_accuracy: 0.7351 - val_loss: 0.5198
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4798 - val_accuracy: 0.7537 - val_loss: 0.4982
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4625 - val_accuracy: 0.7537 - val_loss: 0.5103
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8122 - loss: 0.4532 - val_accuracy: 0.7687 - val_loss: 0.5731
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4978 - val_accuracy: 0.7612 - val_loss: 0.4968
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4764 - val_accuracy: 0.7649 - val_loss: 0.5055
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4688 - val_accuracy: 0.7799 - val_loss: 0.5138
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4757 - val_accuracy: 0.7724 - val_loss: 0.5376
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4612 - val_accuracy: 0.7500 - val_loss: 0.5008
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7833 - loss: 0.4653 - val_accuracy: 0.7425 - val_loss: 0.5034
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4500 - val_accuracy: 0.7575 - val_loss: 0.5021
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4473 - val_accuracy: 0.7761 - val_loss: 0.5487
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4608 - val_accuracy: 0.7612 - val_loss: 0.4954
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4583 - val_accuracy: 0.7687 - val_loss: 0.5019
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7753 - loss: 0.4992 - val_accuracy: 0.7612 - val_loss: 0.5146
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.5426 - val_accuracy: 0.7239 - val_loss: 0.6186
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5357 - val_accuracy: 0.7313 - val_loss: 0.5303
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4630 - val_accuracy: 0.7612 - val_loss: 0.5088
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8170 - loss: 0.4525 - val_accuracy: 0.7687 - val_loss: 0.5034
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4515 - val_accuracy: 0.7500 - val_loss: 0.5074
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4537 - val_accuracy: 0.7425 - val_loss: 0.5207
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4488 - val_accuracy: 0.7612 - val_loss: 0.5079
Epoch 155/5000

wandb: Agent Starting Run: 7106tusf with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5698 - loss: 24.2876 - val_accuracy: 0.6119 - val_loss: 0.8543
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.7546 - val_accuracy: 0.6119 - val_loss: 0.7985
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 0.7304 - val_accuracy: 0.6194 - val_loss: 0.7669
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.7158 - val_accuracy: 0.6119 - val_loss: 0.7543
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.7084 - val_accuracy: 0.6082 - val_loss: 0.7513
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6019 - loss: 0.7035 - val_accuracy: 0.6343 - val_loss: 0.7489
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6019 - loss: 0.7006 - val_accuracy: 0.6306 - val_loss: 0.7491
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6992 - val_accuracy: 0.6381 - val_loss: 0.7395
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.6945 - val_accuracy: 0.6455 - val_loss: 0.7350
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.6914 - val_accuracy: 0.6306 - val_loss: 0.7322
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6035 - loss: 0.6897 - val_accuracy: 0.6455 - val_loss: 0.7303
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6871 - val_accuracy: 0.6493 - val_loss: 0.7276
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.6874 - val_accuracy: 0.6455 - val_loss: 0.7260
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5971 - loss: 0.6849 - val_accuracy: 0.6269 - val_loss: 0.7311
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6838 - val_accuracy: 0.6343 - val_loss: 0.7239
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6826 - val_accuracy: 0.6306 - val_loss: 0.7213
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.6793 - val_accuracy: 0.6306 - val_loss: 0.7227
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6791 - val_accuracy: 0.6306 - val_loss: 0.7203
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6769 - val_accuracy: 0.6343 - val_loss: 0.7171
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6777 - val_accuracy: 0.6381 - val_loss: 0.7154
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.6764 - val_accuracy: 0.6306 - val_loss: 0.7156
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6748 - val_accuracy: 0.6306 - val_loss: 0.7134
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6737 - val_accuracy: 0.6306 - val_loss: 0.7143
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6728 - val_accuracy: 0.6418 - val_loss: 0.7129
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 0.6728 - val_accuracy: 0.6343 - val_loss: 0.7126
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6051 - loss: 0.6725 - val_accuracy: 0.6343 - val_loss: 0.7115
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6712 - val_accuracy: 0.6343 - val_loss: 0.7119
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6719 - val_accuracy: 0.6269 - val_loss: 0.7155
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6710 - val_accuracy: 0.6306 - val_loss: 0.7104
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6691 - val_accuracy: 0.6269 - val_loss: 0.7108
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6132 - loss: 0.6710 - val_accuracy: 0.6306 - val_loss: 0.7128
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6705 - val_accuracy: 0.6343 - val_loss: 0.7089
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 0.6709 - val_accuracy: 0.6231 - val_loss: 0.7095
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6083 - loss: 0.6693 - val_accuracy: 0.6194 - val_loss: 0.7160
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6067 - loss: 0.6701 - val_accuracy: 0.6306 - val_loss: 0.7029
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.7019
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6675 - val_accuracy: 0.6231 - val_loss: 0.7010
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6686 - val_accuracy: 0.6231 - val_loss: 0.7013
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6035 - loss: 0.6676 - val_accuracy: 0.6231 - val_loss: 0.7022
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6667 - val_accuracy: 0.6381 - val_loss: 0.7037
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6666 - val_accuracy: 0.6306 - val_loss: 0.7028
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6659 - val_accuracy: 0.6381 - val_loss: 0.7026
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.7017
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6658 - val_accuracy: 0.6381 - val_loss: 0.7018
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6660 - val_accuracy: 0.6381 - val_loss: 0.7022
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6661 - val_accuracy: 0.6269 - val_loss: 0.7014
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6194 - val_loss: 0.7021
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6657 - val_accuracy: 0.6306 - val_loss: 0.6994
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6663 - val_accuracy: 0.6269 - val_loss: 0.7003
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6666 - val_accuracy: 0.6231 - val_loss: 0.6991
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6651 - val_accuracy: 0.6381 - val_loss: 0.7006
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6653 - val_accuracy: 0.6381 - val_loss: 0.7003
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6231 - val_loss: 0.7000
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6656 - val_accuracy: 0.6231 - val_loss: 0.7003
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6655 - val_accuracy: 0.6231 - val_loss: 0.6999
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6646 - val_accuracy: 0.6231 - val_loss: 0.7002
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6148 - loss: 0.6657 - val_accuracy: 0.6231 - val_loss: 0.7009
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6644 - val_accuracy: 0.6194 - val_loss: 0.7032
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6661 - val_accuracy: 0.6231 - val_loss: 0.7035
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6651 - val_accuracy: 0.6269 - val_loss: 0.7019
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6655 - val_accuracy: 0.6381 - val_loss: 0.7025
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6645 - val_accuracy: 0.6231 - val_loss: 0.7032
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6231 - val_loss: 0.7041
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6649 - val_accuracy: 0.6269 - val_loss: 0.7076
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6643 - val_accuracy: 0.6194 - val_loss: 0.7031
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.7031
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6649 - val_accuracy: 0.6343 - val_loss: 0.7026
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.6641 - val_accuracy: 0.6343 - val_loss: 0.7043
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6157 - val_loss: 0.7052
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6644 - val_accuracy: 0.6231 - val_loss: 0.7047
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6639 - val_accuracy: 0.6231 - val_loss: 0.7055
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.7057
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6639 - val_accuracy: 0.6194 - val_loss: 0.7066
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6632 - val_accuracy: 0.6194 - val_loss: 0.7061
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6630 - val_accuracy: 0.6343 - val_loss: 0.7072
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6650 - val_accuracy: 0.6157 - val_loss: 0.7062
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6630 - val_accuracy: 0.6231 - val_loss: 0.7054
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6633 - val_accuracy: 0.6231 - val_loss: 0.7047
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6639 - val_accuracy: 0.6157 - val_loss: 0.7070
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6231 - val_loss: 0.7065
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6231 - val_loss: 0.7073
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6631 - val_accuracy: 0.6231 - val_loss: 0.7070
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6629 - val_accuracy: 0.6119 - val_loss: 0.7087
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6638 - val_accuracy: 0.6231 - val_loss: 0.7065
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6631 - val_accuracy: 0.6231 - val_loss: 0.7021
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6627 - val_accuracy: 0.6269 - val_loss: 0.7084
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6643 - val_accuracy: 0.6157 - val_loss: 0.7036
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6637 - val_accuracy: 0.6119 - val_loss: 0.7057
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6634 - val_accuracy: 0.6157 - val_loss: 0.7038
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.7034
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6157 - val_loss: 0.7043
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6119 - val_loss: 0.7053
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6633 - val_accuracy: 0.6194 - val_loss: 0.7086
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6635 - val_accuracy: 0.6231 - val_loss: 0.7053
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6157 - val_loss: 0.7057
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6629 - val_accuracy: 0.6157 - val_loss: 0.7059
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6119 - val_loss: 0.7067
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6630 - val_accuracy: 0.6269 - val_loss: 0.7049
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6244 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.7113
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7065
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6641 - val_accuracy: 0.6231 - val_loss: 0.7064
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6631 - val_accuracy: 0.6157 - val_loss: 0.7057
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6157 - val_loss: 0.7062
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6624 - val_accuracy: 0.6157 - val_loss: 0.7051
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6631 - val_accuracy: 0.6157 - val_loss: 0.7051
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6157 - val_loss: 0.7061
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6624 - val_accuracy: 0.6157 - val_loss: 0.7053
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6132 - loss: 0.6627 - val_accuracy: 0.6306 - val_loss: 0.7056
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7055
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.7059
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.7053
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.7040
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.7036
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6116 - loss: 0.6631 - val_accuracy: 0.6381 - val_loss: 0.7047
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6626 - val_accuracy: 0.6381 - val_loss: 0.7055
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6622 - val_accuracy: 0.6306 - val_loss: 0.7039
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7028
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.7042
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.7029
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6621 - val_accuracy: 0.6194 - val_loss: 0.7031
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6629 - val_accuracy: 0.6157 - val_loss: 0.7031
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6623 - val_accuracy: 0.6194 - val_loss: 0.7022
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6627 - val_accuracy: 0.6194 - val_loss: 0.7010
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.7023
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.7030
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.7019
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6625 - val_accuracy: 0.6269 - val_loss: 0.7027
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6260 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.7026
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6625 - val_accuracy: 0.6194 - val_loss: 0.7003
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6616 - val_accuracy: 0.6157 - val_loss: 0.6998
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6611 - val_accuracy: 0.6157 - val_loss: 0.7039
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6194 - val_loss: 0.6999
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.7000
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.7002
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6614 - val_accuracy: 0.6157 - val_loss: 0.7006
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6194 - val_loss: 0.7006
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.7008
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6617 - val_accuracy: 0.6157 - val_loss: 0.7024
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.7006
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6194 - val_loss: 0.7004
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7016
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6618 - val_accuracy: 0.6157 - val_loss: 0.7016
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6621 - val_accuracy: 0.6157 - val_loss: 0.7007
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6148 - loss: 0.6614 - val_accuracy: 0.6194 - val_loss: 0.7005
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6228 - loss: 0.6616 - val_accuracy: 0.6194 - val_loss: 0.7007
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6613 - val_accuracy: 0.6194 - val_loss: 0.7009
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7012
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6164 - loss: 0.6624 - val_accuracy: 0.6381 - val_loss: 0.7011
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6100 - loss: 0.6631 - val_accuracy: 0.6194 - val_loss: 0.6996
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6620 - val_accuracy: 0.6157 - val_loss: 0.7004
Epoch 150: early stopping

wandb: Agent Starting Run: oigvrf5p with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6035 - loss: 2.5035 - val_accuracy: 0.4925 - val_loss: 2.1769
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 2.0776 - val_accuracy: 0.6866 - val_loss: 1.2911
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 1.7803 - val_accuracy: 0.6866 - val_loss: 1.1640
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 1.6102 - val_accuracy: 0.6978 - val_loss: 1.0354
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 1.3710 - val_accuracy: 0.7015 - val_loss: 0.9137
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 1.1093 - val_accuracy: 0.5746 - val_loss: 1.0587
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 1.1299 - val_accuracy: 0.5485 - val_loss: 1.0998
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 1.0083 - val_accuracy: 0.7052 - val_loss: 0.7561
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.8862 - val_accuracy: 0.6903 - val_loss: 0.7063
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.8317 - val_accuracy: 0.6642 - val_loss: 0.8643
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.9653 - val_accuracy: 0.7015 - val_loss: 0.7197
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.7640 - val_accuracy: 0.6828 - val_loss: 0.7438
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.9534 - val_accuracy: 0.6642 - val_loss: 0.7364
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.7519 - val_accuracy: 0.6231 - val_loss: 0.7615
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.8956 - val_accuracy: 0.6642 - val_loss: 0.9362
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.7349 - val_accuracy: 0.4701 - val_loss: 1.1656
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.8984 - val_accuracy: 0.6940 - val_loss: 0.6585
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.7249 - val_accuracy: 0.6381 - val_loss: 1.4639
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.7235 - val_accuracy: 0.6791 - val_loss: 0.7384
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.7544 - val_accuracy: 0.6679 - val_loss: 0.7119
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.8293 - val_accuracy: 0.6343 - val_loss: 1.3591
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6838 - loss: 0.7348 - val_accuracy: 0.6418 - val_loss: 0.7181
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6709 - loss: 0.6827 - val_accuracy: 0.7052 - val_loss: 0.6605
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 0.8523 - val_accuracy: 0.6306 - val_loss: 1.1610
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.6729 - val_accuracy: 0.6903 - val_loss: 0.6990
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6597 - loss: 0.7340 - val_accuracy: 0.6231 - val_loss: 1.3923
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.7757 - val_accuracy: 0.6455 - val_loss: 1.0722
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.7625 - val_accuracy: 0.7239 - val_loss: 0.5998
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6726 - loss: 0.7302 - val_accuracy: 0.6381 - val_loss: 0.7354
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6469 - loss: 0.7986 - val_accuracy: 0.6493 - val_loss: 0.7221
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.7027 - val_accuracy: 0.6828 - val_loss: 0.6732
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.7552 - val_accuracy: 0.6642 - val_loss: 0.8203
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.7659 - val_accuracy: 0.7127 - val_loss: 0.7147
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.7422 - val_accuracy: 0.5112 - val_loss: 0.9761
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6129 - val_accuracy: 0.6493 - val_loss: 1.0530
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6388 - loss: 0.8163 - val_accuracy: 0.7351 - val_loss: 0.6503
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.7690 - val_accuracy: 0.7090 - val_loss: 0.6320
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6661 - loss: 0.7087 - val_accuracy: 0.7313 - val_loss: 0.5804
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6965 - val_accuracy: 0.7351 - val_loss: 0.5769
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7318 - val_accuracy: 0.6978 - val_loss: 0.6405
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7473 - val_accuracy: 0.6978 - val_loss: 0.6668
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6748 - val_accuracy: 0.7313 - val_loss: 0.5944
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.7826 - val_accuracy: 0.6978 - val_loss: 0.7064
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.6928 - val_accuracy: 0.6194 - val_loss: 1.1394
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6449 - val_accuracy: 0.7276 - val_loss: 0.5765
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.7464 - val_accuracy: 0.7351 - val_loss: 0.5724
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6521 - val_accuracy: 0.7201 - val_loss: 0.6529
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6777 - val_accuracy: 0.6978 - val_loss: 0.7111
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.7488 - val_accuracy: 0.6567 - val_loss: 0.9421
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6313 - val_accuracy: 0.6978 - val_loss: 0.6479
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.7009 - val_accuracy: 0.7015 - val_loss: 0.6601
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.7728 - val_accuracy: 0.6493 - val_loss: 1.1048
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.6349 - val_accuracy: 0.7388 - val_loss: 0.5630
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6261 - val_accuracy: 0.6381 - val_loss: 1.4624
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.7264 - val_accuracy: 0.6418 - val_loss: 1.3906
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7289 - val_accuracy: 0.7015 - val_loss: 0.6065
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6758 - loss: 0.6321 - val_accuracy: 0.6306 - val_loss: 1.2852
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.7190 - val_accuracy: 0.6530 - val_loss: 0.8788
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6463 - val_accuracy: 0.5037 - val_loss: 1.0066
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6417 - val_accuracy: 0.7425 - val_loss: 0.5703
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.6930 - val_accuracy: 0.5410 - val_loss: 0.8705
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.6861 - val_accuracy: 0.6418 - val_loss: 1.0966
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.6445 - val_accuracy: 0.7201 - val_loss: 0.5683
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6711 - val_accuracy: 0.6716 - val_loss: 0.7533
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6023 - val_accuracy: 0.7463 - val_loss: 0.5829
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6677 - val_accuracy: 0.7239 - val_loss: 0.6095
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6552 - val_accuracy: 0.6530 - val_loss: 0.9494
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6536 - val_accuracy: 0.7351 - val_loss: 0.5582
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6886 - loss: 0.7338 - val_accuracy: 0.6940 - val_loss: 0.6698
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.6512 - val_accuracy: 0.6530 - val_loss: 0.9968
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5993 - val_accuracy: 0.6978 - val_loss: 0.6494
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7105 - val_accuracy: 0.7164 - val_loss: 0.6184
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.6405 - val_accuracy: 0.7313 - val_loss: 0.6329
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6565 - val_accuracy: 0.6455 - val_loss: 1.2051
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.6479 - val_accuracy: 0.6903 - val_loss: 0.7389
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6723 - val_accuracy: 0.7276 - val_loss: 0.6443
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6008 - val_accuracy: 0.7500 - val_loss: 0.5691
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5577 - val_accuracy: 0.6828 - val_loss: 0.6724
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.6388 - val_accuracy: 0.7313 - val_loss: 0.6263
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6545 - val_accuracy: 0.7239 - val_loss: 0.6290
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6730 - val_accuracy: 0.5112 - val_loss: 1.0654
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6838 - loss: 0.7312 - val_accuracy: 0.6343 - val_loss: 0.7504
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.6628 - val_accuracy: 0.7537 - val_loss: 0.5944
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.5711 - val_accuracy: 0.7164 - val_loss: 0.6164
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.7043 - val_accuracy: 0.7425 - val_loss: 0.5691
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5712 - val_accuracy: 0.7575 - val_loss: 0.5824
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5794 - val_accuracy: 0.7015 - val_loss: 0.7184
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5783 - val_accuracy: 0.5933 - val_loss: 0.7699
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.7939 - val_accuracy: 0.7090 - val_loss: 0.6440
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.6261 - val_accuracy: 0.7276 - val_loss: 0.6155
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6725 - val_accuracy: 0.7388 - val_loss: 0.5700
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6296 - val_accuracy: 0.7537 - val_loss: 0.5800
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4898 - val_accuracy: 0.6418 - val_loss: 1.1265
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.7688 - val_accuracy: 0.7537 - val_loss: 0.5989
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.4970 - val_accuracy: 0.6530 - val_loss: 1.0104
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.6614 - val_accuracy: 0.7761 - val_loss: 0.5710
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.6188 - val_accuracy: 0.6716 - val_loss: 1.0005
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6429 - val_accuracy: 0.6866 - val_loss: 0.7718
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5981 - val_accuracy: 0.6978 - val_loss: 0.6910
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7143 - loss: 0.6524 - val_accuracy: 0.7127 - val_loss: 0.7047
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5825 - val_accuracy: 0.7127 - val_loss: 0.6983
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7223 - loss: 0.5923 - val_accuracy: 0.7948 - val_loss: 0.5675
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5950 - val_accuracy: 0.6978 - val_loss: 0.6555
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.7963 - val_accuracy: 0.7090 - val_loss: 0.7006
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7689 - loss: 0.4861 - val_accuracy: 0.6903 - val_loss: 0.7622
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6492 - val_accuracy: 0.7425 - val_loss: 0.6325
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5720 - val_accuracy: 0.7687 - val_loss: 0.5794
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6897 - val_accuracy: 0.7687 - val_loss: 0.5849
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5281 - val_accuracy: 0.7425 - val_loss: 0.6156
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5981 - val_accuracy: 0.7239 - val_loss: 0.6563
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5647 - val_accuracy: 0.7724 - val_loss: 0.5842
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.6248 - val_accuracy: 0.7724 - val_loss: 0.6119
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5770 - val_accuracy: 0.7239 - val_loss: 0.6761
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4966 - val_accuracy: 0.6828 - val_loss: 0.8161
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.7034 - val_accuracy: 0.7649 - val_loss: 0.5887
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4521 - val_accuracy: 0.7649 - val_loss: 0.5971
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5781 - val_accuracy: 0.5746 - val_loss: 0.8384
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.6964 - val_accuracy: 0.7649 - val_loss: 0.6024
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.5672 - val_accuracy: 0.6642 - val_loss: 0.9986
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.6664 - val_accuracy: 0.7127 - val_loss: 0.7271
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5482 - val_accuracy: 0.7799 - val_loss: 0.6175
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7528 - loss: 0.5568 - val_accuracy: 0.7015 - val_loss: 0.7215
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4900 - val_accuracy: 0.7836 - val_loss: 0.6220
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.6151 - val_accuracy: 0.7127 - val_loss: 0.7539
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6248 - val_accuracy: 0.7873 - val_loss: 0.6114
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5306 - val_accuracy: 0.7612 - val_loss: 0.6489
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6478 - val_accuracy: 0.7164 - val_loss: 0.7939
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7592 - loss: 0.5649 - val_accuracy: 0.7239 - val_loss: 0.7099
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5433 - val_accuracy: 0.5000 - val_loss: 1.3718
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6805 - val_accuracy: 0.6978 - val_loss: 0.7583
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4722 - val_accuracy: 0.7575 - val_loss: 0.6563
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.6014 - val_accuracy: 0.7836 - val_loss: 0.6055
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.6002 - val_accuracy: 0.7649 - val_loss: 0.6569
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7239 - loss: 0.5739 - val_accuracy: 0.7164 - val_loss: 0.7120
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7303 - loss: 0.5737 - val_accuracy: 0.7761 - val_loss: 0.6236
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5235 - val_accuracy: 0.6679 - val_loss: 0.9281
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5951 - val_accuracy: 0.5112 - val_loss: 1.1420
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5545 - val_accuracy: 0.7425 - val_loss: 0.6976
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5433 - val_accuracy: 0.6903 - val_loss: 0.7918
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.6224 - val_accuracy: 0.7761 - val_loss: 0.6106
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4968 - val_accuracy: 0.7500 - val_loss: 0.7096
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.5099 - val_accuracy: 0.7649 - val_loss: 0.6462
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.5557 - val_accuracy: 0.7575 - val_loss: 0.6606
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5841 - val_accuracy: 0.7537 - val_loss: 0.6854
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.5343 - val_accuracy: 0.7761 - val_loss: 0.6495
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.6821 - val_accuracy: 0.7649 - val_loss: 0.6363
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4474 - val_accuracy: 0.6903 - val_loss: 0.8188
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5611 - val_accuracy: 0.7836 - val_loss: 0.6276
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5156 - val_accuracy: 0.5672 - val_loss: 0.9186
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5774 - val_accuracy: 0.7761 - val_loss: 0.6481
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5947 - val_accuracy: 0.6642 - val_loss: 1.0685
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7592 - loss: 0.5725 - val_accuracy: 0.6903 - val_loss: 0.8102
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.6429 - val_accuracy: 0.7537 - val_loss: 0.6983
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8170 - loss: 0.4149 - val_accuracy: 0.7799 - val_loss: 0.6613
Epoch 155/5000

wandb: Agent Starting Run: 0b7d0vb7 with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 16
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5217 - loss: 4.1194 - val_accuracy: 0.6269 - val_loss: 2.5661
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4992 - loss: 2.1704 - val_accuracy: 0.6381 - val_loss: 1.7299
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5345 - loss: 1.3799 - val_accuracy: 0.6530 - val_loss: 1.0802
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5987 - loss: 0.8641 - val_accuracy: 0.5858 - val_loss: 0.7805
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.7262 - val_accuracy: 0.7239 - val_loss: 0.6238
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6790 - loss: 0.6989 - val_accuracy: 0.7351 - val_loss: 0.6089
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.6557 - val_accuracy: 0.6530 - val_loss: 0.6955
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.7030 - val_accuracy: 0.6828 - val_loss: 0.7127
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.7809 - val_accuracy: 0.5037 - val_loss: 0.8506
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6517 - loss: 0.6768 - val_accuracy: 0.6978 - val_loss: 0.6145
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.6283 - val_accuracy: 0.7351 - val_loss: 0.5896
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.5803 - val_accuracy: 0.5448 - val_loss: 0.7318
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6340 - loss: 0.6541 - val_accuracy: 0.6567 - val_loss: 0.7788
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.7094 - val_accuracy: 0.7537 - val_loss: 0.5882
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.6923 - val_accuracy: 0.6530 - val_loss: 0.7702
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6549 - loss: 0.6433 - val_accuracy: 0.5485 - val_loss: 0.7066
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6315 - val_accuracy: 0.6940 - val_loss: 0.5911
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.5667 - val_accuracy: 0.7201 - val_loss: 0.5696
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 0.5533 - val_accuracy: 0.7425 - val_loss: 0.5832
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5611 - val_accuracy: 0.6642 - val_loss: 0.6652
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.6330 - val_accuracy: 0.5037 - val_loss: 0.7784
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.6049 - val_accuracy: 0.7015 - val_loss: 0.5789
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7143 - loss: 0.5405 - val_accuracy: 0.7500 - val_loss: 0.5817
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6998 - loss: 0.5662 - val_accuracy: 0.6642 - val_loss: 0.6323
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.5707 - val_accuracy: 0.7388 - val_loss: 0.5600
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5462 - val_accuracy: 0.7015 - val_loss: 0.5810
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5391 - val_accuracy: 0.6903 - val_loss: 0.6500
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.5547 - val_accuracy: 0.7351 - val_loss: 0.5631
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5375 - val_accuracy: 0.6716 - val_loss: 0.5951
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5328 - val_accuracy: 0.7164 - val_loss: 0.5677
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5264 - val_accuracy: 0.7612 - val_loss: 0.5600
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5380 - val_accuracy: 0.7537 - val_loss: 0.5583
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5255 - val_accuracy: 0.7276 - val_loss: 0.5605
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.5634 - val_accuracy: 0.7724 - val_loss: 0.5931
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5322 - val_accuracy: 0.7649 - val_loss: 0.5595
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.5300 - val_accuracy: 0.7239 - val_loss: 0.5609
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5137 - val_accuracy: 0.7201 - val_loss: 0.5670
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5320 - val_accuracy: 0.7201 - val_loss: 0.5636
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7352 - loss: 0.5335 - val_accuracy: 0.6381 - val_loss: 0.6744
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.5628 - val_accuracy: 0.7873 - val_loss: 0.5631
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5219 - val_accuracy: 0.7799 - val_loss: 0.5773
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.5307 - val_accuracy: 0.7164 - val_loss: 0.5659
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.5467 - val_accuracy: 0.6679 - val_loss: 0.6921
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6413 - val_accuracy: 0.6119 - val_loss: 0.6927
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.7109 - val_accuracy: 0.6791 - val_loss: 0.6911
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5502 - val_accuracy: 0.7724 - val_loss: 0.5476
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5438 - val_accuracy: 0.6903 - val_loss: 0.6051
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7255 - loss: 0.5470 - val_accuracy: 0.6866 - val_loss: 0.6169
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.5740 - val_accuracy: 0.7799 - val_loss: 0.5815
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5502 - val_accuracy: 0.6903 - val_loss: 0.6030
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7063 - loss: 0.5924 - val_accuracy: 0.6791 - val_loss: 0.6399
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5323 - val_accuracy: 0.7575 - val_loss: 0.5474
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.6078 - val_accuracy: 0.6679 - val_loss: 0.7313
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7400 - loss: 0.5600 - val_accuracy: 0.7799 - val_loss: 0.5597
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7464 - loss: 0.5112 - val_accuracy: 0.7201 - val_loss: 0.5522
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5168 - val_accuracy: 0.7239 - val_loss: 0.5494
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7657 - loss: 0.4995 - val_accuracy: 0.7052 - val_loss: 0.5784
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5033 - val_accuracy: 0.7761 - val_loss: 0.5943
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.4970 - val_accuracy: 0.7575 - val_loss: 0.5408
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4753 - val_accuracy: 0.7575 - val_loss: 0.5550
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4851 - val_accuracy: 0.7052 - val_loss: 0.5727
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6076 - val_accuracy: 0.4925 - val_loss: 0.9570
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.6832 - val_accuracy: 0.6642 - val_loss: 0.7687
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7448 - loss: 0.5372 - val_accuracy: 0.5597 - val_loss: 0.7990
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7191 - loss: 0.5582 - val_accuracy: 0.6866 - val_loss: 0.6740
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5429 - val_accuracy: 0.7463 - val_loss: 0.6364
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.4855 - val_accuracy: 0.7090 - val_loss: 0.5669
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4858 - val_accuracy: 0.7761 - val_loss: 0.5848
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5342 - val_accuracy: 0.7015 - val_loss: 0.6268
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5471 - val_accuracy: 0.7761 - val_loss: 0.5415
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7544 - loss: 0.4975 - val_accuracy: 0.7463 - val_loss: 0.5473
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.5219 - val_accuracy: 0.7388 - val_loss: 0.5519
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7817 - loss: 0.4810 - val_accuracy: 0.7201 - val_loss: 0.5581
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.4975 - val_accuracy: 0.7687 - val_loss: 0.5730
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4885 - val_accuracy: 0.7425 - val_loss: 0.5474
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4765 - val_accuracy: 0.7687 - val_loss: 0.5605
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7496 - loss: 0.5180 - val_accuracy: 0.7201 - val_loss: 0.5729
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5046 - val_accuracy: 0.7575 - val_loss: 0.5372
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5083 - val_accuracy: 0.7761 - val_loss: 0.5718
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4716 - val_accuracy: 0.7425 - val_loss: 0.5467
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5120 - val_accuracy: 0.7276 - val_loss: 0.5607
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7335 - loss: 0.5550 - val_accuracy: 0.7761 - val_loss: 0.5982
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.5162 - val_accuracy: 0.7537 - val_loss: 0.5395
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5106 - val_accuracy: 0.7052 - val_loss: 0.6648
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5561 - val_accuracy: 0.7500 - val_loss: 0.5445
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5201 - val_accuracy: 0.7500 - val_loss: 0.5418
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4926 - val_accuracy: 0.7799 - val_loss: 0.5491
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4714 - val_accuracy: 0.7164 - val_loss: 0.5943
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7673 - loss: 0.4948 - val_accuracy: 0.5485 - val_loss: 0.8437
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.6461 - val_accuracy: 0.7090 - val_loss: 0.6829
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7608 - loss: 0.5323 - val_accuracy: 0.7537 - val_loss: 0.5389
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4864 - val_accuracy: 0.7201 - val_loss: 0.5800
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4742 - val_accuracy: 0.7500 - val_loss: 0.5407
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4531 - val_accuracy: 0.7575 - val_loss: 0.5404
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4719 - val_accuracy: 0.7127 - val_loss: 0.5947
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4805 - val_accuracy: 0.7649 - val_loss: 0.6286
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.4913 - val_accuracy: 0.7388 - val_loss: 0.5521
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7384 - loss: 0.5655 - val_accuracy: 0.7761 - val_loss: 0.5396
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7929 - loss: 0.4690 - val_accuracy: 0.7612 - val_loss: 0.5375
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5025 - val_accuracy: 0.7575 - val_loss: 0.5408
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4723 - val_accuracy: 0.7612 - val_loss: 0.5386
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4593 - val_accuracy: 0.7537 - val_loss: 0.5352
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4690 - val_accuracy: 0.7761 - val_loss: 0.5964
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.5083 - val_accuracy: 0.7649 - val_loss: 0.5351
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4566 - val_accuracy: 0.7537 - val_loss: 0.5385
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4586 - val_accuracy: 0.7351 - val_loss: 0.5560
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4664 - val_accuracy: 0.7500 - val_loss: 0.5397
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4837 - val_accuracy: 0.7575 - val_loss: 0.5286
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7737 - loss: 0.5097 - val_accuracy: 0.7612 - val_loss: 0.5320
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4502 - val_accuracy: 0.7612 - val_loss: 0.5392
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4535 - val_accuracy: 0.7612 - val_loss: 0.5471
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4683 - val_accuracy: 0.7575 - val_loss: 0.5377
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4484 - val_accuracy: 0.7761 - val_loss: 0.5747
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5446 - val_accuracy: 0.7164 - val_loss: 0.6776
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5727 - val_accuracy: 0.6940 - val_loss: 0.6798
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.5003 - val_accuracy: 0.7612 - val_loss: 0.5411
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4582 - val_accuracy: 0.7612 - val_loss: 0.5423
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8170 - loss: 0.4418 - val_accuracy: 0.7649 - val_loss: 0.5431
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4704 - val_accuracy: 0.7090 - val_loss: 0.7099
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4870 - val_accuracy: 0.7351 - val_loss: 0.5665
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4578 - val_accuracy: 0.7687 - val_loss: 0.5848
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4554 - val_accuracy: 0.7537 - val_loss: 0.5442
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8122 - loss: 0.4438 - val_accuracy: 0.7799 - val_loss: 0.6008
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4702 - val_accuracy: 0.7612 - val_loss: 0.5471
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4990 - val_accuracy: 0.7425 - val_loss: 0.5710
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7689 - loss: 0.5095 - val_accuracy: 0.7500 - val_loss: 0.5373
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.5098 - val_accuracy: 0.7537 - val_loss: 0.5341
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5013 - val_accuracy: 0.7687 - val_loss: 0.5483
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4640 - val_accuracy: 0.7015 - val_loss: 0.6841
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6049 - val_accuracy: 0.7351 - val_loss: 0.5708
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7416 - loss: 0.5868 - val_accuracy: 0.7127 - val_loss: 0.6965
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4718 - val_accuracy: 0.7164 - val_loss: 0.6705
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7769 - loss: 0.5126 - val_accuracy: 0.7761 - val_loss: 0.5608
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4545 - val_accuracy: 0.7052 - val_loss: 0.6839
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7721 - loss: 0.4957 - val_accuracy: 0.7425 - val_loss: 0.5696
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4419 - val_accuracy: 0.7500 - val_loss: 0.5606
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.4909 - val_accuracy: 0.7575 - val_loss: 0.5432
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7929 - loss: 0.4592 - val_accuracy: 0.7612 - val_loss: 0.5549
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4720 - val_accuracy: 0.7575 - val_loss: 0.5368
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4657 - val_accuracy: 0.5634 - val_loss: 0.8577
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.5911 - val_accuracy: 0.7201 - val_loss: 0.6727
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.5223 - val_accuracy: 0.7761 - val_loss: 0.5927
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4615 - val_accuracy: 0.7052 - val_loss: 0.6911
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7849 - loss: 0.4990 - val_accuracy: 0.7463 - val_loss: 0.5418
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8010 - loss: 0.4462 - val_accuracy: 0.7537 - val_loss: 0.5387
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4363 - val_accuracy: 0.7575 - val_loss: 0.5415
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8026 - loss: 0.4427 - val_accuracy: 0.7612 - val_loss: 0.5357
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4636 - val_accuracy: 0.7276 - val_loss: 0.6238
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7368 - loss: 0.5419 - val_accuracy: 0.7724 - val_loss: 0.5628
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7913 - loss: 0.4722 - val_accuracy: 0.7500 - val_loss: 0.5554
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7640 - loss: 0.5148 - val_accuracy: 0.7799 - val_loss: 0.5766
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5413 - val_accuracy: 0.7463 - val_loss: 0.5627
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4852 - val_accuracy: 0.7537 - val_loss: 0.5342
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4533 - val_accuracy: 0.7612 - val_loss: 0.5361
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: hxdu0qao with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: sgd

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5698 - loss: 46.0728 - val_accuracy: 0.6157 - val_loss: 1.0631
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.7550 - val_accuracy: 0.6157 - val_loss: 0.9528
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.7224 - val_accuracy: 0.6157 - val_loss: 0.8934
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.7061 - val_accuracy: 0.6157 - val_loss: 0.8642
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6945 - val_accuracy: 0.6231 - val_loss: 0.8386
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6843 - val_accuracy: 0.6231 - val_loss: 0.8247
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6808 - val_accuracy: 0.6231 - val_loss: 0.8207
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6790 - val_accuracy: 0.6231 - val_loss: 0.8173
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6774 - val_accuracy: 0.6231 - val_loss: 0.8142
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6758 - val_accuracy: 0.6231 - val_loss: 0.8101
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6745 - val_accuracy: 0.6231 - val_loss: 0.8076
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6733 - val_accuracy: 0.6231 - val_loss: 0.8055
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6723 - val_accuracy: 0.6231 - val_loss: 0.8030
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6116 - loss: 0.6714 - val_accuracy: 0.6231 - val_loss: 0.8011
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6706 - val_accuracy: 0.6231 - val_loss: 0.7997
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6699 - val_accuracy: 0.6269 - val_loss: 0.7975
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6690 - val_accuracy: 0.6269 - val_loss: 0.7956
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6132 - loss: 0.6685 - val_accuracy: 0.6269 - val_loss: 0.7936
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6678 - val_accuracy: 0.6269 - val_loss: 0.7923
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6672 - val_accuracy: 0.6269 - val_loss: 0.7906
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6668 - val_accuracy: 0.6269 - val_loss: 0.7892
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6662 - val_accuracy: 0.6269 - val_loss: 0.7879
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6658 - val_accuracy: 0.6269 - val_loss: 0.7872
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6654 - val_accuracy: 0.6269 - val_loss: 0.7859
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6650 - val_accuracy: 0.6269 - val_loss: 0.7847
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6647 - val_accuracy: 0.6269 - val_loss: 0.7835
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 0.6645 - val_accuracy: 0.6269 - val_loss: 0.7827
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6641 - val_accuracy: 0.6269 - val_loss: 0.7826
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6638 - val_accuracy: 0.6269 - val_loss: 0.7819
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6636 - val_accuracy: 0.6269 - val_loss: 0.7808
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6633 - val_accuracy: 0.6269 - val_loss: 0.7803
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6631 - val_accuracy: 0.6269 - val_loss: 0.7795
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6164 - loss: 0.6629 - val_accuracy: 0.6269 - val_loss: 0.7789
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6627 - val_accuracy: 0.6269 - val_loss: 0.7784
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6625 - val_accuracy: 0.6269 - val_loss: 0.7787
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6624 - val_accuracy: 0.6269 - val_loss: 0.7792
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6623 - val_accuracy: 0.6269 - val_loss: 0.7790
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6164 - loss: 0.6622 - val_accuracy: 0.6269 - val_loss: 0.7777
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6621 - val_accuracy: 0.6269 - val_loss: 0.7781
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.7782
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6619 - val_accuracy: 0.6269 - val_loss: 0.7781
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6617 - val_accuracy: 0.6269 - val_loss: 0.7782
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6616 - val_accuracy: 0.6269 - val_loss: 0.7785
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6615 - val_accuracy: 0.6269 - val_loss: 0.7783
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6614 - val_accuracy: 0.6269 - val_loss: 0.7778
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6180 - loss: 0.6613 - val_accuracy: 0.6306 - val_loss: 0.7782
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6306 - val_loss: 0.7788
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6612 - val_accuracy: 0.6306 - val_loss: 0.7787
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6610 - val_accuracy: 0.6269 - val_loss: 0.7793
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6610 - val_accuracy: 0.6306 - val_loss: 0.7786
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6609 - val_accuracy: 0.6306 - val_loss: 0.7784
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6609 - val_accuracy: 0.6306 - val_loss: 0.7780
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.7784
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.7786
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6180 - loss: 0.6607 - val_accuracy: 0.6306 - val_loss: 0.7787
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6606 - val_accuracy: 0.6306 - val_loss: 0.7789
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6608 - val_accuracy: 0.6306 - val_loss: 0.7785
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6606 - val_accuracy: 0.6306 - val_loss: 0.7779
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6606 - val_accuracy: 0.6306 - val_loss: 0.7778
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6605 - val_accuracy: 0.6306 - val_loss: 0.7768
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6605 - val_accuracy: 0.6306 - val_loss: 0.7774
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6306 - val_loss: 0.7767
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6306 - val_loss: 0.7775
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6306 - val_loss: 0.7778
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6604 - val_accuracy: 0.6306 - val_loss: 0.7770
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6604 - val_accuracy: 0.6306 - val_loss: 0.7764
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6603 - val_accuracy: 0.6306 - val_loss: 0.7767
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6603 - val_accuracy: 0.6306 - val_loss: 0.7764
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6602 - val_accuracy: 0.6306 - val_loss: 0.7761
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6306 - val_loss: 0.7767
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6602 - val_accuracy: 0.6306 - val_loss: 0.7751
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6603 - val_accuracy: 0.6306 - val_loss: 0.7755
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6603 - val_accuracy: 0.6306 - val_loss: 0.7749
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6602 - val_accuracy: 0.6306 - val_loss: 0.7749
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6306 - val_loss: 0.7746
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6306 - val_loss: 0.7753
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6306 - val_loss: 0.7752
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6306 - val_loss: 0.7756
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6601 - val_accuracy: 0.6306 - val_loss: 0.7744
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6306 - val_loss: 0.7735
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6306 - val_loss: 0.7738
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6600 - val_accuracy: 0.6306 - val_loss: 0.7736
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6306 - val_loss: 0.7733
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.7742
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.7739
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.7739
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6306 - val_loss: 0.7723
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6600 - val_accuracy: 0.6269 - val_loss: 0.7731
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.7733
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7727
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7727
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7725
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6599 - val_accuracy: 0.6269 - val_loss: 0.7719
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7720
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7720
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7726
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7726
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7721
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.7717
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.7714
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7711
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7719
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6598 - val_accuracy: 0.6269 - val_loss: 0.7705
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.7705
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.7710
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6269 - val_loss: 0.7708
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7697
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7703
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7702
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7694
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7702
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7699
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6597 - val_accuracy: 0.6231 - val_loss: 0.7703
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7702
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7708
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6180 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7705
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6596 - val_accuracy: 0.6231 - val_loss: 0.7705
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7703
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7704
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7698
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7698
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7703
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7704
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7694
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7697
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7694
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.7697
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6595 - val_accuracy: 0.6194 - val_loss: 0.7692
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.7692
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6157 - val_loss: 0.7693
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6194 - val_loss: 0.7684
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6157 - val_loss: 0.7684
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6594 - val_accuracy: 0.6157 - val_loss: 0.7683
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7686
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7687
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7685
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7684
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7691
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7688
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7686
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7685
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7682
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6593 - val_accuracy: 0.6157 - val_loss: 0.7681
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7685
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7681
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7684
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6592 - val_accuracy: 0.6157 - val_loss: 0.7677
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7678
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6196 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7681
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6180 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7683
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7664
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7674
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6180 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7663
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.6591 - val_accuracy: 0.6157 - val_loss: 0.7678
Epoch 155/5000

wandb: Agent Starting Run: 0jiymffu with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: rmsprop

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3900 - loss: 44.1747 - val_accuracy: 0.3582 - val_loss: 22.0758
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4157 - loss: 9.7164 - val_accuracy: 0.4739 - val_loss: 2.3084
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4735 - loss: 2.3777 - val_accuracy: 0.6269 - val_loss: 2.5106
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5249 - loss: 1.8506 - val_accuracy: 0.3731 - val_loss: 2.8330
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5361 - loss: 1.7574 - val_accuracy: 0.3657 - val_loss: 1.3313
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5024 - loss: 1.3313 - val_accuracy: 0.4963 - val_loss: 0.9542
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5265 - loss: 1.5610 - val_accuracy: 0.4067 - val_loss: 1.7299
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5474 - loss: 1.4094 - val_accuracy: 0.4142 - val_loss: 1.1274
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5474 - loss: 1.3668 - val_accuracy: 0.6642 - val_loss: 0.7844
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6212 - loss: 0.8945 - val_accuracy: 0.4366 - val_loss: 1.1585
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5522 - loss: 1.3911 - val_accuracy: 0.4552 - val_loss: 0.8326
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5714 - loss: 1.1119 - val_accuracy: 0.4925 - val_loss: 0.8095
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.9834 - val_accuracy: 0.7052 - val_loss: 0.6144
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6148 - loss: 1.0456 - val_accuracy: 0.6940 - val_loss: 0.6355
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.9423 - val_accuracy: 0.6007 - val_loss: 0.7295
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6003 - loss: 1.0144 - val_accuracy: 0.4776 - val_loss: 1.0620
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5939 - loss: 1.1277 - val_accuracy: 0.4963 - val_loss: 0.9515
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6324 - loss: 0.8637 - val_accuracy: 0.5261 - val_loss: 0.8305
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5875 - loss: 1.0384 - val_accuracy: 0.6530 - val_loss: 1.1914
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.8881 - val_accuracy: 0.7313 - val_loss: 0.6074
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6404 - loss: 0.8139 - val_accuracy: 0.4366 - val_loss: 1.5501
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.9115 - val_accuracy: 0.6231 - val_loss: 1.5709
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6437 - loss: 0.9004 - val_accuracy: 0.7090 - val_loss: 0.5710
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6485 - loss: 0.7691 - val_accuracy: 0.6381 - val_loss: 1.4371
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6100 - loss: 1.0063 - val_accuracy: 0.6269 - val_loss: 1.5579
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.7830 - val_accuracy: 0.6343 - val_loss: 1.3302
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6196 - loss: 0.9937 - val_accuracy: 0.6530 - val_loss: 0.6769
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6966 - loss: 0.6403 - val_accuracy: 0.4291 - val_loss: 1.4389
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5907 - loss: 1.0780 - val_accuracy: 0.7537 - val_loss: 0.5942
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6276 - loss: 0.9724 - val_accuracy: 0.7201 - val_loss: 0.5531
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6196 - loss: 0.8946 - val_accuracy: 0.7090 - val_loss: 0.5556
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.7421 - val_accuracy: 0.4216 - val_loss: 1.9555
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6067 - loss: 1.1198 - val_accuracy: 0.7388 - val_loss: 0.6384
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.8895 - val_accuracy: 0.6866 - val_loss: 0.6240
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.9120 - val_accuracy: 0.6530 - val_loss: 0.9949
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6565 - loss: 0.8384 - val_accuracy: 0.5970 - val_loss: 0.7140
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6549 - loss: 0.8530 - val_accuracy: 0.5037 - val_loss: 0.8866
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6324 - loss: 0.9434 - val_accuracy: 0.4590 - val_loss: 1.1010
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6051 - loss: 1.0466 - val_accuracy: 0.7500 - val_loss: 0.5587
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.6995 - val_accuracy: 0.7164 - val_loss: 0.5765
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6212 - loss: 0.9613 - val_accuracy: 0.6791 - val_loss: 0.6874
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6340 - loss: 0.9420 - val_accuracy: 0.6306 - val_loss: 1.5818
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6421 - loss: 0.9169 - val_accuracy: 0.6530 - val_loss: 1.0221
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.7379 - val_accuracy: 0.6791 - val_loss: 0.6961
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6308 - loss: 0.9407 - val_accuracy: 0.6418 - val_loss: 1.3494
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.7875 - val_accuracy: 0.7313 - val_loss: 0.5422
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.6584 - val_accuracy: 0.6940 - val_loss: 0.6756
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.8468 - val_accuracy: 0.5746 - val_loss: 0.7379
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.8240 - val_accuracy: 0.6642 - val_loss: 0.8917
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.7740 - val_accuracy: 0.4776 - val_loss: 0.9217
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.9159 - val_accuracy: 0.7425 - val_loss: 0.5354
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6501 - loss: 0.8503 - val_accuracy: 0.6455 - val_loss: 1.1799
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.9281 - val_accuracy: 0.6493 - val_loss: 1.1469
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6709 - loss: 0.8674 - val_accuracy: 0.7313 - val_loss: 0.5333
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.8230 - val_accuracy: 0.7351 - val_loss: 0.5365
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.8387 - val_accuracy: 0.7388 - val_loss: 0.5234
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7111 - loss: 0.6852 - val_accuracy: 0.5000 - val_loss: 0.8789
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.8458 - val_accuracy: 0.7463 - val_loss: 0.5257
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6629 - loss: 0.8718 - val_accuracy: 0.7425 - val_loss: 0.5275
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6244 - loss: 0.9756 - val_accuracy: 0.7537 - val_loss: 0.5272
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6918 - loss: 0.7034 - val_accuracy: 0.6604 - val_loss: 0.8905
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.8551 - val_accuracy: 0.6381 - val_loss: 1.3185
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6982 - loss: 0.7405 - val_accuracy: 0.7649 - val_loss: 0.5685
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6517 - loss: 0.9018 - val_accuracy: 0.6493 - val_loss: 1.1023
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6533 - loss: 0.8884 - val_accuracy: 0.6418 - val_loss: 1.2007
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.8236 - val_accuracy: 0.6642 - val_loss: 0.7972
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.7517 - val_accuracy: 0.7351 - val_loss: 0.5153
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6693 - loss: 0.8094 - val_accuracy: 0.7425 - val_loss: 0.5170
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.7491 - val_accuracy: 0.6604 - val_loss: 0.9143
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7083 - val_accuracy: 0.5261 - val_loss: 0.8196
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6404 - loss: 1.0037 - val_accuracy: 0.6343 - val_loss: 0.6876
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.7989 - val_accuracy: 0.6269 - val_loss: 0.6998
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.8438 - val_accuracy: 0.5261 - val_loss: 0.8145
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6924 - val_accuracy: 0.7388 - val_loss: 0.5269
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6453 - loss: 0.9717 - val_accuracy: 0.4776 - val_loss: 0.9726
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6790 - loss: 0.7764 - val_accuracy: 0.6604 - val_loss: 0.8407
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6677 - loss: 0.8140 - val_accuracy: 0.7687 - val_loss: 0.5243
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6982 - loss: 0.7548 - val_accuracy: 0.6194 - val_loss: 0.7057
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7047 - loss: 0.7046 - val_accuracy: 0.5187 - val_loss: 0.8344
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.8577 - val_accuracy: 0.7425 - val_loss: 0.5232
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.7122 - val_accuracy: 0.4366 - val_loss: 1.3451
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.8386 - val_accuracy: 0.6978 - val_loss: 0.6004
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6613 - loss: 0.8375 - val_accuracy: 0.6604 - val_loss: 0.9648
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6870 - loss: 0.7174 - val_accuracy: 0.7090 - val_loss: 0.5633
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6726 - loss: 0.7972 - val_accuracy: 0.6231 - val_loss: 1.8324
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.7785 - val_accuracy: 0.4776 - val_loss: 1.0347
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6645 - loss: 0.9246 - val_accuracy: 0.7015 - val_loss: 0.6134
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6597 - loss: 0.8729 - val_accuracy: 0.6045 - val_loss: 0.7141
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.7193 - val_accuracy: 0.7575 - val_loss: 0.5067
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.7002 - val_accuracy: 0.6940 - val_loss: 0.6462
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.6974 - val_accuracy: 0.6343 - val_loss: 1.3576
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6709 - loss: 0.7991 - val_accuracy: 0.5187 - val_loss: 0.9513
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.8284 - val_accuracy: 0.6567 - val_loss: 1.0404
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.7232 - val_accuracy: 0.7612 - val_loss: 0.5019
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7014 - loss: 0.7734 - val_accuracy: 0.7239 - val_loss: 0.5567
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6950 - loss: 0.8272 - val_accuracy: 0.7164 - val_loss: 0.5807
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7095 - loss: 0.7550 - val_accuracy: 0.7127 - val_loss: 0.5725
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6870 - loss: 0.7591 - val_accuracy: 0.5522 - val_loss: 0.7874
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7611 - val_accuracy: 0.7836 - val_loss: 0.5114
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6902 - loss: 0.7767 - val_accuracy: 0.7612 - val_loss: 0.5065
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6998 - loss: 0.7297 - val_accuracy: 0.4739 - val_loss: 1.0082
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7368 - loss: 0.6295 - val_accuracy: 0.6604 - val_loss: 0.8737
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.7857 - val_accuracy: 0.6306 - val_loss: 1.3065
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7063 - loss: 0.7196 - val_accuracy: 0.6828 - val_loss: 0.7603
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6806 - loss: 0.7613 - val_accuracy: 0.5933 - val_loss: 0.7422
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6966 - loss: 0.7119 - val_accuracy: 0.6604 - val_loss: 1.0388
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7271 - loss: 0.6512 - val_accuracy: 0.6903 - val_loss: 0.6927
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7089 - val_accuracy: 0.7687 - val_loss: 0.5042
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7063 - loss: 0.7560 - val_accuracy: 0.7724 - val_loss: 0.5025
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6854 - loss: 0.8538 - val_accuracy: 0.7612 - val_loss: 0.5022
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7287 - loss: 0.6749 - val_accuracy: 0.5299 - val_loss: 0.8459
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6838 - loss: 0.8140 - val_accuracy: 0.7090 - val_loss: 0.6167
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7079 - loss: 0.7101 - val_accuracy: 0.6306 - val_loss: 1.4521
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7127 - loss: 0.7579 - val_accuracy: 0.6754 - val_loss: 0.8034
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7319 - loss: 0.6681 - val_accuracy: 0.6530 - val_loss: 1.1041
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6822 - loss: 0.8397 - val_accuracy: 0.7836 - val_loss: 0.5424
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6758 - loss: 0.8063 - val_accuracy: 0.5858 - val_loss: 0.7567
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6712 - val_accuracy: 0.7799 - val_loss: 0.5352
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7303 - loss: 0.6390 - val_accuracy: 0.6791 - val_loss: 0.7555
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7480 - loss: 0.5530 - val_accuracy: 0.6530 - val_loss: 1.0167
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.8199 - val_accuracy: 0.5075 - val_loss: 0.9473
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6934 - loss: 0.8489 - val_accuracy: 0.7649 - val_loss: 0.5031
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.7094 - val_accuracy: 0.6940 - val_loss: 0.6660
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7014 - loss: 0.7136 - val_accuracy: 0.6567 - val_loss: 0.8702
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7624 - loss: 0.5817 - val_accuracy: 0.6493 - val_loss: 1.0540
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.6826 - val_accuracy: 0.7761 - val_loss: 0.5077
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7047 - loss: 0.7912 - val_accuracy: 0.7687 - val_loss: 0.5726
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7223 - loss: 0.6765 - val_accuracy: 0.6604 - val_loss: 1.0525
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7159 - loss: 0.7804 - val_accuracy: 0.7425 - val_loss: 0.5011
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7303 - loss: 0.6740 - val_accuracy: 0.6567 - val_loss: 0.9044
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7030 - loss: 0.7608 - val_accuracy: 0.5336 - val_loss: 0.8636
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7432 - loss: 0.6143 - val_accuracy: 0.6567 - val_loss: 1.0044
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.8494 - val_accuracy: 0.6791 - val_loss: 0.7017
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7239 - loss: 0.6704 - val_accuracy: 0.6567 - val_loss: 0.9393
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.7465 - val_accuracy: 0.7388 - val_loss: 0.5237
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7255 - loss: 0.7177 - val_accuracy: 0.7463 - val_loss: 0.5029
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.7518 - val_accuracy: 0.6940 - val_loss: 0.7186
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7127 - loss: 0.6710 - val_accuracy: 0.6567 - val_loss: 1.0503
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7352 - loss: 0.6959 - val_accuracy: 0.4701 - val_loss: 1.1774
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.7397 - val_accuracy: 0.6604 - val_loss: 0.8866
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7255 - loss: 0.7151 - val_accuracy: 0.7649 - val_loss: 0.5900
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7159 - loss: 0.6533 - val_accuracy: 0.6381 - val_loss: 1.2519
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7239 - loss: 0.7157 - val_accuracy: 0.7537 - val_loss: 0.6078
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6822 - loss: 0.8313 - val_accuracy: 0.7463 - val_loss: 0.5001
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7271 - loss: 0.6298 - val_accuracy: 0.6493 - val_loss: 1.0763
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5862 - val_accuracy: 0.6791 - val_loss: 0.7387
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6758 - loss: 0.8387 - val_accuracy: 0.7388 - val_loss: 0.5422
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7255 - loss: 0.6446 - val_accuracy: 0.7687 - val_loss: 0.5189
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7239 - loss: 0.6886 - val_accuracy: 0.6716 - val_loss: 0.7926
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7111 - loss: 0.7794 - val_accuracy: 0.7537 - val_loss: 0.5016
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7175 - loss: 0.6943 - val_accuracy: 0.7463 - val_loss: 0.5100
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7335 - loss: 0.6724 - val_accuracy: 0.6866 - val_loss: 0.7404
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7608 - loss: 0.5995 - val_accuracy: 0.6791 - val_loss: 0.7338
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6998 - loss: 0.7171 - val_accuracy: 0.6604 - val_loss: 0.9971
Epoch 155/5000

wandb: Agent Starting Run: sf8ircq1 with config:
wandb: 	batch_size: 64
wandb: 	hidden_dense_shape: 24
wandb: 	input_dense_shape: 24
wandb: 	optimizer: adam

Epoch 1/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4623 - loss: 5.5291 - val_accuracy: 0.6157 - val_loss: 2.6906
Epoch 2/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5474 - loss: 2.7352 - val_accuracy: 0.4328 - val_loss: 2.1181
Epoch 3/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5377 - loss: 1.6269 - val_accuracy: 0.4925 - val_loss: 1.3877
Epoch 4/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.5586 - loss: 1.0962 - val_accuracy: 0.5933 - val_loss: 0.7679
Epoch 5/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6276 - loss: 0.8941 - val_accuracy: 0.6828 - val_loss: 0.6985
Epoch 6/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.8218 - val_accuracy: 0.6940 - val_loss: 0.6692
Epoch 7/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6356 - loss: 0.7770 - val_accuracy: 0.6754 - val_loss: 0.6942
Epoch 8/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6421 - loss: 0.7530 - val_accuracy: 0.6791 - val_loss: 0.7057
Epoch 9/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6453 - loss: 0.7181 - val_accuracy: 0.7052 - val_loss: 0.6843
Epoch 10/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6890 - val_accuracy: 0.6866 - val_loss: 0.6762
Epoch 11/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6501 - loss: 0.6637 - val_accuracy: 0.6940 - val_loss: 0.6719
Epoch 12/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6645 - loss: 0.6532 - val_accuracy: 0.6903 - val_loss: 0.6833
Epoch 13/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6677 - loss: 0.6521 - val_accuracy: 0.6940 - val_loss: 0.7111
Epoch 14/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6260 - loss: 0.7261 - val_accuracy: 0.4552 - val_loss: 1.0129
Epoch 15/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6228 - loss: 0.7673 - val_accuracy: 0.6903 - val_loss: 0.7919
Epoch 16/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6661 - loss: 0.6644 - val_accuracy: 0.7463 - val_loss: 0.7015
Epoch 17/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6581 - loss: 0.6526 - val_accuracy: 0.6716 - val_loss: 0.8574
Epoch 18/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6469 - loss: 0.6850 - val_accuracy: 0.7276 - val_loss: 0.6299
Epoch 19/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6902 - loss: 0.5848 - val_accuracy: 0.7313 - val_loss: 0.6323
Epoch 20/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6982 - loss: 0.5841 - val_accuracy: 0.7239 - val_loss: 0.6494
Epoch 21/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6950 - loss: 0.5831 - val_accuracy: 0.7687 - val_loss: 0.6737
Epoch 22/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6886 - loss: 0.6080 - val_accuracy: 0.7388 - val_loss: 0.6282
Epoch 23/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7063 - loss: 0.6137 - val_accuracy: 0.7276 - val_loss: 0.6324
Epoch 24/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7287 - loss: 0.5640 - val_accuracy: 0.6716 - val_loss: 0.7992
Epoch 25/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7030 - loss: 0.5965 - val_accuracy: 0.7724 - val_loss: 0.6324
Epoch 26/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7352 - loss: 0.5583 - val_accuracy: 0.7425 - val_loss: 0.6108
Epoch 27/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7303 - loss: 0.5455 - val_accuracy: 0.7463 - val_loss: 0.6056
Epoch 28/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7207 - loss: 0.5577 - val_accuracy: 0.6716 - val_loss: 0.7579
Epoch 29/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7239 - loss: 0.6105 - val_accuracy: 0.5784 - val_loss: 0.7485
Epoch 30/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5781 - val_accuracy: 0.7201 - val_loss: 0.6056
Epoch 31/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7207 - loss: 0.5437 - val_accuracy: 0.7425 - val_loss: 0.5924
Epoch 32/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7079 - loss: 0.5765 - val_accuracy: 0.6978 - val_loss: 0.6709
Epoch 33/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.5440 - val_accuracy: 0.7388 - val_loss: 0.5902
Epoch 34/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7191 - loss: 0.5453 - val_accuracy: 0.7575 - val_loss: 0.5782
Epoch 35/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7303 - loss: 0.5268 - val_accuracy: 0.7537 - val_loss: 0.5836
Epoch 36/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7255 - loss: 0.5553 - val_accuracy: 0.7388 - val_loss: 0.5834
Epoch 37/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6774 - loss: 0.6205 - val_accuracy: 0.7313 - val_loss: 0.5867
Epoch 38/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6629 - loss: 0.6621 - val_accuracy: 0.7127 - val_loss: 0.6255
Epoch 39/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6934 - loss: 0.5939 - val_accuracy: 0.7948 - val_loss: 0.5960
Epoch 40/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7512 - loss: 0.5179 - val_accuracy: 0.7313 - val_loss: 0.5866
Epoch 41/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.5084 - val_accuracy: 0.7537 - val_loss: 0.5669
Epoch 42/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7319 - loss: 0.5235 - val_accuracy: 0.7500 - val_loss: 0.5608
Epoch 43/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6822 - loss: 0.6421 - val_accuracy: 0.5149 - val_loss: 0.9131
Epoch 44/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7095 - loss: 0.5897 - val_accuracy: 0.7313 - val_loss: 0.5960
Epoch 45/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7448 - loss: 0.5162 - val_accuracy: 0.5485 - val_loss: 0.8045
Epoch 46/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6742 - loss: 0.6527 - val_accuracy: 0.6791 - val_loss: 0.7972
Epoch 47/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.6790 - loss: 0.6551 - val_accuracy: 0.7425 - val_loss: 0.5735
Epoch 48/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7544 - loss: 0.5116 - val_accuracy: 0.7873 - val_loss: 0.5936
Epoch 49/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.5153 - val_accuracy: 0.7500 - val_loss: 0.5593
Epoch 50/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7528 - loss: 0.5320 - val_accuracy: 0.7873 - val_loss: 0.6161
Epoch 51/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7352 - loss: 0.5273 - val_accuracy: 0.7164 - val_loss: 0.6170
Epoch 52/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7576 - loss: 0.5000 - val_accuracy: 0.7649 - val_loss: 0.5524
Epoch 53/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7657 - loss: 0.4915 - val_accuracy: 0.7799 - val_loss: 0.6091
Epoch 54/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.5058 - val_accuracy: 0.7351 - val_loss: 0.5775
Epoch 55/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7608 - loss: 0.4895 - val_accuracy: 0.7910 - val_loss: 0.5839
Epoch 56/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7560 - loss: 0.5236 - val_accuracy: 0.7313 - val_loss: 0.5819
Epoch 57/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7721 - loss: 0.4940 - val_accuracy: 0.7537 - val_loss: 0.6305
Epoch 58/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7640 - loss: 0.5032 - val_accuracy: 0.7500 - val_loss: 0.5413
Epoch 59/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7496 - loss: 0.5057 - val_accuracy: 0.7799 - val_loss: 0.6007
Epoch 60/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7865 - loss: 0.4841 - val_accuracy: 0.7612 - val_loss: 0.5519
Epoch 61/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7673 - loss: 0.5113 - val_accuracy: 0.7761 - val_loss: 0.5496
Epoch 62/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7737 - loss: 0.4833 - val_accuracy: 0.7239 - val_loss: 0.6131
Epoch 63/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7640 - loss: 0.4884 - val_accuracy: 0.7724 - val_loss: 0.5390
Epoch 64/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7640 - loss: 0.5023 - val_accuracy: 0.7575 - val_loss: 0.5407
Epoch 65/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7689 - loss: 0.4936 - val_accuracy: 0.7612 - val_loss: 0.5427
Epoch 66/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7592 - loss: 0.5028 - val_accuracy: 0.7836 - val_loss: 0.5576
Epoch 67/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4690 - val_accuracy: 0.7276 - val_loss: 0.5871
Epoch 68/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7721 - loss: 0.4770 - val_accuracy: 0.7724 - val_loss: 0.5455
Epoch 69/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7464 - loss: 0.5112 - val_accuracy: 0.7463 - val_loss: 0.5917
Epoch 70/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7416 - loss: 0.5469 - val_accuracy: 0.7873 - val_loss: 0.5729
Epoch 71/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7384 - loss: 0.5609 - val_accuracy: 0.7724 - val_loss: 0.5409
Epoch 72/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7319 - loss: 0.5427 - val_accuracy: 0.7910 - val_loss: 0.6178
Epoch 73/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7127 - loss: 0.5840 - val_accuracy: 0.7313 - val_loss: 0.6187
Epoch 74/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4702 - val_accuracy: 0.7537 - val_loss: 0.5352
Epoch 75/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7833 - loss: 0.4768 - val_accuracy: 0.7276 - val_loss: 0.5649
Epoch 76/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7673 - loss: 0.5009 - val_accuracy: 0.7948 - val_loss: 0.6136
Epoch 77/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7705 - loss: 0.4773 - val_accuracy: 0.7612 - val_loss: 0.5415
Epoch 78/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7897 - loss: 0.4658 - val_accuracy: 0.7799 - val_loss: 0.5589
Epoch 79/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7801 - loss: 0.4854 - val_accuracy: 0.7388 - val_loss: 0.5651
Epoch 80/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7640 - loss: 0.5093 - val_accuracy: 0.7687 - val_loss: 0.5332
Epoch 81/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8026 - loss: 0.4588 - val_accuracy: 0.7948 - val_loss: 0.5549
Epoch 82/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7945 - loss: 0.4579 - val_accuracy: 0.7463 - val_loss: 0.5440
Epoch 83/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7929 - loss: 0.4746 - val_accuracy: 0.7985 - val_loss: 0.5963
Epoch 84/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7929 - loss: 0.4660 - val_accuracy: 0.7724 - val_loss: 0.5418
Epoch 85/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7961 - loss: 0.4545 - val_accuracy: 0.7724 - val_loss: 0.5337
Epoch 86/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4518 - val_accuracy: 0.7388 - val_loss: 0.5506
Epoch 87/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7753 - loss: 0.4929 - val_accuracy: 0.7687 - val_loss: 0.5302
Epoch 88/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4912 - val_accuracy: 0.7649 - val_loss: 0.5370
Epoch 89/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7721 - loss: 0.4990 - val_accuracy: 0.7799 - val_loss: 0.5346
Epoch 90/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4591 - val_accuracy: 0.7351 - val_loss: 0.5943
Epoch 91/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7801 - loss: 0.4772 - val_accuracy: 0.7836 - val_loss: 0.6050
Epoch 92/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7576 - loss: 0.5308 - val_accuracy: 0.7351 - val_loss: 0.5819
Epoch 93/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5380 - val_accuracy: 0.7910 - val_loss: 0.5276
Epoch 94/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7785 - loss: 0.4867 - val_accuracy: 0.7761 - val_loss: 0.5372
Epoch 95/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7994 - loss: 0.4467 - val_accuracy: 0.7687 - val_loss: 0.5498
Epoch 96/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8090 - loss: 0.4627 - val_accuracy: 0.7575 - val_loss: 0.5388
Epoch 97/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8042 - loss: 0.4673 - val_accuracy: 0.7910 - val_loss: 0.5999
Epoch 98/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7817 - loss: 0.4741 - val_accuracy: 0.7500 - val_loss: 0.5663
Epoch 99/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7673 - loss: 0.4953 - val_accuracy: 0.7649 - val_loss: 0.5451
Epoch 100/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4738 - val_accuracy: 0.7948 - val_loss: 0.5667
Epoch 101/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.4890 - val_accuracy: 0.7239 - val_loss: 0.6196
Epoch 102/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4743 - val_accuracy: 0.7761 - val_loss: 0.5627
Epoch 103/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7945 - loss: 0.4764 - val_accuracy: 0.7351 - val_loss: 0.5632
Epoch 104/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7705 - loss: 0.5173 - val_accuracy: 0.7948 - val_loss: 0.5818
Epoch 105/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8058 - loss: 0.4689 - val_accuracy: 0.7500 - val_loss: 0.6014
Epoch 106/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7961 - loss: 0.4616 - val_accuracy: 0.7836 - val_loss: 0.5736
Epoch 107/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4779 - val_accuracy: 0.7836 - val_loss: 0.5424
Epoch 108/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7978 - loss: 0.4845 - val_accuracy: 0.7425 - val_loss: 0.6373
Epoch 109/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7865 - loss: 0.5071 - val_accuracy: 0.7910 - val_loss: 0.5507
Epoch 110/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4743 - val_accuracy: 0.7687 - val_loss: 0.5465
Epoch 111/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7849 - loss: 0.4600 - val_accuracy: 0.7351 - val_loss: 0.6027
Epoch 112/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7560 - loss: 0.5458 - val_accuracy: 0.7799 - val_loss: 0.6101
Epoch 113/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7881 - loss: 0.4867 - val_accuracy: 0.7612 - val_loss: 0.5624
Epoch 114/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7833 - loss: 0.5034 - val_accuracy: 0.7724 - val_loss: 0.5383
Epoch 115/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7961 - loss: 0.4611 - val_accuracy: 0.7575 - val_loss: 0.6521
Epoch 116/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7897 - loss: 0.4829 - val_accuracy: 0.7687 - val_loss: 0.5533
Epoch 117/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8074 - loss: 0.4518 - val_accuracy: 0.7687 - val_loss: 0.5358
Epoch 118/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8090 - loss: 0.4419 - val_accuracy: 0.7537 - val_loss: 0.5618
Epoch 119/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8010 - loss: 0.4690 - val_accuracy: 0.7873 - val_loss: 0.5835
Epoch 120/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7978 - loss: 0.4914 - val_accuracy: 0.7313 - val_loss: 0.6977
Epoch 121/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7512 - loss: 0.5637 - val_accuracy: 0.7948 - val_loss: 0.6024
Epoch 122/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7496 - loss: 0.5300 - val_accuracy: 0.7724 - val_loss: 0.5543
Epoch 123/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7785 - loss: 0.5125 - val_accuracy: 0.7687 - val_loss: 0.5450
Epoch 124/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7865 - loss: 0.5181 - val_accuracy: 0.7649 - val_loss: 0.5365
Epoch 125/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8154 - loss: 0.4469 - val_accuracy: 0.7425 - val_loss: 0.5827
Epoch 126/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7817 - loss: 0.5190 - val_accuracy: 0.7724 - val_loss: 0.5361
Epoch 127/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7994 - loss: 0.4803 - val_accuracy: 0.7687 - val_loss: 0.5535
Epoch 128/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7897 - loss: 0.4799 - val_accuracy: 0.7761 - val_loss: 0.5584
Epoch 129/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8042 - loss: 0.4360 - val_accuracy: 0.7575 - val_loss: 0.5337
Epoch 130/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8154 - loss: 0.4376 - val_accuracy: 0.7537 - val_loss: 0.5539
Epoch 131/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.4342 - val_accuracy: 0.7500 - val_loss: 0.5777
Epoch 132/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7961 - loss: 0.4849 - val_accuracy: 0.7537 - val_loss: 0.5515
Epoch 133/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7913 - loss: 0.5249 - val_accuracy: 0.7500 - val_loss: 0.5906
Epoch 134/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8154 - loss: 0.4528 - val_accuracy: 0.7836 - val_loss: 0.5763
Epoch 135/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4376 - val_accuracy: 0.7537 - val_loss: 0.5560
Epoch 136/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8058 - loss: 0.4595 - val_accuracy: 0.7724 - val_loss: 0.5716
Epoch 137/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7833 - loss: 0.4870 - val_accuracy: 0.7836 - val_loss: 0.6440
Epoch 138/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4636 - val_accuracy: 0.7351 - val_loss: 0.6079
Epoch 139/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4522 - val_accuracy: 0.7649 - val_loss: 0.5661
Epoch 140/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4365 - val_accuracy: 0.7649 - val_loss: 0.5445
Epoch 141/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7945 - loss: 0.4730 - val_accuracy: 0.7687 - val_loss: 0.5538
Epoch 142/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8106 - loss: 0.4485 - val_accuracy: 0.7687 - val_loss: 0.5708
Epoch 143/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4436 - val_accuracy: 0.7724 - val_loss: 0.5608
Epoch 144/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8042 - loss: 0.4453 - val_accuracy: 0.7575 - val_loss: 0.5455
Epoch 145/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8058 - loss: 0.4439 - val_accuracy: 0.7612 - val_loss: 0.5641
Epoch 146/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8186 - loss: 0.4583 - val_accuracy: 0.7836 - val_loss: 0.5782
Epoch 147/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8026 - loss: 0.4635 - val_accuracy: 0.7537 - val_loss: 0.5942
Epoch 148/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8106 - loss: 0.4498 - val_accuracy: 0.7649 - val_loss: 0.5542
Epoch 149/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8074 - loss: 0.4505 - val_accuracy: 0.7649 - val_loss: 0.5512
Epoch 150/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.4343 - val_accuracy: 0.7612 - val_loss: 0.5435
Epoch 151/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8234 - loss: 0.4442 - val_accuracy: 0.7649 - val_loss: 0.5609
Epoch 152/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8058 - loss: 0.4433 - val_accuracy: 0.7724 - val_loss: 0.5730
Epoch 153/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.4681 - val_accuracy: 0.7687 - val_loss: 0.5523
Epoch 154/5000
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7817 - loss: 0.5119 - val_accuracy: 0.7575 - val_loss: 0.5420
Epoch 155/5000

wandb: Sweep Agent: Waiting for job.
wandb: Sweep Agent: Exiting.

In [24]:
# グリッドサーチで得た最適なパラメータ値でモデルを作り直す
# （wandbは利用しない）
# テストデータによる予測も行なう
def train_model():
    # モデルの初期化とレイヤー定義
    model = tf.keras.Sequential([
        # 入力層
        tf.keras.Input(shape=(11,)),
        tf.keras.layers.Dense(24, activation='relu'),
        # 隠れ層
        tf.keras.layers.Dense(8, activation='relu'),
        # 出力層
        tf.keras.layers.Dense(1, activation='sigmoid')
    ])

    # モデルの構築
    model.compile(optimizer='rmsprop',
                  loss='binary_crossentropy',
                  metrics=['accuracy'])

    # 学習の実施
    log = model.fit(X_train, Y_train,
                    epochs=5000,
                    batch_size=16,
                    verbose=True,
                    callbacks=[
                        tf.keras.callbacks.EarlyStopping(
                            monitor='val_loss',
                            min_delta=0,
                            patience=100,
                            verbose=1
                        )
                    ],
                    validation_data=(X_valid, Y_valid))

    # テストデータによる予測
    Y_pred_proba = model.predict(X_test)
    Y_pred = (Y_pred_proba > 0.5).astype("int32")

    # Y_predを返す
    return Y_pred

In [25]:
# train_modelを実行する
Y_pred = train_model()
Y_pred

Epoch 1/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3933 - loss: 25.2467 - val_accuracy: 0.3657 - val_loss: 15.9272
Epoch 2/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.3868 - loss: 10.4078 - val_accuracy: 0.3657 - val_loss: 4.7336
Epoch 3/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.4559 - loss: 1.5619 - val_accuracy: 0.4925 - val_loss: 0.8626
Epoch 4/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.5811 - loss: 0.7718 - val_accuracy: 0.5784 - val_loss: 0.7586
Epoch 5/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.6019 - loss: 0.7100 - val_accuracy: 0.6007 - val_loss: 0.7202
Epoch 6/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6132 - loss: 0.6869 - val_accuracy: 0.6007 - val_loss: 0.7126
Epoch 7/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.6164 - loss: 0.6824 - val_accuracy: 0.6045 - val_loss: 0.7178
Epoch 8/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6180 - loss: 0.6789 - val_accuracy: 0.6082 - val_loss: 0.7096
Epoch 9/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6164 - loss: 0.6756 - val_accuracy: 0.6194 - val_loss: 0.7100
Epoch 10/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.6196 - loss: 0.6732 - val_accuracy: 0.6194 - val_loss: 0.7132
Epoch 11/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.6180 - loss: 0.6715 - val_accuracy: 0.6194 - val_loss: 0.7127
Epoch 12/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6196 - loss: 0.6696 - val_accuracy: 0.6194 - val_loss: 0.7131
Epoch 13/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.6196 - loss: 0.6678 - val_accuracy: 0.6194 - val_loss: 0.7136
Epoch 14/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 913us/step - accuracy: 0.6180 - loss: 0.6679 - val_accuracy: 0.6194 - val_loss: 0.7171
Epoch 15/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6228 - loss: 0.6664 - val_accuracy: 0.6194 - val_loss: 0.7178
Epoch 16/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.6244 - loss: 0.6656 - val_accuracy: 0.6194 - val_loss: 0.7159
Epoch 17/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6653 - val_accuracy: 0.6194 - val_loss: 0.7268
Epoch 18/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6212 - loss: 0.6643 - val_accuracy: 0.6194 - val_loss: 0.7279
Epoch 19/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.6212 - loss: 0.6640 - val_accuracy: 0.6194 - val_loss: 0.7350
Epoch 20/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 929us/step - accuracy: 0.6228 - loss: 0.6628 - val_accuracy: 0.6157 - val_loss: 0.7263
Epoch 21/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 959us/step - accuracy: 0.6260 - loss: 0.6630 - val_accuracy: 0.6157 - val_loss: 0.7211
Epoch 22/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.6228 - loss: 0.6626 - val_accuracy: 0.6194 - val_loss: 0.7329
Epoch 23/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6260 - loss: 0.6618 - val_accuracy: 0.6194 - val_loss: 0.7313
Epoch 24/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.6260 - loss: 0.6647 - val_accuracy: 0.6157 - val_loss: 0.7330
Epoch 25/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 944us/step - accuracy: 0.6244 - loss: 0.6659 - val_accuracy: 0.6157 - val_loss: 0.7337
Epoch 26/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6244 - loss: 0.6609 - val_accuracy: 0.6157 - val_loss: 0.7364
Epoch 27/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.6244 - loss: 0.6607 - val_accuracy: 0.6157 - val_loss: 0.7432
Epoch 28/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.6260 - loss: 0.6601 - val_accuracy: 0.6194 - val_loss: 0.7416
Epoch 29/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.6260 - loss: 0.6601 - val_accuracy: 0.6119 - val_loss: 0.7341
Epoch 30/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.6260 - loss: 0.6599 - val_accuracy: 0.6194 - val_loss: 0.7419
Epoch 31/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6260 - loss: 0.6594 - val_accuracy: 0.6231 - val_loss: 0.7426
Epoch 32/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.6292 - loss: 0.6595 - val_accuracy: 0.6231 - val_loss: 0.7459
Epoch 33/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6260 - loss: 0.6586 - val_accuracy: 0.6231 - val_loss: 0.7382
Epoch 34/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6260 - loss: 0.6589 - val_accuracy: 0.6194 - val_loss: 0.7429
Epoch 35/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.6276 - loss: 0.6593 - val_accuracy: 0.6194 - val_loss: 0.7357
Epoch 36/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.6276 - loss: 0.6577 - val_accuracy: 0.6194 - val_loss: 0.7386
Epoch 37/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.6260 - loss: 0.6584 - val_accuracy: 0.6194 - val_loss: 0.7419
Epoch 38/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 928us/step - accuracy: 0.6276 - loss: 0.6570 - val_accuracy: 0.6157 - val_loss: 0.7354
Epoch 39/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6308 - loss: 0.6613 - val_accuracy: 0.6157 - val_loss: 0.7356
Epoch 40/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.6292 - loss: 0.6569 - val_accuracy: 0.6194 - val_loss: 0.7347
Epoch 41/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.6260 - loss: 0.6576 - val_accuracy: 0.6194 - val_loss: 0.7412
Epoch 42/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.6276 - loss: 0.6566 - val_accuracy: 0.6194 - val_loss: 0.7434
Epoch 43/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step - accuracy: 0.6276 - loss: 0.6639 - val_accuracy: 0.6157 - val_loss: 0.7471
Epoch 44/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - accuracy: 0.6324 - loss: 0.6560 - val_accuracy: 0.6194 - val_loss: 0.7560
Epoch 45/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.6292 - loss: 0.6556 - val_accuracy: 0.6194 - val_loss: 0.7498
Epoch 46/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6308 - loss: 0.6550 - val_accuracy: 0.6194 - val_loss: 0.7527
Epoch 47/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.6276 - loss: 0.6566 - val_accuracy: 0.6194 - val_loss: 0.7454
Epoch 48/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.6292 - loss: 0.6550 - val_accuracy: 0.6194 - val_loss: 0.7566
Epoch 49/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.6308 - loss: 0.6549 - val_accuracy: 0.6231 - val_loss: 0.7515
Epoch 50/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6260 - loss: 0.6560 - val_accuracy: 0.6194 - val_loss: 0.7463
Epoch 51/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.6324 - loss: 0.6540 - val_accuracy: 0.6231 - val_loss: 0.7609
Epoch 52/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.6292 - loss: 0.6541 - val_accuracy: 0.6231 - val_loss: 0.7620
Epoch 53/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6276 - loss: 0.6540 - val_accuracy: 0.6157 - val_loss: 0.7611
Epoch 54/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6292 - loss: 0.6570 - val_accuracy: 0.6119 - val_loss: 0.7441
Epoch 55/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6308 - loss: 0.6530 - val_accuracy: 0.6194 - val_loss: 0.7565
Epoch 56/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.6308 - loss: 0.6524 - val_accuracy: 0.6119 - val_loss: 0.7537
Epoch 57/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 880us/step - accuracy: 0.6308 - loss: 0.6562 - val_accuracy: 0.6119 - val_loss: 0.7492
Epoch 58/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.6308 - loss: 0.6523 - val_accuracy: 0.6119 - val_loss: 0.7635
Epoch 59/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.6340 - loss: 0.6521 - val_accuracy: 0.6119 - val_loss: 0.7689
Epoch 60/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.6292 - loss: 0.6562 - val_accuracy: 0.6119 - val_loss: 0.7519
Epoch 61/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.6340 - loss: 0.6501 - val_accuracy: 0.6194 - val_loss: 0.7708
Epoch 62/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6356 - loss: 0.6513 - val_accuracy: 0.6119 - val_loss: 0.7597
Epoch 63/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.6324 - loss: 0.6514 - val_accuracy: 0.6194 - val_loss: 0.7559
Epoch 64/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6340 - loss: 0.6490 - val_accuracy: 0.6119 - val_loss: 0.7666
Epoch 65/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.6356 - loss: 0.6502 - val_accuracy: 0.6157 - val_loss: 0.7515
Epoch 66/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 872us/step - accuracy: 0.6404 - loss: 0.6502 - val_accuracy: 0.6119 - val_loss: 0.7606
Epoch 67/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.6356 - loss: 0.6484 - val_accuracy: 0.6194 - val_loss: 0.7726
Epoch 68/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.6388 - loss: 0.6532 - val_accuracy: 0.6157 - val_loss: 0.7598
Epoch 69/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.6388 - loss: 0.6477 - val_accuracy: 0.6157 - val_loss: 0.7628
Epoch 70/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6356 - loss: 0.6490 - val_accuracy: 0.6157 - val_loss: 0.7803
Epoch 71/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.6308 - loss: 0.6493 - val_accuracy: 0.6194 - val_loss: 0.7627
Epoch 72/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.6340 - loss: 0.6472 - val_accuracy: 0.6194 - val_loss: 0.7768
Epoch 73/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.6276 - loss: 0.6543 - val_accuracy: 0.6194 - val_loss: 0.7743
Epoch 74/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.6356 - loss: 0.6476 - val_accuracy: 0.6194 - val_loss: 0.7692
Epoch 75/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6324 - loss: 0.6481 - val_accuracy: 0.6157 - val_loss: 0.7665
Epoch 76/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.6388 - loss: 0.6442 - val_accuracy: 0.6194 - val_loss: 0.7793
Epoch 77/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.6372 - loss: 0.6440 - val_accuracy: 0.6194 - val_loss: 0.8013
Epoch 78/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.6388 - loss: 0.6483 - val_accuracy: 0.6716 - val_loss: 0.7678
Epoch 79/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.6886 - loss: 0.6205 - val_accuracy: 0.6866 - val_loss: 0.7589
Epoch 80/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.6870 - loss: 0.6083 - val_accuracy: 0.7015 - val_loss: 0.7450
Epoch 81/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7207 - loss: 0.5970 - val_accuracy: 0.6903 - val_loss: 0.7482
Epoch 82/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7014 - loss: 0.6050 - val_accuracy: 0.6903 - val_loss: 0.7343
Epoch 83/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7095 - loss: 0.5935 - val_accuracy: 0.7052 - val_loss: 0.7213
Epoch 84/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7127 - loss: 0.5915 - val_accuracy: 0.6866 - val_loss: 0.7371
Epoch 85/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.7079 - loss: 0.5894 - val_accuracy: 0.6978 - val_loss: 0.7259
Epoch 86/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7127 - loss: 0.5875 - val_accuracy: 0.6940 - val_loss: 0.7410
Epoch 87/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.7047 - loss: 0.5854 - val_accuracy: 0.7127 - val_loss: 0.7188
Epoch 88/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.7207 - loss: 0.5798 - val_accuracy: 0.6866 - val_loss: 0.7568
Epoch 89/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7239 - loss: 0.5813 - val_accuracy: 0.6940 - val_loss: 0.7303
Epoch 90/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.7287 - loss: 0.5720 - val_accuracy: 0.7052 - val_loss: 0.7302
Epoch 91/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.7432 - loss: 0.5694 - val_accuracy: 0.6940 - val_loss: 0.7579
Epoch 92/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.7191 - loss: 0.5756 - val_accuracy: 0.6828 - val_loss: 0.7469
Epoch 93/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7352 - loss: 0.5669 - val_accuracy: 0.6828 - val_loss: 0.7707
Epoch 94/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7239 - loss: 0.5664 - val_accuracy: 0.6866 - val_loss: 0.7488
Epoch 95/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7271 - loss: 0.5669 - val_accuracy: 0.7164 - val_loss: 0.7124
Epoch 96/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7207 - loss: 0.5561 - val_accuracy: 0.6791 - val_loss: 0.7692
Epoch 97/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.7319 - loss: 0.5645 - val_accuracy: 0.7201 - val_loss: 0.7047
Epoch 98/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7271 - loss: 0.5621 - val_accuracy: 0.7015 - val_loss: 0.7299
Epoch 99/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7448 - loss: 0.5485 - val_accuracy: 0.6903 - val_loss: 0.7572
Epoch 100/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.7271 - loss: 0.5540 - val_accuracy: 0.7052 - val_loss: 0.7325
Epoch 101/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.7352 - loss: 0.5489 - val_accuracy: 0.7164 - val_loss: 0.7135
Epoch 102/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7448 - loss: 0.5441 - val_accuracy: 0.7537 - val_loss: 0.7043
Epoch 103/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7544 - loss: 0.5386 - val_accuracy: 0.7537 - val_loss: 0.7057
Epoch 104/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.7400 - loss: 0.5390 - val_accuracy: 0.7239 - val_loss: 0.7256
Epoch 105/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.7640 - loss: 0.5314 - val_accuracy: 0.6903 - val_loss: 0.7572
Epoch 106/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.7175 - loss: 0.5457 - val_accuracy: 0.6530 - val_loss: 0.7864
Epoch 107/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.7576 - loss: 0.5313 - val_accuracy: 0.7351 - val_loss: 0.7263
Epoch 108/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.7432 - loss: 0.5336 - val_accuracy: 0.7090 - val_loss: 0.7621
Epoch 109/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7400 - loss: 0.5336 - val_accuracy: 0.7276 - val_loss: 0.7017
Epoch 110/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.7640 - loss: 0.5195 - val_accuracy: 0.7388 - val_loss: 0.7147
Epoch 111/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 936us/step - accuracy: 0.7496 - loss: 0.5302 - val_accuracy: 0.7425 - val_loss: 0.7108
Epoch 112/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.7624 - loss: 0.5171 - val_accuracy: 0.6642 - val_loss: 0.7901
Epoch 113/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 925us/step - accuracy: 0.7464 - loss: 0.5226 - val_accuracy: 0.7388 - val_loss: 0.7259
Epoch 114/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.7689 - loss: 0.5084 - val_accuracy: 0.7537 - val_loss: 0.7007
Epoch 115/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.7624 - loss: 0.5195 - val_accuracy: 0.7052 - val_loss: 0.7574
Epoch 116/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7560 - loss: 0.5123 - val_accuracy: 0.7425 - val_loss: 0.7341
Epoch 117/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7833 - loss: 0.5054 - val_accuracy: 0.7537 - val_loss: 0.7125
Epoch 118/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.7705 - loss: 0.5148 - val_accuracy: 0.7612 - val_loss: 0.7113
Epoch 119/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7721 - loss: 0.5055 - val_accuracy: 0.7425 - val_loss: 0.7379
Epoch 120/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.7769 - loss: 0.5169 - val_accuracy: 0.7201 - val_loss: 0.7378
Epoch 121/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.7737 - loss: 0.5142 - val_accuracy: 0.7351 - val_loss: 0.7346
Epoch 122/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.7849 - loss: 0.5005 - val_accuracy: 0.7575 - val_loss: 0.6967
Epoch 123/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.7929 - loss: 0.5002 - val_accuracy: 0.7612 - val_loss: 0.7021
Epoch 124/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7849 - loss: 0.4937 - val_accuracy: 0.6455 - val_loss: 0.8527
Epoch 125/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7833 - loss: 0.4982 - val_accuracy: 0.7649 - val_loss: 0.7029
Epoch 126/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 850us/step - accuracy: 0.7897 - loss: 0.5050 - val_accuracy: 0.7463 - val_loss: 0.7404
Epoch 127/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.7945 - loss: 0.5000 - val_accuracy: 0.7500 - val_loss: 0.7026
Epoch 128/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.7849 - loss: 0.5011 - val_accuracy: 0.7425 - val_loss: 0.7073
Epoch 129/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.7801 - loss: 0.4965 - val_accuracy: 0.7463 - val_loss: 0.7416
Epoch 130/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7929 - loss: 0.4956 - val_accuracy: 0.6978 - val_loss: 0.7566
Epoch 131/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7801 - loss: 0.4913 - val_accuracy: 0.7761 - val_loss: 0.7359
Epoch 132/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.7865 - loss: 0.4951 - val_accuracy: 0.7724 - val_loss: 0.6959
Epoch 133/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 876us/step - accuracy: 0.7817 - loss: 0.4947 - val_accuracy: 0.7761 - val_loss: 0.7240
Epoch 134/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7801 - loss: 0.5065 - val_accuracy: 0.7612 - val_loss: 0.6852
Epoch 135/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7881 - loss: 0.4942 - val_accuracy: 0.7761 - val_loss: 0.7035
Epoch 136/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.7978 - loss: 0.4822 - val_accuracy: 0.7612 - val_loss: 0.7092
Epoch 137/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.7994 - loss: 0.4840 - val_accuracy: 0.7313 - val_loss: 0.7335
Epoch 138/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.7865 - loss: 0.4903 - val_accuracy: 0.7724 - val_loss: 0.7290
Epoch 139/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.7865 - loss: 0.4952 - val_accuracy: 0.7761 - val_loss: 0.6910
Epoch 140/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.7897 - loss: 0.4813 - val_accuracy: 0.7687 - val_loss: 0.6949
Epoch 141/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 863us/step - accuracy: 0.7961 - loss: 0.4955 - val_accuracy: 0.7687 - val_loss: 0.6991
Epoch 142/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 885us/step - accuracy: 0.7913 - loss: 0.4820 - val_accuracy: 0.7612 - val_loss: 0.7120
Epoch 143/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.7978 - loss: 0.4742 - val_accuracy: 0.7537 - val_loss: 0.7303
Epoch 144/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7961 - loss: 0.4855 - val_accuracy: 0.7463 - val_loss: 0.7382
Epoch 145/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.7913 - loss: 0.4977 - val_accuracy: 0.7537 - val_loss: 0.7296
Epoch 146/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.7945 - loss: 0.4796 - val_accuracy: 0.7724 - val_loss: 0.6905
Epoch 147/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 884us/step - accuracy: 0.7945 - loss: 0.4791 - val_accuracy: 0.7799 - val_loss: 0.6986
Epoch 148/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.7881 - loss: 0.4803 - val_accuracy: 0.7687 - val_loss: 0.7551
Epoch 149/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.7897 - loss: 0.4894 - val_accuracy: 0.7724 - val_loss: 0.6741
Epoch 150/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7929 - loss: 0.4777 - val_accuracy: 0.7575 - val_loss: 0.7198
Epoch 151/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - accuracy: 0.8138 - loss: 0.4635 - val_accuracy: 0.7649 - val_loss: 0.7082
Epoch 152/5000
39/39 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.7849 - loss: 0.4866 - val_accuracy: 0.7575 - val_loss: 0.7112
Epoch 153/5000

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

In [26]:
# X_testをDataFrameに戻し、X_test2に格納
X_test2 = pd.DataFrame(X_test, columns=test2.columns)

In [27]:
# Kaggleへ提出するためのデータが入ったDataFrameを作成
submission_data = pd.DataFrame()
submission_data["PassengerId"] = X_test2["PassengerId"].astype("int32")
submission_data["Survived"] = Y_pred
submission_data

     PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         0
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [28]:
# Kaggleに提出するためのCSVファイルを作成
submission_data.to_csv("my_submission_titanic.csv", index=False)